### ISSUE TITLE
YouTrack sink

### ISSUE THREAD

**Issue by jokokko** [serilog/serilog#1001]
Hello,

I created a sink for YouTrack. If you want to list it under sinks in Wiki: Package https://www.nuget.org/packages/serilog.sinks.youtrack, repo https://github.com/jokokko/serilog-sinks-youtrack, NuGet badge https://img.shields.io/nuget/v/serilog.sinks.youtrack.svg?style=flat, WriteTo YouTrack.

**Comment by merbla** [comment]
Hi @jokokko,
Added over at https://github.com/serilog/serilog/wiki/Provided-Sinks
