### ISSUE TITLE
Levelled `ForContext()`

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1002]
`ForContext()` is widely-used to add properties to events independently of the message template.

This has some allocation overhead when logging is switched off, since `ForContext()` will allocate a few objects such as the return value and a property enricher.

The overhead can be avoided today by checking `IsEnabled()` and only conditionally adding properties when the level is known to be "on", but, it's quite clunky to do it.

An extension method like the one below would make it easier to add properties conditionally:

```csharp
static ILogger ForContext<TValue>(
    this ILogger logger,
    LogEventLevel level,
    string name, 
    TValue value,
    bool destructureObjects = false)
{
    if (!logger.IsEnabled(level))
        return logger;

    return logger.ForContext(name, value, destructureObjects);
}
```

Usage:

```csharp
log.ForContext(LogEventLevel.Debug, "OrderId", order.Id)
    .Information("Here is an event that may or may not be enriched");
```

Is it worth shipping this in Serilog somewhere?

**Comment by Jaben** [comment]
I like this idea. 👍 
Would be useful for larger object structures in dev vs production environments.

**Comment by pardahlman** [comment]
Hello - hi! I gave this a try. PR submitted 👍
