### ISSUE TITLE
Rolling File Sink: Avoid having the file opened and locked

### ISSUE THREAD

**Issue by emzero** [serilog/serilog#1005]
I noticed when creating a logger with a rolling file, the file gets locked by the process. 

Is it possible to open it only when logging and then closing it? Or is it this way because of performance reasons?

**Comment by nblumhardt** [comment]
Hi @emzero - have you tried passing the `shared: true` flag?

(Yes, perf is a big driver behind this.)

**Comment by emzero** [comment]
@nblumhardt Yes, I tried that flag but the file gets locked by the process anyway.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; :+1: this will be because the file remains open.

Its possible to create a simple wrapper sink that opens and closes the file on each write, but I can imagine it being rather slow. How does this impact you?

Cheers!

**Comment by emzero** [comment]
And couldn't this wrapper make use of async logging? Which shouldn't impact the performance of the application itself, right?

**Comment by nblumhardt** [comment]
Yes, definitely 👍 (up to a point, of course :-))

**Comment by nblumhardt** [comment]
@emzero closing this for now, but please keep us posted with your progress :-)

**Comment by sbryfcz** [comment]
Any more thoughts on this one? I have a use case where I'm using Serilog as middleware for a .netcore 2 API. And I have a need to expose an endpoint to fetch the logs. But since there is a lock on the most recent rolling file, I cant read the file to return it to the user. Has anyone used Serilog in this manner? Maybe there is a better approach for fetching logs on a server?

**Comment by nblumhardt** [comment]
This has now been implemented - pass `shared: true` when constructing the sink.

(Using a log server to collect logs is usually much more enjoyable than collecting files, though :-))

**Comment by nblumhardt** [comment]
Ah, sorry - I see there's already mention of `shared: true` in the thread. The file will still be kept open by the sink when this flag is specified, but it will allow other processes to read and write to the file while open. HTH!

**Comment by sbryfcz** [comment]
I'll take a look again at it. I guess I was probably trying to access the file from the same process. Also, I was looking through the source code a bit. I don't think the shared setting is used if you are using a rolling file sink. But maybe I am mistaken.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @sbryfcz. The `shared` setting is propagated here: https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/RollingFileSink.cs#L152

Good luck with it,
NB

**Comment by CADbloke** [comment]
Here's an edge case for you - of you use a static `Log` property in the App.cs class that is built in a call from the constructor, the Visual Studio 2017 xaml editor builds that class and locks the log file. I moved my call to the Serilog builder in `App.Initialize()`.

Note: I use an individual static logger for AutoCAD plugins so each plugin has its own logger.  See https://stackoverflow.com/questions/46900488/serilog-logger-for-each-plugin-dll-in-one-application
