### ISSUE TITLE
`LogContext.Reset()`

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1006]
When kicking off some background work, for example with:

```csharp
Task.Run(() => { ... });
```

it's not always desirable for contextual state from the parent task to flow to the child.

Either we could do:

```csharp
Task.Run(() =>
{
    LogContext.Reset();
    // ...
});
```

Or:

```csharp
using (LogContext.Suspend())
{
    Task.Run(() => { ... });
}
```

either of which would allow the task body to run with a "clean" log context. (We may wish to provide both, for the sake of flexibility, as despite appearances, `Suspend` can't be emulated in terms of `Reset` and `Clone`.)

**Comment by mariozski** [comment]
Hi @nblumhardt, I will help with this one, but I need few days for that probably, depending on free time. Just to clarify, you want .Reset() to clear context fully and .Suspend() to clear it for the code running inside using block and then restore it? If you would have any other tips, let me know.

**Comment by nblumhardt** [comment]
Awesome, thanks for the offer, @mariozski.

Yes, that's the idea, I think. `Suspend()` can return a `ContextStackBookmark`, so should be fairly straightforward (I think we actually even supported this method back in Serilog 1.x).

Let us know if you need any more info 👍

**Comment by nblumhardt** [comment]
Added in #1007.
