### ISSUE TITLE
Can't get Filter.ByExcluding(Matching.FromSource("some.ns") to work

### ISSUE THREAD

**Issue by neilwashere** [serilog/serilog#1010]
I've seen a couple of issues raised for this but the suggested solutions do not have any effect for me.

I'm using netcore ASP MVC and where I can I use ILogger<T> for dependency injection.

I'm using the Serilog.Extensions.Logging package with FromLogContext enrichment and all of my messages include a "SourceContext" field with the correct NS.

setup is roughly:

```csharp
var namespaces = new[] {"Microsoft", "IdentityServer4"}; // I have a *lot* of these

var loggerConfig =  new LoggerConfiguration()
.MinimumLevel.Information()
.Enrich.FromLogContext();
// sink attachments elided

foreach (var ns in namespaces)
{
    loggerConfig.Filter.ByExcluding(Matching.FromSource(ns))
}

var logger = loggerConfig.CreateLogger(); // using `ForContext<MyClass>` seems to have no effect

var host = new WebHostBuilder()
//other setup elided
.ConfigureLogging(logging =>
{
    logging.AddSerilog(logger);
})
```
example log (with some redactions) I would have expected to be filtered out:
```json
{
    "time":"2017-08-10T08:53:23.6891580+01:00",
    "SourceContext":"IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware",
    "RequestId":"test",
    "RequestPath":"/some/path"
}
```
Even if I use the full namespace in the filter I still see a log entry.
If it makes any difference I use a custom formatter which does quite a lot of things but touch the SourceContext it does not.

Any thoughts?

**Comment by nblumhardt** [comment]
Hi Neil - thanks for getting in touch. Nothing immediately comes to mind. Any chance of baking it down into a minimal repro?

Cheers,
Nick

**Comment by neilwashere** [comment]
Hi @nblumhardt - thanks for taking a look. I was hoping something silly would scream at someone. I'll try to debug a little more and see if I can incrementally factor out any bad actors. If I find it I'll update the issue. If I can't I'll try to get a minimal repo with the behavior for you.

Cheers!
n

**Comment by vlm---** [comment]
You should retain configuration with added filter like this:
`loggerConfig = loggerConfig.Filter.ByExcluding(Matching.FromSource(ns));`

**Comment by neilwashere** [comment]
That was it @vlm--- I'm a little surprised by this. I use a bunch of extension methods to setup various sinks and they are all happy mutating the config. I would have spent hours on this - thank you!

**Comment by nblumhardt** [comment]
Glad you were able to get it working, @neilwashere - and thanks for the help @vlm--- !

I suspect there was something else going on in the code; as with all of the `LoggerConfiguration` methods, the return value is always the same `LoggerConfiguration` object that you started with, so chaining either way should be equivalent.

https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerFilterConfiguration.cs#L55
