### ISSUE TITLE
[Enhancement] Configurable PropertyValueConverter MaximumStringLength (Truncate Properties)

### ISSUE THREAD

**Issue by ckarcz** [serilog/serilog#1012]
This would be great. For dynamic run time properties we log (like http message), can be extremely large and fill up Elastic buffers and log file size fast.

Being able to configure a global max property size field fluently and in app.config/app.json would be most excellent :+1:

**Comment by nblumhardt** [comment]
Hi Chris,

Does `Destructure.ToMaximumStringLength()` cover what you're looking for here?

Cheers,
Nick

**Comment by nblumhardt** [comment]
@ckarcz assuming `ToMaximumStringLength()` is what you were after, let me know if you need further info.
