### ISSUE TITLE
TestCorrelator Sink

### ISSUE THREAD

**Issue by MitchBodmer** [serilog/serilog#1013]
I noticed you starred my little unit testing project! I've refactored it into a sink, which I think works a bit better. You're more than welcome to add it to the list of sinks if you think it might be useful.

https://github.com/Microsoft/serilog-sinks-testcorrelator
https://www.nuget.org/packages/Serilog.Sinks.TestCorrelator

Cheers!

**Comment by merbla** [comment]
Added to the [wiki page](https://github.com/serilog/serilog/wiki/Provided-Sinks).

**Comment by merbla** [comment]
👍
