### ISSUE TITLE
Serilog doesn't write on SQL Server

### ISSUE THREAD

**Issue by el1jaC** [serilog/serilog#1017]
I've installed Serilog version 2.5.0 in my ASP.NET MVC project from nuget package manager, with two sinks:

RollingFile version 3.3.0
MSSqlServer version 5.0.0
Logging on file is ok, but doesn't work on Sql Server, and no error or exception is raised. 

I also tried to downgrade Sql Server sink version to 4.2.0 and 4.0.0, but nothing is changed.

To configure logging on db i followed the tutorial on [github page project](https://github.com/serilog/serilog-sinks-mssqlserver).

Can you help me pls?

Thanks in advance!

**Comment by merbla** [comment]
Hi @el1jaC,

Two questions.

* Firstly what target framework are you using?
* Secondly, this issue can be moved over to the [SQL Server Sink](https://github.com/serilog/serilog-sinks-mssqlserver/issues) as this repo is for the core Serilog functionality.

**Comment by el1jaC** [comment]
Hi @merbla,

- .NET framework 4.5.2
- I don't know how can i move this issue :(

Thanks a lot.

**Comment by merbla** [comment]
Hi @el1jaC,
I just recreated over on the other repo.  Please see https://github.com/serilog/serilog-sinks-mssqlserver/issues/92

**Comment by el1jaC** [comment]
Thanks you @merbla :)
