### ISSUE TITLE
New sink for Google Cloud Logging

### ISSUE THREAD

**Issue by manigandham** [serilog/serilog#1022]
Created new sink for [Google Cloud Platform Stackdriver Logging](https://cloud.google.com/logging/)

Repo: https://github.com/manigandham/serilog-sinks-googlecloudlogging

Nuget: https://www.nuget.org/packages/Serilog.Sinks.GoogleCloudLogging/

Please let me know if you need anything else, thanks.

**Comment by merbla** [comment]
Thanks @manigandham, I have added to the list of [sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks).
