### ISSUE TITLE
Adding an Azure Event Grid sink to the Serilog Org

### ISSUE THREAD

**Issue by sirkirby** [serilog/serilog#1023]
I've developed a new sink which allows you to send your log events to an Azure Event Grid custom topic. Since there is no official SDK for event grid and the fact that using Event Grid is a simple http post, I think Serilog is an ideal implementation. The question to the community is, does this make sense to transfer/add to the serilog org as a core sink, or should I just maintain it separately? Please comment with your thoughts. The repo is currently located here https://github.com/Authenticom/serilog-sinks-eventgrid 
 
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

Serilog 2.5.0
Nuget: https://www.myget.org/feed/sirkirby/package/nuget/Serilog.Sinks.EventGrid/1.0.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

The sink dual targets .NET Standard 2.0 and .NET 4.6.1

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [ ] 4.5.x
- [x] Mono 5.4

**Please describe the current behavior?**
Every log event is packaged as a custom event grid event which posts the custom topic you've already set up. All log event properties are added to the event json object's Data property. In addition to that, each event must contain a subject and a type, which is used to route the event to the appropriate subscription. There are currently three ways to configure both. 1. via the log configuration setup 2. via the included custom attribute 3. as a log property in the log event. 

**Please describe the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by merbla** [comment]
@sirkirby we have not been accepting sinks into the org for some time due to the admin overheard.  Having said that we are more than happy to list the sink over on the wiki - [here](https://github.com/serilog/serilog/wiki/Provided-Sinks).

**Comment by sirkirby** [comment]
@merbla totally understand.. works for me. I contacted @nblumhardt and he told me that as well...and also suggested I post the issue to see if there was any interest.

I'll just keep it where it is and set up the ci/cd through appveyor to nuget. If we do want to bring it in at a later date, I would be happy to transfer it over and continue to maintain.

**Comment by nblumhardt** [comment]
Great, thanks @sirkirby 👍
