### ISSUE TITLE
Add utcdate for output templates

### ISSUE THREAD

**Issue by VladikAN** [serilog/serilog#1024]
Feature

Please add utc date for outputTemplate.

For now its only timestamp and date. I can use {Timestamp:u} but without any other format. I would like to have something like this {utcdate:yyyy-MM-dd HH:mm:ss,fff}

**Comment by merbla** [comment]
Hi @VladikAN,

We recently added issue templates.  Just wondering if it worked for you as the details do not seem to be on the issue.  It would be great if you could use the markdown template below.

e.g.

https://github.com/serilog/serilog/issues/new

**Comment by joshmccleery** [comment]
I found that the timestamp written by the file extension are not readable by the AWS cloudwatch log agent. It runs on python, which expects the microsecond portion of the timestamp to be 6 digits long, but the timestamp is written with 7 digits on the microsecond portion. It would be helpful to be able to configure the timestamp output by the logger.

**Comment by nblumhardt** [comment]
@joshmccleery you can do this by specifying an `outputTemplate:` when configuring the sink. The `{Timestamp}` portion can include a .NET format string, like `{Timestamp:o}` for ISO-8601.

**Comment by nblumhardt** [comment]
@VladikAN for now, `:u` is about the best option available. Another is to enrich the log events with a UTC timestamp like so:

```
class UtcTimestampEnricher : ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory pf)
    {
        logEvent.AddPropertyIfAbsent(pf.CreateProperty("UtcTimestamp", logEvent.Timestamp.UtcDateTime));
    }
}
```

This will make `{UtcTimestamp}` available in output templates.

HTH!
Nick

**Comment by robjinman** [comment]
> [@joshmccleery](https://github.com/joshmccleery) you can do this by specifying an `outputTemplate:` when configuring the sink. The `{Timestamp}` portion can include a .NET format string, like `{Timestamp:o}` for ISO-8601.

Where is this o option documented?
