### ISSUE TITLE
Enricher for ASP.CORE 2.X+

### ISSUE THREAD

**Issue by cgountanis** [serilog/serilog#1028]
Project Core MVC.
```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
```

Everything is working well enough, although looking for a way to understand Enrich.FromLogContext(). It seems that when you add {properties} to the custom output you get a lot of good information, not sure how I even figured that out. Is there a list of properties that you can use per enrich/base?

```
 var output = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message} {ActionName} {RequestPath}{NewLine}{Exception}";
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .WriteTo.Console(outputTemplate: output)
                .WriteTo.RollingFile("logs/SSOWeb-{Date}.log", outputTemplate: output)
                .CreateLogger();
```

OK, my question really boils down to simple IP Address capture on every log being this is a web application without making a huge, slow, middleware class. Is there an enrich in the works for this or available anywhere?

Tips, suggestions? Thank you ~

**Comment by nblumhardt** [comment]
Hi Chris,

In ASP.NET Core, there's no ambient context (like the traditional `HttpContext`) that a simple enricher can retrieve things like the IP address from. Plugging in some middleware is the way to go; the runtime cost is little more than a handful of function calls and context allocation per request, so it doesn't get a whole lot cheaper - it would be very surprising to be able to measure any performance impact from the middleware.

Others might have some alternative ideas to add, though - thanks for raising the ticket!

Best regards,
Nick

**Comment by cgountanis** [comment]
**Sounds great, anyone have any examples of just simple adding of HttpContext information via custom middleware?**

Also, I got lucky finding {Properties} {ActionName} {RequestPath}, is there documentation for what is available stock and per enrich for people that make custom output strings?

**Comment by nblumhardt** [comment]
Hi @cgountanis -

The various output properties from Serilog are described here: https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text

Ones like `ActionName` and `RequestPath` are being added by the ASP.NET Core framework itself - the only way to determine what's there is to explore a log stream as far as I know.

For the middleware, the second example in this comment is essentially what you need to do: https://github.com/serilog/serilog/issues/875#issuecomment-252169224

HTH,
Nick

**Comment by IharYakimush** [comment]
I had similar issue and had to write a middleware utilizing "LogContext.Push" as described here. It is generic enough to be a NuGet package and allows to customize which properties from HttpContext should be pushed to LogContext. Hope it will be useful to someone: https://www.nuget.org/packages/Serilog.Enrichers.AspNetCore.HttpContext

**Comment by dalibor-sanzeru** [comment]
> https://www.nuget.org/packages/Serilog.Enrichers.AspNetCore.HttpContext

Mentioned nuget wotking for me without problems.

**Comment by 18549** [comment]
Using a middleware for cases like this is unsatisfactory as that loads of ASP library code executes before your middleware is hit, and in Debug or Verbose mode that ASP library code will be writing loads of log entries none of which will benefit from anything you do in your middleware.

For example. Outputting a correlation ID in your messages to correlate requests through various services. On entry to a service this ID either needs to be a new ID (if it's the first service in your achitecture to handle the request), or it needs to be populated (usually from a header passed by the upstream service). If you set this in a middleware none of the ASP library logging that executes prior to your middleware (which incidentally includes all authentiation handling)  will have the correct ID and so you won't be able to mine your ELK stack (or wherever you keep your logs) and get the full log for a request.

This is one case where an enricher is required, for the same reason that ThreadId is implemented as an enricher. However as there is no way to inject any dependencies into the enricher context one is left having to bypass the DI system and doing things like initialising a static ServiceProvider somewhere.

It would be very useful if Serilog enrichers supported integration into the ASP DI system somehow.
