### ISSUE TITLE
Surprising `SourceContext` format with .ForContext<T> with generics

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1031]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature : possibility for improvement

**What version of Serilog is affected?  Please list the related NuGet package.**
All of 'em

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [x] 4.5.x

**Please describe the current behavior?**
When using a generic type as a parameter to `Log.ForContext<T>`, the property `SourceContext` is a bit ugly.

For instance, when using `logger.ForContext<DummyGenericClass<int, Version>>`, `SourceContext` has the value : ```Serilog.Tests.Core.DummyGenericClass`2[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Version, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]```

(see this unit test for a repro : https://github.com/tsimbalar/serilog/blob/698672ded1285dc2b5aa97e2c208103dc7ce1665/test/Serilog.Tests/Core/LoggerTests.cs#L123 )

**Please describe the expected behavior?**
I would have expected something shorter like : 
```Serilog.Tests.Core.DummyGenericClass<System.Int32, System.Version>```

The actual results makes sense when you think of `Type.ToString()`, but just the type's name (with namespace) seems more consistent with the way the *non-generic* part of the full type name is written

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
see this failing unit test for a repro : 
```csharp
[Fact]
public void ForContextWithGenericTypeAddsTypeParameterNames()
{
	var evt = DelegatingSink.GetLogEvent(l => l.ForContext<DummyGenericClass<int, Version>>()
		.Information(Some.String()));

	var lv = evt.Properties[Constants.SourceContextPropertyName].LiteralValue();
	Assert.Equal("Serilog.Tests.Core.DummyGenericClass<System.Int32,System.Version>", lv);
}
```
from https://github.com/tsimbalar/serilog/blob/698672ded1285dc2b5aa97e2c208103dc7ce1665/test/Serilog.Tests/Core/LoggerTests.cs#L123

**Comment by tsimbalar** [comment]
I should add that the behavior for another edge case - nested classes - is less disturbing : `Serilog.Tests.Core.LoggerTests+DummyNestedClass`

This test passes : 
```csharp
[Fact]
public void ForContextWitNestedClassAddsNestedTypeNameWithAPlus()
{
	var evt = DelegatingSink.GetLogEvent(l => l.ForContext<DummyNestedClass>()
		.Information(Some.String()));

	var lv = evt.Properties[Constants.SourceContextPropertyName].LiteralValue();
	Assert.Equal($"{typeof(LoggerTests).FullName}+{nameof(DummyNestedClass)}", lv);
}
```

see https://github.com/tsimbalar/serilog/blob/698672ded1285dc2b5aa97e2c208103dc7ce1665/test/Serilog.Tests/Core/LoggerTests.cs#L133


I'm kind of wondering if special cases like those may end up being problematic when processing the `SourceContext` property value, for instance in the case of overrides ....

**Comment by nblumhardt** [comment]
Interesting one to look at... thinking through a few considerations.

 * So far we've assumed the source context is formatted using .NET conventions; the C# generics syntax might itself be surprising for VB.NET or F# consumers.
 * It's easy to compare values like `sourceContext == typeof(T).Name`; anything else would mean having to expose our formatter to keep this scenario working.
 * I don't think we'd want to allocate/format up a type name on every event, so some kind of formatted type name cache would be on the cards.

**Comment by tsimbalar** [comment]
I did not really think about the consequences of changing that, obviously :)

I guess as long as `SourceContext` is stored as a string event property, there is no way to change that without breaking some custom filters somewhere ... 

Maybe storing it with both a user-friendly display name and the actual fully-qualified named would help and opt for one format or the other when rendering but I'm not sure there is any added value in there (plus what is a fully qualified type name anyway ? is Foo.Bar of assembly Qux v1.0 the same type as Foo.Bar of assembly Qux v1.1 ?) ... 

I believe *NLog* has the same behavior for the `name` of `LogManager.GetCurrentClassLogger()`, so that's not completely crazy.

I think I'll close the issue :)
