### ISSUE TITLE
Add more mentions of `{Properties}` near ForContext in docs

### ISSUE THREAD

**Issue by bartelink** [serilog/serilog#1036]
As [discussed via twitter](https://twitter.com/rbartelink/status/914766073194536960), while the `{Properties}` facility of the message formatter is technically documented (it's the second last one on the list), the missing bit is to have it mentioned in or near the `ForContext` construct in order to illustrate that, even with a mundane Sink, one can generically inject contextual info

e.g. https://github.com/serilog/serilog/wiki/Writing-Log-Events could mention 

> ... _or, if not used directly in message templates, be included alongside the message via the `{Properties}` Message field_

**Comment by nblumhardt** [comment]
Added a note to the very end of the linked wiki page. The whole page seems to need some rework, hope I can get back there again before too long. Thanks again, Ruben!
