### ISSUE TITLE
New Feature: NHibernate Logging

### ISSUE THREAD

**Issue by mobius127** [serilog/serilog#1046]
Hi there,
There is a solution or a posibility to integrate NHibernate in Serilog like Log4Net??

**Comment by nblumhardt** [comment]
Hi, thanks for getting in touch. IIRC, NHibernate has a direct dependency on log4net, so probably not. The NHibernate mailing list might locate someone who has tried this, though, so worth a try!

**Comment by nblumhardt** [comment]
The amazing @caioproiete has an _NLog.NHibernate_ package here: https://github.com/cprieto/nhibernate.nlog that looks like a good basis for a Serilog package, if anyone's keen to pursue this. Closing for now however, as it's not something the core Serilog project is likely to ship.

Thanks!

**Comment by lnu** [comment]
Hi, I know the question is closed but you can use your own provider starting from NHibernate 5.1.0
I made one for Serilog:
https://github.com/lnu/NHibernate.Logging.Serilog
https://www.nuget.org/packages/NHibernate.Logging.Serilog/
