### ISSUE TITLE
Documentation: use of Configuration rather than AppSettings for .net core

### ISSUE THREAD

**Issue by postb99** [serilog/serilog#1058]
Hello,

I have a .net core project. After reading [this issue](https://github.com/serilog/serilog-sinks-mssqlserver/issues/74) I understood that app settings from .config file are read only for .net classical projects, while appsettings.json are read for .net core projects. I reviewed nuget packages dependencies and package restore information, because my .net core webapp won't load with "Serilog.Settings.AppSettings" nuget package installed.

So please add a link on [configuration basics page](https://github.com/serilog/serilog/wiki/Configuration-Basics) to a new page explaining how to use appsettings.json file.

This documentation wish may be linked to issue #1053 (altough I found that app settings values are documented good enough for base use).

Regards,

**Comment by nblumhardt** [comment]
Thanks! Fixed, and refreshed some more of the content: https://github.com/serilog/serilog/wiki/Configuration-Basics

👍
