### ISSUE TITLE
Syslog Sink

### ISSUE THREAD

**Issue by JonCanning** [serilog/serilog#1060]
https://www.nuget.org/packages/Serilog.Sinks.SyslogServer

https://github.com/TinyBlueRobots/Serilog.Sinks.Syslog

**Comment by nblumhardt** [comment]
Awesome! Thanks for the pointer. We'll add this to the wiki when we have a chance 👍

**Comment by tsimbalar** [comment]
I have added the sink to the list 
https://github.com/serilog/serilog/wiki/Provided-Sinks

**Comment by tsimbalar** [comment]
I've created an issue in your repo to update the Nuget package specs slightly here TinyBlueRobots/Serilog.Sinks.Syslog#1
