### ISSUE TITLE
SerliLog BufferBaseFilename setting Azure Paas Environment

### ISSUE THREAD

**Issue by prasad12k** [serilog/serilog#1062]
Hi,
I want to use BufferBaseFilename  option in Azure Pass environment,Could please let me know is it right approach.
Or any other option available instead of Buffer File.
**Summarize my question**:I want to use buffer in PAAS Azure environment for log reliability.Since file system is not available in PAAS. How to deal with this situation.

**Comment by nblumhardt** [comment]
Hi @prasad12k, thanks for getting in touch.

`bufferBaseFilename` won't work well in a deployment that doesn't have consistent long-running processes that are always re-started with the same local storage. Using `bufferBaseFilename` here could actually cause more log delivery problems, since on shut-down events are flushed to the file rather than flushed across the network.

In short, direct delivery over HTTP is likely to be the best available option. HTH!

**Comment by prasad12k** [comment]
Thanks For your reply.
What is the best approach when application deploying in Azure (PAAS). If bufferBaseFilename  not working what is the alternate approach to store log if elastic server not available.
How to configure serilog durability mode in Azure PAAS Environment.

**Comment by nblumhardt** [comment]
Sorry, there's no durable shipping option that will work in your environment, as far as I'm aware.

**Comment by prasad12k** [comment]
Hi 
thank you so much for your quick reply.
We are deploying DOTNET-MVC application into Azure PaaS and connecting to ElasticSearch Server in Azure for data transactions and I am working on logging the information/warnings/exceptions into Elastic log indexes.

Can you please brief me about following piece of code while writing logs in to elastic server log indexes:
.
**.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
                {
                    BufferBaseFilename = "./logs/Buffer",
                    
                })** 

I understand that Serilog will write the log information to disk buffer when Elastic server unavailable.
Does that disk buffer (**./logs/Buffer**) is mean disk in VM where ElasticServer is running or disk in MVC-Application server?

Advance Thanks,
Durga

**Comment by nblumhardt** [comment]
This will write to local disk on the machine that the application itself (your MVC app) is running.
