### ISSUE TITLE
Wiki/Docs: Outdated link in Getting Started Example App

### ISSUE THREAD

**Issue by ite-klass** [serilog/serilog#1069]
On the Getting Started wiki page/docs in the [section Example Application](https://github.com/serilog/serilog/wiki/Getting-Started#example-application) the code uses the now recommended Console sink, but the introductory text still names and links to the literate console sink.

Current content:

    2. Install the core Serilog package and the [literate console sink](https://github.com/serilog/serilog-sinks-literate)

Should be:

    2. Install the core Serilog package and the [console sink](https://github.com/serilog/serilog-sinks-console)

I would have forked and sent a PR, but that does not seem to be possible for the wiki? Neither is suggesting edits?

**Comment by nblumhardt** [comment]
Fixed, thanks very much!
