### ISSUE TITLE
Logentries sink not being loaded when reading from appsettings.json

### ISSUE THREAD

**Issue by Priyanka-Kalke-Avalara** [serilog/serilog#1070]
I am reading serilog confgurations from appsettings.json but not able to get sinks loaded for logger.
my appsettings settings are

"Serilog":{
"WriteTo": [
      {
        "Name": "Logentries",
        "Args": {
          "Token": "MY_TOKEN",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "outputTemplate": "{Timestamp:HH:mm:ss} {Level:u4} | {RequestId} -{Properties} Message: {Message},{Exception}"
        }
      }
    ]
}

**Comment by nblumhardt** [comment]
Hi @Priyanka-Kalke-Avalara - thanks for getting in touch.

Have you tried using https://github/Suchiman/SerilogAnalyzer to generate the appsettings.json configuration? It may help eliminate any JSON structure/typo issues.
