### ISSUE TITLE
MinimumLevel managed from a settings.json file

### ISSUE THREAD

**Issue by jansoren** [serilog/serilog#1074]
I'm working on an Azure Function and would like to manage my log level from my settings.json file(Application Settings). Is it possible to extend the minimumlevel to take in a string that represents the log level you wish to set? 

Example:
```
return new LoggerConfiguration()
                .MinimumLevel.Set("Debug")
                .WriteTo.TraceWriter(context.Trace)
                .CreateLogger();
```

**Comment by tsimbalar** [comment]
There is already `MinimumLevel.Is(LogEventLevel level)` : 

```csharp
new LoggerConfiguration()
                .MinimumLevel.Is(LogEventLevel.Debug)
                .WriteTo.TraceWriter(context.Trace)
                .CreateLogger();
```

So you could just *parse the enum* :

```csharp
var level = (LogEventLevel) Enum.Parse(typeof(LogEventLevel), "Debug");
new LoggerConfiguration()
                .MinimumLevel.Is(level)
                .WriteTo.TraceWriter(context.Trace)
                .CreateLogger();
```



You may also want to use the `Serilog.Settings.*` Nuget packages that allow to read logger configuration from [AppSettings in a `.config` file](https://github.com/serilog/serilog-settings-appsettings) or from a [`appsettings.json` file](https://github.com/serilog/serilog-settings-configuration).


I hope this helps :)

**Comment by jansoren** [comment]
This was exactly what I was looking for! Thank you :+1:

(Should maybe been mentionted in the readme)
