### ISSUE TITLE
Add a way to override minimal log level for particular execution context

### ISSUE THREAD

**Issue by zihotki** [serilog/serilog#1078]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**Please describe the current behavior?**

Currently the minimal log level can be set only application-wide and there is no way to override it for particular execution pipeline (web request or queue message handler).

**Please describe the expected behavior?**

In some situations it's desirable to have a way to enable deeper logging for some failing request without affecting the whole system and thus logging huge amount of logs from system under load and without a need to change config or implement functionality to change log level system-wide. I would like to be able to send a web request with some 'debug' header and get more detailed logs for only that request. 

Currently there is a good way to pass contextual information in execution context using `AsyncLocal`. It works well with async as well as non-async code. I suggest to implement an override switch which will keep the min level when it's overriden and respect it when determining whether to write log or not. Setting that override switch is going to be application responsibility.

Please let me know what you think. I'll be glad to help with implementation.

**Comment by nblumhardt** [comment]
Thanks for the suggestion!

We haven't done anything along these lines in the core directly because of the performance-sensitivity of level handling (particularly creation of memory barriers &c.), but I don't think that'd stop us from creating an opt-in system to achieve it.

Here's a hacky sketch of how this could work today:

```csharp
static class LogLevelOverride
{
    static readonly AsyncLocal<LogEventLevel?> _currentLevelOverride = new AsyncLocal<LogEventLevel?>(null);

    sealed class LevelOverrideReset : IDisposable
    {
        readonly LogEventLevel? _previousLevelOverride;

        public LevelOverrideReset(LogEventLevel? previousLevelOverride)
        {
            _previousLevelOverride = previousLevelOverride;
        }

        public void Dispose()
        {
            _currentLevelOverride.Value = _previousLevelOverride;
        }
    }

    public static IDisposable Begin(LogEventLevel level)
    {
        var resetValue = _currentLevelOverride.Value;
        _currentLevelOverride.Value = level;
        return new LevelOverrideReset(resetValue);
    }

    public static LogEventLevel? CurrentLevelOverride => _currentLevelOverride.Value;
}

class LevelOverridableLogger : ILogger
{
    readonly ILogger _target;
    readonly ILogEventSink _emitter;

    public LevelOverridableLogger(ILogger target)
    {
        _target = target;
        _emitter = target as ILogEventSink;
        if (_emitter == null) throw new ArgumentException("The logger must also provide the sink interface.");
    }

    public bool IsEnabled(LogEventLevel level)
    {
        if (!LogLevelOverride.CurrentLevelOverride.HasValue)
            return _target.IsEnabled(level);

        return level >= LogLevelOverride.CurrentLevelOverride.Value;
    }

    void Emit(LogEventLevel level, string messageTemplate)
    {
        _target.BindMessageTemplate(messageTemplate, Array.Empty<object>(), out var parsedTemplate, out var properties);
        _emitter.Emit(new LogEvent(DateTimeOffset.UtcNow, level, null, parsedTemplate, properties));
    }

    public void Information(string messageTemplate)
    {
        if (IsEnabled(LogEventLevel.Information))
            Emit(LogEventLevel.Information, messageTemplate);
    }

    public void Debug(string messageTemplate)
    {
        if (IsEnabled(LogEventLevel.Debug))
            Emit(LogEventLevel.Debug, messageTemplate);
    }

    public ILogger ForContext(string propertyName, object value, bool destructureObjects = false)
    {
        return new LevelOverridableLogger(_target.ForContext(propertyName, value, destructureObjects));
    }

    // <snip!>
}

class Program
{
    static void Main()
    {
        var inner = new LoggerConfiguration()
            .WriteTo.Console(outputTemplate: "[{Timestamp:o} {Level:u3}] {Message:lj} {Properties}{NewLine}{Exception}")
            .CreateLogger();

        var wrapper = new LevelOverridableLogger(inner);

        wrapper.Information("Hello, info!");
        wrapper.Debug("Don't see this");

        using (LogLevelOverride.Begin(LogEventLevel.Debug))
        {
            wrapper.Debug("But do see this");
        }

        wrapper.ForContext("SomeData", 42).Information("This works, too");
    }
}
```

Produces:

![image](https://user-images.githubusercontent.com/342712/34749159-a0eac886-f5eb-11e7-81cd-ab9872f2c0da.png)

This takes advantage of the fact that the built-in logger implements `ILogEventSink` and does not apply level control to events that pass through this interface.

Would you be interested in putting together a complete implementation? I think there'd be interest in shipping it as a separate package for a start (_Serilog.ContextLevels_?), which would let us explore this further.

**Comment by zihotki** [comment]
Yes, I'll put it together since I'm interested in it. There are a few more things to consider (hello non-core asp.net, etc.) but in general the idea is correct. 

How we are going to organize it? I can create a personal repo for initial version and as soon as it's completed (code + docs + tests) I'll share it in this issue, is that OK?

**Comment by nblumhardt** [comment]
Excellent :-) 👍 

Creating a personal repo (using the build scripts etc from a Serilog project, such as https://github.com/serilog/serilog-sinks-file) is the way to go. If it all hangs together and you'd like to transfer the result to the Serilog organisation we can do that down the track.

https://gitter.im/serilog/serilog is useful if you need a hand along the way (feel free to post here as well, of course!).

**Comment by nblumhardt** [comment]
Closing this for the time being, but would love an update if you were able to make headway on this @zihotki 👍

**Comment by mayuragarwal-qm** [comment]
Hello, is there any update on this feature?
I have a similar requirement to override the minimum log level for a tenant (in a multi-tenant asp.net core application).
We get TenantId from Request URL and writing file logs for each tenant in a separate folder using File sink.
In appsettings.json, minimum level is Error but would like to switch Serilog to Debug level for a given tenant and request in production.
How do we make that switch for a given request assuming that the minimum level can be read from Context like HttpContext or similar.

**Comment by StandBackBurrito** [comment]
> Hello, is there any update on this feature? I have a similar requirement to override the minimum log level for a tenant (in a multi-tenant asp.net core application). We get TenantId from Request URL and writing file logs for each tenant in a separate folder using File sink. In appsettings.json, minimum level is Error but would like to switch Serilog to Debug level for a given tenant and request in production. How do we make that switch for a given request assuming that the minimum level can be read from Context like HttpContext or similar.

I am looking for something like this myself
