### ISSUE TITLE
Readme needs updating to use Serilog.Sinks.File

### ISSUE THREAD

**Issue by drewfreyling** [serilog/serilog#1086]
Currently the readme recommends using `Serilog.Sinks.RollingFile` for a rolling log but the readme of `Serilog.Sinks.RollingFile` says to use `Serilog.Sinks.File`.

So the readme needs to refer to using Serilog.Sinks.File. If everyone agrees I'll submit a PR.

**Comment by merbla** [comment]
Please do!

**Comment by nblumhardt** [comment]
Thanks for spotting this, @drewfreyling - I've just given it a once-over, let me know if you still see anything obsolete :-)
