### ISSUE TITLE
SerializationException when using System.Runtime.Serialization.Formatters.Binary.BinaryFormatter on LogEvent class

### ISSUE THREAD

**Issue by IharYakimush** [serilog/serilog#1090]
Currently it is not possible to serialize LogEvent class using 
```System.Runtime.Serialization.Formatters.Binary.BinaryFormatter```

code sample:
```
BinaryFormatter binaryFormatter = new BinaryFormatter();
            using (MemoryStream memoryStream = new MemoryStream())
            {
                binaryFormatter.Serialize(memoryStream, logEvent);
                return memoryStream.ToArray();
            }
```
Exception thrown:
> System.Runtime.Serialization.SerializationException: "Type 'Serilog.Events.LogEvent' in Assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' is not marked as serializable."

Looks like setting Serializable attribute not possible in netstandard1.0.
Do you plan to continue support of netstandard1.0 ?

**Comment by IharYakimush** [comment]
Looks like setting Serializable attribute not possible in netstandard1.0. 
Do you plan to continue support of netstandard1.0 ?

**Comment by nblumhardt** [comment]
Hi Ihar - thanks for getting in touch.

`LogEvent` isn't designed for binary serialization - using _Serilog.Formatting.Compact_ and _Serilog.Formatting.Compact.Reader_ can be an effective alternative in some cases.

Hope this helps,
Nick
