### ISSUE TITLE
Transfer of ownership on Serilog.Sinks.Nats

### ISSUE THREAD

**Issue by daghb** [serilog/serilog#1095]
I have built a new NATS sink for Serilog. The repo is here: https://github.com/daghb/serilog.sinks.nats

I have used the checklist to ensure all the conventions listed including licensing comments and "green" light from Resharper. The repo is using Appveyor for build and is also available as a nupkg on nuget.org: https://www.nuget.org/packages/Serilog.Sinks.Nats

**Comment by nblumhardt** [comment]
Thanks for getting in touch!

I've added the sink to [the Available Sinks wiki page](https://github.com/serilog/serilog/wiki/Provided-Sinks).

We're no longer accepting new sinks into the Serilog organization except in rare cases (e.g. platform functionality). Let us know if you need any help with maintenance, though!

Cheers,
Nick

**Comment by daghb** [comment]
I understand. A little tip: Update this page to reflect the new policy: https://github.com/serilog/serilog/wiki/Contributing
