### ISSUE TITLE
Template renderer confuses placeholders in some situations

### ISSUE THREAD

**Issue by inosik** [serilog/serilog#1097]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.6.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [ ] 4.5.x

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

``` csharp
Log.Information("{X} {X} {Y}", 1, 2);
```

**Please describe the current behavior?**

In this specific case, the rendering gets slightly confused. Serilog renders the former message to this:

```
[09:52:45 INF] 2 2 {Y}
```

**Please describe the expected behavior?**

The message should be rendered to this:

```
[09:52:45 INF] 1 1 2
```

Note that the following messages get rendered correctly:

``` csharp
Log.Information("{X} {Y} {Y}", 1, 2);
Log.Information("{X} {Y} {X}", 1, 2);
```

Output:

```
[09:52:45 INF] 1 2 2
[09:52:45 INF] 1 2 1
```

**Comment by nblumhardt** [comment]
Thanks for the report @inosik.

This is by design - numeric placeholders allow reordering and repeats, but named placeholders are always matched 1:1 with arguments from left-to-right.

https://github.com/Suchiman/SerilogAnalyzer is a VS or NuGet plug-in based on Roslyn that will detect these issues for you at development time.

HTH,
Nick

**Comment by inosik** [comment]
But the other two examples still work as "expected", though. In the first one, the first parameter doesn't appear anywhere.

**Comment by nblumhardt** [comment]
Thanks for the follow-up! Yes, in these cases it just happens to work in the way you're suggesting, but it's only a coincidence based on how the formatting is currently implemented, not something that is expected to work across versions. (There are some trade-offs here around performance vs strong validation - hence _SerilogAnalyzer_ is highly recommended for the compile-time checks.)
