### ISSUE TITLE
Can you list Serilog.Exceptions as a community project?

### ISSUE THREAD

**Issue by krajek** [serilog/serilog#1098]
https://github.com/RehanSaeed/Serilog.Exceptions

I may have missed something, but I did not find any place where `Serilog` wiki mentions `Serilog.Exceptions`. It is an enricher that destructures your exceptions so that all the properties are in the `LogEvent` even if the exception itself does not have them in its message.

**Comment by nblumhardt** [comment]
Done! Thanks for the suggestion. Now can be found at the end of https://github.com/serilog/serilog/wiki/Enrichment.
