### ISSUE TITLE
Cant log to file from NUnit test

### ISSUE THREAD

**Issue by sam-wheat** [serilog/serilog#1102]
[This question](https://github.com/serilog/serilog/issues/607) leads me to beleive logging should work from within NUnit, at least to the console.
Also [this question](https://github.com/serilog/serilog/issues/128) states "...NUnit works very nicely (even within VisualStudio) with Serilog...".

However [this page](https://github.com/luk355/Serilog.Sinks.NUnit) states "Logging currently does not work in VS Test Adapter as TestContext.Out is not being populated there."  Does that mean <i>all</i> logging? Even logging to a file? I know newer versions of NUnit depend on MSTest but I'm not sure what the relationship is or if MSTest now breaks NUnit or Serilog after above posts were written.

I am not using Serilog.Sinks.NUnit. I am just trying to log to a file using plain ol Serilog and the most basic .WriteTo.File(...) configuration.  The result is that no log file is created.  When I log from my app using the same logging configuration it works fine.

This is the desired configuration which does not produce a log file:
		
	    [SetUp]
        protected virtual void Setup()
        {
			Log.Logger = new LoggerConfiguration()
			.MinimumLevel.Debug()
			.WriteTo.File(@"__logfile.txt", rollingInterval: RollingInterval.Day)
			.CreateLogger();
			Log.Logger.Information("Boo");
        }
		
Also tested this configuration based on link referenced above which produces no output ("Copy All" from Test Explorer window).		
		
	    [SetUp]
        protected virtual void Setup()
        {
			Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
            Log.Logger = new LoggerConfiguration()
                .WriteTo
                .TextWriter(Console.Out)
                .CreateLogger();
			Log.Logger.Information("Boo");
        }
		
Using
.NetFramework 4.7.1
Serilog 2.6
Serilog.Sinks.File 4.0.0
Nunit 3.9
All dependencies are nuget latest.

Thank you.

**Comment by sam-wheat** [comment]
Do I need to know the secret handshake?

**Comment by nblumhardt** [comment]
Hi Sam :-)

It looks more like a test framework issue than a Serilog one - what's the working directory, does the process have permissions, etc.

You might also try adding `Log.CloseAndFlush()` after you're done with the file, though without it the file should still be created (it just won't be unlocked until some unspecified future time).

HTH!

**Comment by sam-wheat** [comment]
Thanks Nick I got it. Looks like file sink needs a fully qualified path to work.
