### ISSUE TITLE
Milisecond Precision issue

### ISSUE THREAD

**Issue by davidATceedo** [serilog/serilog#1103]
When writing to file, we noticed that many operations that before took a few miliseconds, now appear as if are in the same time.

Before (Log4Net):
26/01/18 16:53:38.882	INFO	doc extension was added to include list
26/01/18 16:53:38.889	INFO	docx extension was added to include list
26/01/18 16:53:39.020	INFO	xls extension was added to include list
26/01/18 16:53:39.026	INFO	xlsx extension was added to include list
26/01/18 16:53:39.033	INFO	ppt extension was added to include list
26/01/18 16:53:39.039	INFO	pptx extension was added to include list
26/01/18 16:53:39.045	INFO	pdf extension was added to include list

After (Serilog):
12/02/18 15:59:49.312	[INF]	doc extension was added to include list
12/02/18 15:59:49.312	[INF]	docx extension was added to include list
12/02/18 15:59:49.313	[INF]	xls extension was added to include list
12/02/18 15:59:49.313	[INF]	xlsx extension was added to include list
12/02/18 15:59:49.313	[INF]	ppt extension was added to include list
12/02/18 15:59:49.313	[INF]	pptx extension was added to include list
12/02/18 15:59:49.313	[INF]	pdf extension was added to include list

We're now afraid this might cause issues with debugging.

(My file logger: 

                string customTemplate = "{Timestamp:dd/MM/yy HH:mm:ss.fff}\t[{Level:u3}]\t{Message}{NewLine}{Exception}";
                _fileLogger = new LoggerConfiguration().MinimumLevel.ControlledBy(LevelSwitch)
                                .WriteTo.File(_logFile, shared: true, outputTemplate: customTemplate, 
                                fileSizeLimitBytes: rollOver, rollOnFileSizeLimit: true)
                                .CreateLogger();

)

Is there anyway to get better precision on the timestamp?

**Comment by davidATceedo** [comment]
Or is it that Serilog is soooooooooo much faster (keeping the file open) that write to log operations are so fast they appear on the same millisecond? (adding microsecond to the template (.ffffff instead of .fff) shows that these operations are in the exact microsecond, which is of course impossible).

**Comment by tsimbalar** [comment]
Hi,

Someone correct me if I am wrong, but the *File* Sink is not synchronous. Log events are generated when the log statements are called (and may have very very close timestamps in a tight loop), but the actual writing to the file is deferred and batched. 

I believe this is similar to the behavior you would have in log4net when configuring it to be asynchronous with batches like in this article : http://www.nimaara.com/2016/01/01/high-performance-logging-log4net/ .

What is happening in your case is that the logging statements are probably slowing down your code (just a bit, we are talking about miliseconds here !).

You would probably have the same kind of performance if you used `AuditTo` instead of `WriteTo` in your Serilog configuration code : 

```csharp
string customTemplate = "{Timestamp:dd/MM/yy HH:mm:ss.fff}\t[{Level:u3}]\t{Message}{NewLine}{Exception}";
_fileLogger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(LevelSwitch)
    .AuditTo.File(_logFile, 
              shared: true, 
              outputTemplate: customTemplate,
              fileSizeLimitBytes: rollOver, 
              rollOnFileSizeLimit: true)
    .CreateLogger();
```

(using `AuditTo` ensures the event is written to the sink before returning)

**Comment by nblumhardt** [comment]
@tsimbalar yes, they're essentially batched, but by the OS page cache (so nothing's visible on the Serilog side to indicate batching). Setting `flushToDiskInterval: ...` will force a full sync to disk.

If the code is in a loop like:

```csharp
foreach (var ext in extensions)
{
    includeList.Add(ext);
    Log.Information("Extension {ext} was added to the include list");
}
```

then it's likely the whole lot executes within the upper limit of .NET `DateTimeOffset.Now` precision (anecdotally, a few 10s of ms).

It's more likely your log4net configuration is using a higher-resolution timer; it's not impossible to rig this up for Serilog, but the overheads are unlikely to be worth it for most general logging statements.

You might try: https://github.com/serilog-metrics/serilog-metrics or https://github.com/nblumhardt/serilog-timings for the places in the code where precise timings are important. Let me know if this helps!

Cheers,
Nick

**Comment by davidATceedo** [comment]
Ok - thanks for the reply. We will leave as is for now, and if the accuracy becomes an issue will look at the metircs/timings option.
