### ISSUE TITLE
Expose `SilentLogger` as `Logger.None`

### ISSUE THREAD

**Issue by invino4** [serilog/serilog#1105]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.6.0

**What is the target framework and operating system? See [target frameworks]
- [x ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
There is no mechanism for creating a Serilog.ILogger that does nothing.

**Please describe the expected behavior?**
I sometimes use an optional pattern for logging in libraries such as:

````csharp
        public SomeClass(ILogger logger = null)
        {
            m_logger = (logger ?? new SilentLogger).ForContext<SomeClass>();
        }
````

This allows consumers of the class that aren't using logging to use the abstraction without logging, while those that are can pass in a logger without having all log statements require a condition method operator.  Being able to instantiate a SilentLogger makes this cheap.  

Is there a better pattern with Serilog for accomplishing this?

**Comment by nblumhardt** [comment]
Hi @invino4 - this should do the job:

```
var silent = new LoggerConfiguration().CreateLogger();
```

**Comment by invino4** [comment]
A little expensive for library code since it requires several allocations.  Something like:

````csharp
    m_logger = (logger ?? Log.NullLogger).ForContext<SomeClass>();
````

where ```Log.NullLogger``` was a static thread-safe singleton would be cheaper.  What do you think?

**Comment by nblumhardt** [comment]
Still a little awkward, perhaps we should zoom out and look at the scenario in more detail, to see whether there's a better pattern for this?

**Comment by invino4** [comment]
Makes sense.  The scenario is that I have a number of libraries that are fairly general purpose.  In all of these libraries (and most of my software) mutable global variables are strictly avoided to promote composability, race-free operation, etc.  Strictly speaking, all capabilities are passed down when needed including logging.

Some of the consumers of these libraries are using logging.  If logging is in use, then there is some value in passing a logger to the libraries so they can log their actions (or even do Debug or Verbose/Trace logging).  However, if logging is not in use by the consumer it is onerous to have to pass a logger to the class.  Now the class can easily specify the capability as optional, however, in implementing the class I don't want this flexibility to either complicate the code or negatively impact performance.  The easiest way to prevent this is to ensure that the m_logger field is never-null (and usually readonly).  Now the reasoning about the existence of a logger is confined to the constructor.

Assigning the m_logger to an immutable static implementation (effectively a compile-time constant) is nearly free in most runtime environments (and can be truly zero-cost in the presence of tracing JIT or Whole Program Optimization).  This makes the pattern suitable for both class and struct implementations without having any impact on the allocation profile.  E.g.

````csharp
   for (int i = 0; i < 10000; i++) {
      MyStruct s = new MyStruct(logger: null)
      ...
   }
````

This loop silently, implicitly makes 10000 allocations.  If it is easy, I'd like to avoid this.

**Comment by nblumhardt** [comment]
> Assigning the m_logger to an immutable static implementation (effectively a compile-time constant) is nearly free in most runtime environments

It should be easy just to create your own `static readonly ILogger NoLogger = new SilentLogger()` to get going, but having a `Logger.None` on the Serilog side does also sound nice. Open to a PR, if anyone is interested in pursuing this further 👍
