### ISSUE TITLE
Lack of guidance on this pattern

### ISSUE THREAD

**Issue by Lassesen** [serilog/serilog#1106]
I am working on some code and I came across this.  It is unclear if the time to make the call is actually being recorded because the task is returned which may not be completed.

Clarity would be appreciated.

In
  protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, 
 CancellationToken cancellationToken)
        {
            var operationDescription = $"Request Time for '{request.RequestUri.AbsoluteUri}'";            
            using(Log.Logger.BeginTimedOperation(operationDescription))
            {
                return base.SendAsync(request, cancellationToken);
            }
        }

**Comment by nblumhardt** [comment]
Hi! You need to make the method `async` and await the `base...` call for the log context to flow correctly, here.

HTH,
Nick

**Comment by Lassesen** [comment]
Exactly what I expected, should help persuade some other dev's of the issue

**Comment by nblumhardt** [comment]
:+1:
