### ISSUE TITLE
ASP.Net Core 2 Console app Debug/Trace Logs missing

### ISSUE THREAD

**Issue by irashid25** [serilog/serilog#1107]
**Does this issue relate to a new *feature* or an existing *bug*?**
- Bug

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.6.0
Serilog.Extensions.Logging 2.0.2

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- netCore 2.0

**Please describe the current behavior?**
I have made an asp.net core 2 console application and am trying to use serilog for logging. I am reading the serilog config from a appsettings.json file and no matter what i set the min level to, it never outputs debug or trace/verbose logs.

**Please describe the expected behavior?**
All logs levels are written to target sink.

My program main method is like so:

```
static void Main(string[] args)
        {
            var services = new ServiceCollection()
                .AddLogging();
            var serviceProvider = services.BuildServiceProvider();
            var configuration = Configure();

           services.AddSingleton<ILoggerFactory>();

            var loggerFactory = serviceProvider.GetService<ILoggerFactory>();

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            loggerFactory.AddSerilog();

            var logger = serviceProvider.GetService<ILogger<Program>>();
            logger.LogTrace("trace");
            logger.LogWarning("warning");
            logger.LogCritical("critical");
            logger.LogError("error");
            logger.LogInformation("info");
            logger.LogDebug("debug");
            Console.ReadLine();
        }

        public static IConfiguration Configure()
        {
            var path = Directory.GetCurrentDirectory();
            var builder = new ConfigurationBuilder()
                .SetBasePath(path)
                .AddJsonFile("appsettings.json");

            return builder.Build();
        }
```
My appsetting.json file is like so:

```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Verbose",
        "System": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": { "outputTemplate": "[{Timestamp:Timestamp:HH:mm:ss} [{Level}] {SourceContext:l} {Message}{NewLine}{Exception}" }
      },
      {
        "Name": "RollingFile",
        "Args": {
          "MinimumLevel": "Verbose",
          "pathFormat": "logs\\log-{Date}.log",
          "outputTemplate": "[{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level}] {SourceContext:l} {Message}{NewLine}{Exception}"
        }
      }
    ]
  }
}
```

I've even tried to set the min level to verbose when creating the logger configuration above in my main method, but that doesn't seem to help either.
I would like serilog to read the min level from my config file.

Thanks in advance.

**Comment by nblumhardt** [comment]
Hi! For ASP.NET Core 2.0, you need to use the https://github.com/serilog/serilog-aspnetcore package, which has some slightly different setup instructions. Should be fairly straightforward to update.

If you still hit issues using that package, please let us know over on that repository and we'll take a look. Thanks!

**Comment by irashid25** [comment]
Thanks @nblumhardt. I followed the instructions for my web project, and it is working correctly. However i am not sure if the instructions apply to a console application. For anyone in the same boat, i have raised the following issue - https://github.com/serilog/serilog-aspnetcore/issues/34

**Comment by pcbHikeME** [comment]
Yes i had this same problem.  Could not for the life of me get .net core 2.2 console project to read serilog config from appsettings.json using the following pkgs:
Serilog.AspNetCore 2.1.1
Serilog.Extensions.Hosting 2.0.0
Serilog.Extensions.Logging 2.0.4
Serilog.Settings.Configuration 3.1.0
Serilog.Sinks.File 4.0.0

It would only work with config in code via the fluent calls.
```csharp
Log.Logger = new LoggerConfiguration()
                .WriteTo.File(path:"Logs\\log.txt")
                .MinimumLevel.Debug()
                .CreateLogger();
```
