### ISSUE TITLE
New sentry sink

### ISSUE THREAD

**Issue by olsh** [serilog/serilog#1109]
Hello,

Could you please add the Sentry(https://sentry.io) sink to the [List of available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks)?

Source code: 
https://github.com/olsh/serilog-sinks-sentry

Nuget:
https://www.nuget.org/packages/Serilog.Sinks.Sentry/ - the Sentry sink.
https://www.nuget.org/packages/Serilog.Sinks.Sentry.AspNetCore/ - the extended version supports capturing HTTP context in ASP.NET Core apps.

**Comment by merbla** [comment]
Done 👍
