### ISSUE TITLE
NetStandard 2.1 optimization opportunities (use Span<char>)

### ISSUE THREAD

**Issue by shatl** [serilog/serilog#1114]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.6.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
- [x] netCore 2.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

**Please describe the expected behavior?**
Reduce memory allocations by using Span<char> instead of substrings
* In JsonValueFormatter.WriteQuotedJsonString
  * Use Span<char> instead of creating substrings;
  * Use local char array to generate hex code.

Depends on https://github.com/dotnet/corefx/pull/23915 https://github.com/dotnet/corefx/milestone/12

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by ralsu091** [comment]
Unfortunately, there is no netstandard2.1 yet https://github.com/dotnet/standard/issues/682 :(, did you mean netcoreapp2.1?
This feature would be interesting :)

**Comment by coreConvention** [comment]
Any plans on actually updating this to netstandard2.0 at least?

**Comment by nblumhardt** [comment]
@coreConvention adding a .NET Standard 2.0 target would be a welcome PR, I'll raise and link an issue, thanks.

@shatl I think for now it makes sense to close this, and reopen as a PR if you (or anyone else keen to give it a shot) can get good performance numbers out of the change. Thanks for raising it! 👍
