### ISSUE TITLE
CustomDateFormatter example kills all output

### ISSUE THREAD

**Issue by bitchkat** [serilog/serilog#1115]
**A few questions before you begin:**

> Is this an issue related to the Serilog core project or one of the [sinks]
Serilog core

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.6.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I'm following the CustomDateFormatter example on https://github.com/serilog/serilog/wiki/Formatting-Output to provide custom formatting for DateItem properties in messages.  When I add the CustomDateFormatter to my sinks, it disables all output.

When I debug the GetFormat() method, its always passed an object of type System.ICustomFormatter and not a type like System.Globalization.DateTimeFormatInfo.  

It looks like this is invoked from `ScalarValue.cs`:
```csharp
var custom = (ICustomFormatter)formatProvider.GetFormat(typeof(ICustomFormatter));
```

And I suspect that since the example code is returning an IFormatProvider, that the cast is failing which is why nothing is getting printed.

I used this page (https://msdn.microsoft.com/en-us/library/system.icustomformatter(v=vs.110).aspx) as a guide and reimplemented my class as follows:
```csharp
public class CustomDateFormatter : IFormatProvider, ICustomFormatter
{
	private readonly string _datePattern;

	/// <summary>
	/// Initializes a new instance of the <see cref="DateFormatter"/> class.
	/// </summary>
	/// <param name="datePattern">date format pattern</param>
	/// <param name="basedOn">base format provider</param>
	public CustomDateFormatter(string datePattern)
	{
		_datePattern = datePattern;
	}

	/// <summary>
	/// Gets the Formatter object
	/// </summary>
	/// <param name="formatType">format type</param>
	/// <returns>formatter</returns>
	public object GetFormat(Type formatType)
	{
		if (formatType == typeof(ICustomFormatter))
		{
			return this;
		}

		return null;
	}

	/// <summary>
	/// Formats an object for output
	/// </summary>
	/// <param name="format">optional format string, if not provided the default date pattern is used</param>
	/// <param name="arg">the object to be formatted</param>
	/// <param name="formatProvider">format provider</param>
	/// <returns>formatted string</returns>
	public string Format(string format, object arg, IFormatProvider formatProvider)
	{
		if (arg is DateTime)
		{
			return ((DateTime)arg).ToString(format ?? _datePattern);
		}
		else
		{
			try
			{
				return HandleOtherFormats(format, arg);
			}
			catch (FormatException e)
			{
				throw new FormatException($"The format of '{format}' is invalid", e);
			}
		}
	}

	/// <summary>
	/// Fallback formatter for non DateTime objects
	/// </summary>
	/// <param name="format"></param>
	/// <param name="arg"></param>
	/// <returns></returns>
	private string HandleOtherFormats(string format, object arg)
	{
		if (arg is IFormattable)
		{
			return ((IFormattable)arg).ToString(format, CultureInfo.CurrentCulture);
		}
		else if (arg != null)
		{
			return arg.ToString();
		}
		else
		{
			return string.Empty;
		}
	}
}
```
It seems to be working correctly.  In Console at least.  Does the File sink not use the formatter even if I provide a formatProvider on WriteTo.File() ?

**Please describe the expected behavior?**
Just need an example for formatting DateTime that reflects current practice.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by nblumhardt** [comment]
Thanks for the heads-up, looks like we'll need to do some digging around and update either the docs or the impl.

**Comment by bitchkat** [comment]
No problem.  Can you confirm whether its supposed to work with the FileSink or not?  My class above works great for ConsoleSink but the FileSink is formatting with an ISO 8601 format.

**Comment by nblumhardt** [comment]
@bitchkat should definitely work with the file sink :+1:

**Comment by bitchkat** [comment]
@nblumhardt Thanks again.  It looks like the custom formatter is getting ignored in the file sink as my output looks like
`2018/02/23 23:00:35.552 [DBG] Test log message at "2017-10-03T22:00:00.0000000Z" {}
`
The formatter is the exact same one passed to console sink as
`				config.WriteTo.Console(
					levelSwitch: _consoleLogLevel,
					outputTemplate: _outputTemplate,
					formatProvider: formatter);`

and passed to the file sink as
`				.WriteTo.File(
					_logFilePath,
					rollingInterval: RollingInterval.Day,
					rollOnFileSizeLimit: true,
					fileSizeLimitBytes: _logFileSizeLimit,
					shared: true,
					outputTemplate: _outputTemplate,
					formatProvider: formatter);`

**Comment by tsimbalar** [comment]
Hi,

It's been a while , but better late than never :) ... 

I have tried to reproduce the issue, using the example from the wiki with the following test : 

```csharp
[Fact]
[Trait("Bugfix", "#1115")]
public void CustomDateFormatProviderCanBeUsed()
{
    // relying on the example from wiki : https://github.com/serilog/serilog/wiki/Formatting-Output
    // using 5 digits for year on purpose, so it is visible !
    var customDateFormatProvider = new CustomDateFormatter("yyyyy-MM-dd", CultureInfo.InvariantCulture);

    var formatter = new MessageTemplateTextFormatter("{Message}", customDateFormatProvider);
    var evt = DelegatingSink.GetLogEvent(l => l.Information("{@Item}", new
    {
        CreatedOn = new DateTime(2018, 01, 01)
    }));
    var sw = new StringWriter();
    formatter.Format(evt, sw);

    Assert.Contains( "02018-01-01 00:00:00", sw.ToString());
}

class CustomDateFormatter : IFormatProvider
{
    // sample taken from wiki : https://github.com/serilog/serilog/wiki/Formatting-Output
    readonly IFormatProvider basedOn;
    readonly string shortDatePattern;
    public CustomDateFormatter(string shortDatePattern, IFormatProvider basedOn)
    {
        this.shortDatePattern = shortDatePattern;
        this.basedOn = basedOn;
    }
    public object GetFormat(Type formatType)
    {
        if (formatType == typeof(DateTimeFormatInfo))
        {
            var basedOnFormatInfo = (DateTimeFormatInfo)basedOn.GetFormat(formatType);
            var dateFormatInfo = (DateTimeFormatInfo)basedOnFormatInfo.Clone();
            dateFormatInfo.ShortDatePattern = this.shortDatePattern;
            return dateFormatInfo;
        }
        return this.basedOn.GetFormat(formatType);
    }
}
```

This **test passes**. 

It turns out that 
`var custom = (ICustomFormatter)formatProvider.GetFormat(typeof(ICustomFormatter));` 
is indeed called, and our custom `IFormatProvider` does not care much for it ... but later on , the call to `IFormattable.ToString(format, IFormatProvider)` does what needs to be done : 

```csharp
var f = value as IFormattable;
if (f != null)
{
    output.Write(f.ToString(format, formatProvider ?? CultureInfo.InvariantCulture));
}
else
{
    output.Write(value.ToString());
}      
```

This confirms that this may not be an issue in Serilog ***Core*** but rather in the ***File Sink***.

I'll open an issue there so we can look at it.

Cheers !

**Comment by skomis-mm** [comment]
I think the problem with [this](https://github.com/serilog/serilog/blob/dev/src/Serilog/Rendering/MessageTemplateRenderer.cs#L95-L99) one which ignores custom provider when `lj` specified. Should be instead like 
```
if (literal && propertyValue is ScalarValue sv)
{
    sv.Render(output, format, formatProvider);
}
```
@tsimbalar @nblumhardt ?

**Comment by nblumhardt** [comment]
@skomis-mm yes, that seems closer to what's intended, I think :+1:

**Comment by tsimbalar** [comment]
It looks like this does indeed have to do with the `:j` JSON-style rendering.

This test fails (just adding `:j` to the previous test case in `{Message:j}` ... the tests passes with `{Message:l}` ) : 

```csharp
[Fact]
[Trait("Bugfix", "#1115")]
public void CustomDateFormatProviderCanBeUsed()
{
    // relying on the example from wiki : https://github.com/serilog/serilog/wiki/Formatting-Output
    // using 5 digits for year on purpose, so it is visible !
    var customDateFormatProvider = new CustomDateFormatter("yyyyy-MM-dd", CultureInfo.InvariantCulture);

    var formatter = new MessageTemplateTextFormatter("{Message:j}", customDateFormatProvider);
    var evt = DelegatingSink.GetLogEvent(l => l.Information("{@Item}", new
    {
        CreatedOn = new DateTime(2018, 01, 01)
    }));
    var sw = new StringWriter();
    formatter.Format(evt, sw);

    Assert.Contains( "02018-01-01 00:00:00", sw.ToString());
}


class CustomDateFormatter : IFormatProvider
{
    // sample taken from wiki : https://github.com/serilog/serilog/wiki/Formatting-Output
    readonly IFormatProvider basedOn;
    readonly string shortDatePattern;
    public CustomDateFormatter(string shortDatePattern, IFormatProvider basedOn)
    {
        this.shortDatePattern = shortDatePattern;
        this.basedOn = basedOn;
    }
    public object GetFormat(Type formatType)
    {
        if (formatType == typeof(DateTimeFormatInfo))
        {
            var basedOnFormatInfo = (DateTimeFormatInfo)basedOn.GetFormat(formatType);
            var dateFormatInfo = (DateTimeFormatInfo)basedOnFormatInfo.Clone();
            dateFormatInfo.ShortDatePattern = this.shortDatePattern;
            return dateFormatInfo;
        }
        return this.basedOn.GetFormat(formatType);
    }
}
```

with test error message : 

```
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: 02018-01-01 00:00:00
In value:  {"CreatedOn":"2018-01-01T00:00:00.0000000"}
   at Xunit.Assert.Contains(String expectedSubstring, String actualString)
   at Serilog.Tests.Formatting.Display.MessageTemplateTextFormatterTests.CustomDateFormatProviderCanBeUsed() in C:\Dev\serilog\serilog\test\Serilog.Tests\Formatting\Display\MessageTemplateTextFormatterTests.cs:line 296
```

JSON itself does not specify how dates should be formatted, and people seem to usually fall back to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). 

Using a custom `FormatProvider` to customize formatting seems pretty legit. But now I am wondering if `JsonValueFormatter` would need to be changed to , given it uses hard-coded formats:

https://github.com/serilog/serilog/blob/9a46e68d3e224b965f4ac2665fd379ae9568d6b4/src/Serilog/Formatting/Json/JsonValueFormatter.cs#L257-L262

**Comment by nblumhardt** [comment]
I think the idea of `:j` is that it's effectively a serialization format, I wouldn't really expect custom formatting applied in there, personally. I think the ambiguity appears because `:lj` is "JSON with an exception for literal strings" - this could behave either way, but the custom formatting seems more appropriate because we're aiming for human consumption at that level. Thoughts?

**Comment by sukchai19933** [comment]
ok

**Comment by tsimbalar** [comment]
This PR may help with issue serilog/serilog-sinks-file#57 ... 

Does anyone see any reason not to merge it ? :)

**Comment by tsimbalar** [comment]
Just to loop back to this original issue  .... 

We have determined that : 
- the behavior of the *File* sink is the expected one
- the behavior of the *Console* sink is the one that might be considered inconsistent
- we are not going to fix that issue in the *Console* sink because it would force users who relied on that behavior to fix their configuration, and probably generate some extra support work.

Cheers !
