### ISSUE TITLE
Any interest in a Twilio Sink?

### ISSUE THREAD

**Issue by dougkwilson** [serilog/serilog#1116]
I've started working on one here: https://github.com/dougkwilson/Serilog.Sinks.Twilio

I'm looking for feedback, ways to improve, etc.  If there is any interest I would like to contribute it to Serilog.

**Comment by merbla** [comment]
Hi @dougkwilson,

I can add the sink to the [Available Sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) page however we are not currently accepting new sinks into the Serilog organization itself.

Thoughts?

**Comment by tsimbalar** [comment]
@dougkwilson as @merbla said, we are currently not taking new sinks into the organization, and most "specific" sinks are actually maintained out of the organization.

If you are asking for feeback and want to make your sink discoverable, though, here are some suggestions : 
- publish your sink on NuGet, and add the package name and a link in your README
- in the README : add sample configuration code, and possibly sample configuration (in XML and JSON)

The [Http Sink](https://github.com/FantasticFiasco/serilog-sinks-http) is a good example, I believe :) 

I hope this helps !

**Comment by dougkwilson** [comment]
Great! Thanks.
