### ISSUE TITLE
Rollbar sink

### ISSUE THREAD

**Issue by olsh** [serilog/serilog#1117]
Hello,

Could you please add the [Rollbar](https://rollbar.com/) sink to the [List of available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks)?

[Source code](https://github.com/olsh/serilog-sinks-rollbar)
[Nuget](https://www.nuget.org/packages/Serilog.Sinks.RollbarCom/)

**Comment by tsimbalar** [comment]
Done ! 

See https://github.com/serilog/serilog/wiki/Provided-Sinks

Cheers !

**Comment by cbittencourt** [comment]
Looks like Rollbar has their own Serilog sink: https://github.com/rollbar/Rollbar.NET/tree/master/Rollbar.PlugIns.Serilog
