### ISSUE TITLE
How to correctly log in an async method?

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog#1118]
Hello,

Looking for guidance here as to the approaches for logging timed operations or just general log statements within a method marked as **async**  as in this example:

	public virtual async void GetAWDData(string objectId, string correlationId = null)
	{
		using (Log.BeginTimedOperation("GetAWDData", level:LogEventLevel.Debug))
		{
			AWDData = await _letterCoreServices.ExternalFieldsServices.FetchHierarchyAsync<Connect.WorktypeObjects.Case>(correlationId, objectId);
		}
	}

Please overlook the void method for the moment, I believe it should be a Task, but you see the general idea. I'd like to keep timing all my service calls as the information is very important.

Should I not be logging at all inside of the async methods?

Thank you,
Stephen

**Comment by nblumhardt** [comment]
Hi Stephen - your example looks fine to me :+1: - Serilog generally "just works" with `async` wherever it appears.
