### ISSUE TITLE
serilog configuration is too hard to use 

### ISSUE THREAD

**Issue by YINZHU2016** [serilog/serilog#1119]
Serilog configuration is very difficult to operate, particularly in the. Net core project, there are too many components configuration need to go to the configuration, but does not have a unified configuration can be used to study the best practices, I through Google, stackoverflow tools such as a large amount of data, also learn serilog official documentation, found that want to use appseting. The json data configuration way is trivial and multifarious,

I want to achieve a simple request, for example, I want to be according to the log level, the log is divided into multiple folders to store, and each file in folder is in accordance with the specific format, and so on, but I still didn't find the right information. Only a few bits and pieces of knowledge, does anyone know the best practices, or is the full configuration of the json configuration available? thank you

Please forgive my English is not very good.

**Comment by nblumhardt** [comment]
H!

Serilog configuration does not cover 100% of the Serilog API, so it's possible that what you want to achieve can't be done directly in configuration.

https://github.com/serilog/serilog-sinks-map can be used to split the destination for events based on level.

You might also find https://github.com/Suchiman/SerilogAnalyzer useful - it can generate XML and JSON configuration from code (see the demo GIF).

Hope this helps, and best of luck!
Nick

**Comment by YINZHU2016** [comment]
` Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("ProjectId", "xxx")
                .WriteTo.Console()
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information).WriteTo.File(@"Logs\Info\Info.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug).WriteTo.File(@"Logs\Debug\Debug.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Warning).WriteTo.File(@"Logs\Warning\Warning.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Error).WriteTo.File(@"Logs\Error\Error.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Fatal).WriteTo.File(@"Logs\Fatal\Fatal.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Verbose).WriteTo.File(@"Logs\Verbose\Verbose.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit))
                .CreateLogger();`

but i when i use SerilogAnalyzer ,there have some error like that

` /*
            Errors:
`l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information).WriteTo.File(@"Logs\Info\Info.log", outputTemplate: outputTemplateStr, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: fileSizeLimitBytes, rollOnFileSizeLimit: rollOnFileSizeLimit)` -> Can't statically determine value of expression

            "Serilog": {
              "Using": ["Serilog.Enrichers.Thread", "Serilog.Enrichers.Environment", "Serilog", "Serilog.Sinks.Console", "Serilog.Sinks.File"],
              "MinimumLevel": {
                "Default": "Debug",
                "Override": {
                  "System": "Warning",
                  "Microsoft": "Warning"
                }
              },
              "WriteTo": [
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Logger", "Args": { "configureLogger": "?" } },
                { "Name": "Console" },
                { "Name": "File", "Args": { "path": "Logs\\Info\\Info.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } },
                { "Name": "File", "Args": { "path": "Logs\\Debug\\Debug.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } },
                { "Name": "File", "Args": { "path": "Logs\\Warning\\Warning.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } },
                { "Name": "File", "Args": { "path": "Logs\\Error\\Error.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } },
                { "Name": "File", "Args": { "path": "Logs\\Fatal\\Fatal.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } },
                { "Name": "File", "Args": { "path": "Logs\\Verbose\\Verbose.log", "outputTemplate": "[{ProjectId}] {Level} {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{ThreadId}] [{MachineName}]{NewLine}{Message:lj}{NewLine}{Exception}", "rollingInterval": "Day", "fileSizeLimitBytes": "2048", "rollOnFileSizeLimit": "True" } }
              ],
              "Enrich": ["WithThreadId", "WithMachineName", "FromLogContext"],
              "Properties": {
                "ProjectId": "xxx"
              }
            }
            */`

**Comment by tsimbalar** [comment]
Hi @YINZHU2016 , 

I think the issue here is because you are using variables (`outputTemplateStr`, `fileSizeLimitBytes` etc ) in your configuration instead of directly using literals like `"a string"` or `15` ... and the analyzer cannot guess the value of those variables (it only has access to the code source, not the values) ... 

I'll close this issue for now to avoid side-tracking. If you find issues while using *SerilogAnalyzer*, feel free to open an issue in the corresponding repo : https://github.com/Suchiman/SerilogAnalyzer

**Comment by Neutrino-Sunset** [comment]
Imo the practice of putting the entire build up of the logging system into configuration is misguided. It results in a fragile implementation that requires deep understanding of the system's internals on the part of deployment teams to manage safely.

Far better to build up your logging system in code and just expose minimum configuration necessary that represents those aspects of your logging setup that it is actually useful and necessary to adjust.

The first implementation of our N-tier microservices architechture system using Serilog had 20 Serilog config files per customer installation (each installation consists of a main and backup server). This created workload, risk and cognitive overload for our ProdOps team. We've just refactored the whole thing to build up the logging system in code and just expose in the application's own appsettings.json file the half dozen values that it will be necessary for ProdOps to manage.

Just because you _can_ build your entire system in configuration doesn't mean you _should_.
