### ISSUE TITLE
can not customer can not use outputtemplate is use JsonFormatter

### ISSUE THREAD

**Issue by YINZHU2016** [serilog/serilog#1120]
I use Serilog.Sinks.RollingFile plug-in, then I use its JsonFormatter to format log data, but I find that I can't define outputTemplate. I define.Enrich.WithProperty ("ProjectId", "Myapp").

The log output is as follows:

```json
{"Timestamp": "2018-02-28T22:51:39.1809462+08:00", "Level": "Information", "MessageTemplate": "Carries property A = 1", "RenderedMessage": Carries property property = 1 "," "{" "{" "}}}"
```

But the format I want to output is

```json
{"Timestamp": "2018-02-28T22:51:39.1809462+08:00", "Level": "Information", "MessageTemplate": "Carries property A = 1", "RenderedMessage": Carries property property = 1 "," "}": "}"}.
```

ProjectId is formatted directly, not in the Properties property. Do you know how to do it? Thank you

my code 

```csharp
var json = new JsonFormatter();
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .Enrich.WithProperty("ProjectId", "HPA.IdentityServer.Web")
                .WriteTo.Console()
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information).WriteTo.RollingFile(json, @"Logs\Info\{Date}-Info.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug).WriteTo.RollingFile(json, @"Logs\Debug\{Date}-Debug.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Warning).WriteTo.RollingFile(json, @"Logs\Warning\{Date}-Warning.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Error).WriteTo.RollingFile(json, @"Logs\Error\{Date}-Error.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Fatal).WriteTo.RollingFile(json, @"Logs\Fatal\{Date}-Fatal.log"))
                .WriteTo.RollingFile(@"Logs\Verbose\{Date}-Verbose.log")
                .CreateLogger();
```

so i can not define outputTemplate param when i use jsonformat

thank you

**Comment by nblumhardt** [comment]
Hi Yin Zhu -

It doesn't look like your example output came through correctly; the _log output is as follows_ example is not valid JSON, and does not seem to include anything about the `ProjectId` property.

Is it possible to post an updated example?

Best regards,
Nick

**Comment by YINZHU2016** [comment]
//const string outputTemplateStr = "{ProjectId} [{Level}] {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {NewLine} {Message<>} {NewLine} {Exception}";
            var json = new JsonFormatter();
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .Enrich.WithProperty("ProjectId", "HPA.IdentityServer.Web")
                .WriteTo.Console()
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information).WriteTo.RollingFile(json, @"Logs\Info\{Date}-Info.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug).WriteTo.RollingFile(json, @"Logs\Debug\{Date}-Debug.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Warning).WriteTo.RollingFile(json, @"Logs\Warning\{Date}-Warning.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Error).WriteTo.RollingFile(json, @"Logs\Error\{Date}-Error.log"))
                .WriteTo.Logger(l => l.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Fatal).WriteTo.File(json, @"Logs\Fatal\{Date}-Fatal.log"))
                .WriteTo.RollingFile(@"Logs\Verbose\{Date}-Verbose.log")
                .CreateLogger();
this example will log like 
{"Timestamp":"2018-02-28T22:51:39.6992323+08:00","Level":"Debug","MessageTemplate":"Starting token cleanup","RenderedMessage":"Starting token cleanup","Properties":{**"ProjectId":"HPA.IdentityServer.Web"**}}

but i want the ProjectId out of Properties just like

{"Timestamp":"2018-02-28T22:51:39.6992323+08:00","Level":"Debug","MessageTemplate":"Starting token cleanup","RenderedMessage":"Starting token cleanup",**"ProjectId":"HPA.IdentityServer.Web"**}

**Comment by nblumhardt** [comment]
Using `RenderedCompactJsonFormatter` from https://github.com/serilog/serilog-formatting-compact, instead of `JsonFormatter`, will do what you're looking for.
