### ISSUE TITLE
How to not append date to log file?

### ISSUE THREAD

**Issue by scorpion35** [serilog/serilog#1123]
Hello,

Thank you for making this work with .NET Core, and it's very easy to configure!

One issue I have is the not having the ability to choose my own file name. Do you know if there is a way to do that? Please see my code below, 

```C#
using Serilog;
using Serilog.Sinks.File;
using Serilog.Sinks.RollingFile;
using Serilog.Sinks.SystemConsole;

// Logger
var outputTemplate = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u4}] | {Message:l}{NewLine}{Exception}";
var Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console(outputTemplate: outputTemplate)
                .WriteTo.File("logs/log-.log",
                              outputTemplate: outputTemplate,
                              rollingInterval: RollingInterval.Day)
                .CreateLogger();
Logger.Debug("Created logger...");
```

It creates the log files like, `logs/log-20180303.log`. I want something like, 
```
 logs/log-2018-02-05-17-46-32.log
 logs/log-2018-02-05-17-49-48.log
 logs/log-2018-01-29-17-27-40.log
```

My code will be run multiple times per day, and we don't want the subsequent log lines to be appended to one file for the entire day. I would like to make a new log file for each run. If I specify `RollingInterval.Minute`, it is creating a new log for every minute; which is not what I am looking for either.

Any help is greatly appreciated!! Thanks in advance.

**Comment by nblumhardt** [comment]
Hi! If you want a file-per-run, but still have some option to avoid large files, you might try:

```csharp
                .WriteTo.File($"logs/log-{DateTime.Now:yyyy-MM-dd_HH:mm:ss}.log",
                              outputTemplate: outputTemplate,
                              fileSizeLimitBytes: 100_000_000,
                              rollOnFileSizeLimit: true)
```

It won't roll automatically at 12 midnight, but seems like it'd be better aligned with what you're after. HTH!

**Comment by scorpion35** [comment]
@nblumhardt Thank you for response!! 

I have tried specifying my own file name with custom datetime specifiers this morning. Unfortunately, it is creating multiple log files per every second it seems. 

<img width="1111" alt="log" src="https://user-images.githubusercontent.com/18679225/36952448-441567fc-1fde-11e8-82df-24e403e9fb57.png">

I would like to have one log file for the whole session!

**Comment by nblumhardt** [comment]
Just realised looking at your screenshot, it's not such a good idea for me to have included `:` in the generated filenames :-) - `DateTime.Now:yyyy-MM-dd_HH-mm-ss` should be a bit better-behaved.

It sounds like you might be creating a logger each time you write a log message - could that be the case? If so - you need to use the same logger for the whole duration of the program (only call `CreateLogger()` once per program run).

HTH

**Comment by scorpion35** [comment]
Everything fine now! Thank you!!

**Comment by malcolmjerry** [comment]
private readonly Serilog.ILogger _logger; //= Log.ForContext( "Name", "Weather" );

    public WeatherForecastController() {
      string subPath = Path.Combine( DateTime.Now.ToString( "yyyy" ), DateTime.Now.ToString( "MM" ) ) + $"/{DateTime.Now.ToString("dd")}_Weather";
      _logger = Log.ForContext( "Name", subPath );
    }

...........................................

      .UseSerilog( ( hostingContext, loggerConfiguration ) => loggerConfiguration
        .ReadFrom.Configuration( hostingContext.Configuration )
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .WriteTo.Map(
          "Name",
          "Request",
          ( name, wt ) => {
            if (name == "Request")
              wt.RollingFile( Path.Combine( $"{hostingContext.Configuration["LogPath"]}/{{Date}}-{name}.txt" ) );
            else
              wt.File( $"{hostingContext.Configuration["LogPath"]}/{name}.txt" );
          } )
      );
