### ISSUE TITLE
Cleanup of nuget package metadatas in serilog projects

### ISSUE THREAD

**Issue by LordMike** [serilog/serilog#1126]
Hello,

Following the discussion here, https://github.com/serilog/serilog-sinks-email/pull/49, I made a tool to extract information about nuget packages from nuget.org, and output them to JSON, which I've then imported to excel. This allows a quick overview of the packages and their metadata, so that we can quickly identify the things to fix.

_Note: I've only searched for [owner:serilog](https://www.nuget.org/packages?q=owner%3Aserilog&prerel=false) packages on nuget._

The table is huge, so I can't attach it here as markdown, but it's attached as attachments.

[Overview.xlsx](https://github.com/serilog/serilog/files/1782036/Overview.xlsx)
[OverviewData.zip](https://github.com/serilog/serilog/files/1782037/OverviewData.zip)

The things I imagine need fixing are:

* [ ] **Description** -- by default, packages will have "Package description" as description. This goes directly under the title on nuget.  [Example](https://www.nuget.org/packages/Serilog.Sinks.Elasticsearch)

* [ ] **Age** -- some of these packages are really old (2015) - perhaps unlist them ([relevant issue](https://github.com/NuGet/Home/issues/2867)) or similar, if they're deprecated? Alternatively, bring all packages up to date to reference current serilog editions and target `.NET Framework` and `.NET Standard` accordingly.

* [ ] **Icon Url** -- Ensure all packages use one of the 7 icons available - two packages use HTTPS urls, so I assume thats the _new thing_? If so, then all packages should use the HTTPS urls. (that last part will benefit nuget.org, as they currently get mixed-content warnings, [example](https://www.nuget.org/packages/Serilog.Sinks.Elasticsearch)). 

* [ ] **License Url** -- These should point to HTTPs where able, to help nuget.org with their site buildup. One package has no license: [example](https://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDB)

* [ ] **Project Url** -- From the discussion on the email sink, all project urls should use HTTPS - additionally, for those able to, they should point the github page for that specific sink/extension - and not Serilog.net (this is always useless, IMO, as I click the project link to get details about *this* package, and not how awesome the project is).

* [ ] **Repository Url** -- It sems that [Nuget](https://github.com/NuGet/NuGetGallery/issues/4941) is considering showing the repository in the gallery. If set to be used, you can take advantage of the msbuild target for packing, to include not just the repo url, but also the commit hash. [Commit hash issue](https://github.com/NuGet/Home/issues/6547), [pack target properties](https://github.com/emgarten/docs.microsoft.com-nuget/blob/patch-1/docs/reference/msbuild-targets.md#pack-target) -- it should work like this `dotnet pack /p:Repository/Url=XYZ /p:Repository/Commit=ABC`

* [ ] **Tags** -- Unsure what the structure should be. Nuget says its _"[..] describe the package and aid discoverability of packages through search and filtering."_. I assume that all serilog packages should include `serilog` and `logging`, and sinks could then include `sinks` while they all include their specific implementation, such as `elasticsearch`, `es`, `mail`, `file` etc. Currently it's very inconsistent - ElasticSearch has `collector` and `event` while very few other packages have this even though they seem like they should.

* [ ] **Target frameworks** -- Ideally, all packages would specify a `.NET Framework` and `.NET Standard` target with associated dependencies. I'm uncertain if there should be a `.NET Standard` for `1.x` and `2.x`, it seems to "depend". IMO, if a package supports all frameworks, it should explicitly say so, even though it's possible to avoid specifying this. An example, [Serilog.Sinks.AmazonKinesis](https://www.nuget.org/packages/Serilog.Sinks.AmazonKinesis), shows it supports ALL frameworks, but that's not true - [Serilog](https://www.nuget.org/packages/Serilog/) supports Framework and Standard, while [AWSSDK](https://www.nuget.org/packages/AWSSDK.Core/) supports a whole bunch of targets... The result is that this package can only ever work on Net Framework and Standard - not UAP, Mono Android or Xamarin...

* [ ] **Sourcelink** -- it's my impression that *no packages* in serilog support [Sourcelink v2](https://github.com/ctaggart/SourceLink) - this version of sourcelink will allow a developer to seamlessly step into code provided through nuget packages (pdb's actually), without embedding the code in the Symbols package itself. The code is hosted directly on Github, and references through a "raw" link to the file at its specific commit hash. This works best with CI/CD build systems, and I'm not sure how Serilog is built currently.

**Comment by tsimbalar** [comment]
Wow, that's a very thorough and exhaustive analysis, thanks ! Thanks also for linking to the less-known features of nuget packing, I'm discovering quite a few things here :) 

Indeed it would be nice to have more homogenity and consistency across the ecosystem. I am all in favor of fixing the little quirks like https icon links, licences, tags and other simple static metadata (maybe opening an issue "up-for-grab" in each one of the correspounding repos ?). 

My personal opinion is that the more "advanced" fixes that involve changing the build are probably more expensive, and it may be hard to find time to tackle them on ALL repos (not all repos are built exactly the same way). I think it is fair to try and make the most used `Serilog.*` packages as *good* as possible so that they can be a good example to lead the way of the rest of the repos ... 

Also, would those changes justify publishing a new version of the package ? 

I'm pretty sure the rest of @serilog/reviewers-core will have an opinion :)

**Comment by LordMike** [comment]
I've also discovered (although I should've known) that the properties for packing can also be set in the `PropertyGroup` .. group in the csproj file. I suspect that it still makes sense to specify commit id through the command line ... :P ([example - json.net](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L24-L25)) -- do note that Json.net's RepositoryUrl is not [up to spec - see RepositoryUrl example](https://github.com/emgarten/docs.microsoft.com-nuget/blob/patch-1/docs/reference/msbuild-targets.md#pack-target).

I would also recommend setting a lot of these options and settings using import files (aka "props"). These are put in the csproj using an `Import` ([docs](https://msdn.microsoft.com/da-dk/library/92x05xfs.aspx)) element and will in-place put in whatevers in the references file.

Common stuff such as License and icons (one props file pr. type of project f.ex.), common tags (you can later add to tags by writing f.ex. `<PackageTags>$(PackageTags) tag_new tag_new2</PackageTags>` (and eventually, sourcelink) could very well fit into imports.

**Comment by nblumhardt** [comment]
Does anyone have any idea how we might move this one towards a mangeable set of changes/PRs? It looks like we've stalled a bit here because the amount of work seems unbounded...

**Comment by merbla** [comment]
Perhaps we just start with an issue per repo/package? I can start spitting them out from @LordMike awesome analysis.

**Comment by danielchalmers** [comment]
I think this was closed by accident with #1163. Should it be reopened?

**Comment by nblumhardt** [comment]
Thanks for the nudge, @danielchalmers - no, we're not currently pushing this forward, but it might be nice to return to someday :-)
