### ISSUE TITLE
LogContext forgets pushed properties that are not disposed

### ISSUE THREAD

**Issue by ivankoster** [serilog/serilog#1130]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.6.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0

**Please describe the current behavior?**
Here is a minimal reproduce scenario

```

using System;
using System.Threading.Tasks;
using Serilog;
using Serilog.Context;

namespace SerilogAsyncLocalBug
{
    class Program
    {
        static void Main(string[] args)
        {
            AsyncMethod1().Wait();
        }

        private static async Task AsyncMethod1()
        {
            var log = new LoggerConfiguration()
                            .Enrich.FromLogContext()
                            .WriteTo.Console(
                                outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} A:{A} B:{B}] {Message:lj}{NewLine}{Exception}")
                            .CreateLogger();

            log.Information("No contextual properties");

            var disposable1 = LogContext.PushProperty("A", 1);
            log.Information("Carries property A = 1");
            IDisposable disposable2 = await AsyncMethod2(log);
            log.Information("This should carry A = 1 and B = 1, but property B is gone");

            disposable2.Dispose();
            log.Information("Carries property A = 1, again");

            disposable1.Dispose();
            log.Information("No contextual properties");

            log.Dispose();
        }

        private static async Task<IDisposable> AsyncMethod2(Serilog.Core.Logger log)
        {
            await Task.Delay(50);
            var disposable2 = LogContext.PushProperty("B", 1);
            log.Information("Carries A = 1 and B = 1");
            return disposable2;
        }
    }
}

```

**Please describe the expected behavior?**
I expect the properties to be only gone after the corresponding disposable is disposed. Currently they are gone after awaiting the task that pushed the property. This is probably an AsyncLocal<> issue.

**Comment by tsimbalar** [comment]
Just adding the conversation we had in gitter 
```text
Ivan Koster
@ivankoster
16:55
Hello. I found some LogContext behaviour that is completely unexpected to me. I have a minimal reproduce example below. Is this a bug? Is this intended?

using System;
using System.Threading.Tasks;
using Serilog;
using Serilog.Context;

namespace SerilogAsyncLocalBug
{
    class Program
    {
        static void Main(string[] args)
        {
            AsyncMethod1().Wait();
        }

        private static async Task AsyncMethod1()
        {
            var log = new LoggerConfiguration()
                            .Enrich.FromLogContext()
                            .WriteTo.Console(
                                outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} A:{A} B:{B}] {Message:lj}{NewLine}{Exception}")
                            .CreateLogger();

            log.Information("No contextual properties");

            var disposable1 = LogContext.PushProperty("A", 1);
            log.Information("Carries property A = 1");
            IDisposable disposable2 = await AsyncMethod2(log);
            log.Information("This should carry A = 1 and B = 1, but property B is gone");

            disposable2.Dispose();
            log.Information("Carries property A = 1, again");

            disposable1.Dispose();
            log.Information("No contextual properties");

            log.Dispose();
        }

        private static async Task<IDisposable> AsyncMethod2(Serilog.Core.Logger log)
        {
            await Task.Delay(50);
            var disposable2 = LogContext.PushProperty("B", 1);
            log.Information("Carries A = 1 and B = 1");
            return disposable2;
        }
    }
}

It is completely unexpected, because the documentation and examples explicitly states that you have to dispose the objects coming from LogContext.PushProperty(...)
now my properties are gone while i haven't disposed yet
---------------
Thibaud Desodt
@tsimbalar
16:58
does it change anything if you use using blocks instead of disposing yourself ?
also does it change anything if you use an async main method to start with ? (C# 7.1)
anyway, I think it is worth creating an issue on the main serilog repo to track this one done
whether it is a bug or not, it is tricky enough to have a persistent track of this one :grinning:
-----------
Ivan Koster
@ivankoster
17:04
I just added using blocks, but it doesnt change anything as using() is just syntactic sugar.

private static async Task AsyncMethod1()
        {
            var log = new LoggerConfiguration()
                            .Enrich.FromLogContext()
                            .WriteTo.Console(
                                outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} A:{A} B:{B}] {Message:lj}{NewLine}{Exception}")
                            .CreateLogger();

            log.Information("No contextual properties");

            using (var disposable1 = LogContext.PushProperty("A", 1))
            {

                log.Information("Carries property A = 1");
                using (var disposable2 = await AsyncMethod2(log))
                {
                    log.Information("This should carry A = 1 and B = 1, but property B is gone");
                }

                log.Information("Carries property A = 1, again");
            }

            log.Information("No contextual properties");

            log.Dispose();
        }
------------
Thibaud Desodt
@tsimbalar
17:05
@ivankoster Interesting ... ("interesting" as in "dammit, that's strange _") ... Definitely worth opening an issue
(also thanks for a great repro _)
-----------
Ivan Koster
@ivankoster
17:05
async main doesn't change anything, just tested it
I guess it will be an AsyncLocal<> issue in LogContext
```

**Comment by nblumhardt** [comment]
Hey folks!

`LogContext` is a stack - so it needs to be pushed/popped in order. If you skip the top-level element and instead pop something half-way down the stack, this will pop everything above it, by design.

If you have  slightly different use case, implementing an `ILogEventEnricher` that uses its own `AsyncLocal<T>` storage should cover it.

Let me know if I'm off track :-)

Cheers,
Nick

**Comment by tsimbalar** [comment]
Hi Nick,

I believe they are pushed/popped in order in the repro, actually :p 

I see that the order is : 
1. Push A 
2. (Async) WAIT
3. (Async) Push B
4. disposable2.Dispose() (= Pop B)
5. disposabe1.Dispose() (= Pop A)

Or am I missing some asumption here ?

**Comment by nblumhardt** [comment]
Ah, sorry, I misread the code 👍 

I think this probably stems from the tree-like nature of `AsyncLocal` - child tasks inherit the async local state, but it's copy-on-write so changes don't flow back up to the parent task.

It's been a while since I dug around in here so I could again be missing something entirely, but my current guess is that this is "expected behavior" for `AsyncLocal` and not something we necessarily want to try working around in Serilog. Happy to help dig into it further if anyone has an alternative interpretation :-)

**Comment by ivankoster** [comment]
yes, as far as i know you are right on AsyncLocal<> behaviour. But since the Logcontext enricher uses the dispose pattern, i expected it to work like described in this issue.
After a little more thought, if it would work like that, flowing properties back to the parent, you would have a interesting case when a task spawns multiple children and they also push properties to the context. Which properties to keep in the parent? All of them? Should the child tasks share the properties? I'm not sure if you want to change these behaviors for Serilog.Logcontext. Maybe a separate SynchronzedLogcontext is needed, with different semantics.

**Comment by skomis-mm** [comment]
I would add that this behavior is the result of `AsyncLocal` usage and immutable stack as its storage. So when `AsyncLocal` restores its state when leaving the method it restores snapshot of the stack it have. 
If the stack was mutable it would produce \*desired\* behavior but also could mess things up such as one async context would observe changes in another since copies of the async local state are shallow.

**Comment by tsimbalar** [comment]
I am kind of wondering then, if the behavior is the same between .NET 4.5.* and .NET 4.6+/.NET Core ... since 
- .NET 4.5.* relies on Remoting/`CallContext`
- .NET 4.6+ / .NET Core relies on `AsyncLocal<>`

I read here https://stackoverflow.com/a/31708169/474763 that they have a different behavior : 

> Technically, there's a big difference in the implementation as the CallContext is cloned each time it is copied (using CallContext.Clone) while the AsyncLocal's data is kept in the ExecutionContext._localValues dictionary and just that reference is copied over without any extra work.

I'm kind of confused around all that, so sorry or the dumb/irrelevant comment :)

**Comment by ivankoster** [comment]
I have made two examples that make it obvious that in .net code 2.0 AsyncLocal makes a copy of the data for each task, and that it doesn't flow back changes:
```
using System;
using System.Threading;
using System.Threading.Tasks;

namespace SerilogAsyncLocalBug
{
    class Program
    {
        private static readonly AsyncLocal<string> AsyncLocalWithOverwrite = new AsyncLocal<string>();

        static async Task Main(string[] args)
        {
            await AsyncMethod1();
            Console.WriteLine($"No contextual properties. LocalProperties.Value == null = {AsyncLocalWithOverwrite.Value == null}"); // localProperties.Value throws NullReferenceException here
        }

        private static async Task AsyncMethod1()
        {
            Console.WriteLine($"No contextual properties. LocalProperties.Value == null = {AsyncLocalWithOverwrite.Value == null}"); // localProperties.Value throws NullReferenceException here

            AsyncLocalWithOverwrite.Value = "A=1";
            Console.WriteLine($"Carries property A = 1: {AsyncLocalWithOverwrite.Value}");

            await AsyncMethod2();
            Console.WriteLine($"Carries A = 1: {AsyncLocalWithOverwrite.Value}");
        }

        private static async Task AsyncMethod2()
        {
            await Task.Delay(50);
            AsyncLocalWithOverwrite.Value = "A=1, B=1";
            Console.WriteLine($"Carries A = 1 and B = 1 {AsyncLocalWithOverwrite.Value}");
        }
    }
}
```
Of course, using a mutable referenced class, and changing that, does flow back changes to the parent:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace SerilogAsyncLocalBug
{
    class Program
    {
        private static readonly AsyncLocal<List<string>> AsyncLocalWithReference = new AsyncLocal<List<string>>();

        static async Task Main(string[] args)
        {
            await AsyncMethod1();
            Console.WriteLine($"No contextual properties. LocalProperties.Value == null = {AsyncLocalWithReference.Value == null}"); // localProperties.Value throws NullReferenceException here
        }

        private static async Task AsyncMethod1()
        {
            Console.WriteLine($"No contextual properties. LocalProperties.Value == null = {AsyncLocalWithReference.Value == null}"); // localProperties.Value throws NullReferenceException here

            AsyncLocalWithReference.Value = new List<string> {"A=1"};
            Console.WriteLine($"Carries property A = 1: {AsyncLocalWithReference.Value.Aggregate((a, b) => a + b)}");

            await AsyncMethod2();
            Console.WriteLine($"Carries A = 1 and B = 1: {AsyncLocalWithReference.Value.Aggregate((a, b) => a + b)}");
        }

        private static async Task AsyncMethod2()
        {
            await Task.Delay(50);
            AsyncLocalWithReference.Value.Add("B=1");
            Console.WriteLine($"Carries A = 1 and B = 1 {AsyncLocalWithReference.Value.Aggregate((a, b) => a + b)}");
        }
    }
}
```

**Comment by nblumhardt** [comment]
:+1: thanks for all of the extra info @ivankoster.

I think the way to look at this is that `LogContext` isn't so much a "disposable-based API" as a scope-based one. You can't, for example, take that `IDisposable` and pass it over to another thread and assume anything sensible will result. `using` is the primary scenario we're targeting, and beyond that some knowledge of the `async` machinery is going to be required. "Fixing" this would mean somehow reinventing TPL, I think.

Voting "close"/"by design" :-)

**Comment by skomis-mm** [comment]
@tsimbalar I believe behavior is the same for `4.5` and `4.6 / .net core` in this context, because CallContext works across await points since 4.5 like `AsyncLocal`, so the main difference in implementation details as pointed in SO answer.
But for .net 4.0, for example, with `Microsoft.BCL.Async` the behavior would be defferent since  `CallContext` would not work across await points

**Comment by tsimbalar** [comment]
@nblumhardt I'm fine with letting it "as is" ... I'm glad this issue  showed up, I learnt a few things here :) :+1: 

@skomis-mm  thanks for clarifying :+1:
