### ISSUE TITLE
Dynamic or Environment-aware configuration is difficult or not documented

### ISSUE THREAD

**Issue by lukos** [serilog/serilog#1131]
Serilog 2.6.0, AzureTableStorage 4.0.0, AppSettings 2.1.2
.Net 4.6.1 Web Api running on Windows/Azure App Services

This relates to what I think is a normal scenario that doesn't appear to be supported/obvious, in part due to the way some sinks fully support config-driven setup and others that don't. It also appears that an early decision was to use code over configuration.

* I want a file log for development purposes: This works fine driven directly from configuration (AppSettings).
* I want an AzureTableStorage sink for production which should be enabled or disabled in real-time since it will be used for Verbose fault-finding but will produce too much data to be left switched on. This does not seem to support completely config-driven setup since the connection string is not a named parameter.
* I will eventually want another sink but let's not go there now!

Because I cannot setup the AzureTableStorage in config only (which would allow me to add or move AppSettings and restart to enable/disable), I have to manually extract the connection string as a normal app setting and write code to do this in Application_Start but I don't want this to always be present (unless I can add it disabled, which is weird but acceptable).

What is difficult is building the loggers dynamically/only if their config is present in AppSettings. There don't seem to be any methods to chain the creation of the loggers conditionally something like: 
```C#
var logger1 = WriteTo.File(); 
var logger2 = WriteTo.TableStorage(); 
Log.Logger = Combine(logger1 , logger2) 
// or
Log.Logger = logger1.CreateLogger(); 
Log.Logger.AddAnotherLogger(logger2.CreateLogger())
```

I've tried to create a list of LoggerConfiguration but cannot see how to join them together dynamically afterwards. I cannot call logger2.WriteTo.Logger(logger1) for each item in the list since Logger() requires Action<LoggerConfiguration> rather than LoggerConfiguration. This is also less than ideal because sub loggers are filtered by their parent loggers which would make it quite restrictive.

I love the fact that there are loads of Sinks for Serilog, which is the only reason I am considering it but dynamic setup is kind of a major requirement to move forwards. Can anyone help? Thanks.

**Comment by tsimbalar** [comment]
Hi Luke,

not sure I completely get it, but let's try :)

I believe you can configure *AzureTableStorage* also via the appsettings, passing the arguments to call the method: 
```csharp
public static LoggerConfiguration AzureTableStorage(
            this LoggerSinkConfiguration loggerConfiguration,
            string connectionString,
            LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
            IFormatProvider formatProvider = null,
            string storageTableName = null,
            bool writeInBatches = false,
            TimeSpan? period = null,
            int? batchPostingLimit = null,
            IKeyGenerator keyGenerator = null)
{
```
(see https://github.com/serilog/serilog-sinks-azuretablestorage/blob/878ee019dfb5cfc5d2ddd9726d88c0b28aeece8f/src/Serilog.Sinks.AzureTableStorage/LoggerConfigurationAzureTableStorageExtensions.cs#L104-L113 )

You could probably load everything from the `<appSettings>` if it looks like this : 

```xml
<!-- global minimum level of serilog-->
<add key="serilog:minimum-level" value="Information" />
<!-- writing to file -->
<add key="serilog:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:File.path" value="log.txt" />
<!-- writing to Azure Table Storage -->
<add key="serilog:using:AzureTableStorage" value="Serilog.Sinks.AzureTableStorage" />
<add key="serilog:write-to:AzureTableStorage.connectionString" value="TheConnectionString" />
<add key="serilog:write-to:AzureTableStorage.restrictedToMinimumLevel " value="Fatal" />
```

And in your code, calling `.ReadFrom.AppSettings()` as usual ... 

Configuring the *AzureTableStorage* sink with `serilog:write-to:AzureTableStorage.restrictedToMinimumLevel` `Fatal` mostly remove all the noise from *AzureTableStorage*. While not technically disabled, in most scenarios, it's close enough ! And you can change the value later on when you actually need all the noise ...


Anoter option is to use `.ReadFrom.AppSettings(string settingPrefix)` to load the config in 2 shots and do something like : 

```csharp
var logConfig = new LoggerConfiguration
                .ReadFrom.AppSettings(); // load the serilog:* settings

bool azureTableStorageIsEnabled = ReadValueFromConfigSomewhere();
if( azureTableStorageIsEnabled ){
    logConfig = logConfig.ReadFrom.AppSettings("azureTableStorage"); // load the azureTableStorage:serilog:* settings
}

Log.Logger = logConfig.CreateLogger();
```

and have a config file like this one : 

```xml
<add key="enableAzureTableStorageLogs" value="true" />
<!-- global minimum level of serilog-->
<add key="serilog:minimum-level" value="Information" />
<!-- writing to file -->
<add key="serilog:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:File.path" value="log.txt" />
<!-- writing to Azure Table Storage -->
<add key="azureTableStorage:serilog:using:AzureTableStorage" value="Serilog.Sinks.AzureTableStorage" />
<add key="azureTableStorage:serilog:write-to:AzureTableStorage.connectionString" value="TheConnectionString" />
```

I hope this helps :)

You can find more details about the syntax for the configuration formats in here : 
- [*Serilog.Settings.AppSettings*'s repo](https://github.com/serilog/serilog-settings-appsettings)
- A list of examples of configuration here : https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md

**Comment by lukos** [comment]
Thank @tsimbalar I shall give this a go! I'll close for now and raise a more specific issue if this doesn't work.
