### ISSUE TITLE
Event logging does using {Age} works with int? Age

### ISSUE THREAD

**Issue by no1melman** [serilog/serilog#1132]
When trying to log out using

    logger.Information("Here is his age: {Age}", somePersons.Age.Value);

Does that work, or does the `{Age}` need to be `{Value}` ?

**Comment by tsimbalar** [comment]
That works. It will attach a property named `Age`containing the value of `somePersons.Age.Value`. If Value is a simple type like an `int` it will be attached directly without extra steps.

In the *message template*, the text between the `{` `}` is the name of the property that will be attached to the event. As it is the first *token* in the message template, the value will be the first parameter passed afterwards, no matter its name.

You can read more about *Message Template Syntax* [in the wiki ](https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-syntax).
Note that installing [*SerilogAnalyzers*](https://github.com/Suchiman/SerilogAnalyzer) can  also be a great help to validate your usage of the logging methods.
