### ISSUE TITLE
Loging byte array smaller than 1 Kb

### ISSUE THREAD

**Issue by neman** [serilog/serilog#1133]
What is expected behavior for logging byte arrays smaller then 1 Kb?

When the file is smaller than 1 Kb I got value `"System.Byte[]"`. When the file is bigger than 1 Kb I got descriptive value, `"255044462D312E370D0A25B5B5B5B50D... (2296396 bytes)"`, which is fine 

I taught that smaller than 1 Kb values should be logged as complete value? Am I doing something wrong?

![image](https://user-images.githubusercontent.com/350314/37410695-6c7f4d6e-27a1-11e8-9fdc-8cb7a87b929b.png)
![image](https://user-images.githubusercontent.com/350314/37410747-8d6f9c2c-27a1-11e8-857c-6c1af5ea6a86.png)

**Comment by nblumhardt** [comment]
This looks like a bug/regression - the intention is that a small `byte[]` will be logged as an array of numbers, just like we'd do for an `int[]`. Thanks for the report - needs looking into :+1:

**Comment by mihaivader** [comment]
Hi,

I'm having the same issue.
What I have is byte[8] (it's an SQL Timestamp) that I want to serialize as a string.

Thanks

**Comment by Pliner** [comment]
@nblumhardt I tried to find version when it worked as expected, but I'm failed: all minor versions from 1.4 to 2.6 output small byte[] as System.Byte[]. 😢 

Also I found the reason: ScalarValue was [created](https://github.com/serilog/serilog/blob/dev/src/Serilog/Policies/ByteArrayScalarConversionPolicy.cs#L45) from byte[] and later [rendered](https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/ScalarValue.cs#L96) by calling ToString on byte[].

Is hex representation ok? If it is ok I can fix this issue 😜

**Comment by nblumhardt** [comment]
Hey @Pliner, thanks for the offer! Could have to go back as far as 1.0 (or earlier) to find this working :-(

I'm open to using hex for all sizes - assuming that is what we use for larger values already, given the output above, so :+1: from me.
