### ISSUE TITLE
Logging JObject results in a bunch of brackets

### ISSUE THREAD

**Issue by jonathann92** [serilog/serilog#1135]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.7.1-dev-00960

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0

**Please describe the current behavior?**
When I try to log a JObject it will log brackets instead of the Key value pairs.
This is what it looks like:
[21:34:27 INF] [[[]], [[]]]

**Please describe the expected behavior?**
I expect it to log the json object with key value pairs

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the 

```
           Log.Logger = new LoggerConfiguration()
                        .MinimumLevel.Information()
                        .WriteTo.Console()
                        .CreateLogger();

            var jobject = new JObject
            {
                ["FirstName"] = "Foo",
                ["LastName"] = "Bar"
            };

            Log.Information("{@jobject}", jobject);

            Log.CloseAndFlush();
```

**Comment by tsimbalar** [comment]
Hi Jonathan,

did you try using the nuget package [Destructurama.JsonNet](https://www.nuget.org/packages/Destructurama.JsonNet/) (repo : https://github.com/destructurama/json-net) ?

It adds support for destructuring [JSON.NET](https://www.newtonsoft.com/json)'s types.

**Comment by jonathann92** [comment]
Hi yeah I just tried it and it works! Thank you!
