### ISSUE TITLE
Obfuscate sensitive data when serializing to JSON

### ISSUE THREAD

**Issue by omora-RA** [serilog/serilog#1138]
Is there a way to obfuscate properties when Serilogs prints event logs?

For instance, given an object with a sensitive property "SSN":

> var person = new Person{Name = "John Doe", SSN = "1234567890"};
> Log.Logger.Information("Person {@person}", person);

I would like to see "SSN" = "****" when the value is serialized or suppressing the property altogether would be fine too.

**Comment by skomis-mm** [comment]
@omora-RA see [this](https://github.com/destructurama/by-ignoring), [this](https://github.com/destructurama/attributed)

**Comment by omora-RA** [comment]
@skomis-mm that library worked great. @nblumhardt have you considered making the ignore property destructure policy part of Serilog?

**Comment by nblumhardt** [comment]
Not at present, though it'd be great in the short term if we could make extensions like these more discoverable. Thanks for the feedback @omora-RA .
