### ISSUE TITLE
Log file being locked.

### ISSUE THREAD

**Issue by imxzjv** [serilog/serilog#1139]
- [x] Bug?
- [x] netCore 2.0

```
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.6.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
```

**Current behavior**

Log file remains open and locked when run on IIS by .Net process. (`Shared`  true/false doesn't seem to make a difference). FTP download results in Response:	550 The process cannot access the file because it is being used by another process. 

**Expected behavior**

Log file should be downloadable via FTP to be viewed. I need to able to view logs created on production without having to recycle the app pool or use a non-file based option like XSockets etc.

I tested NLog and the same issue exists but only when `keepFileOpen=true` - when set to `false` then files can be accessed. Is there a similar setting in Serilog that i have missed perhaps?

**Comment by nblumhardt** [comment]
Hi, and thanks for getting in touch!

This doesn't sound so much like a problem with file sharing, as with your FTP client; Serilog's file logger allows other processes to read and write to the file, but any that try to take an *exclusive* lock will fail.

This is the situation that `keepFileOpen=true` is working around; we don't currently have an alternative in Serilog - it's not an undesirable feature, but AFAIK it has a pretty heavy performance overhead so no one has looked at it in earnest so far.

**Comment by imxzjv** [comment]
Alright! thanks for the response.

**Comment by nblumhardt** [comment]
:+1:

**Comment by kkarakk** [comment]
> 
> 
> Hi, and thanks for getting in touch!
> 
> This doesn't sound so much like a problem with file sharing, as with your FTP client; Serilog's file logger allows other processes to read and write to the file, but any that try to take an _exclusive_ lock will fail.
> 
> This is the situation that `keepFileOpen=true` is working around; we don't currently have an alternative in Serilog - it's not an undesirable feature, but AFAIK it has a pretty heavy performance overhead so no one has looked at it in earnest so far.

is this mentioned anywhere in the docs? serilog seems quite useless for file based logging when you consider this usecase...have to stop the app to access the logs.

**Comment by CADbloke** [comment]
Adding this in case it helps anyone, my log files were being locked by goddam Visual Studio when I built project, I presume it was the XAML editor newing up stuff it thinks it needs to build the XAML preview. I noticed it writing to the log file when the app (which runs in AutoCAD) wasn't even open. fyi I use https://github.com/RolandPheasant/TailBlazer to watch the logs.

**Comment by sixeyes** [comment]
In our case we're using an Azure Web App (IIS) and FileZilla to download files.

If we can't download a logfile without stopping the application, serilog isn't going to work for us.

Any suggestion as to how to work around this?

**Comment by filmico** [comment]
I know it may sound a little awkward but as a workaround, you can copy the log files to another folder in the same server and download/delete those as you wish. If you have control over that server you can script some batch script that uses robocopy

**Comment by sixeyes** [comment]
Thanks for your answer. In the end we switched from files to Azure table storage, so no more file locking.
