### ISSUE TITLE
Sink Request - Prometheus

### ISSUE THREAD

**Issue by tomkerkhove** [serilog/serilog#1140]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

Are there plans to add a sink for Prometheus? Either be it by exposing a scraping endpoint or simply pushing to a pushgateway?

**Comment by nblumhardt** [comment]
Thanks for the note! No, we're not actively adding sinks into the Serilog core project, but would happily support any community effort to create a Prometheus sink. Dropping into https://gitter.im/serilog/serilog is worthwhile if you decide to give it a go and need any help. Cheers!

**Comment by tomkerkhove** [comment]
Thank you for the update! Actually I created it in the wrong repo and should've been for the metrics but ok :)

Thank you for the quick response!

**Comment by nblumhardt** [comment]
Cool :) :+1:
