### ISSUE TITLE
Add Suave.SerilogExtensions to the list of community projects

### ISSUE THREAD

**Issue by Zaid-Ajaj** [serilog/serilog#1142]
Logging for [Suave](https://github.com/SuaveIO/suave) (F# web framework) with Serilog :smile:

Repo here [Suave.SerilogExtensions](https://github.com/Zaid-Ajaj/Suave.SerilogExtensions)

**Comment by nblumhardt** [comment]
Done! https://github.com/serilog/serilog/wiki/Community-Projects/

Thanks @Zaid-Ajaj
