### ISSUE TITLE
Should enrichers be thread-safe?

### ISSUE THREAD

**Issue by krajek** [serilog/serilog#1144]
I have analyzed the Serilog code and it seems they should be. However, I have not found any explicit mention about thread-safety in the documentation.

The issue was raised on `Serilog.Exceptions` repository https://github.com/RehanSaeed/Serilog.Exceptions/issues/59. For performance reason, this enricher keeps some state, which in some very unlikely scenario would result in a race condition.

Could you please clarify and document this issues?

**Comment by nblumhardt** [comment]
Hi @krajek - yes, enrichers do need to be thread-safe. The whole Serilog pipeline from `Log.X()` to sink is concurrent 👍 

Best regards,
Nick

**Comment by krajek** [comment]
Thanks for the reply. I have made `Serilog.Exceptions` thread-safe.

I suggest documenting the fact, even one sentence would be enough.
