### ISSUE TITLE
Include Remote IP in Logs

### ISSUE THREAD

**Issue by cgountanis** [serilog/serilog#1145]
Have we figured out an easy way to simply include more information about the client without having a bloated middleware process?

Core 2+
MVC

```
// Enrich.
loggerConfiguration.Enrich.FromLogContext();

// Console logging.
loggerConfiguration.WriteTo.Console();
loggerConfiguration.WriteTo.RollingFile(
	outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message} {ActionName} {RequestPath} {Properties}{NewLine}{Exception}",
	pathFormat: "logs/log-{Date}.log");
```

**Comment by nblumhardt** [comment]
Hi Chris, thanks for the note.

Generally an MVC app will have many pieces of middleware; having one for logging/diagnostics is not unusual - it doesn't come much cheaper than the cost of a couple of function calls.

Are you finding that logging middleware shows up during your profiling? Or is there a code quality impact we're not considering? Suggestions for better plug-in points also welcome, if we're missing a better option.

Cheers,
Nick

**Comment by cgountanis** [comment]
Maybe you can tell me if anything can be done to optimize or tweak the output. Right now by using the RequestLogger middleware the {Properties} just dumps everything it can find which includes cookie data and very long strings as well as other useful information such as client info. Is that the best way to get the information?

Startup > Configure
`app.UseMiddleware<RequestLogger>();`

Program > Main
`loggerConfiguration.WriteTo.RollingFile(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message} {ActionName} {RequestPath} {Properties}{NewLine}{Exception}", pathFormat: "logs/log-{Date}.log");`

Middleware
```
public class RequestLogger
{
	private readonly RequestDelegate _next;
	private readonly ILogger<RequestLogger> _logger;

	public RequestLogger(RequestDelegate next, ILogger<RequestLogger> logger)
	{
		_next = next;
		_logger = logger;
	}

	public async Task Invoke(HttpContext context)
	{
		using (LogContext.PushProperty("Headers", context.Request.Headers, destructureObjects: true))
		{
			await _next.Invoke(context);
		}
	}
}
```

Example Log Line (FULL w/Middleware)
`2018-04-04 16:25:27.320 -05:00 [Information] User 91c5ebe5-0bcb-e711-8328-0205857feb80 successfully Initialized. SampleWebSite.Controllers.InitializationController.Initialize (SampleWebSite) /Initialization/Initialize {SourceContext: "SampleWebSite.Controllers.InitializationController", ActionId: "2a9f3d52-c6ff-4e6a-8a77-f1e2bcc0662c", RequestId: "0HLCQEA8J0LQF:00000004", Headers: [KeyValuePair`2 { Key: "Connection", Value: ["Keep-Alive"] }, KeyValuePair`2 { Key: "Accept", Value: ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"] }, KeyValuePair`2 { Key: "Accept-Encoding", Value: ["gzip, deflate, br"] }, KeyValuePair`2 { Key: "Accept-Language", Value: ["en-US,en;q=0.5"] }, KeyValuePair`2 { Key: "Cookie", Value: [".AspNetCore.Antiforgery.pQwBR6WFlQI=CfDJ8PvRdmWNeYhFhjNTK5ewV0Rp8FahYjfUZvn3gVBwcBN19jTaqUfSYbXPaMydi95ViGFyKSU_tE20QZ-zM0AoFH16dtBkLfM_7efkxdoa5jrgxODWvraqOntWTQiNNZ2PZV05vN3M7GaAQH0lYPojTo4; babbc54b-9540-4711-805a-6615f1494a15_Session=CfDJ8PvRdmWNeYhFhjNTK5ewV0T8CJywmMgeG0Xl%2F4z2ZY8PX82MF7FiC65uqBl4ZhteaFX8oJvES1nlXA7kMskr9c%2BwSs5xwWdEDG0WcM6gutrFHGOpA9ZSu4TDUqhjriudZHsOdc6sm6p9pgrnaF%2F1Hcf2UcATECvItx7wgF8PKCLJ; dfbc70f4-3e84-411b-9923-f84c896c05c9_Cookie=CfDJ8PvRdmWNeYhFhjNTK5ewV0QTXCpM8wIuHLpayYxINIOy6UngyPXZYnl3oAeelC0kk_a10vK9rmlETaj6pqzEnd8FG15mEdnPWqkOEZNOMbdDUOoSNwr_PUS7cNQP7PvUqP2b1EXdl1kUdYd_MerG6BIaQQxqgbE_katYoIGGJ-i1fKvm6HgN0l3HSSzxP40zmnNb7m9KAzH8BNrBjraAr6dW4dHGYDaRH1Ff_lGq4eiEMvL-emQk7HAar492yeymY-aLNU3ep-scRvihzb6wtAjEFKN-BbsQR8T_Pc3vU1XfapNdjpJ0PrdnRSccXQ8nID51tS-xLq038l4suB9Ze6I51eT3SSan6HCB_bwUrTP-hyR-CJXCF96l92O2Hs8iaAhZcdz-GhSvtQERwomU3oW8e0deTIox_kKYJ-6a0MtCfan0anz17be6J1atHt_e560EKa9N9F7hm-1RSrDuQDbhwXw8-Xv4r6sEAHtpQl95Ii2PrdVH8unADPeuKLNzNToC9i4xQ0KNNdDRjNwdTa8Qt5RREddfW3gVkIG0AP50945KuAshkXIQwXVoUihfC-3x_LBsXsWnSDWCLLLvC9kKWplB6UGqrccyEA4qvigKcs6woIKecbaBPPiQ3OBV6ok9WaCj61dhl26N6FdDGRZh-BrUvWVV4P_JfSP72bF-xyAafW1mxehyjuMyItA7I3ElXdoDRr3-Jt99X1WX6m9fjQt4sQy6NXW9DX_9jUlHoEGDet8O5NQDMpt8beNKtIrHpkf5sHLvKCP6nzOazM-Mt8JzYY8Hj4MSrwyAZfq7xcHKD17dZU9cP8jEFx_7rDZTTYhYsruJxYuVSNJOx_vtfHV0eCd09jC8K9TSDZpMUiqFm1sSrYzlYLyb9qsuw4KlNMvGMxBU6T2fMLj9fRXRwiNfZZtOv1M5bLZEDdV32PNfFyLdhuSnfmyWZmgX1wrrUtNJM9LL_EGYf7tsfbhDt4cjg6BEIYROa_nEIr_IGcvyPqoehTv6XGaxAsnVjFkdMbzxofvR_6Jm6uTgPCIW2MYqXb45d4VYTnqbXzU3y2X2K2cw4-nFP2e-tcbyYRSYBf5QlHyGtR7TrYzgjwvqj46hcJLI4_RsC9HENNX6pVvbCFDtKUnQghft2uukqNP7sA8gVRqmQ2u8uckiwrbV_Dn_HvqG8kzYa6zXHP4GRYB_VYVhila9XM1-p4-nVA32Km6zOdC5g6zMCxhmtqtnYMEK2xb3A_qPDt16o0SDuZBar56xhccSyWsMe_WO5Aa2CpByLazqYDEBa1WhEFQgycv161ufCmwq0jgUbpD6TWFc0jkUJv7ObkrQ5S210GUInaJPa-NFDIvbwedC3Ufa84hjpzN5tMtvukdWOKmNZcaqiVr_NrsGm2-AJJpGEVhX-WGaE5-GlGwRCz3sSGmSmklr-9t88P7R_m70TiHkdalu2QqHo7FZOsSGfbBoypLNXkzOUCESEMS0D23ZeJ5nIMiHn3a_iiakqd8aaK5KNF2ewAak-DK8YzoSlJt6bLUuo4RKKO_pt8Xi3SwnhXV0D2HDmg6CmG_AzqvFAM5G1jKA5n5aAk-LnuZAcOLoyWNhi2YyUEiUM0ZkfI-SYEdrztWM4sNRmj_RIiivwLBcMRzXT_dCqqO5IAl-YpgHDieg8ulRMDbQOJqanvhCPcysY50GRTlqDGwdhFawE1UG4gKPsZLkHZiBfAkkFsq1fuzOr3gSknLHc5ZBdxQImj0-ddIoTqmIL57aINJK-Olsc_q62HWnhxweeRlEPXATzR21ORNwFs44DOwoXonJNsjRWciejmh-6yUkY19HiBtskGNCy4EBPNHtKJ_o1ovYODJd8KgXUh-nC-lE_GTz9X4nopwATs3xrbCjMF9H-Kyt0KAFIfkxUSxy0DWfObhWZhA_u1kGspPTHqYgD6q0Bux_Vv3KhYlV2jtkJ5i2U8VEJ_tzy27cYuTNsCPSPieD117_CmwKNwgMUFTrHvwj0M12IT7VOVsaCeaiGPxDLtAy_jWlwS0eUQ6fmnCLPOJ-Z-nkpeoq6bu0V1GhUQkq2trbElqFgA6AjM4CxzIdQryuOsVY9EvJWI4nwpG3cmAYkmk0hTk2--b_-AWcbf0ZnjMF1kUNW8SZrez4DLLKgy16CNc3W1pQCXBEKMmTRU4KnJo0hgoiGbudIRr7PTbLcx00tqEV56ILdnqC4tJaU4w6cZ20pITtOUNZB8tquAPsAodzUNMMf4LXurdHt6zTuWSEHh8EHfbU1UtBPg8hUJsV28fiVhRxvPIFYgXRmSrRUcIp41RXCCtHLlQk8o-nPZ5TIaCV7E5OH7XHsyO-Oy-rIN3sqCWbxZ200p0L3MB6IoO34Zb38KrNDZlG8_u04UGEtYpd-hKwIjO4rpYGkv9VD3zJgOwnHUu0k9fyFlgV4WAXZbfQkWiEXP1SrmmNAw7txawd_Qgow68c6fGyomjEqz6lCnvCZyWbHfcQ_mxi3TtSYd1ppNf7N23M4sxIVb45sZ0KHqS34ZyPH0rGFrU1PhIr96X4zRP3TTr88_p6kPDYsFq9GFlWvIgn-6VzB5xGJObjoBQU_ZI1RyW7m7UpCJpzbB-bNGIM3sESmmKeK1LBjxVjzjJ8rj7MI6_q1zPN4T6j3CjSMgjaCbIXZPw4b__LrFJuBJEg3oT14ui_4Lwfu19iqQVFZP9zuih34n-z1XlFRGIp7ABHYvklKLYiSdkSb_y39_gLMS7LFNmF0inpcF5x-CrL3MYDx2TFLMKwe_QyWmw6k8LLZfIyqind7_Iabat0TKzb3tP58WYZBD3r915Gg1kjxkGUvTWL4I_kIMkN39ixtRXt74p8P9ZUSqPea-VXnI-DAGHNnB8YewXSNYAaFLth9wP9mMXm2biuFM2gl0sssU0--lxO7E7UuaKetDKtUGsyHnlIr7KSfqIBAbFDe-M5kIODQijqOvw8Xjl2xqQ65Mx3EmV53zvFh9GibzfoPQN9kWOYLt_GeZR5oXmxcjfEyD5xGOf6gNM-XA19KzR1BMLpyS0f8XhYaeYFD-CYjxR-uZxayL3xJh_VL2UYy9DtbEQrNAMOU-CsTwx4ULw0eC5_tYImFwvUKzfnAIQD_1XeXP9spA2bo2gVMdNXsRdDR2w-RXn8LFZmk2f6QQ1U1CzTaUJiNtg1bvnoqgNotMru6PvJxj9YOBJsh9Zmded2lVX65xcqpdgwmgx3-DcJoDGfzg4Nm-io_zEslCKq3jzqSYDAlyaBpHYUdDF5oz0y6HosiXeHEOW7pxUxvLhbk7lunA97P1sMmtKZR881DaOoMZ2MFmPzcK-qjN1dDexnLXJXwpOZMsmhxdtpTObLa2a1uvZtzuCt"] }, KeyValuePair`2 { Key: "Host", Value: ["localhost:44315"] }, KeyValuePair`2 { Key: "Referer", Value: ["https://localhost:44370/Authorization/Login?returnToUrl=https://localhost:44315/Authorization/Login&siteName=Template%20Sample%20Web%20Site"] }, KeyValuePair`2 { Key: "User-Agent", Value: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"] }, KeyValuePair`2 { Key: "upgrade-insecure-requests", Value: ["1"] }, KeyValuePair`2 { Key: "MS-ASPNETCORE-TOKEN", Value: ["ade7b6eb-55b4-47e0-b876-c968646c8edd"] }, KeyValuePair`2 { Key: "X-Original-Proto", Value: ["http"] }, KeyValuePair`2 { Key: "X-Original-For", Value: ["127.0.0.1:51060"] }]}`

**Comment by cgountanis** [comment]
Honestly not even sure the Key: "X-Original-For", Value: ["127.0.0.1:51060"] is even going to work. Maybe if the client was not on localhost the website was hosted remote, just need the IP for security reasons.

**Comment by nblumhardt** [comment]
Instead of:

```csharp
		using (LogContext.PushProperty("Headers", context.Request.Headers, destructureObjects: true))
		{
			await _next.Invoke(context);
		}
```

Why not try:

```csharp
		// Or whatever mechanism works with your web server
		var remoteIP = context.Connection.RemoteIPAddress.ToString();
		using (LogContext.PushProperty("RemoteIP", remoteIP)
		{
			await _next.Invoke(context);
		}
```

This will reduce the amount of information in `Properties`, but if you wish, you could also just add `RemoteIP` alone to your output template, instead.

**Comment by cgountanis** [comment]
Thanks... Will give it a shot. Is there a way to get just a separate controller and action or is general {properties} still needed for that misc info?

**Comment by nblumhardt** [comment]
You can add `SourceContext`, `ActionId` and so-on separately to the output template along with any other property names. HTH!

**Comment by osudude** [comment]
@nblumhardt   It would be way cool if serilog enrichers had support for constructor dependency injection, then you could inject IHttpContextAccessor into a RemoteIpAddressEnricher and fetch the ip address without resorting to middleware (this is similar to what we do in one of our other logging frameworks).

**Comment by alexandrejobin** [comment]
@osudude, you can inject IHttpContextAccessor in enrichers. Maybe we were'nt able to do it in the past but with Net Core 3.1, I'm doing this:

```
public class RemoteIpAddressEnricher : ILogEventEnricher
{
    private const string RemoteIpAddressPropertyName = "RemoteIpAddress";
    private const string RemoteIpAddressPropertyCacheName = "Serilog.Enrichers.AspnetCore.RemoteIpAddressEnricher";
    private IHttpContextAccessor _httpContextAccessor;

    public RemoteIpAddressEnricher()
        : this(new HttpContextAccessor())
    {
    }

    public RemoteIpAddressEnricher(IHttpContextAccessor httpContextAccessor)
    {
        this._httpContextAccessor = httpContextAccessor;
    }

    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        var httpContext = _httpContextAccessor.HttpContext;

        if (httpContext == null)
        {
            return;
        }

        var remoteIpAddressPropertyCache = httpContext.Items[RemoteIpAddressPropertyCacheName] as LogEventProperty;

        if (remoteIpAddressPropertyCache == null)
        {
            remoteIpAddressPropertyCache = CreateProperty(propertyFactory, httpContext);
            httpContext.Items[RemoteIpAddressPropertyCacheName] = remoteIpAddressPropertyCache;
        }

        logEvent.AddPropertyIfAbsent(remoteIpAddressPropertyCache);
    }

    private LogEventProperty CreateProperty(ILogEventPropertyFactory propertyFactory, HttpContext httpContext)
    {
        var remoteIpAddress = httpContext.Connection.RemoteIpAddress;
        var remoteIpAdresseProperty = propertyFactory.CreateProperty(RemoteIpAddressPropertyName, remoteIpAddress);

        return remoteIpAdresseProperty;
    }
}
```
