### ISSUE TITLE
.Enrich.WithThreadId() not working

### ISSUE THREAD

**Issue by asterixorobelix** [serilog/serilog#1146]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog V2.6.0 and Serilog.Enrichers.Thread V3.0.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0

**Please describe the current behavior?**
Thread IDs are not showing up in log file.

**Please describe the expected behavior?**
Thread IDs saved with each entry to the log file.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Please see attached images. Am i doing something wrong?

![capture](https://user-images.githubusercontent.com/20531795/38328587-9a0acd70-384b-11e8-8513-835357032d2b.PNG)
![capture](https://user-images.githubusercontent.com/20531795/38328606-a91e3626-384b-11e8-8337-20c77dd36bba.PNG)
![capture](https://user-images.githubusercontent.com/20531795/38328654-be494ed2-384b-11e8-96de-9c3208c2a447.PNG)

**Comment by nblumhardt** [comment]
Hi! `File()` accepts an `outputTemplate:` that you can use to add more information. E.g.:

```csharp
w.File(...., outputTemplate:
  "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties}{NewLine}{Exception}")
```

Here, `{Properties}` will include not only `ThreadId`, but any other enrichment that is applied. (`{ThreadId}` could be used instead, if you want only the thread id.)

HTH!

**Comment by asterixorobelix** [comment]
Many thanks for the reply Nicholas!

I didnt realize that an output template was necessary in order to get the thread id logging up and running. I'll submit a PR to adjust the readme.

Will close the issue once I am sure that I've gotten it working.

**Comment by asterixorobelix** [comment]
PR https://github.com/serilog/serilog-enrichers-thread/pull/8 submitted and thanks @nblumhardt
