### ISSUE TITLE
Exploring (and Improving? :)) Scalar vs Structure Behavior

### ISSUE THREAD

**Issue by Mike-EEE** [serilog/serilog#1148]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.6.0

**What is the target framework and operating system? See [target frameworks]**
All of them. :)

**Please describe the current behavior?**
Currently it seems that scalar behavior takes precedence over any structured behavior.  That is, if a destructured policy is defined for a type, this policy is ignored unless the `@` operator is applied.  Additionally, if the same type is defined as a scalar, the destructuring policy is ignored altogether, even if `@` operator is applied.  This seems to be errant/unexpected behavior.

**Please describe the expected behavior?**
If a destructuring policy is applied to a type, then the type should be destructured by the policy when it is encountered within a message template, regardless of whether it has been defined as a scalar.  That is, it would seem that any defined destructuring policies would be considered first before any scalar policies.  Consider that the `IDestructuringPolicy` is `public` while the `IScalarConversionPolicy` is `internal`.  This seems to imply that configured destructuring by way of policy takes greater importance over scalar configuration, but this is not the case (that I can tell).

In defining a destructuring policy, the intent is to provide a way to define a simplified data construct (or view) of the object in memory so that it can be later utilized by a sink for storage purposes.  That is my impression, at least.

Further, there also the concern of formatting the destructured object.

Let's use the `AppDomain` as an example.  Perhaps the intention is to store certain details of the application domain as a destructured view.  This might look like: `Destructure.ByTransforming<AppDomain>(x => new {Name = x.FriendlyName, Id = x.Id})`.

This information gets stored in Seq via the Seq sink no problem.  However, for the sake of rendering this out as text in, say, the Console sink, the entire graph of the destructured view is emitted.  In this case, it makes more sense to be able to format that view into a scalar or custom string.  Currently, this is not possible as it seems that once a destructuring policy is defined, the scalar behavior is ignored (that is, there does not seem to be a way to render a destructured view into a scalar). and vice versa.

Anyways, I hope this all makes sense.  I hope further that there is some obvious configuration that I am overlooking that does exactly as described.  However, a day poring through the code as deployed tells differently.  

Thank you in advance for any and all consideration and discussion around this issue. 😄

**Comment by nblumhardt** [comment]
Hi Mike,

Unfortunately it's a bit of a complex area to sum up in a quick reply - things have evolved to where they are right now via a fairly long process, with perf also playing a significant part. Probably best to tackle it scenario-at-a-time :-)

Given your `AppDomain` example, the issue here is that _capturing_ happens once, to create a `LogEvent` with properties that are either scalar or structure values. The sinks don't get to choose how this is done, and there's no conversion between scalar and structure representations of the same piece of data because by the time you have one or the other, the original, source `AppDomain` object may be long gone.

Hope this helps; if there's another particular scenario that would be a better focal point let me know. Cheers!

**Comment by Mike-EEE** [comment]
OK @nblumhardt thank you for the explanation there.  Please note that I am indeed discussing the capturing of data, or rather, the _configuration_ of capturing of data.  That is, if I have configured a destructuring policy for a particular type, but that policy isn't being recognized and adhered, then why am I bothering to define it? 😄  To quote the documentation that is adding to my confusion here (emphasis mine):

"When Serilog _doesn't recognise the type_, and no operator is specified (see below) then the object will be rendered using `ToString()`."

In the case I am describing, I have provided serilog the definition of a type and what I would like to do with it by way of the destructuring policy, but in my view it is not being recognized.

One of the concerns here is that by forcing the use an operator `@` or `$`, you are forcing the consumer to change their template, which would mean a different hash which complicates the subsequent analytics as a result.

I hate to suggest it, but it is almost as if we require a `ISerializationPolicy` that captures the behaviors around how destructuring and scalar behaviors are defined. 😆 The policy is what then returns the `LogEventPropertyValue` which is then used by Serilog.

Along such lines, the other issue I am seeing is the use of `ToString` to determine the scalar value of an object.  It would be incredibly valuable to configure control over this as well.

FWIW, I am more than happy to send a PR to address these points. 🤓

**Comment by nblumhardt** [comment]
Hi Mike, thanks for the reply. Opting into `@` is pretty central to Serilog's design - there are other ways to look at the problem. `"{@Foo}"` says, _I'm recording the details of this here `Foo`, and I'm okay with the cost of that_, while a few lines of code away, a `"{Foo}"` says _I just want to record what this is_ ... i.e. usually it's `ToString()`.

There's also a very strong performance motive for keeping destructuring policies out of most logging statements; although it might be possible to query policies without a big perf hit, there are a lot of trade-offs involved. This is why extending the set of `IScalarConversionPolicy`s hasn't been a desirable scenario so far - they're individually queried for each logged value, every time.

I would love to dig in further, but this could end up being a very long reply, so I should leave it here - but I should add: I am sure there are opportunities to improve ergonomics, here. Changing the opt-in requirement of `@` probably isn't on the table, but some better control of scalar conversion seems reasonable. It's just that for the possible gains, the implementation effort and mountain of tedious benchmarking work that would come with it keeps me away :-)

**Comment by Mike-EEE** [comment]
Cool, thanks for that @nblumhardt .  So after further discussion around this, it seems to be that my issue stems around having a type that is defined as a scalar, while also having a destructuring policy assigned to it.

I would mostly be able to do what I am looking to accomplish above with the following:

```
new LoggerConfiguration().Destructure.AsScalar<AppDomain>()
			 .Destructure.ByTransforming<AppDomain>(x => new {Name = x.FriendlyName, Id = x.Id})
			 .WriteTo.Console(formatProvider: new FormatterThatKnowsHowToFormatAppDomainIntoPrettyString())
```

That way, I could use `{AppDomain}` for a simple scalar if I chose to, but then also `{@AppDomain}` if I want to destructure it for further information.

However, doing the above does not work as expected as scalars take precedence over destructuring policies at moment.  To make this work, we would have [to modify this code](https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/PropertyValueConverter.cs#L147-L160) to instead read:

```
if (destructuring == Destructuring.Destructure)
{
    foreach (var destructuringPolicy in _destructuringPolicies)
    {
        if (destructuringPolicy.TryDestructure(value, _depthLimiter, out var result))
            return result;
    }
}

foreach (var scalarConversionPolicy in _scalarConversionPolicies)
{
    if (scalarConversionPolicy.TryConvertToScalar(value, out var converted))
        return converted;
}
```

Running the tests within the latest `dev` branch all pass with this modification.  But, wanted to see what you thought before sending over a PR.

**Comment by nblumhardt** [comment]
This is where that perf challenge rears its head :-) .. after the change, we'd go from a very quick capturing of scalar values under destructuring, to a slow check through every policy. The ordering there is deliberate, unfortunately.

I'm afraid there's not a great workaround; you could define a `ScalarWrapper` type and do:

```csharp
Log.Information("Hello {AppDomain}", new ScalarWrapper(appDomain));
```

and then use `Destructure.AsScalar<ScalarWrapper>()` to get the behavior you want. Ugly, I admit :-) Flipping this around to use a wrapper type on the destructuring side might be a fraction nicer.

But on the whole, scalars aren't really designed to be used this way - the requirement that scalar values be thread-safe (and practically immutable) makes them a poor fit for a formatting aid. Your initial identification of `IScalarConversionPolicy` as the extension point seems close to the mark - it's just that for an edge case, the work involved in designing/adapting/benchmarking the mechanism seems on the high side :-)

**Comment by Mike-EEE** [comment]
> after the change, we'd go from a very quick capturing of scalar values under destructuring, to a slow check through every policy

Ah, OK.  I didn't realize that you could destructure scalars, but sure enough in the block above the code there's a check for destructuring a string.  Seems like that should be defined in a `IDestructuringPolicy`, however. 😉 Are there any other scalars that are typically destructured?  The reason I even ask is that changing the order of the statements did not break any tests, which of course raises my suspicions here. :)

In the meantime I will continue to mull this and give some thought to your `ScalarWrapper` suggestion.  Thank you for your time and insight @nblumhardt !

**Comment by Mike-EEE** [comment]
Alright, I figured this one out.  Both Console and Trace sinks accept a `ITextFormatter`.  I'll simply decorate them, intercept the values and pass the new ones to the decorated component.  Piece of cake. 🍰  Closing now and chalking this one up to newb/user error.

**Comment by nblumhardt** [comment]
Nice! Glad you found a workable alternative :+1:
