### ISSUE TITLE
Add support for injecting dynamic values into Enrichers.

### ISSUE THREAD

**Issue by fernandezjose** [serilog/serilog#1149]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
All

**What is the target framework and operating system? See [target frameworks]

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Enrichers are a powerful tool but they enforce a parameterless constructor. This makes them very rigid and virtually impossible to inject anything. 

**Please describe the expected behavior?**
Have a constructor that takes in a IHttpContextAccessor so that we can inject that object and have access to RequestServices services with a scoped or transient lifetime.

**Comment by nblumhardt** [comment]
Hi Jose, thanks for the note!

There's no requirement that enrichers have a parameterless constructor:

```csharp
.Enrich.With(new MyEnricher(...))
```

Serilog's also built to be DI-friendly; unfortunately containers and applications vary so much that you need to work through the container configuration yourself. What you're probably looking for is something like this Autofac-style example:

```csharp
builder.Register(c => new LoggerConfiguration()
    .WriteTo.Console()
    .CreateLogger())
  .SingleInstance()
  .Named<ILogger>("root");

builder.Register(c => c.ResolveNamed<ILogger>("root")
    .ForContext(new HttpContextEnricher(c.Resolve<IHttpContextAccessor>())))
  .As<ILogger>()
  .InstancePerLifetimeScope(); // or per-HTTP request
```

With this kind of configuration you'll get an enriched logger injected whenever you take a dependency on `ILogger`.

A second, and slightly nicer option, is to use some ASP.NET Core middleware to push your enricher onto the ambient log context within which a request executes:

```csharp
class HttpContextLoggingMiddleware
{
    readonly RequestDelegate _next;

    public HttpContextLoggingMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext httpContext)
    {
        using (LogContext.Push(new HttpContextEnricher(httpContext))
        {
            await _next();
        }
    }
}
```

This will have the added benefit that the enrichment will work with any `ILogger` used during the request, even ones injected into singleton components. It'll also work better with https://github.com/nblumhardt/autofac-serilog-integration.

For the above to work, you need `Enrich.FromLogContext()`.

Let me know how you go!
Nick

**Comment by nblumhardt** [comment]
Hi Jose - glad you have a working solution.

> Unfortunately we are dealing with .net core's dependency injection which is limited when compared to Autofac for example. Complex services registration is virtually impossible.

> Is there a roadmap for adding support to .net core native dependency injection engine?

Serilog already has APIs to support just about every possible method of parameterizing/enriching loggers. There's not really anything missing on the Serilog side, that I can see.

Unfortunately, if you're stuck with an IoC container that doesn't provide adequate plug-in points then it's really not something Serilog can fix. Probably better to lobby for new features/APIs to be added to _Microsoft.Extensions.DependencyInjection_ or _Microsoft.Extensions.Logging_ ... or switch to Autofac ;-)

**Comment by Neutrino-Sunset** [comment]
I don't think either of the suggestions posted by @nblumhardt is really useful.

Initialising Serilog as part of the DI buildup means that you don't get to capture any of the startup logic. Not good.

Adding your enricher to the log context in a middleware means that your enricher is not in place during all the ASP logging that occurs in the request pipeline prior to your middleware executing. Also not good.

A key requirement for a logging system is that it covers the entire operation of the program. We need a better solution to this issue.
