### ISSUE TITLE
Serilog instance for MVC app

### ISSUE THREAD

**Issue by fatagun** [serilog/serilog#1152]
Hello, 

I am seeing things like global logger.

My question is when I am wiring up the logger, what should be instance model?

Singleton, instance per request, instance per dependency or something else?

If it is a global logger, is it safe to assume thread safety ? 

Thanks.

**Comment by nblumhardt** [comment]
Hi,

Serilog loggers are thread-safe, so no problem with singletons. Personally, I don't use IoC to inject loggers and instead set up the static `Log` class, but YMMV.

Check out github.com/nblumhardt/autofac-serilog-integration for one take on it.

HTH!
Nick
