### ISSUE TITLE
serilog wrapper or adapter

### ISSUE THREAD

**Issue by fatagun** [serilog/serilog#1153]
I am planning to use serilog in an enterprise app.

Does it make sense to have a wrapper or adapter around serilog? something like following?

https://github.com/uhaciogullari/NLog.Interface/blob/master/NLog.Interface/LoggerAdapter.cs

Thanks.

**Comment by nblumhardt** [comment]
Hi @fatagun,

No, honestly - if you can avoid the cost/complexity of wrapping, then I would. Logging abstractions are either a) leaky (the interface might be consistent, but the implementation behaviors differ), or b) lowest-common-denominator.

My $0.02 :-)

**Comment by adamchester** [comment]
@fatagun I agree with @nblumhardt that you should avoid “wrapping” Serilog. I believe you should try to articulate more clearly what the goal you are trying to achieve by “wrapping” it. Just saying “it’s enterprise” or “reusable" is not enough IMO. Serilog is already enterprise-compatible, and very reusable.

I had a look at [your sample here](https://github.com/fatagun/Serilog.Wrapper/tree/04f0454dd08c8e2ff0d0f9a2dd8070642c5ed143/Logging) and there are already numerous issues you might not be aware of. 

For example, the [serilog analyser](https://github.com/Suchiman/SerilogAnalyzer) will not currently be able to help your users construct good logging statements.

**Comment by nblumhardt** [comment]
Closing, but please let us know if you need more info.
