### ISSUE TITLE
dynamically control the logging level of Serilog at runtime

### ISSUE THREAD

**Issue by fatagun** [serilog/serilog#1155]
Hello,

I wanted to know how to dynamically control the logging level of Serilog at runtime.

Is that possible? Any samples out there for a MVC web app?

Thanks.

**Comment by fatagun** [comment]
is this it?

https://nblumhardt.com/2017/10/logging-filter-switch/

**Comment by joelweiss** [comment]
@fatagun see [Dynamic levels](https://github.com/serilog/serilog/wiki/Writing-Log-Events#dynamic-levels)

**Comment by nblumhardt** [comment]
@fatagun yes, that's the one 👍
