### ISSUE TITLE
Use an organization account for nuget packages

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1159]
In April 2018, Nuget [introduced the concept of **organizations**](https://blog.nuget.org/20180417/organizations-on-nuget-org.html) ... The concept is pretty similar to the Github one, that is, it represents a team, more than it represents a person, and accounts can come and go in or out of the organization. This allows several users to manage packages for serilog without having to share credentials. 

Serilog has been using a few dedicated "non human" accounts on nuget ([serilog](https://www.nuget.org/profiles/serilog), [serilog-web](https://www.nuget.org/profiles/serilog-web)) from the start, and conceptually at least, those should be *organizations*. 

A *regular account* [can be turned into an organization](https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org#transform-existing-account-to-an-organization), but I'm not sure about the consequences and whether it's worth the risk of possibly breaking all the Nuget publish automation around the Serilog repositories : 

![image](https://user-images.githubusercontent.com/160544/39696746-f4b37c60-51ee-11e8-9516-17e261142dd3.png)

**Any thoughts ?** 

Announcement : https://blog.nuget.org/20180417/organizations-on-nuget-org.html
Documentation :  https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org

**Comment by nblumhardt** [comment]
Hi Thibaud - we've already switched across, if you send your NuGet.org username to me I'll add you :-) :+1:
