### ISSUE TITLE
Different representations for different sinks

### ISSUE THREAD

**Issue by arabcewicz** [serilog/serilog#1161]
Hello,
I seem to have some basic question, but I can't find an answer anywhere.
I need to log to two files: the first is for human, the second is for machine processing. I'd like to have objects stringificated for human and destructured for machine.
Is it possible at all?

**Comment by tsimbalar** [comment]
Hi,

What you want in that case it to use the [File ](https://github.com/serilog/serilog-sinks-file)Sink twice when specifying your configuration, but use different _formatters_ in each.

For machine processing, I would recommend that you use `CompactJsonFormatter` from [Serilog.Formatting.Compact](https://github.com/serilog/serilog-formatting-compact) (needs installing from Nuget) , but you can also use `JsonFormatter` that is included with Serilog (see https://github.com/serilog/serilog-formatting-compact#comparison for a comparison of the two).

This would look more or less like : 

```csharp
var log = new LoggerConfiguration()
    .WriteTo.File("humans.txt")
    .WriteTo.File(new CompactJsonFormatter(), "machine.txt")
    .CreateLogger();
```

When your file is generated with `CompactJsonFormatter`, you can use the [**clef-tool** ](https://github.com/datalust/clef-tool)command-line utility to extract information from it, or you can use the [**seqcli**](https://github.com/datalust/seqcli) tool to send the events to Seq for centralizing.

**Comment by arabcewicz** [comment]
@tsimbalar thanks for fast reply. And sorry for not being precise - I'll try to explain deeper:
Let's define a class
```
public class TestObject
{
    public string A { get; set; }
    public int B { get; set; }
    
    public override string ToString() { return A; }
}    
```
and two instances:
```
var testObj = new TestObject { A = "AlphaObject", B = 2 };
var testObjB = new TestObject { A = "BetaObject", B = 3 };
```
With configuration above:
a) ```log.Information("First: {alpha}, Second: {beta}", testObj, testObjB);```
gives (the first for human, and the second for the machine):
```
[23:32:18 INF] First: AlphaObject, Second: BetaObject
{"@t":"2018-05-08T21:32:18.5785012Z","@mt":"First: {alpha}, Second: {beta}","alpha":"AlphaObject","beta":"BetaObject"}
```
b) ```log.Information("First: {@alpha}, Second: {@beta}", testObj, testObjB);```
gives:
```
[23:32:18 INF] First: {"A": "AlphaObject", "B": 2, "$type": "TestObject"}, Second: {"A": "BetaObject", "B": 3, "$type": "TestObject"}
{"@t":"2018-05-08T21:32:18.6020364Z","@mt":"First: {@alpha}, Second: {@beta}","alpha":{"A":"AlphaObject","B":2,"$type":"TestObject"},"beta":{"A":"BetaObject","B":3,"$type":"TestObject"}}
```
What I want is the human form from a) and machine form from b).

Note, that this is possible in NLog with the configuration
```
            var config = new LoggingConfiguration();
            var humanTarget = new ColoredConsoleTarget();
            config.AddTarget("console1", humanTarget);

            var machineTarget = new ColoredConsoleTarget();
            config.AddTarget("console2", machineTarget);

            var jsonLayout = new JsonLayout
            {
                Attributes =
                {
                    new JsonAttribute("time", "${longdate}"),
                    new JsonAttribute("level", "${level:upperCase=true}"),
                    new JsonAttribute("message", "${message:raw=true}"),
                    new JsonAttribute("eventProperties", new JsonLayout
                        {
                            IncludeAllProperties = true,
                            MaxRecursionLimit = 2
                        },
                        //don't escape layout
                        false)
                }
            };
            
            humanTarget.Layout = @"${date:format=HH\:mm\:ss} ${level:upperCase=true} ${message}";
            machineTarget.Layout = jsonLayout;

            var rule1 = new LoggingRule("*", LogLevel.Debug, humanTarget);
            config.LoggingRules.Add(rule1);
            var rule2 = new LoggingRule("*", LogLevel.Debug, machineTarget);
            config.LoggingRules.Add(rule2);
            LogManager.Configuration = config;
```
Then
```
            var nlog = LogManager.GetCurrentClassLogger();
            nlog.Info("First: {alpha}, Second: {beta}", testObj, testObjB);
```
 gives
```
23:32:18 INFO First: AlphaObject, Second: BetaObject
{ "time": "2018-05-08 23:32:18.7686", "level": "INFO", "message": "First: {alpha}, Second: {beta}", "eventProperties": { "alpha": {"A":"AlphaObject", "B":2}, "beta": {"A":"BetaObject", "B":3} } }

```

**Comment by nblumhardt** [comment]
@arabcewicz thanks for the follow-up clarification. This is one we've discussed previously in an issue or two, and no, there's no direct way to do this with Serilog, though schemes along the lines @bartelink is suggesting can work, and with custom `IDestructuringPolicy`s and `ConditionalWeakTable` anything's possible (though with an implementation and run-time cost).

Serilog's view of the world is broken into _capturing_, where we decide on the representation of a nugget of data, and _rendering_, where the nugget is formatted out for machine or human. There are advantages of doing this for the in-between event processing stages, where data can be transformed/modified uniformly.

It's reasonable to want to capture an object in two different ways for the different purposes, but it's not a scenario Serilog is likely to incorporate.

HTH!

**Comment by skomis-mm** [comment]
Since we have and `ILogger` interface another solution  if we introduce a composite logger which acts like a regular logger with subloggers but independent from the parent, so the capturing phase will be for each individual pipeline:
```
    class CompositeLogger : ILogger, IDisposable
    {
        readonly ILogger[] _loggers;

        public CompositeLogger(IEnumerable<ILogger> loggers)
        {
            _loggers = loggers.ToArray();
        }

        public ILogger ForContext(ILogEventEnricher enricher) =>
            new CompositeLogger(_loggers.Select(l => l.ForContext(enricher)));

        public void Write(LogEventLevel level, Exception exception, string messageTemplate, params object[] propertyValues)
        {
            foreach (var logger in _loggers)
            {
                logger.Write(level, exception, messageTemplate, propertyValues);
            }
        }
...
```
Then configure like this:
```
Log.Logger = new CompositeLogger(
    new []
    {
        new LoggerConfiguration()
            .Destructure.AsScalar<TestObject>()
            .WriteTo.File("humans.txt")
            .CreateLogger(), 
        new LoggerConfiguration()
            .WriteTo.File(new CompactJsonFormatter(), "machine.txt")
            .CreateLogger()
    });
```

**Comment by bartelink** [comment]
@arabcewicz https://github.com/serilog/serilog/issues/839 might be an interesting read for you.
I tend to think that this is a pretty rare requirement and as such is best not put into the API on the grounds of [-100 points](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/). For me, the ideal for new code is that you should be able to have a single consistent pipeline for reasons of both efficiency and clarity - especially when asynchrony gets into the mix.
Having said that, it may be interesting to spike. As illustrated by https://github.com/serilog/serilog/issues/1154, having good abstractions to express semantics in a configuration pipeline can be valuable (and devilishly complex).
Before all that, I reckon a self-answered SO question can document the idea (drop a link here) and we can work from there to figure out if this is a common need.

**Comment by nblumhardt** [comment]
:+1: lets just leave this issue here for now, with the workaround - it's only a few lines of code to incorporate, and as far as library APIs like Serilog go, I think the fact we can enable this without code changes on our part is a win :-)
