### ISSUE TITLE
Deeper Audit / Audit Trail support

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1170]
Serilog has had support for *Audit* logging for a while now (thanks to PR #826 namely, and discussed in issues #87 and #820). It allows some kind of alternate logging path where logging may actually fail and cause an app to crash. 

**TL;DR;**

I find myself thinking it would be nice to support **audit scenarios a bit more deeply**, as a first class citizen instead of a specific case of logging.

## *Audit* vs *technical logs*

**Auditing** (also Audit Trail / Audit Trace) has different semantics / expectations than (*technical*) logging.

While technical logging may be considered *optional* (i.e. not a functional requirement), and could be disabled, audit trails are a **functional requirement** and sometimes even a legal requirement.

In technical logging, failing to write log messages should never cause an application to crash ( well described in the [Reliability ](https://github.com/serilog/serilog/wiki/Reliability)wiki page) ... when audit is written, the app needs some guarantee that the message has indeed been written. 

One might go as far as seeing it as **a transaction** : 

1. doing the **business action**
2. writing the occurrence of that business action to the audit trail

either 1 AND 2 succeed or 1 AND 2 fail, but doing 1 without 2 is wrong (loss of history) and doing 2 without 1 is wrong (fake history).

## Current Audit support in Serilog
Those expectations are partly covered by `LoggerConfiguration().AuditTo.*` extension methods as this is the only situation where writing may actually trigger an exception that the application would see.

Because Logging and Auditing have different semantics etc, they should probably be handled slightly differently (one "catch errors" path for logging + one "crash the app" path for auditing) ... but they also have lots in common (pipeline of enrichment filtering etc) ... 

So far, when dealing with both Auditing and Logging in the same app, [the recommendation](https://github.com/serilog/serilog/issues/820#issuecomment-239073554) has been something like : 

```csharp
Log.Logger = new LoggerConfiguration()
    .AuditTo.Logger(cfg => cfg
        // only "audit" events will go through here
        .Filter.ByIncludingOnly(evt => evt.Properties.ContainsKey("AuditEvent"))
        .AuditTo.File(/*snip*/))
    .WriteTo.Logger(cfg => cfg
        // only "non audit events" will go through here
        .Filter.ByExcludingevt => evt.Properties.ContainsKey("AuditEvent"))
        .WriteTo.File(/**/))
    // this applies to all
    .Enrich.WithComputerName()
```

and then usage in the code would be : 

```csharp
private static readonly ILogger Logger = Log.ForContext<MyClass>();
private static readonly ILogger Audit = Log.ForContext("AuditEvent", "Audit").ForContext<MyClass>();

// later on

Logger.Information("this is happening");
Audit.Information("This is official : user has done that")
```

This works but has a few drawbacks : 
- usage of sub-loggers in `WriteTo.Logger()`/`AuditTo.Logger()` is a bit advanced, and there are some limitations in the usage of subloggers
- usage of sub-loggers is not very well supported in the different *settings providers*
- the "This is an Audit Event" or "make it a logger that writes audit events" is duplicated quite a lot
- both the *audit* and the *regular* logger implement the same `ILogger` interface and have the same signature ... because they have different behaviors, explicitly having different interfaces could help 
- one may accidentally change the configuration and no audit trace would be written anymore ... accidentally breaking expected functionality

## Possible improvements
I believe this would be improved to guide the user towards "the pit of success" :) 

Some things I would like to address : 
- clear distinction of semantics between Audit and Log
- detect bad configuration as early as possible
- prevent the user from shooting his/her own foot
- still being able to use the sinks from the Serilog ecosystem *as is* (and not force sink maintainers to provide new functionality)

I'm not sure how deep this would need to be integrated in the Serilog core library or how easily it could be packaged as a separate package ... 

As a brain dump, here is what I would like to have: 

### Configuration

```csharp
// a path dedicated to "tech" logging, like it has always been done so far
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .WriteTo.File("technical.log");

// a new "parallel" path dedicated to Auditing / reliable logging
Audit.AuditLogger = new AuditConfiguration()
    .Enrich.With(/*..*/)
    .Destructure.With(/*..*/)
    .AuditTo.Console(/*..*/)  
    .CreateAuditLogger();
```

The general idea would be that : 
- `AuditConfiguration` has an API that looks a lot like `LoggerConfiguration` ...
- ... but only exposes the features that make sense (no `WriteTo`)
- *Enrichers*, *Destructurers*, *Sinks* (etc) from the Serilog ecosystem can be used *as is*
- a new `static` ambient class `Serilog.Audit` is added that looks a bit like `Serilog.Log`
- `CreateAuditLogger()` would fail when no sink has been defined
- `CreateAuditLogger()` returns a `IAuditLogger` instead of a `ILogger`
- it may also be a good place to plug in some custom error handling when writing to the audit trail fails (log it somewhere else before re-throwing for instance)

### `IAuditLogger`
`IAuditLogger` would look similar to `ILogger` but provide less overloads
- event writing : `Information()` / `Warning()` / `Error()` / `Fatal()` ... but no `Verbose()` or `Debug`
- event writing method calls should throw when there is no sink defined
- log events generated by `IAuditLogger` are *flagged* as being *Audit events* (just adding a property `EventType` = `"Audit"` or something like that ... possibly customized)
- `.ForContext<>()` and other enrichment features should be available 
- this provides an extension point for extension methods that would cover *standard cases* in a consistent way (for instance methods `.Action(string who, string what)` that consistently writes event `User {UserName} has done {Action}` (+ attached properties) that would always be generated with the same hard-coded event template across multiple applications)

### Audit usage
Later in the code, we could use : 

```csharp
private static readonly IAuditLogger Audit = Audit.ForContext<MyClass>();
```

## Cost / Feasibility / Value
As mentioned earlier this is pretty much a brain dump. I do have a few doubts about : 
- is that technically feasible ? 
- isn't that forcing new features down Serilog's throat ? 
- could that be packaged as a separate extension ? (and would we manage to limit duplication between both)
- am I just over-thinking it ? :)

Any comments and feedback welcome ! :)

cc @serilog/reviewers-core

**Comment by nblumhardt** [comment]
Without much time to digest the proposal, this could be a off-track, but the thing I'd consider first is the audience - how widely is `AuditTo()` being used? I implemented it in the (non-rolling) `File()` and `Seq()` sinks early on, but few-to-no requests have arrived to extend this support to things like rolling files or SQL Server, so I'm not certain it's been widely discovered. Wonder how we could get some usage stats/feedback?

**Comment by merbla** [comment]
Great writeup @tsimbalar! 

I understand the need for Auditing as there has been the occasional request over time.  I do wonder as you suggested if this should be a separate package/extension.  The fact we may need to consider a different interface e.g. `IAuditLogger` and possibly a separate configuration reinforces this idea.  

It would be *nice* to have all the code in the one place however my concerns relate to baking into the Serilog pipeline anything that would detract from performance.  Also, I wonder the complexity we would have to force on downstream configuration projects such as `Serilog.Settings.Configuration` to understand the semantics of both logging vs auditing.

I generally externalise auditing into the sink destination  (ELK, Splunk) so the concerns you mentioned re: transactions I solve elsewhere.  It is just a different approach.

Could this be the start of `AuditLog`, Serilog cousin.

P.S. I am terrible at naming....

**Comment by tsimbalar** [comment]
I think I will try looking at it in a separate repo/package and see how far I can get it from there. 

Once that exists and is available on Nuget, the stats should give us a way of measuring the interest and relevance of that sort of functionality, and see if, further down the road, that would make sense to make it more tightly integrated.

@merbla "naming is hard" :) ... I had started to create a repo and lib *SerilogAuditee* as in 

> auditee (ˌɔːdɪˈtiː)
> noun
> a person or organization that is audited

... not a great name either but hey :)

**Comment by nblumhardt** [comment]
Just reviewing open issues - should we keep this one floating here, or move the info over to SerilogAuditee? Cheers!

**Comment by tsimbalar** [comment]
Closing the issue here, and adding a pointer to it from https://github.com/tsimbalar/serilog-auditee/issues/1
