### ISSUE TITLE
Update documentation to note you cannot use full stops in tokens

### ISSUE THREAD

**Issue by dotnetchris** [serilog/serilog#1171]
The documentation on https://github.com/serilog/serilog/wiki/Writing-Log-Events doesn't make any references to you can't use full stops or periods inside of replacement tokens

```c#
Log.Warning("Disk quota {MyQuota} MB exceeded by {MyUser}", quota, user);
```
Behaves as expected

---

```c#
Log.Warning("Disk quota {My.Quota} MB exceeded by {My.User}", quota, user);
```

Does not replace anything.

Alternatively, this could be viewed as a bug and that these should be replaced. I don't really have an explanation to why `{MyQuota}` would be valid but `{My.Quota}` is not.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Chris! I've updated the documentation - this is indeed a requirement, and not a bug :+1: 

Best regards,
Nick

**Comment by dotnetchris** [comment]
OH, do the message templates compile a dynamically created class and these legitimately become property names?

**Comment by nblumhardt** [comment]
No, not quite :-) but features like _Serilog.Filters.Expressions_ consider `Foo.Bar` to be the `Bar` sub-property of the `Foo` property, not a simple property with a dot in the name. Helps interoperability to keep things limited. Cheers!
