### ISSUE TITLE
Serilog not destructing object

### ISSUE THREAD

**Issue by juchom** [serilog/serilog#1175]
I have a strange behavior with Serilog, I have this config:

```csharp
void Main()
{
	var logger = new LoggerConfiguration()
	.WriteTo.Seq("http://seq.log", apiKey: "abcd")
	.CreateLogger();
	
        var email = new Email();
	var data = email.FillWithData("mail@domain.tld");
	data.Dump();

	logger
		.ForContext("EmailPayload", data, true)
		.Information("Linqpad debugging");
}

public class Email
{
	public body FillWithData(string email)
	{
		var myEmail = new body();
		myEmail.email = email;
		myEmail.ctx.utcTimeStamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss.fff");

		return myEmail;
	}

	public class body
	{
		public string email { get; set; }
		public content ctx = new content();
	}

	public class content
	{
		public string utcTimeStamp { get; set; }
	}
}
```

If I dump the data in Linqpad I have this:
![image](https://user-images.githubusercontent.com/17902415/41235311-d50fb8ae-6d8e-11e8-847b-9652174f82f3.png)

If I watch the logs in seq I have this:
![image](https://user-images.githubusercontent.com/17902415/41235291-c8933bc8-6d8e-11e8-8b9e-3f68153f7ca1.png)

Why the destructured object in seq doesn't show all the fields like in linqpad dump?

**Comment by skomis-mm** [comment]
@juchom Hi, I think you need to change `ctx` field to a property:
```
public content ctx { get; set;} = new content();
```

**Comment by juchom** [comment]
Thanks, I didn't saw it wasn't a property!
