### ISSUE TITLE
Core.Logger.Write() - checking of 'messageTemplate' field and silent return

### ISSUE THREAD

**Issue by Etrimus** [serilog/serilog#1181]
For example, I call this code - I don't need custom `messageTemplate`, I have enough buil-in template.
```C#
Log.Logger.Error(exception: new Exception("!!!!"), messageTemplate: null);
```
In Serilog source code line `if (messageTemplate == null) return;` does silent return in My case, and I don't have any info, what happened and why no any logs was recorded.
https://github.com/serilog/serilog/blob/9a46e68d3e224b965f4ac2665fd379ae9568d6b4/src/Serilog/Core/Logger.cs#L363-L367
Why it does this? I guess, if I pass `null`, it might does a code like this - `messageTemplate = string.Empty` and continue execution, without silent return.
Or maybe want a owerloads without `messageTemplate` parameter?

**Comment by nblumhardt** [comment]
In Serilog's model, message templates are required, so this is done in lieu of throwing an exception.

I don't think this is a change we'd want to make at this point - passing a simple/static string should cover this case. Cheers!
