### ISSUE TITLE
Serilog won't destructure collections of objects

### ISSUE THREAD

**Issue by UngaWunga** [serilog/serilog#1182]
In our .Net Core service, using the following packages:
Serilog.AspNetCore  2.1.1
Serilog.Settings.Configuration 2.6.1
Serilog.Sinks.ApplicationInsights 2.6.0

**Please describe the current behavior?**
We're seeing in our AppInsights logs that individual objects can be destructured properly, but lists of those same object types aren't. We're seeing the list of the object's type, as if Serilog is calling ToString() on it and ignoring the "{@blah}" operator. 

We've got a work around going where we loop through the collection of objects and log them individually. Again, individually they get destructured and logged properly. But in a IEnumerable<someType>, we get a list of types.

Here's our Serilog configuration in our Startup:

```
            Serilog.ILogger logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .WriteTo.ApplicationInsightsEvents(Configuration.GetValue<string>("ApplicationInsights:InstrumentationKey"))
                .Enrich.With(new BlackListedPropertyRemover(filterElementNames))
                .CreateLogger();
            loggerFactory.AddSerilog(logger);
```

Our appSettings...

```
    "Serilog": {
        "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning"
            }
        },
        {
            "Name": "Console"
        }]
    }

```

Here's how we're logging the data:
```
        public async Task<IActionResult> Post([FromBody] List<Event> events)
        {
            // this is what we have to do in order to get all the Event objects from our request body
            foreach(Event e in events)
                _logger.LogInformation("EventController.Post request {@event}", e);

            // this doesn't work. We'll get [ Proj.Models.Event, Proj.Models.Event ]  in the appInsight logs
            _logger.LogInformation("EventController.Post request {@events}", events);
```

Let me know if you need more data, or see something that I was going wrong. I posted this on stackoverflow, and the suggestion was to post the question here as it may be a bug if our configuration/code is correct. Thanks

**Comment by nblumhardt** [comment]
Hi! I think this might be AI-specific; an earlier PR was made around this kind of scenario: https://github.com/serilog/serilog-sinks-applicationinsights/pull/14 - does that clear anything up? Cheers!

**Comment by UngaWunga** [comment]
That doesn't look like the same problem. That commit shows destructuring an object that contains a collection. My issue is with destructuring a collection, no wrapper object.  I'll try wrapping my collection with an anonymous object to see if that's a temp work around. Also, we're using Serilog.Sinks.ApplicationInsights v2.6.0, which would contain that above commit. Thanks.

**Comment by UngaWunga** [comment]
Do this will cause Serilog to destructure the collection...
_logger.LogInformation("EventController.Post request {@events}", new { Events = events });

Not ideal, but it works. 
Also, the logged destructured data isn't kept in order with the data element they're associated with. See example:

  | events.Events.Count | 2
  | events.Events.1.EventDetail.Subject | Updated
  | events.Events.1.Publisher.LocationId | aaaaaaaaaaaaaaaaaaaaaaa
  | events.Events.0.RetryCount | 0
  | events.Events.0.ModifiedOn | 0001-01-01T00:00:00.0000000Z
  | events.Events.1.Publisher.Blah | 153
  | events.Events.0.EventDetail.ResourceId | bbbbbbbbbbbbbbbbbbb
  | events.Events.0.Publisher.Blah | 153

**Comment by nblumhardt** [comment]
Thanks for the follow-up. If you're still having trouble with this, it might be one to open on the _Serilog.Sinks.ApplicationInsights_ repository, I don't think it's a core Serilog issue (just creating a new ticket pointing back to this one should cover all of the needed info).

**Comment by bensmith009988** [comment]
This is very much still an issue. I cannot find a way to destructure any collection property that is defined as an anonymous type, when given a complex object. 

For example:

**Class Definition:** 
```
 public class LogRequest
 {
     public string? LogMessage { get; set; }

     public Dictionary<string, object>? AdditionalMetaData { get; set; }
 }
```

**Logging Method in .NET Web API Controller:** 
```
[HttpPost("information")]
public void LogInformation([FromBody] LogRequest requestData)
{
    logger.Information("{@requestData}", requestData);
}
```

**JSON Payload of Request** 
```
{
    "logMessage": "Test log message",
    "additionalMetaData" :{
        "SomeMetaData": 1234,
        "TimeOfLog": "00:00",
        "SomeOtherObject": {
            "SomeProperty": "Some Value",
            "SomeOtherMetaData": 1234
        }
    }
}
```

**Serilog's interpretation of this object:** 
```
requestData: {
  AdditionalMetaData: {
	SomeMetaData: 1234,
	SomeOtherObject: [ 
	  [[]],
	  [[]]
	],
	TimeOfLog: 00:00
  },
  LogMessage: Test log message
}
```

As you can see, any complex object that is defined by the incoming payload, within the collection, expressed as an anonymous type, cannot be properly destructured by Serilog. 

I will mention that in this example, I am Deserializing the incoming JSON payload using Newtonsoft.Json NuGet package. The "SomeOtherObject" is being deserialized into a JObject type. 

The System.Text.JSon deserialization has the same effect. Serilog interprets the object a little bit differently, but it is still unable to destructure complex objects within an anonymous type, defined as a property in a collection.
