### ISSUE TITLE
Agree upon a common JSON format with other structured logging frameworks

### ISSUE THREAD

**Issue by bitc** [serilog/serilog#1184]
Hi! I've recently become more interested in structured logging, and have looked into a few structured logging libraries.

You get amazing power when you dump the logs from all of your different systems and sources into a centralized log store, and can then view and analyze them as one whole.

What I've noticed though is that the various structured logging frameworks all save JSON log entries in similar, but slightly different schemas.

For example, for storing timestamps, some libraries uses the JSON key "time", while other libraries use "timestamp" or "at". Another area where libraries differ is in how they store log levels.

These small differences cause friction when analyzing the central logstore, which contains structured logs that have been collected from multiple systems/microservices.

For example, one service might tag warnings with the string "WARN" while another with the string "warning". So if I want to view only warnings, I need to take this difference into account and write a tricky "OR" filter expression.  This may seem minor, but these small inconsistencies cause great pain.

I believe that these small differences between the various structured logging libraries exist not because of any strongly held opinions, but simply because mainstream structured and centralized logging is still relatively young, and so there is no standard or common consensus.

I think it would be very beneficial to everyone if we could all unite around a common format.

To get things started, I have created a GitHub repository to centralize discussions here: <https://github.com/bitc/structured-logging-schema>

It contains a comparison between several structured logging libraries, summarizing the differences between them all. This can hopefully be a start to help us arrive at common ground.

I encourage the authors of this library (and anyone else who has an opinion) to participate in the discussion!

Discussion takes place in the issues for this repo: <https://github.com/bitc/structured-logging-schema>

**Comment by nblumhardt** [comment]
https://xkcd.com/927/

:-)

Personally, although I wish you all the best and I'm glad to hear others are becoming more interested in structured logging, I don't think there's any chance whatsoever of settling on a single standard for this.

Serilog, for example, already has [a "standard" of sorts](https://github.com/serilog/serilog-formatting-compact), along with docs, [a reader implementation](https://github.com/serilog/serilog-formatting-compact-reader), some [tooling](https://github.com/datalust/clef-tool), and fledgling support in a few other places (an ASP.NET Core file logging implementation, for example). The amount of effort required to stand this up was considerable, and any new standard would also need these things.

Even though the standard we have is "optimal" for Serilog, it _still_ doesn't suit everyone, even Serilog users, so it seems even less likely that we'll achieve a single standard across multiple libraries.

Would a more valuable project here be a set of adapters that could transform any arbitrary format (Elastic's, CLEF, GELF, NLog's etc.; newline-delimited vs streamed vs array-format) into any other? This would make interoperability easier, and is achievable without an enormous amount of collaboration and debate (though it would still be a formidable task).

HTH,
Nick
