### ISSUE TITLE
[New Feature] Simplify Filters Setup by Introducing Filters Buider

### ISSUE THREAD

**Issue by IharYakimush** [serilog/serilog#1191]
Currently it might be hard to configure filters in complex scenarios because OOTB configuration limited to  "ByExcluding()" and "ByIncludingOnly()" methods.

For example at the same time I want to
1. Exclude logs from "Microsoft.EntityFrameworkCore" source with level Verbose and Information 
2. Exclude logs from "Microsoft.AspNetCore" source with level Verbose and Information, however
  2.1 Keep logs from "Microsoft.AspNetCore.DataProtection" source even if Level is Information
  2.1 Keep logs from "Microsoft.AspNetCore.Hosting" source based on "requestPath" property

To achieve this I have to write a code similar to
```
 lc.Filter.ByExcluding(
        e =>
        {
            bool result = false;

            result |= Matching.FromSource("Microsoft.EntityFrameworkCore").Invoke(e)
                      && e.Level < LogEventLevel.Warning;

            result |= Matching.FromSource("Microsoft.AspNetCore").Invoke(e)
                      && e.Level < LogEventLevel.Warning;

            result &= !(Matching.FromSource("Microsoft.AspNetCore.Hosting").Invoke(e)
                        && !Matching.WithProperty<string>("requestPath", r => r.Length < 2).Invoke(e));

            result &= !(Matching.FromSource("Microsoft.AspNetCore.DataProtection").Invoke(e)
                        && e.Level >= LogEventLevel.Information);

            return result;
        });
``` 

I would propose to introduce some sort of a builder for filters configuration which will manage combining of various simultaneous conditions to simplify the process.

**Comment by tsimbalar** [comment]
Hi,

you may want to take a look at https://github.com/serilog/serilog-filters-expressions that introduces a nice filtering syntax.

**Comment by IharYakimush** [comment]
Thanks for pointing to filter expressions. It might be useful in case of storing filter configuration in config files.

However I have some concerns to use them. Instead of complex C# code I will have complex text expression with all text expression limitations.

The idea was to simplify applying of filters, not using another complex approach. By complexity in this case I mean amount of logical operators and its combining.

**Comment by skomis-mm** [comment]
@IharYakimush I think your best bet will be using minimum level with overrides here:
https://github.com/serilog/serilog-settings-appsettings#adding-minimum-level-overrides

**Comment by skomis-mm** [comment]
@IharYakimush  probably the best bet here will be using minimum level with overrides with additional filtering if required:
https://github.com/serilog/serilog-settings-appsettings#adding-minimum-level-overrides

**Comment by IharYakimush** [comment]
Thanks @skomis-mm, minimum level with overrides looks promising

**Comment by tsimbalar** [comment]
As skomis-mm mentioned, what you are trying to acomplish looks a lot like the *minimum level override* feature.

Also, you **don't have to** use the `Matching.` methods in `.Filter.ByExcluding(...)` parameter. You can directly access the contents of the event and filter based on that : 

```csharp
.Filter.ByExcluding(e => {
    // TODO: should check for key existence in dictionary
    if (e.Properties[Constants.SourceContextPropertyName] == "Microsoft.EntityFrameworkCore" && e.Level < LogEventLevel.Warning)
        return true; // will be filtered out
    if (e.Properties[Constants.SourceContextPropertyName] == "Microsoft.AspNetCore" && e.Level < LogEventLevel.Warning)
        return true; // will be filtered out
    // won't be filtered out -> will be included
    return false;
});
```

You can just express the code however you want, but will need to be a bit careful accessing properties that may or not be missing. If it gets complicated, I would recommend moving it to a separate method, and possibly introduce extension methods to make it more readable ...
