### ISSUE TITLE
SilentLogger not a singleton, reference comparision with Logger.None

### ISSUE THREAD

**Issue by mlehmk** [serilog/serilog#1195]
This relates to the Serilog core, this repository

**Does this issue relate to a new *feature* or an existing *bug*?**
It is debatable if this is a new feature or an existing bug. It is also framework independent.

**What version of Serilog is affected?  Please list the related NuGet package.**
Versions from Fixes #1105 up until the current dev as of now https://github.com/serilog/serilog/commit/fcd0c8bb128a853b48869dd7821b3e8661963319

**Please describe the current behavior?**
The SilentLogger instance of Log.Logger is not the same reference as Logger.None, thus it is impossible to determine if Log.Logger has been initialized or not.

**Please describe the expected behavior?**
If Log.Logger has not been initialized, it should be set to the same instance as Logger.None, so Object.ReferenceEquals(Log.Logger, Logger.None) returns a boolean that identifies, whether Log.Logger is uninitialized or closed.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
To reproduce, test whether at program start Object.ReferenceEquals(Log.Logger, Logger.None) returns true or false. It should return true until Log.Logger has been assigned a newly created logger. It should also return true when Log.CloseAndFlush() has been called.

My current workaround for this is to initialize Log.Logger = Logger.None at program start and whenever after I used Log.CloseAndFlush()

**Comment by nblumhardt** [comment]
Thanks for the feedback; this one looks like it should be straightforward to address, if anyone's interested in picking it up.
