### ISSUE TITLE
Test 'LoggerShouldNotReferenceToItsConfigurationAfterBeingCreated' fails

### ISSUE THREAD

**Issue by ie-zero** [serilog/serilog#1196]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Current development branch  (commit fcd0c8bb128a853b48869dd7821b3e8661963319)

**What is the target framework and operating system? 
- [x] netCore 2.0 (2.1.302)
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Test fails

**Please describe the expected behavior?**
Test to pass

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
When I execute the tests, even after a clean build, the test fails. The same test passes on AppVeyor. 

The development machine is Windows 7 Ultimate, running on Mac via Boot Camp.

Any ideas on how we can approach this will be greatly appreciated.

**Comment by ie-zero** [comment]
Apparently, I get the same failure on Windows 10 with .NET Core 2.1.101

**Comment by skomis-mm** [comment]
@ie-zero this test should pass on `Release` configuration. Is that your case?

**Comment by ie-zero** [comment]
Yes, this is the case. The test passes on ```Release``` configuration. Could you point me to the right direction why this is happening please?

**Comment by skomis-mm** [comment]
In the Debug build local variables are temporarily rooted, so their lifetimes are extended thats why GC.Collect() have no effect. Its because the need to be able inspect them under the debugger.

**Comment by nblumhardt** [comment]
FWIW it might be possible to get this passing in Debug by introducing a function that returns `(logger, wr)` (or some permutation of that idea).

**Comment by ie-zero** [comment]
Thank you very much for your explanation. It makes sense now.
