### ISSUE TITLE
[sinks]: Datadog Logs Sink

### ISSUE THREAD

**Issue by ajacquemot** [serilog/serilog#1200]
Hello,

We've been working on a [sink](https://github.com/DataDog/serilog-sinks-datadog-logs) to ship logs to Datadog, could you please add it to the list of [provided sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks).

Thanks a lot.

**Comment by merbla** [comment]
Thanks @ajacquemot!

All done - https://github.com/serilog/serilog/wiki/Provided-Sinks
