### ISSUE TITLE
Can SelfLog be Enabled by default?

### ISSUE THREAD

**Issue by MNF** [serilog/serilog#1201]
**A few questions before you begin:**

> Is this an issue related to the Serilog core project?
Yes

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
v2.7.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0

**Please describe the current behavior?**
As noted in http://www.blog.darcnet.avx.pl/2017/07/09/serilog-debugging/
“When setting up SeriLog, beware! It fails silently!”
Unfortunately, it takes time (especially for new users) to recognize, how to enable SelfLog to view serilog internal errors.

**Please describe the expected behavior?**
It will be good if SelfLog will be Enabled by default and output to some developer friendly targets (e.g. console and Debug output window). It will help to quickly identify configuration errors.
E.g. include by default
Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));

If someone doesn’t like the default output, they can call SelfLog.Enable to specify alternative output, e.g. file.

**Comment by merbla** [comment]
Thanks @MNF for the note.

My initial thought is that our documentation and samples might be the best place to start to make the on boarding process easier for new developers.

In general, the effort to setup Serilog is a once off cost.  We have a open issue relating to documentation over at #1164 and of course we can improve the wiki e.g. https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics#selflog & https://github.com/serilog/serilog/wiki/Getting-Started#example-application

**Comment by MNF** [comment]
Most of the people do not read full documentation, but just started with readme example. If SelfLog.Enable will be included in the  readme example, it will be a step forward for those, who made some configuration incorrect, and have to spend a time to investigate it. However consider dozens of examples on internet, that do not have such statement added. 
And why each program should repeat the code, that can be included by default. Advantage of having serilog errors  visible by default is that developers will see them immediately in the expected outputs(debug and console).There is no disadvantages, as if no errors occurred, no messages will be shown.
It doesn’t sound correct, that the library, one of the purposes is to make errors visible, by default hides their own errors.

>>>>the effort to setup Serilog is a once off cost.
Why not to reduce this cost for hundreds new users?
Also my team( as many others) are creating microservices, and each one has different configuration that potentially can have different errors. So it’s not “once off” work for individual developer.

**Comment by nblumhardt** [comment]
@MNF thanks also for the note :+1:

The challenge is then to prevent this configuration being inadvertently copied into production code, where console writes in particular can be very slow and/or serialized.

I wonder if we can make it much easier for anyone having trouble to find the debugging and diagnostics wiki page? Perhaps we include a section like the Seq sink's README [troubleshooting](https://github.com/serilog/serilog-sinks-seq#troubleshooting) section in more places?

**Comment by merbla** [comment]
@MNF out of interest, did you find the issues/errors were in a specific area?

* core
* sink
* configuration
* enrichment

**Comment by MNF** [comment]
@merbla, we are using appsettings.json and had couple of problems in sinks configuration.

**Comment by MNF** [comment]
@nblumhardt, 
If I would problems in production, I want to see them as well. SelfLog records only exceptions(am I right?) so they shouldn’t be too many.But if there are too many, more reason to see them.

However if you add by default logging errors only to Debug output, it will improve experience for many developers.
The idea to put information to Troubleshooting section not always work, because often people who don’t see any log messages assume, that their application does not have any issues and there is no reasons to troubleshoot, when in reality they need to troubleshoot both logging and application errors.

**Comment by michael-freidgeim-webjet** [comment]
Side note: .Net Core WebHost.CreateDefaultBuilder creates  2 loggers
        ConsoleLoggerExtensions.AddConsole(logging);
        DebugLoggerFactoryExtensions.AddDebug(logging);
which is consistent with my original suggestion.

**Comment by nblumhardt** [comment]
@MNF thanks for the reply. It's good feedback, but the contract of SelfLog (no overhead unless it's explicitly enabled) avoids a whole lot of possible failure modes (memory, CPU, contention, loops). I don't think we should make changes here. Thanks again, though! Appreciate you taking the time to lay out the possibilities :+1:
