### ISSUE TITLE
Community Project: Serilog.Settings.Delegates

### ISSUE THREAD

**Issue by MV10** [serilog/serilog#1205]
Offering up my new-ish package for inclusion on the Community Projects Wiki page. The short explanation is that you can filter or destructure (transform) log entries with snippets of c# script stored in configuration. 

_Serilog.Settings.Delegates_

https://github.com/MV10/serilog-settings-delegates

https://www.nuget.org/packages/Serilog.Settings.Delegates

If you're _really_ bored, how "Hold my beer, watch this!" became a NuGet package:
https://github.com/serilog/serilog-settings-configuration/issues/106

**Comment by merbla** [comment]
Thanks @MV10, the [community projects page](https://github.com/serilog/serilog/wiki/Community-Projects) has been updated.
