### ISSUE TITLE
Calls to ForContext ignored, not enriching logs with properties?

### ISSUE THREAD

**Issue by SeanKilleen** [serilog/serilog#1207]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

v2.5.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Calls to `.ForContext("Property", "Value") do not enrich log messages for that context/scope.

**Please describe the expected behavior?**

Calls to ForContext actually have those values radiated to my log sinks, e.g. Seq.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

I'm having a strange issue with Serilog where calls to `ForContext` in a given method appear to be ignored and not Enrich the logs. However, other packages are successfully enriching the logs (e.g. logs are enriched with http request ID, machine name, etc.). We're successfully using Serilog in general with Seq now, it's just the ForContext additions that appear to be not working.

I'm using Serilog 2.5.0 and wiring it up via Autofac. 

In my Autofac module, I have 

```csharp
builder.Register(c => WireUpSerilog()).As<ILogger>().InstancePerLifetimeScope();`
```

The contents of `WireUpSerilog()` boil down to:

```csharp
            var levelSwitch = new LoggingLevelSwitch(initialMinimumLevel: initalMinimumLevel);
            var logger = new LoggerConfiguration()
                .WriteTo.Seq(seqServerUrl, apiKey: seqApiKey, controlLevelSwitch: levelSwitch)
                .MinimumLevel.ControlledBy(levelSwitch)
                .Enrich.WithProperty("ApplicationName", "Redacted")
                .Enrich.WithProperty("Environment", envName)
                .Enrich.WithEnvironmentUserName()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.With(new HttpRequestIdEnricher())
                .WriteTo.RollingFile(
                    formatter: new JsonFormatter(), 
                    pathFormat: rollingFilePath, 
                    levelSwitch: levelSwitch, 
                    fileSizeLimitBytes: null, 
                    retainedFileCountLimit: retainedFileCount, 
                    buffered: rollingFileBuffered)
                .ReadFrom.AppSettings() // app settings will override these values if present
                .CreateLogger();
```

In my WebAPI Controller method,  I have:

```csharp
            this.logger.ForContext("TestProperty", "TestValue");
            this.logger.Debug("Starting the process of adding a beneficiary.");
```

I would expect at that point that the debug message would contain the test property/value pair, but it does not.

**Comment by SeanKilleen** [comment]
Update: Just to rule it out, I installed the `AutofacSerilogIntegration` package and changed my registration code to:

```
            Log.Logger = WireUpSerilog();
            builder.RegisterLogger();
```

I am still receiving logs -- now with some nice additional context for the class name -- but my calls to `ForContext` within my WebAPI method still appear to be ignored, and do not show up within Seq.

**Comment by khellang** [comment]
You're just throwing away the logger with the added context, no? I think it should be either

```csharp
this.logger = this.logger.ForContext("TestProperty", "TestValue");
this.logger.Debug("Starting the process of adding a beneficiary.");
```

or

```csharp
var contextualLogger = this.logger.ForContext("TestProperty", "TestValue");
contextualLogger.Debug("Starting the process of adding a beneficiary.");
```

or even

```csharp
this.logger.ForContext("TestProperty", "TestValue").Debug("Starting the process of adding a beneficiary.");
```

**Comment by tsimbalar** [comment]
Hi Sean,

actually, the `ForContext()` methods return a new logger, with "extra enriching", but do not affect the `logger` they are called on.

Basically when you do `this.logger.ForContext("TestProperty", "TestValue");` , `this.logger` is not changed at all.

You can either : 

1. chain method calls if you only want to enrich once : 

```csharp
this.logger.ForContext("TestProperty", "TestValue")
           .Debug("Starting the process of adding a beneficiary.");
```

2. store the `ForContext()`ed logger in a separate variable : 
```csharp
var contextLogger = this.logger.ForContext("TestProperty", "TestValue");
contextLogger.Debug("Starting the process of adding a beneficiary.");
```

3. use the `LogContext` if you want all the log events generated in a given scope to be enriched ... See wiki page : https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext

I hope this helps !

**Comment by SeanKilleen** [comment]
Ahhhh, one more look at the docs tells me I'm not doing this quite correctly.

Rather than `logger.ForContext`, apparently I need to use `LogContext.PushProperty`. It feels odd to use a global context rather than adding it to the current logger which has a lifetime scope, but at least I can resolve the issue that way. 

Doing some testing to see if that resolves the issue.

**Comment by SeanKilleen** [comment]
@khellang @tsimbalar this makes perfect sense, and you're right, I totally missed it -- I thought it was modifying internal logger state, not returning a new logger. 

I'll go that route rather than using `LogContext.PushProperty`, which also worked but feels more clunky in my specific scenario.

Thank you both!
