### ISSUE TITLE
[New Feature] Conditional messages

### ISSUE THREAD

**Issue by FaustoNascimento** [serilog/serilog#1210]
A couple of times, I find myself doing something like...

    if (succeeded == true)
    {
        Log.Information("Yay! Something succeeded!");
    }
    else
    {
        Log.Error("Buh! Something failed. Not good. Go and fix it");
    }

Quite often you'll have something else inside those if statements like this, but not necessarily always.

It would be nice to have conditional messages. Basically an extension method with a Func<bool>, so that the following can be done:

    Log.When(() => succceeded).Information("Yay! Something suceeded!");
    Log.When(() => !succeeded).Error("Buh! Something failed. Not good. Go and fix it");

In this case I used the static `Log` class as an example (so here it wouldn't really be an extension method), but the same could be easily done as an extension method that accepts a `ILogger` and returns an `ILogger` as well. When the condition is false, it should return a `SilentLogger` instance to ensure it's never `null`.

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍 

This comes up against the balancing design consideration of keeping the API minimal/focused - I don't think we will take it in this direction, but appreciate the input.
