### ISSUE TITLE
Feature: Location Of Log File

### ISSUE THREAD

**Issue by sktyjd** [serilog/serilog#1213]
I am currently using Serilog in my Xamarin multi-platform project. Since I am using a file based Sink (Rolling File), it would be nice to know where the file is actually located based on a property of the Logger. This at least helps in debugging in where to look for the log based upon the platform the app is running on. 

I would imagine this would be helpful on all supported libraries. I would ask in the RollingFile project, but this seems like at least all file based sinks could use it.

**Comment by merbla** [comment]
Hi @sktyjd,
This issue probably best lives in the  [File Sink](https://github.com/serilog/serilog-sinks-file), not sure the [Xamarin Sink](https://github.com/serilog/serilog-sinks-xamarin) would cater for this setup.

This repo is just for the core issues in the Serilog library.

**Comment by merbla** [comment]
@sktyjd closing this one out, feel free to raise an issue in one of the repos above.
