### ISSUE TITLE
Community Project: Serilog.Sinks.ExcelDnaLogDisplay

### ISSUE THREAD

**Issue by caioproiete** [serilog/serilog#1214]
I'd like to add my new-ish sink **[Serilog.Sinks.ExcelDnaLogDisplay](https://github.com/caioproiete/serilog-sinks-exceldnalogdisplay/)** to the [Provided Sinks Wiki page](https://github.com/serilog/serilog/wiki/Provided-Sinks).

This sink writes Serilog events to Excel-DNA's `LogDisplay`, which is a simple log viewer included in Excel add-ins built with Excel-DNA, that allows end-user of the add-in to see log messages.

[![image](https://user-images.githubusercontent.com/177608/45261966-fb9ab100-b3e2-11e8-8afc-946be983e576.png)](https://github.com/caioproiete/serilog-sinks-exceldnalogdisplay/)

[![image](https://user-images.githubusercontent.com/177608/45261982-50d6c280-b3e3-11e8-9013-06f7b82174c7.png)](https://github.com/caioproiete/serilog-sinks-exceldnalogdisplay/)

[![image](https://user-images.githubusercontent.com/177608/45261984-53d1b300-b3e3-11e8-8b15-7338e44a68bd.png)](https://github.com/caioproiete/serilog-sinks-exceldnalogdisplay/)

---

### Serilog.Sinks.ExcelDnaLogDisplay
* Source code: https://github.com/caioproiete/serilog-sinks-exceldnalogdisplay/
* NuGet package: https://www.nuget.org/packages/Serilog.Sinks.ExcelDnaLogDisplay/

**Comment by merbla** [comment]
Thanks @caioproiete, wiki page updated.
