### ISSUE TITLE
Pushing LogContext Properties with different values on different threads

### ISSUE THREAD

**Issue by BoasE** [serilog/serilog#1216]
Hi

I'm using serlog inside a webapplication which is using in one area threads.

Now I was wondering what is the intended way to push isolated properties.

For example, If my batch import processes multiple customers each in a dedicated thread. and I want to push the customerid for each for each logging. What is the intended way to do this?

In PseduoCode

```
Parallel.foreach(var customer in customers)
{
    using(LogContext.PushProperty("Customer",customer.id))
   {
        Log.Warning("foo")
   }
}
```

Is this meant to work or what to I have to do to get the scenario thread safe?

**Comment by aidansteele** [comment]
That code will work. `LogContext` uses `AsyncLocal`, which will mean it Just Works™ for threading and async-await scenarios. 

If you're interested, the exact code is here: https://github.com/serilog/serilog/blob/9a46e68d3e224b965f4ac2665fd379ae9568d6b4/src/Serilog/Context/LogContext.cs#L56

**Comment by nblumhardt** [comment]
As mentioned above, this should work fine today, please let us know if you hit issues with it @BoasE 👍

**Comment by tangdf** [comment]
```csharp
    class Program
    {
        private static ILogger s_logger;
        static void Main(string[] args)
        {
          
            s_logger = new LoggerConfiguration()
                .WriteTo.Console(new JsonFormatter()).Enrich.FromLogContext()
                .CreateLogger();

            using (LogContext.PushProperty("Main ThreadId", Thread.CurrentThread.ManagedThreadId))
            {
                var task = Task.Run(Log);
                Task.WaitAll(task);
            }
            
            Console.ReadLine();
        }

        private static void Log()
        {
            s_logger.Information("Log {Current ThreadId}", Thread.CurrentThread.ManagedThreadId);
        }
    }
```
Output：
```json
{"Timestamp":"2019-10-11T12:18:51.1488404+08:00","Level":"Information","MessageTemplate":"Log {CurrentThreadId}","Properties":{"CurrentThreadId":4,"MainThreadId":1}}
```
 The "MainThreadId" property in thread 1，output in thread 4.

- Version 3.1.1
- [ ] Bug
- [ ] netCore 3.0

**Comment by nblumhardt** [comment]
@tangdf this is as expected, `LogContext` is not thread-local, but rather is attached to the current execution context, and this flows in several places including `Task.Run`.

See the answer here for a way to suppress this: https://stackoverflow.com/a/52221950/138206

HTH,
Nick

**Comment by tangdf** [comment]
What can be done to solve  similar problem?

**Comment by nblumhardt** [comment]
The same solution (`ExecutionContext.SuppressFlow()`) should work for `LogContext`, too - though I've never tried it personally. HTH.

**Comment by tangdf** [comment]
I think the framework should solve this problem.

**Comment by nblumhardt** [comment]
Thanks for the reply! I agree that there are some quirks in the behavior of `ExecutionContext`/`AsyncLocal` that can be surprising. On the plus side, it's a well-understood part of .NET that's tested thoroughly, and integrates correctly with tricky features like `async`/`await`, on multiple platforms. It's a very tough wheel for us to reinvent in Serilog itself, so sticking with `AsyncLocal` seems a reasonable choice to me at this point.

**Comment by nblumhardt** [comment]
Sorry @tangdf, I forgot completely about `LogContext.Suspend()`, which was a fairly recent addition:

```csharp
using (LogContext.Suspend())
{
   Task.Run(Log); // etc
}
```
