### ISSUE TITLE
Add Repository Url

### ISSUE THREAD

**Issue by MaximRouiller** [serilog/serilog#1219]
This is the tracking issue to manage PRs that are going to be made to all child repositories to ensure that everything is merged before we close this one.

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

All including latest and `-dev` versions.

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [X] netCore 1.0
- [X] 4.7
- [X] 4.6.x
- [X] 4.5.x

**Please describe the current behavior?**

Packages found [on NuGet](https://www.nuget.org/packages/Serilog/) do not implement the Repository Url.

**Please describe the expected behavior?**

Add the Repository Url as described below. 

https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html

**Comment by MaximRouiller** [comment]
All of those pretty much covers all projects that received an update in the past year.

If other projects under the serilog org want to do it, they can follow the above examples no problems. I just don't see the interest in creating PR for projects that haven't received a single commit in the past 2+ years like CouchDB.

**Comment by nblumhardt** [comment]
Cool, thanks @MaximRouiller :+1:

**Comment by nblumhardt** [comment]
Since we have active PRs in the remaining repos, I think we can close this to minimise clutter over here in serilog/serilog. Thanks for all the effort @MaximRouiller !
