### ISSUE TITLE
Serilog GitHub wiki- can editing be enabled to all users?

### ISSUE THREAD

**Issue by MNF** [serilog/serilog#1221]
I wanted to made a minor change  ( add a link to  https://github.com/Suchiman/SerilogAnalyzer) on https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics wiki page and noticed that edit is not enabled.
 Wiki is very easy to contribute, it can give your users ability to provide more details/examples  without any effort from yourself. To raise issues for wiki documentation is more annoying process, and many people will not do it. 
The GitHub Wiki doesn’t support pull requests, because it suppose to be edited directly.
Wiki is supposed to be maintained by community, not by authors of the project, it doesn't expect formal review process. Wikipedia and StackOverflow rely on the community to maintain content and fix what is wrong. It is not an official documentation and you don't need to spend your valuable time to review content.

 If you have a concern that some information may be inaccurate, include on home page a note that wiki pages are not endorsed by owners of the project and maintained by the community.

**Comment by merbla** [comment]
Thanks @MNF for the note.

We are trying to collate our documentation limitations and shortfalls (including the wiki setup) over at #1164.  In the short term I have added @Suchiman tool over at https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics.
