### ISSUE TITLE
Microsoft.Extensions.Logging.ILogger Sink

### ISSUE THREAD

**Issue by JonCanning** [serilog/serilog#1222]
TraceWriter has been deprecated in Azure Functions in favour of ILogger, so this sink offers a replacement

https://github.com/TinyBlueRobots/Serilog.Sinks.ILogger

**Comment by patricknolan** [comment]
Hi @JonCanning unfortunately this only targets  .NETFramework 4.6 and not .NETStandard

**Comment by JonCanning** [comment]
It only targets netstandard 2.0

https://github.com/TinyBlueRobots/Serilog.Sinks.ILogger/blob/master/Serilog.Sinks.ILogger/Serilog.Sinks.ILogger.csproj#L6

**Comment by nblumhardt** [comment]
Listed, thanks Jon!
