### ISSUE TITLE
String.Interpolation

### ISSUE THREAD

**Issue by aensidhe** [serilog/serilog#1225]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

I read [this post](https://nblumhardt.com/2015/01/c-6-string-interpolation-and-serilog/) and [this issue](https://github.com/serilog/serilog/issues/639)

Blog post states two points against string interpolation:
1. A good variable name is not necessarily a good property name
2. Holes don’t always have obvious names

Let's look onto this code:
```csharp
using System;

namespace String.Interpolation
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = 123;
            var b = true;
            var c = "adf";
            F($"{a:Int}, {b:Bool}, {c:Str}");
            F($"{a}, {b}, {c}");
        }

        private static void F(FormattableString s)
        {
            Console.WriteLine();
            Console.WriteLine(s.Format);
            foreach (var o in s.GetArguments())
            {
                Console.WriteLine(o);
            }
        }
    }
}
```

It's produce output:

```
{0:Int}, {1:Bool}, {2:Str}
123
True
adf

{0}, {1}, {2}
123
True
adf
```

We can parse and pass `s.Format` and arguments from `s.GetArguments()` to usual `ILogger` methods and have current behaviour with mitigated point 1 about names.

Point number 2 (about holes) is not mitigated, but can be via analyzer for compiler.

I think that will be great addition to great library.

All credits should go to @kekekeks, if any.

**Comment by adamchester** [comment]
Thank you for your suggestion! I once wanted to do this too.

What I came to realise is that it would further discourage the use of better variable names, and decrease the motivation to use better message templates, and decrease the opportunity to learn about them.

**Comment by adamchester** [comment]
Also, it looks a bit like an abuse of the `Format` property, can you comment on that please?

**Comment by aensidhe** [comment]
> What I came to realise is that it would further discourage the use of better variable names, and decrease the motivation to use better message templates, and decrease the opportunity to learn about them.

That probably needs clarification since it's not clear why it will decrease motivation and how current implementation enforces it, because what I did several times is remove string interpolation from logging and replace it with templates. People are accustomed to string interpolation and they write code like this:

```csharp
Log.Logger.Info($"Whatever I {need} to log"); // let's not discuss usage of global logger, it's out of scope
```

And you need to change it everywhere to:
```csharp
Log.Logger.Info("Whatever I {need} to log", need);
```

if you want to use the power of serilog and structured logging. Because if you don't, people will just log strings and will parse them afterwards.

I don't think that effort to write good template is different in those two cases:
```csharp
Log.Logger.Info($"Whatever I {need:Reason} to log");
Log.Logger.Info($"Whatever I {Reason} to log", need);
```

About the learning point. Unless you'll have some analyzer that fails compilation by default on bad templates, only small amount of people will learn about templating. And you can do that for string interpolation:
```csharp
Log.Logger.Info($"Whatever I {need:Reason} to log"); // OK
Log.Logger.Info($"Whatever I {need} to log"); // Compile fails
```

People will be able to disable it or lower severity of compile errors in their projects.

Also, those methods can be provided as an extensions methods, probably and via separate package, if you don't want include it to core from the start. We can measure adoption of feature this way.

> Also, it looks a bit like an abuse of the Format property, can you comment on that please?

It's used in EF core that way. [Docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters), [source](https://github.com/aspnet/EntityFrameworkCore/blob/b969be3431415dfe224dfb3c7804592bb4b6c661/src/EFCore.Relational/RelationalQueryableExtensions.cs#L62)

**Comment by adamchester** [comment]
> Also, those methods can be provided as an extensions methods, probably and via separate package, if you don't want include it to core from the start. We can measure adoption of feature this way.

Seems like a reasonable thing to try in this case :+1:

**Comment by nblumhardt** [comment]
> Unless you'll have some analyzer that fails compilation by default on bad templates,

See: https://github.com/Suchiman/SerilogAnalyzer - there's a NuGet-installable package that will do this.

Definitely let us know if you are able to publish the extension package, interested to hear how it turns out; we can list it on the community packages section of the wiki 👍

**Comment by khellang** [comment]
There's also the problem with [`string` overloads being picked over `FormattableString` overloads](https://github.com/dotnet/roslyn/issues/46):

> We generally believe that libraries will mostly be written with different API names for methods which do different things. Therefore overload resolution differences between FormattableString and String don't matter, so string might as well win. Therefore we should stick with the simple principle that an interpolated string is a string. End of story.

Also

> Some library APIs really want consumers to use FormattableString because it is safer or faster. The API that takes string and the API that takes FormattableString actually do different things and hence shouldn't be overloaded on the same name. Library authors will want to lead people to use interpolated strings, hence it should have a shorter name.

If these methods were introduced, they'd need different names in order to pick the correct overload.

**Comment by nblumhardt** [comment]
Closing as we're not likely to act on this in the core project right now, but keep us posted if you explore it further, @aensidhe!

**Comment by artemious7** [comment]
Here's my solution
https://stackoverflow.com/questions/61816775/c-sharp-serilog-how-to-log-with-string-interpolation-and-keep-argument-names-in/61816776#61816776

**Comment by Drizin** [comment]
I've just published a library (with extensions to Serilog, NLog, and Microsoft ILogger) which allows writing log messages using interpolated strings and yet defining the property names through different syntaxes. 
Would love to hear some feedback.
https://github.com/Drizin/InterpolatedLogging
