### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1227]
Hi all!

Blazor is an interesting new WASM runtime target based on .NET Standard 2.0. I'm not personally planning to use Blazor in the near future, but I'm intrigued by the platform and think it will probably play a significant part in future .NET web dev.

Just as we did with .NET Core, I think we should aim to be there and ready at RTM, so that we can figure out the best story for supporting Serilog there, and pass useful feedback on to the Blazor devs before v1 is set in stone.

I spiked out some simple console and HTTP sinks in https://github.com/nblumhardt/serilog-blazor; @wtulloch has done something slightly different to support the console in https://github.com/wtulloch/Blazor-Serilog-sink.

As mentioned above, there's some basic starting-point code already assembled; I think the first packages to tackle are:

 * _Serilog.Sinks.BrowserConsole_ - just like the regular console sink, but as native/integrated as possible with the browser environment (_Serilog.Sinks.Console_ doesn't currently work, because of unsupported APIs, though in the future we might fix that)
 * _Serilog.Sinks.BrowserHttp_ - a streamlined experience for sending logs back to the origin server, as batched CLEF/JSON payloads, with support for dynamic level control (have the server control the logging level used by the client)
 * _Serilog.AspNetCore.HttpLogIngestion_ - the server-side companion to _BrowserHttp_, which receives log batches from the client and sends them through a server-side Serilog pipeline, built as ASP.NET Core middleware

Two more worth considering - a WebSockets sink for the client-side, and WebSockets log ingestion middleware for the server.

If you've got an interest in Blazor, and especially if you have a project in mind for it, this is the ticket for discussion. We can use it as an informal "working group" to organize ourselves - I'm going to set up repositories and import some initial code for the first three packages, I'll post an update here with links when they're ready to go.

Beyond that, I think we should find someone among us to champion good Blazor support and manage the first few packages - things are moving fairly quickly and it'd be worth having dedicated eyes on it :-)

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-sinks-browserconsole/pull/1

**Comment by nblumhardt** [comment]
I think the value of keeping this issue open is diminishing; if anyone's keen to jump in and champion it then please shout :-)

**Comment by kevingates** [comment]
So there isn't any support for .Net Core 3.1 Blazor Server-Side?

**Comment by dahlsailrunner** [comment]
@kevingates I would think that the standard ASP.NET Core Serilog stuff would work here.  Any C# code that you want to run would be running server-side, and you could just use things like `Log.Information(...)` or whatever to create log entries, and the standard Serilog setup in Program.cs would wire up the logging itself.
