### ISSUE TITLE
SelfLog only for failures or OK for warnings?

### ISSUE THREAD

**Issue by MV10** [serilog/serilog#1230]
Quick question from the perspective of a sink author/contributor:

Is the intent of `SelfLog` only to ouput exceptions and other messages of a critical or failure nature, or would it also be acceptable for a sink to emit warnings this way (in my case, the use of deprecated configuration features)?

Obviously good judgement would be called for -- nobody wants high-volume spam ("OMG you used deprecated method XYZ!" on every event).

Perhaps @nblumhardt or @merbla or @tsimbalar can chime in? Thanks!

**Comment by tsimbalar** [comment]
We are already using it in places to notify about usage of unsupported features/edge-cases like this one :  

https://github.com/serilog/serilog/blob/5b0569ac42363dffced9854b0406ca338248f5fc/src/Serilog/Configuration/LoggerSinkConfiguration.cs#L135-L136


We even have tests for those cases : 

https://github.com/serilog/serilog/blob/5b0569ac42363dffced9854b0406ca338248f5fc/test/Serilog.Tests/Core/ChildLoggerKnownLimitationsTests.cs#L13-L37


So I think it is a pretty reasonable use of the `SelfLog` :)

**Comment by MV10** [comment]
Awesome, thanks TS!
