### ISSUE TITLE
Combining log context properties with positional properties

### ISSUE THREAD

**Issue by cocowalla** [serilog/serilog#1231]
This is a question about how to combine log context properties with positional message template properties. I've found similar issues here, but none that approach it from the same angle.

Take the following example:

```
using (LogContext.PushProperty("Myergen", "fit?"))
{
    Log.Information("Message using context {Myergen}");
    Log.Information("Message using context {Myergen} and something {Else}", "the else");
}
```

The 1st statement works as expected. The 2nd does not, as {Myergen} is replaced with "the else".

I thought to work around this by using `null` as positional parameters for properties that should already exist in the log context. I first tried:
```
using (LogContext.PushProperty("Myergen", "fit?"))
{
    Log.Information("Message using context {Myergen}", null);
}
```
Success, it renders `{Myergen}` from the context! Then I tried:
```
using (LogContext.PushProperty("Myergen", "fit?"))
{
    Log.Information("Message using context {Myergen} and something {Else}", null, "the else");
}
```
Alas, it doesn't work, and replaces `{Myergen}` with `null`! I guess my first success is some kind of corner case?

So, my question: is there any way to combine context properties with positional properties, such that existing context properties are left intact? Perhaps there is some kind of constant you can pass, such as:

```
using (LogContext.PushProperty("Myergen", "fit?"))
{
    Log.Information("Message using context {Myergen} and something {Else}", Property.FromContext, "the else");
}
```

**Comment by nblumhardt** [comment]
Hi @cocowalla - rendering context properties in messages is not supported/considered "undefined behavior" - the parameters for a log event's message all need to come from the arguments provided directly to the logging method. #1080 links to some earlier discussions to check out. Cheers!

**Comment by cocowalla** [comment]
The reason I'm asking is that I want to make better use of context properties. We log them to a database, and it's _great_ having all that extra contextual information. But what if I want to include these in logs going to file or console sinks?

For example, if I have a `MessageId` in the context and I want to include it in an actual log message (so it appears in file or console-based logs), I have to repeat myself if I want to use any additional properties:

```
var messageId = "14497bbb-c9c8-4991-8f4f-790a2dcbae0f";
using (LogContext.PushProperty("MessageId", messageId ))
{
    Log.Information("Processing {MessageId}");                                     <---- DRY FTW!
    Log.Information("Processing {MessageId} with another {Value}", messageId, 12); <---- boo :(
}
```

One of the benefits of context properties, as I see it, is that I shouldn't have to repeat myself.

**Comment by tsimbalar** [comment]
@cocowalla if you have defined a sink with a `outputTemplate` containing `{Properties}`, all the event properties that are not already rendered somewhere in the template will show up. 

See https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text for more info about the `Properties` tag.

**Comment by nblumhardt** [comment]
Sorry @cocowalla - I didn't mean to close it as unreasonable, only that this design choice is baked pretty deeply in, and not something I think is changeable at this point. IIRC, the linked thread's pretty extensive, but happy to discuss further if you think there's a closeable gap 👍

**Comment by cocowalla** [comment]
No problem, I wasn't offended :)
