### ISSUE TITLE
LoggingLevelSwitch as an Interface

### ISSUE THREAD

**Issue by 0shi** [serilog/serilog#1232]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**Please describe the current behavior?**
SeriLog provides the [LoggingLevelSwitch ](https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/LoggingLevelSwitch.cs) to allow for runtime re-configuration of the current minimum Log Level.

**Please describe the expected behavior?**
As LoggingLevelSwitch has been implemented as a concrete class, it is not possible to provide a custom implementation of it. Would any consideration be given to this being provided as an interface instead of a concrete class?

In our use case we are attempting to control log levels via our Feature Toggling framework, as an existing means that we have for orchestrating settings across multiple disconnected microservices. Currently this has been implemented using a Filter.ByExcluding, but it looks to me that it would have been more efficient if I had been able to implement it using an override of the LoggingLevelSwitch.MinimumLevel property, but making use of the property as it is currently would instead require standing up a long-running task to check the feature flag values and update the MiniumLevel periodically instead.

**Comment by nblumhardt** [comment]
Thanks for the feedback! This has been done for (noticeable) performance reasons; updating the level switch when your feature toggles change is the way to go, here. Cheers!
