### ISSUE TITLE
Community Project: Serilog.Enrichers.ExcelDna

### ISSUE THREAD

**Issue by caioproiete** [serilog/serilog#1239]
I'd like to add my new enricher **[Serilog.Enrichers.ExcelDna](https://github.com/caioproiete/serilog-enrichers-exceldna/)** to the [Enrichment page](https://github.com/serilog/serilog/wiki/Enrichment#available-enricher-packages).

This enricher allow developers to enrich Serilog events with information from Excel add-ins built with [Excel-DNA](https://github.com/Excel-DNA/ExcelDna), such as its location path and version of the Excel running the add-in.

[![image](https://user-images.githubusercontent.com/177608/47399288-27ad8f80-d70e-11e8-808e-5cd5c31cec11.png)](https://github.com/caioproiete/serilog-enrichers-exceldna/)

---

### Serilog.Enrichers.ExcelDna
* Source code: https://github.com/caioproiete/serilog-enrichers-exceldna/
* NuGet package: https://www.nuget.org/packages/Serilog.Enrichers.ExcelDna/

**Comment by merbla** [comment]
Thanks @caioproiete I have update the [community projects](https://github.com/serilog/serilog/wiki/Community-Projects).
