### ISSUE TITLE
Community Project: Serilog.Sinks.Graylog and Serilog.Sinks.Graylog.Batching

### ISSUE THREAD

**Issue by whir1** [serilog/serilog#1242]
I'd like to add my sinks [Serilog.Sinks.Graylog](https://www.nuget.org/packages/Serilog.Sinks.Graylog) and  [Serilog.Sinks.Graylog.Batching](https://www.nuget.org/packages/Serilog.Sinks.Graylog.Batching) to the [Provided Sinks Wiki page.](https://github.com/serilog/serilog/wiki/Provided-Sinks)

This sink writes Serilog events to [Graylog](https://www.graylog.org/)

![default](https://user-images.githubusercontent.com/4126174/47836617-1a516e80-ddba-11e8-8106-83910c17adc5.png)
![default](https://user-images.githubusercontent.com/4126174/47836716-47058600-ddba-11e8-9d47-19430ccddf00.png)

Source code: https://github.com/whir1/serilog-sinks-graylog
NuGet package: https://www.nuget.org/packages/Serilog.Sinks.Graylog
NuGet package: https://www.nuget.org/packages/Serilog.Sinks.Graylog.Batching

**Comment by nblumhardt** [comment]
Thanks, will do! :-) 👍

**Comment by merbla** [comment]
@whir1 sorry for the delay.  Added Graylog to [available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) page.
