### ISSUE TITLE
Serilog Provided Sinks page

### ISSUE THREAD

**Issue by Mirimon** [serilog/serilog#1244]
Hello,

Logify, our application monitoring service, supports Serilog. How our plugin can be included to your Provided Sinks page?
 
Information on our Serilog plugin can be found here: https://logify.devexpress.com/Alert/Documentation/Send/IntegrationWithLogSystems/Serilog.

Source code is available here: https://github.com/DevExpress/Logify.Alert.Clients/tree/develop/dotnet/Logify.Alert.Serilog.
 
I look forward to your reply. 

Best Regards,
Alex
Logify.devexpress.com

**Comment by merbla** [comment]
Thanks @Mirimon this has been added to the [available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) page.
