### ISSUE TITLE
Question on final output 

### ISSUE THREAD

**Issue by sachabarber** [serilog/serilog#1246]
So let me just give a bit of context here we use Serilog and we use various sinks including some of our own ones. But we also use the **Serilog.Sinks.File**

For most of the sinks we add extra properties that we need to use to drive logic, such as routing/filtering etc etc

So for us a given log statement may look something like this

```
public class SomeClass
{
    public String Name { get; set; }
    public string AppType { get; set; }
}

var loggingEnvironment = new SomeClass()
{
    Name = "foo",
    AppType = "test",

};
```
`Logger.Error("{Category} {Message} {@LoggingEnvironment}", LogCategory.BUS, "Oh no its gone bad jim", loggingEnvironment);`

Where we need the **LoggingEnvironment** property to travel all the way through MOST of our sinks.

However for the file Sink output we see if this

`2018-11-21 10:30:21.332 [ERR] BUS "Oh no its gone bad jim" SomeClass { Name: "foo", AppType: "test" }` 

What we would like the file written text to be its just

`2018-11-21 10:30:21.332 [ERR] BUS "Oh no its gone bad jim"`

Reading more into this section from Serilog https://github.com/serilog/serilog/wiki/Formatting-Output it talks about the formatters for Message.

Message - The log event's message, rendered as plain text. The :l format specifier switches of quoting of strings, and :j uses JSON-style rendering for any embedded structured data.

But as this extra property is not really part of the message, I don't think that section of the docs applies.

Short of bringing in all the code for the **Serilog.Sinks.File** into our own codebase, is there a way to get to rid of this (or any other property) value from being written to a sink output?

**Comment by tsimbalar** [comment]
Hi Sacha,

 I think what you want is : 

```csharp
Logger.ForContext("LoggingEnvironment", loggingEnvironment, destructureObjects: true).Error("{Category} {Message}", LogCategory.BUS)
```

This allows to add properties that are not in the rendered message.

See https://stackoverflow.com/questions/30637416/how-can-i-add-a-named-property-that-is-not-part-of-the-message-template

**Comment by sachabarber** [comment]
Ah what I wanted was the opposite of that, I want to renmove properties from the final string written to  file/console, but still have these properties (we already use Destructorama.JsonNet) for this.

I have managed to solve it like this

```
public class MyFormatter : ITextFormatter
{
    public void Format(LogEvent logEvent, TextWriter output)
    {
        var listOfPropertiesToNotInclude = new List<string>();
        listOfPropertiesToNotInclude.Add("LoggingEnvironment");
        var allOutputItems = new List<string>();
        allOutputItems.Add($"[{logEvent.Timestamp.ToString("T")} {LevelOutputFormat.GetLevelMoniker(logEvent.Level, "u3")}]");
        allOutputItems.AddRange(logEvent.Properties.Where(x => !listOfPropertiesToNotInclude.Contains(x.Key))
            .Select(p => $"{p.Value}"));

        var props = allOutputItems.ToArray();
        output.Write(string.Join(" ", props));
        output.WriteLine();
    }
}
```
