### ISSUE TITLE
New Azure storage queue sink

### ISSUE THREAD

**Issue by gjbdebug** [serilog/serilog#1248]
**New sink: Serilog.Sinks.AzureQueueStorage**

I have created [Serilog.Sinks.AzureQueueStorage](https://github.com/gjbdebug/serilog-sinks-azurequeuestorage) which is modeled after [Serilog.Sinks.AzureTableStorage](https://github.com/serilog/serilog-sinks-azuretablestorage). Simply put, instead of writing to an Azure storage table, it writes to an Azure storage queue.

Like the AzureTableStorage sink, AzureQueueStorage should be considered prerelease.

I'm using it to send messages to Azure storage queues then process the messages using Azure Functions and it's worked flawlessly.

I offer it to the Serilog community to ideally be listed on the wiki and attract additional contributors.

Thank you,
[gjbdebug](https://github.com/gjbdebug)

**Comment by merbla** [comment]
Thanks @gjbdebug , added to the [available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) page.
