### ISSUE TITLE
Serilog write to file operation is taking more time.

### ISSUE THREAD

**Issue by amshekar** [serilog/serilog#1252]
Serilog write to file operation is taking more time so which on and average it is taking 515 milliseconds to
Log one entry in the notepad.

We added following but no luck
Implemented async mechanism to write data to file.
Instead of using transient dependency injection we are using scoped  in dot net core startup.
Used Buffer True flag by expecting that may help to increase performance. 

Code snippet 
![49520715-e641ff80-f8c9-11e8-976e-cfaf2fd2c3b6](https://user-images.githubusercontent.com/16417812/49527353-b8d06400-f87f-11e8-9241-076c3935d692.png)

Log times: 
![49520626-b09d1680-f8c9-11e8-9531-4e03ae3d9d1d](https://user-images.githubusercontent.com/16417812/49527274-91799700-f87f-11e8-951c-4609b059f05b.png)

Target framework
Serilog.Sinks.File version -4.0.0
Serilog version 2.5.0

operating system
Windows server 2008 R2

- [ ] netCore 2.1

**Comment by merbla** [comment]
Hi @amshekar,

Thanks for creating the issue, however this would better live over at the [File sink issues](https://github.com/serilog/serilog-sinks-file/issues) list.

If you could provide an full sample that illustrates the problem that would be great.

Thanks!

**Comment by merbla** [comment]
Seems that #1253 and 1252 are duplicates.

**Comment by nblumhardt** [comment]
Hi @amshekar - if you're still experiencing an issue here, would it be possible to reopen the issue with some more information/performance traces/etc.? It's hard for us to narrow this down without profiling the app on your infrastructure. Thanks!

**Comment by vkbishnoi** [comment]
Hi @nblumhardt . I am observing the same issue. Actually, when i set buffered =true in the config, I am getting exactly the same amount of time to write logs into file(s) when this buffered is set to false.
Since it's a simple test project, I can share it with you. Please let me know.
