### ISSUE TITLE
How do I remove a superfluous field($“type”) from the structure of output log.

### ISSUE THREAD

**Issue by otot333** [serilog/serilog#1256]
Hi all,
i declare one log class 
public class LogDetail
{
   public string Message { get; set; }
}

when i use Debug method to record log 
var logDetail = new LogDetail(){Message = "i am debugMessage"};
_log.Debug("@LogDetail",logdetail)

i got this one text
[Debug]{"Message":"i am debugMessage","$type":"DebugDetail"} 

How to remove "$type":"DebugDetail"?

**Comment by merbla** [comment]
Hi @otot333,

Check out some of the notes on destructing objects [here](https://github.com/serilog/serilog/wiki/Structured-Data#customizing-the-stored-data).

HTH

**Comment by nblumhardt** [comment]
It's possible to wire in an `ILogEventEnricher` to do this - the enricher needs to iterate over all properties, and for those that are of type `StructureValue`, call `LogEvent.AddOrUpdateProperty()` passing a new `StructureValue` with the same fields but no `typeTag` parameter set.

Hope this helps; currently working through tidying up the tracker (we've accumulated a backlog of questions here :-)) .. please feel free to chime in/reopen if you still need a hand with this @otot333 .
