### ISSUE TITLE
New Azure Appending Blob Sink

### ISSUE THREAD

**Issue by chriswill** [serilog/serilog#1257]
I also wanted to announce a new sink for possible inclusion in the Wiki list.

[Serilog-Sinks-AzureBlobStorage](https://github.com/chriswill/serilog-sinks-azureblobstorage) is based on the [Azure Table Storage sink](https://github.com/serilog/serilog-sinks-azuretablestorage) but writes to Azure's [appending blob storage](https://blogs.msdn.microsoft.com/windowsazurestorage/2015/04/13/introducing-azure-storage-append-blob/).  Appending blobs are ideal for logging scenarios.  

This project has already gotten several community contributions, which I'm grateful to receive.

**Comment by merbla** [comment]
Thanks @chriswill, added to the [available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) page.
