### ISSUE TITLE
Add Giraffe.SerilogExtensions to the list of community projects

### ISSUE THREAD

**Issue by Zaid-Ajaj** [serilog/serilog#1260]
Library [Giraffe.SerilogExtensions](https://github.com/Zaid-Ajaj/Giraffe.SerilogExtensions)

Serilog extensions to make it easy to add logging to [Giraffe](https://github.com/giraffe-fsharp/Giraffe) (F# web framework on top of AspNet core)

**Comment by merbla** [comment]
Thanks @Zaid-Ajaj I have added to the community projects [here](https://github.com/serilog/serilog/wiki/Community-Projects).
