### ISSUE TITLE
Padding not applied in output templates when property values are missing

### ISSUE THREAD

**Issue by mariopasquali** [serilog/serilog#1261]
Hi all,

I enjoy Serilog a lot and appreciate its simple and flexible architecture, but one aspect I feel Serilog falls short is on the text output.  I know Serilog is mainly about structured outputs and not so much about plain text outputs, but a plain text output is still useful in certain cases, and unfortunately Serilog doesn't help much in making a nice-looking text output.  Let consider a few simple cases to illustrate where I would like more flexibility: 

`[P:{ProcessId,5} T:{ThreadId,5}] {Message}`

The idea here is to get an aligned output by having the ProcessId and ThreadId fields of fixed width.  But guess what happen if ProcessId or ThreadId are not present?  We end up with an output like "[P: T: ] My message".  In such a case, I might want to replace the missing field by spaces, such as:

```
[P:00001 T:12345] My message with process and thread
[P:00001 T:     ] My message with process only
[P:      T:12345] My message with no process or thread
```

As another example, consider a template like:

`{ClassName}.{MethodName]: {Message}`

ClassName and MethodName are optional.  MethodName must be displayed only if ClassName is present.  The '.' shall be only visible if ClassName and MethodName are present.  ": " shall be only visible if ClassName is present.  So we can end up with:

```
My message without any context
MyClass: My message with class context
MyClass.MyMethod: My message with class and method context

```
ClassName might be replaced by SourceContext if SourceContext could be formatted in a more compact way (it currently contains the full namespace in addition to the class name, which is usually too verbose for a text output).

I evaluated a few approaches to extend Serilog's text template to support some of the above features but this proved to be quite difficult.  For example I would like to extend both Console and File sinks.  There is no way to extend the binary assemblies, so I must either take Serilog in source code and extend it, or alternatively take the Console and File sinks source code and extend these.  An approach would be to reimplement a full ITextFormatter but this would lose some features of the Console sink (like coloring).  And fully reimplementing ITextFormatter is not trivial as nothing is exposed from Serilog.  Another approach would be to pass a MessageTemplateParser to the sinks and then extend the formatting, but the formatting is done in Serilog, so this approach requires extending all assemblies.  

Did I miss the right approach to get a more flexible text output?  Am I alone here with this need?

Thank you,
Mario

**Comment by mariopasquali** [comment]
@nblumhardt @tsimbalar: Am I out of context with my need?

**Comment by nblumhardt** [comment]
Hi @mariopasquali, thanks for the well-considered issue 👍 

I think it might be reasonable to consider this a bug - padding should probably still apply even when no value is present for a property. It'll need some time and investigation at our end, though.

Cheers,
Nick

**Comment by mariopasquali** [comment]
Hi @nblumhardt, thank you for considering my feedback, much appreciated. 

Resolving the padding would indeed be a great step towards having a more readable text output. 

The other side of my message was about what I could qualify as "decorative characters", so basically characters used to decorate properties to make the text output more readable. (like spaces, dots, etc).  I am not sure if this is the right place or way to discuss this so let me know if I am not reporting this the right way. 

Before taking the original case in my first message, let's consider the simple case:

`{SourceContext}: {Message}`

I believe this is a pretty this is a pretty common case.  It should also be pretty common that SourceContext is not always informed.  The need here is obviously to not have the decorative characters ": " if the SourceContext is not present.  I would like to have a way to associate decorative characters to a property so if the property is not present, the decorative characters would not be put in the formatted text.  There are a few ways to achieve this.  I thought about an approach to open discussion:

`{SourceContext;$: }{Message}`

The above template use a suggested property formatting option.  The formatting is specified after ';'.  '$' is the placeholder for the formatted property.  This example works well in this simple example.  If SourceContext is missing then only Message will be printed out, easy. 

My first email actually had a slightly trickier case:

`{ClassName}.{MethodName}: {Message}`

Where ClassName and MethodName potentially optional.  The additional difficulty is that if ClassName is missing then MethodName should not be printed even if available.  I am not sure if this is a too special case that it is not worth supporting, but for the sake of the discussion I tried expressing this with my suggested extended template format:

`{ClassName;${Method;.$}: }{Message}`

The trick is to embed a property to the formatting of another.  The extended template is still simple and readable, 

I will stop here for now, waiting feedback to understand if it is worth pushing the discussion further. 

Cheers,
Mario

**Comment by nblumhardt** [comment]
Thanks for the follow-up, Mario, and sorry I missed replying to the second part of your message.

The goal of Serilog's template syntax is to be/remain as close as possible to the .NET format string syntax, so it's not likely we'd address the second item here via this ticket.

There's a lot of room to plug in new/alternative text formatters, though - the case of "conditional" formatting is very interesting. I've thought in the past about writing an alternative formatter to support this (either with a custom syntax, or something like Handlebars), but it would be a separate project to Serilog's core.

**Comment by mariopasquali** [comment]
Thank you for the comment Nicholas.  I am totally fine of having this as a separate project and this is actually what I was looking for initially, but I didn't find any way to extend the Serilog templates in a way that would work with existing Serilog sinks.  I briefly explained the approaches I considered in the last paragraph of the first message.  

Did I miss something that would enable me to create the desired functionality?

Thank you,
Mario

**Comment by mariopasquali** [comment]
(sorry, didn't mean to close it)

**Comment by nblumhardt** [comment]
Hi Mario - regarding how to maintain compatibility with existing sinks, all of the text-based sinks accept an `ITextFormatter` that is responsible for rendering out events as text. The default [`MessageTemplateTextFormatter`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs#L33) does this for the regular output templates. Your alternative plug-in would need to implement the same interface, and then be passed in via methods like `WriteTo.File()` etc. - HTH.

**Comment by nblumhardt** [comment]
One note regarding the alignment issue; fixing it will create a regression for anyone currently relying on it to squeeze two properties into the space of one, e.g. `{RequestId,10}{MessageId,10}` in cases where one or the other property, but not both, will be present.

Therefore I think we should save the fix for the 3.0 milestone.

**Comment by liviriniu** [comment]
> fixing it will create a regression for anyone currently relying on it to squeeze two properties into the space of one

Maybe it would help to come up with a flag `KeepPaddingForEmptyProperties` with `false` as default as to ensure backwards compatibility (if I'm wording it correctly).

I write here because I would want a feature of console/file sink where you can prepend/post-pend tab or new line (maybe extended to any string) to properties in output and find it to be somehow a sub-case of this discussion. Also, reading this issue looks like the implications are far more complex than I imagined.

What would be useful in my opinion to be able to do in `outputTemplate` is `{t|prop}{n|anotherProp|n}`. If `prop` is "value" and `anotherProp` is empty, rendered output is only `\tvalue`. But I see as equally relevant cases where tabs/new lines are to be kept for empty properties.

_I can move this comment elsewhere if it's not suited here._

**Comment by liviriniu** [comment]
@nblumhardt & @mariopasquali : I looked through `MessageTemplateTextFormatter` and connected classes. I'd love to contribute to your work, Mario, if you'll take this for a PR or to try on my fork to achieve this whole thing if specs are made clear / consensus is reached - as I would really like to see implemented a way (`!`) to enable/disable that "keeping" for each part (pre- ; main ; -post) of each placeholder. I think this 3-part model obtains more flexibility to decorate a property.

**Comment by nblumhardt** [comment]
_Serilog.Expressions_ has some features that should now cover everything discussed in this PR. I'm still interested in improving this behavior, but since it's been stale for so long I'll close it now, and we can reopen if the Serilog.Expressions route is unfruitful. Cheers!
