### ISSUE TITLE
[Question] - Is it possible to determine how a log event property was set?

### ISSUE THREAD

**Issue by JosephWoodward** [serilog/serilog#1264]
I'm currently writing a Sink and an accompanying enricher (based off of [this example](https://gist.github.com/sonicjolt/91321dac3ae815178453)) and I notice properties from enrichers are added via the `logEvent.Properties` collection.

From what I can see it looks like the properties collection is a simple key/value collection, which means that you lose any insight as to what added the the property to the collection (via an enricher vs a log entry or pushed on via the `PushProperty` API).

Other than the enricher creating a property key with a particular prefix (ie `enricher_instanceid`), are there any other means of determining how the property was added?

**Comment by tsimbalar** [comment]
Hi Joseph
and thanks for the question.

There is nothing "out of the box" right now for this. Not sure that is something one would want to enable by default, as it could quickly generate *fat* log events with lots of information that is not useful most of the time.

In addition, *Enrichers* can attach properties, but also update existing properties. What would we show in that case ?

While I can totally see it can be useful, I'm not sure how such a feature would fit in the existing APIs in Serilog.

**Comment by nblumhardt** [comment]
Hi @JosephWoodward - as suggested by @tsimbalar, there are some pretty big hurdles to leap in order to implement this, so we're not likely to be able to attempt it as far as we can tell. If you need a hand debugging your way through some code that adds a mystery property, let me know, happy to dig into it with you 👍

**Comment by JosephWoodward** [comment]
Sorry for the late response - thanks for your help with this. I found another way to do it following @tsimbalar's comments, so thanks for that :)
