### ISSUE TITLE
Add a .NET Standard 2.0 target

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1268]
Serilog 2.7.1 supports all current versions of .NET Core [via the `netstandard1.3` TFM](https://github.com/serilog/serilog/blob/dev/src/Serilog/Serilog.csproj#L7). Its smoother to consume libraries that target .NET Standard 2.0 (`netstandard2.0`) with current tooling - we should add this TFM even though it won't expand the platforms reachable by the package.

**Comment by chriswolf-nrg** [comment]
Disregard my remark about `.netcoreapp` - those are not for library DLLs.
