### ISSUE TITLE
Conditional configuration of sinks

### ISSUE THREAD

**Issue by danielwertheim** [serilog/serilog#1277]
Is there some way to get conditional bootstrapping of sinks to use? I have attached sample configuration and solution but I'm guessing that something already exists or perhaps something you shouldn't be doing or ...?

```
public static class SerilogExtensions
{
    public static LoggerConfiguration ConfigureIf(
        this LoggerConfiguration cfg,
        bool shouldConfigure,
        Func<LoggerSinkConfiguration, LoggerConfiguration> writeTo)
        => shouldConfigure ? writeTo(cfg.WriteTo) : cfg;
}
```

```
private static LoggerConfiguration BuildLoggerConfig(IConfiguration config, ServiceInfo serviceInfo, bool isRunningAsConsole) => new LoggerConfiguration()
    .MinimumLevel.Information()
    .ConfigureIf(isRunningAsConsole, writeTo => writeTo.Console(
        restrictedToMinimumLevel: LogEventLevel.Debug,
        outputTemplate: template))
    .ConfigureIf(!isRunningAsConsole, writeTo => writeTo.File(
        $".\\logs\\foo-{serviceInfo.Name}.log",
        restrictedToMinimumLevel: LogEventLevel.Information,
        outputTemplate: template,
        rollingInterval: RollingInterval.Day,
        retainedFileCountLimit: 20))
    .Enrich.WithProperty("Svc", serviceInfo.Name)
    .ReadFrom.ConfigurationSection(config.GetSection("Serilog"));
```

**Comment by nblumhardt** [comment]
Hi Daniel!

```csharp
var configuration = new LoggerConfiguration()
    .MinimumLevel.Information();

if (isRunningAsConsole)
{
    configuration.WriteTo.Console(
        restrictedToMinimumLevel: LogEventLevel.Debug,
        outputTemplate: template));
}
else
{
    configuration.WriteTo.File(
        $".\\logs\\foo-{serviceInfo.Name}.log",
        restrictedToMinimumLevel: LogEventLevel.Information,
        outputTemplate: template,
        rollingInterval: RollingInterval.Day,
        retainedFileCountLimit: 20));
}

return configuration.Enrich.WithProperty("Svc", serviceInfo.Name)
    .ReadFrom.ConfigurationSection(config.GetSection("Serilog"));
```

Cheers,
Nick

**Comment by danielwertheim** [comment]
Kind of brakes the "flow" with expression body functions and the fluent configuration that you have in there so I guess I'll stick to my extension method.

**Comment by nblumhardt** [comment]
Thanks for the reply - great that you can add this on for your requirements 👍

Taking this on in Serilog seems like it would start us down the slippery slope to implementing `While()`, `ForEach()`, `Unless()`, `Try()`, `TryCatch()` etc. for completeness (there are a lot of different conditional ways to configure logging) and it seems then like we're stepping on C#'s toes 😆 

If you look at it another way, you might as well define:

```csharp
public static class OverExtensions
{
    public static T If<T>(
        this T target,
        bool condition,
        Action<T> act)
    {
        if (condition) act(target);
    }
}
```

Then you can use it in the Serilog configuration example, and anywhere else you like (i.e. in expression-bodied functions):

```csharp
user
    .If(loginSucceeded, u => u.Logins++)
    .If(!loginSucceeded), u => u.FailedLogins++);
```

(Okay couldn't help it; I know this is totally stretching credibility - but it's the kind of horrifying Frankenlanguage thing that I end up with when taking this all the way 😄 ).

Appreciate the input, could still be something we look at down the line but will close as wontfix for now.

Cheers!

**Comment by danielwertheim** [comment]
Yes, one can go bananas, but I tried to be more explicit and add constraints as it gives context and adheres to semantics. Not really sure why those other members would need to exist. But sure, I can see that people would say: "you have X, then give me Y".

Anyway, thanks for an awesome library and quick responses. Makes we even more positive to look at GetSeq and invest in a license in that. Cause if support on an open source project is this good, the support on a commercial product will be super awesome, right? 😉 

Cheers

**Comment by stephenpatten** [comment]
Posted a quest on SO that is very similar, but my expectation is much smaller in scope I believe.

I'd like my bootstrap to look something like this 

    var logger = Log.Logger = new LoggerConfiguration()
          .ReadFrom.AppSettings()
          .Enrich.FromLogContext()
          .Enrich.WithMachineName()
          .Enrich.WithProcessId()
          .Enrich.WithThreadId()
          .WriteTo.ElasticsearchIfEnabled() // <--- Chained Sink
          .WriteTo.Async(
              a => a.File(
                  filePath,
                  outputTemplate: CanonicalTemplate,
                  retainedFileCountLimit: 31,
                  rollingInterval: RollingInterval.Day,
                  rollOnFileSizeLimit: true,
                  buffered: true,
                  flushToDiskInterval: TimeSpan.FromMilliseconds(500)))
        .CreateLogger();

But, I'm stuck on stupid trying to figure out how to handle passing the original configuration in the case where my is turned off.

	public static class MyConfigExtensions
	{
		public static LoggerConfiguration ElasticsearchIfEnabled(this LoggerSinkConfiguration loggerSinkConfiguration)
		{
			var isElasticSinkEnabled = GetThisValue();

			if (isElasticSinkEnabled)
			{
				// Code necessary to configure sink....

				return loggerSinkConfiguration.Sink(new ElasticsearchSink(elasticSearchSinkOptions));
			}

			return loggerSinkConfiguration; // <-- what is passed here that will propagate the configuration?
		}
	}

**Comment by Alik2015** [comment]
@stephenpatten I am trying to do the same thing actually. As I also have some loggers i only need to enable based on configuration.  Did you find the answer to what to pass out of the extension method when not enabled?

**Comment by stephenpatten** [comment]
Yes, Nick pointed me in the right direction, I believe the answer is in this repo. Let me check

**Comment by rebeccapowell** [comment]
I would be interested in this too. Do you have that link? I've been searching for a couple of hours and getting frustrated :)
