### ISSUE TITLE
New EmailPickup Sink

### ISSUE THREAD

**Issue by gkinsman** [serilog/serilog#1278]
Hiya, 

I'm working on converting a log4net project to Serilog, and we use the SmtpPickupDirAppender which generates an email and puts it in a pickup directory. I replicated it as a serilog sink that adds the properties and exception details. Figured I may as well publish it 🙂.

Nuget: https://www.nuget.org/packages/Serilog.Sinks.EmailPickup/
Github: https://github.com/gkinsman/Serilog.Sinks.EmailPickup

Cheers!

**Comment by merbla** [comment]
Sink added to the [wiki](https://github.com/serilog/serilog/wiki/Provided-Sinks).
