### ISSUE TITLE
No log file on Azure web app

### ISSUE THREAD

**Issue by vRITHNER** [serilog/serilog#1283]
**A few questions before you begin:**

> Is this an issue related to the Serilog core project or one of the [sinks]
Core and Sinks I guess

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug

**What version of Serilog is affected?  Please list the related NuGet package.**

```
    <PackageReference Include="Serilog" Version="2.8.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.3.1-dev-00063" />
    <PackageReference Include="Serilog.Sinks.AzureApp" Version="2.1.2" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="2.6.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.2-dev-00788" />
```

**What is the target framework and operating system? See [target frameworks]

- [x] netCore 2.2

**Please describe the current behavior?**
I want to log stuff in console and files

**Please describe the expected behavior?**
it is working fine on localhost but nothing happened in Azure. 

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
1-Create a new web app
2-Add logging config
3-Run locally 
4-Deploy on a new web app on Azure
5-Check in Kudu for any log files

Thanks in advance
-Vince

**Comment by nblumhardt** [comment]
Hi @vRITHNER - a lot of this comes down to the oddities of file handling on Azure, unfortunately, so it's difficult to answer from a high level; check out https://github.com/serilog/serilog-aspnetcore#writing-to-the-azure-diagnostics-log-stream for some clues, though. HTH!
