### ISSUE TITLE
[Feature Request]Need a file configuration without ASP support

### ISSUE THREAD

**Issue by watsonsong** [serilog/serilog#1287]
I am writing a console application that using serilog. It will not use the asp, and I don't want to introduce something like configuration and appsettings. Is there any configuration for serilog in this case?

**Comment by tsimbalar** [comment]
You can always configure as code. That's the native way to configure Serilog : https://github.com/serilog/serilog/wiki/Configuration-Basics

In a Full Framework console application, you can use [`Serilog.Settings.AppSettings`](https://github.com/serilog/serilog-settings-appsettings) to read config from an `app.config` file.

In a .NET Core console application, you can use [`Serilog.Settings.Configuration`](https://github.com/serilog/serilog-settings-configuration) to read from a `json` file or any other provider from the .NET Core configuration extensions as described in https://garywoodfine.com/configuration-api-net-core-console-application/.

I hope this helps !

**Comment by nblumhardt** [comment]
There's also `ReadFrom.KeyValuePairs()` in the core Serilog library, which can handle key/value settings from wherever you choose to store them, which could be in a text file.

Examples: https://github.com/serilog/serilog/blob/dev/test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

Cheers,
Nick
