### ISSUE TITLE
404 is an error and not an Information!

### ISSUE THREAD

**Issue by dorathoto** [serilog/serilog#1289]
I'm using Serilog in ASP.NET Core 2.2
And I have seen that 404 errors it has marked as Level Information
But for me 404 is a mistake!

```
Request finished in 2.0646ms 404
{HostingRequestFinishedLog: l}
Information
```

**My initial settings**
```
            Log.Logger = new LoggerConfiguration()
               .ReadFrom.Configuration(Configuration)
               .Destructure.ByTransforming<ExpandoObject>(e => new Dictionary<string, object>(e))
               .Enrich.WithProperty("SetorErro", SetorLogErro.MVC)
               .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
               .MinimumLevel.Override("System", LogEventLevel.Warning)
               .CreateLogger();
```
appsettings.json
```
  "Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "__ConnectionString__",
          "tableName": "LogError",
          "autoCreateSqlTable": true,
          "restrictedToMinimumLevel": "Debug", //https://github.com/serilog/serilog/wiki/Writing-Log-Events
          "columnOptionsSection": {
            "customColumns": [
              {
                "ColumnName": "SetorErro",
                "DataType": "int",
                "AllowNull": true
              },
              {
                "ColumnName": "LocalErro",
                "DataType": "nvarchar",
                "DataLength": 150,
                "AllowNull": true
              }
            ]
          }
        }
      }
    ]
  },
```

**Package:**
_Serilog.AspNetCore 2.1.1
Serilog.Settings.Configuration 3.0.1
Serilog.Sinks.MSSqlServer 5.1.3-dev-00232_

When I used Elmah in ASP.NET MVC 5 I caught many errors, it seems that Serilog natively can not catch all the errors (API, hangfire, etc). But that does not enter into the question of this question.

**Comment by mivano** [comment]
A 404 indicates a Not Found. Which is perfectly sensible when a record is not available. As such, it is IMHO not an error at all. Your business process might require a certain record to be there, then it can be an error for your process and you need to log it as such, but the mere existence of a 404 is not an error.

**Comment by khellang** [comment]
Who is logging this 404? I'm assuming this is ASP.NET Core's own logging so this wouldn't be related to Serilog.

**Comment by nblumhardt** [comment]
Hi @dorathoto, thanks for getting in touch. As @khellang suggests, this event is passing _through_ Serilog, but isn't being generated by it: it's part of ASP.NET Core and the decision on the event's level is made in that framework.
