### ISSUE TITLE
Adding elmah.io sink to the wiki

### ISSUE THREAD

**Issue by ThomasArdal** [serilog/serilog#1290]
I was browsing through the [list of sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) on the wiki and noticed that the [elmah.io](https://elmah.io/) sink isn't listed. Would it be possible to list this?

Sink Name: elmah.io
Sink URL: https://github.com/elmahio/serilog-sinks-elmahio
WriteTo.*: ElmahIo
Package: https://www.nuget.org/packages/Serilog.Sinks.ElmahIo
Build stats badge: https://buildstats.info/nuget/Serilog.Sinks.ElmahIo

**Comment by nblumhardt** [comment]
Thanks for the heads-up! Fixed 👍

**Comment by ThomasArdal** [comment]
![Thank you](https://user-images.githubusercontent.com/563206/53559780-34724200-3b4b-11e9-9501-bec398f4ae7c.gif)
