### ISSUE TITLE
Serilog doesn't accept MinimumLevel for StaticFiles, Hosting and EF Core

### ISSUE THREAD

**Issue by CribAd** [serilog/serilog#1292]
I'm trying to get a clean log with Serilog from my ASP.NET Core application. To clear some image requests and db commands from EF Core, I am using next filtering:
```
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .MinimumLevel.Override("System", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.Console(outputTemplate: "{Timestamp:o} [{Level:u3}] [{SourceContext}] {Site}: {Message}{NewLine}")
    .WriteTo.Logger(lc => lc
        .MinimumLevel.Information()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
        .MinimumLevel.Override("System", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft.AspNetCore.Hosting.Internal.WebHost", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft.EntityFrameworkCore.Database.Command", LogEventLevel.Error)
        .WriteTo.File("logs/log.txt", rollingInterval: RollingInterval.Hour, outputTemplate: "{Timestamp:o} [{Level:u3}] [{SourceContext}] {Site}: {Message}{NewLine}")
    )                
    .CreateLogger();
```
The **expected result** is a console log with a lot of information and a log file with much less information, because for `Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware`, `Microsoft.AspNetCore.Hosting.Internal.WebHost` and `Microsoft.EntityFrameworkCore.Database.Command` I set a new `MinimumLevel`.

But the **actual result** is that all INFORMATION logs of `Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware`, `Microsoft.AspNetCore.Hosting.Internal.WebHost` and `Microsoft.EntityFrameworkCore.Database.Command` are still present in the file.

**Comment by nblumhardt** [comment]
Hi! You need to use filters (`Filter.ByExcluding(...)`, possibly in conjunction with _Serilog.Filters.Expressions_) for this, rather than minimal level overrides, because `MinimumLevel.Override` on sub-loggers doesn't do what you'd expect. #967 has the earlier discussion IIRC.

Thanks for the detailed report; marking as `duplicate` but let us know if you need a hand with filtering configuration.
