### ISSUE TITLE
New Relic sink link in wiki unavailable

### ISSUE THREAD

**Issue by dininski** [serilog/serilog#1295]
Not sure how much the wiki is maintained, but it seems that in the wiki page the [NewRelic sink repository](https://github.com/Applicita/serilog-sinks-newrelic) is no longer available. There is currently a [Serilog.Sinks.NewRelic](https://www.nuget.org/packages/Serilog.Sinks.NewRelic/) Nuget package, so the link in the wiki should either be updated or removed altogether.

**Comment by nblumhardt** [comment]
Thanks! It looks like the original sink from #546 has moved to: https://github.com/Mimeo/serilog-sinks-newrelic - but isn't being published to NuGet from that repository, as far as I can tell.

The package on NuGet doesn't have any repository or background information listed at all (not even a README) so I don't think we should list it.

I'll update the wiki to point to the new repo location, hopefully that's an improvement :-)
