### ISSUE TITLE
Trouble outputting to JSON

### ISSUE THREAD

**Issue by InteXX** [serilog/serilog#1299]
I'm following the documentation in an attempt to produce JSON-formatted structured data, but the guidance and sample code aren't working. I consistently get string literals.

Here're my minor modifications to the [sample introductory code](https://github.com/serilog/serilog/wiki/Getting-Started#example-application):

    Imports Serilog

    Friend Module Main
      Public Sub Main()
        Log.Logger = New LoggerConfiguration().
          MinimumLevel.Debug.
          WriteTo.Console.
          WriteTo.File("D:\Logs\Serilog\MyApp.txt", rollingInterval:=RollingInterval.Day, outputTemplate:=OUTPUT_TEMPLATE).
          CreateLogger

        LogFruit()
        LogError()
      End Sub

      Private Sub LogFruit()
        Log.Information("In my bowl I have {Fruit}", {"Apple", "Pear", "Orange"})
      End Sub

      Private Sub LogError()
        Dim a, b, c As Integer

        a = 10
        b = 0
        c = 0

        Log.Information("Hello, world!")

        Try
          Log.Information("Dividing {a} by {b}", a, b)
          c = a / b

        Catch ex As Exception
          Log.Error(ex, "Something went wrong")

        End Try

        Log.CloseAndFlush()

        Console.WriteLine()
        Console.WriteLine("Press any key to exit...")
        Console.ReadKey()
      End Sub

      Private Const OUTPUT_TEMPLATE As String = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
    End Module

As we can see, I'm including the [`{Message:lj}` format option](https://github.com/serilog/serilog/wiki/Configuration-Basics#output-templates) as indicated.

Here's my output:

    2019-04-23 12:50:48.946 -08:00 [INF] In my bowl I have ["Apple","Pear","Orange"]
    2019-04-23 12:50:49.064 -08:00 [INF] Hello, world!
    2019-04-23 12:50:49.068 -08:00 [INF] Dividing 10 by 0
    2019-04-23 12:50:49.084 -08:00 [ERR] Something went wrong
    System.OverflowException: Arithmetic operation resulted in an overflow.
       at SerilogTest.Main.LogError() in D:\Dev\Projects\Testing\SerilogTest\SerilogTest\Main.vb:line 28

No JSON.

I found [this issue](https://github.com/serilog/serilog/issues/230):

> I needed to create the sink myself passing in the JsonFormatter and use `WriteTo.Sink(sink)`

However, when I attempt this construct I encounter an `Obsolete` warning:

> `FileSink` is obsolete: 'This type will be removed from the
> public API in a future version; use `WriteTo.File()` instead.'

But this brings us back to square one.

How can I get Serilog to output JSON-formatted text?

**Comment by nblumhardt** [comment]
Hi! `{Message:lj}` will only cause structured data within the message to be written as JSON; you can see this in the `["Apple", ...` output.

To write the file in newline-delimited JSON, the best option is https://github.com/serilog/serilog-formatting-compact:

```csharp
// Install-Package Serilog.Formatting.Compact
Log.Logger = new LoggerConfiguration()
  .WriteTo.File(new CompactJsonFormatter(), "./logs/myapp.json")
  .CreateLogger();
```

HTH 👍

**Comment by InteXX** [comment]
That's much better, thank you  :-)
