### ISSUE TITLE
Log.ForContext in a multitasking environment ?

### ISSUE THREAD

**Issue by abrasat** [serilog/serilog#1301]
Is it posssible to use Log.LogContext work in a multitasking environment ? I have a .NET Core console application which receives data on different communication channels. The data comes asynchronously and should be logged. There are common properties that should be logged, and also eventually some special custom properties that should be added to the logged data (each communication channel handles eventually some specific data format). My idea was to have different ILogger instances in the application and to be able to add some special custom properties to the logged data in the context of each ILogger instance. As far as I understand Log.LogContext is static and is shared across the application. Can Serilog be configured to handle several ILogger instances, each with its own context?

Later edit: I got confused about the difference between LogContext vs. ForContext ... I meant LogContext and wrote erroneously ForContext. Not sure if my problem above can be eventually be better solved by using ForContext...

**Comment by bartelink** [comment]
`x.ForContext` enriches a given logger and can be passed wherever you want and is thread safe.
the `LogContext` mechanism lets you stash stuff in the .NET `ExecutionContext`; stuff you place there will follow the thread of execution including across async Task invocxations etc - then when someone logs and there's an `Enrich.FromLogContext` in play, the log entries get decorated with stuff you stashed (via a `LogContext.Push`) as they get captured.
If you want to to/fro this, the gitter.im for serilog can be useful and/or stackoverflow
