### ISSUE TITLE
List Sumo Logic official Serilog Sink on wiki

### ISSUE THREAD

**Issue by wdolek** [serilog/serilog#1302]
Add `SumoLogic.Logging.Serilog` to wiki (/serilog/serilog/wiki/Provided-Sinks). This is now official Serilog Sink for Sumo Logic.

- NuGet: https://www.nuget.org/packages/SumoLogic.Logging.Serilog/
- name: SumoLogic.Logging.Serilog
- project/source: https://github.com/SumoLogic/sumologic-net-appenders/

Since I don't know how to fork & PR to wiki, here's simple diff:
```
[Sumo Logic](https://github.com/SumoLogic/sumologic-net-appenders) | `SumoLogic` | [SumoLogic.Logging.Serilog](https://www.nuget.org/packages/SumoLogic.Logging.Serilog/) <br/> ![NuGet Version](https://buildstats.info/nuget/SumoLogic.Logging.Serilog) |
```

Also not sure whether make this "official" or make Bill Pratt's "unofficial", or just leave both without any special flag.

**Comment by merbla** [comment]
Sink listing has been updated.

Given that the existing listing had ~150K downloads, I did not mark it unofficial.
