### ISSUE TITLE
EF Core logging in console app

### ISSUE THREAD

**Issue by kofifus** [serilog/serilog#1303]
I have a .NET Core latest EF framework in a console app (windows service) with SqlLite

I am unable to configure serilog to log EF messages.

Looking [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging) it seems I need to pass `ILoggerFactory` to `UseLoggerFactoryin` my `DbContext`

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseLoggerFactory(MyLoggerFactory) // Warning: Do not create a new ILoggerFactory instance 
each time
```

Looking [here](https://dennisroche.com/ef-core-logging-with-serilog/) it shows how to pass `ILoggerFactory loggerFactory` to the `DBContext` 

However after that I'm stuck .. how do I get the `ILoggerFactory` from my `Log` object to pass to my `DBContext` constructor ? if this was a web app it would be injected for me but in a console app I don't know how to do this ?

I tried `.AddSerilog()` on my `HostBuilder` but I get "'IServiceCollection' does not contain a definition for 'AddSerilog'" and anyway I am not sure if all of the above is the correct way to get what I want in the first place ?

**Comment by nblumhardt** [comment]
Hi! I can't say for certain, but I think https://github.com/serilog/serilog-extensions-hosting is what you're looking for. HTH!

**Comment by nblumhardt** [comment]
Closing as stale, please let us know if the above didn't help.
