### ISSUE TITLE
New fork of serilog-sinks-postgresql that is better maintained.

### ISSUE THREAD

**Issue by SeppPenner** [serilog/serilog#1308]
**A few questions before you begin:**

This is related to the https://github.com/serilog/serilog/wiki/Provided-Sinks wiki.

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Improvement

**What version of Serilog is affected?  Please list the related NuGet package.**
https://www.nuget.org/packages?q=Serilog.Sinks.PostgreSQL

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- not related

**Please describe the current behavior?**

It seems like the sink is not maintained very good. That's why I created a fork of it which is maintained better and will always be updated as far as possible.

**Please describe the expected behavior?**

List https://github.com/SeppPenner/SerilogSinkForPostgreSQL instead of https://github.com/b00ted/serilog-sinks-postgresql because its better maintained.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Not a bug.

**Comment by nblumhardt** [comment]
Fantastic, thanks @SeppPenner - we'll do that 👍

**Comment by SeppPenner** [comment]
I have updated the file in a fork already: https://github.com/SeppPenner/serilog-wiki/blob/master/Provided-Sinks.md

**Comment by nblumhardt** [comment]
Thanks; I added this as _PostgreSQL<sup>alternative</sup>_.

**Comment by SeppPenner** [comment]
Thanks @nblumhardt.
