### ISSUE TITLE
F# extension methods aren't picked up by configuration 

### ISSUE THREAD

**Issue by btrepp** [serilog/serilog#1309]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.8.0

**What is the target framework and operating system?**
- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

I'm pretty sure it effects the others too.

**Please describe the current behavior?**

F# style extension methods aren't picked up by the reflection in the configuration sections.
These extension methods work in a C#/F# project, and allow the WriteTo.X syntax to work, but aren't picked up when using the AppSettings module.

```
[<Extension>]    
type Extensions =
    [<Extension>] 
    static member MySink(sinkConfiguration:LoggerSinkConfiguration) =
        sinkConfiguration.Sink(new SinkConfig()))
```
```
<add key="serilog:using:MySink" value="MyApp" />
<add key="serilog:write-to:MySink" />
```

**Please describe the expected behavior?**

The logger is picked up and ran. Or at least an exception/error is thrown that the appsettings configuration is incorrect.

**Workaround**
Line https://github.com/serilog/serilog/blob/6dd2ddbd6d5c7e37f4efd76eaa5b99fb3ee2770e/src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs#L31

Filters out anything that's not abstract and sealed.
It seems the F# compiler doesn't give extension methods this (checked via ildasm)
What's weird is that the still work as extension methods (even from C#)

We can add the attributes to make the extensions look like serilog is expecting.

```
[<Extension>]    
[<Sealed>]
[<AbstractClass>]
type Extensions =
    [<Extension>] 
    static member MySink(sinkConfiguration:LoggerSinkConfiguration) =
        sinkConfiguration.Sink(new SinkConfig()))
```

I'm not 100% sure what the proper rules for extension methods should be, and whether these have ended up being relaxed in newer versions of compilers.

**Comment by nblumhardt** [comment]
Thanks for the report and investigation :+1:

It's possible C# just marks types containing extension methods this way because, in C#, extension methods are declared in `static` classes, and static classes translate to `abstract sealed`.

Serilog uses this as an optimisation; it's not a super-critical one, but would be good to maintain if we can. I wonder if we can check top-level assembly metadata to figure out whether the assembly is a C# or F# one, and filter accordingly?

**Comment by nblumhardt** [comment]
I have a feeling an unlinked PR addressed this already; please let me know if not and it's still an issue. Thanks!

**Comment by bartelink** [comment]
The fact that F# types that look static are not (i.e. are not marked abstract and sealed) is a common confusion with a workaround, see https://stackoverflow.com/a/13419343/11635 and the linked related dotnet issues - hopefully a resolution of those (e.g. if `type private () =` could imply a static class, i.e. auto production of `[<Sealed; AbstractClass>],  will make it less likely for F# authors to run into this.
