### ISSUE TITLE
Extract Dictionary values from LogEventProperty

### ISSUE THREAD

**Issue by abrasat** [serilog/serilog#1313]
There is a use-case where our application stores in the LogEvent properties a Dictionary<string,object> element:

```
var embeddedLogCtx = new Dictionary<string, object>();
DateTimeOffset embeddedLogTimeStamp = GetEmbeddedLogTimeStamp(..);
embeddedLogCtx["App"] = "MyEmbeddedApp";
embeddedLogCtx["Function"] = "MyEmbeddedAppFunct";
embeddedLogCtx["TS"] = embeddedLogTimeStamp;
var logLevel = GetLogLevelFromEmbeddedLogLevel(...);
logger.Log(logLevel, "{@Context}", embeddedLogCtx);
```

How can be extracted the "TS" DateTimeOffset from the properties of the LogEvent object in a serilog sink or enricher ?

**Comment by abrasat** [comment]
Got the dictionary data by casting the LogEventPropertyValue to the DictionaryValue type.
Is there any possibility to add some "hidden" properties to the LogEvent, which are not serialized to JSON by default?

**Comment by bartelink** [comment]
An Enricher can mutate the dictionary, removing properties from the LogEvent as they pass through the rendering pipeline.

I'd appeal to you to provide your actual problem and not a proxy for it, so the best solution can be found.

**Comment by abrasat** [comment]
I described my use-case here [https://github.com/serilog/serilog/issues/1311](https://github.com/serilog/serilog/issues/1311)
By using a serilog sink I have now the timestamp (received from an embedded system as a long value containing the unixtime) as LogEvent timestamp, but it appears also as text in the log message (it is stored in a dictionary inside a LogEvent property which is set as LogEvent timestamp in a serilog sink)). I would like to have it only as LogEvent timestamp and "hide" it in the message text

**Comment by bartelink** [comment]
In that case, it seems you just need to override the message template for your Sink to not include the timestamp ?

**Comment by abrasat** [comment]
Thank you for the hint, it put me on the right direction!
Actually I did not change the message template, but used a dictionary property with one of the items containing the timestamp. In the sink I extracted the timestamp and then removed it from the dictionary when re-creating the LogEvent.
