### ISSUE TITLE
New sink: Serilog.Sinks.AmazonS3 available soon.

### ISSUE THREAD

**Issue by SeppPenner** [serilog/serilog#1318]
Hi, I've created a new serilog sink to upload log files to Amazon S3 storage. The intention was to upload the files to make them available for Amazon EMR services or similar analytics. The sink will be under https://github.com/SeppPenner/Serilog.Sinks.AmazonS3. I plan to provide the code in some hours when I'm done with testing.

@nblumhardt I will give you the Nuget package link and stuff, so that you can add this to the https://github.com/serilog/serilog/wiki/Provided-Sinks wiki.

**Comment by merbla** [comment]
Hi @SeppPenner,

Let us know when you have a package setup on NuGet and we can update the wiki.

**Comment by SeppPenner** [comment]
The package is there: https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.AmazonS3 (It might take some time until it's indexed on nuget.org, however).

**Comment by nblumhardt** [comment]
Done! 👍
