### ISSUE TITLE
The CI builds take too much time.

### ISSUE THREAD

**Issue by teo-tsirpanis** [serilog/serilog#1321]
AppVeyor builds take a solid quarter of an hour, while all they have is to build and package one project.

This happens because before building, the CI process downloads the entire .NET Core SDK to match the exact version specified in `global.json`. As a sidenote, the version currently used, .NET Core SDK 2.2.300 is [not included in AppVeyor](https://www.appveyor.com/docs/windows-images-software/#net-framework).

A solution would be to entirely remove this mechanism, and simply use the latest .NET Core SDK version that is available. It significantly lessens the burden for new programmers who might not have that particular version installed. Besides, the syntax is mostly the same; at least for the features we require.

I will get a PR ready.

**Comment by merbla** [comment]
Thanks @teo-tsirpanis, in the past we have experienced issues when relying on the AppVeyor SDK installed hence the reason for the [info](https://github.com/serilog/serilog/blob/dev/Build.ps1#L3) listed at the start of the build.

Perhaps updating the version to a known version might be the first step (`2.2.4`)?   

`.NET Core 3.0.0-preview-27122-01 runtime (Visual Studio 2019 Preview)` is in the pipeline and we may not want to move to it immediately when AppVeyor updates their infrastructure.

The current build process gives us a degree of control.

**Comment by nblumhardt** [comment]
:+1:
