### ISSUE TITLE
Setting Global Minimum Level Declaritively

### ISSUE THREAD

**Issue by markolbert** [serilog/serilog#1324]
This is an admittedly minor issue/question/enhancement request. The context/environment is Net Core 2.2, although I don't think that matters.

Setting the global minimum log level (i.e., on LoggerConfiguration, not an individual sink) is done by calls like this:

 `new LoggerConfiguration().MinimumLevel.Debug()`

Would it break something to do it like this:

`new LoggerConfiguration().MinimumLevel(LogEventLevel.Debug)`

The latter approach appears to fit better with setting minimum levels when those levels are specified through configuration. OTOH, building an extension method to work around the issue isn't that big a deal:

```
public static LoggerConfiguration SetMinimumLevel( this LoggerConfiguration config, LogEventLevel minLevel )
{
    if( config == null ) return null;

    switch (minLevel)
    {
        case LogEventLevel.Debug:
            config.MinimumLevel.Debug();
            break;

        case LogEventLevel.Error:
            config.MinimumLevel.Error();
            break;

        case LogEventLevel.Fatal:
            config.MinimumLevel.Fatal();
            break;

        case LogEventLevel.Information:
            config.MinimumLevel.Information();
            break;

        case LogEventLevel.Verbose:
            config.MinimumLevel.Verbose();
            break;

        case LogEventLevel.Warning:
            config.MinimumLevel.Warning();
            break;
    }

    return config;
}
```

But such an extension is fragile if and when there are other log levels added.

**Comment by nblumhardt** [comment]
Hi Mark, thanks for the suggestion.

I think you're looking for: `MinimumLevel.Is(LogEventLevel.Debug)` - does that cover it?

Best regards,
Nick

**Comment by markolbert** [comment]
Yep, I am. I just didn't know that construct existed, as I don't recall seeing it in the documentation :). Thanx!
