### ISSUE TITLE
Docs: No logging information when the logger failed to configure correctly :/

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog#1326]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [ ] New Feature
- [X] Update to docs

**What version of Serilog is affected?  Please list the related NuGet package.**
Latest : 2.8.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Give then common "Getting Started with a Console" example, if the setting up of the Logger failed to parse the details because (for example) a some bad data was provided to a Sink which tried to parse some config file data (or could be hardcoded) ... the Logger fails to `CreateLogger()`. Now when we try and log _why/what happened_ in the exception handler, we're stuck with the default `SilentLogger` and nothing is dumped .. anywhere.

**Please describe the expected behavior?**
It would be nice to suggest a fall back if the worst case happens -> the first thing in the console app is to create a logger, but we messed up and _that failed_. So we log the error to the Console. Nothing fancy and possibly the wrong place ... but something is better than nothing AND we are in an emergency right now. 

**More Info**

Here's some sample code i was thinking of and I got stuck at checking if the current Log.Logger is a SilentLogger ...

```
        static void Main()
        {
            // THIS FAILS.... 
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .WriteTo.File("logs\\myapp.txt", rollingInterval: RollingInterval.Day)
                .CreateLogger();
            }
            catch (Exception ex)
            {
               if (Log.Logger is SilentLogger)
               {
                   Console.WriteLine("assplosion etc...");
               }
               else
               {
                    Log.Error(ex, "Something went wrong");
               }
            }

            Log.CloseAndFlush();
            Console.ReadKey();
        }
```

e.g.

![image](https://user-images.githubusercontent.com/899878/59903954-aa295300-9445-11e9-85e7-00eba62fd7c4.png)

so yeah .. thoughts and help?

**Comment by PureKrome** [comment]
So - can anyone help determine if the current logger is a `SilentLogger` (as in the example above) .. so if it is, I can manually handle logging to console instead (this is an emergency scenario).

I just can't seem to check for that? I would have thought this would have worked but it doesn't:

```
if (Log.Logger == null ||
    Log.Logger is Serilog.Core.Pipeline.SilentLogger) 
{
   // write to console
}
else
{
    // write via SL
}
```

![image](https://user-images.githubusercontent.com/899878/60477086-634b2100-9cc1-11e9-8067-eb087c99b6fe.png)

**Comment by nblumhardt** [comment]
Hi! Not sure it's better, but you _could_ just try inverting the test:

```csharp
if (!(Log.Logger is Logger))
```

(Not tested by me but I think this is close to what you need :-))

**Comment by PureKrome** [comment]
~But that won't work because if we have a [SilentLogger](https://github.com/serilog/serilog/blob/8ed3afd0f2d942429832b6674a2f599c7fb1fa38/src/Serilog/Core/Pipeline/SilentLogger.cs#L21) is an ILogger same as a [Logger](https://github.com/serilog/serilog/blob/8ed3afd0f2d942429832b6674a2f599c7fb1fa38/src/Serilog/Core/Logger.cs)~

Ah.. tricky. I kept thinking an `SL` was an `L` .. but it's an `IL`.

/me tries...

yep worked.

final code...  (note: i might add some more ascii to it)

```
if (Log.Logger is Logger)
{
    // TODO: Add metrics (like Application Insights?) to log telemetry failures.
    Log.Logger.Fatal(exception, errorMessage);
}
else
{
    Console.WriteLine(errorMessage);
    Console.WriteLine(exception.Message);
}
```

So IMO, can I submit a PR to update the [web-sample](https://github.com/serilog/serilog-docker/blob/master/web-sample/src/Program.cs#L16) with this simple suggestion?

**Comment by nblumhardt** [comment]
Thanks for the follow-up.

I think it's an unusual-enough use case that having this discussion thread will be enough documentation for now, but if it comes up repeatedly then we can revisit the sample 👍 

Thanks again!
