### ISSUE TITLE
New alternative sink for Microsoft Teams available

### ISSUE THREAD

**Issue by SeppPenner** [serilog/serilog#1327]
The new sink is based on .NetStandard 2.0 and bundles the messages according to topics.

Links:
* https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams
* https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams

It fixes both issues from the reference https://github.com/DixonDs/serilog-sinks-teams/issues.

**Comment by nblumhardt** [comment]
Done, thanks!
