### ISSUE TITLE
Optional argument of MessageTemplateTextFormatter is not syntactically optional

### ISSUE THREAD

**Issue by bender2k14** [serilog/serilog#1328]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.8.0 (currently the latest)

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

All or NA

**Please describe the current behavior?**
The only [constructor of `MessageTemplateTextFormatter`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs#L44) requires as its second and last argument a reference to an instance of `IFormatProvider`.  However, the documentation says that this reference is allowed to be `null`.  Indeed, `MessageTemplateTextFormatter` eventually passes this reference into four functions and all them syntactically specify that a reference to an instance of `IFormatProvider` is optional by providing the default value `null`.

**Please describe the expected behavior?**
I was expecting that the constructor of `MessageTemplateTextFormatter` would also syntactically specify that a reference to an instance of `IFormatProvider` is optional by providing the default value `null`.

If it would be helpful, I can create a PR to resolve this issue.

**Comment by nblumhardt** [comment]
Thanks for the note. I think a default `= null` would make sense, here :+1:
