### ISSUE TITLE
New sink for Telegram

### ISSUE THREAD

**Issue by SeppPenner** [serilog/serilog#1329]
I have created a new sink for Telegram here:
https://github.com/SeppPenner/Serilog.Sinks.Telegram

The nuget package is available here: https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.Telegram

**Comment by merbla** [comment]
Thanks @SeppPenner this has been added to the [sinks page](https://github.com/serilog/serilog/wiki/Provided-Sinks).

**Comment by SeppPenner** [comment]
@merbla I believe you have added the wrong sink...

However, I'm absolutely fine if @nblumhardt or you added mine (Please check the links above) as `alternative`, the other sink on the sinks page https://github.com/serilog/serilog/wiki/Provided-Sinks is from @carlozamagni.

**Comment by SeppPenner** [comment]
Well, I cannot re-open the issue by the way. (Do not know if this is intended?)

**Comment by nblumhardt** [comment]
Fixed, thanks for spotting it 👍
