### ISSUE TITLE
[New Feature] Limit boxing for Logger Write methods

### ISSUE THREAD

**Issue by Scooletz** [serilog/serilog#1331]
AFAIK Logger now skips boxing and creating an `object[]` if the log level is not enabled. I tried to follow the whole path and eventually, all the calls to `.Write` end in https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Logger.cs#L361-L375 which effectively boxes values and allocates the mentioned array. I followed the flow which is 

`Logger.Write` -> 
 `MessageTemplateProcessor.Process` -> 
`PropertyValueConverter.CreatePropertyValue`

which potentially could have a generic overload for `CreatePropertyValue` and then allow to propagate the unboxing to the calls above. 

Would that be something interesting for you? I think I could try to spike it and then we could have a follow up discussion under this issue.

This is somewhat related to [my work on extending the public seam](https://github.com/aspnet/Extensions/pull/1874) of `Microsoft.Extensions.Logging` and finding that eventually Serilog will box and allocate anyway.

**Comment by nblumhardt** [comment]
I think with this one still up in the air, it might be best to close it here, and discuss via the PR when we have something to go on. Cheers!

**Comment by Scooletz** [comment]
Sure @nblumhardt This issue was created in the "issue first, PR second" manner 😄
