### ISSUE TITLE
Add LogContext properties for remainder of HttpRequest (higher in call stack)

### ISSUE THREAD

**Issue by agilenut** [serilog/serilog#1333]
Is there a way to add logging properties so that they can be later logged by classes higher in the call stack?

I've tried LogContext.PushProperty() but the added properties are not available to any controllers or middleware higher in the call stack. I assume this is due to the use of AsyncLocal<>. 

Ideally, I'm looking for a way to add a logging property in a domain service and have it added to any subsequent logs created in the calling controller and middleware during that HttpRequest.

**Comment by nblumhardt** [comment]
Hi! As luck would have it, I've been working on this for the past week, and it's now published in a pre-release update to _Serilog.AspNetCore_.

If you're using that library, you can just update to the `3.0.0-dev-*` version, call `UseSerilogRequestLogging()` on your `IApplicationBuilder`, and add properties using `IDiagnosticContext.Add()` (available via DI).

The feature is described in more detail here: https://github.com/serilog/serilog-aspnetcore/pull/94#issue-290980797

In the future, it's likely that some part of this will be implemented within `LogContext`.

If you have questions or feedback (or if this turns out to be perfect!) it would be great to hear.

**Comment by nblumhardt** [comment]
* Example configuration: https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/EarlyInitializationSample/Startup.cs#L53
 * Example of usage: https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/EarlyInitializationSample/Controllers/HomeController.cs#L28

**Comment by agilenut** [comment]
Interesting. 

I began working toward a similar solution. I already had my own middleware that was logging requests and a few custom Enrichers that pulled information from the HttpContext. 

The solution I had been working toward was to create an IRequestLoggingScope which wrapped IHttpContextAccessor and stored log properties in HttpContext.items. This seems similar to your IDiagnosticContext except it uses HttpContext.Items instead of AsyncLocal. Then, a registered enricher would pull data out of the cached HttpContext.Items collection and add it to the log event. 

Due to the custom HttpContext enrichers I already had in place, this was a fairly straight-forward incremental change and seems to work. Do you see any significant benefit over the use of IDiagnosticContext?

**Comment by tsimbalar** [comment]
@agilenut that sounds **a lot** like what we've been doing in "non Core" ASP.NET in https://github.com/serilog-web/classic-webapi and https://github.com/serilog-web/classic-mvc :)

**Comment by nblumhardt** [comment]
@agilenut the reason for avoiding `IHttpContextAccessor` in the implementation of `IDiagnosticContext` was to support use cases like message handling, [gRPC](https://gsferreira.com/archive/2019/04/logging-grpc-requests-using-serilog/), and so-on, where the overall structure of the app is similar (collect property data and emit in one completion event) but the HTTP pipeline isn't used.

I checked out the typical implementation of `HttpContextAccessor` and was careful to match its semantics as closely as possible in the diagnostic context - so apart from pathological cases I haven't spotted, the behavior should be the same.

**Comment by agilenut** [comment]
Thanks for the clarification. Makes sense. Since our middleware is already fairly reliant on HttpContext, I think we may stick with what I have working. But we might look into switching over to your middleware sometime later.

**Comment by nblumhardt** [comment]
Thanks! If you have a chance to spike it out sometime, it would be great to hear whether there are any substantial differences from what you've been running. I'll close this but keep an ear to the ground :-)
