### ISSUE TITLE
Destructuring F# ValueNone throws an exception

### ISSUE THREAD

**Issue by atlemann** [serilog/serilog#1339]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.8.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

Running this in F#:

```fsharp
logger.Information("Try to destructure voption {Params}", ValueOption.None)
```

Gives this in the log:

```
[09:16:03 INF] Try to destructure voption Capturing the property value threw an exception: InvalidOperationException
```

**Please describe the expected behavior?**

Behave similar to `Option.None`, or at least not throw an exception.

**Comment by nblumhardt** [comment]
Hi! This might be a good candidate for inclusion in: https://github.com/destructurama/fsharp/ .. any chance you'd be interested in PR-ing it over there? Cheers!

**Comment by atlemann** [comment]
I could give it a try when I'm back from vacation, which just started.

**Comment by nblumhardt** [comment]
Great, thanks. I'll close this here as it's not a Serilog issue; we can track it in the other project 👍
