### ISSUE TITLE
Use Particular Log Context Properties If having two Logger Configuration

### ISSUE THREAD

**Issue by vasanth3390** [serilog/serilog#1345]
LogContext is static and shared across all the logger configuration. The Properties and values from LogContext will gets logged only if Enrich.FromLogContext() is set for Logger Configuration.

In my case, I am having two logger configuration and assigned it to two different logger. I am having two properties pushed in LogContext as below

                LogContext.PushProperty("ConversationId", samplevalue);
                LogContext.PushProperty("TransactionId", samplevalue);

I could able to get the above two value when the application gets started.

I need to exclude one property when using first logger (i.e ConversationId) and I need to have both the properties when using another logger. I have enabled enrich.FromLogContext() in both the logger configuration. Let me know if there is any way to achieve the above scenario

**Comment by nblumhardt** [comment]
Hi! Using `secondLogger.ForContext("ConversationId")` will enrich its events, without putting the property onto the shared `LogContext`.
