### ISSUE TITLE
Newline character skipped when log message is 120 characters long (.Net Core)

### ISSUE THREAD

**Issue by Macaddict42** [serilog/serilog#1350]
I've been looking all over for an explaination as to why I'm getting multiple log messages on the same line. 

2019-07-31 14:12:00.145 [Debug] (MyExample.Common.MessageParser) Received SendFileChunkRequest - Length: 32806
2019-07-31 14:12:00.149 [Debug] (MyExample.Common.SerialPortWrapper) Sending SendFileChunkResponse - Length: 24
**2019-07-31 14:12:00.154 [Debug] (MyExample.Common.MessageParser) Received SendFileChunkRequest - Length: 79332019-07-31 14:12:00.156 [Information] (MyExample.Client.Services.OutputService) DownloadFile Complete**
2019-07-31 14:12:00.156 [Debug] (MyExample.Common.SerialPortWrapper) Sending SendFileChunkResponse - Length: 24
2019-07-31 14:12:00.195 [Debug] (MyExample.Common.MessageParser) Received DownloadFileResponse - Length: 49
2019-07-31 14:12:00.197 [Information] (MyExample.Client.Program) Press any key to stop the server...

I read somewhere that this won't happen as long as you only use a single logger. I'm doing this but I'm also using logger.ForContext() which I suspect is actually creating a new logger rather than enriching the original. 

Is there any way to have a logger that includes the name of my class while still being threadsafe to avoid writing multiple messages to the same line?

.Net Core 3.0 Preview 7
Serilog: 2.8.0
Serilog.Sinks.Console 3.1.1
Serilog.Sinks.RollingFile 3.3.0

Logger registration:

```csharp
var logFormat = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] ({SourceContext}) {Message}{NewLine}{Exception}";
container.Register<ILogger>(() => new LoggerConfiguration()
#if DEBUG
                .MinimumLevel.Debug()
#else
                .MinimumLevel.Information()
#endif
                .Enrich.FromLogContext()
                .WriteTo.Console(outputTemplate: logFormat)
                .WriteTo.RollingFile(logName, outputTemplate: logFormat, shared: true)
                .CreateLogger(), Lifestyle.Scoped);
```

**Comment by skomis-mm** [comment]
Hi, @Macaddict42. Try to use singleton lifetime instead of scoped. Generally there should be one root logger instance.

**Comment by Macaddict42** [comment]
I tried that, no difference. Not surprising because I only have one scope so it's effectively acting like a singleton.

**Comment by nblumhardt** [comment]
Hi @Macaddict42; somehow there will still be multiple instances of `ConsoleSink` involved in this. I've raised a PR on the sink to synchronize writes in this case, but if you can work out how multiple pipelines might be being created in your app, there are other good reasons to switch to a single pipeline. HTH!

**Comment by nblumhardt** [comment]
Hi @Macaddict42 - let us know if you have more info you can add to the ticket, we'll otherwise close it as we don't have enough context to make useful progress on it. Thanks!

**Comment by Macaddict42** [comment]
I'll try and make a sample project to reproduce the issue in the morning.

**Comment by Macaddict42** [comment]
Alright I've narrowed down the problem and it's quite a bit different than I originally though. It appears the issue is simply with the length of the log message. You can reproduce the issue using Serilog.Sinks.Console. And this code:

```csharp
var logFormat = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] ({SourceContext}) {Message}{NewLine}{Exception}";

var logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .Enrich.FromLogContext()
    .WriteTo.Console(outputTemplate: logFormat)
    .CreateLogger().ForContext(typeof(Program));

logger.Information("This is a message of the magic length ------------");
logger.Information("This is a message of the magic length ------------");
logger.Information("This is a message with one less character length-");
logger.Information("This is a message with one less character length-");
logger.Information("This is a message of the magic length ------------");
logger.Information("This is a message of the magic length ------------");
logger.Information("This is a message with one more character length-");
logger.Information("This is a message with one more character length-");

Console.ReadLine();
```

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/62400568-00e88780-b5c3-11e9-9d08-5aca6b2e7a65.png)

🤔

**Comment by Macaddict42** [comment]
Are you using .Net Core 3.0 Preview 7? This was also on Visual Studio 2019 16.3 Preview 1. Visual studio version shouldn't matter, but .Net Core version probably does.

**Comment by Macaddict42** [comment]
I confirmed, the issue is not present on .Net Framework but is on .Net Core 2.2+. So you don't need 3.0 Preview 7.

**Comment by nblumhardt** [comment]
Thanks for taking the time to narrow it down. I'm using .NET Core 3 preview 7, though, so there must still be some difference. Are you using the standard cmd.exe Windows terminal?

**Comment by Macaddict42** [comment]
I zipped up the exact same project on one computer and ran it on my other desktop. It runs fine there. There's something special about my one development machine that's having this issue. I'll try to gather more information on monday. Thanks for the help.

**Comment by Macaddict42** [comment]
Well, I've determined the issue appears to be a bug in the windows 10 console. I can reproduce it without serilog entirely using just Console.WriteLine(). What happens is in the console settings under the layout tab, there is a checkbox that says "Wrap text output on resize". If this is checked, and the text is exactly the width of the console window, when you resize the lines will run together. By default, the console width should be 120 characters. But if you've resized it on your system, it will be different. So the workaround is to just resize your default console width. Thanks for the help.

**Comment by nblumhardt** [comment]
Interesting! Thanks for closing the loop :+1:

**Comment by olegku** [comment]
Worth to mention that this bug is reproducible when Virtual Terminal mode is enabled: https://github.com/serilog/serilog-sinks-console/blob/65e237f685e017cbdae05ee5ff8b77b3713cf81e/src/Serilog.Sinks.Console/Sinks/SystemConsole/Platform/WindowsConsole.cs#L37
