### ISSUE TITLE
Optionally write final layer of ToMaximumDepth as ScalarValue instead "Null"

### ISSUE THREAD

**Issue by HeartofTheForce** [serilog/serilog#1351]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.8.0 

**Please describe the current behavior?**
Currently reaching maximum depth sets all values on that layer to "Null"

**Please describe the expected behavior?**
Have an optional flag to serialize final depth as using ScalarValue types e.g.
`.Destructure.ToMaximumDepth(3, writeFinalDepthAsScalar: true)`

**Comment by nblumhardt** [comment]
That's an excellent idea, thanks - if it had been suggested early on, we'd have made this the default, I think. We still might want to consider changing the default, if we can implement this seamlessly enough (a 3.0 feature?).

**Comment by HeartofTheForce** [comment]
@nblumhardt I've made a PR for this here #1357

**Comment by nblumhardt** [comment]
Hi @HeartofTheForce - I notice you closed your PR; thanks for the help all the same! I'll mark this as up-for-grabs, let me know if you are interested in picking it back up.

**Comment by Jlalond** [comment]
@HeartofTheForce any reason you deleted your PR @nblumhardt I'm looking into this btw.

**Comment by nblumhardt** [comment]
Seems as though this one is stale; still a really interesting idea if anyone decides to look into it, but I'll close this as it's now been quite some time without activity.
