### ISSUE TITLE
Custom format string not accepted by the message template parser

### ISSUE THREAD

**Issue by EamonHetherton** [serilog/serilog#1353]
This might be a little esoteric but as I understand the message formatting is intended to follow standard .net formatting:
 >Message templates are a superset of .NET format strings. That means every valid .NET format string is also a valid message template.
[blog](https://nblumhardt.com/2016/06/message-templates-and-properties-structured-logging-concepts-in-net-3/)

So in that spirit I'm raising an issue that serilog does not support using the [";" section separator for numeric formats](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#SectionSeparator).

likely related to #1323, #1325

I'm currently migrating some old code from Diagnostics.Trace to serilog and found a particular message was failing

The message logged a number of process metrics in a table-like fashion using alignment with the following format string:
`"{0,-25} {1,10:#,##0} {2,10:#,##0} {3,10:+#,##0;-#,##0;0} {4,10:0.00}"`

With serilog:
`Log.Information("{0,-25} {1,10:#,##0} {2,10:#,##0} {3,10:+#,##0;-#,##0;0} {4,10:0.00}", "Process.HandleCount:", 1364, 1370, 6, 0.4398826979472);`
produces 
> Process.HandleCount:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1364&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1370&nbsp;{3,10:+#,##0;-#,##0;0}&nbsp;0.4398826979472

vs

`Trace.WriteLine("{0,-25} {1,10:#,##0} {2,10:#,##0} {3,10:+#,##0;-#,##0;0} {4,10:0.00}", "Process.HandleCount:", 1364, 1370, 6, 0.4398826979472);`
 that produces the expected
>Process.HandleCount:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1,364&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1,370&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.44

The main problem is the "{3,15:+#,##0;-#,##0;0}" part which is not identified as a format string but instead rendered literally.

Actually looking at that output now I realise that it has also ignored other parts of the numeric string formats.

Currently not sure whether this is core Serilog behaviour or the sink(s).  I'm currently using the File sink.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Eamon - sounds like a bug. Are you running 2.8.0? Cheers!

**Comment by EamonHetherton** [comment]
Yeah, 2.8.0.

Quite the collection actually :)

`<PackageReference Include="Serilog" Version="2.8.0" />`
`<PackageReference Include="Serilog.Sinks.Async" Version="1.4.0" />`
`<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />`
`<PackageReference Include="Serilog.Sinks.Debug" Version="1.0.1" />`
`<PackageReference Include="Serilog.Sinks.File" Version="4.1.0-dev-00847" />`
`<PackageReference Include="Serilog.Sinks.File.Header" Version="1.0.0-dev" />`
`<PackageReference Include="Serilog.Sinks.Seq" Version="4.0.0" />`
`<PackageReference Include="Serilog.Sinks.Trace" Version="2.1.0" />`
`<PackageReference Include="SerilogMetrics" Version="2.1.0" />`
`<PackageReference Include="SerilogTimings" Version="2.2.0" />`
