### ISSUE TITLE
Question: Is there a way to have a specific log output every time the logger is initialized?

### ISSUE THREAD

**Issue by CreepyGnome** [serilog/serilog#1356]
I would like to output at least one log message that has no level that is just like a "header" or "I'm actually started" type of message.  Or be told why it's a bad idea to do this as I don't think any logger has ever supported this and have always had to hack around it in the past. 

When it was just a single "line" per log entry type of it was nice to know that logging is really initialized and everything appears to be good after the application started without logging information messages.  Basically, something like "<Application/Service Name> has started" each time the app starts to show its started without errors if this is the only line in the after starting. 

This was useful in headless situations where we have no easy way for a CM/DevOps type person to know the services started without errors. 

Now we do post-deployment testings so maybe this is less of an issue, and with structured logging now maybe it's just a bad idea.  So looking for good reasons why its a bad idea and I can stop trying to stuff like this, or why it doesn't really matter and here is how you can do it in Serilog without it being hacky! ;)

Any direction is appreciated! Thanks in advance!

**Comment by tsimbalar** [comment]
I typically just log at info level as early as possible a message like "App is started" , and attach properties like version number or anything that can be useful to track deployments.

**Comment by nblumhardt** [comment]
👍 I do the same as @tsimbalar - this kind of thing:

https://github.com/serilog/serilog-aspnetcore/blob/5d49fee2cc2014fbd4aa0898dce15e74b99897b6/samples/EarlyInitializationSample/Program.cs#L32

I don't think it's a feature we're likely to build in, if only because we want to keep the codebase as lean as possible and so exclude most features that can be added on externally. Not at all a bad idea!

**Comment by CreepyGnome** [comment]
@tsimbalar yeah right, but how does that make it to a log output that is set to warning or error? It will not log that message.

@nblumhardt yeah that is what everyone does but doesn't solve the problem I presented, nor does it explain that I shouldn't want this feature.  The point is logs should really be no lower than warning but mots likely at error for majority of the products use. So how do you get "I am started" logged in those situations?  The purpose is to make sure that an entry is created proving the service/app started, especially in headless situations. As if no warnings or errors happen, which is what you want, you have to find other ways more cumbersome sometimes to verify the service/app is really started as sometimes just looking at a log is easy. Same for the exit/shutdown message. 

Like if a logger added flags to say write starting and/or ending messages and what provides a way to set what each will say. Then you could have a log file, console, sink, etc that has only these as its starts and stops, and you will have logged when it started and stopped which is important information to have in a log in many cases.  

I would think this would be a good candidate for an Enricher however I didn't see any way for them to force output without a log level, to have access to a raw stream or anything.  Also would be nice to control which sinks it goes to, etc.

It seems like to allow this is a low-level change at the core and would have to be implemented safely and as disabled by default.  

If its something that you would be willing to consider seriously, I can try to find time to work on it and if I can find a clean way to pull it off I could send you PR for review. However, if you don't think this fits your goals for this project I completely understand I will not pursue it further.

**Comment by nblumhardt** [comment]
@CreepyGnome ah, I understand what you mean, now 👍

One thing to look at:

```csharp
var levelSwitch = new LoggingLevelSwitch(Level.Information);

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .WriteTo.Console()
    .CreateLogger();

Log.Information("I'm alive!");
levelSwitch.MinimumLevel = LogEventLevel.Warning;
```

Regarding writing an event with no level, casting the root logger to `ILogEventSink` and calling `Emit()` will have this effect, although it requires manually constructing a `LogEvent` to pass through.

Filters could be used to control destinations for the event, if needed (sink-level filtering, coming in 2.9, might simplify this a bit).

At shut-down, the level switch or `ILogEvent.Emit()` tricks should come close to covering it.

It's an interesting use case, though; thanks for taking the time to explain. I think right now it's great food for thought but for much the same reasons as above, we'd probably not consider adding support directly in the near future.

If you come up with a combination of features that works to your liking, a blog post, Gist, or separate NuGet package might be a good way to get it out there. Cheers!

**Comment by CreepyGnome** [comment]
@nblumhardt thanks for sharing a workaround its a good way to get similar results withing the existing framework.

I have two concerns right off the bat which is event leakage.  First, there is a brief moment when more than your one message could be logged.  Could be a minor issue depending on the system you are adding logging to and when you add it. Second, I would have to either have a special JSON configuration section to control this as I will be overriding the configured logging levels and could not hard code it to go back to "Warning" if it was not at warning before. An alternative could be I would have to get the current configured logging level for all the things required as they can be different for each sink and then change them all and change them all back to what they were set before as well.

I currently cannot see how something external to the core of a logging framework support this functionality of "start" and "stop" type messages that are not related to logging levels and are just a simple message with a timestamp. Which is why I think I may be crazy that I've _needed_ this in the past and hacked around my previous logging frameworks to achieve something similar to what you suggested essentially. Which is why I was hoping someone to explain why I am crazy and talk me out of actually every really needing it and why having no logs on startup and shutdown of a system/app is perfectly okay. :)

Thanks for your time discussing the topic.  For now, I am going to proceed as if I don't need this and see what happens and how it goes. ;)

**Comment by skomis-mm** [comment]
@CreepyGnome you can also use dumb private source context combined with minimum level overrides to without the risk of getting more log events than needed:
```csharp
class Program
{
    static void Main(string[] args)
    {
        var logger = new LoggerConfiguration()
                .MinimumLevel.Warning()
                .MinimumLevel.Override(typeof(Startup).FullName, LogEventLevel.Information)
                .WriteTo.Console()
                .CreateLogger();

        logger.LogStartup();

        // ...
        logger.Information("invisible");
        // ...

        logger.LogShutdown();
    }

}

class Startup { }

static class LogExtensions
{
    public static void LogStartup(this ILogger logger)
        => logger.ForContext<Startup>().Information("service started");

    public static void LogShutdown(this ILogger logger)
        => logger.ForContext<Startup>().Information("service shutted down");
}
```

**Comment by CreepyGnome** [comment]
Hey, @skomis-mm that looks pretty clean actually didn't know about the overwrite for based on a type.  I think that is the best workaround/solution for this issue yet. Thanks!

**Comment by nblumhardt** [comment]
..and I'd overlooked that option, too - nice one!
