### ISSUE TITLE
Improve Serilog.PerformanceTests with more tests and code converge

### ISSUE THREAD

**Issue by rafaelsc** [serilog/serilog#1359]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
N/A. This only affects the Serilog.PerformanceTests

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [x] netCore 1.0
- [x] 4.7
- [x] 4.6.x
- [x] 4.5.x

**Please describe the current behavior?**
The current performance tests test only specific parts in Serilog, missing the testing performance of "real-life" usage. The tests are missing better code coverage, testing more options, methods and using different combinations of types in each log.

**Please describe the expected behavior?**
 - Tests to simulate a "real-world" scenario.
 - Better code coverage. 
 - More tests logging with many combinations types.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
N/A.

**Comment by nblumhardt** [comment]
I think in this case the PR is adequate for tracking this, I'll close this ticket as it's somewhat redundant.
