### ISSUE TITLE
.Net Core 3.0

### ISSUE THREAD

**Issue by xaviergxf** [serilog/serilog#1365]
Hi,
  When will .net core 3.0 be supported?

Thanks

**Comment by nblumhardt** [comment]
Hi Xavier,

.NET Core 3.0 has been supported for a while now via `netstandard2.0` - are you having problems with it?

Best regards,
Nick

**Comment by tleylan** [comment]
Nick can I pick your brain for a few minutes :-) If there is a better place to discuss it please let me know. I'm using Serilog with >NET Core 3.0 (so xaviergxf there should be no problem) but I'm trying to discover the "cleanest" way to set up the configuration..

I think reading them from appsettings.json is ideal in that the settings can be modified without recompiling right? But I set the "path" to a full path (including the drive) but the drive letter when deployed is different from C: on localhost to D: on the server. Is there an accepted way to define a drive letter such that it will be different in those situations without editing the file? Do we define an environment variable perhaps? Or a combination of the folder in the appsettings and code to determine the drive?

Thanks for any pointers.

**Comment by tleylan** [comment]
I just found an example that uses %TEMP% as the drive letter which I assume that is an environment variable. Of course now that has to be set in any place that hosts the website. Do we think that is the ideal way?

**Comment by nblumhardt** [comment]
Hi @tleylan - thanks for the note; this one might be better to put to the brains trust in https://gitter.im/serilog/serilog - cheers!

**Comment by xaviergxf** [comment]
@nblumhardt i heard .net core 3.0 had some changes on simplifying log setup on the host.

**Comment by nblumhardt** [comment]
Hi @xaviergxf - check out https://github.com/serilog/serilog-aspnetcore for some 3.0 examples that show the new hosting setup 👍 (the _Serilog.AspNetCore_ and _Serilog.Extensions.Hosting_ packages facilitate this).
