### ISSUE TITLE
Formatting Timestamp as total milliseconds

### ISSUE THREAD

**Issue by sawilde** [serilog/serilog#1367]
I can see how I can format the TimeStamp as UTC by using the `:o` formatting directive but I can't see how I would format this as total milliseconds - is this possible with serilog as it is or do I need to add some additional hooks into serilog to allow this formatting - if the latter then some guidance please.

**Comment by nblumhardt** [comment]
Hi Shaun, thanks for the note.

There's no format that I'm aware of that will write milliseconds from epoch. The standard approach to these sorts of problems in Serilog is to create an `ILogEventEnricher` (a few examples out there) that computes the required value and adds it to a new event property like `TimestampMS`, and then include the generated `{TimestampMS}` value in the sink's `outputTemplate`.

HTH,
Nick

**Comment by sawilde** [comment]
@nblumhardt that's fine and thanks for pointing me in the right direction
