### ISSUE TITLE
Community Project: Prism.Logging.Serilog

### ISSUE THREAD

**Issue by caioproiete** [serilog/serilog#1372]
I'd like to add **[Prism.Logging.Serilog](https://github.com/caioproiete/prism-logging-serilog/)** to the [Community Projects](https://github.com/serilog/serilog/wiki/Community-Projects) page.

This library integrates Serilog with the [Prism library](https://github.com/PrismLibrary) for WPF, UWP, and Xamarin Forms apps by providing a custom implementation of Prism's `ILoggerFacade`, that forwards messages to a Serilog logger, allowing developers to capture the logging events written in their _ViewModels_ and _Services_, in Serilog.

---

### Prism.Logging.Serilog
* Source code: https://github.com/caioproiete/prism-logging-serilog/
* NuGet package: https://www.nuget.org/packages/Prism.Logging.Serilog/

**Comment by nblumhardt** [comment]
Done, thanks!

https://github.com/serilog/serilog/wiki/Community-Projects

**Comment by DinnerGit** [comment]
Prism.Logging.Serilog 已经无法使用
