### ISSUE TITLE
Add in-memory sink to the wiki

### ISSUE THREAD

**Issue by sandermvanvliet** [serilog/serilog#1375]
Not a bug but a request for an addition to the Serilog wiki.

I've created a sink that captures log events in memory to make it easier to verify that your code sends certain log messages: [Serilog.Sinks.InMemory](https://github.com/sandermvanvliet/SerilogSinksInMemory/)

Unfortunately I can't find the right avenue to provide a PR to add it to the [list of sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) on the wiki, which is why I've created this issue.

I would appreciate some help here, if I need to create a PR please let me know!

**Comment by nblumhardt** [comment]
Done - thanks! 👍
