### ISSUE TITLE
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by 51tharea** [serilog/serilog#1380]
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

>  at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
>    at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Objec
> t asyncState)
>    at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creation
> Options)
>    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
>    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
>    at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
> 

```
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.File(new CompactJsonFormatter(new JsonValueFormatter()),
                    "Logs/app.json",
                    fileSizeLimitBytes: 8000,
                    rollingInterval: RollingInterval.Day).CreateLogger();
            try
            {
                Log.Information("Starting web host");
                CreateWebHostBuilder(args)
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseSerilog((context, configuration) =>
                    {
                        var loggerConfiguration = configuration
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Debug)
                            .ReadFrom.Configuration(context.Configuration);

                        if (context.HostingEnvironment.IsDevelopment())
                        {
                            loggerConfiguration = loggerConfiguration.MinimumLevel.Debug();
                        }
                        else
                        {
                             loggerConfiguration = loggerConfiguration.MinimumLevel.Error();
                        }


                        loggerConfiguration.Enrich.FromLogContext().WriteTo.ColoredConsole();
                    })
                    .UseKestrel()
                    //.UseIISIntegration()
                    .UseUrls("https://*:3001")
                    .UseSetting("https_port", "3001")
                    .UseStartup<Startup>()
                    .Build()
                    .Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args);
```

if I use only  "UseSerilog()" then no warning message..

**Comment by nblumhardt** [comment]
Thanks for the note. Seems unlikely to be Serilog related, but enabling Serilog's `SelfLog` should show up any problems with the logging configuration that may be involved. HTH!

**Comment by 51tharea** [comment]
Thanks, mate. I'm trying again.    🙄
