### ISSUE TITLE
Question: why don't just ouput property name?

### ISSUE THREAD

**Issue by HppZ** [serilog/serilog#1383]
for this log call:
`Log.Warning("Disk quota {Quota} MB exceeded by {User}", quota, user);`
the output is:
**Disk quota 1024 MB exceeded by "nblumhardt"**
what if serilog could output property name, then the output would be:
**Disk quota Quota 1024 MB exceeded by User "nblumhardt"**
so we could rewritten that to 
`Log.Warning("Disk {quota} MB exceeded by {user}", quota, user);`
and output would be:
**Disk quota 1024 MB exceeded by user "nblumhardt"**

more:
if quota or user is null, the output is:
**Disk null exceeded by null**
if serilog output property name, the output would be be better
**Disk quota null exceeded by user null**

**Comment by bartelink** [comment]
can you expand please? OOTB either will work - Serilog uses with the exact name you put inside the `{` and `}` without altering the casing; i.e. any examples with PascalCasing of the name are just a convention (i.e. for instance I've settled on camelCasing as you suggest but that doesnt require any change that I can see?)

**Comment by HppZ** [comment]
I edited the comment. 
(I hate myself for my poor english)

**Comment by nblumhardt** [comment]
@HppZ thanks for the suggestion and clarification 👍 

It's not a change we can make (the impact on existing systems would be chaotic), but it would also be unsuitable for some kinds of messages (e.g. `"Logged on {Domain}/{User}"`), and need localization to be considered. Thanks again, though!
