### ISSUE TITLE
AppSettings conflict with ApplicationSettings

### ISSUE THREAD

**Issue by Chanhhoathom** [serilog/serilog#1388]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0  ( suspect )
- [ ] netCore 1.0
- [x ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
You cannot use AppSetting element and ApplicationSettings

**Please describe the expected behavior?**
Be able to use both  I have legacy application that has an old web service - I tried to merge the 2 elements but could not stop exceptions being thrown

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Simple demo 
 static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
           .MinimumLevel.Debug()
          // .WriteTo.File("logs\\myapp.txt", rollingInterval: RollingInterval.Day)
          .ReadFrom.AppSettings()
               .CreateLogger();

            Log.Information("Hello, world!");
and app.cofig as folllows

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <appSettings></appSettings>
  
</configuration>

**Comment by Chanhhoathom** [comment]
Wooops missed the app.config file.  The error if both are there is ConfigurationErrorsException: Unrecognized configuration section applicationSettings. 
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="serilog:minimum-level" value="Debug"/>
    <add key="serilog:using:File" value="Serilog.Sinks.File" />
    <add key="serilog:write-to:File.path" value="\Sample.txt" />
    <add key="serilog:write-to:File.rollOnFileSizeLimit" value="true" />
    <add key="serilog:write-to:File.fileSizeLimitBytes" value="2000" />
  </appSettings>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <applicationSettings></applicationSettings>
  
</configuration>

**Comment by Chanhhoathom** [comment]
[App_config.txt](https://github.com/serilog/serilog/files/3918187/App_config.txt)

**Comment by nblumhardt** [comment]
Hi! Thanks for the report.

I think this is a _System.Configuration_ problem and unrelated to Serilog; `<applicationSettings>` is not a standard/built-in element (might be custom?); if it's used by your app you'll need to do some digging to find out how it's consumed (see e.g. https://stackoverflow.com/questions/1316058/how-to-create-custom-config-section-in-app-config .)

Hope this helps,
Nick

**Comment by Chanhhoathom** [comment]
Yes you are .....

**Comment by Chanhhoathom** [comment]
The issue is not serilog but my flawed use of config
