### ISSUE TITLE
Destructuring as a separate package

### ISSUE THREAD

**Issue by goldenc** [serilog/serilog#1389]
Hi,
        We are using Serilog in combination with ElasticSearch for our structured logging concerns. One of the downsides/irritations of ES is the limit of 1000 fields per index (I know it can be increased but then we'd have to write custom code to create the index and its a bit of a pain). When you use destructuring it can quite easily blow this limit quite quickly. What would be nice IMO is to be able to separate out the destructuring part including all the nice attributes, fluent interface for configuration etc and just write the result as a string. This would then be shipped to ES as one field (I know Seq is better :) ) which we can still do rudimentary searches on.

Thoughts?

**Comment by nblumhardt** [comment]
Hi Cathal,

Thanks for the note. Not sure I properly understand your suggestion - this sounds like something to raise and discuss via the Elasticsearch sink, perhaps? I don't think we'd want to make any central changes to how Serilog works to deal with what seems like a point-in-time limitation of Elastic. I'd guess there's already a discussion somewhere in https://github.com/serilog/serilog-sinks-elasticsearch with some ideas. Let me know if I've misunderstood.

Cheers,
Nick

**Comment by goldenc** [comment]
Hi Nick,
              Thanks for the reply. I did consider creating the issue in the sink, and I agree its mainly a ES issue (wish i was using Seq :) ). I thought it was more a Serilog thing just be be able to extract out the power of destructuring into a separate library. Its quite a powerful feature especially with the ability to configure how the destructuring works via the various attributes and fluent interface. I realise its probably a big change but thought I'd mention it anyway. Feel free to close the issue.

in terms of an api I probably would consider something like

```
var destructureConfig = Destructure.ByTransform<Foo>(x => ....);
var foo = new Foo();
var destructuredString = destructureConfig.Destructure(foo);
```

Cheers,
Cathal

**Comment by nblumhardt** [comment]
Ah, interesting 👍 - thanks for the follow-up, Cathal.

Probably not something we have the bandwidth to consider, currently. Might be an interesting side-project to hack out as a wrapper for the current Serilog APIs? Thanks again for the suggestion, though!
