### ISSUE TITLE
restrictedToMinimumLevel with namespace overriding

### ISSUE THREAD

**Issue by baruchiro** [serilog/serilog#1391]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
```xml
<PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
<PackageReference Include="Serilog.Settings.AppSettings" Version="2.2.2" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
<PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
```

**What is the target framework and operating system?

- [x] netCore 2.1

**Please describe the current behavior?**

Today, you can define a `MinimumLevel` for the whole logger, and it's mean that these are the logs entries that will pass to the Sinks.
In the Sinks, you can add more level filter by `restrictedToMinimumLevel`, so the specific Sink will handle fewer logs.
But filtering logs by their Namespace, can be done only for the entire Logger, and you can't add Namespace filtering per Sink,

**Please describe the expected behavior?**

Option to define `Override` alongside the `restrictedToMinimumLevel` per Sink.

**Comment by nblumhardt** [comment]
Thanks for the note! You might find that `WriteTo.Conditional()` paired with _Serilog.Filters.Expressions_ covers most of what you need:

```csharp
    .WriteTo.Conditional(
        "SourceContext not like 'MyNamespace.%' or @Level in ['Warning', 'Error', 'Fatal']",
        wt => wt.SomeSink())
```

Let me know if this helps,
Nick

**Comment by baruchiro** [comment]
Knows what?
I knew it and forgot.

The last time I dealt with it I really found this solution at the end.

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up.
