### ISSUE TITLE
Potential bug in either template parser or renderer

### ISSUE THREAD

**Issue by davidpeden3** [serilog/serilog#1393]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

Serilog 2.8.0 by way of Serilog.AspNetCore 3.2.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netstandard2.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

I am emulating the Serilog `RequestLoggingMiddleware` in an Azure Function using filters. Everything works except that I discovered that properties with `.` in the name do not render correctly in the log line but do show up correctly as structured data properties. Though I'm doing this in the context of the ASP.NET Core package, I believe that the underlying core classes `MessageTemplateParser` and `MessageTemplateRenderer` are where the issue lies.

**Please describe the expected behavior?**

Property names with `.` should either work all of the time or none of the time.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

The following code:

```csharp
var logEventProperties = new List<LogEventProperty>
{
    new LogEventProperty("Request.Method", new ScalarValue(request.Method)),
    new LogEventProperty("Request.Scheme", new ScalarValue(request.RequestUri.Scheme)),
    new LogEventProperty("Request.Host", new ScalarValue(request.RequestUri.Host)),
    new LogEventProperty("Request.Port", new ScalarValue(request.RequestUri.Port)),
    new LogEventProperty("RequestPath", new ScalarValue(request.RequestUri.AbsolutePath)),
    new LogEventProperty("Request.AbsoluteUri", new ScalarValue(request.RequestUri.AbsoluteUri)),
    new LogEventProperty("Elapsed", new ScalarValue(_state.ElapsedMilliseconds)),
    new LogEventProperty("FunctionName", new ScalarValue(executedContext.FunctionName)),
    new LogEventProperty("FunctionInvocationId", new ScalarValue(executedContext.FunctionInstanceId))
};

var messageTemplateParser = new MessageTemplateParser();

var logEvent = new LogEvent(
    DateTimeOffset.Now,
    level,
    executedContext.FunctionResult.Exception,
    messageTemplateParser.Parse("HTTP {Request.Method} {RequestPath} responded in {Elapsed:0.0000} ms"),
    logEventProperties);

logger.Write(logEvent);
```

Produces the following log in Seq:

![image](https://user-images.githubusercontent.com/11466099/71922227-2ec49000-3150-11ea-9fa0-093b3304d1ce.png)

*Note:* the property `RequestPath` is intentionally missing a `.` separator to demonstrate a successfully rendered property. `Request.Method` is the property that is broken.

**Comment by nblumhardt** [comment]
Thanks for the report, David. In this case, we could almost say "properties with dotted names work none of the time" - in message and output templates.

Historically, this is because message templates were designed to work anywhere, on any logging pipeline, with any data store, so they stick to a lowest-common-denominator definition of what constitutes a valid property name.

Serilog's underlying pipeline is more flexible, but as you've observed, this does create a bit of inconsistency.

(Seq is very permissive because it can accept data from just about anywhere.)

I agree that there's a good argument for trying to bring the syntax and pipeline into line, but it's a horse that's already bolted, if we want to preserve the wide compatibility between [message template implementations](https://messagetemplates.org/#implementations) - which I think continues to be good for the ecosystem.

**Comment by davidpeden3** [comment]
Hey Nick, thanks for the link. I was unaware of that specification. I read through it and didn't see any restrictions on the allowable string literal between `{` and `}` as far as token names are concerned. Having said that, I'm certainly not married to `.` as a delimiter though I do prefer it. I tried `_` and it seems to work fine.

**Comment by nblumhardt** [comment]
Thanks for the follow-up 👍 

The allowed characters in a name are covered by: https://messagetemplates.org/#name

Cheers!
Nick

**Comment by davidpeden3** [comment]
Ah, totally skipped over that part apparently. Thanks for pointing it out.

**Comment by nblumhardt** [comment]
👍 thanks David.
