### ISSUE TITLE
New Sink for Humio

### ISSUE THREAD

**Issue by ThomasLeschley** [serilog/serilog#1394]
Hi!
I've created a new sink for Humio available here:
https://github.com/ThomasLeschley/Serilog.Sinks.Humio/

NuGet: 
https://www.nuget.org/packages/Serilog.Sinks.Humio/

I had need of a sink like this in a project im working on and figured others could find it useful as well.
Feedback and suggestions are very welcome!

Best regards
Thomas

**Comment by nblumhardt** [comment]
Thanks for the heads-up! 👍

**Comment by merbla** [comment]
Added over at [Provided Sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks)

**Comment by ragnarstolsmark** [comment]
@ThomasLeschley You beat me to it 👍 . I have created the following repo: 
https://github.com/IdentityStream-AS/Serilog.Sinks.Humio 
I have a couple of suggestions:
- Could you make it possible to set the humio url via configuration (for on-prem support)?
- Could you drop the serilog-aspnetcore dependency and instead have a direct dependency to serilog for those of us not using aspnetcore?
I am happy to provide a pull request if you need it.

**Comment by ThomasLeschley** [comment]
@ragnarstolsmark yes definitely! 
Great idea with the url configuration. I've only been using Humio's cloud so far but on-prem should definitely be supported as well.
I can make those changes by the coming weekend. You're most welcome to create pull-requests if you'd like it done before then :)
I also plan to write some automated testing as soon as im able.
