### ISSUE TITLE
New sink: MariaDB and MySQL

### ISSUE THREAD

**Issue by Dissimilis** [serilog/serilog#1395]
We have created a sink for MySQL and MariaDB with PeriodicBatching, Audit support.
Please add it to the wiki.

Links:
https://www.nuget.org/packages/Serilog.Sinks.MariaDB
https://github.com/TeleSoftas/serilog-sinks-mariadb
https://buildstats.info/nuget/serilog.sinks.mariadb

**Comment by merbla** [comment]
Thanks @Dissimilis, this has been added

**Comment by Rwing** [comment]
The repo "https://github.com/TeleSoftas/serilog-sinks-mariadb" is no longer public, so are there any risks associated with it?

**Comment by nblumhardt** [comment]
Thanks for the heads-up @Rwing. I've dropped this off of the relevant Serilog wiki page. I can't provide any useful info on risk one way or the other.
