### ISSUE TITLE
Custom format specifiers get ignored when applied inside the message template

### ISSUE THREAD

**Issue by AroglDarthu** [serilog/serilog#1396]
**Does this issue relate to a new *feature* or an existing *bug*?**
Could be either, but I suspect it is a bug.

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.9.0
Serilog.Sinks.Console 3.1.1

**What is the target framework and operating system?**
netCore 3.1

**Please describe the current behavior?**
I have a class that has it's own format specifiers. These are being ignored when used in the message template.

**Please describe the expected behavior?**
I would expect the same behavior as when using `string.Format`, `ToString(format)` and `string interpolation`.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

```
static void Main(string[] args)
{
    Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));
    var logger = new LoggerConfiguration()
        .WriteTo.Console(outputTemplate: "{Timestamp:HH:mm} [{Level:u3}] {Message}{NewLine}")
        .CreateLogger();

    logger.Information("Hello World!");

    var temperature = new Temperature(12);
    logger.Information("MessageTemplate : {Temperature:K}", temperature);
    logger.Information("String.Format   : {Temperature}", string.Format("{0:K}", temperature));
    logger.Information("ToString(format): {Temperature}", temperature.ToString("K"));
    logger.Information("Interpolation   : {Temperature}", $"{temperature:K}");
}
```
Output:
```
// [INF] MessageTemplate : "12,00°C"
// [INF] String.Format   : "285,15K"
// [INF] ToString(format): "285,15K"
// [INF] Interpolation   : "285,15K"
```

Temperature class taken from: https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types#the-iformattable-interface

```
using System;
using System.Globalization;

public class Temperature : IFormattable
{
   private decimal m_Temp;

   public Temperature(decimal temperature)
   {
      this.m_Temp = temperature;
   }
   
   public decimal Celsius
   {
      get { return this.m_Temp; }
   }
   
   public decimal Kelvin
   {
      get { return this.m_Temp + 273.15m; }   
   }
   
   public decimal Fahrenheit
   {
      get { return Math.Round((decimal) this.m_Temp * 9 / 5 + 32, 2); }
   }

   public override string ToString()
   {
      return this.ToString("G", null);
   }
   
   public string ToString(string format)
   {
      return this.ToString(format, null);
   }
   
   public string ToString(string format, IFormatProvider provider)  
   {
      // Handle null or empty arguments.
      if (String.IsNullOrEmpty(format))
         format = "G";
      // Remove any white space and covert to uppercase.
      format = format.Trim().ToUpperInvariant();

      if (provider == null)
         provider = NumberFormatInfo.CurrentInfo;
            
      switch (format)
      {
         // Convert temperature to Fahrenheit and return string.
         case "F":
            return this.Fahrenheit.ToString("N2", provider) + "°F";
         // Convert temperature to Kelvin and return string.
         case "K":
            return this.Kelvin.ToString("N2", provider) + "K";
         // Return temperature in Celsius.
         case "C":
         case "G":
            return this.Celsius.ToString("N2", provider) + "°C";
         default:
            throw new FormatException(String.Format("The '{0}' format string is not supported.", format));
      }      
   }
}
```

**Comment by nblumhardt** [comment]
Looks like this may be a bug; would be great if someone has a chance to dig in deeper. Thanks @AroglDarthu :+1:

**Comment by SimonTouchtech** [comment]
I looked into this and believe I have a fix in #1434. Note that for the example given above the output would still not be exactly the same for all versions, as the string will not be quoted, i.e.

Output with #1434:
```
// [INF] MessageTemplate : 285.15K
// [INF] String.Format   : "285,15K"
// [INF] ToString(format): "285,15K"
// [INF] Interpolation   : "285,15K"
```

**Comment by SimonTouchtech** [comment]
Unfortunately my PR did not work, as it wasn't thread safe. I am unable to see any way to solve it in a thread safe way so I have now closed the PR. 

If you happen to know that your custom implementation of `IFormattable` is thread safe (which `Temperature` is afaict) and you for some reason need to use the message template approach instead of the other ones listed by @AroglDarthu (`string.Format`, `ToString(format)`, interpolation) you can do the following workaround:

```csharp
var logger = new LoggerConfiguration()
    .Destructure.AsScalar<Temperature>() // Added
    .WriteTo.Console(outputTemplate: "{Timestamp:HH:mm} [{Level:u3}] {Message}{NewLine}")
    .CreateLogger();
```

That will essentially have the same result as my PR had (so it won't be in quotes), but I did it for all `IFormattable` implementations without considering the thread safety of the implementation.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, @SimonTouchtech .

I think, currently, `Destructure.AsScalar()` is the right way to address this one 👍
