### ISSUE TITLE
Forcing float values to output with decimal places

### ISSUE THREAD

**Issue by dcyoung** [serilog/serilog#1397]
We are encountering issues with dynamic type parsing in our ELK stack because some float values such as 1.0 or 0.0 are being interpreted as ints. 

For example...
```csharp
Log.ForContext("FloatVal", 1.1f)
    .ForContext("WholeFloatVal", 1.0f)
    .Information("Test");
```

outputs 

```json

{
    "Timestamp": "2020-02-04T13:23:00.4895730-08:00",
    "Level": "Information",
    "MessageTemplate": "Test",
    "Properties": {
        "FloatVal": 1.1,
        "WholeFloatVal": 1,
    }
}
```

Instead of `WholeFloatVal: 1`, i'd like to output `WholeFloatVal: 1.0`. While the json spec does not specifically require this behavior, it also does not disallow it. Newtonsoft has adopted this behavior as well (https://github.com/JamesNK/Newtonsoft.Json/commit/0319263756212f4a1875cda6534b9b8e1fb53188).

If this is not a suitable change for the default behavior of serilog, is there a way to accomplish this behavior using the existing Serilog?

**Comment by nblumhardt** [comment]
Not against exploring this - https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Json/JsonValueFormatter.cs#L229 (two functions) would be the place to look.

Would need a benchmark over formatting of JSON values, and some thought put into whether this is likely to break anyone relying on the current behavior 👍
