### ISSUE TITLE
Question: multiple loggers?

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog#1399]
I have my own custom class that is injected into all my web services called `IRecorder`. 
It has 4 logical capabilities: Metrics, Tracing, Auditing, CrashReporting. 
* Metrics = counting certain application events (i.e. password attempts, featureA versus featureB, etc)
* Tracing = structured logging (in general)
* Auditing = capturing certain auditable events in the system (i.e. password reset, change permissions, etc)
* CrashReporting = capturing certain failure events in the app.

There is essentially a single instance of this `IRecorder` used for each HTTP request, injected into all the service handling code.

Under the covers the implementation of `IRecorder` uses multiple Serilog `new LoggerConfiguration().CreateLogger()` calls, each using a different set of sinks.

For example, CrashReporting events go onto one Azure queue via a custom sink, Audits go to another Azure queue via another custom sink, all Traces use Serilog.TraceSink(), etc. All custom sinks are wrapped in the `Serilog.Async` sink as well.

So the single instance of `IRecorder` news up 4 different `LoggerConfiguration` instances, and it disposes all of them after the HTTP request has gone. (We do not use nor set the static `Log.Logger` singleton at all)

My question is this.

Is this design prone to memory leaks with the current design of Serilog?

I ask this because over the years I've seen comments related to memory leaks and uses/misuses of `LoggerConfiguration`, even comments saying it should be a singleton.
I just want to learn if this design may need review/reworking.

**Comment by nblumhardt** [comment]
Hi Jezz, thanks for the note.

As far as we're aware, these won't (shouldn't - it would be a bug) leak in any way.

However, many of the sinks allocate heavyweight resources like timers, threads, and so on, which aren't always cheap to allocate or quick to clean up.

I'd personally recommend refactoring towards a long-running set of loggers for each of the targets, with `ForContext()` used to set up additional enrichment per HTTP request.

_Serilog.Sinks.Map_ can also help if the sinks need to be customized on a per request basis.

HTH!

**Comment by jezzsantos** [comment]
Hey @nblumhardt, thanks for the guidance, and affirmation.

I'm quite keen to learn about what you alluding to with "long-running set of loggers for each of the targets".

Can you guide me any more on what you are thinking about there?
Ill check out `Serilog.Sinks.Map` since each request has different data connections to use for each request.

**Comment by jezzsantos** [comment]
Flag that @nblumhardt I think I know what you mean. I get back if any issues

**Comment by nblumhardt** [comment]
Great, thanks Jezz 👍

**Comment by LyubomirStoimchev** [comment]
Hi guys, I have a question that is kind of related to the thread. How can I have multiple loggers(or sinks) that store the logs only for the specific thread.

I was thinking of creating a separate logger for each thread, but as far as I saw the serilog is static and thus cannot be instantiated.

Another thing that I was thinking is using a sink like TextWriter and enrich the log with the thread id. But how can I get the results only for that thread?

Any help is appreciated!
