### ISSUE TITLE
New Feature: RenderedJsonFormatter 

### ISSUE THREAD

**Issue by Everwig** [serilog/serilog#1401]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.9.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [X] netCore 1.0
- [X] 4.7
- [X] 4.6.x
- [X] 4.5.x

**Please describe the current behaviour?**
Missing but mentioned RenderedJsonFormatter type in the https://github.com/serilog/serilog-formatting-compact

**Please describe the expected behaviour?**
Implemented RenderedJsonFormatter based on the RenderedCompactJsonFormatter type, but without the shortened property names

**Comment by nblumhardt** [comment]
Thanks for the note. In the linked readme, `RenderedJsonFormatter` is a benchmark name, not a type name. I've updated the readme to fix this.

We already support this through `new JsonFormatter(renderMessage: true)`; the format used by `JsonFormatter` is heading towards "legacy" so we will probably not make this change.

Thanks again, though - appreciate your input 👍

**Comment by Everwig** [comment]
Thank you for pointing it out, I didn't know. 😄 

Can you please tell me how to enable it from appsettings?
Because locally I'd like to use the humanly readable unrendered format, but when we send it to a repository, like Splunk, I'd rather do it in a rendered format.

**Comment by Everwig** [comment]
Nevermind, got it, but leaving it here, for future references:

`"Serilog": {
    "MinimumLevel": "Debug",
    "Enrich": [ "FromLogContext" ],
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "renderMessage": true
        }
      }
    ]
  }`

**Comment by pawan-regoti** [comment]
This worked for me. 
```
"Serilog": {
	"Using": [ "Serilog.Sinks.Console" ],
	"MinimumLevel": {
		"Default": "Information",
	},
	"Enrich": [ "FromLogContext" ],
	"WriteTo": [
		{
			"Name": "Console",
			"Args": {
				"formatter": {
					"type": "Serilog.Formatting.Json.JsonFormatter, Serilog",
					"renderMessage": true
				}
			}
		}
	],
	"Properties": {
		"Application": "YourApplication"
	}
}
```
