### ISSUE TITLE
UseSerilog() breaks Visual Studio Code's "ServerReadyAction"

### ISSUE THREAD

**Issue by mjnorman** [serilog/serilog#1408]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
3.2.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
None specific

- [x] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
When utilizing `UseSerilog()` in Program.cs to override logging, VS Code's "ServerReadyAction" which watches output for a specific pattern then launches the browser, ceases to function.  You can simply comment this line out to go back to Microsoft default logging, and that feature works as expected.

**Please describe the expected behavior?**
VS Code should still function as normal when Serilog is overriding the Logging pipeline.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

1. dotnet new mvc
2. add serilog.aspnetcore package
3. set up Program.cs as described [here](https://nblumhardt.com/2019/10/serilog-in-aspnetcore-3/)
```c#
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .CreateLogger();
...
        Host.CreateDefaultBuilder(args)
            .UseSerilog() // <- Add this line
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
```
4. launch vscode and start debug  (default launch.json includes the below config:)
```json            
          "serverReadyAction": {
                "action": "openExternally",
                "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"                
            }
```
5. See that browser does not launch

To bypass the issue simply comment out `UseSerilog()` in Program.cs and relaunch debug session and see that the browser does launch.

**Comment by nblumhardt** [comment]
Thanks for the report, @mjnorman. Unfortunately there's not much we can do about this except perhaps lobby for the default pattern to be changed to something more permissive.

There's an earlier discussion in https://github.com/serilog/serilog-aspnetcore/issues/139 and an open ticket on https://github.com/serilog/serilog-sinks-console/issues/83 - closing as duplicate.

**Comment by freiguy1** [comment]
I also ran into this. Sort of patched it up by having serilog write to the console (`.WriteTo.Console()`) and then slightly modified the `serverReadyAction`'s pattern: `"pattern": "\\s*Now listening on:\\s+(https?://\\S+)"`

**Comment by MephistoNp** [comment]
@freiguy1  any luck with serverReadyAction's pattern for .net 5?

**Comment by TheNetStriker** [comment]
I think I found a good solution for this. I've added the Serilog.Sinks.Debug library and configured it so that serilog also logs to the debug output. Now my browser is starting again.
