### ISSUE TITLE
Please add new entries to community projects list

### ISSUE THREAD

**Issue by akovac35** [serilog/serilog#1415]
This issue is intended for [community projects](https://github.com/serilog/serilog/wiki/Community-Projects).

Please add the following lines to the list:

`| <img src="https://github.com/akovac35/Logging/raw/master/Resources/.NET_Core_Logo_small.png" width="100px"> | [Logging](https://github.com/akovac35/Logging) | Helpful resources for .NET Core and ASP.NET Core logging using various logger frameworks. |`

`| <img src="https://github.com/akovac35/Logging.Samples/raw/master/Resources/.NET_Core_Logo_small.png" width="100px"> | [Logging.Samples](https://github.com/akovac35/Logging.Samples) | Logging.Samples demonstrate how to use Serilog for .NET Core and ASP.NET Core logging. Samples are provided for console, test, web api, web app and entity framework core configurations.|`

**Comment by nblumhardt** [comment]
Thanks for getting in touch!

At the moment, we're keeping the "projects" page to extensions/integrations, rather than learning materials, because this would greatly expand the scope of what would be listed (there's a huge amount of content out there, so it's a bit much for us to keep up with).

Best regards,
Nick

**Comment by akovac35** [comment]
Hi,

in that case, please remove the second entry and only add the first one, a Library project using Serilog.

Thanks and regards,
Aleksander

**Comment by nblumhardt** [comment]
Hi, thanks for the follow-up.

> This library contains helpful resources for .NET Core and ASP.NET Core logging using various logger frameworks and Microsoft.Extensions.Logging.ILogger interface.

I think as the project is focused on MEL and not Serilog, it's out-of-scope for the Serilog community page right now, but, best of luck with the project!
