### ISSUE TITLE
Serilog logging the logs in different timezone for two different services with same sink configuration

### ISSUE THREAD

**Issue by sukhdev1103** [serilog/serilog#1416]
"Serilog.Sinks.Console" Version="3.1.1"
"Serilog.Sinks.File" Version="4.1.0"
Target Framework - netcoreapp3.1

[Bug]
I saw a weird behavior which is I have two services and both services are using Serilog and both are using the same output template for configuring the sink.

For e.g. private const string OutputTemplate = "{Timestamp:O} [{ProcessName}({ProcessId}):{ThreadId}:

But, one service is logging the logs in the local time zone and the other is logging in UTC timezone.
Again, they are using the same output template.

Expected behavior - Both services should log in the same time zone ISO.

**Comment by nblumhardt** [comment]
Hi! Serilog will write to the console using whatever is the local time zone on the machine running the service. If you want UTC output, the most convenient way to consume that is via the _Serilog.Formatting.Compact_ JSON format and a suitable destination, but there are some other discussions out there with information on using UTC output if that's desired (let me know if you have trouble finding these). HTH!

**Comment by sukhdev1103** [comment]
Thank you,
I am having a hard timing finding those, could you please point to the right discussion?

**Comment by nblumhardt** [comment]
No worries - https://github.com/serilog/serilog/issues/1024#issuecomment-338518695 should cover it
