### ISSUE TITLE
Question: Detecting LoggingLevelSwitch just happened

### ISSUE THREAD

**Issue by janzakrzewskipl** [serilog/serilog#1417]
Hi,

Is there a way to know/react that something just changed LoggingLevelSwitch?

**Context:**
From time to time on Production we have some weird issues and because of that we would like to change log level at runtime. In particular we would like to lower log level to Debug or Verbose to get as much info as we can. Thanks to LevelSwitches it is possible, but we would like something more. We would like to lower "Microsoft" logs to Debug or Verbose as well. Currently it is not possible because we override "Microsoft" logs to Warning, because on Info level it produces to much logs that we usually don't need.

So our idea was that if we could somehow detect that we changed LevelSwitch to Debug, then we could try to override log level for "Microsoft" as well. Is there some event to react to? Or maybe delegate to register for that? If not, maybe you could advise how to approach it in different manner?

My config is more or less like following:

```
  "Serilog": {
    "LevelSwitches": { "$controlSwitch": "Information" },
    "MinimumLevel": {
      "ControlledBy": "$controlSwitch",
      "Override": {
        "Microsoft": "Warning"
      }
    },
    "WriteTo": {
      "Seq": {
        "Name": "Seq",
        "Args": {
          "serverUrl": "url",
          "apiKey": "xxx",
          "controlLevelSwitch": "$controlSwitch"
        }
      }
    },
  }
```

As you see we change log level via SEQ's MinimumLevel property associated with given ApiKey.

Thanks!

**Comment by nblumhardt** [comment]
Hi; no, this isn't possible given the current API and implementation. Configuring the level switch in code, and monitoring its value on a timer, should work but might be a bit cumbersome in practice.

**Comment by janzakrzewskipl** [comment]
Works. Thanks for tip.
