### ISSUE TITLE
Sensitive data masking

### ISSUE THREAD

**Issue by sandermvanvliet** [serilog/serilog#1421]
Not a bug but a request for an addition to the Serilog wiki.

I have created an enricher for Serilog that has the capability to mask sensitive data from log event properties: [Serilog.Enrichers.Sensitive](https://github.com/sandermvanvliet/Serilog.Enrichers.Sensitive)

I would very much appreciate feedback from the official side of things is this would be a useful addition. Some feedback can be found on [this reddit](https://www.reddit.com/r/dotnet/comments/fbc828/sensitive_data_masking_for_serilog/) thread.

I found some older issue #1138 that talks about this but that's from 2018 or so

**Comment by nblumhardt** [comment]
Listed! https://github.com/serilog/serilog/wiki/Community-Projects - thanks 👍
