### ISSUE TITLE
when serilog is writing the log into file,i cant open that file 

### ISSUE THREAD

**Issue by hangyejiadao** [serilog/serilog#1423]
this is my code, who can tell me how to set the serilog 
 

`    
       Log.Logger = new LoggerConfiguration() 
                .MinimumLevel.Debug() 
                .MinimumLevel.Information() 
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                 // .WriteTo.Async(c => c.File("Logs/logs.txt")) 
                .WriteTo.Logger(lg => lg.Filter.ByIncludingOnly(p => p.Level == LogEventLevel.Debug).WriteTo.File(LogFilePath("Debug"), rollingInterval: RollingInterval.Day, outputTemplate: SerilogOutputTemplate))
                .WriteTo.Logger(lg => lg.Filter.ByIncludingOnly(p => p.Level == LogEventLevel.Information).WriteTo.File(LogFilePath("Information"), rollingInterval: RollingInterval.Day, outputTemplate: SerilogOutputTemplate))
                .WriteTo.Logger(lg => lg.Filter.ByIncludingOnly(p => p.Level == LogEventLevel.Warning).WriteTo.File(LogFilePath("Warning"), rollingInterval: RollingInterval.Day, outputTemplate: SerilogOutputTemplate))
                .WriteTo.Logger(lg => lg.Filter.ByIncludingOnly(p => p.Level == LogEventLevel.Error).WriteTo.File(LogFilePath("Error"), rollingInterval: RollingInterval.Day, outputTemplate: SerilogOutputTemplate))
                .WriteTo.Logger(lg => lg.Filter.ByIncludingOnly(p => p.Level == LogEventLevel.Fatal).WriteTo.File(LogFilePath("Fatal"), rollingInterval: RollingInterval.Day, outputTemplate: SerilogOutputTemplate)) 
                .CreateLogger();`

**Comment by hangyejiadao** [comment]
![微信图片_20200424112938](https://user-images.githubusercontent.com/16451639/80174399-21f77980-8625-11ea-95a1-64433bfb4cca.png)

**Comment by bartelink** [comment]
These sorts of questions are far better asked on stackoverflow.com - way more traffic, and quicker responses (be sure to a) format the wireup code correctly in the question b) include the text of the exception and c) specify what it is that you expect to happen, as it's not obvious (at least to me!)).
Feel free to post a link to your question here in case someone happens to find this in the future

**Comment by hangyejiadao** [comment]
@bartelink  ok sir ,i just wanna open that file that the serilog is writing the log into when i am debugging

**Comment by bartelink** [comment]
I often use Visual Studio Code in the background to view the log file - the log writer will attempt to open the file in Write mode, and the Operating System will prevent more than one thing from doing that; this is likely part of your problem. I hope you got sorted.

**Comment by hangyejiadao** [comment]
ok sir,when the serilog is writting the log into txt  file,i wanna delete this file or open this file in  visual studio ,what should i do?

**Comment by bartelink** [comment]
You can't delete a file that's been locked for writing. There may be a way to tell the File sink not to hold the file open (please DO NOT ENGAGE ME IN CHAT HERE REGARDING THAT!). It's possible that VS has a Read Only mode that will work even if the file is locked. Visual Studio WILL work. And I will now Work too. Again: Stackoverlow.com please.

**Comment by rafaelsc** [comment]
I think this is the best place to discuss this is in https://github.com/serilog/serilog-sinks-file repository not in the Serilog Core repository.
_I will reply there._

**Comment by nblumhardt** [comment]
Closing as duplicate
