### ISSUE TITLE
A bad designed Class can cause an Exception when using Stringify

### ISSUE THREAD

**Issue by rafaelsc** [serilog/serilog#1426]
**Description**
A bad designed Class can cause an Exception when logging with stringification operator.

**Reproduction**
Log using stringification operator with a instance of a class that can return null in ToString().

```csharp
        class ABadBehavior
        {
            public override string ToString() => null;
        }
        Log.Information("{$Data}", new ABadBehavior());
```

**Expected behavior**
That the Serilog Core doesn't throw an exception. And Log the result like was another null property

**Relevant package, tooling and runtime versions**
All runtimes and using the lastest Serilog codebase.

**Additional context**
I find this issue when implementing the C#8 Nullable Reference Type in Serilog codebase.

**Comment by nblumhardt** [comment]
Excellent - thanks!
