### ISSUE TITLE
Wiki Datadog Log link incorrect

### ISSUE THREAD

**Issue by chase-swanson** [serilog/serilog#1428]
I wanted to do a PR for this as it is simple, but the Wiki does not allow that on GitHub

**Description**
The link on the Available Sinks page for DataDog Logs is incorrect.

Link to repo should be I believe

`[DataDog Logs](https://github.com/DataDog/serilog-sinks-datadog-logs)`

**Comment by nblumhardt** [comment]
Fixed - thanks!
