### ISSUE TITLE
Per Request Minimum Log Level

### ISSUE THREAD

**Issue by ali-tayebi** [serilog/serilog#1432]
**Is your feature request related to a problem? Please describe.**
Troubleshooting application behaviour in production environments quite often limits our tool belt to a minimum. Cloud-native, DevOps and modern application such as microservice are even harder to track and debug. Having a chance to change logging behaviour remotely can be very beneficial for the team running services on production. No one likes finding a noodle in a haystack. Also, distributed log aggregator solutions are costly. So, it is importance to have a smarter control of the minimum log level

**Describe the solution you'd like**
Setting up the minimum log level per Http request based on a given Http header value

**Describe alternatives you've considered**
[Log4J](https://www.innoq.com/en/blog/per-request-debugging-with-log4j2/) does that

**Additional context**
Not as this stage but happy to provide more details if required

**Comment by skomis-mm** [comment]
Hi @ali-tayebi ,

Take a look at [this](https://github.com/serilog/serilog/issues/1078#issuecomment-356453248) gist. In combination with custom middleware that monitor for a custom http header and open scope for that request should solve your task.

**Comment by ali-tayebi** [comment]
Hi @skomis-mm 
Thank you for your comment. I pretty like that solution. I will give it a go
