### ISSUE TITLE
Update docs regarding LoggerMinimumLevelConfiguration.Override()

### ISSUE THREAD

**Issue by JakenVeina** [serilog/serilog#1444]
Referring to https://github.com/serilog/serilog/pull/1033...

The XML docs for this method should specify that this is intended behavior (that it is ignored when configuring sub-loggers). A message in a log that is meant for debugging, and is opt-in, is not sufficient to provide discoverability for this behavior.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, makes sense 👍 

We can take a look at this, but if you're keen to send a PR, that would also be welcome.

**Comment by JakenVeina** [comment]
Was already planning on it. ;)
