### ISSUE TITLE
An ability to dispose nested loggers

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog#1447]
**Is your feature request related to a problem? Please describe.**
I have a quite complex logging pipeline having at least two levels of nesting via `configuration.WriteTo.Logger(nestedLogger)`. The problem is, I can't dispose all of it in one go, because nested loggers are _not_ disposed when parent logger is.

**Describe the solution you'd like**
I would like to be able to specify that I want nested logger to be disposed with the pipeline, i.e.:
```
configuration.WriteTo.Logger(nestedLogger, dispose: true)
```
This can be easily accomplished by passing the flag down to `SecondaryLoggerSink`.

**Describe alternatives you've considered**
- `WriteTo.Logger(Action<LoggerConfiguration>)` which creates logger internally and disposes of it.
  I was able to replace only on of my usages with this one, because in other cases the logger is already created.
- `WriteTo.Sink(logger)` (using the fact that `Serilog.Core.Logger` is actually a `ILogEventSink`).
  This way the events pushed to logger are not copied so they can (and will be, in my case) modified by nested logger's enrichment. Also, feels hack-ish and requires access to `Logger` instead of `ILogger`.
- `WriteTo.Logger(lc => lc.WriteTo.Sink(logger))`.
  This, probably, will work (and I might settle for this in a short-term), but, same as above, requires access to `Logger` and feels even more hack-ish.

BTW, I'd add a simple overload in my own code, but both `SecondaryLoggerSink` and `LogEvent.Copy` are `internal`.

**Comment by srogovtsev** [comment]
I think I can take this one myself, but I'd like to get an approval for the approach beforehand.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, will need to loop back around and give it some thought :+1:

**Comment by nblumhardt** [comment]
I think the approach is sound; if anyone's interested in picking this up please jump in, otherwise given the lack of activity this should probably be closed as stale now.

**Comment by srogovtsev** [comment]
I'll give it a try around the week end.
