### ISSUE TITLE
Lightweight JSON file configuration solution

### ISSUE THREAD

**Issue by TysonMN** [serilog/serilog#1450]
**Problem description**
I like configuring Serilog from a JSON file.  I currently achieve this via [serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration).  However, I am not thrilled with how many dependencies it requires.  In addition to `Serilog.dll`, `Serilog.Settings.Configuration.dll`, and `Newtonsoft.Json.dll`, there 14 DLLs from Microsoft, including `Microsoft.Extensions.Configuration.Json.dll` (when targeting .NET Core 3.1).

This seems like a lot of dependencies to me.

**Potential solution**
Is there a more lightweight solution to configuring Serilog from a JSON file?  Does anyone else feel like I do that the standard solution to this problem has too many dependencies?

**Alternative solutions**
I found `Serilog.Settings.Json` (on [GitHub](https://github.com/morphey83/Serilog.Settings.Json) / [NuGet.org](https://www.nuget.org/packages/Serilog.Settings.Json)), but I didn't try it since I am not willing to take on a such an immature dependency.

**Comment by KamranShahid** [comment]
exactly same here. i am using log4net in my asp.net core 3.1 application which have rolling fille appender and couple of separate adonet file appender which i am planning to  migrate to serilog. in my asp.net core i am using System.Text.json builtin json serilizer for everyting

**Comment by nblumhardt** [comment]
No changes planned here - checking out the existing impl seems like a worthwhile endeavour.
