### ISSUE TITLE
MinimumLevel:Override does not work when MinimumLevel.Default has higher restriction level.

### ISSUE THREAD

**Issue by dfrunet** [serilog/serilog#1453]
**Description**
MinimumLevel.Override works only when increasing the restriction level comparing to MinimumLevel.Default and does not work when Override value is less than the Default.

**Reproduction**
Setting `"MinimumLevel": { "Default": "Warning", "Override": {"Foo": "Error", "Foo.Bar": "Information"}}`, output level is `Error` for the `Foo` namespace and `Warning` for all the rest, including `Foo.Bar` (override does not have effect).

**Expected behavior**
Setting `"MinimumLevel": { "Default": "Warning", "Override": {"Foo.Bar": "Information"}}`, output level is `Information` for the `Foo.Bar` namespace only and `Warning` for all the rest.

**Relevant package, tooling and runtime versions**
Serilog (2.8.0)
Serilog.Extensions.Logging (3.0.1)
Serilog.Settings.Configuration (3.1.0)

Finally [realized](#issuecomment-653955010) that the main configuration is not supposed to be fully applied to subloggers, registered like:
```cs
.WriteTo.Logger(lc =>
                    {
                        lc
                          // the next line is the reason to use the sublogger, 
                          // but it's not relevant for the bug, thus commented out
                          //.Filter.ByIncludingOnly(evt => evt.Level < LogEventLevel.Warning)
                           .WriteTo.Console(theme: AnsiConsoleTheme.Code,
                                outputTemplate: "[{Timestamp:HH:mm:ss.fff}][{Level}]: {Message}{NewLine}");
                    });     
``` 
and that's by design.

**Comment by skomis-mm** [comment]
Hi @dfrunet ,

Could not reproduce this..can you make a minimal repro project? Thanks!

**Comment by dfrunet** [comment]
@skomis-mm thank you for the answer, will create the repo in a day or two.

**Comment by dfrunet** [comment]
Now it seems that I have to say sorry and close the item. I started with a minimal repo and was unable to reproduce the issue too, and then when I went back to my work project and started playing with the settings, the problem disappeared there too. I'll play there a bit more, but for now I see no problem at all.

**Comment by dfrunet** [comment]
@skomis-mm Finally I found the way to reproduce the issue. When started to play with different configurations I used json output for simplicity and everything worked fine. But in real project I have to use flat formatting with several format switches. It looks like:

```
LoggerConfiguration loggerConfiguration = new LoggerConfiguration().ReadFrom
    .Configuration((IConfiguration) config, (DependencyContext) null).Enrich.FromLogContext();
loggerConfiguration
    //next two lines works fine when uncomment
    //.WriteTo.Console(theme: AnsiConsoleTheme.Code,
    //                            outputTemplate: "[{Timestamp:HH:mm:ss.fff}][{Level}]: {Message}{NewLine}");
    //and the following leads to to the problem I explained initially
   .WriteTo.Logger(lc =>
                    {
                        lc
                          //we  cover all possible levels with different filters. it does not cause the issue: 
                          //when commented, the problem is still there
                          //.Filter.ByIncludingOnly(evt => evt.Level < LogEventLevel.Warning)
                           .WriteTo.Console(theme: AnsiConsoleTheme.Code,
                                outputTemplate: "[{Timestamp:HH:mm:ss.fff}][{Level}]: {Message}{NewLine}");
                    });      
```

**Comment by skomis-mm** [comment]
@dfrunet I think you hit the limitation that level overrides with subloggers are [not supported](https://github.com/serilog/serilog/pull/1445/files). Also see [this](https://github.com/serilog/serilog/pull/1033) and linked discussions.

For the sublogger you can only restrict with minimum level for all contexts by passing desired level to `restrictedToMinimumLevel` parameter.

**Comment by dfrunet** [comment]
@skomis-mm so according to the updated docs the overrides are not supposed to work with filtering at all? In fact they do(!), but as I explained, in the only direction (to more restricted level). Strange that this major bug (one major feature restricts another major feature) is kept for years without any intention to fix it. I do not think having overrides configurable for each particular sublogger separately is relevant, but having the (whole) main configuration properly applied to each (sub or not) logger is a must.

In my particular case I think getting rid of that hardcoded filters (and later -- flat formatting) would the best workaround.

**Comment by skomis-mm** [comment]
@dfrunet , seems you are right. The limitation on overrides mentioned above is about this:
```csharp
.WriteTo.Logger(lc =>
 {
    lc.MinimumLevel.Overrides(...) ; // not supported
});     
```
But your example is about different issue - why root log events that where passed on main logger (because of overrides) are skipped on sublogger - seems unintuitive. 

The root cause of this is _inherited default logging level_ of the parent (`Warning`), so with you example its essentially translates to:
```csharp
    var logger = new LoggerConfiguration()
        .MinimumLevel.Warning()
        .MinimumLevel.Override(...) // does not matter
        .WriteTo.Logger(
            lc => lc.MinimumLevel.Warning() // the same as for the parent
                    .WriteTo.Console(...))
        .CreateLogger();
``` 

[Inheritance](https://github.com/serilog/serilog/pull/654) of the parent level was introduced before overrides feature, so it was consistent. But I wonder if it could be just `LevelAlias.Minimum` by default for all subloggers configurations created with delegate as for the `restrictedMinimumLevel` parameter?
@nblumhardt is there some missing context/gotchas?

The current workaround is to specify `Verbose` as default minium level for the sublogger:
```csharp
.WriteTo.Logger(
      lc => lc.MinimumLevel.Verbose()
         .WriteTo.Console(...))
```

**Comment by dfrunet** [comment]
The current workaround seems to work fine! @skomis-mm thanks a lot!

**Comment by nblumhardt** [comment]
Duplicate of #1472
