### ISSUE TITLE
Add support C# 8 nullable reference types

### ISSUE THREAD

**Issue by rafaelsc** [serilog/serilog#1455]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Enable [nullable-references](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in Serilog and add update the codebase to support the nullable reference types in .NET Core 3.0 and 3.1.

**Additional context**
Links about the *Nullable reference types*:
 - [Nullable reference types (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
 - [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
 - [Introducing Nullable Reference Types in C#](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/)

**Comment by SimonCropp** [comment]
@nblumhardt close?
