### ISSUE TITLE
Config file auto find 

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog#1461]
**Is your feature request related to a problem? Please describe.**
auto search for config file

**Describe the solution you'd like**
something like this
https://github.com/NLog/NLog/wiki/Configuration-file#configuration-file-locations

**Comment by nblumhardt** [comment]
Thanks for the suggestion. Currently we're unlikely to pursue this, as the Microsoft.Extensions.Configuration system covers similar functionality and we'd rather lean on it, when possible.
