### ISSUE TITLE
Throw exception when no config was specified

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog#1462]
**Is your feature request related to a problem? Please describe.**
null check for setting is not enough, it could be an empty list
https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerSettingsConfiguration.cs#L55
```C#
   if (settings == null) throw new ArgumentNullException(nameof(settings));
```

**Describe the solution you'd like**
```C#
   if (settings == null)
            {
                throw new ArgumentNullException(nameof(settings));
            }

            var keyValuePairs = settings.ToList();
            if (!keyValuePairs.Any())
            {
                throw new ArgumentException($"{nameof(settings)} should not be empty.");
            }
```

**Comment by nblumhardt** [comment]
Hi Chuck, thanks for the note!

In this case an empty list is fine - it just means "the logger doesn't write events anywhere", which is a valid configuration in some scenarios.

All the best,
Nick

**Comment by chucklu** [comment]
@nblumhardt  What if someone forget to do the configuration, and he wants to write log.

**Comment by nblumhardt** [comment]
We need to choose one option or the other, unfortunately, so we'll stick with the current behavior. Thanks!
