### ISSUE TITLE
LoggerSinkConfiguration.Wrap() fails to dispose wrapped sinks in some scenarios

### ISSUE THREAD

**Issue by JanEggers** [serilog/serilog#1463]
**Description**
When using async sinks with multiple sinks dispose does not work.
The async sink tries to dispose its childs but the child is a SafeAggregateSink that is not disposable and therefore breaking the cleanup. as SafeAggregateSink is part of the core I opened the bug here.

**Reproduction**

```csharp
var logger = new Configuration().WriteTo.Async(a => a.WriteTo.File("test.log").WriteTo.Console()).CreateLogger();
logger.Dispose();

 logger = new Configuration().WriteTo.Async(a => a.WriteTo.File("test.log")).CreateLogger();  // throws file in use exception
```

**Expected behavior**
the first logger should be disposed correctly

**Relevant package, tooling and runtime versions**
serilog.core

**Comment by nblumhardt** [comment]
Thanks, Jan! Will need some careful analysis as I think internally, where Serilog uses this type, it doesn't necessarily own the sinks that it aggregates. May be that `Wrap()` should return a different (disposable) type 🤔
