### ISSUE TITLE
Resolving a typed HttpClient in UseSerilog causes a circular execution path

### ISSUE THREAD

**Issue by EnquiringStone** [serilog/serilog#1469]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
When registering a typed HttpClient using the AddHttpClient extension method, resolving the service leads somehow to an circular execution path in the UseSerilog(HostBuilder, IServiceProvider, LoggerConfiguration) method. Meaning that Sinks using a typed HTTP client in their constructor are unable to be used.

For more information on typed HttpClients see:

[https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Reproduction**
Create a new .NET Core 3.1 WebApi Project

Include the latest release of Serilog.AspNetCore (my example uses 3.4.0)

Create an interface called IHttpClientService
`public interface IHttpClientService { }`

Create an implementation of the interface
`public class HttpClientService : IHttpClientService`
`{ public HttpClientService(HttpClient client) { } }`

Register the HttpClient in the ConfigureServices in the Startup.cs
`services.AddHttpClient<IHttpClientService, HttpClientService>();`

Add a custom sink using the typed HttpClient
`public class CustomSink : ILogEventSink {`
`public CustomSink(IHttpClientService service) { }`
`public void Emit(LogEvent logEvent) { throw new NotImplementedException(); }`
`}`

Add an extension method of initializing the custom sink to make your life a bit easier
`public static LoggerConfiguration CustomSink (this LoggerSinkConfiguration loggerConfiguration, IHttpClientService service)`
`{ return loggerConfiguration.Sink(new CustomSink(service)); }`

Add the inline initialization of Serilog in the Program.cs
`.UseSerilog((hostBuilder, services, config) => config.ReadFrom(hostBuilder.Configuration).Enrich.FromLogContext().WriteTo.CustomSink(services.GetRequiredService<IHttpClientService>()));`

Start the application. You will see an never ending loading page in your browser

The problem occurs in `services.GetRequiredService<IHttpClientService>()`
When debugging through it, it steps into the configuration lambda of the UseSerilog over and over.
When configuring the service as a Singleton and removing the HttpClient from the constructor of IHttpClientService it works as excpected.

So why is the configuration lambda of the UseSerilog being called recursively when resolving a typed HttpClient?

**Expected behavior**
The typed HttpClient gets resolved and passed in as parameter to the custom sink.

**Relevant package, tooling and runtime versions**
.NET Core 3.1
Serilog.AspNetCore 3.4.0
Google Chrome (latest version)

**Additional context**
This might be an issue in .NET Core itself. However I had some problems trying to reproduce that issue without Serilog. So for now I think it's an issue specific to Serilog. It would be nice if you guys could look at this further.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. This is somewhat expected - resolving any component from the `IServiceProvider` that itself depends on logging will cause this failure (circular dependency).

It's not something specific to Serilog that we can fix, unfortunately - turning to your DI container configuration might offer some alternatives/possibilities. HTH!
