### ISSUE TITLE
Get original property value type from ILogEventPropertyFactory

### ISSUE THREAD

**Issue by tzographos** [serilog/serilog#1474]
Hello, I asked this [question ](https://stackoverflow.com/questions/63161623/get-original-property-value-type-from-ilogeventpropertyfactory )on StackOverflow but with no luck. 
Therefore I am asking the same here, hoping to receive an answer.

I'm writing the simplest of enrichers: find all properties ```XProperty``` that have enum value types and add another property named ```XPropertyString``` which is the string representation of the ```Enum``` value. 

I started with something like this:
```
  public class EnumStringEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            foreach(var p in logEvent.Properties)
            {
                Type t = p.Value?.GetType();
                if (t != null && t.IsEnum)
                {
                    //create property <enum_property>String with Enum description as value
                    LogEventProperty enumString = propertyFactory.CreateProperty($"{p.Key}String", Enum.GetName(t, p.Value));
                    logEvent.AddPropertyIfAbsent(enumString);
                }
            }
        }
    }
```
It seems that property values are "wrapped-in" Serilog's types ```Serilog.Events.ScalarValue```, ```Serilog.Events.SequenceValue``` etc.
Is there any way to get the underlying property value type in the above example?

Thanks

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. The SO question is still the best place to get help, I'll zip over there and take a look.
