### ISSUE TITLE
Not support property name contains dash(-) in ForContext

### ISSUE THREAD

**Issue by idubnori** [serilog/serilog#1479]
**Description**
if the property name contains dash(-) in `ForContext`, can not output it using `outputTemplate`

**Reproduction**
1. Set `.ForContext("fo-DICOM", "Foo");`
2. Configure `"outputTemplate": "{fo-DICOM} {Properties} {NewLine}"` on `appsettings.json`
3. The output would be `{fo-DICOM} {fo-DICOM="Foo"}`

* if remove dash(-) in property name, output would be `Foo {}`

**Expected behavior**
I think the output should be `Foo {fo-DICOM="Foo"}`, if the following does not change with the latest version.
Or, fix the Wiki documentation.

> While accepted by Serilog, dashed-names are not compatible with many back-end data stores and so are strongly discouraged.

References
- [Writing Log Events · serilog/serilog Wiki](https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-recommendations)
- #642 
- #944

**Relevant package, tooling and runtime versions**
```
<TargetFramework>netcoreapp3.1</TargetFramework>

<PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

**Additional context**
> ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

I could not identify which package is related to this.

**Comment by nblumhardt** [comment]
Thanks @idubnori - I've removed the confusing line from the wiki.

Dashed names are not accepted in message templates; they _are_ accepted in `ForContext()` but really only because it's too expensive to parse/validate property names every time `ForContext()` or `PushProperty()` is called.

As the note was suggesting, they're not compatible with most Serilog infrastructure, including output templates, which use the same message template syntax.

Wiki is fixed; closing as by-design. Thanks!

**Comment by idubnori** [comment]
@nblumhardt Thank you for the quick!

Can we clarify the prohibited character list that cannot be used in property names for methods such as:

> ForContext()
PushProperty()
Enrich.WithProperty(), LogFromContext, and so on...

**Comment by nblumhardt** [comment]
Hi @idubnori thanks for the reply.

There are no prohibited characters in the arguments to any of those functions; the limitation you've hit is one of message templates, of which output templates are an example.

Serilog events can have properties with any name, but message templates don't have syntax for describing them, and thus they can't be output using that mechanism.

The syntax for names in message templates (in the linked spec) is best to use wherever possible.

HTH!
