### ISSUE TITLE
BeginScope contextual information enricher (for per-thread scoping)

### ISSUE THREAD

**Issue by apenni** [serilog/serilog#1480]
I had a need to add scoped information and the BeginScope provided by Microsoft extensions does not appear to do what  want; it sets a _global_ scope, where I want a scope for the executing context (e.g. scope for the thread).

To that end I created my own simple scope using thread-local storage and a stack to store the most current scope data. 

I'm leaving it here in hopes it might be useful and someone else more familiar with serilog project structure can put it in its own enricher (it's a bit too much of a start-up cost to create a new enricher project for such a small class):

        /// Enriches log events with contextual information specific to a scope and thread.
        class ScopeEnricher : ILogEventEnricher
        {
            class Scope : IDisposable
            {
                public readonly string Name;
                public readonly object Value;

                readonly ILogger Logger;
                readonly LogEventLevel Level;
                readonly DateTime StartTime;
                bool disposedValue;

                public Scope(ILogger logger, LogEventLevel level, string name, object value)
                {
                    Name = name;
                    Value = value;
                    Logger = logger;
                    Level = level;
                    StartTime = DateTime.Now;

                    if (Scopes == null)
                    {
                        Scopes = new Stack<Scope>();
                    }

                    Scopes.Push(this);
                    Logger.Write(Level, "begin");
                }

                protected virtual void Dispose(bool disposing)
                {
                    if (!disposedValue)
                    {
                        if (disposing)
                        {
                            Logger.Write(Level, "end [{ElapsedTime:n}ms]",
                                (DateTime.Now - StartTime).TotalMilliseconds);

                            Scopes.Pop();
                        }

                        disposedValue = true;
                    }
                }

                public void Dispose()
                {
                    // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
                    Dispose(disposing: true);
                    GC.SuppressFinalize(this);
                }
            }

            [ThreadStatic]
            static Stack<Scope> Scopes;

            /// <summary>
            /// Create a scope for the current thread.
            /// </summary>
            /// <param name="logger">the logger to log begin/end events for the scope</param>
            /// <param name="level">the level at which to log begin/end events</param>
            /// <param name="name">the name of the scoped property</param>
            /// <param name="value">the value of the scoped property</param>
            /// <returns></returns>
            public static IDisposable BeginScope(ILogger logger, LogEventLevel level, string name, object value)
            {
                return new Scope(logger, level, name, value);
            }

            /// <see cref="ILogEventEnricher.Enrich"/>
            public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
            {
                if (Scopes == null || Scopes.Count == 0)
                {
                    return;
                }

                var currentContext = Scopes.Peek();
                logEvent.AddOrUpdateProperty(
                    propertyFactory.CreateProperty(
                        currentContext.Name, currentContext.Value));
            }
        }

**Comment by rafaelsc** [comment]
Look like you recreate the [LogContext](https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext) with the a little mix of [serilog-metrics](https://github.com/serilog-metrics/serilog-metrics)

**Comment by apenni** [comment]
Yep, pretty much; Serilog's LogContext along with Microsoft extension's BeginScope both appear to be a _global_ context, and I needed a context per-thread (e.g. for a multi-threaded environment); and then threw in timing as a bonus :)

it's pretty useful so far, in that it's great for tracking calls and durations (and other metadata) and not as invasive and non-performant as parsing a callstack on each call (which as the another alternative I considered, but likely too expensive at runtime).

**Comment by nblumhardt** [comment]
Thanks for posting the code, @apenni !

Just to clarify, `LogContext` is also per-thread; if it's showing up as if its global, perhaps you're not disposing the result of `PusProperty()` when you're done?

Will be great if others can find your example here; we keep the core package pretty lean so most new ideas get tried out in gists and community packages, so it's not likely we'd incorporate it at this point.

**Comment by apenni** [comment]
oh boy, that would save me some time! reading through both the docs on PushProperty and Microsoft's BeginScope I didn't seem to come across where it says per-thread, maybe I missed it. 
Thanks folks, I'll need to adjust my implementation so its a wrapper around these existing tools

**Comment by bstordrup** [comment]
> Just to clarify, `LogContext` is also per-thread; if it's showing up as if its global, perhaps you're not disposing the result of `PusProperty()` when you're done?

What in the situation where you have several threads using the same class in code, and you want a `LogContext` per each of these threads (class instances). In that scenario, it would not be enough to use `PushProperty()` and rely on disposing them when done. Because multiple threads will be running at the same time, and none of them would exit until application exit.

Each of the class instances would push the same PropertyType into the context, but with individual values. For example the class A would push an integer with value 48, class B would push an integer with value 49.

I'm not sure it can be handled with the Thread enricher, because the thread id or name would not make sense for those looking in the logs, while some custom information only present in that thread would. For example a company id that would differ from thread to thread.

But being able to hook a LogContext to an ILogger<T> instance would be nice.

**Comment by nblumhardt** [comment]
Hi @bstordrup;

I think what might work best for you is to store an `ILogger` field in the class itself, and use `ForContext` to set it up in the constructor:

```csharp
class Thing
{
    readonly ILogger _log;

    public Thing(int number, ILogger log)
    {
        _log = log.ForContext("Number", number);
    }

    public void Foo()
    {
        // will carry Number property assigned in constructor
        _log.Information("Here in Foo");
    }
}
```


If you don't want to pass an `ILogger` in, you can use the static `Log.ForContext(..)` variant of that method.

HTH!

**Comment by bstordrup** [comment]
Hi @nblumhardt 

I actually got a working solution by using the ILogger<T>.BeginScope() method. I already have the Enrich.FromLogContext as part of the Serilog settings in appsettings.json, and using BeginScope puts the properties in the parameters into the log context, and can be retrieved in the outputTemplate :-)
