### ISSUE TITLE
Formatting Output Wiki Incorrect Sample Output

### ISSUE THREAD

**Issue by nCubed** [serilog/serilog#1483]
On the [Formatting Output Wiki](https://github.com/serilog/serilog/wiki/Formatting-Output) page, the very last example descibes a `CustomDateFormatter` with an example output using 2 different console sinks.

The example output is incorrectly shown as:
```
Created User {Id=1, Name="Adam", Created=17/05/2018 7:08:44 PM} on 17/05/2018 7:08:44 PM // Console1
Created {"Id": 1, "Name": "Adam", "Created": "2018-05-17T19:08:44.0500574+10:00", "$type": "User"} on 17-May-2018 7:08:44 PM // Console2
```

The actual output, using the sample code and .Net Core 3.1 is:
```
[13:57:12 INF] Created {"Id": 1, "Name": "Adam", "Created": "2020-09-01T13:56:59.7803740-05:00", "$type": "User"} on 1/09/2020 1:57:12 PM
[13:57:12 INF] Created {"Id": 1, "Name": "Adam", "Created": "2020-09-01T13:56:59.7803740-05:00", "$type": "User"} on 01-Sep-2020 1:57:12 PM
```
With the only difference between the two outputs being the **`{Created}`** parameter at the end of the log line.

Wasn't sure how to update the Wiki, so opening an issue.

**Comment by nblumhardt** [comment]
Fixed, thank you 👍
