### ISSUE TITLE
New AMQP Serilog Sink ready for listing

### ISSUE THREAD

**Issue by xzuttz** [serilog/serilog#1484]
Hi,

I've created a Serilog Sink that uses the [AMQPNetLite](https://github.com/Azure/amqpnetlite) library, to send logs to message brokers supporting AMQP 1.0. This includes RabbitMQ, EventHub and ServiceBus, to mention a few. 

The sink uses PeriodicBatching and differentiates itself from an [already existing AMQP Sink](https://www.nuget.org/packages/Serilog.Sinks.Amqp/) by both implementation and the ability to send logs in batches. A key selling point is that you can switch brokers by changing the connection string. 

Sink Nuget: https://www.nuget.org/packages/Serilog.Sinks.AMQP.Batching/
Sink Github: https://github.com/xzuttz/serilog-sinks-amqp

Would it be possible to get the sink listed on https://github.com/serilog/serilog/wiki/Provided-Sinks ?

Regards

**Comment by augustoproiete** [comment]
Thanks @xzuttz. Added to the list of [provided sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks).
