### ISSUE TITLE
Serilog does not override minimum level

### ISSUE THREAD

**Issue by apazureck** [serilog/serilog#1487]
Hi, I have a bug / question trying to getting my log output filtered using overrides.

**Description**
When I set overrides to my default loglevel, they still use the same log level, as set on default, even though the _overrides field in my static logger (Serilog.Log.Logger) says otherwise.

![grafik](https://user-images.githubusercontent.com/14858596/93092045-381ed880-f69f-11ea-8b4e-3369887aad60.png)

Overriding `System.Net.Http` still prints Information messages:

```
[INF] System.Net.Http.HttpClient.IDeviceManagementRestClient.LogicalHandler ...
[INF] System.Net.Http.HttpClient.IDeviceManagementRestClient.ClientHandler ...
```

**Reproduction**

I am using serilog with asp.net core 3.1 and adding it like this:

```csharp
hostbuilder.UseSerilog((hostingContext, loggerConfiguration) =>
            {
                    loggerConfiguration
                        .ReadFrom.Configuration(hostingContext.Configuration);
            });
```

In my appsettings I have set the overrides like this:

```json
"Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Error",
                "System.Net.Http": "Warning",
                "ifm.Suite.BuildingBlocks": "Warning"
            }
        },
```

**Expected behavior**

The minimum level for the context should be set to the level I set in my override property.

**Relevant package, tooling and runtime versions**
Serilog 2.10.0
netcore 3.1
Microsoft.AspNetCore 2.2.0

**Comment by nblumhardt** [comment]
Hi @apazureck - thanks for the report.

Can you please install _Serilog.Sinks.Console_ and _Serilog.Formatting.Compact_, and send the output produced by:

```
    .WriteTo.Console(new CompactJsonFormatter())
```

when those _System.Net.Http_ messages are logged?

(Hoping to capture some more detail about how they're structured.)

Many thanks,
Nick

**Comment by apazureck** [comment]
Hi,

Sorry for the late reply. I got sick last week. I'll try to reproduce it in a small demo project to isolate the problem and then put in the formatter.

**Comment by apazureck** [comment]
Hi,

I tried to make a repo to reproduce the issue. I was not able to get it to not work there. So I think the issue is somewhere in our configuration. I will close this issue and post the solution here, when we found the real source that causes the error. Thank you for your support.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; good luck with it!
