### ISSUE TITLE
Update wiki to state Serilog.Settings.Configuration works on .NET Framework too

### ISSUE THREAD

**Issue by Swimburger** [serilog/serilog#1490]
Under the wiki "[Configuration Basics](https://github.com/serilog/serilog/wiki/Configuration-Basics)" it states:

> When external configuration is desirable it can be mixed in sparingly using the Serilog.Settings.AppSettings package (.NET Framework) or Serilog.Settings.Configuration package (.NET Core).

The `Serilog.Settings.Configuration` package works on .NET Framework too. Should that be phrased differently?
I personally recommend using the configuration package because it supports auto-reload of the `MinimumLevel`.

**Comment by nblumhardt** [comment]
Thanks for the note, will fix this 👍

**Comment by nblumhardt** [comment]
Done :-)
