### ISSUE TITLE
I have implemented a new sink for Serilog.

### ISSUE THREAD

**Issue by mahdighorbanpour** [serilog/serilog#1492]
Hi, I have implemented a sink for Azure CosmosDB with supporting partitionkeys. here is the link
https://github.com/mahdighorbanpour/serilog-sinks-azurecosmosdb
how can I contribute that to the serilog github page?

**Comment by nblumhardt** [comment]
Great, we'll add a link; thanks 👍

**Comment by mahdighorbanpour** [comment]
Great, thank you

**Comment by tsimbalar** [comment]
@mahdighorbanpour is this package available somewhere on Nuget ? 

I can't seem to find it there, which means we can't really link it there yet ...

**Comment by mahdighorbanpour** [comment]
I'll make one today.

**Comment by mahdighorbanpour** [comment]
Package is added and readme is also updated with the link.

**Comment by tsimbalar** [comment]
@mahdighorbanpour I just added to https://github.com/serilog/serilog/wiki/Provided-Sinks#list-of-available-sinks 

BTW, watch outm in your README, the first code sample still says `.WriteTo.AzureDocumentDB(<uri>, <secure-key>)` instead of `WriteTo.AzureComosDB` ;)

**Comment by mahdighorbanpour** [comment]
Thanks for reminding me. it's updated now

**Comment by mahdighorbanpour** [comment]
Hi, Still it's not listed on the Serilog page. Do I need to fix something? Thank you

**Comment by bartelink** [comment]
@mahdighorbanpour I can see it at the link Thibaud supplied; please confirm you can too

**Comment by mahdighorbanpour** [comment]
@bartelink Thanks for the hint. Yes, I can see it.
