### ISSUE TITLE
Destructure.ByTransformingWhere for all objects returns null

### ISSUE THREAD

**Issue by andremantaswow** [serilog/serilog#1493]
**Description**
So I need to apply some transformations on all objects that are passed to every log call.
The simplest solution seemed to be to use the `Destructure.ByTransformingWhere`  but it is always printing null. 
It seems like it might be a recursion issue since it hits a breakpoint inside the transformation function a lot of times.
If this is the case, why would it try to transform the thing that was just transformed by the same `LoggerDestructuringConfiguration` ? (i know it matches the predicate but still)

Is there another way to achieve this?

**Reproduction**

```csharp
Log.Logger = new LoggerConfiguration()
    .Destructure.ByTransformingWhere<object>(
        where => true, // i need to transform all parameters passed and i dont know every type that will be passed
        obj =>
        {
            // example of transformation that returns also another object, since i just want to mutate some properties
            return JsonConvert.DeserializeObject(JsonConvert.SerializeObject(obj));
        }
    )
    .WriteTo.Console(new CompactJsonFormatter())
    .CreateLogger();

Log.Logger.Information("test with argument {@arg}", new { prop = "qwerty" });
```
```{"@t":"2020-09-30T15:22:43.2825427Z","@mt":"test with payload {@arg}","arg":null}```

**Expected behavior**
The transformed object should be returned

**Relevant package, tooling and runtime versions**
2.10.0 on windows

**Comment by nblumhardt** [comment]
Thanks for the note, we'll take a look :+1:

**Comment by andremantaswow** [comment]
any updates? @nblumhardt

**Comment by nblumhardt** [comment]
I think recursion is very likely getting involved, here. Writing an `IDestructuringPolicy` and using `Destructuring.With()` is your best bet. Sorry about the slow response! :-)

**Comment by nblumhardt** [comment]
:-) My guess is that whatever the transform is returning, it's then matching the same policy again (since it's catch-all); could possibly be handled better internally, but would be challenging (perf and back-compat). If it turns out to be a simple change and you can send a PR I can definitely take a look, but not planning to dig into it further myself right now.
