### ISSUE TITLE
Can i use serilog without newtonsoft depencey in my asp.net core 3.1 application?

### ISSUE THREAD

**Issue by KamranShahid** [serilog/serilog#1494]
Can i use serilog without newtonsoft depencey in my asp.net core 3.1 application?

**Comment by Numpsy** [comment]
If you're talking about references to Newtonsoft.Json via Serilog.Settings.Configuration (refs #1450), I think https://github.com/serilog/serilog-settings-configuration/pull/222 removes an indirect reference to it but that doesn't look to have made it into a non-preview release yet.

If that is the case, you could try referencing Microsoft.Extensions.DependencyModel v3.x from your own app and see if that helps?
