### ISSUE TITLE
New sink for LogDNA

### ISSUE THREAD

**Issue by iojancode** [serilog/serilog#1495]
Hi I just build and publish a new sink for LogDNA https://logdna.com, consider adding it to the wiki of available sinks:
https://github.com/iojancode/Serilog.Sinks.LogDNA
https://www.nuget.org/packages/Serilog.Sinks.LogDNA

**Comment by augustoproiete** [comment]
Thanks @iojancode !

Wiki page updated - https://github.com/serilog/serilog/wiki/Provided-Sinks
