### ISSUE TITLE
Ability to suppress output of $type in Console Sink

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog#1497]
I'm not sure if this issue applies to the "core" Serilog repo or to the https://github.com/serilog/serilog-sinks-console.

Given that output from https://github.com/serilog/serilog/wiki/Formatting-Output
![изображение](https://user-images.githubusercontent.com/21261007/96257980-fe096500-0fc3-11eb-9424-33340c2b1d90.png)
how can I prevent the output of type information? I tried to figure it out myself from the source code for a while, but I got lost. I've tried using different format strings, but they all render the `$type` or type name of the logged structure.

**Comment by nblumhardt** [comment]
Hi @sungam3r - sorry the reply on this took so long 😅  -- not sure if we ended up discussing this anywhere else?

Currently, this can be overcome by plugging in an `ILogEventEnricher` that removes `StructureValue.TypeTag` on any properties where it appears.

I don't have a better solution for this in mind just now; it might be one of those things that's in the awkward-but-achievable bucket.

Example enricher is: https://github.com/serilog/serilog/issues/1523#issuecomment-754480512

**Comment by djeikyb** [comment]
Btw, this worked out great for me because I'm using the compact formatter anyway:

```
Log.Logger = new LoggerConfiguration()
  .Enrich.FromLogContext()
  .WriteTo.Console(new RenderedCompactJsonFormatter(new JsonValueFormatter(typeTagName: null)))
  .CreateLogger();
```

**Comment by sungam3r** [comment]
Thanks. I came to the same solution.
