### ISSUE TITLE
LoggerConfiguration doesn't have url parameter named 'url'

### ISSUE THREAD

**Issue by AvgustPol** [serilog/serilog#1499]
# Description
In the serilog C# documentation asking to use 'url' parameter for the LoggerConfiguration
![Documentation - LoggerConfiguration doesn't have url parameter named 'url'](https://github.com/AvgustPol/SerilogToDataDog/blob/master/img/%5B%20Documentation%20%5D%20LoggerConfiguration%20doesn't%20have%20url%20parameter%20named%20'url'.png?raw=true)

But the **LoggerConfiguration** doesn't have url parameter named 'url'

# Reproduction 
## NetCore (Issue 1)
https://github.com/AvgustPol/SerilogToDataDog/blob/master/ConsoleApp-NetCore/Program.cs#L31

![Proof - NetFramework - LoggerConfiguration doesn't have url parameter named 'url'](https://github.com/AvgustPol/SerilogToDataDog/blob/master/img/%5B%20NetCore%20%5D%20LoggerConfiguration%20doesn't%20have%20url%20parameter%20named%20'url'.png?raw=true)

## NetFramework (Issue 1)
https://github.com/AvgustPol/SerilogToDataDog/blob/master/ConsoleApp-NetFramework/Program.cs#L31

![Proof - NetFramework - LoggerConfiguration doesn't have url parameter named 'url'](https://github.com/AvgustPol/SerilogToDataDog/blob/master/img/%5B%20NetFramework%20%5D%20LoggerConfiguration%20doesn't%20have%20url%20parameter%20named%20'url'.png?raw=true)

# Expected behavior 
Project builds 

# Relevant package, tooling and runtime versions 

## NetCore
```
  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Datadog.Logs" Version="0.3.3" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="1.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" />
  </ItemGroup>
```

## NetFramework
packages.config
```
<packages>
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net45" />
  <package id="Serilog" version="2.10.0" targetFramework="net45" />
  <package id="Serilog.Enrichers.Environment" version="2.1.3" targetFramework="net45" />
  <package id="Serilog.Enrichers.Thread" version="3.1.0" targetFramework="net45" />
  <package id="Serilog.Sinks.Datadog.Logs" version="0.3.3" targetFramework="net45" />
  <package id="Serilog.Sinks.File" version="4.1.0" targetFramework="net45" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.2.0" targetFramework="net45" />
  <package id="SerilogAnalyzer" version="0.15.0.0" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net45" />
</packages>
```

# Additional context 
Part of the Datadog Support Team regarding ticket #402376.

**Comment by tsimbalar** [comment]
I guess the documentation is incorrect :) 

If you look at the documentation for the DataDog sink, you'll see an example of configuration : 

https://github.com/DataDog/serilog-sinks-datadog-logs

```cs
var config = new DatadogConfiguration(url: "intake.logs.datadoghq.com", port: 10516, useSSL: true, useTCP: true);
var log = new LoggerConfiguration()
    .WriteTo.DatadogLogs(
        "<API_KEY>",
        source: "<SOURCE_NAME>",
        service: "<SERVICE_NAME>",
        host: "<HOST_NAME>",
        tags: new string[] {"<TAG_1>:<VALUE_1>", "<TAG_2>:<VALUE_2>"},
        configuration: config
    )
    .CreateLogger();
```


This is the general repository. I guess if you have issues with the DataDog sink, the proper place would be the corresponding project https://github.com/DataDog/serilog-sinks-datadog-logs

**Comment by AvgustPol** [comment]
The documentation was updated so it should be working now
