### ISSUE TITLE
Add async-compatible enrich interface

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog#1501]
**Is your feature request related to a problem? Please describe.**
We had a requirement to add some HttpContext-related properties inside an enricher. One of these properties was the request body. However, when attempting to read the body, we got an exception caused by this decision:
- [[Announcement] AllowSynchronousIO disabled in all servers #7644
](https://github.com/dotnet/aspnetcore/issues/7644)

Turns out attempting to read the body synchronously in Net Core 3+ is not something you can do by default. We opted for the sync read call inside the enricher because the `ILogEventEnricher` api is not async-compatible.

To make it work, we had to add some nasty workarounds by setting `AllowSynchronousIO` to true for IIS and Kestrel for example.

**Describe the solution you'd like**
If there was an async-compatible version of the `void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)` API we could just call the async read methods as usual, with no need for workarounds.

**Describe alternatives you've considered**
Attempting to block the async calls inside our enricher implementation was not considered since it is a known bad practice that can introduce bugs/deadlocks/etc.

**Additional context**
Perhaps having an async version of the whole interface would be an option:

```csharp
public interface ILogEventEnricher
    {
        Task EnrichAsync(LogEvent logEvent, ILogEventPropertyFactory propertyFactory);
    }
```

Another alternative would be to add the async method into the same interface, but this would probably force a base class design which might be a bigger breaking change.

**Comment by julealgon** [comment]
Found this which seems quite relevant to this discussion:
https://github.com/serilog/serilog-aspnetcore/issues/157#issuecomment-567094265

Looks like creating a middleware with a scoped property would work too as a workaround. However, I'm not sure I like that approach because it mixes "two distinct ways of enriching" at the same time... I could completely get rid of the standard Serilog enrichment system and go with scoped properties if that was the case.

**Comment by nblumhardt** [comment]
I think it'd be great to have a baked-in solution for this 👍 - I don't think it can be via an async method on any current abstraction, however, as these would bubble up and result in needing `ILogger.InformationAsync()` and so-on.

Some infrastructure in _Serilog.AspNetCore_ that emulates enrichment, but hooks in via middleware, could be an option - but how this'd look isn't immediately clear. Otherwise, pushing scoped properties from middleware will be the way to go.

**Comment by julealgon** [comment]
> I think it'd be great to have a baked-in solution for this 👍 - I don't think it can be via an async method on any current abstraction, however, as these would bubble up and result in needing ILogger.InformationAsync() and so-on.

While I get why you are saying this, don't Serilog already support the concept of "async loggers" today? Maybe something along those lines could be done for enrichment as well?

> Some infrastructure in Serilog.AspNetCore that emulates enrichment, but hooks in via middleware, could be an option - but how this'd look isn't immediately clear. 

The biggest challenge would probably to allow similar behaviors within and outside AspNet though right...

> Otherwise, pushing scoped properties from middleware will be the way to go.

This makes me sad because we'll end up having two enrichment mechanisms working at the same time in our solution. Oh well, will probably proceed with that for now.

**Comment by nblumhardt** [comment]
> don't Serilog already support the concept of "async loggers" today?

No, it doesn't support this today.

**Comment by julealgon** [comment]
> No, it doesn't support this today.

Sorry, I think I expressed myself in the wrong way. I mean async _sinks_, not loggers. If enrichment could be delayed until the logs are actually sent to the sync (instead of this being done in the `Log` calls) perhaps it would be possible to decouple the sync from the async parts?

Would probably need some consideration to make all sinks async (instead of sync by default).

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Unfortunately, in the cases where sinks use `async`, they're called on a background thread, and so the context that enrichers would be reading from is not available.
