### ISSUE TITLE
How to generate a unique timestamp

### ISSUE THREAD

**Issue by wbehning** [serilog/serilog#1502]
How do I assure the timestamp is unique when writing events to a log.  With heavy logging, particularly in Debug, many of the records are created with the same exact timestamp value.  This happens with both SQL and Rolling File.  Or is this not feasable.

**Comment by Mario-Hofstaetter** [comment]
Not sure if it is feasible, I'd see it's unnecessary.
Why do you want to achive timestamp uniqueness?

**Comment by wbehning** [comment]
It is just kind of annoying.  There tend to be several entries in the log that are of exactly the same timestamp, down to the millisecond.  The end result is that when using the log in troubleshooting, some of these entries do not necessarily reflect the order in which the code created them.
________________________________

**Comment by nblumhardt** [comment]
Thanks for the note! This is a sink responsibility.

In the rolling file sink, the order of entries in the file will reflect the order of logging. In a database you'll need something like an autoincrement field if you want to preserve below-timestamp-resolution order. Log servers like Seq do this automatically behind the scenes to preserve order.

Hope this helps!
