### ISSUE TITLE
Logging of incoming request details

### ISSUE THREAD

**Issue by stianl** [serilog/serilog#1506]
I just banged my head on an issue trying to get the client remote ip using X-Forwarded-For.

Now I figured Serilog had been "lying" to me all the time. I'm using the "UseForwardedHeaders" middleware and UseSerilogRequestLogging. I'm configuring `EnrichDiagnosticContext` to dump all headers to the log:
```c#
app.UseSerilogRequestLogging(serilogOptions =>
{
    serilogOptions.EnrichDiagnosticContext = (diagnosticContext, httpContext) => diagnosticContext.Set("request_headers", httpContext.Request.Headers.ToDictionary(i => i.Key, i => string.Join(',', i.Value)), true);
});
```

If the application sees a request with a `X-Forwarded-Header`, the `UseForwardedHeaders` middleware uses this so any calls to `HttpContext.Connection.RemoteIpAddress` returns this IP. But, it seems like this mw is actually _modifying_ the headers so Serilog does not see this anymore!

Here's an example where I'm logging to a file. I have a simple controller setup that just returns `HttpContext.Connection.RemoteIpAddress` as a string.

```sh
$ curl -s -H "X-Forwarded-For: 10.10.10.10" http://127.0.0.1:5000/WhatIsMyIp
10.10.10.10
```

```json
{
  "@t": "2020-11-14T07:14:10.1980320Z",
  "@mt": "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms",
  "@r": [
    "0.9083"
  ],
  "request_headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1:5000",
    "User-Agent": "curl/7.71.1",
    "X-Original-For": "[::ffff:127.0.0.1]:65307"
  },
  "RequestMethod": "GET",
  "RequestPath": "/WhatIsMyIp",
  "StatusCode": 200,
  "Elapsed": 0.9083,
  "SourceContext": "Serilog.AspNetCore.RequestLoggingMiddleware"
}
```

I was surprised to see this behaviour in the UseForwardedFor MW , but it seems to be intentional. 

So the feature I'd like to see in Serilog is way to log the _actual_ incoming request which I think is what most care about - not the request after some middleware has modified it.

**Comment by joacar** [comment]
@stianl Why not just place the Serilog middleware _before_ the `UseForwardedHeaders` middleware`?

**Comment by stianl** [comment]
Hi @joacar, thanks for the suggestion! If only it'd be that simple. Unfortunately it seems like `RequestLoggingMiddleware` logs completion *after* the request is processed so it doesn't matter where it is placed.

Here's a snippet from [RequestLoggingMiddleware.cs#L63](https://github.com/serilog/serilog-aspnetcore/blob/2857be82d45801b1fe3a38d7aa2d194a31cc4fc9/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L61):
```csharp
await _next(httpContext);
var elapsedMs = GetElapsedMilliseconds(start, Stopwatch.GetTimestamp());
var statusCode = httpContext.Response.StatusCode;
LogCompletion(httpContext, collector, statusCode, elapsedMs, null);
```
The rationale for having `LogCompletion` where it is, is probably to be able to log the elapsed time and response status code - which makes sense, but makes it difficult to log original request headers when other middleware messes with them - which brings me back to this issue. Maybe we could have something like a `LogStart` in addition to `LogCompletion`?

**Comment by joacar** [comment]
I haven't used this particular feature but I use Serilog, so sorry for not being up to date.
Perhaps you can utilize the collector in your own middleware that runs **before** `UseForwardedHeaders` and add them there and then have them re-added in `LogCompletion`?

**Comment by stianl** [comment]
Thanks for the suggestion @joacar, I think that would be a feasible workaround, yes.
