### ISSUE TITLE
How to Write logs to Cassandra DB using serilog

### ISSUE THREAD

**Issue by neerajk22** [serilog/serilog#1514]
How to Write logs to Cassandra DB using serilog

**Comment by bartelink** [comment]
Search for `serilog cassandra sink` is one answer (this is a general repo for low level implementation; it's not intended to be a discussion forum - its for people working on extending or fixing the core implementation of Serilog).

I'd also ask myself _why_ though - Cassandra really is not an ideal place to be saving logs (having said that, there are Serilog Sinks for all sorts of things I could never imagine people wanting to route logs into, so I won't actually judge!)

**Comment by Parsa2820** [comment]
> Search for `serilog cassandra sink` is one answer (this is a general repo for low level implementation; it's not intended to be a discussion forum - its for people working on extending or fixing the core implementation of Serilog).
> 
> I'd also ask myself _why_ though - Cassandra really is not an ideal place to be saving logs (having said that, there are Serilog Sinks for all sorts of things I could never imagine people wanting to route logs into, so I won't actually judge!)

I'm agree with your comment but I just want to mention that Cassandra is a good database to store your log if you don't need to run search against them.
