### ISSUE TITLE
Ability to remove _typeTag via configuration

### ISSUE THREAD

**Issue by marekott** [serilog/serilog#1523]
Let's consider following scenario:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console(new JsonFormatter())
    .CreateLogger();

var user = new User
{
    Name = "Tom",
    Surname = "Hardy"
};

Log.Information("User: {@user}", user);
```
It is producing following json:
`
{
    "Timestamp": "2021-01-04T09:56:19.1012263+01:00",
    "Level": "Information",
    "MessageTemplate": "User: {@user}",
    "Properties": {
        "user": {
            "_typeTag": "User",
            "Name": "Tom",
            "Surname": "Hardy"
        }
    }
}
`

We are intrested in preserving above structure but removing `_typeTag` property because it's unecessary for us and is only 
polluting our logs. Currently there is very easy way of doing that. Deriving from `JsonFormatter` and overriding `WriteStructure` method:

```csharp
protected override void WriteStructure(string typeTag, IEnumerable<LogEventProperty> properties, TextWriter output)
{
    base.WriteStructure(null, properties, output);
}
```
Passing null to base implementation removes `_typeTag` from output. The problem is that you have marked deriving and overriding from `JsonFormatter` as obsolete and as an alternative you are proposing writing own implementation based on `JsonValueFormatter`. Comparing to current solution it seems as an overkil espesially that we would need to duplicate all logic from `JsonFormatter` and only change one line. Could you provide some alternative allowing to remove `_typeTag` via configuration?

**Comment by rafaelsc** [comment]
Related: 
- https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-json
- https://github.com/serilog/serilog/issues/1256
- https://stackoverflow.com/questions/58302858/serilog-remove-type-property

**Comment by rafaelsc** [comment]
Here is a code that needs more testing to archive what you want.


```csharp
Log.Logger = new LoggerConfiguration()
  .Enrich.With(new RemoveTypeTagEnricher())
  .WriteTo.Console(new JsonFormatter())
  .CreateLogger();
```

```csharp
public class RemoveTypeTagEnricher : ILogEventEnricher
{
	public void Enrich(LogEvent le, ILogEventPropertyFactory lepf)
	{
		foreach (var p in le.Properties)
		{
			if (p.Value is StructureValue sv)
			{
				le.AddOrUpdateProperty(new LogEventProperty(p.Key, RemoveTypeTag(sv)));
			}
		}
	}

	private StructureValue RemoveTypeTag(StructureValue sv)
	{
		return new StructureValue(RemoveTypeTag(sv.Properties), typeTag: null);
	}
	private IEnumerable<LogEventProperty> RemoveTypeTag(IEnumerable<LogEventProperty> props)
	{
		foreach (var p in props)
		{
			if (p.Value is StructureValue sv)
				yield return new LogEventProperty(p.Name, RemoveTypeTag(sv));
			else
				yield return p;
		}
	}
}
```

**Comment by marekott** [comment]
@rafaelsc thanks for your response. We have already tried that solution but compared to override, mentioned in my first post it adds time complexity. Especially that foreach loop should contain inner recursive loop on each property value because they could contain complex type with it's own `_typeTag`, e.g.

```
"ComplexType": {
    "_typeTag": "ComplexType",
    "AdditionalMetadata": [
        {
            "_typeTag": "KeyValuePair`2",
            "Key": "metadataKey1",
            "Value": "medatadaValue1"
        }
    ]
}
```

That's why we were asking for a way to remove that field without damaging performance, a way that we currently have but it will be removed in future releases.

**Comment by nblumhardt** [comment]
Thanks for the feedback @marekott. Does need some more thought.

Are you using `JsonFormatter` with the console sink, or is that just your example? Where are you sending logs to? Thanks!

**Comment by rafaelsc** [comment]
I think the only possible ways are:

- Use the `RemoveTypeTagEnricher `above.
- Using the `CompactJsonFormatter` with `new JsonValueFormatter(typeTagName: null)`. (_Not the same output)_
- Create a new completely new `JsonFormat`. (_Can use the JsonValueFormatter and be implemented to have the same output as the JsonFormatter_)
- Post-processing the JSON file to remove the unwanted property. 
- Override the Serlig `JsonFormatter` as you did, but you will need to ignore the **Obsolete** warning and this new class will probably break in the future.

I don't know if is possible to do this in any other way.

**Comment by marekott** [comment]
@rafaelsc thanks for your comprehensive answers.

**Comment by marekott** [comment]
@nblumhardt, yes in our case we use `JsonFormatter` along with console output. Stdout is consumed (by some native component of container orchestrator) and finally logs are stored in Elasticsearch.

**Comment by marekott** [comment]
Hi @nblumhardt, any thoughts to share regarding this topic?

**Comment by nblumhardt** [comment]
Thanks for your reply, @marekott; sorry about the slow response.

I think [_Serilog.Expressions_](https://github.com/serilog/serilog-expressions#formatting) is the best answer to all output-related issues like this :-)

The template you need is along the lines of:

```
WriteTo.Console(new ExpressionTemplate(
    "{ {Timestamp: @t, Level: @l, MessageTemplate: @mt, Exception: @x, Properties: RemoveTypeTags(@p)} }\n"))
```

where `RemoveTypeTag()` would be [a user-defined function](https://github.com/serilog/serilog-expressions#implementing-user-defined-functions) and should only need to do the (slightly more expensive) type tag removal if properties have structured values.

(You need to plug in the user-defined function via the `ExpressionTemplate`'s `nameResolver` argument - there's an example at the link above.)

Would be great to hear how this goes! If `RemoveTypeTags()` is widely-enough used, we may be able to build an implementation of it into _Serilog.Expressions_ at some point.

Best regards,
Nick

**Comment by marekott** [comment]
Thanks for your response @nblumhardt. After trying your solution I am not sure if I am able to achive my goal (removing `_typeTag`) with preserving structure of logs provided by `JsonFormatter`. Could you please provide your proposal of implementation for `RemoveTypeTag()` where for entity like this:
```csharp
public class User
{
    public string Name { get; set; }
    public string Surname { get; set; }
    public ImmutableDictionary<string, string> AdditionalData { get; set; }
}
```

the result will be exactly `{"Timestamp":"2021-02-12T10:06:06.8708386+01:00","Level":"Information","MessageTemplate":"User: {@user}","Properties":{"user":{"Name":"Tom","Surname":"Hardy","AdditionalData":[{"Key":"age ","Value":"23"}]}}}`? My implementations were creating new `ScalarValue` or `StructureValue` but the result was different compared to the one from `JsonFormatter`.

**Comment by nblumhardt** [comment]
Glad to hear you gave it a shot! I won't have time to try an implementation this week - do you remember how your results were different from what you wanted? Cheers!

**Comment by nblumhardt** [comment]
(Feel free to post the code here 👍 )

**Comment by marekott** [comment]
First, result with `JsonFormatter` is as follows 
```
{
    "Timestamp": "2021-02-18T10:39:37.5982349+01:00",
    "Level": "Information",
    "MessageTemplate": "User: {@user}",
    "Properties": {
        "user": {
            "_typeTag": "User",
            "Name": "Tom",
            "Surname": "Holland",
            "AdditionalData": [
                {
                    "_typeTag": "KeyValuePair`2",
                    "Key": "someKey",
                    "Value": "someValue"
                }
            ]
        }
    }
}
```
As I mentioned before overriding `WriteStructure` preserve this structure simply omitting `_typeTag` properties. Now going to  Serilog.Expressions. My implementation:
```csharp
var myFunctions = new StaticMemberNameResolver(typeof(MyFunctions));

Log.Logger = new LoggerConfiguration()
    .WriteTo.Console(new ExpressionTemplate(
        "{ {Timestamp: @t, Level: @l, MessageTemplate: @mt, Exception: @x, Properties: RemoveTypeTags(@p)} }\n", nameResolver: myFunctions))
    .CreateLogger();
```

Where MyFunctions:

```csharp
public static class MyFunctions
{
    public static LogEventPropertyValue? RemoveTypeTags(LogEventPropertyValue? properties)
    {
        if (properties is StructureValue sv && sv.TypeTag != null)
        {
            return new StructureValue(sv.Properties, null);
        }

        // Undefined - argument was not a string.
        return properties;
    }
}
```
Here comes the question what to return in RemoveTypeTags method. Doing it as above produces response:
```
{
    "Timestamp": "2021-02-18T10:53:22.3020682+01:00",
    "Level": "Information",
    "MessageTemplate": "User: {@user}",
    "Properties": {
        "user": {
            "Name": "Tom",
            "Surname": "Holland",
            "AdditionalData": [
                {
                    "Key": "someKey",
                    "Value": "someValue",
                    "$type": "KeyValuePair`2"
                }
            ],
            "$type": "User"
        }
    }
}
```
We replaced `_typeTag` with `$type`. I was trying to return ScalarValue with some string manipulation but it always ended up with diffrent structure that the first posted in this comment.

**Comment by nblumhardt** [comment]
`RemoveTypeTags` will need to be recursive, e.g.:

```csharp
public static LogEventPropertyValue? RemoveTypeTags(LogEventPropertyValue? value)
{
    if (value is StructureValue sv)
    {
        return new StructureValue(
            sv.Properties.Select(p => new LogEventProperty(p.Name, RemoveTypeTags(p.Value))));
    }

    if (value is SequenceValue qv)
    {
        return new SequenceValue(qv.Elements.Select(RemoveTypeTags));
    }

    return value;
}
```

**Comment by marekott** [comment]
That solved my problem, thanks for help.

**Comment by nblumhardt** [comment]
You're welcome 👍
