### ISSUE TITLE
Dynamic creation of sub-loggers at runtime

### ISSUE THREAD

**Issue by LelandGrunt** [serilog/serilog#1524]
Hello everybody!

My requirement is to dynamically create sub-loggers at application startup/runtime.
The application has a plug-in interface, and a separate (file-)logger should be created for each plug-in.
For the application itself and for all other cases, the default logger should be used.
The default logger is created first, before the plug-ins are loaded.
Based on different blog posts and articles, my solution looks like this:
```csharp
using Serilog;
using Serilog.Filters;

public static class ApplicationLogger
{
    public static ILogger CreateDefaultLogger()
    {
        LoggerConfiguration loggerConfiguration =
                                new LoggerConfiguration()
                                    .MinimumLevel.Information()
                                    .Enrich.WithProperty("PluginName", "Default");

        loggerConfiguration.WriteTo.File(path: "Application.log",
                                         outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {PluginName} {Message:lj}{NewLine}{Exception}");

        return loggerConfiguration.CreateLogger();
    }

    public static ILogger CreateSubLogger(string pluginName)
    {
        LoggerConfiguration loggerConfiguration = new LoggerConfiguration();

        loggerConfiguration.WriteTo.Logger(Log.Logger);

        loggerConfiguration.WriteTo.Logger(lc =>
            {
                lc.Enrich.WithProperty("PluginName", pluginName);
                lc.Filter.ByIncludingOnly(Matching.WithProperty<string>("PluginName", p => p == pluginName));
                lc.WriteTo.File(path: $"{pluginName}.log",
                                outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {PluginName} {Message:lj}{NewLine}{Exception}");
            });

        return loggerConfiguration.CreateLogger();
    }
}

// Usages
public class Application
{
    public void Startup()
    {
        Log.Logger = ApplicationLogger.CreateDefaultLogger();
    }
}


public static class MyPlugin
{
    private static readonly ILogger log;
    
    static MyPlugin()
    {
        log = ApplicationLogger.CreateSubLogger("MyPlugin");
        log.ForContext("PluginName", "MyPlugin")
    }

    public static void DoSomething()
    {
        log.Information("MyPlugin info");
    }
}
```
But it doesn't work as expected.
The plug-in log files are created, but all log messages are saved to the default log file.
Also the {PluginName} property is not available in the files.

What is wrong?
Do I have a Serilog misunderstanding?

Thanks in advance for your help!

**Comment by augustoproiete** [comment]
Hi @LelandGrunt. I see you edited the question and it looks like you already figured out that `Log.Logger` is `static`, thus if your plugins are running on the same application context, they share the same `Log.Logger`, and in your initial code sample you had two different places setting the `Log.Logger`: `MyPlugin` static constructor and `Application.Startup` and the last one to run wins and replaces what was there.

Feel free to reopen if I misunderstood your question.

ps: In the future StackOverflow would be a better fit for usage questions ([`serilog` tag](https://stackoverflow.com/questions/tagged/serilog)).
