### ISSUE TITLE
serilog LoggingLevelSwitch has no effect

### ISSUE THREAD

**Issue by wbehning** [serilog/serilog#1526]
I am configuring Serilog thusly and registering it with my IOC:

```
var levelSwitch = new LoggingLevelSwitch();
levelSwitch.MinimumLevel = LogEventLevel.Information;
_container.RegisterFactory<ILogger>(factory =>
{
	ILogger log = new LoggerConfiguration()
	  .MinimumLevel.ControlledBy(levelSwitch)
	  .Enrich.FromLogContext()
	  .Enrich.WithMachineName()
	  .WriteTo.File(salesPadLogFile, shared: true
		  , outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
		  , rollingInterval: RollingInterval.Day
		  , fileSizeLimitBytes: 1024000
		  , rollOnFileSizeLimit: true
		  , retainedFileCountLimit: 10)
	  .WriteTo.MSSqlServer(connectionString: _connectionString
		, sinkOptions: sinkOptions
		, columnOptions: columnOptions)
	  .CreateLogger();
	return log;
}, new ContainerControlledLifetimeManager());

```

Then I resolve the Logger thusly:

`Logger = _bootstrapper.GetImplementation<ILogger>().ForContext<Worker>();`

However all events are logged.

Examining Logger, I see the the _minimumLevel is set to Verbose.

What gives?

**Comment by augustoproiete** [comment]
@wbehning I'm not able to reproduce. Your code above writes only log events of level `Information` and above, as expected.

The fact that `_minimumLevel` internally is `Verbose` is not relevant when using a `LoggingLevelSwitch`. You should look at `_levelSwitch` and see the minimum level you expect.

![image](https://user-images.githubusercontent.com/177608/103790458-9b9a9080-5017-11eb-8cb3-bdd91fd71e5c.png)

If you can put together a reproducible example, we can investigate further. You might also consider posting details on [Stackoverflow under the Serilog tag](https://stackoverflow.com/questions/tagged/serilog) for a more broader reach.

**Comment by wbehning** [comment]
You are correct - I am seeing the _levelSwitch value being Information.

However, Serilog continues to log Debug events.

**Comment by augustoproiete** [comment]
My guess is that something might wrong in the configuration of your DI container and you're getting a different instance of `ILogger`.

Again, if you can put a Console app reproducible example together, it should be easy to spot the issue.

**Comment by wbehning** [comment]
I was not able to reproduce the issue, which lead me to the real issue.  It was nothing with Serilog or DI.  Essentially we had two versions of the app pointing to the same SQL database.  In short - sorry for the red herring.
