### ISSUE TITLE
 When Serilog is added to the server in Blazor WASM asp core hosted dotnet watch run profile stops working

### ISSUE THREAD

**Issue by rdm1234** [serilog/serilog#1528]
**Description**
I am using Blazor WASM asp core hosted. The dotnet watch run profile is used for debugging.
Before adding Serilog to Program.cs, the profile works correctly - when debugging starts, the browser opens automatically, where the live reload is working.
After I add the UseSerilog method to CreateHostBuilder, the following problem appears: the server side starts, but the browser does not open automatically. Because of this, it is not possible to use live reload.
When using dotnet run, everything works correctly - the browser starts automatically.

**Reproduction**
Here is the code I'm using in Program.cs:
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Serilog;
using Serilog.Core;
using System;
using System.Threading.Tasks;
using TMTC.Server.Extensions;

namespace TMTC.Server
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var levelSwitch = new LoggingLevelSwitch();

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.ControlledBy(levelSwitch)
                .WriteTo.Console()
                .CreateLogger();

            Log.Information("Starting server");

            try
            {
                IHost host = CreateHostBuilder(args).Build();

                await host.RunWithTasksAsync();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Application start failed");
                throw;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```

Here is the profile I use in launchSettings.json:
```
"TMTC Watch": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "workingDirectory": "$(ProjectDir)",
      "commandLineArgs": "watch run",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

**Expected behavior**
The server starts, the browser starts automatically, logging works, live reload works.

**Relevant package, tooling and runtime versions**
Serilog: 2.10.0.
Platform: ASP.NET with .NET 5.

**Additional context**
Here is the logs from server:
![image](https://user-images.githubusercontent.com/20128252/104763151-87bd0000-5776-11eb-8d10-07e01c6b0d9b.png)

**Comment by AliHome** [comment]
I encounter exactly the same issue.

**Comment by nblumhardt** [comment]
I believe this is resolved by https://github.com/dotnet/sdk/pull/15865
