### ISSUE TITLE
Make toplevel destructuring defaults also apply to properties of anonymous objects

### ISSUE THREAD

**Issue by penenkel** [serilog/serilog#1529]
I like to use ad hock anonymous types to combine multiple values into one logged property. This works very well if the properties of said anonymous types are "simple" types like `int` or `string`. But wenn using arrays or other enumerables this breaks down as these are not destructured if they are not toplevel log-properties or explicitly destructured. Explicitly destructuring the anonymous type is also not an option, because this causes the property-names be rendert escaped and, much worse the items within the enumeration to be also destructured.

I would propose applying the same destructuring logic that is used for toplevel log-properties to be also used for the properties of any anonymous type encountered.

Because I`m not certain that I have managed to properly convey my meaning with that description, here a concrete example.  Consider the following four log statements. Message 1 and 2 demonstrate how arrays are destructured when used as toplevel log-properties. Message 3 and 4 use the same arrays as part of an anonymous type. With the anonymous object of message 4 being explicitly destructered.
```
var array1 = new[] {1,2,3};
var array2 = new[] {new MyClass(), new MyClass()};

log.Information("message1 {Data1}", array1);		
log.Information("message2 {Data2}", array2);
log.Information("message3 {Data3}", new {
	Prop1 = 1, 
	Prop2 = array1, 
	Prop3 = array2
});
log.Information("message4 {@Data4}", new {
	Prop1 = 1, 
	Prop2 = array1, 
	Prop3 = array2
});
```
with 
```
class MyClass
{
	Guid _value = Guid.NewGuid();
	public override string ToString(){
		return $"MyClass({_value})";	
	}
}
```
produces the following output
```
[21:53:21 INF] message1 [1, 2, 3]
[21:53:21 INF] message2 ["MyClass(528a0603-cf7f-4e6e-b87f-34c1993b04c3)", "MyClass(a0467dec-bde8-4939-a1e1-096b5642dac1)"]
[21:53:21 INF] message3 { Prop1 = 1, Prop2 = System.Int32[], Prop3 = MyClass[] }
[21:53:21 INF] message4 {"Prop1": 1, "Prop2": [1, 2, 3], "Prop3": [{"$type": "MyClass"}, {"$type": "MyClass"}]}
```
My wish is that message 3 would be rendered like this instead:
```
[21:53:21 INF] message3 { Prop1 = 1, Prop2 = [1, 2, 3], Prop3 = ["MyClass(528a0603-cf7f-4e6e-b87f-34c1993b04c3)", "MyClass(a0467dec-bde8-4939-a1e1-096b5642dac1)"]
```

The above example as [runnable code](https://dotnetfiddle.net/2h7v2E) on dotnetfiddle.net.

**Comment by penenkel** [comment]
Hm, that is understandable. Could we get the build-in destructuring mechanics exposed as a public component somehow, so that we can simply use it in custom destructuring policies?

**Comment by nblumhardt** [comment]
Hi @penenkel - thanks for your reply.

`IDestructuringPolicy`s are only invoked when an event property is marked with `@` in the message template, so this won't enable your scenario without the `@`, but otherwise - if you try message 4, but configure your logger with:

```csharp
    Destructure.AsScalar<MyClass>()
```

I think you'll get output close to what you want. HTH!
