### ISSUE TITLE
PushProperty is ignored if the name is the same as a formatted string placeholder

### ISSUE THREAD

**Issue by davidshen84** [serilog/serilog#1530]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
If I push a property like "prop1" and I have a formatted string in the context in which it contains a named placeholder with the same name, like "message {prop1}", the push property is ignored.

**Reproduction**

```csharp
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .Build();

            var logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .Enrich.FromLogContext()
                .CreateLogger();

            using (LogContext.PushProperty("Prop1", 1))
            {
                logger.Information("message {Prop1}", 1);    
            }
```

```js
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console"
    ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}",
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "Logs/log.txt"
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithThreadId"
    ],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```

**Expected behavior**
The property *Prop1* should appear in the log context.

**Relevant package, tooling and runtime versions**
```xml
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

**Additional context**

I only tested this behaviour with the Console log.

**Comment by nblumhardt** [comment]
Hi! Thanks for your reply.

If you mean by this "`Prop1` appears in the output but only has the value from the message" then this is by design - `Prop1` can only carry a single value, and the more-specific value (from the message) will override the less-specific one (from the context).

If you mean that `Prop1` is missing entirely, can you please include a sample of the output? This would be a bug (but seems unlikely that it would be the case).

Thanks!

**Comment by davidshen84** [comment]
The value of the `Prop1` does show in the final log message.

```csharp
      var Prop1 = "world";
      using (LogContext.PushProperty("Prop1", Prop1))
      {
        logger.Information("hello {Prop1}", Prop1);  
      }
```

```
[10:50:31 INF] hello world {"Application": "Sample"}
```

The *world* even got a highlighting. If this is expected behaviour, then I have a counterexample.

Imaging I am logging some numeric value, e.g. the number of jobs in a message queue. I want to log a message says *current message queue length is {queueLength}*, and add the `queueLength` value in the context in that log message. I can use that *queueLength* value in the context to easily filter my logs.

**Comment by nblumhardt** [comment]
Thanks for the follow-up! Yes, this is expected behavior - `Properties` only includes values not also rendered in the template.

You might the `ExpressionTemplate` formatting mechanism in https://github.com/serilog/serilog-expressions a better match for your scenario here. HTH!

**Comment by davidshen84** [comment]
No, I want to log everything. By *filter my logs`, I mean after the messages have been logged, I want to review or analyze my logs later.

**Comment by davidshen84** [comment]
Actually, if I use string interpolation, I do not have this issue, except I do not get that nice *world* highlighting which I do not need. I guess it is not an urgent issue. We can close this issue if you like.

**Comment by nblumhardt** [comment]
> No, I want to log everything. By *filter my logs`, I mean after the messages have been logged, I want to review or analyze my logs later.

`ExpressionTemplate` can provide that. It's `@p` is synonymous with `Properties`, but includes everything, even fields in the message.

String interpolation sounds like a fine workaround, too 👍
