### ISSUE TITLE
Documentation for .Net Framework is outdated.

### ISSUE THREAD

**Issue by justinjalandoniiwest** [serilog/serilog#1532]
I am following this link: https://github.com/serilog/serilog/wiki/AppSettings#setting-the-minimum-level
But it doesn't seem to be applicable anymore.

The xml settings don't work for instance:
![image](https://user-images.githubusercontent.com/75491773/107124629-fe659d00-68df-11eb-88be-34de333fd405.png)

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. This looks like an issue with your editor configuration - nothing has changed in this regard that we're aware of.

**Comment by justinjalandoniiwest** [comment]
Will check
