### ISSUE TITLE
Automatic Detection of SourceContext without specifiyong source context

### ISSUE THREAD

**Issue by justinjalandoniiwest** [serilog/serilog#1535]
Instead of doing:

```
ILogger _log = Log.ForContext<ClassName>();
```

Allow serilog to do this automatically

**Comment by augustoproiete** [comment]
@nblumhardt implemented this for Autofac: https://github.com/nblumhardt/autofac-serilog-integration

The same building blocks can be used for other DI containers.

**Comment by nblumhardt** [comment]
This isn't something Serilog can do automatically; using IoC to achieve it is a decent option if you are keen to experiment :+1:
