### ISSUE TITLE
Make Serilog.Formatting.Display.LevelOutputFormat public

### ISSUE THREAD

**Issue by Yaroshvitaliy** [serilog/serilog#1538]
I am writting my own serilog sink and I need `Serilog.Formatting.Display.LevelOutputFormat.GetLevelMoniker()` method.
Is it possible to make LevelOutputFormat class public so that I can reuse this functionality?
Or maybe you can suggest another way to convert` LogEventLevel` into string with needed format?

**Comment by nblumhardt** [comment]
Thanks for the note; it would be great to hear what kind of sink it is - is the output text or JSON, for instance?

Here's the class in question for anyone interested:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/LevelOutputFormat.cs

**Comment by Yaroshvitaliy** [comment]
Thank you for the quick reply.
I am writing a sink for [spectre.console](https://github.com/spectresystems/spectre.console) as replacement of console sink.
Output is a text.
The main reason that's because console sink's logs conflict with spectre's progress.
Also I'd like to change colors for log's parameters and level in order to be consistent with other parts of interface built with this library.

**Comment by augustoproiete** [comment]
FYI a version of `LevelOutputFormat` also exists within Serilog.Sinks.Console:

https://github.com/serilog/serilog-sinks-console/blob/65e237f685e017cbdae05ee5ff8b77b3713cf81e/src/Serilog.Sinks.Console/Sinks/SystemConsole/Output/LevelOutputFormat.cs

**Comment by Yaroshvitaliy** [comment]
@augustoproiete, Yes, I saw it, but it's also not public, thanks.

**Comment by augustoproiete** [comment]
@Yaroshvitaliy Sure, but since you said you were creating your own sink as a replacement to the existing console, I thought you'd mention the possibility of "borrowing" the same code for the time being.

**Comment by nblumhardt** [comment]
Grabbing a copy of the code will definitely be the fastest way forward 👍  - even if we move this forward, here, it takes a long time for a new minor/major version of the Serilog package to bake.
