### ISSUE TITLE
KeyValuePairSettings to use SelfLog

### ISSUE THREAD

**Issue by simmotech** [serilog/serilog#1539]
**Is your feature request related to a problem? Please describe.**
I have been using [serilog-settings-xml](https://github.com/rsabirov/serilog-settings-xml) for configuration and couldn't get it to create a simple File sink.
The other settings were OK but not the File sink - it just didn't get created.

I was using the Configuration sample (on the README.md) for guidance but I don't think it was correct
Eventually, I tried adding `<add name="Serilog.Sinks.File" />` and it worked.

**Describe the solution you'd like**
Use SelfLog in KeyValuePairSettings to identify any KeyValue pairs that will effectively be ignored because of a missing Include or any other issue.

**Describe alternatives you've considered**
None

**Additional context**
I am a newbie to serilog.

**Comment by octos4murai** [comment]
@nblumhardt Do you think this is a good fit for a first-time contributor to serilog? If so, I would like to take a stab at it.

**Comment by nblumhardt** [comment]
Hi @octos4murai, thanks for the offer! I think to avoid too many round-trips/wasted effort, it would be good to approach in two parts - (1) if you're able to explore the current code and write up how this can be implemented here first, we can discuss the details before (2) putting together a PR. Sound like a plan?

**Comment by octos4murai** [comment]
> Hi @octos4murai, thanks for the offer! I think to avoid too many round-trips/wasted effort, it would be good to approach in two parts - (1) if you're able to explore the current code and write up how this can be implemented here first, we can discuss the details before (2) putting together a PR. Sound like a plan?

Perfect. Thanks!

**Comment by octos4murai** [comment]
> Hi @octos4murai, thanks for the offer! I think to avoid too many round-trips/wasted effort, it would be good to approach in two parts - (1) if you're able to explore the current code and write up how this can be implemented here first, we can discuss the details before (2) putting together a PR. Sound like a plan?

What are your thoughts on modifying the existing method `KeyValuePairSettings.ApplyDirectives()` to make a call to `SelfLog` when a `target` is not found. Something like this perhaps:

```csharp
static void ApplyDirectives(...)
{
    foreach (var directiveInfo in directives)
    {
        var target = SelectConfigurationMethod(configurationMethods, directiveInfo.Key, directiveInfo);

        if (target == null)
        {
            Serilog.Debugging.SelfLog.WriteLine("Target not found for directive: {0}", directiveInfo.Key);
        }
        else
        {
            var call = (from p in target.GetParameters().Skip(1)
                        let directive = directiveInfo.FirstOrDefault(s => s.ArgumentName == p.Name)
                        select directive == null ? p.DefaultValue : ConvertOrLookupByName(directive.Value, p.ParameterType, declaredSwitches)).ToList();

            call.Insert(0, loggerConfigMethod);

            target.Invoke(null, call.ToArray());
        }
    }
}
```

As long as `SelfLog` is enabled, I think this will provide a means for users to know when they might have forgotten to include a target, in a way that does not block functionality.

**Comment by nblumhardt** [comment]
Looks good to me! 🚀 

"Target" and "directive" are the terms the implementation uses, but perhaps as a user I'd expect it to be more like: "Setting `{0}` could not be matched to an implementation in any of the loaded assemblies" or similar?

**Comment by octos4murai** [comment]
Thanks @nblumhardt! I took your suggestion and added a little more. Kindly let me know if you recommend any further changes.
