### ISSUE TITLE
Custom Fields in Postgres

### ISSUE THREAD

**Issue by RonaldRizkDev** [serilog/serilog#1542]
I am trying to use a custom table layout for my logging.  i am using postgres.  i was able to make it work in sql server, but postgres has been a bear.

This is where i create the logger:
                PerfLogger = new LoggerConfiguration()
                    .WriteTo.PostgreSQL("Conn String", 
                                        "DiagPerformanceLogging", 
                                        batchSizeLimit: 1, 
                                        columnOptions: GetPerfColumnOptions())
                    .CreateLogger();

        private static IDictionary<string, ColumnWriterBase> GetPerfColumnOptions()
        {
            return new Dictionary<string, ColumnWriterBase>
            {
                {"Level", new LevelColumnWriter(true, NpgsqlDbType.Text) },
                {"TenantId", new SinglePropertyColumnWriter("UrlParameters", dbType: NpgsqlDbType.Uuid) },
                {"ProcessName", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
                {"StartedDateTime", new TimestampColumnWriter() },
                {"CompletedDateTime", new TimestampColumnWriter() },
                {"ElapsedMilliseconds", new SinglePropertyColumnWriter("ElapsedMilliseconds", dbType: NpgsqlDbType.Integer) },
                {"UrlPath", new SinglePropertyColumnWriter("UrlPath", dbType: NpgsqlDbType.Varchar) },
                {"UrlMethod", new SinglePropertyColumnWriter("UrlMethod", dbType: NpgsqlDbType.Varchar) },
                {"UrlParameters", new SinglePropertyColumnWriter("UrlParameters", dbType: NpgsqlDbType.Varchar) },
            };
        }

This is where i write the log:
            PerfLogger.Write(LogEventLevel.Information,
                "{TenantId}{StartedDateTime}{CompletedDateTime}{ElapsedMilliseconds}{ProcessName}{UrlPath}{UrlMethod}{UrlParameters}",
                infoToLog.TenantId,
                infoToLog.StartedDateTime, 
                infoToLog.EndDateTime, 
                infoToLog.ElapsedMilliseconds, infoToLog.ProcessName, "UrlPath", "UrlMethod", "UrlParameters");

This is an image of what the table looks like:
https://gyazo.com/6166c272b6101ce51600e720341376e6

When i wirte the data though i never get anything in the log table.  where am i going wrong?

**Comment by augustoproiete** [comment]
@RonaldRizkDev Serilog does not provide out-of-the-box support for PostgreSQL. You are probably using one of the sinks created by the community such as [Serilog.Sinks.Postgresql](https://github.com/b00ted/serilog-sinks-postgresql) or [SerilogSinkForPostgreSQL](https://github.com/SeppPenner/SerilogSinkForPostgreSQL), for example, in which case you can open an issue in the corresponding repository of the sink you're using.

That said, [StackOverflow](https://stackoverflow.com) is usually a good place to ask questions - Make sure your question is under the [`serilog`](https://stackoverflow.com/questions/tagged/serilog) tag.
