### ISSUE TITLE
Allow overriding of MinimumLevel

### ISSUE THREAD

**Issue by mc0re** [serilog/serilog#1547]
#1468 is the other way around. I want to change the `MinimumLevel` based on the current HTTP context (User), not to listen to it.

_Originally posted by @mc0re in https://github.com/serilog/serilog/issues/1545#issuecomment-795843038_

**Comment by mc0re** [comment]
Made a new issue, as you closed the old one, so I'm not sure you'd see my comment there...

**Comment by nblumhardt** [comment]
Reopening the original - thanks 👍
