### ISSUE TITLE
Superfluous check for logging level

### ISSUE THREAD

**Issue by mc0re** [serilog/serilog#1549]
Looks like the current implementation checks the logging level one too many times.

```
        public void Write(LogEventLevel level, string messageTemplate)
        {
            // Avoid the array allocation and any boxing allocations when the level isn't enabled
            if (IsEnabled(level))
            {
                Write(level, messageTemplate, NoPropertyValues);
            }
        }
```

which eventually calls this:

```
        public void Write(LogEventLevel level, Exception exception, string messageTemplate, params object[] propertyValues)
        {
            if (!IsEnabled(level)) return;
```

As methods like `Debug` call the second method directly, the check in the first `Write` is probably superfluous.

**Comment by johnduhart** [comment]
The comment in the first method explains why

```
// Avoid the array allocation and any boxing allocations when the level isn't enabled
```

**Comment by mc0re** [comment]
But to `propertyValues` you pass `NoPropertyValues`, which is a pre-allocated empty array. What am I missing?

**Comment by nblumhardt** [comment]
Thanks @mc0re !

It does look as if the one check in https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Logger.cs#L199 is superfluous. The comment is correct for the other (generic) overloads, but the `NoProperties` case doesn't need it.

Fix and tests would be welcome if anyone's able to.

**Comment by rafaelsc** [comment]
I have a pending PR that fixes this. _Some double-check are still present to avoid the allocation like said before._ But for all other cases, the double-check is not present.

The `NoProperties` case now.
https://github.com/serilog/serilog/pull/1517/files#diff-6419ee31cf5f4ebf5b21ae7e480275b9fb4cbb2c12ae8226418788340470de62R204
And the new Internal Method that is been called.
https://github.com/serilog/serilog/pull/1517/files#diff-6419ee31cf5f4ebf5b21ae7e480275b9fb4cbb2c12ae8226418788340470de62R382

And probably with the use of the `AggressiveInlining` and some compiler optimization together could be removing the double-check and the allocation when is not needed. But I did not disassemble the code to be sure.

**Comment by nblumhardt** [comment]
Closing this as it's stagnated, and the performance cost of this behavior might not be enough to even detect. If anyone's interested in picking it up please feel free to chime in, though!
