### ISSUE TITLE
LogContext Not Working with Single File Publish in .NET 5

### ISSUE THREAD

**Issue by draconastar** [serilog/serilog#1558]
I have a .NET 5.0 application running as a Windows Service using the `BackgroundService` class.  When publishing the application as a single file, log enrichment stops working, but works as expected without that publish option enabled.  The following `ExecuteAsync` example produces these results for me:

```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    using var _ = LogContext.Push(
        new PropertyEnricher("TestProperty1", "Test1"),
        new PropertyEnricher("TestProperty2", "Test2"),
        new PropertyEnricher("TestProperty3", "Test3")
    );

    Log.Warning("Test warning.");

    while (!stoppingToken.IsCancellationRequested)
    {
        Log.Error("Looping test error.");
        await Task.Delay(TimeSpan.FromSeconds(5));
    }
}
```

Running this example in debug produces the expected log output with properties included.  Running it after a _standard_ publish process does as well, but properties are omitted when running the application after a single-file publish.

I've included an archive containing a Solution with the above example, as well as publish results for both single-file and standard publish processes.

[SingleFileExample.zip](https://github.com/serilog/serilog/files/6199080/SingleFileExample.zip)

**Comment by cocowalla** [comment]
Hi, thanks for the report. To get some more clarity, you should [enable Serilog's internal diagnostic logging](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics).

That said, I've just come across this myself, and see things like this:

```
Unable to find a method called FromLogContext
Unable to find a method called WithThreadId
Unable to find a method called Console
Unable to find a method called File
```

Single file publish has some [constraints](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility), so my assumption is they are being hit somewhere along the line. I've only with configuring Serilog using [appsettings](https://github.com/serilog/serilog-settings-configuration) so far, which presumably uses a lot of reflection.

I found a [related issue](https://github.com/serilog/serilog-settings-configuration/issues/244) over at the serilog-settings-configuration repo, which seems to confirm that appsettings-based config doesn't work with single-file apps. I need to try config from code myself to be sure tho.

**Comment by cocowalla** [comment]
So, it was the appsettings config that was the problem - it worked as expected if I moved the config to code. But I didn't want to do that, so dug a bit deeper, and [found ](https://github.com/serilog/serilog-settings-configuration#net-50-single-file-applications) you can work around the appsettings issues by adding the assembly names in a `Using` section of the JSON config, e.g.

```json
{
  "Serilog": {
    "Using": [    <-----THIS SECTION!!!
      "My.Assembly.With.Serilog.Extensions",
      "Serilog",
      "Serilog.Enrichers.Thread",
      "Serilog.Settings.Configuration",
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File"
    ],
    "WriteTo": [

      ...
      
    ],
    "Enrich": [
      "FromLogContext",
      "WithThreadId",
      "WithEventId"
    ]
  }
}
```

**Comment by draconastar** [comment]
This did the trick.  For the sample project above, the `Using` section already had the Sink assemblies but was missing the base Serilog assembly.  Adding that alone got basic LogContext enrichment working:

```json
{
  "Serilog": {
    "Using":  [
      "Serilog",    <--- Adding this line got it working
      "Serilog.Sinks.Console", 
      "Serilog.Sinks.File",
      "Serilog.Sinks.Async"
    ],
    "MinimumLevel": "Information",
    "Enrich": [ "FromLogContext" ],
    "WriteTo": [

         ...

    ]
  }
}
```

Thank you for pointing this out, I must have missed that part of the documentation.

**Comment by nblumhardt** [comment]
The documentation on it is pretty brief - currently just [this paragraph](https://github.com/serilog/serilog-settings-configuration/#net-50-single-file-applications) - we may need some additions over there.

**Comment by hoaza** [comment]
> So, it was the appsettings config that was the problem - it worked as expected if I moved the config to code. But I didn't want to do that, so dug a bit deeper, and [found ](https://github.com/serilog/serilog-settings-configuration#net-50-single-file-applications) you can work around the appsettings issues by adding the assembly names in a `Using` section of the JSON config, e.g.
> 
> ```json
> {
>   "Serilog": {
>     "Using": [    <-----THIS SECTION!!!
>       "My.Assembly.With.Serilog.Extensions",
>       "Serilog",
>       "Serilog.Enrichers.Thread",
>       "Serilog.Settings.Configuration",
>       "Serilog.Sinks.Console",
>       "Serilog.Sinks.File"
>     ],
>     "WriteTo": [
> 
>       ...
>       
>     ],
>     "Enrich": [
>       "FromLogContext",
>       "WithThreadId",
>       "WithEventId"
>     ]
>   }
> }
> ```

thanks so much!!!!
