### ISSUE TITLE
Update wiki link "setting up a new web app" to serilog-aspnetcore repo

### ISSUE THREAD

**Issue by tbolon** [serilog/serilog#1559]
Currently, the wiki link "setting up a new web app" redirects to the [serilog-docker web-sample](https://github.com/serilog/serilog-docker/tree/master/web-sample/src).

This sample does not offer any documentation, neither redirects the reader to the [serilog-aspnetcore](https://github.com/serilog/serilog-aspnetcore) repository which has an excellent readme, and which contains a link to a [more updated sample](https://github.com/serilog/serilog-aspnetcore/tree/dev/samples/Sample).

Perhaps this link could be updated? I think it will help newcomers.

**Comment by augustoproiete** [comment]
Thanks @tbolon. I've updated the link on the wiki to point to [serilog-aspnetcore](https://github.com/serilog/serilog-aspnetcore#serilogaspnetcore---).

[![image](https://user-images.githubusercontent.com/177608/112658144-e3b89a80-8e31-11eb-96be-2b7a55d245c0.png)](https://github.com/serilog/serilog/wiki)
