### ISSUE TITLE
Destructure.AsDictionary<T>() to override default dictionaries-are-enumerables behavior

### ISSUE THREAD

**Issue by alexb5dh** [serilog/serilog#1562]
### Description
Instances of `Dictionary<string, T>` are destructured as objects, this is also [documented](https://github.com/serilog/serilog/wiki/Structured-Data#collections). But it's inheritors does not behave the same.

I understand that class can implement multiple `IDictionary<string, T>` so such interfaces are not handled as objects. But class can not inherit from multiple `Dictionary<string, T>` so I don't think this limitation applies here.

### Reproduction
This works:
```csharp
Serilog.Log.Logger.Information("{@Instance}", new Dictionary<string, string>
{
    {"TestKey", "TestValue"}
});
```
populating **Instance** property as `{TestKey: 'TestValue'}`

But this doesn't:
```csharp
public class MyDictionary: Dictionary<string, string> {}

Serilog.Log.Logger.Information("{@Instance}", new MyDictionary
{
    {"TestKey", "TestValue"}
});
```
and populates **Instance** with `[{Key: 'TestKey', Value: 'TestValue'}]`

### Relevant package, tooling and runtime versions
Serilog 2.10.0, .NET 5.0, Windows 10

**Comment by nblumhardt** [comment]
Thanks for the note - this is by design, subclassing/inheritance isn't taken into account by destructuring rules. There are some APIs for getting around this, but `Destructure.AsDictionary<MyDictionary>()` also might be worth considering as an addition.

**Comment by alexb5dh** [comment]
@nblumhardt thanks for the reply.
I don't understand the reasoning for not considering subclasses, but agree that `Destructure.AsDictionary<MyDictionary>()` would solve this issue. Would you propose to close it or update to track suggested new method?

**Comment by dorathoto** [comment]
```
var fruit = new Dictionary<string, int> { { "Apple", 1 }, { "Pear", 5 } };
  Log.ForContext("Test my fruit", fruit , destructureObjects: true)
         .Information("example");
```

**Comment by nblumhardt** [comment]
`Destructure.AsDictionary<T>` sounds like a reasonable addition; let's keep this open to track :+1:

**Comment by octos4murai** [comment]
Hi folks. If you're set on `Destructure.AsDictionary<T>` as a solution, I would like to take a stab at an implementation.

**Comment by nblumhardt** [comment]
Sounds good to me! :+1: Thanks @octos4murai.

**Comment by octos4murai** [comment]
@nblumhardt, what are your thoughts on the following possible implementations:

### A
```csharp
public LoggerConfiguration AsDictionary<T, TKey, TValue>() where T : IDictionary<TKey, TValue> =>
            ByTransforming<T>(customDict => customDict.ToDictionary(customDict => customDict.Key, cd => cd.Value));
```

- Simple and clean implementation
- Requires the user to specify the key and value types when using `AsDictionary()`
- Sample Usage: `Destructure.AsDictionary<MyDictionary<string, int>, string, int>()`

### B
```csharp
public LoggerConfiguration AsDictionary<T>() where T : IDictionary =>
            ByTransforming<T>(customDict =>
            {
                Type[] argTypes = customDict.GetType().GetGenericArguments();
                Type keyType = argTypes[0];
                Type valType = argTypes[1];

                // Create a standard Dictionary with the same key and value types as T
                dynamic dict = Activator.CreateInstance(typeof(Dictionary<, >).MakeGenericType(keyType, valType));

                foreach (var key in customDict.Keys)
                {
                    dict.Add(
                        (dynamic)Convert.ChangeType(key, keyType),
                        (dynamic)Convert.ChangeType(customDict[key], valType)
                    );
                }

                return dict;
            });
```

- Use of dynamic type may increase chances of runtime errors
- Able to glean the key and value type from the Dictionary when using `AsDictionary()`
- Sample Usage: `Destructure.AsDictionary<MyDictionary<string, int>>()`

**Comment by nblumhardt** [comment]
Hi! Both of these options would require additional allocations and copying; instead, we can create an `IDestructuringPolicy` that detects instances of the type and converts them directly into `DictionaryValue` (no intermediate `Dictionary` step.)

Let me know if this makes sense - should be some example `IDestructuringPolicy` impls out there/already in the codebase.

**Comment by nblumhardt** [comment]
It'd be cool to see this one move forward, but at present it seems to have stagnated so I'll close the ticket as stale. Please chime in if you're interested in picking it back up at any point, or if anyone following along wants to take a shot at it :-)

**Comment by chase-miller** [comment]
@nblumhardt I think this will do the trick. Hopefully I'll be able to open a PR soon, but for now here it is:

```cs
internal class DictionaryDestructurePolicy : IDestructuringPolicy
{
    private readonly Func<object, bool> _destructurePredicate;

    public DictionaryDestructurePolicy(Func<object, bool> destructurePredicate)
    {
        _destructurePredicate = destructurePredicate;
    }

    public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue result)
    {
        if (value == null || _destructurePredicate(value) == false || value is not IDictionary asDictionary)
        {
            result = null;
            return false;
        }

        var elements = new List<KeyValuePair<ScalarValue, LogEventPropertyValue>>();

        foreach (var item in asDictionary.Keys)
        {
            var logEventPropertyValue = propertyValueFactory.CreatePropertyValue(asDictionary[item], true);
            elements.Add(new KeyValuePair<ScalarValue, LogEventPropertyValue>(new ScalarValue(item), logEventPropertyValue));
        }

        result = new DictionaryValue(elements);
        return true;
    }
}
```

```cs
public static class DictionaryDestructurePolicyExtensions
{
    public static LoggerConfiguration AsDictionaryWhere(this LoggerDestructuringConfiguration config, Func<object, bool> destructurePredicate)
    {
        return config.With(new DictionaryDestructurePolicy(destructurePredicate));
    }

    public static LoggerConfiguration AsDictionaryAssignableTo<TValue>(this LoggerDestructuringConfiguration config)
    {
        return config.AsDictionaryWhere(obj => obj is TValue);
    }

    public static LoggerConfiguration AsDictionary<TValue>(this LoggerDestructuringConfiguration config)
    {
        return config.AsDictionaryWhere(obj => obj.GetType() == typeof(TValue));
    }

    public static LoggerConfiguration AllDictionaryTypesAsStructured(this LoggerDestructuringConfiguration config)
    {
        return config.AsDictionaryWhereAssignableTo<IDictionary>();
    }
}
```

Usage:
```cs
            var loggerConfig = new LoggerConfiguration()
                .Destructure.AllDictionaryTypesAsStructured();
```

or:

```cs
            var loggerConfig = new LoggerConfiguration()
                .Destructure.AsDictionary<MyDictionary>();
```

or:

```cs
            var loggerConfig = new LoggerConfiguration()
                .Destructure.AsDictionaryAssignableTo<MyDictionary>();
```

or:

```cs
            var loggerConfig = new LoggerConfiguration()
                .Destructure.AsDictionaryWhere(obj => MyPredicate(obj));
```

**Comment by chase-miller** [comment]
aaaand I just noticed that @sungam3r opened a PR for this. my bad.
