### ISSUE TITLE
Logging System Exceptions

### ISSUE THREAD

**Issue by markbartolo** [serilog/serilog#1563]
Hi,

When logging exceptions with **Serilog** I've noticed then whenever I log the exception as follows:

`Logger.LogError("Some text");` the message is shown in **ApplicationInsights**.

However, when including the exception as follows: `Logger.LogError(exception, exception.Message);` the message is not shown in **ApplicationInsights**. Note that exception is of type `System.Exception`

Is there something additional that is required to log `System.Exception` in **ApplicationInsights**?

Thanks in advance.

**Comment by augustoproiete** [comment]
Closing in favor of the same question posted on StackOverflow: https://stackoverflow.com/questions/67211647/logging-exceptions-with-serilog

**Comment by artemious7** [comment]
the link to StackOverflow is broken

**Comment by augustoproiete** [comment]
@artemious7 It's working for me:

![image](https://user-images.githubusercontent.com/177608/121935307-acfe6c00-cd1e-11eb-9ef8-242bc3b810fa.png)
