### ISSUE TITLE
Not working in Production/AWS EKS

### ISSUE THREAD

**Issue by nambir** [serilog/serilog#1564]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
What's going wrong?
Hi Team,
I am able to wrtie logs and ship logs to logzio from my local system. When i deploy the same code to AWS EKS, the logs are not writing to log file and not shipping to logzio, any idea?

**Reproduction**
Please provide code samples showing how you're configuring and calling Serilog to produce the behavior.

**Expected behavior**
A concise description of what you expected to happen.

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?

**Additional context**

**Comment by bartelink** [comment]
@nambir For troubleshooting of day to day issues, its strongly recommended to route such discussion via Stackoverflow.com - simply tag your question with `serilog` and anyone that will see it here, will see it in their feeds (along with tens of thousands more who will never see it). I recommend reading [this guide](https://stackoverflow.com/help/how-to-ask) before asking to ensure you have the best chace of getting useful help to resolve your issue.
