### ISSUE TITLE
Destructure.ByTransforming<T> not working with fsharp Discriminated Union

### ISSUE THREAD

**Issue by Evangelink** [serilog/serilog#1565]
**Description**
I am not sure if this is really considered as a bug or not but I have noticed that `Destructure.ByTransforming` does not work with fsharp discriminated unions.

**Reproduction**

```fsharp
// Define a DU type
type AB =
    | A of int
    | B of string

// Add the following to your logger configuration
.Destructure.ByTransforming<AB>(fun _ -> "foo" :> obj)

// Instantiate the type
let a = A 10
Log.Information ("{a}", a)
Log.Information ("{@a}", a)
```

**Expected behavior**
I would expect the lambda to be called.

**Relevant package, tooling and runtime versions**
Serilog 2.10.0 on Win 10

**Additional context**
I have tried with and without `Destructurama.FSharp`.

**Comment by nblumhardt** [comment]
Thanks! This is not a bug AFAIK, but a design limitation; Serilog's `ByTransforming<T>` is invariant for `T`, while DUs in F# use subclassing so the type of the member `A` will be `A` and not `AB`.

**Comment by nblumhardt** [comment]
See also https://github.com/destructurama/fsharp#destructuramafsharp --- heading over there now to try to get the wheels turning on that project again, all help appreciated.
