### ISSUE TITLE
Allow some messages to be always sent to sinks regardless of minimum level

### ISSUE THREAD

**Issue by tillig** [serilog/serilog#1566]
## Is your feature request related to a problem? Please describe.

We have a set of requirements where:

- There are two general "classes" of messages being written to logs: diagnostic messages and audit messages.
- Audit messages have a log property `audit=true` attached, diagnostic messages do not.
- All messages go to `Console.Out` in JSON format (via standard console/JSON sinks).
- Consuming classes are using the Microsoft `ILogger<T>` via the `Serilog.Extensions.Logging` package.
- All messages need to have their own source information - there isn't an `ILogger<Audit>` or something where you can set the log levels based on a single source.
- Audit messages should be written at `Information` level so the levels from `Warning` and up are actually application issues that can be alerted.
- Applications are generally configured with a minimum level `Warning` so the log output isn't noisy, but we need to make sure that audit messages are _always_ written, regardless of the configured minimum level.
- Apps are generally configured using the appsettings.json style configuration, though we can absolutely augment that with some additional programmatic config at app startup.

This is sort of the inverse of #1491 - I don't want to change the level of the message itself. I need audit events to stay `Information`, I just need to make sure they're written.

It's also not quite #1078 - I don't want to change the minimum level for a whole execution context, I need the override for a _single message_ based on the presence of a property/value in that message.

## Describe the solution you'd like

I can imagine a couple of different solutions, though I could absolutely be missing something where this is already possible.

- Ability to add a per-message "flag" of some nature to indicate the message should always be written regardless of the configured minimum log level. Granted, usually this means the message should be written at a level like `Critical`, but in this particular case the message isn't "actionable," it's more about legal aspects of ensuring the data is captured.
- An enhancement to `LoggerConfiguration.WriteTo.Conditional(...)` where the log events are _always_ sent to the conditional predicate regardless of the configured log level minimum. Right now it seems the conditional only gets messages that meet the minimum level.

Re: `WriteTo.Conditional` - this along the lines of what I was _hoping_ would work, but it doesn't because if min level is set to `Warning` then `Information` messages never show up.

```c#
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .WriteTo.Conditional(
        e => e.Properties.TryGetValue("audit", out var value) &&
             value is ScalarValue scalar &&
             scalar.Value is bool actualValue &&
             actualValue == true,
        c => c.Console(LogEventLevel.Verbose))
    .CreateLogger();
```

## Describe alternatives you've considered

Likely we'll end up setting up two different Serilog logger configurations, one for diagnostics and one for audit. We'll have to duplicate all the sink configuration because audit and diagnostics need to go to the same sinks with the same formats. The Microsoft logging stuff will be hooked up to the diagnostics side of things; we'll have to create a new `IAuditLogger<T>` interface to handle auditing that is a thin wrapper over Serilog or Microsoft interfaces and resolve that separately from `ILogger<T>`. That kind of sucks because it means two logging dependencies per class and duplicate config.

We've considered something along the lines of what's in #1078 where we have wrappers around all the loggers and factories and things to enable some dynamic handling of the events. We admittedly haven't fully formed this thought; I'm not super eager to have to own wrappers around everything.

## Additional context

I may be missing something, like some clever way to use the `Serilog.Sinks.Map` package to get this done, but between sub-loggers and conditionals and things... I just didn't see something clean here to get the job done.

Here's some code that sort of illustrates what we're trying to do. Note the whole `PushContext` thing is actually hidden behind some helper stuff we have to format audit messages, but this is the general gist:

```c#
public class Worker
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        this._logger = logger;
    }

    public void DoWork()
    {
        this._logger.LogInformation("This won't show because config has minimum level at Warning.");

        using (LogContext.PushProperty("audit", true))
        {
            this._logger.LogInformation("This should ALWAYS show even if the min level is Warning - it's an audit message.");
        }
    }
}
```

**Comment by skomis-mm** [comment]
Hi @tillig ,

There are a couple of ways. Simplest I could get with your hint using `Serilog.Sinks.Map`:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map("audit", false, (audit, lc) => lc.Console(audit ? LogEventLevel.Information : LogEventLevel.Warning))
    .CreateLogger();
```

But can only be configured via code. 

Another one using conditionals:
```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Conditional(Matching.WithProperty("audit", true), lc => lc.Console())
    .WriteTo.Conditional(
        e => !Matching.WithProperty("audit", true)(e), // avoid duplicating audit messages
        lc => lc.Console(LogEventLevel.Warning))
    .CreateLogger();    
```

And can be expressed in `appsettings.json` using `Serilog.Expressions` and `Serilog.Settings.Configuration` (3.2.0-pre):
```json
{
  "Serilog": {
    "Using": [ "Serilog.Expressions", "Serilog.Sinks.Console" ],
    "WriteTo": [
        {
            "Name": "Conditional",
            "Args": {
                "expression": "audit = true",
                "configureSink": [ "Console" ]
            }
        },
        {
            "Name": "Conditional",
            "Args": {
                "expression": "Coalesce(audit, false) = false",
                "configureSink": [
                    {
                        "Name": "Console",
                        "Args": {
                            "restrictedToMinimumLevel": "Warning"
                        }
                    }
                ]
            }
        }
    ]
  }
}
```

**Comment by tillig** [comment]
@skomis-mm These are really interesting examples. Let me pass them back to my team and see if we can get them working. Likely the second one will be closer to where we end up because we do have some "different log sources have different minimum log level overrides" things going on and I think that'll be easier to deal with if we can configure it external to the code.

**Comment by nblumhardt** [comment]
One other thing to think about - the audit logger should use Serilog's `AuditTo....` if possible.

I'd personally consider `IAuditLogger<T>` pretty strongly, since the contract of an audit logger is slightly different from a normal one: auditing failures will throw (via the use of `AuditTo`), so they need to be used with more care/awareness. HTH!

**Comment by tillig** [comment]
Excellent point about `AuditTo` - we definitely want to know about failures. That's something we hadn't considered. Thanks!

**Comment by nblumhardt** [comment]
Sink support for `AuditTo` is still a little thin on the ground; if you run into any gaps let me know, happy to dig in further

**Comment by nblumhardt** [comment]
Let me know if you still need any help/info here, @tillig
