### ISSUE TITLE
Clickonce installation has issue with Sql logging

### ISSUE THREAD

**Issue by danzhang001** [serilog/serilog#1570]
Deploying my application using Clickonce, the Serilog doesn't work with Sql Sink.
it works with other method deployment.

**Comment by augustoproiete** [comment]
@danzhang001 If you're using [Serilog.Sinks.MSSqlServer](https://github.com/serilog/serilog-sinks-mssqlserver) you should create this issue in the sink's repo.

Also, [StackOverflow](https://stackoverflow.com) is usually a good place to ask questions - Make sure your question is under the [`serilog`](https://stackoverflow.com/questions/tagged/serilog) tag.

Here are [some ideas that could help you troubleshoot](https://stackoverflow.com/questions/52953060/serilog-mssql-sink-doesnt-write-logs-to-database/52960592#52960592).

In any case, you'll need to provide a more detailed description of the issue, any error messages from the [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics), and steps to reproduce.
