### ISSUE TITLE
Literal format breaks for DateTime, TimeSpan (causes output truncation) 

### ISSUE THREAD

**Issue by AlexGuzmanAtAbsa** [serilog/serilog#1575]
**Description**
Bug in Serilog package 2.10 when formatting value types with literal (:l) modifier. 

**Reproduction**
Log.Information("first, {value1}, middle, {value2:l}, last", DateTime.Now, DateTime.Now);

**Expected behavior**
first, 05/14/2021 16:29:30, middle, 05/14/2021 16:29:30, last

**Actual behavior**
first, 05/14/2021 16:29:30, middle,

The output is truncated without new line terminator due to an issue with literal formatter on value types. Next logging sentence will continue on the same line (the rest of arguments or template text is ignored).  

**Relevant package, tooling and runtime versions**
Serilog 2.10 used on netcoreapp3.1 (Windows)

**Additional context**
Tested with DateTime, TimeSpan and int value types. Truncation seems to happen for all value types.

If literal modifier is not applicable to value types it should ignore it rather than cause output truncation.

**Comment by nblumhardt** [comment]
Hi! `:l` is a format that is interpreted by Serilog for event messages; if you specify any format for a `DateTime` property it'll need to be a valid .NET DateTime format string (`o`, `yyyy-MM-dd`, etc.) HTH!

**Comment by AlexGuzmanAtAbsa** [comment]
Hi Nicholas, 
Just to clarify, I was not trying to format a datetime using literal per se. The point I was trying to make was using the literal modifier in any value type e.g. `Log.Information("value:l}={value}", 2, 2) `causes the logger to truncate the output. 

A bit of background on my part would help: I have a library wrapping Serilog providing an interceptor logger and a logging filter (ASP net core) whereby you can specify the serialization type for arguments and return type (being a generic library I support  `omit | destructure | toString | literal | type` ). Obviously when used this interceptor or log filter the arguments of these methods/controllers could be anything, so while unit testing the Serilog output I noticed the log events being concatenated because it doesn't handle value types formatted as  literal well.   

There is an easy workaround by using standard formatter check: `if value.GetType().IsValueType == true `=> use `{value}` instead of `{value:l} ,` so not a big deal but I thought, given the fact the user would choose the serialization type somehow arbitrarily the output truncation is an issue, so the logger should probably ignored the (literal) format rather than cause truncated output.

**Comment by nblumhardt** [comment]
Hi @AlexGuzmanAtAbsa - yes, this is expected; `l` isn't a valid format string for most types, and so trying to output them this way will throw.

(E.g. see:

```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine("Hello {0:l}", DateTime.Now);
	}
}
```

Serilog does exactly the same thing, and doesn't try to recover from this and just stops formatting the event.

I don't think `literal` belongs in that list of options - it's a formatting directive that is only valid for `string` (and even so, is emulated by Serilog rather than being a true format specifier). The other options all seem to be about capturing.

**Comment by AlexGuzmanAtAbsa** [comment]
Ok that explains the behavior... I will restrict the use to string types then. Thanks.

**Comment by nblumhardt** [comment]
👍
