### ISSUE TITLE
OpenTelemetry Sink

### ISSUE THREAD

**Issue by xavierjohn** [serilog/serilog#1577]
**Is your feature request related to a problem? Please describe.**
Open telemetry sink.
https://opentelemetry.io/

**Describe the solution you'd like**
Need a open telemetry sink so that we can start using the Open Telemetry Exporters with Serilog.

**Describe alternatives you've considered**
My current alternate solution is to use the ILogging provider as described here.
https://stackoverflow.com/questions/67540739/is-it-possible-to-use-serilog-with-opentelemetry

**Comment by nblumhardt** [comment]
Hi @xavierjohn - thanks for the note. This is something that would normally be developed outside of the core Serilog library. Someone appears to have started working on one recently - though they haven't posted a GitHub repo link: https://www.nuget.org/packages/Serilog.OpenTelemetry/ --- may be worth contacting them to ask what their development plans are?

Another option would be to kick one off and look for collaborators. It's not likely we'll start one here in the core project at this stage (plenty of enthusiasm but limited time :-) )

**Comment by xavierjohn** [comment]
Is it possible to use the UseSerilog writeToProviders: true to write to the ILogger OpenTelemetry implementation?

**Comment by xavierjohn** [comment]
I tried this
https://github.com/xavierjohn/OpenTelemetrySerilogSample/blob/main/OpenTelemetrySerilogSample/Program.cs
but the Serilog entries are missing.


If I try
```
 .UseSerilog((hostingContext, serviceProvider, loggerConfiguration) =>
   {
         var ilogger = serviceProvider.GetRequiredService<ILogger<Serilog.ILogger>>();
         loggerConfiguration.WriteTo.ILogger(ilogger);
   }, writeToProviders: true)
```
I get an infinite loop.

**Comment by nblumhardt** [comment]
Hi - thanks for the follow-ups. It's uncertain which approach will be the best here (`writeToProviders` seems promising, but it's possible that the OpenTelemetry provider has implementation dependencies on the MEL logger so that route may be a dead end.

I think it's most likely that this will need to be developed as an independent add-on/sink, so I'll close this issue - it's not likely we can invest in building this as part of the core project right now. Would be great to hear from anyone who is able to have a go at it, though!

**Comment by ppumkin** [comment]
Is there any way to enrich Serilog with OpentTelemetry ? 
Like so it can catch Acticity Id's / Span Id's into a scope or something.
We have several providers that I build in house and can just add any details I want in the Provider... but I have never had to like work out how to extend a provider like Serilog.

Loving it by the way. It was very easy to integrate into our logger pattern. Thanks for keeping it simple!

**Comment by skomis-mm** [comment]
Hi @ppumkin ,
Probably (https://github.com/RehanSaeed/Serilog.Enrichers.Span) is what you are looking for.

HTH!
