### ISSUE TITLE
Anonymous type name in rendered message

### ISSUE THREAD

**Issue by Tolyandre** [serilog/serilog#1578]
Why does RenderedCompactJsonFormatter put an anonymous type name in `@m`?

I compare its output with Console's default renderer (I use dotnet-script):
```c#
#r "nuget:Serilog, 2.10.0"
#r "nuget:Serilog.Sinks.Console, 3.1.1"
#r "nuget:Serilog.Formatting.Compact, 1.1.0"

using Serilog;
using Serilog.Formatting.Compact;

var log = new LoggerConfiguration()
    .WriteTo.Console()
    .WriteTo.Console(new RenderedCompactJsonFormatter())
    .CreateLogger();

log.Information("Hello {@test}", new {t=123});
```

Output is
```
[00:51:08 INF] Hello {"t": 123, "$type": "<>f__AnonymousType0#1`1"}
{"@t":"2021-05-16T20:51:08.6543982Z","@m":"Hello <>f__AnonymousType0#1`1 { t: 123 }","@i":"3e91f977","test":{"t":123,"$type":"<>f__AnonymousType0#1`1"}}
```

Note that `@m` has "<>f__AnonymousType0#1`1".

Probably the intended behavior is to hide compiler-generated type names from the rendered message.  And probably this happens because of `typeInfo.IsNotPublic` in https://github.com/serilog/serilog/blob/v2.10.0/src/Serilog/Capturing/PropertyValueConverter.cs#L372 is false for an anonymous type.

**Comment by Tolyandre** [comment]
Ok, thank you. I put here a reference https://github.com/dotnet/interactive/issues/1349 where they confirmed that publicity of anonymous types in dotnet-script is intended.

**Comment by KZedan** [comment]
Hey @Tolyandre, I am currently taking a look at this :)

**Comment by KZedan** [comment]
@Tolyandre I am quite tempted to just remove

`typeInfo.IsNotPublic `

from 
![image](https://user-images.githubusercontent.com/48921114/150686231-ef88d68f-e754-4f74-af79-7de97c47bcb6.png)

As it is checking the type chars for anonymous types. Is there a scenario where we would want to have this shown whether public or not?
