### ISSUE TITLE
Conditional sinking at runtime

### ISSUE THREAD

**Issue by kentahikaru** [serilog/serilog#1582]
Hello, we are using serilog in .NET 5   ASP.NET project.
We are currently using File and MSSQL sinks at the same time.

However, we would like to to sink into File only when MSSQL is not awailable (write into sink fails?) for some reason 
Is it possible to configure serilog in this way ?

The problems i see are:
* How do i determine the MSSQL is not available ? Can i get that info from serilog somehose (exception maybe) or do i have to check it outside of serilog by myself ?
* How can i make the swittch from one sink into another ?

PS: Is there some "Serilog API reference" ? Where can i find it ?

Thank you.

**Comment by augustoproiete** [comment]
Hi @kentahikaru check these questions & answers on StackOverflow:

- [Can you configure a default or backup sink?](https://stackoverflow.com/questions/61808109/can-you-configure-a-default-or-backup-sink)
- [C# Serilog conditional logging if one fails?](https://stackoverflow.com/questions/67436306/c-sharp-serilog-conditional-logging-if-one-fails)
