### ISSUE TITLE
Add SerilogUI project to Community Projects wiki

### ISSUE THREAD

**Issue by mo-esmp** [serilog/serilog#1583]
Hi! 👋

I have developed a log viewer for Serilog, It would be great if add you add [SerilogUI](https://github.com/mo-esmp/serilog-ui) to the community projects wiki.

Thanks

**Comment by augustoproiete** [comment]
Thanks @mo-esmp! Added to the [Community-Projects](https://github.com/serilog/serilog/wiki/Community-Projects) wiki
