### ISSUE TITLE
Serilog SignalR sink not compatible with .NET Core 5.0

### ISSUE THREAD

**Issue by enricobenedos** [serilog/serilog#1589]
**Is your feature request related to a problem? Please describe.**
I was looking for a sink in order to stream my backend logs over SignalR. I found the [SignalR sink](https://github.com/serilog/serilog-sinks-signalr) but it is not fully supported on ASP NET Core 5.0. The last commit has been push in 2017.

**Describe the solution you'd like**
Update the SignalR sink.

**Describe alternatives you've considered**
Migrate my project to another log provider.

**Comment by nblumhardt** [comment]
Hi @enricobenedos - thanks for getting in touch. If you're keen to update the SignalR sink for the newer framework version, we'd definitely be up for improving it! I'm no longer watching that repository, but if you `@` mention me in a PR I'll jump in and review.

Another option might be to just grab the interesting parts of the sink project and include them with your own app.

HTH!
