### ISSUE TITLE
PCL Support

### ISSUE THREAD

**Issue by prasannavl** [serilog/serilog#159]
Any-chance, a PCL version is on the near roadmap?

**Comment by ftedin** [comment]
I am not able to use Serilog.Sinks.PeriodicBatching in a PCL project, any idea?

**Comment by SimonCropp** [comment]
what exactly do you mean by "not able to use"?

**Comment by SimonCropp** [comment]
@ftedin and since this issue is closed a while back i suggest you raise a new issue
