### ISSUE TITLE
Allow easier way to add properties to events without adding them to rendered message

### ISSUE THREAD

**Issue by harvinders** [serilog/serilog#1590]
## Problem

I have been using serilog for many years now,  and found one use case where things could be little better. Sometimes we log binary or long value properties to events which makes rendered message difficult to read. Not only that the whole value is repeated, this is especially expensive in storage term when the property is a long value property.

### **Describe the solution you'd like**
It would be great if there is a way to continue to use the convenient logging methods, but enhance them a little like

from
`log.Debug("I am logging a {@Buffer} for {MessageId}", buffer, id);`

to 
`log.Debug("I am logging a {%Buffer} for {MessageId}", buffer, id);`

In the second case % should force the render messaged to not include the buffer value and instead just keep the `{%Buffer}`. 

### **Describe alternatives you've considered**

- Add property using `Log.ForContext` or `LogContext.PushProperty`
  However, this is very verbose and increase the clutter, not as clean as the suggestion. Doable if this logging requirement is limited to only few places in the code base

- Provide custom implementation of `MessageTemplateRenderer`
  Maybe not possible
  
*Additional context**

**Comment by nblumhardt** [comment]
Thanks for the suggestion!

It's an interesting idea, but adding to the message template format currently requires a super-high bar for applicability and utility.

I don't think:

```csharp
log.ForContext("Buffer", buffer).Debug("I am logging a buffer for {MessageId}", id);
```

is so much worse than:

```csharp
log.Debug("I am logging a {%Buffer} for {MessageId}", buffer, id);
```

that we'd consider an extension to cover this case.

We'd also need to resolve questions like whether `%` should imply `@`, or whether `%` and `@` could be combined into `%@`, etc., and then work through updating all of the message template parsers, formatters, and integrated systems, to make sure everything continued to operate smoothly with this addition.

If we could go back in time it would be really interesting to consider, but I think the ship has sailed on this one :-)
