### ISSUE TITLE
Destructuring of arrays seems to be failling 😕

### ISSUE THREAD

**Issue by mvelosop** [serilog/serilog#1606]
**Description**
A simple array didn't get destructured when using the `@` prefix

**Reproduction**
- Clone repo https://github.com/mvelosop/reference-logging

- Run the app and see the log traces

- Switch line 38 between `.ToList()` and `.ToArray()` in  [WeatherForecastController](https://github.com/mvelosop/reference-logging/blob/main/src/SerilogWebApi.DotNetCore31/Controllers/WeatherForecastController.cs):

```cs
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
    _logger.LogInformation("----- Getting values");

    var rng = new Random();
    var result = Enumerable.Range(1, 5)
            .Select(index => new WeatherForecast {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToList();

    _logger.LogInformation("----- Returning result {@Result}", result);

    return result;
}
```

- Trace when `.ToArray()`:

![image](https://user-images.githubusercontent.com/7357806/126864782-122b7ae8-86c3-4202-820f-0a4d75404610.png)

- Trace when `.ToList()`:

![image](https://user-images.githubusercontent.com/7357806/126864802-ee6d0af2-382e-408e-ba95-86ed72bc6773.png)

**Expected behavior**
Should see all array items

**Relevant package, tooling and runtime versions**
- Destructurama.JsonNet - 2.0.0
- Microsoft.AspNetCore.Mvc.NewtonsoftJson - 3.1.17
- Serilog.AspNetCore - 4.1.0
- Serilog.Enrichers.Environment - 2.1.3
- Serilog.Sinks.ApplicationInsights - 3.1.0
- Serilog.Sinks.Seq - 5.0.1

**Additional context**
The repo: <https://github.com/mvelosop/reference-logging>

**Comment by nblumhardt** [comment]
Hey @mvelosop!

This is the ol' covariant-`params`-array-binding gotcha: when you pass `result` as an array, C# binds that to the single `params object[] args` argument in `LogInformation(template, args)`.

Serilog's own `ILogger` works around this, but the _Microsoft.Extensions.Logging_ `ILogger<T>` does not (pros and cons to both approaches). If you use `Log.Information()` (or inject a Serilog `ILogger` instead), this will work as expected.

HTH, let me know if you need more info.

**Comment by mvelosop** [comment]
Hey @nblumhardt! long time 😊

A bit ashamed but also surprised I hadn't stump on this before!

Thanks for the info.

Closing this issue now.

Cheers 😊

**Comment by nblumhardt** [comment]
You're welcome 👍 It's definitely an annoying footgun!
