### ISSUE TITLE
When published as a single exe file,Log folder unable to generate

### ISSUE THREAD

**Issue by quan0zhou** [serilog/serilog#1607]
The log folder cannot be generated when the asp.net core web application is published as a single exe file.
![image](https://user-images.githubusercontent.com/27860834/127617982-02fd13d8-802d-4148-b004-32f0a3671b8d.png)
![image](https://user-images.githubusercontent.com/27860834/127618557-d04cc5fc-2fc2-425c-a5c0-2bd7bb76f873.png)

If you do not check to generate a single file, It will create a log file normally.

**Comment by quan0zhou** [comment]
Also published as a Windows service, there is no log log folder
My code is configured as follows：
![image](https://user-images.githubusercontent.com/27860834/127622756-1a878ba8-f993-4ea8-9f58-39e93c916ac9.png)
appsettings.json
`  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "./logs/log-.txt",
          "rollingInterval": "Day"
        }
      }
    ]
  },`

**Comment by nblumhardt** [comment]
Hi! This looks like: https://github.com/serilog/serilog-settings-configuration/#net-50-single-file-applications
