### ISSUE TITLE
Destructure.ToMaximumStringLength doesn't work consistently

### ISSUE THREAD

**Issue by R4cOOn** [serilog/serilog#1609]
[SerilogTruncateLogs.zip](https://github.com/serilog/serilog/files/6929600/SerilogTruncateLogs.zip)

**Description**
Some of the data that I log is very large/long and messing up the logs (log files get too big, Splunk logging failing etc.)
I used the `Destructure.ToMaximumStringLength` configuration option but the behaviour os the setting is wildly inconsistent.

**Reproduction**
I included a small project showing the inconsistencies for string, collections and objects.

**Expected behavior**
I expected all "objects" to be shortened to the set maximum length.
Whether the logged objects are in collections or complex objects should be irrelevant.
Whether I use "{Token}" or "{0}" syntax should be irrelevant.

**Relevant package, tooling and runtime versions**
.NET Core 5.0, latest Serilog

**Comment by nblumhardt** [comment]
Howdy! Thanks for the note.

Unfortunately, `Destructure.*` policies only apply when "destructuring" (applying capturing directives `{@...}` or `{$...}`), and not when capturing regular properties via plain `{...}`. You'll find that the behavior is consistent from this angle. It's a bit sad not to be able to apply this across the board, but this was one of the trade-offs that had to be made when implementing the feature.

When using .NET format string syntax `{0}`, only one property is being captured, so it's invalid to include multiple different capturing directives against the same property in the one template.

To get the behavior you are looking for, a custom `ILogEventEnricher` plugged in alongside `ToMaximumStringLength()` should be sufficient.

HTH!

**Comment by R4cOOn** [comment]
Thanks for the quick reply and apologies for not replying before.

I'll set the ticket as closed as the feature gets me most of the way there.
