### ISSUE TITLE
Error  at Serilog.Capturing.PropertyValueConverter.GetProperties(Object value)+MoveNext()

### ISSUE THREAD

**Issue by kpato** [serilog/serilog#1612]
**Description**
In a production environment as everting is working properly we get Serilog spikes of 1000+ errors for a few milliseconds.
The error call stack is 
"textPayload": "2021-08-10T16:16:45.0171499Z The property accessor System.DateTime AsUniversalTime threw exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.\n"

--> System.InvalidCastException: Unable to cast object of type 'MongoDB.Bson.BsonString' to type 'MongoDB.Bson.BsonDateTime'.
   at MongoDB.Bson.BsonValue.get_AsBsonDateTime()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Serilog.Capturing.PropertyValueConverter.GetProperties(Object value)+MoveNext()

Witch is not very descriptive and we can't figure out what is causing it. 

**Reproduction**
 loggerConfiguration
                        .MinimumLevel.Is(isDevelopment ? LogEventLevel.Debug : LogEventLevel.Information)
                        .MinimumLevel.Override("Microsoft", isDevelopment ? LogEventLevel.Debug : LogEventLevel.Warning)
                        .MinimumLevel.Override("System", isDevelopment ? LogEventLevel.Debug : LogEventLevel.Warning)
                        .ReadFrom.Configuration(hostingContext.Configuration)
                        .WriteTo.Console(new StackdriverJsonFormatter())
                        .Enrich.WithExceptionDetails()
                        .Enrich.FromLogContext()
                        .Enrich.WithOpenTracingContext();

**Relevant package, tooling and runtime versions**
.netcore 3.1
Serilog.AspNetCore 3.2.0

**Additional context**

**Comment by SergeyZubatkin** [comment]
The issue is in WithExceptionDetails enricher. 
When you log some of mongo exceptions (e.g. MongoAuthenticationException) it tries to destruct all exception's public properties. The problem is that some of them are values from MongoDB.Bson with many public properties like (AsBoolean, AsBsonArray etc.).
To solve this particular problem please use Serilog.Exceptions.MongoDb or remove WithExceptionDetails enricher.
