### ISSUE TITLE
Suspicious memory consumption pattern

### ISSUE THREAD

**Issue by siberianguy** [serilog/serilog#1613]
We're using Serilog with RabbitMq sink and see quite a suspicious memory consumption pattern:
![image](https://user-images.githubusercontent.com/1661681/129060968-0dc289fe-cbef-4ff4-a15b-499ddb844622.png)
As soon as we raise minimal error level from Verbose to Error, memory consumption becomes completely flat, which in my opinion localised the problem to either Serilog or particularly to RabbitMq sink. It does seem like we have some kind of hour-long cycles over there, I checked all the settings but the closest one I was able to find was sinkConfiguration.Period but it's 2 second by default so it doesn't seem to be related to this issue.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. This isn't enough info for us to go on, unfortunately. If you disable the RMQ sink do you still see the issue? In a heap dump at the peak of the cycle, what are the allocation stats per type? HTH!

**Comment by SimonCropp** [comment]
we had something similar when we were logging exceptions thrown from EF. the exception had a property that was the data context, so when serilog was serializing the exception the entire database was being serialized

**Comment by siberianguy** [comment]
> Hi! Thanks for the note. This isn't enough info for us to go on, unfortunately. If you disable the RMQ sink do you still see the issue? In a heap dump at the peak of the cycle, what are the allocation stats per type? HTH!

I will try to investigate further by changing with Sink

> we had something similar when we were logging exceptions thrown from EF. the exception had a property that was the data context, so when serilog was serializing the exception the entire database was being serialized

Interesting... We do use both Serilog and EF but it doesn't seem like it explains what's going on. The thing is we see this memory consumption only when we record Verbose logs, as soon as we switch to Error, everything is fine. As Serilog records only Errors, I feel like it should not be influenced by it

**Comment by nblumhardt** [comment]
Triggering this for exceptions will require something like `"{@Exception}"` in a message template, or use of _Serilog.Exceptions_ - by default, Serilog only records exceptions using `ToString()`.

Any (very) deep-and-wide or circularly-linked type that you serialize in your verbose logs using `@` would be a potential cause, though 👍

**Comment by siberianguy** [comment]
It looks like it was all about GC. Here's a graph over a day:
![image](https://user-images.githubusercontent.com/1661681/132131306-0c774a96-c0df-4c2d-97a6-0bc0236dcee2.png)
In the beginning is when the system started, then it got a little bit more aggressive with GC and then the third phase. We're still running .net 3.1 with default GC settings. I've heard there were a lot of GC optimisations in .net 5 and upcoming .net 6, so we'll hopefully see improved GC patterns over there. There's a chance we can get a better result by playing with Server GC in .net 3.1 but it doesn't seem to be worth it at the moment. Besides, we definitely need to reduce the amount of Verbose logs we write which we reduce memory allocation.

Thanks for the helps, guys. I'm closing the issue as it doesn't seem like there's any issue on the Serilog's side.
