### ISSUE TITLE
JsonValueFormatter don't format a string with defined params

### ISSUE THREAD

**Issue by condezero** [serilog/serilog#1616]
**Description**
On using  theLoggerMessage.Define  with formatString the output json data is not replaced by the parameters

**Reproduction**
```csharp
 public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                })

            .UseSerilog((hostingContext, config) => config
            .ReadFrom.Configuration(hostingContext.Configuration)
            .WriteTo.Console()
            .WriteTo.File(new CompactJsonFormatter(), ("log.json")));
    }
```

```csharp
public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            _logger.SendMessageInfo(Guid.NewGuid(), "Hello", "Bye");
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```
```csharp
public static class LoggerMessageExtensions
{
    internal static class Events
    {
        public static readonly EventId TestMessage = new EventId(1, "MyTestMessage");
    }
    private static readonly Action<ILogger, Guid, string, string, Exception> _testMessageInfo = LoggerMessage
        .Define<Guid, string, string>(LogLevel.Information, Events.TestMessage, "Info: {Param1} {Param2} {Param3}");
        
    public static void SendMessageInfo(this ILogger logger, Guid param1, string param2, string param3) =>
        _testMessageInfo(logger, param1, param2, param3, null);
}
```

**Expected behavior**
I expected a result like
`{"Timestamp":"2021-08-24T15:20:13.0629306+02:00","Level":"Information","MessageTemplate":"Info: 9175043f-96d7-48f9-bc48-29dfe454561c Hello By","Properties":{"Param1":"9175043f-96d7-48f9-bc48-29dfe454561c","Param2":"Hello","Param3":"Bye","EventId":{"Id":1,"Name":"MyTestMessage"},"SourceContext":"SampleService.Worker"}}`
But the result is:
`{"Timestamp":"2021-08-24T15:20:12.0517012+02:00","Level":"Information","MessageTemplate":"Info: {Param1} {Param2} {Param3}","Properties":{"Param1":"c5b66ddb-e1c2-4ad4-bc29-65271431bb53","Param2":"Hello","Param3":"Bye","EventId":{"Id":1,"Name":"MyTestMessage"},"SourceContext":"SampleService.Worker"}}`
On console there is no problem
![image](https://user-images.githubusercontent.com/4093264/130625614-a865b3b5-98be-46db-94f7-24d847922e5b.png)

**Comment by nblumhardt** [comment]
Hi! Sounds like you might be looking for `RenderedCompactJsonFormatter` - ?

**Comment by condezero** [comment]
Hi. This is the way but it does not replace as in the console format.
```
{"@t":"2021-08-25T06:08:52.1328180Z","@m":"Info: 44e56c6a-8dba-413b-a0b4-4df15b337474 \"Hello\" \"Bye\"","@i":"0aab1d95","Param1":"44e56c6a-8dba-413b-a0b4-4df15b337474","Param2":"Hello","Param3":"Bye","EventId":{"Id":1,"Name":"MyTestMessage"},"SourceContext":"SampleService.Worker"}
```
I expect something like
```
{.... 
"@m": "Info: 44e56c6a-8dba-413b-a0b4-4df15b337474 Hello Bye" .
..}
```
Well, I will try to implement custom JsonFormatter like RenderCompactJsonFormatter for expected format.

**Comment by condezero** [comment]
Thanks for help @nblumhardt.

**Comment by nblumhardt** [comment]
If you're considering a custom JSON formatter, https://nblumhardt.com/2021/06/customize-serilog-json-output/ is a worthwhile read :-)

**Comment by condezero** [comment]
Ok, i'll read it. Thanks
