### ISSUE TITLE
EFCore Sink

### ISSUE THREAD

**Issue by TonyValenti** [serilog/serilog#1618]
Is there an EFCore sink?  I know that today there is a MSSQL sink, but I'm wanting something more general that can be used with MSSQL and SQLITE.

Thanks!

**Comment by nblumhardt** [comment]
None I'm aware of, @TonyValenti, but switching between the MSSQL sink and https://github.com/saleem-mirza/serilog-sinks-sqlite would be a reasonable option. HTH!
