### ISSUE TITLE
Dynamically adding a sink causes all file sinks to produce empty logfiles

### ISSUE THREAD

**Issue by chtenb** [serilog/serilog#1619]
The problem scenario described here involves the `File` and `Async` packages as well, but I'm filing the issue here because it looks like a generic problem. The async+file sinks work fine in isolation, it's just that composing them messes things up.

**Description**
The reproduction code below produces empty log files, while this is unexpected. 
It involves a workaround proposed in https://github.com/serilog/serilog/issues/485 to add a sink after the logger is already initialized.
The reason for this is that some sinks are dependent on information that is not available at the very beginning of the application lifetime.
If I do not add the second logger sink "dynamically", but directly in the upper fluent chain, they work fine and produce normal log files.

**Minimal reproduction**
```cs
using Serilog;
using Serilog.Events;
using System.IO;

namespace ConsoleApp1 {
  class Program {
    static void Main(string[] args) {
      var logFileDir = @"fill/in/some/path";

      Log.Logger = new LoggerConfiguration()
        .WriteTo.Logger(lc => lc
          .WriteTo.Async(a => a.File(Path.Combine(logFileDir, "all.log")))
        ).CreateLogger();

      var anotherSink = new LoggerConfiguration()
        .WriteTo.Logger(lc => lc
          .Filter.ByIncludingOnly(e => e.Level >= LogEventLevel.Error)
          .WriteTo.Async(a => a.File(Path.Combine(logFileDir, "error.log")))
        ).CreateLogger();

      // Add the new sink dynamically using workaround from https://github.com/serilog/serilog/issues/485
      Log.Logger = new LoggerConfiguration()
        .WriteTo.Logger(Log.Logger)
        .WriteTo.Logger(anotherSink)
        .CreateLogger();

      Log.Fatal("Logger initialized.");
      Log.Fatal("Closing and flushing logger.");
      Log.CloseAndFlush();
    }
  }
}
```

**Relevant package, tooling and runtime versions**
Windows 10

```
  <package id="Serilog" version="2.10.0" targetFramework="net48" />
  <package id="Serilog.Sinks.Async" version="1.5.0" targetFramework="net48" />
  <package id="Serilog.Sinks.File" version="5.0.0" targetFramework="net48" />
```

**Comment by nblumhardt** [comment]
Thanks for the note. The #485 workaround is imperfect - `Log.CloseAndFlush()` here won't be closing/flushing the first two loggers.

[`ReloadableLogger` from Serilog.Extensions.Hosting](https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/Extensions/Hosting/ReloadableLogger.cs) is a more recent take on this, which better handles this scenario. Still may be some corner cases to flush out from it, but eventually this should move towards the core Serilog package. It'd be great to hear how it goes for you, if you're able to pull it in and give it a try.

**Comment by chtenb** [comment]
Thanks for the reply.

>  Log.CloseAndFlush() here won't be closing/flushing the first two loggers

Will `Log.CloseAndFlush()` _never_ flush subloggers, or just in this particular configuration?

**Comment by nblumhardt** [comment]
`WriteTo.Logger(ILogger)` will never close/flush the passed-in sub-logger; there's no way to instruct Serilog to take ownership of the logger, currently.

A `dispose: true` optional argument might help, but in cases like `WriteTo.Logger(someLogger.ForContext<T>(), dispose: true)`, the contextual logger that's passed in won't be meaningfully disposable, anyway.

The `WriteTo.Logger(callback)` overload does close/flush the created logger, since it's fully owned by the parent logging pipeline.

HTH :-)
