### ISSUE TITLE
Null values are stringified differently than string.Format

### ISSUE THREAD

**Issue by chtenb** [serilog/serilog#1620]
**Description**
The documentation states that 

> Message templates are a superset of standard .NET format strings, so any format string acceptable to string.Format() will also be correctly processed by Serilog.

However, null values are printed by serilog as `null` but by string.Format as `""`. If this is intentional the docs should reflect this and my question becomes: how do I stringify null values as an empty string?

**Reproduction**
```cs
using Serilog;
using System.IO;

namespace ConsoleApp1 {
  class Program {
    static void Main(string[] args) {
      var logFileDir = @"path\to\dir";

      Log.Logger = new LoggerConfiguration().WriteTo.File(Path.Combine(logFileDir, "all.log")).CreateLogger();

      long? v = null;
      Log.Error("A long value {Value}.", v);
      Log.Information($"A long value {v}.");
      Log.CloseAndFlush();
    }
  }
}
```

The output is

```
2021-09-02 17:49:31.186 +02:00 [ERR] A long value null.
2021-09-02 17:49:31.206 +02:00 [INF] A long value .
```

**Expected behavior**

```
2021-09-02 17:49:31.186 +02:00 [ERR] A long value .
2021-09-02 17:49:31.206 +02:00 [INF] A long value .
```

**Relevant package, tooling and runtime versions**
Windows 10

```
  <package id="Serilog" version="2.10.0" targetFramework="net48" />
  <package id="Serilog.Sinks.File" version="5.0.0" targetFramework="net48" />
```

**Comment by nblumhardt** [comment]
Hi; thanks for the note. This is expected - the message template syntax is a superset of .NET format strings, but the formatting/substitution is not identical in all cases (this one, and arrays/enumerables, are the examples that come to mind).

You should be able to use an `ILogEventEnricher` to substitute nulls for empty strings if you want to (you may need to use `WriteTo.Logger()` if you want to apply the enricher to one sink only).

HTH!

**Comment by chtenb** [comment]
Is there any downside to have mixed types as value for a certain logevent property?

**Comment by nblumhardt** [comment]
Will depend on the sink - it'll be fine for `Console` or `File` but may be less great when hooked up to log servers/databases

**Comment by nblumhardt** [comment]
Closing as I don't think there's much we can do here right now - but just to add to the above, in case it helps:

 * You can do the enricher trick only on a sub-logger (`WriteTo.Logger()`) to control which sinks get nulls/empty strings switched, and
 * Alternatively, you might find _Serilog.Expressions_'s `ExpressionTemplate` has a more hackable formatting system which would allow (with some effort) a custom `message()` function to be plugged in in place of the built-in `@m` property that is responsible for rendering the message.

HTH!
