### ISSUE TITLE
How does RequestId get logged?

### ISSUE THREAD

**Issue by nicholasyin** [serilog/serilog#1621]
I spot the RequestId property logged by default, but after a tons of research and search, I still couldn't find where this happened. Not a clue of even which package did this.

The code I'm using is the simplest that I can think of:
```
public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Seq("http://localhost:5341")
                .CreateLogger();
   
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
            .UseSerilog();
    }
```

![image](https://user-images.githubusercontent.com/17007651/132097817-476ff440-327b-494b-87b0-4a6877c39dbc.png)

**Comment by augustoproiete** [comment]
`RequestId` is a property that ASP .NET Core generates and Serilog includes in the `LogContext`. 

- [Serilog: Request Id implementation](https://stackoverflow.com/a/48626278)

**Comment by nicholasyin** [comment]
Still didn't see how exactly this specific RequestId property gets pushed into the scope in the first place. But I guess that's more a Microsoft issue than a Serilog one.
