### ISSUE TITLE
Update provided sink and NuGet links for my sinks

### ISSUE THREAD

**Issue by SeppPenner** [serilog/serilog#1622]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The links to my sinks should be updated.

**Describe alternatives you've considered**
None.

**Additional context**
Under https://github.com/serilog/serilog/wiki/Provided-Sinks, the following sinks need to be updated:

* Amazon S3: From https://github.com/SeppPenner/Serilog.Sinks.AmazonS3 to https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3, the package link has changed from https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.AmazonS3 to https://www.nuget.org/packages/Serilog.Sinks.AmazonS3
* Microsoft Teams alternative: From https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams to https://github.com/serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative, the package link has changed from https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams to https://www.nuget.org/packages/Serilog.Sinks.MicrosoftTeams.Alternative
* Postgres Alternative: From https://github.com/SeppPenner/Serilog.Sinks.Postgresql.Alternative to https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative, the package link has changed from https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.SerilogSinkForPostgreSQL to https://www.nuget.org/packages/Serilog.Sinks.Postgresql.Alternative/
* Telegram alternative: From https://github.com/SeppPenner/Serilog.Sinks.Telegram.Alternative to https://github.com/serilog-contrib/Serilog.Sinks.Telegram.Alternative, the package link has changed from https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.Telegram to https://www.nuget.org/packages/Serilog.Sinks.Telegram.Alternative

The links are forwarded to the serilog-contrib organization and the NuGet package links refer to the new ones (Old ones are deprecated). Nevertheless, it would be good to update the links, I guess :)

**Comment by augustoproiete** [comment]
Wiki updated ✅
