### ISSUE TITLE
Unbundling the Serilog GitHub Organization

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1627]
Way back when Serilog was conceived, we set up this organization so that we could collaborate - we shared project setup, build scripts, and publishing know-how, and we could globally roll out changes as the early versions evolved.

Those were really fun times to be working on Serilog - green fields as far as the eye could see! Within a few years, we'd built sinks and extensions for just about every logging scenario imaginable. The ecosystem that grew directly out of those first projects, or drew on them for examples, is the reason Serilog is where it is today, which is, **everywhere** 😊.

### Where is the `serilog` org today?

The role of the `serilog` organization has changed in the intervening years, though. Although we do still work together here, it's increasingly been perceived as a "blue tick" for blessed packages that carry some implied promise of quality and continuity.

This has brought with it some problems. The quality and continuity are mostly there, but, the selection of packages that benefit from this are a historical accident: the things we were interested in using or working on ten years ago. Should those sinks and extensions still be the ones that attract core maintainer time? In some cases yes, but in many others, I feel like the answer is increasingly "no".

At the same time, there are at least as many sinks and other projects outside of the Serilog organization that ship with high quality year after year. It's unfortunate that the existence of the organization implies that these are somehow lesser, "unofficial", "community", or "third-party" offerings.

But since we're digging into the flaws of centralizing things in the organization, the one that inspired me to post is the difficulty of keeping the projects under the `serilog` umbrella healthy. Given the limited time that we have, does it make sense to try keeping all sixty-five repositories here to a minimum standard of consistency and activity?

Personally, I feel like I'm spread too thinly over organizational basics like keeping builds running and NuGet API keys current (ugh), and as people come and go, it's hard to ensure that every project has the attention of at least a few people to review PRs, answer questions, and keep up with changing tools and dependencies.

As much as I'd love to keep forging ahead, the path we're on is heading for a patchwork of inconsistent quality, and busywork in the organization is detracting from time that could be spent improving the most widely-used projects. I think we're overdue to try something new, and hopefully better.

I've been working on a roadmap out of this for a while, and have some ideas to propose, which I'd appreciate your feedback on (even if you're not a current contributor or maintainer!).

### The small core

The first thing that I think is critical is for the organization to stop being about "organizing", and return to its roots as a way for contributors to the fundamental Serilog libraries to collaborate.

Which packages are "the core"? There's room for adjustment, but I think they are roughly:

* _Serilog_
* _Serilog.Extensions.Hosting_, _Serilog.Extensions.Logging_, _Serilog.Settings.AppSettings_, and _Serilog.AspNetCore_ - integration with the modern .NET stack
* _Serilog.Sinks.Async_, _.BrowserConsole_, _.Console_, _.Debug_, _.EventLog_, _.File_, _.Map_, _.PeriodicBatching_, _.TextWriter_, and _.Trace_ - fundamental sinks that sit close to the core .NET libraries
* _Serilog.Formatting.Compact_, _Serilog.Formatting.Compact.Reader_, and _Serilog.Expressions_ - ecosystem building blocks
* _Serilog.Settings.Configuration_ - XML configuration support for Windows Desktop
* _Serilog.Enrichers.Environment_, _.Process_, and _.Thread_ - these benefit the ecosystem by loosely standardizing the names and contents of enriched properties like `ThreadId`

I'll save you the effort counting: that's twenty-two packages, so no small task to maintain - but many of these are small and stable, and don't require a lot of upkeep.

The organization would also keep the https://serilog.net website, in `serilog.github.io`.

### A single team

Getting out of the business of organizing means having one team that shares maintenance of all of the repositories in the organization. Anyone actively maintaining any of the projects above would move to `@serilog/maintainers`. This makes sense because the knowledge required for maintaining all of these packages is similar (specific to Serilog + general .NET).

I think this would put around a dozen of us in "maintainers", with at least half of us active in the past year.

### What happens to all of those _other_ packages?

That leaves forty-two repositories to find new homes for. These fall into some broad categories.

#### Obsolete, superseded, and abandoned projects

Thes packages would move to a new GitHub organization, owned by a few of the Serilog maintainers, which would be a holding pen or graveyard for unmaintained projects.

All of the projects in `serilog-archive` would themselves be archived, so that they don't generate pointless issue tracker traffic, etc.

Although the projects would be archived, the published NuGet packages would not be, and each project's README would carry prominent instructions for how the project might be revived (in rare/special cases by adoption, but in most instances, by forking and re-publishing under a new name).

Which projects could land here? Some examples are:

 * `serilog-docs`, `serilog-dnx-prerelease`, _Serilog.Enrichers.Xamarin_ - already archived and obsolete
 * _Serilog.Filters.Expressions_ - superseded by _Serilog.Expressions_
 * `serilog-docker`, and `serilog-generator` - essentially "done"/no current plans to update or maintain these

#### Maintained packages

Maintained packages - those whose maintainers are active or contactable within a set window of us kicking off this plan, would ideally move to an organization (new or existing) managed by those maintainers.

The first call on this would belong to the current maintainers. For some, this might mean taking the package on as personal repository, and for others, it will mean that the package moves into a related organization. I've worked with many of the maintainers in the Serilog organization for many years, and I'm confident that they'll know what's best for the packages they're working with.

Packages **without** active or contactable maintainers would move to, in order of preference:

 1. A strongly-related organization; in particular, if the project is a sink that integrates with another app or service, then the owners of that app or service would be given the option to adopt the project. I'm currently a maintainer of _Serilog.Sinks.Seq_, and work for Datalust, who make Seq, so I can fairly safely say that _Serilog.Sinks.Seq_ would move to `datalust` - and so-on.
 2. A new spin-off organization, or an existing one managed by one or more of the current Serilog maintainers, if there's a compelling reason to do so. Some non-core sinks without a reasonable home are still very widely used, and in these cases we might stand up single-package organizations, if we can find maintainers for them.
 3. `serilog-archive`

Why not put packages up for general adoption? Unfortunately, the potential for software supply chain mischief makes this unreasonable.

### Logistics

There are two things we'd need to carry along with projects that move from `serilog`:

 * NuGet publishing permissions: one of the package's maintainers, or an organization managed by them, would receive publishing rights on https://nuget.org, and the `serilog` organization would be removed.
 * CI setup; the Serilog organization primarily uses the free CI services that are graciously provided by the wonderful AppVeyor team. When a project moves out, the existing CI setup would be shut down: it's easy for the new maintainers to set up a build in AppVeyor if they want to, since the `appveyor.yml` file in each repository carries all of the needed information, or they could move to another CI service however they prefer.

 Hopefully, no drama, though some legwork required.

 Short of a better channel, we have this repository, GitHub team discussions, and our Gitter channel for coordination.

 ### And that's it!

 I guess it's safe to consider this an "RFC". When would we move forward? I'm keen for feedback, but I think giving ourselves some preparation time would be wise. If there's general agreement on this direction, we'd begin making the "obvious" changes soon, but should hold off from archiving unmaintained projects etc. until at least January 1st 2022.

Thoughts?

**Comment by niemyjski** [comment]
If we are moving into a new organization I feel it would have the same problems... I'd rather just move our sink into our org and have an official callout that links to our sink? It would be nice to have nuget package ownership as well. Perhaps it would be best to start by getting all projects to use GitHub actions... that might alleviate a lot of maintenance...

**Comment by shahiddev** [comment]
Thanks for the update @nblumhardt - it sounds like sensible approach given the current sprawl.

**Comment by nblumhardt** [comment]
Ah sorry @niemyjski - RE GitHub Actions, I don't really have the bandwidth to attempt it, but once one project is onto Actions (wherever that happens) it should be pretty easy for others to pick that up.

**Comment by augustoproiete** [comment]
Awesome ideas! 💡  Happy to help in making these happen.

> ### _The small core_

The list of packages considered "Core" and kept in this org seem reasonable and including the serilog.net website makes sense

> ### _A single team_

💯 

> _### What happens to all of those _other_ packages?_
> 
> _That leaves forty-two repositories to find new homes for. These fall into some broad categories_.
> 
> _#### Obsolete, superseded, and abandoned projects_
> 

I like the `serilog-archive` home for these projects. I noticed recently that Fody project is doing something similar ([`Fody`](https://github.com/fody) vs [`FodyArchived`](https://github.com/fodyarchived)) and seems to be working... The active Fody org is a lot cleaner and easier to find repos

It would be great if we can work with the authors to mark the obsolete packages as deprecated on nuget.org so that users see warnings

> #### _Maintained packages_
> 
> _Packages **without** active or contactable maintainers would move to, in order of preference_:
> 
 > _1. A strongly-related organization; in particular, if the project is a sink that integrates with another app or service_

Make sense. Sinks linked to an existing GitHub org such as `Seq`, `Elmah`, `ExceptionLess`, etc. are a natural fit to move into these orgs.

> _2. A new spin-off organization, or an existing one managed by one or more of the current Serilog maintainers_

Seems like the [Serilog Contrib](https://github.com/serilog-contrib) org would be a good catch-all for all the Serilog-related projects that fit into this category. Maintainers remain admins on their repos, and makes it easier for everyone interested to follow what's going on through the [org's dashboard](https://github.com/orgs/serilog-contrib/dashboard), as well as providing a good place to promote projects and giving more visibility.

It creates (IMO) a nice distinction of "official" extensions supported by the core team in the Serilog org, and community-supported extensions in the Serilog Contrib org.

> _3. `serilog-archive`_
> 
> _Why not put packages up for general adoption? Unfortunately, the potential for software supply chain mischief makes this unreasonable_.

💯 

> ### _Logistics_
> 

*+1*. Once projects move, the right people have the right permissions to repo and NuGet package, and CI is working normally with AppVeyor on the new home, if there's a desire, we could explore alternatives for making it easier to develop extensions for Serilog and have some standardization both in terms of NuGet package metadata (best practices), as well as having a more out-of-box CI setup that involves less copy/paste and more reusable builds that is easily portable to GitHub Actions, AppVeyor, etc. I'm thinking something along the lines of a creating a "[Serilog Recipe for Cake](https://cake-contrib.github.io/Cake.Recipe/)"... Anyway, this is a whole discussion and deserves its own thread - in the future 😄

**Comment by mivano** [comment]
Good idea to clean/reorganize this. It was not really clear what is an _official_ sink and even so, what makes it official or supported and even if this is better than a non Serilog prefixed sink. 

@Mpdreamz For the Serilog.Sinks.Elasticsearch, does Elastic fancy taking ownership for it? I have not been using ES myself for the last couple of years and that is starting to show in the support of this sink. it has 21.1M downloads on Nuget, so I assume people are still using it :-)

**Comment by nblumhardt** [comment]
Nice to see this rolling along, thanks a bunch everyone for jumping in :-)

If you're managing a sink that hasn't moved yet (I know that Elastic and Elmah.IO both have), perhaps a good next step would be to raise an issue in its repository for the move, pointing back here, so that we can all keep an eye on progress?

I've raised https://github.com/serilog/serilog-sinks-seq/issues/158 for the Seq sink; I'll keep notes on that thread about what actually needed to change, as a mini-reference for the others.

**Comment by nblumhardt** [comment]
See also: https://github.com/NuGet/NuGetGallery/issues/8844

**Comment by nblumhardt** [comment]
Another quick PSA: when you've moved your sink out, and would like CI under the Serilog account removed/disabled, please let me know. The NuGet issue linked above means that the `serilog` account on NuGet can still publish to most moved packages, so if CI isn't disabled there may be a bit of chaos :-)

**Comment by augustoproiete** [comment]
FYI `Serilog.Sinks.Elasticsearch` moved to serilog-contrib with the help of @mivano and @Mpdreamz new repo: https://github.com/serilog-contrib/serilog-sinks-elasticsearch

**Comment by niemyjski** [comment]
@nblumhardt we ended up moving it to our org (https://github.com/exceptionless/serilog-sinks-exceptionless). We are more than happy to keep on contributing to this community! Feel free to turn off the build as I'm going to update it to GitHub actions. If there is a template for how we want all NuGet packages to follow I'd be more than happy to align the package for consistency.

**Comment by nblumhardt** [comment]
Alrighty, folks, moving ahead this week. Might need a hand to track down maintainers, etc., etc., - will post updates here, so you may want to unsubscribe from this thread to avoid being spammed :-)

Oh, and all the best for 2022!

**Comment by nblumhardt** [comment]
Hi folks! As you'll see from the linked issues above, there are still a few of these to figure out, but quite a bit has now been completed.

Here's the current state of things:

Package | New Organization | Repository Moved? | Package Ownership Changed? | Package Deprecated? | Notes
-- | -- | -- | -- | -- | --
✅ serilog.filters.expressions | serilog-archive | Yes | NA | Yes |  
🚧 serilog.formatting.elasticsearch | serilog-contrib | Yes |   |   |  
❓ serilog.sinks.amazonkinesis |   |   |   |   |  
❓ serilog.sinks.applicationinsights |   |   |   |   |  
❓ serilog.sinks.azuredocumentdb |   |   |   |   |  
❓ serilog.sinks.azureeventhub |   |   |   |   |  
❓ serilog.sinks.azuretablestorage |   |   |   |   |  
✅ serilog.sinks.coloredconsole | serilog-archive | Yes | NA | Yes |  
✅ serilog.sinks.couchbase | serilog-archive | Yes | NA | Yes |  
✅ serilog.sinks.couchdb | serilog-archive | Yes | NA | Yes |  
✅serilog.sinks.dynamodb | serilog-archive | Yes | NA | Yes |  
🚧 serilog.sinks.elasticsearch | serilog-contrib | Yes |   |   |  
🚧 serilog.sinks.exceptionless | exceptionless | Yes |   |   |  
✅ serilog.sinks.glimpse | serilog-archive | Yes | NA | Yes |  
✅ serilog.sinks.literate | serilog-archive | Yes | NA | Yes |  
✅ serilog.sinks.log4net | serilog-archive | Yes | NA | Yes |  
❓ serilog.sinks.logentries |   |   |   |   |  
❓ serilog.sinks.loggly |   |   |   |   |  
✅ serilog.sinks.loggr | serilog-archive | Yes | NA | Yes |  
❓ serilog.sinks.mongodb |   |   |   |   |  
🚧 serilog.sinks.mssqlserver | serilog-mssql | Yes |   |   |  
✅ serilog.sinks.nlog | serilog-archive | Yes | NA | Yes |  
❓ serilog.sinks.ravendb |   |   |   |   |  
❓ serilog.sinks.raygun |   |   |   |   |  
❓ serilog.sinks.reflectinsight |   |   |   |   |  
✅ serilog.sinks.rethinkdb | serilog-archive | Yes | NA | Yes |  
❓ serilog.sinks.rollingfile |   |   |   |   | *
🚧 serilog.sinks.seq | datalust | Yes |   |   |  
✅ serilog.sinks.signalr | serilog-archive | Yes | NA | Yes |  
🚧 serilog.sinks.splunk | serilog-archive |   |   |   |  
🚧 serilog.sinks.splunk.tcp | serilog-archive |   |   |   |  
🚧 serilog.sinks.splunk.udp | serilog-archive |   |   |   |  
✅ serilog.sinks.xsockets | serilog-archive | Yes | NA | Yes |  

Legend: ✅ completed, 🚧 in progress (most just need package ownership updates via https://github.com/NuGet/NuGetGallery/issues/8844), ❓ TBC (generally, requires confirmation of the new organization).

serilog.sinks.rollingfile is due for proper deprecation/archiving, but due to its wide use we'll take this one slowly.

A few projects had already moved to `serilog-archive` earlier on, so I've omitted them from the list.

**Comment by niemyjski** [comment]
Exceptionless should be completely migrated

**Comment by nblumhardt** [comment]
@niemyjski the `serilog` org is still an owner of the package on NuGet (linked issue above).

**Comment by niemyjski** [comment]
@nblumhardt I'm unable to remove serilog, can you please login and remove it https://www.nuget.org/packages/Serilog.Sinks.Exceptionless/3.1.5/Manage

**Comment by NxSoftware** [comment]
So is `Serilog.Sinks.Splunk` been completely deprecated or is another org picking up maintenance? The company I work for is in the middle of moving to Splunk and we currently use Serilog, if this combination is no longer going to be supported we'll likely have to move to a logging package other than Serilog 😢

**Comment by nblumhardt** [comment]
Hi @NxSoftware, thanks for the note. The package isn't going away, but we don't currently have a maintainer identified. Given the very low rate of change in it, I might be able to shepherd it along somewhere like `serilog-contrib`, but ideally that would be temporary in the hope that someone from Splunk is able to pick it up in the future (I don't have any Splunk experience, and the previous maintainer is not keen to continue it). Will give it some thought 👍

**Comment by VictorioBerra** [comment]
I second keeping Splunk under the umbrella. Its a simple sink with low rate of change.

**Comment by nblumhardt** [comment]
@VictorioBerra thanks for chiming in! I've unarchived the project and moved it to `serilog-contrib`, without a maintenance team assigned for now. Would you and/or @NxSoftware be interested in co-maintaining and ensuring any future changes to the sink actually work with Splunk? (Not running it myself, I have no way to validate any changes.)

**Comment by VictorioBerra** [comment]
@nblumhardt Thanks for doing that. Like @NxSoftware I would not want to commit and then not be able to maintain a standard level  of service for consumers. I will say Splunk has a free demo here https://hub.docker.com/_/splunk-enterprise-free-for-docker which means anyone should be able to test the sink without any license or installing anything.

**Comment by djordjedjukic** [comment]
@nblumhardt I would like to take ownership on **serilog.sinks.ravendb**. Is that possible?

**Comment by nblumhardt** [comment]
Hi @djordjedjukic - thanks for the ping! Someone from RavenDB has reached out and offered to take on maintenance, so the sink will be transferred to their organization.

**Comment by nblumhardt** [comment]
Hi all - this is just about done! I've updated the list above. Where no maintainers could be found, and no users chimed in in support of keeping the package unarchived, I've transferred to `serilog-archive` and deprecated on NuGet.org. While this might seem like a bit of a "nuclear option" it will hopefully encourage people to come forward and request or suggest new owners. I'll leave this ticket open until the NuGet.org transfers are completed.

**Comment by nblumhardt** [comment]
And looks like it's a wrap! Thanks everyone for your help and guidance! (Special thanks also to @joelverhagen for taking care of the NuGet side of things 🙇‍♂️).

I'm really excited to see where all of the new teams/orgs take things! Back to focusing on moving the core project forward, for me 😃

**Comment by VictorioBerra** [comment]
@nblumhardt I would like to co-maintain the https://github.com/serilog-contrib/serilog-sinks-splunk package if possible. It looks like the lack of maintainer's is causing some PRs and issues to back up. I think if I can at least nudge it along that is better than it having no maintainer at all.

**Comment by nblumhardt** [comment]
@VictorioBerra awesome, thanks! Pinging @augustoproiete, who has been managing membership of the `serilog-contrib` org; Augusto, anything special I need to do to enable this? :-)

**Comment by nblumhardt** [comment]
@VictorioBerra I've sent an invitation now, let me know if it doesn't reach you :-)

**Comment by VictorioBerra** [comment]
@nblumhardt got it, thanks!

**Comment by bencami22** [comment]
Hey @nblumhardt, another repo that is not maintained is https://github.com/serilog-contrib/serilog-sinks-azureeventhub.

is it possible for me to co-maintain as the lack of a maintainer is causing some PRs and issues to back up.

**Comment by nblumhardt** [comment]
Hi @bencami22, thanks for the offer!

I think things have stalled because basic maintenance is needed, but the incoming PRs appear to be feature-driven, and there hasn't been much prior discussion around feature goals for the repo.

If you're still keen to contribute, would it be possible to get the ball rolling by sending a PR (or helping one of the other submitters there to reshape one) that sorts out dependency versions, TFMs, etc., roughly in line with [what's currently going on in the Serilog org](https://github.com/serilog/serilog/issues/2075)? I can make time to review it and we can work forward from there.

If you think any of the existing PRs should be merged as-is please `@` me on them too and I can take a look :-) Thanks!
