### ISSUE TITLE
When writeToProviders is true, the LogLevel of a provider is ignored

### ISSUE THREAD

**Issue by kristofferjalen** [serilog/serilog#1628]
## Description
Setting `writeToProviders` to true will write events to providers. However, the **LogLevel** of a provider seems to be ignored.

In the following example, when removing `UseSerilog`, only error logs are written to MyCustomLogger (as expected).

## Reproduction
**Program.cs**
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .UseSerilog(ConfigureLogger, writeToProviders: true)
        .ConfigureLogging(
            builder => builder.AddMyCustomLogger())
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```
**appsettings.json**
```
"Logging": {
    "LogLevel": {
      "Default": "Debug"
    },
    "MyCustomLogger": {
      "LogLevel": {
        "Default": "Error"
      }
    }
  }
```

## Expected behavior
Logs written to a provider should respect the log level.

## Relevant package, tooling and runtime versions
```
<PackageReference Include="Serilog" Version="2.10.0" />
<PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
```

**Comment by nblumhardt** [comment]
Thanks for the note! `WriteTo.Providers()` doesn't bring in support for the MEL configuration system, so this is expected.

You can get finer-grained control of individual providers if you can move your configuration into code; e.g.:

```csharp
var providers = new LoggerProviderCollection();
providers.AddProvider(new MyCustomProvider());

...

    .WriteTo.Sink(new LoggerProviderCollectionSink(providers), restrictedToMinimumLevel: LogEventLevel.Error);
```

Let me know if this helps :-)

**Comment by nblumhardt** [comment]
Thanks for the follow-up; it looks like what you're after is currently very well supported; will need some more investigation.

**Comment by kristofferjalen** [comment]
> is currently very well supported

Do you mean "is _not_ currently"? Or does it actually work?

**Comment by nblumhardt** [comment]
Sorry, @kristofferjalen  - I meant "not currently" - editing my comment now :-)

**Comment by kristofferjalen** [comment]
:) I see. Any idea on a solution?

**Comment by nblumhardt** [comment]
Sorry I wasn't able to move this one forward. Closing as stale, since there hasn't been a lot of activity in this area.

**Comment by Mike-E-angelo** [comment]
FWIW, I ran into this issue and created a forwarding filter for Serilog to abide by the rules created for MEL in appSettings:

https://github.com/DragonSpark/Framework/blob/7d6e19c2d8c643599964d29d6303bfb97d0a60f7/DragonSpark.Diagnostics/ForwardedFilter.cs

Full commit for context;
https://github.com/DragonSpark/Framework/commit/7d6e19c2d8c643599964d29d6303bfb97d0a60f7
