### ISSUE TITLE
custom Log level fields in addition to Serilog levels

### ISSUE THREAD

**Issue by dkezri** [serilog/serilog#1629]
Hi

We need to have custom log levels "Notice", "Trace" and "Monitor" in addition to  Serilog LogEventLevels enum.
Our old solution is used by external customers and we have to have those three levels.  Is there any way to add  fields.level with custom levels?

**Comment by nblumhardt** [comment]
Hi! Which sink(s) are you using?

**Comment by ClementeGao** [comment]
custom Log level  +1

**Comment by nblumhardt** [comment]
Looks like overriding `WriteLevel` on a custom JSON formatter is supported by the Elastic sink:

https://github.com/serilog-contrib/serilog-sinks-elasticsearch/blob/f14e29ffd8eb1b536efd9b5e8e150b60f49971ec/src/Serilog.Formatting.Elasticsearch/DefaultJsonFormatter.cs#L254

(You can use `ForContext("CustomLevel", MyCustomLevels.SomeLevel).Information(...)` to get more level information through to the sink, if you need to.)

**Comment by dkezri** [comment]
@nblumhardt  I have already tried that way but it will adding ForContext("Level", "MyLevelName").Information(...).

Then it adds  both  "Level:MyLevelName" and  "level:information" fields to the  Elasticsearch and it is confusing for those who try to read logs by levels.

**Comment by nblumhardt** [comment]
@dkezri that's the bit that the custom formatter needs to handle; when you override `WriteLevel()` you can grab the `CustomLevel` property value (if there is one); then, in `WriteProperties()` or a similar override, you can skip the `CustomLevel` property and avoid including it. HTH!

**Comment by nblumhardt** [comment]
Assuming your custom formatter is now working; if you need more help with it, please let us know.
