### ISSUE TITLE
Log of arg throws NotSupportedException

### ISSUE THREAD

**Issue by matthiaslischka** [serilog/serilog#1632]
This throws an `NotSupportedException: Specified method is not supported.` exception:
```c#
var serilogLogger = new LoggerConfiguration().CreateLogger();
var microsoftLogger = new SerilogLoggerFactory(serilogLogger).CreateLogger<ExceptionTests>();
microsoftLogger.LogInformation("{@asd}", new ReadOnlyMemory<byte>());
```
Repo: https://github.com/matthiaslischka/SerilogMethodNotSupportedException

Its caused by the property `public unsafe ReadOnlySpan<T> Span` on `GetValue()`.
I did not yet debug any further to see why exactly this is an issue but I think this special case should be handled by serilog.

BR Matthias

**Comment by matthiaslischka** [comment]
Seems to be related to #348, however I feel that Serilog should catch this.

**Comment by skomis-mm** [comment]
Hi @matthiaslischka ,
indeed, reflection on span api is not supported yet, [see](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Memory/tests/Span/Reflection.cs).

As a workaround now you can specify custom destructure policy e.g.
```csharp
.Destructure.ByTransforming<ReadOnlyMemory<byte>>(x => new { x.IsEmpty, x.Length, Span = x.Span.ToArray() })
```

We probably should handle this type of exception even if `CanRead` is true. @nblumhardt what do you think?

**Comment by nblumhardt** [comment]
:+1: some kind of `SpanTypesScalarConversionPolicy`, perhaps?

**Comment by skomis-mm** [comment]
> 👍 some kind of `SpanTypesScalarConversionPolicy`, perhaps?

The problem that ReadOnlyMemory<>/Span<> are generic types. We can't use reflection api to handle them like ValueTuple<>, unless specify all kinds of closed types statically (as workaroun we can handle subset of them (most common like ReadOnlyMemory<string|int|byte>))

**Comment by nblumhardt** [comment]
Ah, yes - thanks, I see why a policy won't work :-)

We could hook in at https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/GetablePropertyFinder.cs#L33 and check the property type's generic type definition before yielding properties? (Some pros/cons vs attempting to handle the exception...)

Keen to dig in but short on time just now, so I might be missing more obvious things. Definitely does seem like one to fix, though.

**Comment by skomis-mm** [comment]
The main con with `GetablePropertyFinder` is opt-in exclusion. We can't be sure if another new type today or in the future won't throw NSE that will result on bad `Serilog` user experience, given fast and short release cycles of .NET. 

Handling `NSE` prevents that. When Reflection API will work  (aforementioned issue is open) on Span/Memory types it will just work without modification.

Both can be combined with custom `ByteMemoryScalarConversionPolicy`-like policy if we wan't to support some of them.
