### ISSUE TITLE
No log output when using IDestructuringPolicy and reading config from json

### ISSUE THREAD

**Issue by nitewulf** [serilog/serilog#1633]
**Description**
I apologize.  I tried a couple times to get the code formatting to behave.

I have an interface that I am destructuring.  I've implemented an IDestructuringPolicy and observed that it worked perfectly but only when I included a sink in the configuration.  If I read from my configuration json file only I get empty created log files.  If I read from the config file and use a Sink in code I get two populated log files. 

**Reproduction**
This works:

```csharp
public class MyResultDestructuringPolicy : IDestructuringPolicy
{
    public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue result)
    {
        if (value is IResultBase response)
        {
            result = propertyValueFactory.CreatePropertyValue(new { response.ReturnMessage, response.ReturnCode });
            return true;
        }

        result = null;
        return false;
    }
}      

public static Logger GetSerilogger()
{
    var configuration = new ConfigurationBuilder()
    .SetBasePath(AppContext.BaseDirectory)
    .AddJsonFile("logSettings.json", false, true)
    .Build();

    var logger = new LoggerConfiguration()
        .ReadFrom.Configuration(configuration)                
        .Destructure.With(new MyResultDestructuringPolicy())
        .WriteTo
            .File(new CompactJsonFormatter(),
            Path.Combine(AppContext.BaseDirectory, "logs", "log-Json.txt"))
        .CreateLogger();
    Log.Logger = logger;
    return logger;
}
 ```

and my config looks like:
```json
{
  "Serilog": {
    "Using": [
      "Serilog",
      "Serilog.Sinks.File",
      "Serilog.Sinks.Async",
      "Serilog.Formatting.Compact"
    ],
    "MinimumLevel": "Debug",
    "WriteTo:Async": {
      "Name": "Async",
      "Args": {
        "configure": [
          {
            "Name": "File",
            "Args": {
              "path": "./logs/log.json",
              "restrictedToMinimumLevel": "Debug",
              "rollingInterval": "Day",
              "shared": "True",
              "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
            }
          }
        ]
      }
    }
  }
}
```

**Expected behavior**
If I omit the .WriteTo.File in code I would expect logging to still work.

**Relevant package, tooling and runtime versions**
Serilog 2.10.0

**Comment by skomis-mm** [comment]
Hi @nitewulf ,
I took you code and it worked as expected. What version of `Serilog.Settings.Configuration` do you use? 
Can you make a complete minimal example  that reproduces the problem? 
Thanks!

**Comment by nitewulf** [comment]
Sure.  I'll put together a complete sample application on github to demonstrate what I'm seeing.  Thanks for fixing the formatting.  ```chsarp and ```json.  I'll remember that.  And it's version 3.3.0

**Comment by nitewulf** [comment]
I did figure out what was going on.  I was using an Autofac container which I had forgotten to dispose of.  What's interesting is that when a code sink is configured the logger seems to get implicitly disposed of.  However with only using a .json config and forgetting to dispose the container the logger does not flush and write.

Totally understand that not disposing of objects is bad and was the culprit here - oops.  But, there's still something different happening when using a code configured sink vs not.  If it's worth looking into further I did put together a project where I discovered my error.  A couple of the unit tests don't technically pass since I'm testing for a populated log file which gets written to after the test method finishes.

https://github.com/nitewulf/serilog-destructure-test

**Comment by skomis-mm** [comment]
@nitewulf the difference I see between configuration via code in your sample and via `appsettings.json` is using `Serilog.Sinks.Async` wrapper for the latter. 
This wrapper adds delay on flushing to the wrapped sink. This probably results in the differences you observed.
