### ISSUE TITLE
Configurable JSON formatter

### ISSUE THREAD

**Issue by kmcclellan** [serilog/serilog#1637]
**Is your feature request related to a problem? Please describe.**
In #819 the virtual members to configure `JsonFormatter` were deprecated, with [the note](https://github.com/serilog/serilog/blob/13dd8cfc5ee47a841128beaef853b3798464f807/src/Serilog/Formatting/Json/JsonFormatter.cs#L35-L37) that custom formatters should now be written using `JsonValueFormatter`. This was a good decision, but if leaves a bit of a configuration vacuum. Whereas before if I wanted to skip formatting the exception, I could override `WriteException` and have it do nothing, it's a bit harder to do the same thing using just `JsonValueFormatter`.

**Describe the solution you'd like**
Serilog could provide a more configurable alternative to `JsonFormatter`. It could be configured to do things like skip certain pieces of information in the log event or choose other names for their JSON object keys. It would make common use cases easier by avoiding the need to write a custom class.

Example usage:
```c#
// Configure file sink to use the key "MyLogMessage" and skip the exception.
Log.Logger = new LoggerConfiguration()
  .WriteTo.File(
      new ConfiguredJsonFormatter(messageName: "MyLogMessage", exceptionName: null),
      "logs.json")
  .CreateLogger();
```

**Describe alternatives you've considered**
I understand there are other formatters available in the `serilog-formatting-compact` project that do some of the things such a formatter could be configured to do. However, the compact formatters are designed to serve specific purposes (compactness) and are still lacking in configurability. I think that a configurable formatter belongs in this repository since it is in its nature intended for general purposes.

**Comment by kmcclellan** [comment]
Let me know if there's feedback or interest in a PR for the following. It leverages `JsonValueFormatter` to do the heavy lifting and manages to stay small (and performant?) while introducing some useful configuration features.

```c#

#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using Serilog.Events;

namespace Serilog.Formatting.Json
{
    /// <summary>
    /// Formats log events into JSON text using configurable property mappings.
    /// </summary>
    public class MappedJsonFormatter : JsonValueFormatter, ITextFormatter
    {
        /// <summary>
        /// Intializes a new instance of <see cref="MappedJsonFormatter"/>.
        /// </summary>
        /// <param name="typeTagName">
        /// The JSON property name for <see cref="StructureValue.TypeTag"/> values. Default is "_typeTag."
        /// </param>
        public MappedJsonFormatter(string? typeTagName = DefaultTypeTagName) : base(typeTagName)
        {
        }

        /// <summary>
        /// The collection of delegates used to select and/or build properties for each log event.
        /// </summary>
        /// <remarks>
        /// Use <see cref="AddStandardMappings"/> to populate with default mappings.
        /// </remarks>
        public IList<Func<LogEvent, LogEventProperty>> PropertyMappings { get; }
            = new List<Func<LogEvent, LogEventProperty>>();

        /// <summary>
        /// Adds standard mappings for timestamp, level, message, exception, and/or properties to <see cref="PropertyMappings"/>.
        /// </summary>
        /// <param name="timestampName">The JSON property name for the timestamp, or <see langword="null"/> to skip.</param>
        /// <param name="levelName">The JSON property name for the level, or <see langword="null"/> to skip.</param>
        /// <param name="messageName">The JSON property name for the message, or <see langword="null"/> to skip.</param>
        /// <param name="exceptionName">The JSON property name for the exception, or <see langword="null"/> to skip.</param>
        /// <param name="propertiesName">The JSON property name for the properties, or <see langword="null"/> to skip.</param>
        /// <returns>The same formatter instance, for chaining.</returns>
        public MappedJsonFormatter AddStandardMappings(
            string? timestampName = "Timestamp",
            string? levelName = "Level",
            string? messageName = "Message",
            string? exceptionName = "Exception",
            string? propertiesName = "Properties")
        {
            if (messageName != null)
            {
                PropertyMappings.Add(ev => new(messageName, new ScalarValue(ev.RenderMessage())));
            }

            if (timestampName != null)
            {
                PropertyMappings.Add(ev => new(timestampName, new ScalarValue(ev.Timestamp)));
            }

            if (levelName != null)
            {
                PropertyMappings.Add(ev => new(levelName, new ScalarValue(ev.Level)));
            }

            if (exceptionName != null)
            {
                PropertyMappings.Add(ev => new(exceptionName, new ScalarValue(ev.Exception)));
            }

            if (propertiesName != null)
            {
                PropertyMappings.Add(ev => new(propertiesName, new StructureValue(MapProperties(ev.Properties))));

                static IEnumerable<LogEventProperty> MapProperties(
                    IEnumerable<KeyValuePair<string, LogEventPropertyValue>> properties)
                {
                    foreach (var (key, value) in properties)
                    {
                        yield return new(key, value);
                    }
                }
            }

            return this;
        }

        /// <inheritdoc />
        public void Format(LogEvent logEvent, TextWriter output)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));
            if (output == null) throw new ArgumentNullException(nameof(output));

            Format(new StructureValue(GetProperties(logEvent)), output);
        }

        IEnumerable<LogEventProperty> GetProperties(LogEvent logEvent)
        {
            foreach (var mapping in PropertyMappings)
            {
                yield return mapping(logEvent);
            }
        }
    }
}
```

**Comment by nblumhardt** [comment]
Thanks for this, Kyle!

Unfortunately the note in the obsoletion message is itself obsolete 😅 - customizable JSON formatting is now pretty much fully supported via `ExpressionTemplate`: https://nblumhardt.com/2021/06/customize-serilog-json-output/

Your `MyMessage` example would look something like:

```csharp
.WriteTo.Console(new ExpressionTemplate(
        "{ {Timestamp: @t, MyMessage: @m, Level: @l, Exception: @x, Properties: @p} }\n"))
```

The `ExpressionTemplate` mechanism covers most cases; there are still some situations where a formatter class will be needed, but those are getting esoteric (and pluggable template functions add another option to the mix). Keen to hear your thoughts.

We'd better fix that obsoletion message, sorry about that!

**Comment by kmcclellan** [comment]
Thanks for the quick reply. That makes a lot of sense actually. I'm used to templates for rendering the message (used by all sinks); it never occurred to me to use another template to format how a sink writes a log event. But yeah, it's actually a great way to express that configuration.

Do you even need to pull in `Expressions` in this case? For just renaming and skipping, seems like the vanilla [`MessageTemplateTextFormatter`](https://github.com/serilog/serilog/blob/13dd8cfc5ee47a841128beaef853b3798464f807/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs#L34) would do the trick...

**Comment by nblumhardt** [comment]
@kmcclellan thanks for the reply! The vanilla formatter could work in some very limited cases, but probably not (it will emit empty strings instead of `null` or eliding a property entirely when no value is present, for example, which makes producing well-formed JSON tough).
