### ISSUE TITLE
Guid Destructure.ByTransforming doesn't work. 

### ISSUE THREAD

**Issue by cdanek** [serilog/serilog#1640]
**Description**
Destructuring `Guid` appears to not work. This may be related to expressions, but unfortunately I can't tell. Apologies in advance is this is unrelated to the core functionality.

**Reproduction**
Create a new C# console app (I used .net 6.0 but do not believe it's relevant). Added Serilog (2.10), Serilog.Sinks.Console (4.0.1), Serilog.Expressions (3.2.1) from NuGet. 

```
using Serilog;
using Serilog.Templates;
using Serilog.Templates.Themes;

string _outputTemplate = "[{@t:HH:mm:ss} {@l:u3}] {@m}\n{@x}";
ExpressionTemplate _consoleExpression = new(_outputTemplate, theme: TemplateTheme.Literate);

Log.Logger = new LoggerConfiguration().
    MinimumLevel.Verbose().
    Destructure.ByTransforming<Guid>(g => g.ShortForm()). 
    WriteTo.Console(formatter: _consoleExpression).
    CreateLogger();

Guid g1 = Guid.NewGuid();
Log.Debug("Guid: {g1}", g1);
Log.Debug("Destructured Guid: {@g1}", g1);

public static class GuidExtensions
{
    public static string ShortForm(this Guid guid)
    {
        if (guid == Guid.Empty)
            return "????????";
        return guid.ToString().Substring(0, 8);
    }
}
```

**Expected behavior**
Expected: Outputted Guid to be destructured and trimmed to 8 characters. 
Observed:
```
[11:37:17 DBG] Guid: 46fa8a9e-4c85-47b5-8046-1a5ead9734b2
[11:37:17 DBG] Destructured Guid: 46fa8a9e-4c85-47b5-8046-1a5ead9734b2
```

**Comment by nblumhardt** [comment]
Thanks for your message. `Guid` is one of the built-in types that Serilog always considers to be scalar: https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/PropertyValueConverter.cs#L45 - unfortunately there isn't a way to override this, but you can plug in an `ILogEventEnricher` and programmatically/conditionally transform the GUID values on their way through the pipeline.

**Comment by cdanek** [comment]
Thank you for your response (and thank you for all the amazing work/content on Serilog).
