### ISSUE TITLE
Log Serilog message to Azure Log stream

### ISSUE THREAD

**Issue by venkateshkuppusamy** [serilog/serilog#1642]
Is there a way to get the serilog message to the azure log stream. I am using a aspnet core function app. Below is my config.

`
{
  "version": "2.0",
    "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.ApplicationInsights","Serilog.Sinks.File" ],
    "MinimumLevel": { // This controls wether to log the trace into app insight or not
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning",
        "Host": "Warning",
        "EIP": "Information", // LogTest is a context to filter logs under SourceContext = "Function.<FunctionName>"
        "Function.*": "Warning"
      }
    },
      "WriteTo": [
        {
          "Name": "Console",
          "Args": {
            "restrictedToMinimumLevel": "Information",
            "outputTemplate": "===> {Timestamp:HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}"
          }
        },
        {
          "Name": "File",
          "Args": {
            "restrictedToMinimumLevel": "Information",
            "path": "C:\\home\\LogFiles\\Application\\Functions\\function\\Function1\\myapp.log",
            "shared": "true",
            "flushToDiskInterval": "0:00:02"
          }
        },
        {
          "Name": "ApplicationInsights",
          "Args": {
            "restrictedToMinimumLevel": "Information",
            "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
          }
        }
      ]
  }
 
}

`

**Comment by silkfire** [comment]
Yes, you can use the `AzureApp` sink: https://github.com/cnelsonakgov/serilog-sinks-azureapp:

```
Log.Logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .WriteTo.AzureApp()
    .CreateLogger();
```

**Comment by nblumhardt** [comment]
Done, thanks @silkfire 👍

**Comment by amigax** [comment]
.AzureApp() does not exist here.
