### ISSUE TITLE
Destructuring should respect ISerializable

### ISSUE THREAD

**Issue by Jehoel** [serilog/serilog#1645]
**Description**

My application throws an `ArgumentOutOfRangeException` where the `.ActualValue` property contains a value of a custom `struct` of mine that has properties that cause Serilog's property-walker to enter into an (almost) infinite loop.

Specifically, it's a custom `struct Date`, with properties like `.Tomorrow`, so Serilog fills my logs with an (almost) infinite destructing of `.ActualValue.Tomorrow.Tomorrow.Tomorrow.Tomorrow...`. Fortunately Serilog has a recursion-depth limit, but I want to fix things properly.

My `struct Date` implements `ISerializable` and has `[Serializable]` applied, this means that when my custom `struct Date` is serialized by Newtonsoft.Json it defers to `Date.GetObjectData` to know what to serialize to JSON, however as Serilog doesn't use Newtonsoft.Json but has its own mini built-in JSON serializer it ends up with the awkward property-walk.

Confounding things, my `struct Date` is in another assembly that does not (and cannot) reference `Serilog.dll` or `Destructurama.Attributed` for `[LogAsScalar]` or `[NotLogged]`.

I know I can use `IDestructuringPolicy` but this means introduces non-local centralization, which is bad (and every project that uses both `struct Date` and Serilog will need to reimplement (or copy+paste) and that's bad for maintenance).

Given that my type _already_ implements `ISerializable` it should be respected by Serilog so I can avoid the aforementioned issues.

### Reproduction 

1. Create a new ASP.NET Core 3.1 project.
2. Configure Serilog with `JsonFormatter`.
3. I'm also using `Serilog.Exceptions`, `Serilog.AspNetCore`, `Serilog.Sinks.File` and `Serilog.Sinks.Console`.
4. Add the `struct Date` below to the project (though in my case it lives in a separate assembly).
5. Add an ASP.NET Core Controller and Action. Inside the action do: `throw new ArgumentOutOfRangeException( paramName: "foobar", actualValue: Date.TodayUtc, message: "test" )`.
6. Run the application and trigger the action.
7. Observe that Serilog saved a 5MB+ sized Json log file that looks like the screenshot below.

#### `struct Date`

```
// This is not my actual Date struct, but should be enough to repro the issue
[Serializable]
struct Date : ISerializable
{
    public Date( Int32 y, Int32 m, Int32 d )
    {
        this.Year = y; this.Month = m; this.Day = d;
    }

    private Date( DateTime dt )
    {
        this.Year = dt.Year; this.Month = dt.Month; this.Day = dt.Day;
    }

    public Int32 Year { get; }
    public Int32 Month { get; }
    public Int32 Day { get; }

    public DateTime AsDateTime => new DateTime( this.Year, this.Month, this.Day );

    public Date AddDays( Int32 n ) => return new Date( this.AsDateTime.AddDays(n) );

    public Date Tomorrow => this.AddDays(1);

    void ISerializable.GetObjectData( SerializationInfo info, StreamingContext context )
    {
        // etc
    }

    public static Date TodayUtc => new Date( DateTime.UtcNow );
}
```

#### Screenshot of huge 5MB JSON log file with a single `LogEvent` in it:

(And that's 5MB _without_ indenting and formatting, otherwise it balloons to 11MB)

![image](https://user-images.githubusercontent.com/1693078/146193805-f5bb2245-e879-405d-b5b2-2ee615bf71fc.png)

**Expected behavior**

I expected Serilog to use a property-value's `ISerializable` implementation instead of trying to serialize it by itself.

**Relevant package, tooling and runtime versions**

* ASP.NET Core 3.1
* `Serilog` - 2.10.0
* `Serilog.AspNetCore` - 4.1.0
* `Serilog.Exceptions` - 8.0.0
* `Serilog.Extensions.Logging` - 3.1.0
* `Serilog.Sinks.Console` - 4.0.1
* `Serilog.Sinks.File` - 5.0.0

**Additional context**

So it isn't actually just `Date.Tomorrow.Tomorrow.Tomorrow` but it's actually recursively  iterating through two different types (`UtcDateTime` and `Date`, however both types correctly implement `ISerializable`) and walking through this path:

* `ArgumentOutOfRangeException.ActualValue` which is a `Date`.
* `Date.get_UtcDateTime` which returns a `UtcDateTime` representation of the `Date`.
* `Date.get_UtcDateTime.get_Date` which returns a `Date`.
* `Date.get_UtcDateTime.get_Date.get_UtcDateTime` - and it repeats at this point.
* `Date.get_UtcDateTime.get_Date.get_UtcDateTime.get_Date` - and so on...

**Comment by nblumhardt** [comment]
Thanks for the note!

Serilog has never targeted `ISerializable` support, so marking this as an enhancement.

It seems rare to find `ISerializable` used in the wild, so I don't think we'd initially jump to include this in Serilog core.

It would be really interesting to see a pluggable `SerializableObjectDestructuringPolicy` implemented out there, though! Building that and getting some use/feedback on it out-of-band would be the first step. If you decide to give it a shot, please let us know!

In your scenario, can you add:

```csharp
    .Destructure.AsScalar<Date>()
```

when your logger is configured?

**Comment by Jehoel** [comment]
@nblumhardt 

Using `Destructure.AsScalar<Date>()` does work, the problem is that doing-so requires _every_ custom type to be listed with `AsScalar<T>`, which isn't really feasible when the types are in external dependencies.

> It would be really interesting to see a pluggable SerializableObjectDestructuringPolicy implemented out there, though! 

It is kinda straightforward though:

```
class SerializableDestructuringPolicy : IDestructuringPolicy
{
	public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue? result)
	{
		if( value is ISerializable serializable )
		{
			result = SerializeISerializableToDictionaryValue( serializable );
			return true;
		}
		else
		{
			result = null;
			return false;
		}
	}
	
	private static DictionaryValue SerializeISerializableToDictionaryValue( ISerializable value )
	{
		var kvps = GetScalarsFromISerializable( value );
		return new DictionaryValue( kvps );
	}
	
	private static IEnumerable< KeyValuePair<ScalarValue,LogEventPropertyValue> > GetScalarsFromISerializable( ISerializable value )
	{
		Type type = value.GetType();
		
		FormatterConverter formatterConverter = new FormatterConverter();
		
		SerializationInfo serializationInfo = new SerializationInfo( type, formatterConverter );
		
		StreamingContext ctx = default;
		
		value.GetObjectData( serializationInfo, ctx );
		
		{
			SerializationInfoEnumerator e = serializationInfo.GetEnumerator();
			while( e.MoveNext() ) // Fun-fact: Both ye olde school IEnumerable and IEnumerator do not extend IDisposable.
			{
				SerializationEntry entry = e.Current;
				if( entry.Value != null )
				{
					if( entry.ObjectType.IsValueType || entry.ObjectType == typeof(String) )
					{
						ScalarValue           key = new ScalarValue( entry.Name );
						LogEventPropertyValue sv  = new ScalarValue( entry.Value );
						yield return KeyValuePair.Create( key, sv );
					}
					else
					{
						throw new NotImplementedException( "Type not supported yet: " + entry.ObjectType.FullName );
					}
				}
			}
		}
	}
}
```

I'm unsure what the best approach is for handling serializable children and reference-types though. Any thoughts?

**Comment by nblumhardt** [comment]
Thanks for the reply! Lots to think about. It'd be somewhat unusual to serialize everything to dictionaries when `StructureValue` is the common Serilog representation of an object - might be one tweak to consider?

> while( e.MoveNext() ) // Fun-fact: Both ye olde school IEnumerable and IEnumerator do not extend IDisposable.

Yeah, trap for the unwary! I'm assuming that you mean a production version of this would require an attempt at a cast, and a `using` or `try`/`finally` block 👍
