### ISSUE TITLE
The link to courses on Pluralsight about Serilog displays Html as text instead of webpage.

### ISSUE THREAD

**Issue by 839998664** [serilog/serilog#1648]
**Description**
The Url to the courses on Pluralsight about serilog does not work. It displays the Html as text instead of the webpage.

**Reproduction**
1. Navigate to https://github.com/serilog/serilog.
2. Scroll down to Getting Help section of the Readme.md file.
3. Click on the Serilog-related Courses on PluralSight link

**Expected behavior**
Should open PluralSight website with search results of courses related to Serilog

**Relevant package, tooling and runtime versions**
Windows 10/Chrome 96.0.4664.110 

**Additional context**

**Comment by bartelink** [comment]
Hm that looks like a short term bug on the PluralSight website which would be worth reporting to them - the URL (`https://www.pluralsight.com/search/?q=serilog`) in the readme is valid and did work but presently yields html as plaintext.

(While I can repro in Chrome on a Mac, If I right click to open in incognito, and/or navigate from https://github.com/serilog/serilog  in a fresh incognito instance also suggests some pretty mangled history/referer parsing)

Doing the search manually:
- yields the same URL: `https://www.pluralsight.com/search?q=serilog`
- yields no results

The fact that PluralSight's website chokes when clicking the link but 'works' when going manually can't (and IMO shouldn't) be fixed this side.

The larger problem is that their search at present is not returning any results; again one would hope and expect they'll fix that in due course.
