### ISSUE TITLE
Provide more context information to SelfLog if a log statement fails

### ISSUE THREAD

**Issue by penenkel** [serilog/serilog#1651]
Consider [this](https://github.com/serilog/serilog-extensions-logging/blob/e25ed7ddfd0c664bd3a7e9cdbeeec6f87ff12964/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L69) line in the `SerilogLogger` implementation. 

As you can see there, if writing the log message fails, the exception is written to the SelfLog. This includes the exception stacktrace.
Unfortunately the stackrace of an exception only ever contains the stack frames between the point where the exception was thrown and the point where it is caught. Usually that is quite sufficient. But in the special case of structured logging the probability that the error was caused by an unsuitable input to the log statement is quite high. Regrettably that piece of information can not currently be gained from the message written to the SelfLog as the exception stacktrace ends when it is caught and written to the SelfLog.

A simple fix would be to manually append the current stacktrace to the message. Like so:
```
SelfLog.WriteLine($"Failed to write event through {typeof(SerilogLogger).Name}: {ex}\n{new System.Diagnostics.StackTrace()}");
```

If I recall correctly there have been other issues which request a more general way to improve the SelfLog capabilities but perhaps this   could be a

**Comment by penenkel** [comment]
@nblumhardt To be honest I don't quite see what the advantage of wrapping it into another exception is I mean, yes, the two stacktrace segements are now clearly separated. But on the other hand the only thing we do with said exception is to print it to string. The naive implementation of simply appending the current stacktrace results in almost the same output:
https://dotnetfiddle.net/ZNaRFr
```
Yada yada: System.NotImplementedException: The method or operation is not implemented.
   at Program.<<Main>$>g__C|0_2()
   at Program.<<Main>$>g__B|0_1()
   at Program.<<Main>$>g__B|0_1()
   at Program.<<Main>$>g__A|0_0()
   at Program.<Main>$(String[] args)

Yada yada: System.Exception: Failed
 ---> System.NotImplementedException: The method or operation is not implemented.
   at Program.<<Main>$>g__C|0_2()
   at Program.<<Main>$>g__B|0_1()
   --- End of inner exception stack trace ---
   at Program.<<Main>$>g__B|0_1()
   at Program.<<Main>$>g__A|0_0()
   at Program.<Main>$(String[] args)
--- End of stack trace from previous location ---
```

I would argue that having to nested exceptions is further from the "truth" than simply elongating the stacktrace. What additional message/information does the wrapping exception provide? Combined with the mentioned .NET5 requirement necessitating an other workaround ... why bother?

**Comment by nblumhardt** [comment]
Hmm, yes, you're probably right, there. Shall we get a PR going, in this repo, to push it along a bit?

**Comment by penenkel** [comment]
Could you confirm, that the location I mentioned above is the equivalent place to where I added it in serilog-extensions-logging?https://github.com/serilog/serilog/blob/1aabe1d6bde10382233fb2a50e0e2c6e0c9b8287/src/Serilog/Core/Logger.cs#L406

The "native" Serilog logger is built slightly different and I am not totally sure if I am in the correct place there.

**Comment by nblumhardt** [comment]
Most likely no; I think:

https://github.com/serilog/serilog/blob/1aabe1d6bde10382233fb2a50e0e2c6e0c9b8287/src/Serilog/Capturing/PropertyValueConverter.cs#L360

is closer. It needs a bit of experimentation and testing, though - a list of specific inputs we really care about capturing call site stack traces for should flush out any that the above misses.

**Comment by nblumhardt** [comment]
Closing this one as stale; although there are some nice opportunities here, I don't think changes to `SelfLog` are on the current roadmap. Thanks again for all of the input!
