### ISSUE TITLE
SourceContext is empty for top-level statements

### ISSUE THREAD

**Issue by cremor** [serilog/serilog#1662]
**Description**
The `{SourceContext}` logging property is empty for logs that are done in top-level statements.

**Reproduction**
1. Create a new .NET 6 console or web app (.NET 6 now uses top-level statements in Program.cs by default in those 2 project templates)
2. Add and configure Serilog.
3. Add `{SourceContext}` to the outputTemplate.
4. Log something in Program.cs

**Expected behavior**
`{SourceContext}` should be replaced by the string "Program".

**Relevant package, tooling and runtime versions**
Serilog 2.10.0
.NET 6
Windows

**Additional context**
The correct class name "Program" (without any namespace) can be found by executing this in a top-level statement:

```cs
string fullName = new StackFrame().GetMethod().DeclaringType.FullName;
```

**Comment by nblumhardt** [comment]
`SourceContext` is never derived automatically from the logging location; try out `Log.ForContext()` if you want to tag logs with a typed (or named) context explicitly. HTH!

**Comment by cremor** [comment]
@nblumhardt That works, thanks! And sorry for the invalid issue, I'm still new to Serilog.

One question though: Why do I need to explicitly call `ForContext()` when logging directly with Serilog, but not when logging via `Microsoft.Extensions.Logging.ILogger<T>`?

**Comment by bartelink** [comment]
Technical answer: The DI wiring logic triggers application of `ForContext(typeof(T)` via one of the support packages

(IME as you get deeper into Structured Logging, you tend to end up structuring messages such that the SourceContext is not as critical as it historically has been)
