### ISSUE TITLE
ILogger instances from `Serilog.Log.ForContext` before configuration never log anything and this is a gotcha, especially for log4net users

### ISSUE THREAD

**Issue by loop-evgeny** [serilog/serilog#1665]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when... I migrate from log4net to Serilog and I get no logs from *some* classes, while for other classes it works, and it's not obvious why.

In log4net I had code like this:

```
        private static readonly ILog Logger = LogManager.GetLogger(typeof(Program));

        private static void Main(string[] args)
        {
            Logger.Info("Before configuration - this is not logged, as expected");
            BasicConfigurator.Configure();
            Logger.Info("After configuration - this is logged, now that logging has been configured");
```

So I try to do the same thing in Serilog:

```
        private static readonly Serilog.ILogger Logger = Serilog.Log.ForContext(typeof(Program));

        private static void Main(string[] args)
        {
            Logger.Information("Before configuration - this is not logged");

            var loggerConfig = new LoggerConfiguration().MinimumLevel.Information().WriteTo.Console();
            Serilog.Log.Logger = loggerConfig.CreateLogger();

            // The static Logger field is already set to a Serilog.Core.Pipeline.SilentLogger at this point
            Logger.Information("After configuration - this is still not logged");

            Serilog.Log.Logger.Information("(but this is logged)");
```

So ILogger instances obtained from `Serilog.Log.ForContext` before configuration do not log anything and it's not immediately clear why, while in log4net this works.

**Describe the solution you'd like**
Loggers obtained from Serilog.Log before configuration still use the configuration.

How exactly that would be implemented is hard to say - I suppose instead of just a SilentLogger they could get a wrapper class with a reference back to `Serilog.Log.Logger`, so they can use the current configuration.

**Describe alternatives you've considered**

Make `Logger` a property instead:

```
       private static Serilog.ILogger Logger => Serilog.Log.ForContext(typeof(Program));
```

This works, but then I have to either do that everywhere, which may affect performance (I have not tested it) or figure out which classes are loaded before logging is configured and do it only for those, which is still quite a "gotcha".

**Comment by nblumhardt** [comment]
Thanks for the feedback! Probably not something we will be able to make major changes for, but do check out `CreateBootstrapLogger()` in _Serilog.Extensions.Hosting_ - its purpose is to implement a reconfigurable logger that has the properties you're looking for.

**Comment by loop-evgeny** [comment]
Thanks a lot! I found [your blog post](https://nblumhardt.com/2020/10/bootstrap-logger/) about it, which talks about how to do this for an ASP.NET application, but I need it to also work in a regular console application. I did something like this:

```
public static class MainHelper
{
    private static readonly ReloadableLogger BootstrapLogger = new LoggerConfiguration().WriteTo.Console().CreateBootstrapLogger();
    
    public static ILogger GetLogger(Type source) => BootstrapLogger.ForContext(source);
    
    public static void InitializeLogging()
    {
        IConfiguration config = ... // read config for logging to file, etc.
        LoggerConfiguration loggerConfig = new LoggerConfiguration().ReadFrom.Configuration(config);
    
        Serilog.Log.Logger = BootstrapLogger; // Have to use BootstrapLogger here because only 1 logger can be created from a LoggerConfiguration
        BootstrapLogger.Reload(_ => loggerConfig); // Apply this configuration to any loggers already obtained from MainHelper.GetLogger()
        AppDomain.CurrentDomain.ProcessExit += (sender, args) => Serilog.Log.CloseAndFlush();
    }
}

public class Program
{
    private static readonly Serilog.ILogger Logger = MainHelper.GetLogger(System.Reflection.MethodBase.GetCurrentMethod()!.DeclaringType!);

    public static void Main(string[] args)
    {
        Logger.Warning("This logs to console only");
        MainHelper.InitializeLogging();
        Logger.Warning("Now it logs to a file as well, as configured");
    }
}
```

This is much better, but some issues remain:

1) I still need to make sure to call my `MainHelper.GetLogger` method and not `Serilog.Log.ForContext` in any classes whose static constructors may run before logging is configured. That's fairly obvious for the type containing the Main() method, but other types might get loaded early as well. If could use it everywhere to be safe, but then I would need to reference an additional NuGet package everywhere, rather than only in entry assemblies as I'm currently doing.
2) I have to set `Serilog.Log.Logger` to the bootstrap logger even after logging is configured, which means that all loggers from now on will go via the bootstrap logger class. Hopefully the overhead of it is negligible, but it would be nice to avoid that and set `Serilog.Log.Logger = loggerConfig.CreateLogger();` while also updating the `BootstrapLogger`. That throws an exception, though: CreateLogger can only be called once per LoggerConfiguration object.

**Comment by nblumhardt** [comment]
On (2), I think you can reorder things very slightly and use:

```csharp
BootstrapLogger.Reload(_ => loggerConfig); 
Serilog.Log.Logger = BootstrapLogger.Freeze();
```

which will eliminate any overhead for loggers created from that point onward.

On (1), in practice, if you set `Log.Logger` on the very first line of `Main()` it's enough to beat most other static initialization including field initializers in other types.

Since `Main()` is usually a tiny method without much of a runtime role to play, I tend to use `Log.X()` without worrying about `ForContext()`, but you might also just assign a local `var logger = Log.ForContext(typeof(Program))` in there somewhere early, and use that.

HTH,
Nick

**Comment by loop-evgeny** [comment]
Yes, that works, thanks a lot for your help!

Log.Logger is not set on the first line of Main because that's done in a common method that's called from the static constructor, but in practice I haven't yet found any types that are not logging because they were initialized too early, so it's probably fine, as you say.
