### ISSUE TITLE
Get LoggerConfiguration without modifying LoggerSinkConfiguration

### ISSUE THREAD

**Issue by pikausp** [serilog/serilog#1670]
**Is your feature request related to a problem? Please describe.**
I have an extension method that conditionally adds a sink to the configuration and right now to match the `WriteTo` pattern I have to pollute the configuration should the logger not be enabled. The extension method looks at the presence of an environment variable and if present adds an appropriate sink to the bootstrap logger.

```csharp
public static LoggerConfiguration SeqFromEnvironment( this LoggerSinkConfiguration configuration ) {
    var seqUrl = Environment.GetEnvironmentVariable("SEQ_URL");
    if( string.IsNullOrWhiteSpace(seqUrl) ) {
        return configuration.Conditional(e => false, cs => { });
    }

    var seqApiKey = Environment.GetEnvironmentVariable("SEQ_API_KEY");

    return configuration.Seq(seqUrl, apiKey: seqApiKey);
}
```

**Describe the solution you'd like**
For `LoggerSinkConfiguration` to have a method/property which returns the `LoggerConfiguration` it stores as a reference.

**Describe alternatives you've considered**
Right now I'm using a static false conditional
```
return configuration.Conditional(e => false, cs => { });
```

**Comment by nblumhardt** [comment]
Thanks for the note. The intention of the API here is that the caller would only call your configuration method if the sink should be enabled (minimizing the magic behind configuration methods - if it looks like the configuration writes to a sink, it'll write to the sink).

But... there is a slightly hacky workaround if you really want to hide the conditional logic in the `WriteTo` call:

```csharp
        return LoggerSinkConfiguration.Wrap(configuration, s => s, wt => { }, LevelAlias.Minimum, null);
```

I.e. construct a wrapped sink, but don't wrap anything.

https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerSinkConfiguration.cs#L246

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think this one falls in the very large category of things it would be reasonable to do, but if we do all of them would lead to bloat, so I don't think we'd add this right now, anyway 👍 Thanks for the feedback though!

**Comment by luboid** [comment]
Hi @nblumhardt 
Is that can be used as a safer variant of your proposal, it doesn't seem so hacky

```c#
        if (!cfg.Enabled)
        {
            return loggerAuditSinkConfiguration.Sink(NullSink.Instance, restrictedToMinimumLevel: LevelAlias.Off);
        }
```

```c#
public class NullSink : ILogEventSink
{
    public static readonly ILogEventSink Instance { get; } = new NullSink();

    public void Emit(LogEvent logEvent)
    {
        //Intentionally we do not log anything
    }
}
```
