### ISSUE TITLE
[Docs] Features of Serilog when used with Blazor

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog#1671]
I followed the advice and asked first on [StackOverflow](https://stackoverflow.com/q/72073438), but of course it was closed ... because... StackOverflow moderators. (And there's no "Discussions" tab here.)

**Is your feature request related to a problem? Please describe.**
Serilog supports blazor. Many projects and sample apps and templates use it.

But it's important to keep boat to a minimum for wasm. I'm wondering what features serilog provides on the client that are better/extra than already provided by the native logger?

Much effort went into making serilog compatible/usable with blazor - so I'm very curious what it offers. We just need simple  guidance/advice in what scenarios it is useful.

**Describe the solution you'd like**
A note in the docs mentioning the above.

**Comment by nblumhardt** [comment]
Hi! Blazor is no different from other client platforms in this regard. Compared with MEL, Serilog provides more options for enrichment, more sinks/easier construction of custom sinks, `@` support for capturing structured data, more options for capturing, filtering, formatting. There's nothing specific to Blazor (though the [`BrowserConsole` sink](https://github.com/serilog/serilog-sinks-browserconsole) really is pretty nice :-)).

You might also benefit from having a consistent logging API between client and server, if you're using Serilog server-side.

Whether you should use Serilog or not comes down to the type and complexity of the project you're building, and your own preferences. Good luck with it!

**Comment by lonix1** [comment]
I'm already using serilog on the server side, I can't imagine writing code without it, it's great!

I want to be sure I understand. The reasons to use serilog client side are 1) feature/dev experience parity with server side, and 2) that special browser console sink.

I read somewhere there's a way to pass log messages from the browser to the server (to be stored in a db, etc.), but maybe that was some third-party thing, it's not built into serilog itself?

**Comment by nblumhardt** [comment]
Hi! The pass-logs-to-the-server thing is [this sample](https://github.com/nblumhardt/serilog-sinks-browserhttp/#server-side-relay-for-aspnet-core).

**Comment by lonix1** [comment]
That is really useful, thanks! I think I'll use in on the client after all. Thanks @nblumhardt for maintaining this incredible library.

(I've made a link from that [StackOverflow question](https://stackoverflow.com/q/72073438) to this issue so others will find it - your advice was very helpful.)
