### ISSUE TITLE
Review requested: IDestructuringPolicy that serializes to JsonDocument using user-supplied settings and uses structure from that document

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog#1675]
There are no good solutions for destructuring F# types. ([Destructurama.FSharp](https://github.com/destructurama/fsharp) doesn't work well and seems to not be actively maintained.) In trying to come up with a good solution that caters to everyone's desires for structure (particularly for F# discriminated unions, which can be structured in many different ways), I figured I could make something that lets me piggy-back on the excellent [FSharp.SystemTextJson](https://github.com/Tarmil/FSharp.SystemTextJson) which has lots of options.

To make it as general as possible, I therefore created an `IDestructuringPolicy` with no dependencies other than Serilog and System.Text.Json (available out of the box in modern target frameworks) that serializes to `JsonDocument` using user-supplied standard serialization options and uses the structure from that document.

I may publish this, but before that I am hoping that someone more knowledgeable about Serilog internals, structured logging, etc. can just quickly review the code below and look for any obvious issues (correctness relating to the Serilog API, obvious performance issues, etc). The code is F#, but if I publish I'll rewrite in C# to avoid the dependency on FSharp.Core (since this is unrelated to F#).

```f#
open System.Text.Json
open Serilog.Core
open Serilog.Events

type FromSerializedJsonDestructuringPolicy(options: JsonSerializerOptions) =

  new() = FromSerializedJsonDestructuringPolicy(JsonSerializerOptions())

  interface IDestructuringPolicy with
    member _.TryDestructure(value, propertyValueFactory, result) =
      let doc = JsonSerializer.SerializeToDocument(value, options)

      let rec destructure (el: JsonElement) : LogEventPropertyValue =
        match el.ValueKind with
        | JsonValueKind.Undefined ->
            // TODO: Fail silently? AFAIK this should never happen.
            failwith "JsonValueKind.Undefined not supported"

        | JsonValueKind.Object ->
            let properties = ResizeArray()
            use mutable e = el.EnumerateObject()
            while e.MoveNext() do
              let value = destructure e.Current.Value
              properties.Add(LogEventProperty(e.Current.Name, value))
            StructureValue(properties)

        | JsonValueKind.Array ->
            let values = ResizeArray()
            use mutable e = el.EnumerateArray()
            while e.MoveNext() do
              values.Add(destructure e.Current)
            SequenceValue(values)

        | JsonValueKind.String -> propertyValueFactory.CreatePropertyValue(el.GetString(), false)

        | JsonValueKind.Number -> propertyValueFactory.CreatePropertyValue(el.GetDecimal(), false)

        | JsonValueKind.True -> propertyValueFactory.CreatePropertyValue(true, false)

        | JsonValueKind.False -> propertyValueFactory.CreatePropertyValue(false, false)

        | JsonValueKind.Null -> propertyValueFactory.CreatePropertyValue(null, false)

        | kind ->
            // TODO: Fail silently? AFAIK this should never happen.
            failwith $"Invalid {nameof JsonValueKind} value: %A{kind}"

      result <- destructure doc.RootElement
      true
```

**Comment by nblumhardt** [comment]
Unfortunately I wasn't able to add much to this - hopefully you made some progress on it! Closing a stale now, but good luck, and please send an update if this ships/has shipped anywhere :-)

**Comment by cmeeren** [comment]
I vaguely remember making this, but I can't remember more, so apparently I have abandoned it a while ago for some reason. Not sure what that was for this specifically, but it might simply be that I abandoned destructuring generally. It ultimately gave me no added value over just logging serialized objects.
