### ISSUE TITLE
Replacement library for Serliog.Sinks.AzureQueueStorage

### ISSUE THREAD

**Issue by jimmytricks** [serilog/serilog#1676]
**Is your feature request related to a problem? Please describe.**
Hi folks,

We have been using the sink created for AzureQueue storage from [this nuget package](https://www.nuget.org/packages/Serilog.Sinks.AzureQueueStorage).

However the github repo no longer exists and it uses the deprecated WindowsAzure.Storage package, so we've recreated it using Azure.Storage.Queues, so you may want to [list the Serilog.Sinks.AzureQueueStoragev2 package](https://www.nuget.org/packages/Serilog.Sinks.AzureQueueStoragev2/), under your sinks page instead of the no longer maintained package

Cheers!

**Comment by nblumhardt** [comment]
Done, thanks 👍
