### ISSUE TITLE
Requestid performance is inconsistent

### ISSUE THREAD

**Issue by SpringHgui** [serilog/serilog#1677]
```
Serilog.AspNetCore 6.0.0-dev-00265
Serilog 2.11.0
```

temp：`[{Timestamp:HH:mm:ss} {RequestId} {Level:u3}] {Message:lj}{NewLine}{Exception}`

## My situation：
RequestId performance is inconsistent

***Local environment***：RequestId performance like `0HMHJP0IGCO99:00000002`
***Production environment***：RequestId performance like `80000cca-0000-d600-b63f-84710c7967bb`

**Comment by nblumhardt** [comment]
Thanks for the report! The request id doesn't come from this package (or from Serilog at all), it's set by the ASP.NET Core hosting infrastructure.

My guess is that you might be deploying to Kestrel locally, and something else (HTTP.sys?) in prod.

Closing as it's not under the control of this project, but thanks all the same 👍
