### ISSUE TITLE
Is it able to write to different files by ByIncludingOnly?

### ISSUE THREAD

**Issue by bthulu** [serilog/serilog#1681]
**Is your feature request related to a problem? Please describe.**
i have some strategies, each has a name and a log like `Log.ForContext("Strategy", name)`.
i want each strategy write to a separate file, such as LoadStrategy write to LoadStrategy.log, UnloadStrategy write to UnloadStrategy.log.
and some of the strategies is generated by reflect at runtime, so i can't hardcode all the strategy log files.
i expect it will work below, but unfortunately {Strategy} is not replaced by the value in `Log.ForContext("Strategy", name)`.
is there anything exists to do this?
```
WriteTo.Logger(lc => lc.Filter.ByIncludingOnly(e => 
    e.Properties.ContainsKey("Strategy")).WriteTo.File("logs/{Strategy}.log"))
```

**Comment by bartelink** [comment]
My wild guess is that `Serilog.Sinks.Map` addresses your need.

Best to log this on stackoverflow.com, paste a link here and close - anyone that monitors this issues list (which is limited to bugs and PRs, not for questions) will see the question there.
