### ISSUE TITLE
PropertyEnricher has not been updated for nullable reference types

### ISSUE THREAD

**Issue by taspeotis** [serilog/serilog#1686]
Hi team,

For your consideration: some methods for manipulating the `LogContext` worked previously with `null` values but now the nullable reference types disallow it. This occurs with 2.11.0.

[PropertyEnricher.cs](https://github.com/serilog/serilog/blob/697a23189e3068bfe0da1460a2676913239d2757/src/Serilog/Core/Enrichers/PropertyEnricher.cs#L15) had `#nullable enable` added to it, but `value` and `_value` were not changed from `object` to `object?`.

The documentation tells us that it is not an exception to pass `null` for `value`, only `name`:

https://github.com/serilog/serilog/blob/697a23189e3068bfe0da1460a2676913239d2757/src/Serilog/Core/Enrichers/PropertyEnricher.cs#L40-L41

Ultimately `_value` is used with `propertyFactory.CreateProperty(_name, _value, _destructureObjects);` which seems to tolerate `null` values:

https://github.com/serilog/serilog/blob/e1cdad57d96dc1d5eb2c1077a2d918965e82488d/src/Serilog/Capturing/PropertyValueConverter.cs#L94

Upgrading Serilog causes compile errors were there previously were none.

**Comment by nblumhardt** [comment]
Thanks for letting us know, @taspeotis - we'll fix this up! 👍

**Comment by nblumhardt** [comment]
Sorry @taspeotis - yes, absolutely! 👍

**Comment by taspeotis** [comment]
Thank you @nblumhardt. I did intend to send a PR it was just a bit far down my todo list.

**Comment by nblumhardt** [comment]
👍 I'm hoping to get a 2.12 release of Serilog together in the next week or two, so wanted to make sure this was in :-)

**Comment by sungam3r** [comment]
What does 2.12 mean? New versioning?

**Comment by nblumhardt** [comment]
2.12.0 is the next minor version I think @sungam3r - current release on NuGet is 2.11.0.

**Comment by sungam3r** [comment]
🤦‍♂️ of course...
