### ISSUE TITLE
Serilog sink for Maui (android, ios ...)

### ISSUE THREAD

**Issue by tranb3r** [serilog/serilog#1692]
A Serilog sink for Xamarin exists ([Serilog.Sinks.Xamarin](https://nuget.org/packages/serilog.sinks.Xamarin)).
However it does not work with a Maui application.

Could you please make the Xamarin sink compatible with Maui, or provide a new sink for Maui ?

Thank you.

**Comment by tranb3r** [comment]
Serilog.Sinks.Xamarin has been migrated to maui.
https://www.nuget.org/packages/Serilog.Sinks.Xamarin/1.0.0-dev-00104-fd287b7

**Comment by Moes81** [comment]
The existing version 1.0.0 is not compatible with .net7. So, no help here.
