### ISSUE TITLE
Azure CosmosDb Replacement/Addition for Unmaintained Library

### ISSUE THREAD

**Issue by tghamm** [serilog/serilog#1693]
I would like to propose an alternative NuGet package that replaces the current Azure CosmosDb sink for serilog.  The current owner has seemingly left the repo abandoned after I made several enhancements, and I'd like to either add or replace the listed package.  Would this be possible?  I am an active user with long maintained and active projects, and I contributed much of the code to the current implementation, so a fork would be fairly natural.  Would this be supported by the serilog maintainers in one form or another?  There are outstanding enhancements that could be merged into a new package, but it really only makes sense with some visibility.

If so, I can provide an updated package within a couple of days and amend this issue with the relevant items.

**Comment by nblumhardt** [comment]
Hi @tghamm - this isn't something the core Serilog project has anything to do with, unfortunately, so I can't really answer your question usefully. If you are able to move forward on your own then I'm sure it'll be appreciated by others with the same needs. Good luck with it!

**Comment by tghamm** [comment]
@nblumhardt Thank you for the response.  To clarify, I simply meant, if I were to publish my own fork with enhancements that is maintained, could it be listed in the serilog wiki for added visibility?

Thanks again for your time!

**Comment by nblumhardt** [comment]
Yes, that's fine, thanks @tghamm 👍

**Comment by tghamm** [comment]
@nblumhardt Thanks, I've done the necessary work to fork the library and create my own maintained package that pulls in some outstanding enhancements.  Details below.  Let me know if you need anything else from me to get it added to the wiki!

Name: Serilog.Sinks.AzCosmosDb (v.3.0.0)
Github: [https://github.com/tghamm/serilog-sinks-azcosmosdb](https://github.com/tghamm/serilog-sinks-azcosmosdb)
Nuget Package: [https://www.nuget.org/packages/Serilog.Sinks.AzCosmosDB](https://www.nuget.org/packages/Serilog.Sinks.AzCosmosDB)

Thanks again for your time!

**Comment by cocowalla** [comment]
@tghamm The other CosmosDB sink was last updated 4 months ago, which doesn't sound like it's unmaintained? I see you asked if you could get contributer rights on that repo... but that was literally just yesterday.

I don't use CosmosDB, so it has little bearing on myself, but where possible it would be preferable not to fragment the ecosystem; could your changes be a PR to the original sink, rather than creating a new NuGet package? I understand it can be frustrating when maintainers don't respond as quickly as you'd like, but it might be worth giving them a bit more time?

**Comment by tghamm** [comment]
Hi @cocowalla that was actually a month ago, not yesterday :)  The maintainer has not responded to any messages or had any activity since February.  I'm ok waiting a bit longer if that's your preference, but 1 day certainly wasn't my timeline if that was your concern.  I also have outstanding PR's to the original Sink that are even older, they haven't been touched, which is what prompted me to ask to be a maintainer a month ago.

**Comment by cocowalla** [comment]
@tghamm thanks for adding some context I was missing and pointing out my silly mistake with the date (oops!) - I retract my previous comment, it sounds like you're doing the right thing 👍

**Comment by YipingRuan** [comment]
@tghamm 
Will `CosmosDb sink` forced to include the `Json.NET`?

**Comment by tghamm** [comment]
@YipingRuan right now because it's largely an enhanced port, it does, but I could break it out to use either that or `System.Text.Json` pretty easily/modularly if that would be helpful.

**Comment by YipingRuan** [comment]
@tghamm 

Ping me if you think I can contribute in anyway.

**Comment by nblumhardt** [comment]
Alternative added to the sinks wiki page 👍
