### ISSUE TITLE
Serilog & asmx

### ISSUE THREAD

**Issue by martinRocks** [serilog/serilog#1695]
I can't seem to get serilog to work correctly with a framework 4.8 asmx web api site.

I have only added 2 packages, Serilog v2.11.0 and Serilog.Sinks.File v5.0.0.

In my global.asax.cs file, I have 2 methods.

`private  ILogger _logger;`
`protected void Application_Start(object sender, EventArgs e)`
`{`
`    _logger = new LoggerConfiguration()`
`        .MinimumLevel.Debug()`
`        .WriteTo.File(HttpContext.Current.Server.MapPath("~/logs/log-.log"), rollingInterval: RollingInterval.Day)`
`        .CreateLogger();`
`    _logger.Information("App started !");`
`}`
`protected void Application_End(object sender, EventArgs e)`
{
`    _logger.Debug("In Application_End");`
`}`

And then in my asmx file, I have this.

`public class Dime : WebService`
`{`
   `private readonly ILogger _logger  = Log.ForContext<Dime>();`
`}`

`[WebMethod(Description = "For testing of logging")]`
`  public DateTime TestLogging()`
`  {`
`      _logger.Debug("Writing debug to the logs");`
`      _logger.Information("Writing info to the logs");`
`      _logger.Warning("Writing warning to the logs");`
`      _logger.Error("Writing error to the logs");`
`      _logger.Fatal("Writing fatal to the logs");`
`      return DateTime.Now;`
`  }`

What seems to be happening, is the log file is made, and the value of 'App started !' is there, but nothing else.  I have tried with the loggerConfiguration in the asmx file, but that only writes the log after the application shuts down.  And for every call to the web service, a new empty file is made. What am I doing wrong?

What I think should happen is the log is created with a start value, and every time I call the TestLogging method, 5 new lines are added to the file until the application is shutdown and the then end value will be added to the log.

Also, it seems to work fine with the log created in the asmx file while debugging the application, however, when on IIS, it works like above.

**Comment by cocowalla** [comment]
When you first create the logger, you want to assign the logger to the _global_ logger, e.g.

```c#
protected void Application_Start(object sender, EventArgs e)
{
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .WriteTo.File(HttpContext.Current.Server.MapPath("~/logs/log-.log"), rollingInterval: RollingInterval.Day)
        .CreateLogger();
        
    Log.Information("App started !");
}

protected void Application_End(object sender, EventArgs e)
{
    Log.Debug("In Application_End");
}
```

Then when you go to create a logger elsewhere, such as in your `Dime` class, it will be created using the correct configuration.

**Comment by martinRocks** [comment]
OMG, thank you so very much!!!!  I don't why there aren't examples that I could find, but this did the trick.
