### ISSUE TITLE
Serilog.Sinks.AzureDataExplorer link

### ISSUE THREAD

**Issue by saguiitay** [serilog/serilog#1696]
Please add link to [Serilog.Sinks.AzureDataExplorer](https://github.com/saguiitay/serilog-sinks-azuredataexplorer) to the list of supported Sinks

**Comment by augustoproiete** [comment]
Thanks @saguiitay. I've added it to the [list of available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks).
