### ISSUE TITLE
Serilog can cause app to crash - should defend against this 'at all costs'

### ISSUE THREAD

**Issue by IanMercer** [serilog/serilog#171]
I reported a separate issue where Serilog is throwing an exception in `PropertyValueConverter .GetProperties` but this is a more meta-issue.

As a logging framework I think Serilog should defend against all internal exceptions and should never crash the application. i.e. the outermost call to `log.Debug`, `log.Information`, ... should `try..catch` and never leak the exception out into the calling code.

Without this, the risk to a server application through inclusion of Serilog is too high.

I would rather miss a line in the log or get a line stating simply that an internal exception occurred than have a customer facing application crash because the logging framework encountered an unexpected situation.

**Comment by tsimbalar** [comment]
Very old issue, but just out of completeness, a page exists in the wiki : https://github.com/serilog/serilog/wiki/Reliability .

It details the philosophy about logging not taking down the application.
