### ISSUE TITLE
Consider removing some target frameworks

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog#1710]
To simplify the conditional code and avoid having to support people on legacy frameworks

My preference would be to remove netstandard1, netstandard1.3, net45 (support ended in 2016), and net46 (support ended in April). 

Add net462 which is still supported. might be worth targeting net461 to avoid the type clashes people have if they consume netstandard2.0 from within 461

Would result in the new min supported versions being

![image](https://user-images.githubusercontent.com/122666/181166903-74fe70e1-bf8c-4bd8-a80f-b0e01d328803.png)

which are all ~5 years old 

Refs:

 * https://en.wikipedia.org/wiki/.NET_Framework_version_history
 * https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#select-net-standard-version

**Comment by nblumhardt** [comment]
I think this is worthwhile for a 3.0; I don't think we'd get a lot of benefit making the change right now. I checked out your PR along these lines, definitely some wins to be had there 👍 

If we were to break backwards compatibility/drop platforms in a 3.0, are there other opportunities (aside from removing deprecated or obsolete APIs) we could jump on? 🤔 May just be something to bake and consider for a while.

**Comment by nblumhardt** [comment]
Having spent a bit of time back in the codebase again ---- I think this is worth cutting a 3.0 for; let's make 2.12 the last of the 2.x series, and drop support for the worst out-of-support frameworks in 3.0 shortly after :+1:

**Comment by SimonCropp** [comment]
@nblumhardt 👍🏻

**Comment by AraHaan** [comment]
I do not think separate targets for net46 are needed because they implement .NET Standard 2.0. When I used to target netstandard2.0 only on my old versions of my packages one was successfully still able to use the code even with .NET Framework.

**Comment by cremor** [comment]
I've posted my thoughts here: https://github.com/serilog/serilog/issues/1820#issuecomment-1532479506

@AraHaan 
> I do not think separate targets for net46 are needed because they implement .NET Standard 2.0.

From Microsoft's [Open-source library guidance](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting):

> CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

**Comment by nblumhardt** [comment]
Closing this in favour of #1820 where we've carried on this discussion.
