### ISSUE TITLE
Color Lines

### ISSUE THREAD

**Issue by scascalespAV** [serilog/serilog#1718]
Hello
IS posible to generate winword or rtf documents and color lines. For example red to errors, yellow to inf, etc...
Thanks

**Comment by nblumhardt** [comment]
Hi, no, this isn't possible today and would be very unlikely to make it into the core (could always try building a community sink for this though)

**Comment by SimonCropp** [comment]
@scascalespAV i have to ask. why would u want this?

**Comment by scascalespAV** [comment]
To see inmediatly how line are errors and how not

**Comment by SimonCropp** [comment]
sorry. why "winword or rtf documents"?

**Comment by scascalespAV** [comment]
Becasuse has colors

**Comment by pmiossec** [comment]
> Because has colors

You'd better use a tail like software that allows highlighting following some patterns.
An example: https://github.com/RolandPheasant/TailBlazer

**Comment by nblumhardt** [comment]
@scascalespAV hopefully some leads/ideas to follow there. It's a bit out of scope for the Serilog core project so I'll close this but good luck and I hope you find something that suits.
