### ISSUE TITLE
Serilog.Sinks.AzureBlobStorage not working in function app when Microsoft.Azure.WebJobs.Extensions.ServiceBus is installed in .net6 project

### ISSUE THREAD

**Issue by msr8939** [serilog/serilog#1727]
Currently we develop a azure function app with .net 6 framework & AzureFunctionsVersion v4 which includes of service bus package Microsoft.Azure.WebJobs.Extensions.ServiceBus (v 5.7), when i try to implement serilog sinks with azure blob storage(v 3.1.3) we observed application itself failed to start (please refer screenshot attached). It is noticed that on removing service bus package from function app logs were successfully created in container
![image](https://user-images.githubusercontent.com/111277564/184793678-62cd29f4-7fa8-4dca-8028-f08eaa323b7c.png)
.

Please find zip file attached of sample function app solution, please user visual studio 2022 &  configure your azure connection string, container name in startup.cs,
[FunctionApp1.zip](https://github.com/serilog/serilog/files/9347774/FunctionApp1.zip)
 try to run it your local and you'll face the error.

**Comment by nblumhardt** [comment]
Thanks for your message; unfortunately this is the wrong repo for this issue; you can find the Serilog.Sinks.AzureBlobStorage project at:

https://github.com/chriswill/serilog-sinks-azureblobstorage

Cheers,
Nick
