### ISSUE TITLE
There is a typo in the Wiki

### ISSUE THREAD

**Issue by MaZe3D** [serilog/serilog#1738]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
There is a Typo in the Wiki entry https://github.com/serilog/serilog/wiki/Formatting-Output
![image](https://user-images.githubusercontent.com/45102464/187187818-1736dfe3-7e66-4dcd-b639-dedc653c9797.png)
The Marked word should be "off" instead of "of"

**Reproduction**
Open the Wiki and read the text https://github.com/serilog/serilog/wiki/Formatting-Output

**Expected behavior**
The word "of" should be "off"

**Relevant package, tooling and runtime versions**
Current Wiki entry (2022-08-29)

**Comment by nblumhardt** [comment]
Fixed, thank you :+1:
