### ISSUE TITLE
Serilog.Enrichers.GlobalLogContext.dll Strong named validation failed

### ISSUE THREAD

**Issue by sra-michaelgold** [serilog/serilog#1743]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
I'm unable to use my ClickOnce application which uses Serilog.Enrichers.GlobalLogContext.dll because the strong name validation fails on this dll when the application is installed.

**Reproduction**
run from VS command prompt:
`C:\Users\me\.nuget\packages\serilog.enrichers.globallogcontext\1.1.0\lib\netstandard2.0>sn -v Serilog.Enrichers.GlobalLogContext.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
`

**Expected behavior**
Strong name validation passes (or assembly is not strong named)

**Relevant package, tooling and runtime versions**
using VS2022

**Comment by augustoproiete** [comment]
Hey @sra-michaelgold this repository is for issues in the core **Serilog** package only. Please open this issue in the correct repository: https://github.com/serilog-contrib/serilog-enrichers-globallogcontext

**Comment by sra-michaelgold** [comment]
apologies, I just realized that.
