### ISSUE TITLE
Conditional level logging

### ISSUE THREAD

**Issue by jovball** [serilog/serilog#1744]
This is somewhat related to #1210.

There are times when I log at a different level depending on the runtime data. I realize this example implies business process that would be better handled in another way but it's easy to understand.

`
if (inventoryLevel >= 10)
{
    Log.Debug("Inventory level: {inventoryLevel}", inventoryLevel);
}
else
{
    Log.Warning("Inventory level: {inventoryLevel}", inventoryLevel);
}
`

It would be nice to have some way to do this in one line, maybe something like this.

`
Log.Debug("Inventory level: {inventoryLevel}", inventoryLevel).ElevateWhen(inventoryLevel < 10, LogEventLevel.Warning);
`

**Comment by nblumhardt** [comment]
```csharp
Log.Write(
    inventoryLevel < 10, LogEventLevel.Warning : LogEventLevel.Debug,
    "Inventory level: {inventoryLevel}", inventoryLevel);
```

Cheers,
Nick

**Comment by jovball** [comment]
I feel both happy and silly. Thanks.

**Comment by nblumhardt** [comment]
You're welcome! :+1:
