### ISSUE TITLE
Collection of LogContext Properties

### ISSUE THREAD

**Issue by likquietly** [serilog/serilog#1748]
How can i get collection of properties current LogContext in ASP.NET Core custom Middleware? 
I PushProperty in Middleware like this: 
```
  var profile = context.Request.Host.Host;
  
  using (LogContext.PushProperty("TestProp", "MyCustomProp"))
  using (LogContext.PushProperty("Profile", profile))
  {
    await _next(context);
  }
```
Then i want to get the whole collection of properties, how can i do that?

**Comment by bartelink** [comment]
The interface is deliberately designed not to surface such information. You can read [the impl](https://github.com/serilog/serilog/blob/c5a5b44daf11d5be8add28b862103d949e1a16aa/src/Serilog/Context/LogContext.cs).

You'll thus need to manage this externally.

**Comment by bartelink** [comment]
Thanks for [posting this on SO](https://stackoverflow.com/questions/73610646/collection-of-logcontext-properties) - that's definitely the best place to get eyes on it - moving my answer there. Can you close this issue please?
