### ISSUE TITLE
An optional installer that installs serilog as a shared framework.

### ISSUE THREAD

**Issue by AraHaan** [serilog/serilog#1753]
**Is your feature request related to a problem? Please describe.**
Let's say for example you own a handful of applications, all of which use serilog and updating the packages would take too long (not to mention the need to rebuild them all) could take months to update simple dependencies (for private projects not on github).

**Describe the solution you'd like**
A feature that will allow one to update serilog in mass for all of their applications in bulk without rebuilding them leveraging the good old "Roll Forward" feature of shared frameworks.

**Describe alternatives you've considered**
``dotnet store`` however the apphost no longer supports (or looks for them) them since .NET 6.

**Additional context**
Why use roll forward and shared frameworks as a distribution option? Shared frameworks was designed for something like this where one can ``FrameworkReference`` serilog and then build and serilog's assembles (unless you do self-contained builds) are not in the application directory (which is a good way to easily patch security problems in things like serilog or it's dependencies) by simply installing the security fixed version of serilog as a shared framework where then it would automatically roll forward. I created such an installer repository but I would like it if I could give it to the serilog people so they can make use of it (and so all of its nuget packages can be pushed to nuget.org).

**Comment by SimonCropp** [comment]
seems like this is not a problem specific to Serilog, and instead should be raised against the nuget repository

**Comment by AraHaan** [comment]
Where is that because I was looking for the perfect place to ask the serilog maintiners if they would be alright if I could transfer what I have on the installers repo I made to them. However the installers install text would need to be updated and the icon can easily be changed to serilog’s icon to replace the default dotnet icon provided by dotnet/arcade. Also the localizations of the changed english text would need to be made as well (because I only know english).

**Comment by SimonCropp** [comment]
u should raise this here https://github.com/NuGet/Home

how people deploy and update serilog.dll is not unique to serilog. and supporting/documenting custom installers should not be in this repo. 

i recommend u close this one

**Comment by nblumhardt** [comment]
Supporting Windows installers and shared frameworks is going to be quite time-consuming, and there's no way we have the bandwidth to assist people with this. It would be great if you can prominently mark this as a community project and not something endorsed or supported by the Serilog maintainers? Thanks!

**Comment by AraHaan** [comment]
I did have plans to automate it all except for tags or if you wanted to do updates to the CI's used .NET SDK to use a specific pinned version (for cases where it would fix CI because of issues where it might fail building).

**Comment by nblumhardt** [comment]
Hope this went well - closing as nothing's moving ahead here.

**Comment by AraHaan** [comment]
I did successfully do such an installer; you guys alright with taking ownership of it as it would be automated entirely?

**Comment by nblumhardt** [comment]
Thanks for the offer @AraHaan, but no, sorry, it's a lot of work to support something like this.
