### ISSUE TITLE
Serilog support for old .Net Frameworks

### ISSUE THREAD

**Issue by pieroviano** [serilog/serilog#1759]
It would be useful to use Serilog in old Frameworks like .Net 3.5 and .Net 4.0

**Comment by SimonCropp** [comment]
i would prefer we drop support for more frameworks https://github.com/serilog/serilog/issues/1710

**Comment by SimonCropp** [comment]
for context. serilog v1 was released 6 years after  .Net 3.5

**Comment by pieroviano** [comment]
OK, thanks.

I'll take my modifications for private use.
Piero

**Comment by SimonCropp** [comment]
@pieroviano i am not an owner of this project. so it is not my decision

**Comment by nblumhardt** [comment]
Thanks for the PR all the same, @pieroviano 👍 

In case it helps - Serilog 1.x still runs on at least .NET 4.0, so if your needs are modest it could also be a viable option.
