### ISSUE TITLE
SeriLog.Sinks.File/SeriLog.Sinks.Async Fails To Log All Data

### ISSUE THREAD

**Issue by Mohammad-Moussa-Haidar** [serilog/serilog#1761]
While Testing SeriLog.Sinks.File/SeriLog.Sinks.Async performance by logging 600k through a for loop, I have noticed that 40% of the data is being Ignored and the performance is not that great comparing to a simple async/await logger implementation I created.  It is worth to mention that the more the buffer size, the more the data be logged.  I currently set the buffer size to 128000, If I increase the value, less data will be ignored and at 1085764, the 600k logs are being completely logged!

Here is the full code at https://github.com/Mohammad-Moussa-Haidar/LoggersComparison

And here are the code snippets which creates and utilize the loggers

Logger setup and utilization

	static async Task Main(string[] args)
	{
		var builder = new ConfigurationBuilder();
		BuildConfig(builder);

		Log.Logger = new LoggerConfiguration()
			.ReadFrom.Configuration(builder.Build())
			.WriteTo.Async(a => a.File("logs/seriLogger.log"), bufferSize: 128000)
			.CreateLogger();          
		
		var host = Host.CreateDefaultBuilder().ConfigureServices((context, services) =>
		{
			services.AddSingleton(Log.Logger);

			services.AddTransient<ILoggerComparison, LoggerComarison>();
			services.AddSingleton<IFileLogger, FileLogger>();

		})
		.UseSerilog()
		.Build();

		var svc = ActivatorUtilities.CreateInstance<LoggerComarison>(host.Services);
		await svc.Compare();
		Log.CloseAndFlush();
	}	

	public class LoggerComarison: ILoggerComparison
	{
		private readonly ILogger<LoggerComarison> _log;
		private readonly IConfiguration _config;
		private readonly IFileLogger _fileLogger;

		public LoggerComarison(ILogger<LoggerComarison> log, IConfiguration config, IFileLogger fileLogger)
		{
			_log = log;
			_config = config;
			_fileLogger = fileLogger;
		}
		private void RunSeriFileLogger()
		{
			_log.LogInformation("Seri Log - Logging Started");

			var stopWatch = Stopwatch.StartNew();
			for (int i = 0; i < _config.GetValue<int>("LoopTimes"); i++)
			{
				_log.LogInformation("Run number {runNumber}", i);
			}
			
			stopWatch.Stop();

			Console.WriteLine($"SeriLog Logger {_config.GetValue<int>("LoopTimes")} in {stopWatch.Elapsed}");

		}

		private async Task RunCustomFileLogger()
		{
			var stopWatch = Stopwatch.StartNew();
			var awitableTasks =new List<Task>();
			awitableTasks.Add(_fileLogger.LogAsync("0000-0000-0000-0000", "Customer Logger - Logging Started", LoggingLevel.INF));

			for (int i = 0; i < _config.GetValue<int>("LoopTimes"); i++)
			{
				awitableTasks.Add(_fileLogger.LogAsync($"{i}", $"Run number {i}", LoggingLevel.INF));
			}
			await Task.WhenAll(awitableTasks);
			await _fileLogger.Flush();
			stopWatch.Stop();
			Console.WriteLine($"Custom Logger {_config.GetValue<int>("LoopTimes")} in {stopWatch.Elapsed}");

		}

		public async Task Compare()
		{
			await RunCustomFileLogger();
			RunSeriFileLogger();
		}

	}

The seriLog Logger never logs the 600k logs,  it only logs up to 400k, see the below image

![image](https://user-images.githubusercontent.com/5898514/197295501-a88f176d-8327-46b4-9994-a83e9780b8d0.png)

The other thing I would like to understand is they the performance is not optimal, a simple async/await implementation I created is considerably faster than SeriLog.Sinks.Async

Here is a comparison for the same number of records (600k)

![image](https://user-images.githubusercontent.com/5898514/197298026-98fbdb59-dcc3-435b-bc4a-42db54e71682.png)

**Comment by nblumhardt** [comment]
Thanks for dropping by!

The performance comparison is meaningless unless the custom file logger has equivalent features to Serilog: message template capturing, a concurrent structured logging pipeline with enrichment, etc. etc..

There's definitely still room to beat Serilog's performance using newer .NET features, but there's not much point comparing performance unless you're matching features. Bottleneck finding is always welcome though, so if you do figure out any specific ways Serilog could improve by all means please do let us know :-)

Just in case it helps you to reach your perf goals - you're using the Serilog file logger in blocking mode, you should [let it buffer](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs#L108) if you're comparing to a buffered implementation. You'll also then need to `CloseAndFlush()` before taking your perf measurements after making that change.

You might need to whittle your test code down to a minimal repro to figure out why you're not seeing all logs despite increasing the buffer size. It's possible there's some problem in the way the async sink works, but there's a lot of code still in your test harness, so it's quite likely once you start simplifying you'll find the problem there. Interested to hear what you find, either way!

Hope this helps,
Nick

**Comment by Mohammad-Moussa-Haidar** [comment]
Thanks @nblumhardt  
Here is a small code that demonstrates the issue, the Issue can be resolved in one of two methods, either set the blockWhenFull attribute to true so when buffer is full the, any further attempted writes are not dropped or by increasing the buffer size.


        static void Main(string[] args)
        {


            Log.Logger = new LoggerConfiguration()
            .WriteTo.Async(a => a.File("logs/seriLogger.log"), bufferSize: 128000)
            .CreateLogger();



            for (int i = 0; i < 600000; i++)
            {
                Log.Information("Run number {runNumber}", i);
            }
            Log.CloseAndFlush();

        }

Even though I disagree with the statement "performance comparison is meaningless" but I agree that seriLog has great and much mature feature comparing to the basic logging that I do, so is there anything I can modify on the above code to have better performance and at the same time get all the data logged with no issues?

**Comment by Mohammad-Moussa-Haidar** [comment]
@nblumhardt Thanks for your reply,

Below is a simple example that demonstrates the issue, where almost 30k entry logs are dropped, the onlyway to workaround this is either by by increasing the buffer size or settings blockWhenFull: true so buffered writes are not dropped when the queue is full, but this adds extra latency. setting buffered to true reduced the number of dropped records as without it, more than 60% of the logs are dropped, it also slightly enhanced the performance.

            Log.Logger = new LoggerConfiguration()
            .WriteTo.Async(a => a.File("logs/seriLogger.log", buffered: true), bufferSize: 64000)
            .CreateLogger();

            for (int i = 0; i < 1200000; i++)
            {
                if(i==1)
                    stopWatch = Stopwatch.StartNew();

                Log.Information("Run number {runNumber}", i);
            }
            Log.CloseAndFlush();
            stopWatch.Stop();
            Console.WriteLine($"SeriLog Logger 600000 in {stopWatch.Elapsed}");

Even though I disagree with your statement that _"performance comparison is meaningless"_ as I am only using the basic logging feature of seriLog but yes, I get your point, so is there anything else I can modify to have better performance and at the same time avoid missing logs?

**Comment by nblumhardt** [comment]
Hi @Mohammad-Moussa-Haidar -

There's always going to be a problem if the log source produces events faster than the sink can emit them. When you're logging in a tight loop, that's always going to be the case - it's much faster to allocate events in memory than it is to write them out to disk.

When this happens there are three possible outcomes -

 * You fill up RAM and eventually OOM
 * You drop events
 * You wait for the sink to catch up

Serilog steers you towards the latter two and gives you the choice which you prefer.

(You might have another option which meets your requirements - obtain a much faster disk 🤔)

In normal applications though:

 * The app actually does something, so rarely if ever will generate logs fast enough to saturate disk
 * The most important performance number is the added latency on the application/logging side, which Serilog.Sinks.Async deals with quite well (on the sink side, only throughput really matters in this case)

Not sure if there's much more I can add but hopefully you find a solution to fit your requirements - all the best with it!

**Comment by Mohammad-Moussa-Haidar** [comment]
Thank you @nblumhardt, I will evaluate the options I have and go with the best. feel free to mark this issue as closed.

Thanks again and best regards,

**Comment by nblumhardt** [comment]
👍 keep us posted! Thanks @Mohammad-Moussa-Haidar
