### ISSUE TITLE
:l format not respected for items in StructureValue

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog#1763]
```c#
var formatter = new Serilog.Sinks.SystemConsole.Output.OutputTemplateRenderer(ConsoleTheme.None, "{Message}", null);
var str = JsonSerializer.Serialize(new { a = 1, b = true }, new JsonSerializerOptions { WriteIndented = true }); // string with new line
var evt = DelegatingSink.GetLogEvent(l => l.Information("{@arg:l}", new { y = str }));
var sw = new StringWriter();
formatter.Format(evt, sw);
var res = sw.ToString();
Console.WriteLine(res);
```

outputs
```
{y="{\r\n  \"a\": 1,\r\n  \"b\": true\r\n}"}
```
(\r\n not expected)

Now let's change `new { y = str }` to just `str`:
```c#
var formatter = new Serilog.Sinks.SystemConsole.Output.OutputTemplateRenderer(ConsoleTheme.None, "{Message}", null);
var str = JsonSerializer.Serialize(new { a = 1, b = true }, new JsonSerializerOptions { WriteIndented = true }); // string with new line
var evt = DelegatingSink.GetLogEvent(l => l.Information("{@arg:l}", y = str));
var sw = new StringWriter();
formatter.Format(evt, sw);
var res = sw.ToString();
Console.WriteLine(res);
```

outputs
```
{
  "a": 1,
  "b": true
}
```
(no \r\n as expected)

The question is how can I archive `:l` format behavior for inner properties of complex objects?

**Comment by nblumhardt** [comment]
Ah sorry I see I slightly misunderstood - it's not so much about the `b` property as the whole object. In this case thought still, `:l` only applies to string literals, rather than structures, and an enricher or formatting function is still going to be needed. HTH!

**Comment by nblumhardt** [comment]
I was thinking along the lines of converting the whole structure to a JSON string, and then using `:l` to format it out through the template. It's not a particularly straightforward thing to implement currently, unfortunately.

**Comment by sungam3r** [comment]
What do you think about new format modifier like `:lr` - _literal recursive_ - the same as `:l` but affects all inner properties ?

**Comment by nblumhardt** [comment]
I think it sounds a bit niche to get that level of support - if you convert the property to a string for output using a Serilog.Expressions plug-in function, then add `:l` to your template (e.g. `{display(mystruct):l}`) you should be able to achieve something close to what you want, here.

**Comment by nblumhardt** [comment]
Closing as stale, hope you found a solution you were happy with
