### ISSUE TITLE
Adding Serilog to docker enabled project cause error when trying to run in docker

### ISSUE THREAD

**Issue by Misiu** [serilog/serilog#1765]
**Description**
What's going wrong?
I've created a simple worker project in VS 2022 Using .NET 7 RC2.
I've enabled docker support.
As soon as I try to debug my project in docker I get below error:

> You must install or update .NET to run this application.
> 
> App: /app/bin/Debug/net7.0/RabbitWorker.dll
> Architecture: x64
> Framework: 'Microsoft.AspNetCore.App', version '7.0.0-rc.2.22476.2' (x64)
> .NET location: /usr/share/dotnet/
> 
> No frameworks were found.
> 
> Learn about framework resolution:
> https://aka.ms/dotnet/app-launch-failed
> 
> To install missing framework, download:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=7.0.0-rc.2.22476.2&arch=x64&rid=debian.11-x64
> 
> 

**Reproduction**
Clone my repo (https://github.com/Misiu/SerilogAndDocker) and try to run in in docker:
![image](https://user-images.githubusercontent.com/1741838/200591835-cb708759-1d2c-4aa1-ac1e-8a94201e5144.png)

**Expected behavior**
Project should work just fine. If I remove Serilog nuget packages everything works fine, but I'd like to use Serilog in my project.

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?

.NET 7 RC2

```
<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
<PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
```
**Additional context**
This is a standard background worker template in VS2022 with Docker support added

**Comment by clazarev** [comment]
Hi @Misiu ,
so I tested you solution and found out that the docker file uses wrong container image
it uses
`mcr.microsoft.com/dotnet/runtime:7.0 ` which is just .NET Core runtime, however
your project is ASP.NET Core
and should use
`mcr.microsoft.com/dotnet/aspnet:7.0`
So it is not an issue with Serilog

Here is a good article explaining the difference
https://andrewlock.net/exploring-the-net-core-mcr-docker-files-runtime-vs-aspnet-vs-sdk/

**Comment by Misiu** [comment]
@clazarev thank you for checking and for the response.
I didn't manually add the docker support to my project.
As we have the final release of .NET7, I'll test this again.

**Comment by Misiu** [comment]
I got the exact same output (dockerfile) in VS2022 17.4.3.
So I think that the worker template isn't intended for web-based projects (without required changes)
After editing the dockerfile the project started working!
