### ISSUE TITLE
 the serilog could be  provider the Structured Query for it's output log ?

### ISSUE THREAD

**Issue by sgf** [serilog/serilog#1768]
**Is your feature request related to a problem? Please describe.**
 ---
 the serilog could be  provider the Structured Query for it's output log?

I know that serilog can store logs in a structured way. But it doesn't seem to control how many structures there are. And it's not so smart, for example: add indexes to the properties of Json for structured output.
Well the log output sinks, whether storing Json flat files or databases. I believe serilog is still just storing as strings.

People still cannot conveniently and quickly query and get the log results they want.
That being the case, what is the significance of the structured log storage declared by serilog?
Why does it feel like I'm getting nothing.

**Maybe it only really makes sense to use Elasticsearch or another full-text search database as a backend?**

**Comment by nblumhardt** [comment]
Hi! Thanks for reaching out. What you're asking for is essentially what tools like Elasticsearch or Seq provide. Serilog is just the logger, but if you dig around you should find some suitable structured log search tools connected via sinks.

Closing as this is out of scope of the project, but thanks again for dropping by.

**Comment by sgf** [comment]
> Hi! Thanks for reaching out. What you're asking for is essentially what tools like Elasticsearch or Seq provide. Serilog is just the logger, but if you dig around you should find some suitable structured log search tools connected via sinks.
> 
> Closing as this is out of scope of the project, but thanks again for dropping by.

tks.
