### ISSUE TITLE
Optimize memory allocations

### ISSUE THREAD

**Issue by igor84** [serilog/serilog#1769]
**Is your feature request related to a problem? Please describe.**
I am considering replacing our in house logging solution for Unity3D with Serilog but it allocates 3x more memory for logging a simple string.

**Describe the solution you'd like**
Using a few quick experiments  I found that we could bring the allocations to the same minimal level with these 3 changes:
1. Use foreach over _outputTemplate.TokenArray instead of Tokens IEnumerator in MessageTemplateTextFormatter.Format method so no IEnumerator is allocated.
2. Pool and reuse internally created StringWriters using writer.GetStringBuilder.Clear().
3. Pool and reuse LogEvent instances.

**Additional context**
If you agree this would be useful I could make a pull request. It would be nice if I could use ConcurrentBag<T> for the pools but we would have to sack .netstandard1.0 since it is not supported there.

**Comment by sungam3r** [comment]
👍  I would recommend to split into separate PRs to make changes measurable and use assets from Serilog.PerformanceTests to approve improvements.

**Comment by sungam3r** [comment]
These files are not tests actually, these are benchmarks. Docs here https://github.com/dotnet/BenchmarkDotNet
I see some wrapper around benchmarks - https://github.com/serilog/serilog/blob/dev/test/Serilog.PerformanceTests/Harness.cs#L18

**Comment by igor84** [comment]
I found that I was getting the error that Serilog.snk file could not be found. I had to copy the assets folder to test/Serilog.PerformanceTests/bin/Release/ for benchmarks to start working.

Anyway, for pools implementation should I use `lock` with standard collections or should I remove netstandard1.0 from csproj and use `System.Collections.Concurrent`?

**Comment by nblumhardt** [comment]
Dropping `netstandard1.0` would need to wait for a 3.0 release, but it's possible to conditionally include one implementation or another depending on the target platform.

Dictionaries with locks are often faster than ConcurrentDictionary if the lock isn't contended IIRC, which is generally the case at the formatting/output end of Serilog. The logger/input end is often more highly-contended. Would be interesting to check this out via some benches.

**Comment by sungam3r** [comment]
https://github.com/serilog/serilog/pull/1772#issuecomment-1332819952

**Comment by sungam3r** [comment]
To summarize initial post:

- Use foreach over _outputTemplate.TokenArray instead of Tokens IEnumerator in MessageTemplateTextFormatter.Format method so no IEnumerator is allocated. #1770 
- Pool and reuse internally created StringWriters using writer.GetStringBuilder.Clear(). #1771
- Pool and reuse LogEvent instances. #1788

**Comment by sungam3r** [comment]
Could be closed?

**Comment by igor84** [comment]
I am satisfied with the changes we made so I am closing this ticket.
