### ISSUE TITLE
Entry not logged when 'message' is used as property name

### ISSUE THREAD

**Issue by user114145** [serilog/serilog#1773]
When using a messageformat in the `ILogger.<Loglevel>(messageTemplate, propertyValue)` family of functions, using '_message_' as propertyname as depicted below will result in the logmessage (quietly) not being processed.

`Log.Warning("User received error: {message}", ErrorMessage);`

(Took me awhile to figure that out XD)

Serilog 2.12.0 on .NET 6.0

**Comment by nblumhardt** [comment]
Hi! I can't repro, can you please share a minimal reproduction? Might be sink-dependent.

![image](https://user-images.githubusercontent.com/342712/205184632-eb9add4f-7ae3-4742-9b7f-b69229846e62.png)

![image](https://user-images.githubusercontent.com/342712/205184644-1a7acf0d-fcfd-4da4-8c8f-06d9d5fa8c5c.png)

**Comment by user114145** [comment]
Thanks for looking into this!
The problem does indeed seem to be with the sink. 
I've notified that project.
