### ISSUE TITLE
Wildcard for minimum level override

### ISSUE THREAD

**Issue by dantheman999301** [serilog/serilog#1786]
**Is your feature request related to a problem? Please describe.**
When using the default `HttpClientClientFactory` you get log messages on the following classes
- `System.Net.Http.HttpClient.<HttpClientName>.LogicalHandler`
- `System.Net.Http.HttpClient.<HttpClientName>.ClientHandler`

These messages are very similar and I'd ideally like to only log the latter of the two.

**Describe the solution you'd like**
I would like to be able to do something similar to the following:
```json
"Serilog": {
    "MinimumLevel": {
      "Override": {
        "System.Net.Http": "Warning"
        "System.Net.Http.HttpClient.*.ClientHandler": "Information"
      }
    }
}
```
This would let me get information logs from the handlers I want but suppress everything else.

For what it's worth this is not a major issue as I have a work around but thought others may have run a similar need.

**Describe alternatives you've considered**
For the time being, I've got around this by removing the `IHttpMessageHandlerBuilderFilter` and replacing it with a custom one where the loggers are renamed to something internal to our application. A bit hacky but does the job.

Another alternative would be to set individual overrides for every `HttpClient` but that is a maintenance nightmare.

**Additional context**
There was a similar feature request here but the use cases are different - https://github.com/serilog/serilog/issues/1500
The filter that sets these up - https://github.com/dotnet/runtime/blob/eb8d5f73a6e6f5ceb9a07674ed7e95fb9c694ecf/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingHttpMessageHandlerBuilderFilter.cs

**Comment by nblumhardt** [comment]
Hi! Thanks for the suggestion. Minimum levels and overrides are a delicate and performance-sensitive area, so these kinds of problems are better solved by adding filters.

I.e. set the minimum level for `System.Net.Http.HttpClient` to allow `Information` though, but use `Filter.ByExcluding(...)` and e.g. [an expression](https://github.com/serilog/serilog-expressions) to exclude `SourceContext like 'System.Net.Http.HttpClient.%.LogicalHandler`.

Closing as this is a few months old, but let me know if I've misunderstood. Thanks!
