### ISSUE TITLE
General Sink question

### ISSUE THREAD

**Issue by LiorBanai** [serilog/serilog#1789]
Hi
I'm writing a custom sink that send event to other application in the same workstation (gRPC) and to a File Sink, and have the following:
If the Logger is disposed there is exception when using emit (if, for example, it forward the event to the file sink). Is there a way inside a sink to know if the logger(underline stream?) is dispose?

**Comment by nblumhardt** [comment]
Hi Lior! Each sink is fully independent, so if your sink completely wraps up a file sink, then the only way the file sink should be disposed is through your sink disposing it when your sink's `Dispose()` method is called in turn.

If you're using `LoggerSinkConfiguration.Wrap()`, the mechanism might be a bit less obvious, but your sink's `Dispose()` method should still be called before that of the wrapped sink when the logging pipeline is disposed.

Let me know if this helps! If not, a bit more illustrative code would be handy.

**Comment by LiorBanai** [comment]
@nblumhardt  Thanks,  I'll check the ```Dispose()``` method

**Comment by LiorBanai** [comment]
@nblumhardt  the sink itself ```ILogEventSink``` does not have  dispose method so no way for the sink to know if the undeline logger is disposed..

**Comment by nblumhardt** [comment]
To add disposal to a sink, you can just implement `IDisposable` on it; to check if a sink is disposable when you don't know its concrete type, you can cast `as IDisposable` and check the result. HTH!

**Comment by LiorBanai** [comment]
@nblumhardt  with the added interface it is indeed enabled me to solve my issue. Thanks!
