### ISSUE TITLE
Support for Serilog.Sink.RedisTimeSeries

### ISSUE THREAD

**Issue by Jeevananthan-23** [serilog/serilog#1790]
It could be great to have the **Serilog Sink** support for RedisTimeSeries, to measure log metrics like Kibana.
Thanks!

**Comment by augustoproiete** [comment]
Hey @Jeevananthan-23 new Serilog sinks are generally developed by the community, so this would depend on someone building a sink for RedisTimeSeries...

Let us know if you ever develop one or if you find one that is useful.
