### ISSUE TITLE
Add hoat reload for adding.updating sink configuration

### ISSUE THREAD

**Issue by Furiphan** [serilog/serilog#1792]
**Is your feature request related to a problem? Please describe.**
Currently, we can't add or update sink configuration from appsettings without restarting the application.

**Describe the solution you'd like**
I would like have the possibility to update Serilog sinks configuration from my appsettings on runtime.

**Comment by sungam3r** [comment]
You can add all needed sinks at startup with log level off and then just switch that log level.

**Comment by augustoproiete** [comment]
@Furiphan You might be interested in this: [Serilog, Change the loglevel at runtime for a specific namespace (> MinimumLevel)](https://stackoverflow.com/a/62074296)
