### ISSUE TITLE
Wiki: "Home" doesn't follow recommendations

### ISSUE THREAD

**Issue by taspeotis** [serilog/serilog#1829]
The [Home page](https://github.com/serilog/serilog/wiki) of the wiki uses a trailing period in its message template.

> ```cs
> var input = new { Latitude = 25, Longitude = 134 };
> var time = 34;
> 
> log.Information("Processed {@SensorInput} in {TimeMS:000} ms.", input, time);
> ```
> ...
> The :000 segment following TimeMS is a standard .NET format string that affects how the property is rendered (not how it is captured). The standard console sink included with Serilog will render the above message as:
> 
> `09:14:22 [Information] Processed { Latitude: 25, Longitude: 134 } in 034 ms.`

The wiki also has [recommendations on how message templates](https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-recommendations) should be written:

> Sentences vs. Fragments - log event messages are fragments, not sentences; for consistency with other libraries that use Serilog, avoid a trailing period/full stop when possible.

The home page probably shouldn't have the trailing period.

I would submit a PR but GitHub doesn't support that for wikis?

**Comment by augustoproiete** [comment]
Thanks @taspeotis. I've updated the wiki removing the trailing period.
