### ISSUE TITLE
Incorrect logging of Dictionary<string, Class> - Missing ending '}'

### ISSUE THREAD

**Issue by omerron** [serilog/serilog#1844]
Hi,

Using Serilog in .NET Core project to log an object with dictionary in it, and it is missing `}` at the end.
Can you please check?

I reproduced the minimum structure that has an issue, using LINQPAD with the below code.

Nuget versions:
**Serilog - 2.12.0
Serilog.Extension.Logging - 3.1.0
Serilog.Settings.Configuration - 3.4.0
Serilog.AspNetCore - 6.1.0**

Output:
`{"Dictionary":{"Key":{}}}` // Console
`[19:22:44 INF] {"Dictionary":{"Key":{}}` // Serilog, missing **}** at the end

```
void Main()
{
	var log = new LoggerConfiguration()
	  .WriteTo.Console()
	  .CreateLogger();
	var res = new ClassWithDictionary
	{
		Dictionary = new Dictionary<string, EmptyClass>
		{
			{
				"Key", new EmptyClass()
			}
		}
	};

	var resultsAsString = JsonConvert.SerializeObject(res);
	
	Console.WriteLine(resultsAsString);
	log.Information(resultsAsString);
}

public class EmptyClass
{
}

public class ClassWithDictionary
{
      public Dictionary<string, EmptyClass> Dictionary { get; set; }
}
```

Some notes:
* It doesn't repro when serializing the dictionary itself (i.e. without new ClassWithDictionary)
* It doesn't repro when I replace `new EmptyClass()` with `null` in the initialization

**Comment by nblumhardt** [comment]
Hi! This is not a bug but rather that the argument to `log.Information()` is a [message template](https://messagetemplate.org), not a plain string. `{{` and `}}` are the escape sequences in that language for single `{` and `}`.

To do what you want you can:

```csharp
log.Information("{Result}", resultAsString);
```

Or if you want to do structured logging, skip the JSON serialization altogether and:

```csharp
log.Information("{@Result}", res);
```

HTH,
Nick

**Comment by bartelink** [comment]
@omerron you simply change your `.Information` call as Nick suggested, adding the template, i.e.: 

> log.Information(resultsAsString);

becomes 

>log.Information("{Result}", resultAsString);

(or the other suggestion)

If your logic is using MEL `.LogInformation`, then it's the same thing - same need for a template argument, same choices about using `@Result` to do the structured logging

**Comment by omerron** [comment]
@bartelink @nblumhardt when using ILogger's LogInformation with ($"Results are: {{@Results}}", res) the response is logged escaped and not as plain JSON.

Is there any option to log it regularily?

And what was recently changed? We used to log all of our objects with interpolated string and without template - and everything worked fine

**Comment by bartelink** [comment]
In general with Serilog, you should never be using the string interpolation (`$`) operator
Perhaps `:lj` might be what you're after, see the formatting wiki https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text
>And what was recently changed? We used to log all of our objects with interpolated string and without template - and everything worked fine
Very little chance anything changed - there's massive usage and you hear about stuff instantly if there's anything even subtly different (this rarely happens though; the maintainers of te core are at this a long time and have skin in the game)
I'd say the likelihood is that you've gotten lucky through some coincidences; the first argument has absolutely always been a message template.
To trap this and other issues, https://marketplace.visualstudio.com/items?itemName=Suchiman.SerilogAnalyzer is fantastic too

**Comment by omerron** [comment]
@bartelink I prefer not to change the format of the entire log itself, it is used by hundreds of services, how can I log the message we discussed before, without changing the format for everyone?

for example:
```
var resultAsJson = JsonConvert.SerializeObject(results);
log.Information($"This is the result: {resultAsJson}");
```

Thanks!

**Comment by bartelink** [comment]
@omerron This is simply contrary to how it works. It cannot be made to work. Don't do it.
Read https://serilog.net/
While there is low level hacking that can be done with message interpolation to unmangle things, thats seriously error prone
Please stop digging and move on ;)

**Comment by sungam3r** [comment]
Agree with @bartelink .

@omerron Think of it as SQL injection. You use a data (string that you want to be logged) as not a data but as a "flow control sequence". This string is interpreted in a special way and under certain conditions (data/config dependant) even _may_ call arbitrary malicious code.

**Comment by omerron** [comment]
@bartelink @sungam3r I am not sure I understand why it doesn't log it correctly.
I just give it a string as parameter, this string happen to contain a serialized JSON in it - why it doesn't log it properly?

**Comment by bartelink** [comment]
The parameter is a `string`, but the format MUST be a message template. Message templates have tokens in them for fields, that open with `{`; the semantic require quoting (by doubling) if you want to use a brace as a literal. Just like for `String.Format` (it has the same semantics, try it).
But seriously, you've been told enough times. Time to read and/or accept.

**Comment by sungam3r** [comment]
> why it doesn't log it properly?

Because the nature of JSON's content **inside** that string parameter contradicts with semantics of that parameter which is used as message **template**, i.e. format string. You cannot safely set any value to this parameter from an unknown or uncontrolled source. Once time again - this is **not** plain text to log, this is message **template** to interpret/parse.

**Comment by omerron** [comment]
thanks
