### ISSUE TITLE
test fail did not break the build

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog#1850]
this pr https://github.com/serilog/serilog/pull/1690 introduced a failing test https://ci.appveyor.com/project/serilog/serilog/builds/46127831

![image](https://user-images.githubusercontent.com/122666/216727437-13dac947-6ff2-4364-a1a9-f0a39b5446a8.png)

but the build did not fail

![image](https://user-images.githubusercontent.com/122666/216727580-b50bb11d-caeb-4619-9c70-77bddd14ed64.png)

need to investigate why

**Comment by sungam3r** [comment]
The same behaviour for my changes in #1845
