### ISSUE TITLE
ILogger.LogInformation write to console has miss some charactor like }

### ISSUE THREAD

**Issue by liugt34** [serilog/serilog#1853]
first i thought it's the bug of ILogger , so i submit an issue to aspnetcore
[dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues/46382)
but when i remove serilog ,it works well, so the issue like this

**Description**
this is the message  

`{"traceIdentifier":"0HMO45HGLUH99:00000003","method":"POST","controller":"SpreadsheetSeal","action":"Add","requestBody":{"input":{"spreadsheetId":"5115faf4-4670-4a4d-821b-97ffd8baa53d","formId":"0be291ec-cb7c-4539-b5c5-a5982a5c17ad","jobId":null,"options":[{"pageNumber":1,"sheetName":"string","cellKey":"string","sealType":0,"left":0.0,"top":0.0,"width":0.0,"height":0.0,"sealId":"fc710e8c-a88d-43c6-81fe-cd2278e0f740","signImageBase64":null,"remark":"string"}]}},"path":"/fullprocess/api/SpreadsheetSeal/Add","query":"","address":{"remoteIP":"::1","realIP":null,"forwardedFor":null,"proxyIP":null},"responseBody":"{\"success\":true,\"code\":0,\"errors\":null}","statusCode":200,"creatorId":"9e1fda21-69db-47b4-ba42-9cd8a4495cc0","creator":"汤姆.刘","creationTime":"2023-02-01T16:15:23.7591442+08:00"}`

**Reproduction**
```

public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Information()
            .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}").Enrich.FromLogContext()
            .WriteTo.Async(lsc => lsc.File($"logs{Path.DirectorySeparatorChar}fs_.log", restrictedToMinimumLevel: LogEventLevel.Warning, rollingInterval: RollingInterval.Hour, outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}"))
            .CreateLogger();

            Log.Information("Start FullProcessApi Server...");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog();
    }
```

**the Controller**

```

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var message = "{\"traceIdentifier\":\"0HMO45HGLUH99:00000003\",\"method\":\"POST\",\"controller\":\"SpreadsheetSeal\",\"action\":\"Add\",\"requestBody\":{\"input\":{\"spreadsheetId\":\"5115faf4-4670-4a4d-821b-97ffd8baa53d\",\"formId\":\"0be291ec-cb7c-4539-b5c5-a5982a5c17ad\",\"jobId\":null,\"options\":[{\"pageNumber\":1,\"sheetName\":\"string\",\"cellKey\":\"string\",\"sealType\":0,\"left\":0.0,\"top\":0.0,\"width\":0.0,\"height\":0.0,\"sealId\":\"fc710e8c-a88d-43c6-81fe-cd2278e0f740\",\"signImageBase64\":null,\"remark\":\"string\"}]}},\"path\":\"/fullprocess/api/SpreadsheetSeal/Add\",\"query\":\"\",\"address\":{\"remoteIP\":\"::1\",\"realIP\":null,\"forwardedFor\":null,\"proxyIP\":null},\"responseBody\":\"{\\\"success\\\":true,\\\"code\\\":0,\\\"errors\\\":null}\",\"statusCode\":200,\"creatorId\":\"9e1fda21-69db-47b4-ba42-9cd8a4495cc0\",\"creator\":\"汤姆.刘\",\"creationTime\":\"2023-02-01T16:15:23.7591442+08:00\"}";

            Console.WriteLine("Console.WriteLine===>" + message);

            _logger.LogInformation("ILogger.LogInformation===>" + message);


            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
```

**Expected behavior**
how can i output the origin message

**Relevant package, tooling and runtime versions**
netcore 5.0.8, netcore 6.0
4.1.0

**Additional context**
no

Use Serilog, output miss }

![image](https://user-images.githubusercontent.com/8056013/216220791-a95d2343-9fae-4201-ab3d-9cd7cd960087.png)

Remove Serilog, output is Ok
![image](https://user-images.githubusercontent.com/8056013/216944884-eee65744-6f9e-41b7-aad0-0e75137a0adb.png)

**Comment by vlm---** [comment]
Same mistake as in #1844, basically don't use values from objects or json in message templates.

**Comment by liugt34** [comment]
@vlm---   thank you!  solve it by next
 
_logger.LogInformation("ILogger.LogInformation===>{@message}", message);
