### ISSUE TITLE
Lifecycle wiki page should document shutdown behavior when using DI

### ISSUE THREAD

**Issue by Timovzl** [serilog/serilog#1854]
The [lifecycle wiki page](https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers) mentions how to handle application shutdown, especially with regards to background processes (such as periodic flushing). However, no mention of this topic is made when it comes to using a DI container.

This leaves me wondering: if my application terminates, _especially_ (though not only) when the shutdown logic writes further log entries, does Serilog have code in place to ensure that a final flush is done?

If such code is in place, it seems worth mentioning. If it is not, then hopefully it can at least be documented, but much more preferably be implemented. In the latter case, I have some experience writing shutdown logic that must run last, and I'm happy to offer suggestions.

**Comment by nblumhardt** [comment]
Hi! DI generally performs shutdown via `IDisposable`, and Serilog's `Logger` (as returned from `CreateLogger()`) implements this interface. The specifics will depend on your DI implementation, but as long as container disposal is the last thing your app does, everything will be flushed as expected.

I've grappled with shutdown hooks across the years on various .NET versions too - it's kind of you to offer to help with this, but it's rather tricky to support and something I think is best left out of scope for this library. Thanks again, though!
