### ISSUE TITLE
UseSerilog support for .net 7 CreateApplicationBuilder and HostApplicationBuilder

### ISSUE THREAD

**Issue by kris-g** [serilog/serilog#1855]
Are there any plans to implement another UseSerilog extension method for the new application bootstrapper method from .net 7?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createapplicationbuilder

https://github.com/dotnet/runtime/issues/61634

**Comment by dezren39** [comment]
an interesting aspect is the global namespace program.cs file. i'd like if we could just builder.Logger.UseSerilog and then add configuration from there, all within builder.Logger. No more redefining Log constant at top except for logging before builder.build() and no need for Host. In most cases I'd guess it'd be just changing from 'Host' to 'Logging' in user code, but I think there is more going on in the backend?

**Comment by dezren39** [comment]
it's also unclear if/when a new console app will come out to match the new webapplication. this may be something to plan for as well.

also i think it's .net6 and up support this

**Comment by SF-Simon** [comment]
At the same time, I hope to consider the part of MAUI, which comes from: _Microsoft.Maui.Hosting.MauiAppBuilder_.

thx.

**Comment by nblumhardt** [comment]
I think this went into _Serilog.Extensions.Hosting_ last week: https://github.com/serilog/serilog-extensions-hosting/pull/70 - should now be on NuGet in the lastest -dev version of that package.

Please let me know if it's not a match. Thanks!

**Comment by scottmwyant** [comment]
Can we revisit this issue?  It's not been fully addressed.

We are expecting to see an extension method on the [`HostApplicationBuilder`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostapplicationbuilder?view=dotnet-plat-ext-7.0) class, which comes from [`Host.CreateApplicationBuilder()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createapplicationbuilder?view=dotnet-plat-ext-7.0) but right now it's only available on [`HostBuilder`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuilder?view=dotnet-plat-ext-7.0).

Reference: [SerilogHostBuilderExtensions.cs](https://github.com/serilog/serilog-extensions-hosting/blob/52f29a676444e58015863ab92c1432357d0fa03f/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L41).

**Comment by crozone** [comment]
I think it would make more sense to just add an additional `.UseSerilog()` extension to `IHostApplicationBuilder` that takes similar arguments as `IHostBuilder UseSerilog()`. The primary difference is that you no longer have an `HostBuilderContext`, it gets replaced with `IHostApplicationBuilder` itself.

All the newer hosts, be it `HostApplicationBuilder` or `WebApplicationBuilder`, implement `IHostApplicationBuilder`. Ultimately, we just need access to `IHostApplicationBuilder.Configuration` and `IHostApplicationBuilder.Logging.Services`.

An example of what the extension method could look like:

```csharp
public static IHostApplicationBuilder UseSerilog(this IHostApplicationBuilder builder, Action<IHostApplicationBuilder, IServiceProvider, LoggerConfiguration> configureLogger, bool preserveStaticLogger = false, bool writeToProviders = false)
{
    if (builder is null)
    {
        throw new ArgumentNullException(nameof(builder));
    }

    if (configureLogger is null)
    {
        throw new ArgumentNullException(nameof(configureLogger));
    }

    builder.Logging.Services.AddSerilog(
        (services, loggerConfiguration) => configureLogger(builder, services, loggerConfiguration),
        preserveStaticLogger,
        writeToProviders);

    return builder;
}
```

**Comment by silkfire** [comment]
@nblumhardt Any plans to add the above discussed extension method?

**Comment by nblumhardt** [comment]
@silkfire I think `builder.Services.AddSerilog(...)` should cover every current application/builder model; does that one not work in your scenario?

**Comment by silkfire** [comment]
Sure, as long as it's made clear in the documentation that UseSerilog cannot be used anymore with this scenario. Otherwise it's confusing why there's no equivalent for it when using minimal APIs.

**Comment by nblumhardt** [comment]
:+1: raised https://github.com/serilog/serilog-aspnetcore/issues/368 - thanks!
