### ISSUE TITLE
For Serilog 3, consider maintain LibLog runtime compatibility

### ISSUE THREAD

**Issue by pnstickne** [serilog/serilog#1857]
While 'obsolete', LibLog is still the best solution I've found to maintaining multiple libraries in a .NET Framework ecosystem as it is entirely dependency free (excluding the runtime bindings..). It would not be viable to for use to switch to Serilog 3 if the LibLog binder breaks. (Changing the configuration and API/ABI used in the hosts programs to setup Serilog is A-OK.)

The SerilogLog adapter is here:

https://github.com/damianh/LibLog/blob/master/src/LibLog/LogProviders/SerilogLogProvider.cs

**Comment by SimonCropp** [comment]
there are beta nugets of v3. can u let us know if they are still compatible with liblog?

out of curiosity, why cant u use Microsoft.Extensions.Logging.Abstractions ?

**Comment by nblumhardt** [comment]
Just checking over the adapter again, I think it's safe to say that v3 will be 100% compatible (source and binary). If we were to break the kind of functionality that LibLog relies on we'd make life very hard for everyone.

The compatibility breaks in v3 are really driven by the need to keep the project maintainable, by dropping unused baggage (long obsolete APIs) and unmanageable targets (e.g. long obsolete .NET versions).

Even in those cases, we're taking binary breakage of existing packages - especially sinks, but also consuming applications - very seriously.

**Comment by SimonCropp** [comment]
given @nblumhardt comment, i think it is safe to say LibLog compat will be maintianed
