### ISSUE TITLE
LoggingLevelSwitch should implement interface

### ISSUE THREAD

**Issue by sgtobin** [serilog/serilog#1870]
I would like to be able to change the LoggingLevel for individual transactions. I have an extremely high load application and would like to be able to switch LoggingLevel for a very small number of transactions.  LoggingLevelSwitch only allows me to change the level for all transactions.

**Describe the solution you'd like**
Allow a logging level provider to be injected as a scoped dependency.

**Comment by nblumhardt** [comment]
Hi Sean, thanks for dropping us a line.

Are you aiming to implement sampling with this? (I.e. record detailed logs for only a small sample of transactions?). I'll have a think about what options might be out there. `LoggingLevelSwitch` is performance-critical and unlikely to be changed to use virtual dispatch at this point, but there could be other ways to achieve what you're after.

**Comment by sgtobin** [comment]
@nblumhardt,

No - we would not be using it for sampling.
We would use it to debug a specific transaction.
If a transaction fails, we would set up the system to have debug level logging for that transaction only. Then we would send the transaction back through the system and use the increased logging to try to identify the problem with that specific transaction. Thx.

**Comment by nblumhardt** [comment]
@sgtobin looping back around to this, would implementing `ILogger` be a workable alternative? We've done this for a couple of trickier cases and it's now pretty straightforward to wrap an underlying `ILogger` while applying some additional logic.

In this case, your logger would check the transaction's logging level, and either choose from two underlying logger instances, or manually construct low-`Level` `LogEvents` and force them past the underlying logger's level check using `ILogEventSink.Emit()`.

Here's an example wrapping `ILogger` that's widely deployed:

https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/Extensions/Hosting/ReloadableLogger.cs

And here's how events can be passed through `Emit()`:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Logger.cs#L380

(`Write()`, by comparison, will perform a level check.)

Let me know if this does the trick!

**Comment by sgtobin** [comment]
I was a little wary of the performance implications of this approach but I guess it is currently the only way to go. Thank you.

**Comment by nblumhardt** [comment]
Sounds good. I think the performance should end up pretty similar, since the check in the virtualized `LoggingLevelSwitch` version would have similar (order of magnitude) overhead to the check in the wrapper logger. Interested to hear how you go, though!
