### ISSUE TITLE
Configure CI to not publish each commit to `dev` to nuget?

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog#1876]
See https://www.nuget.org/packages/Serilog/ - there are dozens of preview packages.

**Comment by nblumhardt** [comment]
Currently it's pretty handy for me to be able to zip into our codebase and update to the latest `3.0.0-dev-*` build every week or two just to make sure everything still works smoothly. It's also handy to be able to point people to these builds for improvements/fixes ahead of stabilizing them.

Perhaps we could keep those advantages but cut down on noise by having some way to opt out of publishing, perhaps in the commit message? `[skip publish]` or something like that? 🤔

**Comment by sungam3r** [comment]
I have always worked with opt-in Nuget publishing when tag happens in git starting publishing workflow in Github Actions. And each commit in master (or dev in your case) ends with publishing to GitHub package registry to not clutter Nuget.

**Comment by sungam3r** [comment]
skip publish approach requires developers to know about that and may be useless if one does not know if he wants to publish at all.

**Comment by cremor** [comment]
Alternative solutions:

- Hide/unlist older dev versions on NuGet automatically (only keep a few).
- Move dev versions to https://www.myget.org/

**Comment by Numpsy** [comment]
> * Move dev versions to https://www.myget.org/

I've been doing some testing with CI builds of Avalonia recently, and fwiw they have separate nuget feeds for CI and Nightly builds, and only publish preview packages to nuget.org occasionaly

**Comment by nblumhardt** [comment]
I often work across the org on different packages and find I rely on the NuGet/dev versions quite a lot. I'm not sure that there's really any issue worth fixing at this point, personally - or at least wouldn't be worth the added friction for me :-)

**Comment by SimonCropp** [comment]
yeah i prefer to have every commit pushed

**Comment by sungam3r** [comment]
Feel free to close if you are fine with that working as is.
