### ISSUE TITLE
Accept different common naming schemes for log levels

### ISSUE THREAD

**Issue by mickelsonmichael** [serilog/serilog#1879]
**Is your feature request related to a problem? Please describe.**

The default Microsoft logger utilizes the keyword `Trace` to define the highest detail logs. This is contrary to what Serilog utilizes, `Verbose`. This can be confusing and can lead to misconfigurations at times.

**Describe the solution you'd like**

Ideally, some common synonyms could be parsed as well, which would make transitioning between loggers a little smoother.

For example:

- `Verbose` could map from `Verbose`, `Trace`, or `Detailed`
- `Information` could map from `Information`, `Info`, or `Normal`
- `Warning` could map from `Warning` or `Warn`

**Describe alternatives you've considered**

Obviously, the alternative is to simply be more mindful of the proper keywords and to utilize the proper keywords each time.

**Additional context**

No additional context needed, as far as I can tell.

**Comment by nblumhardt** [comment]
Hi Michael, thanks for the suggestion!

I think that path could lead to some confusing behavior, e.g. a filter `@Level = 'Trace'` would match nothing, even if the minimum level setting in the same JSON configuration file was set to `"Trace"`. There are quite a few more places where levels and strings are interchangeable that would need to be found and considered.

At the moment, although it's a bit awkward to discover, once you know the Serilog levels the whole system uses them, so I'd be inclined to leave this as-is.

**Comment by mickelsonmichael** [comment]
I see what you mean. After looking around in the code a little bit, I think my recommendation would be more suited for projects like the [serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration) project which read strings in from files. That may be a place where flexibility could be added without functionality being majorly altered in the core library

**Comment by nblumhardt** [comment]
Even then, we'll end up in the situation where some subprojects accommodate different level names and others don't.

(Tangentially related, but may be useful to you on the output end of things, https://nblumhardt.com/2021/06/customize-serilog-json-output/#-rename-verbose-to-trace-and-fatal-to-critical shows how to change level names in formatting.)

**Comment by mickelsonmichael** [comment]
> Even then, we'll end up in the situation where some subprojects accommodate different level names and others don't.

That's a good point and a side-effect I hadn't considered.

I suppose it's a dream that's better off left unfulfilled 😀 thank you for the discussion and insight!

**Comment by nblumhardt** [comment]
👍 thanks!
