### ISSUE TITLE
option to disable double-quoting strings when using `JsonFormatter`

### ISSUE THREAD

**Issue by dhduvall** [serilog/serilog#1880]
I know similar things have come up a zillion times before, but I don't think any of the fixes apply to this situation. Specifically, I have a statement like this:

```csharp
loggerConfiguration.WriteTo.Console(new JsonFormatter(renderMessage: true));
```
and later a log call like this:
```csharp
logger.LogInformation("I am a {thing}, {attributes}.",
    "teapot",
    String.Join(" and ", new []{"short", "stout"}));
```
In the final log rendering, I see
```json
"RenderedMessage": "I am a \"teapot\",  \"short and stout\"."
```
whereas what I really want, in the end, is
```json
"RenderedMessage": "I am a \"teapot\", \"short\" and \"stout\"."
```
for which I'm perfectly happy constructing the `attributes` string and inserting all the quotes manually.

I don't think there's anything I can do to remove those double quotes inside the value, except to add the `:l` format string to each instance of a `string` variable being used in a template. Since there's no logger-wide event template for the `JsonFormatter`, I can't just specify the `:l` there, and there don't seem to be any other options that would apply to the logger globally.

It would make sense to me from a user-API perspective to have another optional boolean argument to the `JsonFormatter` constructor that would switch this behavior off, but I don't know whether that's feasible or not.

**Comment by augustoproiete** [comment]
@dhduvall Your argument for `{attributes}` is a single string because of your call to `String.Join(" and ", new []{"short", "stout"})` so that string is being serialized as valid JSON.

The behavior you're seeking is not what a *JSON* formatter can ever do. You can write your own formatter with the semantics you want though, but what you're after is no longer *JSON*...

**Comment by dhduvall** [comment]
I'm not sure where you're getting that. I understand that the argument for `{attributes]` is a single string and that's why it's getting double quotes around it. But it's not a JSON string value, and it's not supposed to be. It's a string that's being put _inside_ a JSON string.

The code that's adding the quotes is in [`Serilog/Events/ScalarValue.cs`](https://github.com/serilog/serilog/blob/19d8b1a0b947d70adc7539dbb88772e1410bbab6/src/Serilog/Events/ScalarValue.cs#L66-L79), which is not part of the JSON construction (which is over in [`Serilog/Formatting/Json/JsonValueFormatter.cs`](https://github.com/serilog/serilog/blob/19d8b1a0b947d70adc7539dbb88772e1410bbab6/src/Serilog/Formatting/Json/JsonValueFormatter.cs#L559), but part of the message rendering.

**Comment by dhduvall** [comment]
Okay, thanks. I had wanted to avoid replicating the JSON structure, but since the template renderer does most of the work for me, and I get the ability to convert timestamps to UTC, then I'll go ahead with this.

Having those really detailed blog posts is super helpful; I'm glad you wrote them!

I'll let you close the issue if you want this to be the expected and official way of getting the result I wanted.

**Comment by nblumhardt** [comment]
👍
