### ISSUE TITLE
Serilog.Sinks.RabbitMQ Nuget

### ISSUE THREAD

**Issue by AsyncTaskSola** [serilog/serilog#1883]
hello , I use this nuget ,when I setting this config in code .Find have a question,the rabbitmq can connect ,but can't build a new quene and exchange .Or is there something wrong with my configuration ？
Log.Logger = new LoggerConfiguration()
   .Enrich.FromLogContext()
   .Enrich.WithExceptionDetails()
   .WriteTo.RabbitMQ((clientConfiguration, sinkconfig) =>
        {
            //ConnecttoRbbitMq();
            clientConfiguration.Username = "guest";
            clientConfiguration.Password = "guest";
            clientConfiguration.Exchange = "rqlogstashExchange";
            clientConfiguration.ExchangeType = ExchangeType.Direct;
            clientConfiguration.DeliveryMode = RabbitMQDeliveryMode.NonDurable;
            clientConfiguration.RouteKey = "rqlogstash";
            clientConfiguration.Port = 5672;
            clientConfiguration.Hostnames.Add("127.0.0.1");
            sinkconfig.TextFormatter = new JsonFormatter();
        })
    .ReadFrom.Configuration(configuration)
    .CreateLogger();

![image](https://user-images.githubusercontent.com/48469129/227836824-25084b41-135d-485c-86c0-91c35b59997a.png)
![image](https://user-images.githubusercontent.com/48469129/227836886-b1d32671-20bc-46c4-882c-44ca6074cc16.png)

**Comment by nblumhardt** [comment]
Hello! Thanks for your message. This is the wrong repository/project to raise this in; you'll need to find the repository associated with the Serilog.Sinks.RabbitMQ NuGet package. (This is the core Serilog project, we don't maintain or know anything about this sink.)

**Comment by AsyncTaskSola** [comment]
ok,thanks

**Comment by sungam3r** [comment]
@AsyncTaskSola As I can see from RabbitMQSink [sources](https://github.com/lyng-dev/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQSink.cs) it does not create any RabbitMQ entities so you should do that yourself before.

**Comment by AsyncTaskSola** [comment]
@sungam3r yeah! maybe u are right !
