### ISSUE TITLE
can add an option to keep current log file without date attached while rolled with date attched?

### ISSUE THREAD

**Issue by bthulu** [serilog/serilog#1894]
**Is your feature request related to a problem? Please describe.**
while use rolling file on day, log file will always attched with a day, such as log20230415.txt.
it's very strange to someone who used to use java or nlog.

**Describe the solution you'd like**
write current log to log.txt, and archive to log20230415.txt while rolling.

**Comment by nblumhardt** [comment]
Hi - you're looking for https://github.com/dfacto-lab/serilog-sinks-file

Some discussion in the earlier duplicate issue https://github.com/serilog/serilog-sinks-file/issues/40
