### ISSUE TITLE
New sink for Discord

### ISSUE THREAD

**Issue by Codeh4ck** [serilog/serilog#1895]
I have made a Serilog Sink that posts events on a Discord channel through Discord's webhook functionality. 
The NuGet package is available here: https://www.nuget.org/packages/Codelux.Serilog.Sinks.Discord/

Project repository: https://github.com/Codeh4ck/Serilog.Sinks.Discord

Thanks

**Comment by Codeh4ck** [comment]
I see there is already a sink for Discord which isn't included in the wiki but is under the official Serilog account on NuGet.

Let me know if this can be included as an alternative and if so, whether I should rename the package to avoid confusion or not. My package offers a little bit more customization when it comes to printing logs on Discord.

**Comment by nblumhardt** [comment]
Howdy! `serilog-contrib` is a very loose umbrella and shouldn't be considered "official Serilog" - it's just a way some of us try to support community efforts on things like the Disqus sink.

The more the merrier, here - I think including an alternative, and letting users find the one that matches their needs the best, is a good thing 👍

**Comment by Codeh4ck** [comment]
Hello, thanks for the response! Of course, neither of the existing Discord sinks are official Serilog.

I do believe however it would be nice if they were added in the wiki for people who are interested in posting their logs in a Discord channel. Just so they can know the sinks exist, without putting much effort into searching! 

I, for one, created this sink thinking there wasn't any Discord sink available because of missing inclusions in the wiki. 

Just a thought 😄

**Comment by nblumhardt** [comment]
Unfortunately the Provided Sinks page is rather stale; we're likely better off leaving this entirely in the hands of NuGet package search, to avoid this kind of issue. On my TODO list, but closing this one as I don't plan making the updates. Thanks all the same for your contribution! Hope it's going well :-)
