### ISSUE TITLE
Destructure `IReadOnlyDictionary<...>` the same way as `IDictionary<...>`

### ISSUE THREAD

**Issue by pavel-faltynek** [serilog/serilog#1896]
**Is your feature request related to a problem? Please describe.**
`IReadOnlyDictionary` is destructured as a collection of `KeyValuePair`, which, at least from my point of view, is unwanted.

**Describe the solution you'd like**
`IReadOnlyDictionary` is destructured the same way as `IDictionary`, meaning `{ "Key1Name": "Value1", "Key2Name": "Value2" }`

**Describe alternatives you've considered**
No alternatives.

**Additional context**
```
        using var logger = new LoggerConfiguration().WriteTo.Console().CreateLogger();
        var dictionary = new Dictionary<string, object>
        {
            ["Text"  ] = "alpha",
            ["Number"] = 3.14,
            ["Object"] = new { Child = "new" },
        };


        logger.Information("Dictionary: {@Dictionary}", dictionary);
        // Would be nice to have the same results also for this:
        logger.Information("IReadonlyDictionary: {@IReadonlyDictionary}", dictionary.AsReadOnly()); 
```
Results in:
```
Dictionary: {"Text": "alpha", "Number": 3.14, "Object": {"Child": "new"}}
IReadonlyDictionary: [{"Key": "Text", "Value": "alpha", "$type": "KeyValuePair`2"}, {"Key": "Number", "Value": 3.14, "$type": "KeyValuePair`2"}, {"Key": "Object", "Value": {"Child": "new"}, "$type": "KeyValuePair`2"}]
```

**Comment by nblumhardt** [comment]
Hi @pavel-faltynek - thanks for the note.

The destructuring mechanism works on implementation type, not through interfaces, so this is deliberate though tricky.

Does the `AsReadOnly()` method have a well-known concrete implementation type?

**Comment by sungam3r** [comment]
`System.Collections.ObjectModel.ReadOnlyDictionary<TKey, TValue>` is a well-known type.
