### ISSUE TITLE
ability to proxy destructure (it takes too much time to Destructure )

### ISSUE THREAD

**Issue by mike7ang1rdz** [serilog/serilog#1904]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
](https://stackoverflow.com/questions/76129061/serilog-takes-too-much-time-to-destructure)

**Describe the solution you'd like**
a similar approach to sinks (aync sink)

**Describe alternatives you've considered**

**Additional context**

**Comment by bartelink** [comment]
I'm guessing this is related to this SO issue https://stackoverflow.com/questions/76129061/serilog-takes-too-much-time-to-destructure
The fact that destructuring takes place on the logging thread is a key part of the design - it ensures the objects being logged are not being used concurrently and/or disposed.
As it stands, this "proposal" is not sufficient to meet any reasonable bar in terms of conveying your desires, and/or how they can be made a reality.
I would strongly suggest closing this issue as it is simply not actionable as it is.

**Comment by nblumhardt** [comment]
Sounds like the issue was the masking library in use (1 second is extreme for any simple local operation in C#), and the solution (in the comments of the linked issue) was to move to https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive.
