### ISSUE TITLE
Operation Context/Stack

### ISSUE THREAD

**Issue by richiej84** [serilog/serilog#191]
I’ve built an OperationContext class (not sure if this is the best name for it or not) that started as a copy of TimedOperation. Fundamentally it’s every similar in that it represents a fixed scope and it records the elapsed time taken; however OperationContext does a few additional things

* Defines an outcome for the operation – Success, Fail, Unknown – that can be set in code before the operation completes.
*  Allows a set of properties to be applied to the OperationContext and in turn applied to each nested LogEvent.
* Supports nesting of child OperationContexts that inherit their parent’s properties
* Adds the operation identifier as a property of the op as well as maintaining a stack of id’s of the current OperationContext hierarchy. This means that when I see a log entry from within an OperationContext, I can not only see what operation it belongs to but also the full operation hierarchy.

Here's a sample usage of it, showing nested operations

    private static void ParentMethod()
    {
        using(_log.BeginOperation("Parent", "ParentId", new { SomeProperty = "The property value in the parent"}))
        {
            _log.Information("Start of parent");
            ChildMethod();
            _log.Information("End of parent");
        }

        _log.Information("Outside of operation");
    }

    private static void ChildMethod()
    {
        using (_log.BeginOperation("Child", "ChildId", new { SomeProperty = "The property value in the child" }))
        {
            _log.Information("Start of child");
            GrandchildMethod();
            _log.Information("End of child");
        }
    }

    private static void GrandchildMethod()
    {
        using (_log.BeginOperation("Grandchild", "GrandchildId", new { SomeProperty = "The property value in the grandchild" }))
        {
            _log.Information("Some work");
        }
    }

And here's the associated output in Seq
![image](https://cloud.githubusercontent.com/assets/8443143/3928331/68cade5e-2408-11e4-8226-7658fe9ee070.png)

Do others think this concept would be useful? In which project would you see this living? Currently I have it in the Serilog.FullNetFx project alongside LogContext.

**Comment by nblumhardt** [comment]
Hi @richiej84 - I still think this is a very interesting idea but it doesn't look like it'll be at the top of the priority stack for a while; to keep the tracker manageable I'll close this for now. Thanks again!
