### ISSUE TITLE
LogContext does not maintain properties across `async` calls when not using `using` statement

### ISSUE THREAD

**Issue by nmccrina-contessa** [serilog/serilog#1913]
**Description**
If I call `LogContext.PushProperty()` in a child class and store the IDisposable in my own stack for later disposal, then try to write a log message in the base class before I have disposed the IDisposable, the property is not applied to my log message if I call an `async` method later in my child class method.

My use case is I have a base class that puts a `try`/`catch` block around a virtual method that different child classes will implement in order to execute custom logic. I want the child implementations of the virtual method to be able to add their own properties to the LogContext which will be added to log messages from the `catch` block in the base class.

Obviously I can't use a `using` statement in this scenario (because if I set it up in the base class I won't know the
value of the property at that point since it's local to the child class, and if I set it up in the child class the `using` will go out of scope when the exception is thrown) so I realize I'm straying a bit from the basic use case outlined in the docs.

**Reproduction**
I was able to reproduce with a unit test (LogContextTests.cs):

```
abstract class LogContextTestHelperBase
{
    public LogContextTestHelperBase(Logger logger)
    {
        _contextProperties = new Stack<IDisposable>();
        _logger = logger;
    }

    public async Task DoStuff()
    {
        try
        {
            await DoImplementationSpecificStuff();
        }
        catch (Exception ex)
        {
            _logger.Error(ex, ex.Message);
        }
        finally
        {
            IDisposable? nextContextProperty;

            while (_contextProperties.TryPop(out nextContextProperty))
            {
                nextContextProperty.Dispose();
            }
        }
    }

    protected abstract Task DoImplementationSpecificStuff();

    protected void AddLogContextProperty(string name, object? value)
    {
        var property = LogContext.PushProperty(name, value);
        _contextProperties.Push(property);
    }

    private Stack<IDisposable> _contextProperties;
    private readonly Logger _logger;
}
```
```
class LogContextHelper : LogContextTestHelperBase
{
    private readonly int _value;
    private readonly int _waitTime;

    public LogContextHelper(Logger logger, int value, int waitTime = 1000)
        : base(logger)
    {
        _value = value;
        _waitTime = waitTime;
    }
    protected override Task DoImplementationSpecificStuff()
    {
        AddLogContextProperty("A", _value);
        // await Task.Delay(_waitTime); // <-- uncomment this and change to async Task above to cause test failure
        throw new NotImplementedException($"In class {_value}");
    }
}
```
```
[Fact]
    public async Task PropertiesCanBePushedFromChildClass()
    {
        LogEvent? lastEvent = null;

        var log = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .WriteTo.Sink(new DelegatingSink(e => {
                lastEvent = e;
            }))
            .CreateLogger();

        var worker1 = new LogContextHelper(log, 1);

        await worker1.DoStuff();

        Assert.NotNull(lastEvent);
        Assert.Equal(1, lastEvent.Properties["A"].LiteralValue()); // works unless the await in DoImplementationSpecificStuff() is uncommented
    }
```

**Expected behavior**
If I push a property to the LogContext in a child class, I should see it applied to messages from the base class as long as I haven't disposed the property, regardless of async calls.

**Relevant package, tooling and runtime versions**
dev branch of Serilog, .net 7

**Additional context**

**Comment by nblumhardt** [comment]
Thanks for raising this. Unfortunately I think what you're observing is the intrinsic behavior of async-local data in .NET; it's not to do with inheritance but rather the way that child tasks inherit async-local data from their parent (there are some not-immediately-intuitive aspects to this, such as the children being arranged in a tree rather than a stack, that complicate things significantly).

Your best bet here is to organize for the parent task to push the contextual information onto the stack somehow, before invoking any async calls.

Hope this helps, sorry for the very brief explanation and if I've missed anything please do let me know :-)

**Comment by nmccrina-contessa** [comment]
@nblumhardt thanks for replying. I figured it would be something nuanced like that. We are currently working around by doing something similar to your suggestion but our first attempt at it was a bit awkward. If there's nothing to be done for the root problem though we can keep improving on that workaround.

**Comment by mhDuke** [comment]
@nblumhardt if you can share your findings, would be much appreciated. I am thinking we could play with the `ExecutionContext` `Capture()` or `Run()` somehow to fix this.
