### ISSUE TITLE
CI-CD System Pollutes NuGet With Dev Versions of NuGet Package

### ISSUE THREAD

**Issue by bleepzter** [serilog/serilog#1914]
Your CI/CD pipeline is publishing non-stop dev releases to the official NuGet gallery. 
Push your official release packages or release candidates only. Its confusing to reference a dev-only package and have hundreds of them in-between releases.

![image](https://github.com/serilog/serilog/assets/3333921/ad48a662-39c5-48d7-9f31-9a3ae92fb700)

**Comment by augustoproiete** [comment]
@bleepzter This seems like a NuGet gallery UI issue to me. You should be able to see stable releases only, either by default, or by filtering on their UI.

I'd recommend you open a ticket with the NuGet team to improve the UX there - https://github.com/NuGet/NuGetGallery

Publishing builds from the develop branch to NuGet makes it possible (and very easy) for sink authors to test their sinks against the latest builds and there's a lot of value on being able to do this without any friction.

[We've discussed this before BTW](https://github.com/serilog/serilog/issues/1876) and decided to keep publishing to NuGet.
