### ISSUE TITLE
Update Enrichment page

### ISSUE THREAD

**Issue by mo-esmp** [serilog/serilog#1931]
Hence [Serilog.Enrichers.CorrelationId](https://github.com/ekmsystems/serilog-enrichers-correlation-id) is archived and no longer maintained, I added correlation id enricher to [Serilog.Enrichers.ClientInfo](https://github.com/mo-esmp/serilog-enrichers-clientinfo). It would be great if you update the description for `Serilog.Enrichers.ClientInfo`.
- `WithClientIp()`, `WithCorrelationId()` and `WithRequestHeader("header-name")` will add properties with client IP, correlation id and HTTP request header value

**Comment by nblumhardt** [comment]
Done - thanks!
