### ISSUE TITLE
ILogger.BindMessageTemplate and ILogger.BindProperty implemented using default configuration.

### ISSUE THREAD

**Issue by Atomosk** [serilog/serilog#1933]
**Description**
When you implement your own logger by implementing only abstract methods of `ILogger` it ignores some of configurations like additional scalar types.

**Reproduction**
Make a decorator of `ILogger`, which does nothing, but delegation. Implement only required members.  
Pass a logger with custom scalar types
```CSharp
public class DelegateEverythingLoggerDecorator : ILogger
{
    private ILogger _loggerImplementation;

    public DoNothingLoggerDecorator(ILogger loggerImplementation)
    {
        _loggerImplementation = loggerImplementation;
    }

    public void Write(LogEvent logEvent)
    {
        _loggerImplementation.Write(logEvent);
    }
}

ILogger logger = new DoNothingLoggerDecorator(new LoggerConfiguration()
    .Destructure.AsScalar<ValueTuple<int, int>>()
    .CreateLogger());
logger.Information("{@Value}", (1, 2));

```

**Expected behavior**
Decorator, which does nothing, behaves just like the object it decorates. `ValueTuple` is not deconstructed.

**Actual behavior**
Decorator ignores some of configurations of it's `loggerImplementation`. `ValueTuple` is deconstructed.

**Comment by nblumhardt** [comment]
Thanks for your message. This is expected - if you want your decorator to forward `BindMessageTemplate()` to the decorated object, you'll need to add that explicitly.

**Comment by Atomosk** [comment]
It's kinda weird. By looking at that decorator I'd say it does nothing, but it does. But if you think it's obvious what and how it changes then it probably is. Should I close issue then?

**Comment by nblumhardt** [comment]
Checking out the default implementations of `BindMessageTemplate()` and `Write()` on the `ILogger` implementation might make the relationship between these a bit clearer.

The defaults make it pretty easy to build simple loggers for odd jobs, but for a decorator that will work well you should look at implementing:

 * `Write(LogEvent)`
 * `BindMessageTemplate(...)`
 * `BindProperty(..)`
 * `IsEnabled(LogEventLevel)`
 * `ForContext(..)` (most/all of the overloads)

HTH!
