### ISSUE TITLE
Changes.md not updated

### ISSUE THREAD

**Issue by sagarpuranik** [serilog/serilog#1934]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
What's going wrong?
Where can we find the changes between 2.12 and 3.0.1

**Comment by nblumhardt** [comment]
Thanks for your message. This information is maintained in [Releases](https://github.com/serilog/serilog/releases).

I believe we should remove `CHANGES.md`, as it only duplicates information already recorded in the release notes linked above.

**Comment by sagarpuranik** [comment]
Thanks a lot. This helps.

**Comment by georgiosd** [comment]
@nblumhardt we have a bunch of dependencies that don't seem to have new stable versions - are these compatible with 3.0.1?

```
<PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.2.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="4.2.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="7.1.1" />
```
