### ISSUE TITLE
Typo in Formatting Output Wiki

### ISSUE THREAD

**Issue by gupta-kartik** [serilog/serilog#1939]
> Message - The log event's message, rendered as plain text. The :l format specifier switches of quoting of strings, and :j uses JSON-style rendering for any embedded structured data.

Message - The log event's message, rendered as plain text. The :l format specifier switches **off** quoting of strings, and :j uses JSON-style rendering for any embedded structured data. 

It should be `off quoting of string` not `of quoting of string`. This confused me for a bit.

**Comment by nblumhardt** [comment]
Fixed - thank you 👍
