### ISSUE TITLE
[Security] How does serilog prevent log forging from user input?

### ISSUE THREAD

**Issue by douglasg14b** [serilog/serilog#1940]
There is a SO post here that is unanswered for almost a year https://stackoverflow.com/questions/73370165/serilog-and-log-injection which is partially why I'm posting here.

Since this is a rather important topic, and `Microsoft.Extensions.Logging` is flagged for [log injection](https://owasp.org/www-community/attacks/Log_Injection) & [CWE-117](https://cwe.mitre.org/data/definitions/117.html) by CodeQL even when Serilog is used. This should probably be covered here on GitHub.

Does serilog escape, or use a library which escapes, unsafe inputs for structured logging?

**Comment by nblumhardt** [comment]
Yes, if configured mindfully, Serilog completely overcomes this issue.

However, this is formatter/sink-specific and relies on using Serilog as a structured logger (writing to unstructured output streams can definitely thwart this).

If you take the example from the OWASP article:

```
    var val = request["val"];
    try {
        int value = Int32.Parse(val);
    }
    catch (Exception ex) {
        log.Information("Failed to parse val {Val}");
    }
```

Then the resulting Serilog event in CLEF format will look like:

```json
{"@t":"...","@mt":"Failed to parse val {Val}","Val":"twenty-one"}
```

Imagining the "bad guy" scenario:

> if an attacker submits the string “twenty-one%0a%0aINFO:+User+logged+out%3dbadguy” ...

Serilog will produce a structured event like:

```json
{"@t":"...","@mt":"Failed to parse val {Val}","Val":"twenty-one\n\nINFO: User logged out=badguy"}
```

Note that the injected "event" is completely within the `Val` field and can't be mistaken for a "real" event.

This holds even if the injected event is made to look like JSON, as Serilog's JSON formatter escapes JSON values correctly, and so the fake event will still be entirely within the "Val" field.

Even when misusing the Seriog API and not correctly recording `Val` as structured data, injected content will still only ever appear within the message field or whatever field it's placed into, and can't masquerade as an entirely separate event.

Just to stress it again, you'll need to check how your formatter and sink behave, to be sure. I'm talking about the formatters in _Serilog.Formatting.Compact_ here.
