### ISSUE TITLE
No logs on AWS lambda using appsettings args formatter field when upgrading to .Net 6

### ISSUE THREAD

**Issue by AlexanderDarbyVerisk** [serilog/serilog#1949]
**Description**
There is no logs on the AWS lambda when using the appsettings 'args formatter' configuration with our custom formatter when upgrading from .Net Core 3.1 to .Net 6.

**Reproduction**
appsettings configuration:

```
  "Serilog": {
      "Using": [
        "Serilog.Sinks.Console"
      ],
      "MinimumLevel": "Information",
      "WriteTo": [
        {
          "Name": "Console",
          "Args": {
            "formatter": "ourClassPathAndName, ourAssemblyName"
          }
        }
      ],
      "Enrich": [
        "FromLogContext",
        "WithExceptionDetails"
      ]
    }
```

**Expected behavior**
Logs to appear on the AWS lambda instance.

**Relevant package, tooling and runtime versions**
Serilog 3.0.1
Serllog.Exceptions 8.4.0
Serilog.Settings.Logging 7.0.0
Serilog.Settings.Configuration 7.0.0
Serilog.Sinks.Console 4.1.0

**Additional context**

* This was working when using .Net Core 3.1 and it also works locally with .Net 6 using the AWS lambda test tool in VS.
* If the appsetings formatter line is removed then the logs appear but without our custom format.

**Comment by AlexanderDarbyVerisk** [comment]
It was due to a shared project LogContext property issue.

**Comment by bartelink** [comment]
Thanks for taking the time to report back and close (this is also why stuff like this is always best to log on Stackoverflow.com first though...)
