### ISSUE TITLE
Serilog cannot destructure anonymous complex objects within a collection

### ISSUE THREAD

**Issue by bensmith009988** [serilog/serilog#1951]
I cannot find a way to destructure any collection property that is defined as an anonymous type, and also a complex object.

For example:

**Class Definition:**
```
 public class LogRequest
 {
     public string? LogMessage { get; set; }

     public Dictionary<string, object>? AdditionalMetaData { get; set; }
 }
```

**Logging Method in .NET Web API Controller:**
```
[HttpPost("information")]
public void LogInformation([FromBody] LogRequest requestData)
{
    logger.Information("{@requestData}", requestData);
}
```

**JSON Payload of Request**
```
{
    "logMessage": "Test log message",
    "additionalMetaData" :{
        "SomeMetaData": 1234,
        "TimeOfLog": "00:00",
        "SomeOtherObject": {
            "SomeProperty": "Some Value",
            "SomeOtherMetaData": 1234
        }
    }
}
```

**Serilog's interpretation of this object:**

```
requestData: {
  AdditionalMetaData: {
	SomeMetaData: 1234,
	SomeOtherObject: [ 
	  [[]],
	  [[]]
	],
	TimeOfLog: 00:00
  },
  LogMessage: Test log message
}
```
As you can see, any complex object that is defined by the incoming payload, within the collection, expressed as an anonymous type, cannot be properly destructured by Serilog. The "SomeOtherObject"'s property values were completely wiped out by Serilog in the interpretation.

I will mention that in this example, I am Deserializing the incoming JSON payload using Newtonsoft.Json NuGet package. The "SomeOtherObject" is being deserialized into a JObject type.

The System.Text.JSon deserialization has the same effect. Serilog interprets the object a little bit differently, but it is still unable to destructure complex objects within an anonymous type, defined as a property in a collection.

**Comment by nblumhardt** [comment]
Hi! You need to add the _Destructurama.JsonNet_ package, which will sort this out.

**Comment by bensmith009988** [comment]
That did it! I thought this was a bug... My apologies!

**Comment by sungam3r** [comment]
Just sorting issues from my email. @bensmith009988 For now I'm a maintainer in https://github.com/destructurama/json-net . It was actualized last months. Please see https://github.com/destructurama/json-net/releases for more information.
