### ISSUE TITLE
{MachineName} not working appsettings.json

### ISSUE THREAD

**Issue by kshitiz1007** [serilog/serilog#1952]
.

**Comment by bartelink** [comment]
If you're trying to figure out how to achieve something and are having trouble, it's best to ask on StackOverflow.com showing clearly the what you've tried, and the exact desired output, and tagging it `serilog` so people that have searches configured will see it; there are way more people tracking that than this repo's issue list.

When that's done, feel free to post a link back here as you close.

A `bug` logged in the issue tracker for something with 230,000 downloads per day better be something that's broken and have a full repro.
