### ISSUE TITLE
Add option to Serilog.Formatting.Json.JsonFormatter for adding rendered Message to output

### ISSUE THREAD

**Issue by Pikabanga** [serilog/serilog#1953]
**Is your feature request related to a problem? Please describe.**
The `Serilog.Formatting.Compact.RenderedCompactJsonFormatter` has a useful feature of adding in the resulting json an `@m` property which is a rendered version of the message template. But we don't want to use the compact format for other reasons, but then this rendered message is not available.

**Describe the solution you'd like**
Add an option to `Serilog.Formatting.Json.JsonFormatter` that adds a `Message` property to the json which contains a rendered version of what can be seen in the `MessageTemplate` property. Alternatively, the option could be flexible in if you want `Message`, `MessageTemplate`, or both.

See this [issue](https://stackoverflow.com/questions/66598821/how-can-i-include-both-message-and-messagetemplate-in-the-serilog-jsonformat) on StackOverflow that asks for the same thing:

> I want in the output JSON to have both: "Message" and "MessageTemplate" nodes,
> However I'm getting only either "Message" or "MessageTemplate", but not both.

**Comment by Pikabanga** [comment]
Ok, I dug a bit in the code and found that this option already exists as a parameter to the JsonFormatter constructor:

![image](https://github.com/serilog/serilog/assets/22037089/f464140d-ebc0-444b-9e59-93ccc56a3f5f)

I'll add an answer to the stackoverflow question with this information.

You can close this issue if you want :)

**Comment by nblumhardt** [comment]
FWIW, the answer to the linked StackOverflow post also does this :-) 👍
