### ISSUE TITLE
Wrapping Logger loses Destructure configuration

### ISSUE THREAD

**Issue by kmcclive** [serilog/serilog#1958]
**Description**
I used the example [here](https://github.com/serilog/serilog/wiki/Structured-Data) to configure custom destructuring for a type.  It works great in most cases, but I can't get it to work if I "wrap" the Serilog `Logger` in my own class. Please see the example in the next section.

**Reproduction**
```
using Serilog;
using Serilog.Events;

namespace SerilogTest;

class Program
{
    public class CustomLogger : ILogger
    {
        private readonly ILogger _logger;

        public CustomLogger(ILogger logger)
        {
            _logger = logger;
        }

        public void Write(LogEvent logEvent)
        {
            _logger.Write(logEvent);
        }
    }

    static void Main()
    {
        Log.Logger = new LoggerConfiguration()
            .Destructure.ByTransforming<HttpRequestMessage>(
                r => new { Uri = r.RequestUri?.ToString(), Method = r.Method.ToString() })
            .WriteTo.Console()
            .CreateLogger();

        var request = new HttpRequestMessage(HttpMethod.Get, "logs");

        var defaultLogger = Log.Logger;
        var customLogger = new CustomLogger(defaultLogger) as ILogger;

        defaultLogger.Information("Request with destructuring: {@Request}", request);
        customLogger.Information("Request without destructuring: {@Request}", request);
    }
}
```

**Expected behavior**
I expected the destructuring to behave the same whether performed by the `defaultLogger` or the `customLogger`.  However, the `customLogger` does not appear to use the destructuring that I configured.

**Relevant package, tooling and runtime versions**
I've tried Serilog versions 2.12.0 and 3.0.1 on both macOS and Windows.  I am also using Serilog.Sinks.Console version 4.1.0.

**Additional context**
I am working on a project where Serilog was used extensively from the start.  Recently, we wanted to introduce the `SourceContext` property to our logs.  The simplest approach we could find was to wrap the Serilog `Logger` in a custom generic class and use dependency injection to specify the type.  We are calling `Log.ForContext<T>()` in our wrapper class, but that doesn't seem to have any impact on the behavior.  I realize this is likely an edge case, but I would appreciate any guidance on how to make this work.

**Comment by nblumhardt** [comment]
You'll need to override and forward `BindMessageTemplate()` and `BindProperty()` on your custom logger to the wrapped one. HTH!

**Comment by kmcclive** [comment]
> You'll need to override and forward `BindMessageTemplate()` and `BindProperty()` on your custom logger to the wrapped one. HTH!
@nblumhardt Thanks for that!  I didn't even notice that `ILogger` had those methods because of their default implementations.
