### ISSUE TITLE
Use of source generators to generate LogEventLevel overloads

### ISSUE THREAD

**Issue by Guiorgy** [serilog/serilog#1961]
### Instead of a request, this is a question/disscussion on source generators.

I'd like to know whether you think it makes sense for method overloads in `ILogger` interface and its implementations (and maybe other things too) to be generated using source generators?

I made a quick prototype in a [fork](https://github.com/Guiorgy/serilog/tree/generator), but only for the `ILogger` interface.

Possible pros:

- It can reduce the copypasta boilercode (in my prototype ILogger **1368** -> **251** lines, but **+595** lines were added, including 2 projects)
- If done well, updates to the source can be done in a few places quickly, instead of having to modify every overload
- If 3 generic overload optimizations are deemed insufficient in the future, using a generator we can easily generate as many overloads as we want, for example (generated): 

```cs
    /// <summary>
    /// Write a log event with the specified level.
    /// </summary>
    /// <param name="level">The level of the event.</param>
    /// <param name="exception">Exception related to the event.</param>
    /// <param name="messageTemplate">Message template describing the event.</param>
    /// <param name="propertyValue0">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue1">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue2">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue3">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue4">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue5">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue6">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue7">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue8">Object positionally formatted into the message template.</param>
    /// <param name="propertyValue9">Object positionally formatted into the message template.</param>
    [MessageTemplateFormatMethod("messageTemplate")]
    void Write<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(LogEventLevel level, Exception? exception, string messageTemplate, T0 propertyValue0, T1 propertyValue1, T2 propertyValue2, T3 propertyValue3, T4 propertyValue4, T5 propertyValue5, T6 propertyValue6, T7 propertyValue7, T8 propertyValue8, T9 propertyValue9)
#if FEATURE_DEFAULT_INTERFACE
    {
        // Avoid the array allocation and any boxing allocations when the level isn't enabled
        if (IsEnabled(level))
        {
            Write(level, exception, messageTemplate, new object?[] { propertyValue0, propertyValue1, propertyValue2, propertyValue3, propertyValue4, propertyValue5, propertyValue6, propertyValue7, propertyValue8, propertyValue9 });
        }
    }
#else
        ;
#endif
```

Cons:

- Harder to debug
- May be harder to maintain
- If done wrong, updating the source may require rewriting the whole/part of the generator
- Support for source generators is not yet perfect, working with them is quite painful at the moment

I hope to hear what others think on this matter.

**Comment by nblumhardt** [comment]
Nice exploration! Thanks for sharing the idea.

I think that right now, since very little energy is going into maintaining `ILogger` overloads, we're probably better off leaving things as-is, there are quite a few "cons" there to work through.
