### ISSUE TITLE
Potential V4 nits/breaking changes?

### ISSUE THREAD

**Issue by bartelink** [serilog/serilog#1966]
Minor nits from perusing the source; most are likely breaking changes best kept for v4

- TFMs
  - maybe a note somewhere about having a `net6.0` TFM but explaining that no egregious later ones will be added see (see reasoning in https://github.com/serilog/serilog-sinks-console/pull/145#issuecomment-1709862581)
  - remove net5.0 TFM (see above)
  - remove `net7.0` TFM (atm it has identical DefineConstants values to `net6.0`)
  - Remove netcoreapp3.1, net5.0 from tests
- README
  - Is there a stance/policy on copyright years (atm readme has 2020)
  - `var log = new LoggerConfiguration()` should gain a `using`
  - `Log.CloseAndFlush();` in static example
    -  should probably gain `a `// Normally in a `try/finally`; ensures File, Async etc sinks have been flushed before program exits` 
    - or, more tersely '// ensure buffering or async Sinks are flushed before app exits'
  - move gitter mention further down the list? or remove?
  - > We welcome bug reports and suggestions through our
   
     We welcome reproducable bug reports and detailed feature requests through our [issue tracker](https://github.com/serilog/serilog/issues) here on GitHub; please note the other avenues are much better or for quick questions or seeking usage help 
- 🤔 remove changes.md given it stops dead at 2.10 (or sync with GH release notes)
- AssemblyVersion [for 3.x] is `2.0`, maybe shift to 4.0 in v4?
- on https://github.com/serilog/serilog/wiki/Getting-Started, in the sample app
  - maybe lose `and Windows Phone 8+.` (maybe add some Blazor mention?)
  - use a top level `namespace SerilogExample`
  - consider using `await Log.CloseAndFlushAsync()`
  - (if this makes sense, ping me and I can do the edits)
- 914M on https://www.nuget.org/packages/Serilog/ is insane (currently # 8 all time, should be 7 soon) - not long to go to 1B!  

(Happy to do PRs for any that get agreed; equally happy for someone else to do them...)

**Comment by nblumhardt** [comment]
These all look good, just dropping thoughts in here to try unblocking as many as possible.

> TFMs

This one will need a standalone ticket for discussion, keen to simplify things where possible but also eager to avoid covering all the ground covered in the last thread over again :-)

> Is there a stance/policy on copyright years (atm readme has 2020)

I think we've moved away from specifying the year, "Copyright &copy; Serilog Contributors" is preferred

> move gitter mention further down the list? or remove?

Remove 👍 

> 🤔 remove changes.md given it stops dead at 2.10 (or sync with GH release notes)

Remove 👍 

> AssemblyVersion [for 3.x] is 2.0, maybe shift to 4.0 in v4?

May pay to search past issues; I think the intention was to freeze it for all time (completely kill off all binding redirect related support) but tooling has moved on so kicking it up to 4.0 might end up being better now.

> maybe lose and Windows Phone 8+. (maybe add some Blazor mention?)

:+1:

> use a top level namespace SerilogExample

May just be noise, it's not strictly required AFAIK.

> consider using await Log.CloseAndFlushAsync()

Definitely 👍

**Comment by bartelink** [comment]
>> TFMs

>This one will need a standalone ticket for discussion, keen to simplify things where possible but also eager to avoid covering all the ground covered in the last thread over again :-)

OK, will do

Seems I was looking at an old version and/or you resolved all of them, thanks!

Did [a wiki edit](https://github.com/serilog/serilog/wiki/Getting-Started/_compare/0baa07687acda25bae3716df177835875c1a248d...4505af2a3d5c378b3663dcedeb39866afbb7e12f)

My remaining items are addressed in https://github.com/serilog/serilog/pull/1969
