### ISSUE TITLE
Extension/property request for allowing configurable way to simplify the log format with LoggerName as simple

### ISSUE THREAD

**Issue by aravindk777** [serilog/serilog#1968]
I am asking for an extension, enhancement, feature request as a property to the File Sink where can we keep the loggerName property if mentioned be simplified to take the Class name and not the whole namespace qualified string? 

While there are custom formatters possible from stackOverflow responses to achieve this, wouldn't it be nice to have it from a configurable way for those who would want to have it? Sometimes, when the file/logger name goes deeper with namespaces, the log text/body goes far with this loggerName being very lengthy. While it helps to stay/show which class name as loggerName is the source for that log entry, can we not customize/configure it to ignore namespace qualified string?

**Comment by bartelink** [comment]
Closing on the basis that the above covers it (this question was in the File Sink repo initially, but, unless I'm mistaken, applies across all Sinks)
