### ISSUE TITLE
Issue logging complex objects

### ISSUE THREAD

**Issue by jboada** [serilog/serilog#1972]
Hi everybody,

I am having problems logging complex objects.

I am working on a Web API that it receives information from many sources.  Each source sends its information (a JSON) and the schema varies among the sources. It is not a single schema.

To be all on the same page, let's say we have a dummy endpoint that receives the information and gives it back to the source with some extra info.

```c#
[HttpPost("TestPost")]
public ActionResult<object> TestPost([FromBody] object JsonData)
{
    Log.Information("Data {@JsonData}", JsonData);
    string? X_Forwarded_For = Request.Headers["X-Forwarded-For"].ToString();
    string? ConnectionRemoteIpAddress = Request.HttpContext.Connection.RemoteIpAddress?.ToString();

    string z = @"
        {
            ""Name"": ""Squid Game"",
            ""Genre"": ""Thriller"",
            ""Rating"": {
                ""Imdb"": 8.1,
                ""Rotten Tomatoes"": 0.94
            },
            ""Year"": 2021,
            ""Stars"": [""Lee Jung-jae"", ""Park Hae-soo""],
            ""Language"": ""Korean"",
            ""Budget"": ""$21.4 million""
        }";

    var y = JsonSerializer.Deserialize<object>(z);

    var x = new
    {
        data = JsonData
        , ContentType = Request.ContentType
        , host = Request.Host
        , X_Forwarded_For = X_Forwarded_For
        , ConnectionRemoteIpAddress = ConnectionRemoteIpAddress
        , Origin = Request.Headers.Origin.ToString()
        , y = y
    };

    Log.Information("LeadDeliverySiteService = {@X}", x);
    return StatusCode(200, x);
}
```

The endpoints returns everything without any issue.

But when I open the log, it writes the following record:

```
{
	"@t": "yyyy-MM-ddTHH:mm:ss.Z",
	"@mt": "LeadDeliverySiteService = {@X}",
	"X": {
		"data": {
			"ValueKind": "Object",
			"$type": "JsonElement"
		},
		"ContentType": "application/json",
		"host": {
			"Value": "dummyhost",
			"HasValue": true,
			"Host": "dummyhost",
			"Port": null,
			"$type": "HostString"
		},
		"X_Forwarded_For": "xxx.xxx.xxx.xxx",
		"ConnectionRemoteIpAddress": "::1",
		"Origin": "pp",
		"y": {
			"ValueKind": "Object",
			"$type": "JsonElement"
		}
	}
}
```

As you can see, the "data" and "y" elements do not have the proper values:
```
"data": {
"ValueKind": "Object",
"$type": "JsonElement"
},
```

```
"y": {
"ValueKind": "Object",
"$type": "JsonElement"
}
```

I have been googling around but I haven't found any possible solution/workaround yet.

**Comment by nblumhardt** [comment]
Hi! You need an `IDestructuringPolicy` for _System.Text.Json_. Here's an example: https://gist.github.com/beppemarazzi/b3292b207427481200676936a3553391 (not sure if there's a NuGet package out there yet with one of these?)

**Comment by jboada** [comment]
> Hi! You need an `IDestructuringPolicy` for _System.Text.Json_. Here's an example: https://gist.github.com/beppemarazzi/b3292b207427481200676936a3553391 (not sure if there's a NuGet package out there yet with one of these?)

Hi, I will check out this code.

Thank you for the quick answer.

**Comment by jboada** [comment]
> Hi! You need an `IDestructuringPolicy` for _System.Text.Json_. Here's an example: https://gist.github.com/beppemarazzi/b3292b207427481200676936a3553391 (not sure if there's a NuGet package out there yet with one of these?)

Hi @nblumhardt ,

This is kind of odd. I opened the project today. I ran some test without modifying the code at all. Serilog is writing everything.

The only difference between yesterday and today. I turned off my computer lat night and turned it on today. 

I will add the code to my project and let know the outcome.

**Comment by jboada** [comment]
> Hi! You need an `IDestructuringPolicy` for _System.Text.Json_. Here's an example: https://gist.github.com/beppemarazzi/b3292b207427481200676936a3553391 (not sure if there's a NuGet package out there yet with one of these?)

Hi @nblumhardt ,

Thank you for this code. It works amazing.

The issue is:
- If you have a typed object, Serilog works fine.
- If you have a generic object, Serilog needs a Destructuring Policy. 
I really appreciate your help.

**Comment by jboada** [comment]
> Hi! You need an `IDestructuringPolicy` for _System.Text.Json_. Here's an example: https://gist.github.com/beppemarazzi/b3292b207427481200676936a3553391 (not sure if there's a NuGet package out there yet with one of these?)

This is the solution,
