### ISSUE TITLE
Make 1-3-argument log overrides not allocate a new object

### ISSUE THREAD

**Issue by TheMLGSquid** [serilog/serilog#1973]
**Is your feature request related to a problem? Please describe.**
As of now, the logger class supports 3 overrides for the Write method, that are generic.
Those implementations in generic types without regards to value/ref types, and allocate a new object?[] to send them to the main, 
params object?[] based overload.
This boxes value types, and allocates new arrays, when those are not really necessary as the array is immediatly disposed after binding the template.

**Describe the solution you'd like**

I think that it would be wise and could improve performance if those overloads were to utilize their potential -  
Perhaps add a different override for ref types to prevent boxing, or stop using object[] all together and instead a BindTemplate overload that accepts a single property value. There is a lot of potential of adding optimizations and prevent allocation on logs, which a very hot part of the code in every program.

**Describe alternatives you've considered**
At work I am using Microsoft.Extensions.Logging.ILogger as a wrapper for Serilog, and I've come to see that there is no actual way around allocating the params object[] allocation - I thought about adding another extension method of my own, but after looking at the core serilog code I've come to see that I would have reached a dead end upon trying.

**Additional context**
Perhaps other libraries/packages should be adapted to this too if this is taken as an issue.

**Comment by nblumhardt** [comment]
Hi! This doesn't look to be the case to me - though IIRC these changes are fairly recent:

https://github.com/serilog/serilog/blob/e37837ebf5d819ce4cd6702c43154c89a4b764f0/src/Serilog/Core/Logger.cs#L255C1-L271C6

Am I on the same page? Thanks!

**Comment by TheMLGSquid** [comment]
Damn, I didn't see that
I guess my serilog version has not been updated yet, I was sure it was
Thanks a bunch for the response!

**Comment by TheMLGSquid** [comment]
Anyhow, extensions like Microsoft.Logging.Extensions sadly do not utilize this

**Comment by nblumhardt** [comment]
Would be interesting to investigate how we could do something similar via https://github.com/serilog/serilog-extensions-logging, in case you have a chance to take a look over there sometime 👍
