### ISSUE TITLE
Memory leak when logging large json

### ISSUE THREAD

**Issue by cargt3** [serilog/serilog#1982]
I have default logger configuration

```
var logger = new LoggerConfiguration();

Log.Logger = logger.CreateLogger();
```
When i send 30Mb json before hitting controller memory increase by 0.5GB

`_logger.LogInformation($"Controller AddBatch {batch}");`
This line cause increasing memory by 2GB. This memory is never disposed. 

```
        [HttpPost(Name = "Test")]
        public string Test([FromBody] JObject batch)
        {
            _logger.LogInformation($"Controller AddBatch {batch}");
            return "";
        }
```

Edited because i reproduced this on simple example

**Comment by Numpsy** [comment]
Is the ```$"Controller AddBatch {batch}"``` interpolation going to allocate a potentially large string before even hitting Serilog?

Do you really want to be passing an interpolated string to LogInformation? (it might treat a huge json string as a message template when you don't want it to - should it be ```LogInformation("Controller AddBatch {Batch}", batch)``` instead?

**Comment by nblumhardt** [comment]
Hi! Thanks for the note, @cargt3.

Memory leaks are _bad_, so we naturally would want to hunt them down. I don't think that's what's happening here, though: it's most likely that by turning `batch` into a massive string, you're causing .NET to increase the size of the heap/LOH, and although garbage will be collected, this isn't immediate nor is it perfect, so the heap won't drop back to its original size in any fixed amount of time.

You didn't mention the versions of Serilog and Serilog.* that you're using, so I tried reproducing with Serilog 3.1.1 and Serilog.Extensions.Logging 8.0.0:

![image](https://github.com/serilog/serilog/assets/342712/1919a9cc-1c58-44d0-8017-72235db79d29)

Working set shoots up quickly to 700 MB or so on my machine, despite the string allocations in the loop being only ~60 MB.

I can run this program indefinitely and memory use never increases from there, though.

To investigate this as a leak we'd need some more information on:

1. How memory use behaves when running the test case for a long period of time (e.g. with a load test harness pointing at your /test endpoint), and (if memory steadily increases or the machine OOMs)
2. The state of the heap after running the test for a little while: what types make up the majority of the allocations, and where are they rooted?

Thanks!

**Comment by nblumhardt** [comment]
Duplicated here: https://stackoverflow.com/questions/77489290/serilog-memory-leak-when-logging-large-json

**Comment by mrtristan** [comment]
@nblumhardt in case it's helpful i'm suddenly getting `Stackoverflow` exceptions in a few apps across our org upon attempting a log entry having a json prop. I just recently updated from `Serilog.AspNetCore` `5.0.0` to `7.0.0` and `Serilog.Sinks.Console` `4.1.0` to `5.0.0`
