### ISSUE TITLE
LogContext.PushProperty not working when running with OWIN middleware in ASP.Net MVC 5

### ISSUE THREAD

**Issue by mk0sojo** [serilog/serilog#1988]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
When using LogContext.PushProperty in an OWIN middleware to add a correlation ID to all log events, it is only added in the middleware, but not added when logging in a controller which we would expect.

**Reproduction**
Reproduced here https://github.com/mk0sojo/SerilogOwinBug.
It is the Asp.Net MVC on .Net framework template changing the following:
- Add Microsoft.Owin.Host.SystemWeb Nuget package to run OWIN middleware in IIS
- Add Serlog and Serilog.Sinks.Trace from Nuget
- Add a Startup.cs file at the root of the project with the following content:
```csharp
using Microsoft.Owin;
using Owin;
using Serilog;

[assembly: OwinStartup(typeof(SerilogOwinBug.Startup))]

namespace SerilogOwinBug
{
    public class Startup
    {
        // Running the app produces the following log:
        // 2023-11-28 14:25:35Z [RequestId: 123] Starting middleware. URL: "/"
        // 2023-11-28 14:25:35Z [RequestId: ] Hello from Home Controller
        // 2023-11-28 14:25:37Z [RequestId: 123] Ending middleware. URL: "/"
        //
        // Expecting
        // 2023-11-28 14:25:35Z [RequestId: 123] Starting middleware. URL: "/"
        // 2023-11-28 14:25:35Z [RequestId: 123] Hello from Home Controller
        // 2023-11-28 14:25:37Z [RequestId: 123] Ending middleware. URL: "/"
        public Startup()
        {

            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Trace(
                    outputTemplate: "{Timestamp:u} [RequestId: {RequestId}] {Message}"
                 )
                .CreateLogger();
        }
        public void Configuration(IAppBuilder app)
        {
            app.Use<SerilogMiddleware>();
        }
    }
}

```
- Add SerilogMiddleware.cs at the root of the project:
```csharp
using Microsoft.Owin;
using Serilog.Context;
using Serilog;
using System.Threading.Tasks;

namespace SerilogOwinBug
{
    public class SerilogMiddleware : OwinMiddleware
    {
        public SerilogMiddleware(OwinMiddleware next) : base(next)
        {

        }

        public override async Task Invoke(IOwinContext context)
        {
            using (LogContext.PushProperty("RequestId", "123"))
            {
                Log.Information("Starting middleware. URL: {URL}", context.Request.Path);
                await Next.Invoke(context);
                Log.Information("Ending middleware. URL: {URL}", context.Request.Path);
            }
        }
    }
}
```
- Add a log statement to the HomeController.cs file so it looks like this:
```csharp
using Serilog;
using System.Web.Mvc;

namespace SerilogOwinBug.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            Log.Information("Hello from Home Controller");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}
```
- Run the application and open it in a web browser. Check the logs in the Output window. It would look like this:
```
iisexpress.exe Information: 0 : 2023-11-28 14:25:35Z [RequestId: 123] Starting middleware. URL: "/"
iisexpress.exe Information: 0 : 2023-11-28 14:25:35Z [RequestId: ] Hello from Home Controller
...
iisexpress.exe Information: 0 : 2023-11-28 14:25:37Z [RequestId: 123] Ending middleware. URL: "/"
```

**Expected behavior**
Would expect the output to be:
```
iisexpress.exe Information: 0 : 2023-11-28 14:25:35Z [RequestId: 123] Starting middleware. URL: "/"
iisexpress.exe Information: 0 : 2023-11-28 14:25:35Z [RequestId: 123] Hello from Home Controller
...
iisexpress.exe Information: 0 : 2023-11-28 14:25:37Z [RequestId: 123] Ending middleware. URL: "/"

```

**Relevant package, tooling and runtime versions**
Serilog 3.1.1 in a ASP.Net MVC 5 WebApplication running .Net Framework 4.8 on Windows 10.
Microsoft Visual Studio Professional 2022 17.8.0

**Additional context**
This is similar to #517 and #472, but the solution there doesn't seem to work.

**Comment by bartelink** [comment]
I'd suggest asking this on stackoverflow.com - you'll get many more eyes in it there - this repo is for specific granular issues with the core Serilog engine only.

There are [a number of other people using Serilog with ASP.NET](https://www.nuget.org/stats/packages/Serilog.AspNetCore?groupby=Version), so the chances are it's something niggly that's been missed somewhere in your config rather than an outright bug.

Thanks for making the time to do a repro, but to actually action this as a bug would involve a failing test in one repo. Rest assure the fact that you have code demonsrtating the problem is definitely not wasted time - anyone assisting you in narrowing it down will benefit from that.

**Comment by bartelink** [comment]
Thanks for logging https://stackoverflow.com/questions/77566707/serilog-logcontext-pushproperty-not-working-with-owin-middleware-in-asp-net-mvc
Answers over there much appreciated!
