### ISSUE TITLE
Support for extra properties not included in the message template

### ISSUE THREAD

**Issue by object** [serilog/serilog#199]
I am refactoring logging for a large application that is using Microsoft's Logging Application Block. Current implementation enriches log events with extra properties in a similar way to how it's done by Serilog, but it also supports sending extra properties that will be logged as a part of the log event but not rendered in a text message. This is what I am missing in Serilog: to make a set of key-value pairs handled by Serilog I must include it in a message template. Even use of custom enrichers won't help: only properties included in a message templates are accessible for enrichers.

It would be great to have an overload like this:

Debug(IDictionary<string, object> extraProperties, string messageTemplate, params object[] propertyValues);

The set of extra properties would be serialized into rich log sinks such as document databases or JSON converters but wouldn't affect plain text sinks.

**Comment by timcapps** [comment]
Is there a way to achieve this same behavior in a library .dll using Liblog?

**Comment by nblumhardt** [comment]
@timcapps might be one to ask on the LibLog issue tracker, not sure.

**Comment by timcapps** [comment]
@nblumhardt will do. Thank you!
