### ISSUE TITLE
Interesting perf stats: Serilog vs NLog

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog#1990]
Was just looking at the latest perf stats for Serilog vs NLog: https://github.com/panchengtao/LoggingPerformance/issues/1#issuecomment-1848956863

Interesting to see the results. 

This is more of a `discussion`, than a bug or request. Maybe there's someone hardcore coders around here that might be inspired to try and close the gap between the two?

Just an FYI 🍰 

DISCLAIMER: this could be comparing apples to cars ... I've not spent any time validating the comparison _code_. Just that the author (of the linked comment, above) does contribute to the NLog repo.

**Comment by nblumhardt** [comment]
Hi! If you're keen to try boosting Serilog's numbers in this particular scenario, _Serilog.Sinks.File_ would be the place to start digging around.

Serilog balances a bunch of usability/ergonomic/maintainability/performance trade-offs that are different from NLog's. It's always good to look out for opportunities to improve perf, but a single benchmark without surrounding context isn't by itself a useful starting point for any work, here, so I'll close this.

Thanks!

**Comment by bartelink** [comment]
IME, as someone who migrated to Serilog ~4y ago, contention in the face of concurrency is a major factor in the through[put of actual systems doing work besides logging 
 (not 1/2/3 threads continually blasting messages in an artificial benchmark; a real application being pushed in a load test). `Serilog.Sinks.Async` probably has room for improvement (It could probably gain perf from re-implementing with `System.Theading.Channels`), but it fundamentally works, and the code is not scary. The fact that an implementation is small and decoupled, and has good tests should be of paramount concern.
