### ISSUE TITLE
serilog JSON format using original field names

### ISSUE THREAD

**Issue by contione** [serilog/serilog#1992]
Starting from version 3.1, TraceId and SpanId have been introduced and are now written in JSON format as @tr and @sp. How can I use TraceId and SpanId directly without using abbreviations? How should I handle this?

Current
{
"time": "2023-12-27T16:05:49.961610672+08:00",
"@t": "2023-12-27T08:05:49.9614905Z",
"@mt": "xxxxxx",
"https://github.com/tr": "88a772ee01ba9638826404854610b04b",
"@sp": "baa96aeaf9601eac",
"ConnectionId": "0HMVS8LGKQ6UQ"
}

expect
{
"time": "2023-12-27T16:05:49.961610672+08:00",
"@t": "2023-12-27T08:05:49.9614905Z",
"@mt": "xxxxxx",
"TraceId": "88a772ee01ba9638826404854610b04b",
"SpanId": "baa96aeaf9601eac",
"ConnectionId": "0HMVS8LGKQ6UQ"
}

**Comment by bartelink** [comment]
Best place to ask these questions is by putting a question on stackoverflow.com with the tag `serilog` - anyone that watches this repo will see it there. Suggest conveying what your goal is as part of the question - what are you doing, what's the goal, show code you have so far, show what output you're aiming for, etc

**Comment by contione** [comment]
Current
{
	"time": "2023-12-27T16:05:49.961610672+08:00",
	"@t": "2023-12-27T08:05:49.9614905Z",
	"@mt": "xxxxxx",
	"@tr": "88a772ee01ba9638826404854610b04b",
	"@sp": "baa96aeaf9601eac",
	"ConnectionId": "0HMVS8LGKQ6UQ"
}

expect
{
	"time": "2023-12-27T16:05:49.961610672+08:00",
	"@t": "2023-12-27T08:05:49.9614905Z",
	"@mt": "xxxxxx",
	"TraceId": "88a772ee01ba9638826404854610b04b",
	"SpanId": "baa96aeaf9601eac",
	"ConnectionId": "0HMVS8LGKQ6UQ"
}

**Comment by contione** [comment]
> Best place to ask these questions is by putting a question on stackoverflow.com with the tag `serilog` - anyone that watches this repo will see it there. Suggest conveying what your goal is as part of the question - what are you doing, what's the goal, show code you have so far, show what output you're aiming for, etc

Okay, thanks for the advice.

**Comment by bartelink** [comment]
Thanks!; question on SO: https://stackoverflow.com/questions/77720978/serilog-json-format-using-original-field-names
