### ISSUE TITLE
Unpin `AssemblyVersion`

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#1996]
Came here via https://github.com/serilog/serilog-extensions-logging/issues/238

The strategy of pinning our assembly version to 2.0.0.0 forever was very successful in the era of binding-redirect-misery. Times have changed, tools have improved, and now I think it's no longer pulling its weight.

In 4.x, let's consider unpinnig, and just use precise versions for the assembly.

**Comment by avichay-kardash** [comment]
Hello,
Using .net 4.7.2 and Serilog 3.1.1, our application encounters the same issue as described on [serilog-extensions-logging](https://github.com/serilog/serilog-extensions-logging/issues/238) 

How difficult would it be to create a new version of Serilog (3.1.2) with unpinned assembly version 2.0.0.0?

**Comment by nblumhardt** [comment]
@avichay-kardash unfortunately this change will result in some non-trivial breakage in consuming projects; I've just opened PR #2015 to get the 4.0 ball rolling, which is the best we can do, I think.

**Comment by avichay-kardash** [comment]
Thank you @nblumhardt 
Is there an ETA for version 4.0?

**Comment by nblumhardt** [comment]
@avichay-kardash not at this stage, unfortunately. The prerelease version on NuGet is pretty much exactly 3.1.1 with an unpinned assembly version, so it'd reasonable to pull that in if you're able to in a pinch.
