### ISSUE TITLE
Support for .NET 8

### ISSUE THREAD

**Issue by ehavelaarsnz** [serilog/serilog#2004]
I'm trying to upgrade my Azure Function App to .NET 8.  I have upgraded all Nuget packages, so I am on Serilog 3.1.1
It does not list net8.0 in the dependencies, and when I try to run my function, it hits this line

``` csharp
            LevelSwitch.MinimumLevel = LogEventLevel.Verbose;
```

and then dies with this exception

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=Serilog
  StackTrace:
   at Serilog.Core.LoggingLevelSwitch.set_MinimumLevel(LogEventLevel value)
```

**Comment by ehavelaarsnz** [comment]
My colleague tells me in-process. This was working under .NET 6; has there been a change?

**Comment by nblumhardt** [comment]
In-process apps don't support .NET 8, might be one to dig around in the Azure Functions docs/blog for. Closing as we can't action it here, but good luck with it!
