### ISSUE TITLE
Crash with serilog 3.1.0/3.1.1

### ISSUE THREAD

**Issue by barnabas90** [serilog/serilog#2006]
**Description**
Crash with 3.1.0/3.1.1 with a net framework 4.7.2 app. 
System.IO.FileNotFoundException, could not load file or assembly System.Diagnostics.DiagnosticSource version 7.0.0.2, pubkeytoken cc7b..., or one of its dependencies, the system cannot find the file specified.
The serilog package says the minversion of that dependency is 7.0.2, I tried to install 7.0, ..., 8.0, nothing worked.

Downgrading to 3.0.1 is a workaround.

**Reproduction**
Try to write an informational log entry.

**Expected behavior**
No crash

**Relevant package, tooling and runtime versions**
VS 2022 latest, .net 4.7.2 targeted app

**Comment by nblumhardt** [comment]
Hi! This one will be specific to your deployment - something in the GAC, etc., - best bet there will be to enable assembly bind logging and track it down at runtime. HTH!

**Comment by nblumhardt** [comment]
(Here's the CI test run for that version, with .NET Framework tests included: https://ci.appveyor.com/project/serilog/serilog/builds/48492594/job/m10a8yjeylhfvvg0 - HTH!)
