### ISSUE TITLE
log levels reading order

### ISSUE THREAD

**Issue by AcernisSupport** [serilog/serilog#2007]
Good evening
I'm using your log system.
In the implementation I am not using the minimum log level system.
If I use the information level everything works but if I use the debug level it doesn't write any values to me either in the console or in the file.
I wanted to know what is the highest value that will allow me to write all the data
For the selection of levels I am implementing them in code.
How can I solve the problem
Thanks and good job

**Comment by nblumhardt** [comment]
`MinimumLevel.Is(LevelAlias.Minimum)` will take care of this. HTH!
