### ISSUE TITLE
JObject/JToken objects are not properly serialized

### ISSUE THREAD

**Issue by object** [serilog/serilog#201]
Here is the sample code:

```
        var json = JToken.FromObject(_person);
        // Alternative: var json = JObject.Parse(JsonConvert.SerializeObject(_person));
        _logger.Debug("This is a JSON representation of {Person}", json);
        _logger.Debug("This is also a JSON representation of {@Person}", json);
```

where Person is a simple class with a few properties.

And here is the output in rolling file sink using JsonFormatter:

{"Timestamp":"2014-08-28T13:22:15.5280000+02:00","Level":"Debug","MessageTemplate":"This is a JSON representation of {Person}","RenderedMessage":"This is a JSON representation of [[[]], [[]], [[]], [[[[]]]], [[]]]","Properties":{"Person":[[[]],[[]],[[]],[[[[]]]],[[]]]}}

{"Timestamp":"2014-08-28T13:22:15.6030000+02:00","Level":"Debug","MessageTemplate":"This is also a JSON representation of {@Person}","RenderedMessage":"This is also a JSON representation of [[[]], [[]], [[]], [[[[]]]], [[]]]","Properties":{"Person":[[[]],[[]],[[]],[[[[]]]],[[]]]}}

The best would be to to render JSON as json, i.e. attach a JSON to "Person" property. But current implementation causes just a series of square brackets to be written which I guess is wrong.

**Comment by MonDeveloper** [comment]
2018 and the problem is still here :(
Any resolution out there?

**Comment by nblumhardt** [comment]
It's literally the very first result if you Google "serilog json.net" :-)
