### ISSUE TITLE
Aggregate consecutive identical log message lines

### ISSUE THREAD

**Issue by middiu** [serilog/serilog#2012]
Hello there,
Is there a plugin/filter/sink (or any other sort of code) for Serilog that would aggregate consecutive identical log messages to something like this:

```
[DB] [MyClass] This is a message
[DB] [MyClass] This is a message
[DB] [MyClass] This is a message
Plus 97 more
```

I have some situations where I have a LogDebug inside a Loop, an in some circumstances an identical log is printed dozens of times, for example in this code

```
//myLargeList as 1000 items and all of them raise the same exception
foreach(var item in myLargeList){
  try{
   //do something here with item that throw an Exception
  }catch(Exception e){
    logger.LogDebug("This is a message")
  }
}
```
Is there anything in Serilog that can help me with this?

Thanks

**Comment by nblumhardt** [comment]
Hi @middiu,

This is one to handle in your program - something as simple as a `bool errorMessageEmitted = false` and then a check/set of that variable in the `catch` block will do it.

It's possible to attempt this in the logging pipeline, but it'll be much more complex, fragile, and compute intensive than the direct approach.

Hope this helps!
Nick
