### ISSUE TITLE
Update Formatting-Output wiki to include trace id and span id documentation

### ISSUE THREAD

**Issue by RandomBuffer** [serilog/serilog#2021]
**Is your feature request related to a problem? Please describe.**
No, just requesting a simple documentation fix to some missing information in the wiki.

**Describe the solution you'd like**
Currently **TraceId** and **SpanId** are not documented in  https://github.com/serilog/serilog/wiki/Formatting-Output. However they seem to work in .NET 8 and <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" /> based on an example I found here earlier. Please add these properties to the wiki with wording can be copied over from https://github.com/serilog/serilog-formatting-compact like below.

**TraceId** - The id of the trace that was active when the event was created, if any
**SpanId** - The id of the span that was active when the event was created, if any

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nblumhardt** [comment]
Done, thanks 👍
