### ISSUE TITLE
Add FTP Sink to serilog

### ISSUE THREAD

**Issue by Msalehip** [serilog/serilog#2026]
Is there any way to create files and send logs to ftp server?

**Comment by nblumhardt** [comment]
Hi! There's no plan to do anything in this area, but you may find some implementations out on the 'net.

Personally, I'd try writing local files with Serilog.Sinks.File, and use a synchronization utility to upload them periodically to your FTP server.

(Or just do away with FTP and use a network-based log collector.)

HTH,
Nick
