### ISSUE TITLE
Please may you add a new formatting token 'UTCTimestamp'  to MessageTemplateTextFormatter 

### ISSUE THREAD

**Issue by MatthewHays** [serilog/serilog#2050]
Currently I'm trying to convert logevent timestamps to UTC when they get logged to the file sink (and others that use the message template renderer)

I can set this as my output template

> {Timestamp:u} [{Level:u3}] [{RequestId}] {Message:j}{NewLine}{Exception}

The :u converts the datetimeoffset to UTC, but formats to **yyyy-MM-dd HH:mm:ssZ** when I want **yyyy-MM-dd HH:mm:ss.fffZ**

If you had an explicit UTCTimestamp token, then this could be inserted near line 101 in MessageTemplateTextFormatter.cs

> else if (pt.PropertyName == OutputProperties.UTCTimestampPropertyName)
> {
>    ScalarValue.Render(logEvent.Timestamp.ToUniversalTime(), writer, pt.Format, _formatProvider);
> }
> 

This means I could then set my template to be

> {UTCTimestamp:yyyy-MM-dd HH:mm:ss.fffZ} [{Level:u3}] [{RequestId}] {Message:j}{NewLine}{Exception}

I know I can use the expression editor for this, but it feels rather heavy weight for such a small thing, and I'm sure a number of others would really appreciate being able to log in UTC with a custom format

Thanks

**Comment by bartelink** [comment]
Assuming it was approved, would you be willing to do the PR for it, inc some minimal tests?

**Comment by MatthewHays** [comment]
Sure, it seems a pretty straightforward change. Do I need any special permissions to make a mere request?

**Comment by bartelink** [comment]
(This is subject to @nblumhardt or others not being able to think of a better way to achieve your intent without adding code)

>Do I need any special permissions to make a merge request?

No - nobody makes brnahces in the repo. TLDR The process is:
- clone the repo
- make a branch in your local with the change
- push
- go to github.com and there willl be a link ot make a PR

**Comment by bartelink** [comment]
See also https://github.com/serilog/serilog/issues/1024#issuecomment-338518695 and the other things linked to that as workarounds
(IIRC I used that, but it feels like it should be in the box. The tradeoff is of course that every token that gets added occupies more space in the docs, but I think I'd vote for it as core funcionality)

**Comment by MatthewHays** [comment]
Thanks, I've created the pull request seeing @nblumhardt 's thumbs up on my proposal. I hope that means he's ok with it, happy to change anything off of any feedback.
