### ISSUE TITLE
Serilog files creation when change the date backwards will not created new file unless restart 

### ISSUE THREAD

**Issue by Minasardari** [serilog/serilog#2056]
When I change date backward in system my app doesn’t creat new file for log in new date and keeps writing to old file wih old date unless restart the window 
Note: it is working good on forwarding dates

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. This is by intentional: rolling intervals determine when a new file is created, not what events go into which file. (It's even possible for log events that arrive "late" for the previous interval to end up in the file created for the following one.)

**Comment by Minasardari** [comment]
Thank you for your response is there any way I can set the logfile to new date without restarting windows.

**Comment by Minasardari** [comment]
The app has feature to change date inside app not in windows how can I set serilog to start with new date

**Comment by nblumhardt** [comment]
Just restarting the app would work; but, if you can't restart the app, you could try using `ReloadableLogger` from https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/Extensions/Hosting/ReloadableLogger.cs#L57 and calling `Reload(lc => ..)` whenever you want to reload the file sink. HTH!
