### ISSUE TITLE
RenderMessage ignores the ':l' (literal) specifier in the Enrich method

### ISSUE THREAD

**Issue by alekdavisintel** [serilog/serilog#2059]
**Description**
My app writes two logs: one to console, another to a text file. When logging to console, I need to escape all new lines in the messages and exceptions (that's because we send the console messages to the Azure event hub which treats new lines as log message separators messing up the log format). When logging to a text file, I want to preserve new lines.

To escape new lines in the console output, I implemented a log event enricher, which renders the message from the log event, escapes new lines, and sets the escaped message value as a new property named `EscapedMessage` (I do the same for the exceptions, but let's ignore these, since the idea is the same). The problem is that if I use the literal specifier in the log message template format (e.g. `[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedMessage:lj}`, when I call the `RendedMessage` method in the `Enrich` method, the `:l` modifier gets ignored and all log message parameters get enclosed in double quotes, which I do not need (for a few reasons that I can go over if needed). 

**Reproduction**
Implement an enricher as:

```csharp
public class EscapedMessageEnricher: ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        if (logEvent.MessageTemplate == null)
        {
            return;
        }

        string message = logEvent.RenderMessage();

        LogEventProperty logEventProperty = propertyFactory.CreateProperty(
            "EscapedMessage",
            message
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
        );

        logEvent.AddPropertyIfAbsent(logEventProperty);
    }        
}
```
Set the `WithEscapedMessage` logging extension:

```csharp
public static class LoggingExtensions
{
    public static LoggerConfiguration WithEscapedMessage(
        this LoggerEnrichmentConfiguration enrich)
    {
        return enrich == null ? throw new ArgumentNullException(nameof(enrich)) : enrich.With<EscapedMessageEnricher>();
    }

    public static LoggerConfiguration WithEscapedException(
        this LoggerEnrichmentConfiguration enrich)
    {
        return enrich == null 
            ? throw new ArgumentNullException(nameof(enrich)) 
            : enrich.With<EscapedExceptionEnricher>();
    }
}
```

In the console sink's configuration, set the log event template to use `EscapedMessage`, e.g.:

`[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] {EscapedMessage:lj}\n`

In the Serilog setup or configuration file, define the `WithEscapedMessage` enricher, e.g.:
```
  "Serilog": {
    ...
    "Enrich": [
      ...
      "WithEscapedMessage"
    ],
```

In the application, write a log with string parameters as:
```csharp
logger.LogInformation("Testing '{a}'.", "xyz");
```

**Expected behavior**
I expect the output to look something like:
```
[2024-05-07 09:08:16.833868 -07:00] [INF] Testing 'XYZ'.
```
But I get:
```
[2024-05-07 09:08:16.833868 -07:00] [INF] Testing "'XYZ'".
```

**Relevant package, tooling and runtime versions**
Using Serilog 3.1.1 on Windows (the app gets deployed to Linux and Windows).

**Additional context**
There is a chance that I'm totally missing something and there is a better way to do what I need to do, but I could not find any suggestions. The basic problem we are trying to solve is the Azure event hub behavior that cannot read event messages with new lines, so it splits them into multiple events that messes the log structure. We push messages from Azure to Splunk, so when we escape new lines, on the Splunk end, we change them back to the original new lines, which works great, except all the quoted message parameters.

It's a bit more complicated than I described because we also need to handle the case of exception, so we use Serilog expressions and the actual log entry looks like this:
```
[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedMessage:lj}\n{#if @x is not null}[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedException:lj}\n{#end}
```
I know it's ugly, but I could not figure out how else we can do this. For the purpose of the `:l` specifier handling, I do not think this is relevant, but I thought I would mention it just in case.

Also, if I add the `:l` to the parameter specifier, (e.g., `logger.LogInformation("Testing '{a:l}'.", "xyz");`), it works fine, but this means for every log entry we need to remember to include `:l` and I'm sure people will forget to do it, so I'd rather have the global setting in the template, and I think that's how it is supposed to work.

**Comment by nblumhardt** [comment]
Hi @alekdavisintel! Thanks for dropping by.

This is a bit of any annoying limitation in how the default message template rendering works. #2011 touches on it, but it's not looking likely to make it into v4 at this stage.

Fortunately, you appear to be using `Serilog.Expressions`, which provides some better options for doing what you're after (and doesn't need `:l` and `:j` etc. - they're the built-in defaults).

In a nutshell, your expression template will look like:

```
[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapeNewlines(@m)}
```


The change is the `EscapeNewlines(@m)` call; this will be a user-defined formatting function you add when setting up the logger:

```csharp
    .WriteTo.Console(new ExpressionTemplate(
        "the template from above",
        nameResolver: new StaticMemberNameResolver(typeof(EscapingFunctions)))
```

Its definition:

```csharp
public static class MyFunctions
{
    public static LogEventPropertyValue? EscapeNewlines(
        StringComparison comparison,
        LogEventPropertyValue? maybeMessage)
    {
        if (maybeMessage is ScalarValue sv && sv.Value is string s)
            return new ScalarValue(s
                .Replace("\r", "\\r")
                .Replace("\n", "\\n"));

        return null;
    }
}
```

See also: https://github.com/serilog/serilog-expressions/?tab=readme-ov-file#implementing-user-defined-functions

Not tested so you may need to tweak some of this, but should be pretty close. Keen to hear how it goes!

**Comment by alekdavisintel** [comment]
Thank you, @nblumhardt. I appreciate a quick response and the suggestion. If this works, it's actually a better apprach that my custome property thing. Question: **How do I configure the `nameResolver` setting in the configuration file?** Because we do different things in different environments, we set up Serilog configuration via the `appSettings` files (then we can easily merge between global, dev, test, prod, etc). Currently, the global setting looks like this:
```json
  "Serilog": {
    "Using": [
      "Destructurama.Attributed",
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File",
      "Serilog.Enrichers.ClientInfo",
      "Serilog.Enrichers.Environment",
      "Serilog.Enrichers.Thread",
      "Serilog.Enrichers.Process",
      "Serilog.Enrichers.Sensitive",
      "Serilog.Exceptions",
      "Serilog.Expressions",
      "<OurCustomLibraryImplementingSerilogExtensions>"
    ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "Microsoft.AspNetCore": "Warning",
        "Microsoft.AspNetCore.Mvc": "Warning",
        "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter": "Warning",
        "CorrelationId.CorrelationIdMiddleware": "Warning"
      }
    },
    "Enrich": [
      "FromLogContext",
      "WithClientIp",
      "WithClientAgent",
      "WithMachineName",
      "WithThreadId",
      "WithProcessId",
      "WithExceptionDetails",
      "WithEscapedMessage",
      "WithEscapedException"
    ],
    "Destructure":
    [
      {
        "Name": "UsingAttributes"
      }
    ],
    "WriteTo": {
      "0": {
        "Name": "Console",
        "Args": {
          "formatter": {
            "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
            "template": "[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedMessage:lj}\n{#if @x is not null}[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedException:lj}\n{#end}"
          }
        }
      }
    }
  },
```
Thanks again.

**Comment by nblumhardt** [comment]
Hi @alekdavisintel,

Currently you need to do:

```csharp
public static class MyFunctions
{
    public static NameResolver NameResolver { get; } = new StaticMemberNameResolver(typeof(MyFunctions));

    // As before
```

And:

```json
          "formatter": {
            "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
            "template": "[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedMessage:lj}\n{#if @x is not null}[{@t:yyyy-MM-dd HH:mm:ss.ffffff zzz}] [{@l:u3}] [{MachineName}] [{ProcessId}:{ThreadId}] [{CorrelationId}] [{ClientIp}] [{UserName}] [{ApplicationId}] [{SourceContext}] [{ActionName}] [{MethodName}] {EscapedException:lj}\n{#end}",
            "nameResolver": "MyNamespace.MyFunctions::NameResolver, MyAssembly"
          }
```

Untested, so may need some tweaking. [Original feature PR](https://github.com/serilog/serilog-settings-configuration/issues/287).

**Comment by alekdavisintel** [comment]
Awesome! It works. Btw, just realized, that for the bootstrap logger, I also need to use the way to programmatically set up the name resolver, so I used both the programmatic and configuration options. Thank you so much.

Just an FYI if anyone needs the programmatic approach, in the example above `EscapingFunctions` should be `MyFunctions` (i.e. it must reference the class implementing the `EscapeNewlines` method):
```
    .WriteTo.Console(new ExpressionTemplate(
        "the template from above",
        nameResolver: new StaticMemberNameResolver(typeof(EscapingFunctions)))
```
Should be:
```
    .WriteTo.Console(new ExpressionTemplate(
        "the template from above",
        nameResolver: new StaticMemberNameResolver(typeof(MyFunctions)))
```
