### ISSUE TITLE
Serilog v3.1.1 throws an exception with System.Diagnostics.DiagnosticSource v8.0.0

### ISSUE THREAD

**Issue by jaminman** [serilog/serilog#2061]
**Description**
Serilog version 3.1.1 NuGet package shows a dependency on [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/) (>= 7.0.2).  When updating System.Diagnostics.DiagnosticSource to version 8.0.0, I get the following exception thrown when I hit a line of logging code (see Reproduction section): 

> System.IO.FileLoadException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Here is additional information from the pre-bind state (project name blocked):
> === Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Work/Repos/XXXXX/Xxxx.Xxxxxx.Xxxx/bin/Local/net48
LOG: Initial PrivatePath = NULL
Calling assembly : Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Work\Repos\XXXXX\Xxxx.Xxxxxx.Xxxx\bin\Local\net48\Xxxx.Xxxxxx.Xxxx.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Attempting download of new URL file:///C:/Work/Repos/XXXXX/Xxxx.Xxxxxx.Xxxx/bin/Local/net48/System.Diagnostics.DiagnosticSource.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Reproduction**
Upgrading the package version.
```xml
<PackageReference Include="Serilog" Version="3.1.1" />
<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.0" />
```

Code snippet of where the exception was thrown:
```csharp
Logger.Debug("Request {ServiceName}.{Method}() was received.", ObjectName, LogDetailExt.GetMethodName());
```

**Expected behavior**
To allow for updating dependent of packages.

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?
Using Serilog version 3.1.1 on Windows 11 using .Net framework 4.8 (WCF solution).  It was crashing on my dev laptop.  So, I couldn't push to server.  Server is Windows 2016.

**Additional context**

**Comment by nblumhardt** [comment]
Hi! This combination of targets and packages works fine for me, and given the large amount of Serilog usage on .NET 4.8 it's likely we'd see more reports if the problem here lay with Serilog itself.

My best guess is that your build setup isn't generating assembly binding redirects correctly for some reason or other. Unfortunately this kind of issue is not much fun to debug, but should be info out there. Good luck with it!

**Comment by hellobody** [comment]
Looks like I get the same issue. The issues is random. Sometimes there is an exception, sometimes there is no one.
Hi @jaminman, did you solve that issue? Could you please share your findings?

**Comment by hellobody** [comment]
Just crashes here sometimes:
![image](https://github.com/serilog/serilog/assets/1161879/4be5602c-257c-4b24-9c40-74a513954478)
Tried to downgrade packages. Tried to delete bin folder and rebuild.
System.Diagnostics.DiagnosticSource.dll is there.

**Comment by nblumhardt** [comment]
Hi; my bet here is that there's a different Serilog version in the GAC from the one expected by the app.

Updating your app to Serilog 4, which uses a different assembly versioning scheme, should fix this. Let me know if this helps!

**Comment by hellobody** [comment]
Hey Nicholas.
At least for me the issue is somehow gone. Not sure what caused it.
But I didn't use Serilog on my PC before and I installed it via NuGet package first time I believe.
What I did is I moved Serilog configuration code into other project in my solution.
