### ISSUE TITLE
Question: v4 roadmap/release date

### ISSUE THREAD

**Issue by dario-griffo-paytently** [serilog/serilog#2071]
Thanks for all the effort and continue improvement of Serilog!
We are starting a project from scratch and leveraging on OTEL for our observability, we are using serilog-otel package and serilog v4, both on pre-release mode.
Do you have a roadmap to know when they will become stable?

**Comment by bartelink** [comment]
https://github.com/serilog/serilog/pull/2067#issuecomment-2138753536

**Comment by dario-griffo-paytently** [comment]
Amazing thanks!
Closing this :100:
