### ISSUE TITLE
Unpinning the assembly version in just Serilog and not the remaining packages results in incompatibilities

### ISSUE THREAD

**Issue by jcasale** [serilog/serilog#2073]
**Description**
I maintain a PowerShell v5.1 binary module that exposes some Serilog logging functionality as binary cmdlets.

I reference the following packages:

- Serilog (v4.0.0)
- Serilog.Enrichers.Environment (v2.3.0)
- Serilog.Enrichers.GlobalLogContext (v3.0.0)
- Serilog.Enrichers.Process (v2.0.2)
- Serilog.Enrichers.Thread (v3.1.0)
- Serilog.Expressions (v4.0.0)
- Serilog.Sinks.Async (v1.5.0)
- Serilog.Sinks.Console (v5.0.1)
- Serilog.Sinks.Email (v3.0.0)
- Serilog.Sinks.EventLog (v3.1.0)
- Serilog.Sinks.File (v5.0.0)

Although tests work fine, the resulting binary module cannot be loaded in an instance of the PowerShell without throwing a binding error:
```
Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies.
```

**Reproduction**
See the dev branch of [PSSerilog](https://github.com/jcasale/PSSerilog/tree/dev).

I have modified the project to run with just Serilog v4.0.0 (which it does) and individually with each of the remaining packages resulting in the error individually for each.

**Expected behavior**
No binding errors when the module is loaded into an instance of PowerShell.

**Relevant package, tooling and runtime versions**
I am using Serilog v4.0.0 with .net framework v4.6.2 on Windows.

**Additional context**
There are no versions of Serilog in the GAC (and no other assemblies in the GAC that reference it).

The problem manifests on a clean version of Windows Server 2022.

**Comment by nblumhardt** [comment]
Hi! Thanks for the heads-up. Unfortunately, even when the mentioned packages catch up, future changes will result in fragility, here.

https://stackoverflow.com/questions/24181557/powershell-config-assembly-redirect has details on how this can be solved, you might wish to make the resolve handler a bit more specific, but the general idea will work in this situation.

Hope this helps,
Nick
