### ISSUE TITLE
Publish Serilog 4.0.0 versions of all `serilog` org packages

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#2075]
Better perf, new APIs (+obsoletions), fewer dependency issues.

 - [x] Serilog.Expressions - https://github.com/serilog/serilog-expressions/pull/111
 - [x] Serilog.Sinks.PeriodicBatching - https://github.com/serilog/serilog-sinks-periodicbatching/pull/87
 - [ ] ~~Serilog.Extensions.Logging~~ - it'll be best to hold this until the 9.0.0 in a few months, since the dependency update will be breaking
 - [ ] ~~Serilog.Settings.Configuration~~ - as for s.e.Logging
 - [x] Serilog.Sinks.OpenTelemetry - https://github.com/serilog/serilog-sinks-opentelemetry/pull/140
 - [x] Serilog.Sinks.Async - https://github.com/serilog/serilog-sinks-async/pull/96
 - [x] Serilog.Sinks.EventLog - https://github.com/serilog/serilog-sinks-eventlog/pull/57
 - [ ] ~~Serilog.AspNetCore~~ - as for s.e.Logging
 - [ ] ~~Serilog.Extensions.Hosting~~ - as for s.e.Logging
 - [x] Serilog.Sinks.Email - https://github.com/serilog/serilog-sinks-email/pull/134
 - [x] Serilog.Sinks.Console - https://github.com/serilog/serilog-sinks-console/pull/158
 - [x] Serilog.Formatting.Compact - https://github.com/serilog/serilog-formatting-compact/pull/67
 - [x] Serilog.Enrichers.Environment - https://github.com/serilog/serilog-enrichers-environment/pull/64
 - [x] Serilog.Sinks.Trace - https://github.com/serilog/serilog-sinks-trace/pull/27
 - [x] Serilog.Sinks.File - https://github.com/serilog/serilog-sinks-file/pull/312
 - [x] Serilog.Enrichers.Thread - https://github.com/serilog/serilog-enrichers-thread/pull/23
 - [x] Serilog.Enrichers.Process - https://github.com/serilog/serilog-enrichers-process/pull/26
 - [x] Serilog.Formatting.Compact.Reader - https://github.com/serilog/serilog-formatting-compact-reader/pull/41
 - [x] Serilog.Sinks.BrowserConsole - https://github.com/serilog/serilog-sinks-browserconsole/pull/28
 - [ ] ~~Serilog.Sinks.Xamarin~~ &mdash; future of this project needs to be figured out
 - [ ] ~~Serilog.Extensions.Logging.File~~ as for s.e.Logging
 - [ ] ~~Serilog.Sinks.RollingFile~~ &mdash; may be best archived now, too
 - [x] Serilog.Sinks.TextWriter - https://github.com/serilog/serilog-sinks-textwriter/pull/9
 - [x] Serilog.Settings.AppSettings - https://github.com/serilog/serilog-settings-appsettings/pull/53
 - [x] Serilog.Sinks.Debug - https://github.com/serilog/serilog-sinks-debug/pull/15
 - [x] Serilog.Sinks.Map - https://github.com/serilog/serilog-sinks-map/pull/35
 - [x] Serilog.Sinks.Observable - https://github.com/serilog/serilog-sinks-observable/pull/12

**Comment by Numpsy** [comment]
I started making some changes for Serilog.Enrichers.Process in https://github.com/serilog/serilog-enrichers-process/pull/25

**Comment by Numpsy** [comment]
Some updated for Serilog.Sinks.Debug at https://github.com/serilog/serilog-sinks-debug/pull/14

**Comment by cremor** [comment]
> * [ ]  ~Serilog.Extensions.Logging~ - it'll be best to hold this until the 9.0.0 in a few months, since the dependency update will be breaking
> * [ ]  ~Serilog.AspNetCore~ - as for s.e.Logging

Can the current version of Serilog.AspNetCore be used with Serilog 4.0, event though it was build for Serilog 3.x?

**Comment by Numpsy** [comment]
fwiw I'm using Serilog.Extensions.Hosting v8 with Serilog 4 and that seems ok

**Comment by Numpsy** [comment]
Serilog.Sinks.TextWriter - https://github.com/serilog/serilog-sinks-textwriter/pull/8

**Comment by Numpsy** [comment]
Serilog.Sinks.Observable - https://github.com/serilog/serilog-sinks-observable/pull/11

**Comment by Numpsy** [comment]
WIP settings for Serilog.Settings.AppSettings at https://github.com/serilog/serilog-settings-appsettings/pull/52/files

**Comment by nblumhardt** [comment]
Done! Thanks to everyone who contributed to this release 😎
