### ISSUE TITLE
Add disposal support to ILogger

### ISSUE THREAD

**Issue by dengel-rnd** [serilog/serilog#2076]
I'm running unit/integration tests that include writing logs through various loggers (and therefore not appropriate for using the static Log object) to a directory. At the end, I want to clean up (delete) the directory. This is being impeded by the fact that the application currently has open streams connected to files in that directory.

Adding a "CloseAndFlush" to the logger itself (not just the static Log object) would solve this.

I get that most uses within a normal application flow would not need this, but I can't think of a downside to having the capability. My desire to delete the files is what prompted my search for this capability in this particular case, but there may also be other use cases where this is helpful. Who knows what needs can arise in non-trivial applications?

I've tried looking for ways to dispose the logger, access the individual sink to dispose it, etc.

Another way to address this /could/ be for the File sink to always open-write-close the log file. Even then, it would be helpful in the case above (and possibly other cases) to at least have a Flush() method to ensure flushing with a buffered log.

**Comment by nblumhardt** [comment]
Hi @dengel-rnd; the `Logger` object returned from `CreateLogger()` implements `IDisposable` (and `IAsyncDisposable`) for this purpose. HTH!

**Comment by dengel-rnd** [comment]
Seriously!?

I wonder how I missed that.

Get BlueMail for Android<https://bluemail.me>
On Jun 5, 2024, at 7:18 PM, Nicholas Blumhardt ***@***.******@***.***>> wrote:
CAUTION: This email originated from outside of The RND Group. Do not click links or open attachments unless you recognize the sender and you are certain the content is safe.


Hi @dengel-rnd<https://github.com/dengel-rnd>; the Logger object returned from CreateLogger() implements IDisposable (and IAsyncDisposable) for this purpose. HTH!
