### ISSUE TITLE
Wrong links in the release notes

### ISSUE THREAD

**Issue by cremor** [serilog/serilog#2077]
The [release notes](https://github.com/serilog/serilog/releases/tag/v4.0.0) for version 4.0.0 contain links to non-existing HTML anchors:

> assembly version number has [been unpinned](https://github.com/serilog/serilog/releases/tag/v4.0.0#2015)
> Sinks that need batching functionality [can now be easily written](https://github.com/serilog/serilog/releases/tag/v4.0.0#2055),
> message templates [can be used](https://github.com/serilog/serilog/releases/tag/v4.0.0#2063)

I assume those should all be links to issues.

**Comment by nblumhardt** [comment]
Thanks for taking the time to let us know! I've fixed this now 👍
