### ISSUE TITLE
Memory leak with version 4.0.0, ASP.NET Core 8.0.1, .NET 8 and docker

### ISSUE THREAD

**Issue by PawelTroka** [serilog/serilog#2080]
We are getting huge memory leaks, memory just keeps growing fast until the app restarts. The problem disappears when we don't use Serilog.

Packages:
```
  <PackageReference Include="Serilog.AspNetCore" Version="8.0.1"/>
  <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
  <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0"/>
  <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
  <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.1" />
  <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
```

Code:
```
public class Program
{
    public static void Main(string[] args)
    {
        Log.Logger = DefaultLogger.LoggerToConsole;
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
            .UseSerilog() // Use Serilog as the logging framework
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
    }
}


public class DefaultLogger
{
    public static string DefaultOutputTemplate =>
        "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}";

    public static LoggerConfiguration Configuration => new LoggerConfiguration()
        .Enrich.FromLogContext()
        .Enrich.WithProperty("ClassName", "{Class}");

    private static LoggerConfiguration ConfigurationToConsole =>
        Configuration.WriteTo.Console(outputTemplate: DefaultOutputTemplate);
    
    public static Logger LoggerToConsole => ConfigurationToConsole.CreateLogger();
}
```

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0.302 AS build
WORKDIR /src
COPY ["OurApp/OurApp.csproj", "OurApp/"]
RUN dotnet restore "OurApp/OurApp.csproj"
COPY . .
WORKDIR "/src/OurApp"
RUN dotnet build "OurApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OurApp.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "OurApp.dll"]
```

Memory usage:
![image](https://github.com/serilog/serilog/assets/11928766/f6935ac9-786f-4c0a-8d2d-1cfd597e7402)

When we remove Serilog from Program.cs the problem goes away and memory usage is super low:
```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
    }
}
```
![image](https://github.com/serilog/serilog/assets/11928766/05b5f08c-21ea-4579-99b8-98b13b3ebddc)

**Comment by vlm---** [comment]
You are creating new logger pipeline with every log. Quick fix would be to change `LoggerToConsole `method to property and create logger only once.

**Comment by PawelTroka** [comment]
> You are creating new logger pipeline with every log. Quick fix would be to change `LoggerToConsole `method to property and create logger only once.

@vlm--- I though that assigning to logger will make it just use a created instance
```
public class Program
{
    public static void Main(string[] args)
    {
        Log.Logger = DefaultLogger.LoggerToConsole;
        CreateHostBuilder(args).Build().Run();
    }
```

**Comment by nblumhardt** [comment]
@PawelTroka it's likely to be whatever bit of code is using:

```
    public static LoggerConfiguration Configuration => new LoggerConfiguration()
        .Enrich.FromLogContext()
        .Enrich.WithProperty("ClassName", "{Class}");
```

Grepping your codebase for `CreateLogger()` should reveal it. HTH!

**Comment by PawelTroka** [comment]
leak is still there

**Comment by nblumhardt** [comment]
Still not likely to be our leak though, sorry.

**Comment by PawelTroka** [comment]
> Still not likely to be our leak though, sorry.

It is only there when Serilog is active, not there when it is not. I've given a reproducible example. We are 100% sure that the leak is caused by Serilog.

**Comment by nblumhardt** [comment]
Hi -

Apologies if I missed a link somewhere; the snippet you've given doesn't appear to be a repro, unless the leak is there even with no web endpoints and no logging being performed?

There are lots of ways one can generate high memory consumption using C#, but that doesn't make them C# memory leaks. Likewise with Serilog, there are plenty of ways you can use it to consume or leak memory, but they're generally usage issues and not bugs in Serilog core (this repo).

It could still turn out that you've found a leak, but this ends up being very rare. In almost every case like this one, either a Serilog plug in of some kind is broken, there's some enormously-large thing being serialized, a logger pipeline is being created for every request and not disposed, or some other gotcha is involved.

We're happy to help but we'll need more info and a close analysis of the issue from your end. If you have access to a profiler, recording a heap snapshot and sending a listing of the objects on the heap will narrow things down. Otherwise, a minimal executable repro in a clean GitHub repository would also improve our chances of spotting what's going wrong.

**Comment by PawelTroka** [comment]
> Hi -
> 
> Apologies if I missed a link somewhere; the snippet you've given doesn't appear to be a repro, unless the leak is there even with no web endpoints and no logging being performed?
> 
> There are lots of ways one can generate high memory consumption using C#, but that doesn't make them C# memory leaks. Likewise with Serilog, there are plenty of ways you can use it to consume or leak memory, but they're generally usage issues and not bugs in Serilog core (this repo).
> 
> It could still turn out that you've found a leak, but this ends up being very rare. In almost every case like this one, either a Serilog plug in of some kind is broken, there's some enormously-large thing being serialized, a logger pipeline is being created for every request and not disposed, or some other gotcha is involved.
> 
> We're happy to help but we'll need more info and a close analysis of the issue from your end. If you have access to a profiler, recording a heap snapshot and sending a listing of the objects on the heap will narrow things down. Otherwise, a minimal executable repro in a clean GitHub repository would also improve our chances of spotting what's going wrong.

Ok, I will try to prepare a clean repo with a reproducible case

**Comment by vlm---** [comment]
Please, try to change your code:
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Log.Logger = DefaultLogger.ConfigurationToConsole.CreateLogger();
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
            .UseSerilog() // Use Serilog as the logging framework
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
    }
}


public class DefaultLogger
{
    public static string DefaultOutputTemplate =>
        "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}";

    public static LoggerConfiguration Configuration => new LoggerConfiguration()
        .Enrich.FromLogContext()
        .Enrich.WithProperty("ClassName", "{Class}");

    private static LoggerConfiguration ConfigurationToConsole =>
        Configuration.WriteTo.Console(outputTemplate: DefaultOutputTemplate);
    
    //public static Logger LoggerToConsole => ConfigurationToConsole.CreateLogger();
}
```
Your now commented out method `LoggerToConsole` was creating a new `Logger` instance on every use of `Log.Logger`. Now I have moved the call to CreateLogger() so that it is called only once.

There's a really nice [post about configuration of Serilog in net8.0](https://nblumhardt.com/2024/04/serilog-net8-0-minimal/) I found most helpful lately.

**Comment by PawelTroka** [comment]
> Please, try to change your code:
> 
> ```cs
> public class Program
> {
>     public static void Main(string[] args)
>     {
>         Log.Logger = DefaultLogger.ConfigurationToConsole.CreateLogger();
>         CreateHostBuilder(args).Build().Run();
>     }
> 
>     public static IHostBuilder CreateHostBuilder(string[] args)
>     {
>         return Host.CreateDefaultBuilder(args)
>             .UseSerilog() // Use Serilog as the logging framework
>             .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
>     }
> }
> 
> 
> public class DefaultLogger
> {
>     public static string DefaultOutputTemplate =>
>         "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}";
> 
>     public static LoggerConfiguration Configuration => new LoggerConfiguration()
>         .Enrich.FromLogContext()
>         .Enrich.WithProperty("ClassName", "{Class}");
> 
>     private static LoggerConfiguration ConfigurationToConsole =>
>         Configuration.WriteTo.Console(outputTemplate: DefaultOutputTemplate);
>     
>     //public static Logger LoggerToConsole => ConfigurationToConsole.CreateLogger();
> }
> ```
> 
> Your now commented out method `LoggerToConsole` was creating a new `Logger` instance on every use of `Log.Logger`. Now I have moved the call to CreateLogger() so that it is called only once.
> 
> There's a really nice [post about configuration of Serilog in net8.0](https://nblumhardt.com/2024/04/serilog-net8-0-minimal/) I found most helpful lately.

Ok, I did exactly done  - will do some testing and get back to you

**Comment by PawelTroka** [comment]
Ok, we no longer have a leak after switching to alpine-based docker image and the leak was likely coming from .NET 8 (https://github.com/dotnet/runtime/issues/95922), not serilog
