### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [serilog/serilog#2082]
**Is your feature request related to a problem? Please describe.**
Ask for the `PrivacyInfo.xcprivacy` manifest as required by Apple, please refer to the Apple's document https://developer.apple.com/documentation/bundleresources/privacy_manifest_files for the detailed information, thanks.

**Describe the solution you'd like**
The `PrivacyInfo.xcprivacy` manifest file included in the repository.

**Describe alternatives you've considered**
N/A

**Additional context**
No

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-configuration/issues/424
