### ISSUE TITLE
Circular reference handling changed?

### ISSUE THREAD

**Issue by rcollette** [serilog/serilog#2087]
**Description**
The behavior of circular reference handling seems to have changed.   We were logging a ClaimsPrincipal object, which contains a ClaimsIdentity which contains a Claims collection where each Claim.Subject references back to the ClaimsIdentity.

```
logger.Information(messageTemplate: "Blows up {@LogContext}", new { principal = claimsPrincipal });
```
Though this is a circular reference, we were not previously seeing a long JSON output when writing this object.  I don't know if it is the recent update to 4.0 that resulted in this or some update in .NET itself.

**Reproduction**
See: https://github.com/rcollette/serilog-circular-reference-handling

**Expected behavior**
The prior behavior seemed to have a traversal limit of 1 and that should be restored or at least made configurable.

**Relevant package, tooling and runtime versions**
```
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
        <PackageReference Include="Serilog" Version="4.0.0"/>
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.2" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
```

**Comment by nblumhardt** [comment]
Hi @rcollette, thanks for the heads-up. My best guess is that the underlying `ClaimsPrincipal` data structure has changed, but not sure what that might be.

If you can capture "before" and "after" JSON outputs that would help narrow it down. Thanks!

**Comment by nblumhardt** [comment]
Howdy again! Any more data to go on, here? Thanks!

**Comment by rcollette** [comment]
Sorry, I just have been swamped and have not been able to put together a before and after example.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I'm keen to dig in further if there's been a Serilog change; my best guess is that it's the data being serialized and not a Serilog issue, so I'll close this for now and reopen if it turns out we have work to do here. Cheers!
