### ISSUE TITLE
Logging Breaks When a Format Specifier is Used On An Enum Or Struct

### ISSUE THREAD

**Issue by devinlyons** [serilog/serilog#2091]
**Description**
Logging breaks when a format specifier is used on an enum or struct. This happens on multiple sinks.

**Reproduction**

```csharp
namespace SerilogExample;

using Serilog;

enum TestEnum { A }

public class Program
{
    public static void Main(string[] args)
    {
        Serilog.Log.Logger = new LoggerConfiguration()
            .WriteTo.Console()
            .CreateLogger();

        Serilog.Log.Information("Hello, {Subject:l}!", "World");
        Serilog.Log.Information("The special number is {Number:l}", 42);
        Serilog.Log.Information("The special date is {Date:l}", DateTime.Parse("2024-07-24T12:00:00"));
        Serilog.Log.Information("The special value is {Value:l}", TestEnum.A);
    }
}
```

It produces this output:

```
[12:58:08 INF] Hello, World!
[12:58:08 INF] The special number is [12:58:08 INF] The special date is [12:58:08 INF] The special value is 
```

**Expected behavior**
I expected the properties to be written.

**Relevant package, tooling and runtime versions**
Here is the project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

</Project>
```

**Additional context**
Nope.

**Comment by nblumhardt** [comment]
Thanks for dropping us a line!

When a format specifier appears in a message template (or format string), it's an argument to `IFormattable.ToString(string, IFormatProvider)` on the value being formatted.

`l` isn't a valid format specifier for enums or `DateTime`s, so these types' `IFormattable` implementations throw when `ToString()` is called with this value.

If you replace the `ILogger.Information()` calls with `Console.WriteLine()`, you'll see the exception; Serilog makes a guarantee not to throw exceptions from `ILogger` methods, so the exception in our case is written to the `SelfLog` output instead. You can check this by calling `SelfLog.Enable(Console.Error)`.

Serilog's no-exception guarantee doesn't go any further than that, though. When the exception is hit, logging for that message stops, and Serilog (the console sink in this case) just moves on. We're keen not to clutter the code up trying to handle cases of invalid usage like this, so I don't think this behavior should change.

Switching your code to not use the format specifier, or to use a format specifier that's valid for the target type being logged, will sort this out.

Thanks again for the report, though :+1:  - hope this helps.
