### ISSUE TITLE
Add/Remove Sinks After Initial Configuration

### ISSUE THREAD

**Issue by Brian-at-Baebies** [serilog/serilog#2096]
I found [this issue](https://github.com/serilog/serilog/issues/1929) but I think that one is more geared toward accessing/modifying a _specific sink_ after configuration, rather than accessing/modifying the _sink collection_.  I also found [this issue](https://github.com/serilog/serilog/issues/714) which seems to be very much in line with my request, but the conversation there ended in 2016 with "try doing it this other, fairly complicated way" (if you'll pardon my editorializing).

**Describe the solution you'd like**
I have a situation where I want to separately collect portions of the log while certain actions are in progress.  Ideally I'd like to be able to add a sink to a logger when the action starts, then remove it when the action is complete, much as one can do with events and delegates in C#.  This also encapsulates the idea of having the portions of the log completely separate from each other (into separate files, separate memory locations, etc., all which could be accomplished by adding and removing individual late-configured sinks).

**Describe alternatives you've considered**
Briefly considered the alternative provided in [714](https://github.com/serilog/serilog/issues/714) but would much prefer a simpler Add/Remove API if that doesn't somehow violate a guiding principle of the project.  What is the reasoning behind not making the internal collection of sinks mutable after construction?

**Comment by nblumhardt** [comment]
Hi Brian, thanks for dropping us a line.

If your use case is simple enough, this kind of thing can work:

```csharp
class SwitchableSink : ILogEventSink, IDisposable
{
    readonly object _sync = new();
    readonly ILogEventSink? _instance = null;

    public void Emit(LogEvent logEvent)
    {
        lock (_sync)
        {
             _instance?.Emit(logEvent);
        }
    }

    public IDisposable Set(Action<LoggerSinkConfiguration> configure)
    {
        lock (_sync)
        {
             (_instance as IDisposable)?.Dispose();
             var instance = _instance = LoggerSinkConfiguration.CreateSink(configure);
             return new UnsetOnDispose(() => Unset(instance));
        }
    }

    sealed class UnsetOnDispose(Action onDispose): IDisposable
    {
        public void Dispose() => onDispose();
    }

    void Unset(ILogEventSink instance)
    {
        lock (_sync)
        {
             if (_instance != instance) return;
             (_instance as IDisposable)?.Dispose();
             _instance = null;
        }
    }

    public void Dispose()
    {
        lock (_sync)
        {
             (_instance as IDisposable)?.Dispose();
             _instance = null;
        }
    }
}
```

Usage:

```csharp
// Put this somewhere accessible: static field, IoC container, etc.
var switchable = new SwitchableSink();

Log.Logger = new LoggerConfiguration()
    .WriteTo.Sink(switchable)
    .CreateLogger();

// Later
using (var extraSink = switchable.Set(wt => wt.Console()))
{
    Log.Information("Extra sink is active");
}
```

The synchronization you can see in `SwitchableSink` is one of the main reasons for avoiding mutability in the sink collection.

Not compiled/tested; assuming you're going to need to modify this for the specifics of your scenario. HTH!

**Comment by nblumhardt** [comment]
Another option: https://github.com/serilog/serilog/pull/1764#issuecomment-2411335049
