### ISSUE TITLE
Issue with Message Templates and Property Names in Serilog

### ISSUE THREAD

**Issue by cberger-dfx** [serilog/serilog#2097]
I am encountering an issue when transitioning from Microsoft’s abstraction console logging to Serilog for file sink logging. Specifically, there are problems with message templates and property names.

#### Issue

Microsoft’s logging abstraction allows the use of `{}` in message templates, while Serilog uses `{propertyname}` for property placeholders. This discrepancy is causing issues when migrating logging code from Microsoft logging to Serilog.

#### Steps to Reproduce

1. Configure logging with Serilog.
2. Use message templates with `{}` placeholders.
3. Observe the behavior when logging messages.

#### Example Code

```csharp
using Serilog;

Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateLogger();

Log.Information("doesn't work {}", DateTime.Now);
Log.Information("works {any}", DateTime.Now);
Log.Information("works {Now}", DateTime.Now);

```

#### Expected Behavior

Serilog should correctly handle message templates using `{}` as placeholders or provide a clear mechanism for mapping these placeholders to the appropriate property names in Serilog.

#### Actual Behavior

- The log message `Log.Information("doesn't work {}", DateTime.Now);` does not work as expected, and the placeholder `{}` is not replaced with the value.
- Log messages with `{propertyname}` placeholders, such as `Log.Information("works {any}", DateTime.Now);` and `Log.Information("works {Now}", DateTime.Now);`, work correctly.

#### Workaround

Currently, I am manually updating all `{}` placeholders to `{propertyname}` format, which is cumbersome and error-prone.

#### Suggested Solution

Implement support for `{}` placeholders in Serilog, or provide a configuration option to automatically convert or map these placeholders during the transition.

#### Additional Information

Please let me know if there are any existing workarounds or if this issue could be addressed in a future release. Thank you!

**Comment by bartelink** [comment]
Fundamentally, fields in structured logs have names (see overview in https://serilog.net/), which is important for lots of sinks. The other thing in play is that the format string is upward compatible from .NET format strings (e.g. `{0}` etc will work).

The next thing you could potentially run into is that `Log.Information("{} is {}", "a", "b")` involves two names. While one could envisage having `{}` be silently be replaced with `{0}`, that would make things unclear as `Log.Information("{0} is {0}", "a", "b")` should use the first value for both properties.

I would not be surprised if https://github.com/Suchiman/SerilogAnalyzer would flag such usages...

Someone that knows more of the details will be along in due course, but it seems to me that the change you're suggesting is not an obvious bug with an obvious easy fix that doesn't have any cons.

**Comment by nblumhardt** [comment]
Hi! Thanks for the heads-up about this.

I think in this case, it's just a matter of MEL skipping extensive format string validation, perhaps for flexibility or performance reasons. The use of `{}` isn't a documented `ILogger` feature that I'm aware of (the safe, interchangeable log message template syntax in .NET is described in https://messagetemplates.org).

As @bartelink points out above, there are enough limitations/open questions about how this would work that grepping your codebase and updating the format strings is a better bet than us adding support directly in Serilog at this point.

**Comment by cberger-dfx** [comment]
Thank you for the quick response.

I guess i have to update my codebase.
