### ISSUE TITLE
Accessing Session inside an ILogEventEnricher throws 'Session has not been configured for this application or request.' error

### ISSUE THREAD

**Issue by kfuller002** [serilog/serilog#2099]
When creating a Serilog ILogEventEnricher everything works fine until I try to access session. Doing so throws the following error:

Session has not been configured for this application or request.

Eventually, I created a new Asp.Net MVC Application for repro and added session and serilog with everything working fine.

Then when I added the enricher I can get the httpcontext but the second I look at session it still throws the error.

Any ideas as to why session is not accessible or if there is a way around this? I know I could use middleware but I'm trying to get it to work with the enricher.

Here's my Program.cs:

![](https://i.sstatic.net/wjFt0D7Y.png)

Here's my controller accessing session fine:

![](https://i.sstatic.net/3Kh6rcrl.png)

Here's my enricher:

![](https://i.sstatic.net/oTrh6Z9A.png)

I’m using the latest .NET and Serilog

**Comment by bartelink** [comment]
Cross-posted in https://stackoverflow.com/questions/78853983/enriching-serilog-logs-with-session-throws-session-has-not-been-configured-for
Note for usage questions, best to stick to StackOverflow - there are many more watchers, and this tracker is intended primarily for proven addressable issues rather than usage issues that may have potential workarounds etc

**Comment by kfuller002** [comment]
> Cross-posted in https://stackoverflow.com/questions/78853983/enriching-serilog-logs-with-session-throws-session-has-not-been-configured-for Note for usage questions, best to stick to StackOverflow - there are many more watchers, and this tracker is intended primarily for proven addressable issues rather than usage questions that may have potential workarounds etc

Yeah, I posted over there but then realized how specific my question was to Serilog Enrichers and figured I might not have much luck on StackOverflow, to which I have had no one reply yet.  Mostly I wanted to know if this is related to a limitation of enrichers where they differ in some way to say a middleware that would prevent session from working.  Is this a known thing or something I'm doing wrong...
