### ISSUE TITLE
Breaking change in PropertyValueConverter optimization: avoiding hashset lookup for primitive types #1959

### ISSUE THREAD

**Issue by daniilBoushys** [serilog/serilog#2101]
**Description**
After updating the Serilog package from version 3.0.1 to version 3.1.0 it was noticed that some logs are not written to the MongoDB. The investigation showed that in #1959 IntPtr type in 3.1.0 is logged as ScalarValue (before it was StructureValue), leading to _System.ArgumentException: .NET type System.IntPtr cannot be mapped to a BsonValue_ exception in Serilog.Sinks.MongoDB package

**Reproduction**
[ReproSerilogIssue.zip](https://github.com/user-attachments/files/16657649/ReproSerilogIssue.zip)

**Expected behavior**
Serilog package update from version 3.0.1 to version 3.1.0 doesn't lead to the error described above or it should be marked as a breaking change in the release notes

**Relevant package, tooling, and runtime versions**
.NET 8
Serilog 3.1.0
Serilog.Sinks.Console 4.1.0
Serilog.Sinks.MongoDB 5.4.1
MongoDB.Driver 2.27.0

**Comment by nblumhardt** [comment]
Hi @daniilBoushys, thanks for the note and sorry about the surprise - I'd somehow missed this PR from the 3.1.0 release notes, which I've updated now.

The current behavior is intended, so I think the correct solution will be to update the MongoDB sink.

In the meantime, though, you could potentially work around this with an `ILogEventEnricher` that modifies the affected properties to use `long` and `ulong` where necessary (if you need a hand sketching this out, let me know what the event data in question looks like).

HTH!

**Comment by daniilBoushys** [comment]
Hi @nblumhardt, thanks for the updates!
To work around this and not change behavior for all Serilog logs, the following code for MongoDB mapper was added
`
BsonTypeMapper.RegisterCustomTypeMapper(typeof(IntPtr), new CustomIntPtrMapper());
BsonTypeMapper.RegisterCustomTypeMapper(typeof(UIntPtr), new CustomIntPtrMapper());

class CustomIntPtrMapper : ICustomBsonTypeMapper
{
    public bool TryMapToBsonValue(object value, [UnscopedRef] out BsonValue bsonValue)
    {
        switch (value)
        {
            case IntPtr intPtr:
                bsonValue = intPtr.ToInt32();
                return true;
            case UIntPtr uIntPtr:
                bsonValue = uIntPtr.ToUInt32();
                return true;
            default:
                bsonValue = null;
                return false;
        }
    }
}`

I think it can be safely used until scalar type handling for IntPtr, UIntPtr will be updated in MongoDB sink

**Comment by daniilBoushys** [comment]
Closed issue since it is intentional and was updated in the release notes
