### ISSUE TITLE
Adding Serilog stops Sentry from reporting Scope properties

### ISSUE THREAD

**Issue by georgiosd** [serilog/serilog#2104]
Hey guys

This is not exactly a bug but a problem when Serilog is used together with Sentry, where created logger scopes are reported fine by Serilog but stop being reported by Sentry.

I have already reported this to the Sentry team and they figured that there is no extensibility feature in Serilog to allow them to sync the scope.

Could you please lend a hand?

https://github.com/getsentry/sentry-dotnet/issues/3544

**Comment by nblumhardt** [comment]
Hi @georgiosd, thanks for looping us in. I don't think there's anything concrete we could try in the Serilog project to achieve this, so I'll join the other thread and keep discussion centralized there.

**Comment by georgiosd** [comment]
Thank you for caring 😄
