### ISSUE TITLE
Allow IDestructuringPolicy to access the log level

### ISSUE THREAD

**Issue by mobilebilly** [serilog/serilog#2105]
**Is your feature request related to a problem? Please describe.**
I am a bit frustrated when implementing custom destructuring policies because I cannot access the log level within the IDestructuringPolicy. This limitation prevents me from constructing different log messages based on the log level. The ability to tailor the output based on log severity is crucial for effective logging, especially when dealing with sensitive data or verbose information that should only be logged at certain levels.

**Describe the solution you'd like**
I would like the IDestructuringPolicy interface to provide access to the log level, allowing developers to construct log messages differently depending on the severity of the log event. This could involve adding a method or property to the interface that gives context about the log level when the destructuring process is invoked.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature would greatly enhance the flexibility and power of custom destructuring in Serilog, enabling more granular control over how log data is formatted and presented. It would be particularly useful in scenarios where log output needs to adapt based on the severity of the event.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Could you elaborate a bit more on where this comes up for you? It's definitely a scenario I've encountered, but it's usually solved with a line or two of code at the point the log event is raised, so I'm not sure the benefits would be enough to bake in deep plumbing for this.

**Comment by mobilebilly** [comment]
Thank you for the follow-up! Let me provide an example related to logging user profile data, where accessing the log level within IDestructuringPolicy would be highly beneficial.

Suppose we want to log all details of a user profile when the log level is Verbose, but for all other levels, we only want to log the username and email.

#
```c#
public class UserProfileDestructuringPolicy : IDestructuringPolicy
{
    public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue result)
    {
        if (value is UserProfile userProfile)
        {
            // Access the current log level (desired feature)
            var logLevel = // Ideally, we would obtain the current log level here

            // Log everything if the level is Verbose, otherwise just username and email
            if (logLevel == LogEventLevel.Verbose)
            {
                result = propertyValueFactory.CreatePropertyValue(new
                {
                    userProfile.UserName,
                    userProfile.Email,
                    userProfile.PhoneNumber,
                    userProfile.Address,
                    userProfile.DateOfBirth,
                    userProfile.AccountCreationDate,
                    // any other relevant fields
                }, true);
            }
            else
            {
                result = propertyValueFactory.CreatePropertyValue(new
                {
                    userProfile.UserName,
                    userProfile.Email
                }, true);
            }
            return true;
        }

        result = null;
        return false;
    }
}
``` 

In this scenario, being able to check the log level inside the destructuring policy would allow us to centralize the logic for what gets logged. Without this capability, we would need to implement conditional logic at every logging point or handle this in a more convoluted way, which can quickly become cumbersome in a large application.

Allowing access to the log level directly within IDestructuringPolicy would streamline the process, reducing code duplication and making the logging logic cleaner and more maintainable.

**Comment by mobilebilly** [comment]
We have two options which require no breaking change to the exising IDestructuringPolicy interface

1. Introduce an RequiresContextAttribute attribute
```c#
[AttributeUsage(AttributeTargets.Class)]
public class RequiresContextAttribute : Attribute
{
}
``` 
2. Introduce a marker interface IContextualDestructuringPolicy
```c#
public interface IContextualDestructuringPolicy : IDestructuringPolicy
{
    // No members, just a marker interface
}
``` 

If a policy has the attribute applied (or derived from the marker interface), we could wrap the value with the DestructuringContext below, othewise we could pass the original value as usual: 
```c#
public class DestructuringContext
{
    public LogEventLevel LogLevel { get; }
    public object Value { get; }

    public DestructuringContext(LogEventLevel logLevel, object value)
    {
        LogLevel = logLevel;
        Value = value;
    }
}
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up! I was wondering more about where you log the data - what the logging statement looks like, and what it would look like to manually/selectively log just the bits of the `UserProfile` that you need.

E.g. is it something like this?

```csharp
if (Log.IsEnabled(LogEventLevel.Verbose))
{
    Log.Verbose("Loaded profile {@Profile} for {UserName} <{Email}>", user, user.UserName, user.Email);
}
else
{
    Log.Information("Loaded profile for {UserName} <{Email}>", user.UserName, user.Email);
}
```

and I guess whether this is something that appears at one point in the application, vs. something that comes up widely.

There's a very high bar for adding features (they live a long time :-)) so I'm keen to think about this from the consuming code's point of view to see whether there's an existing alternative feature that can achieve similar results, or perhaps some broader functional category that this points us towards and which may have enough wide applicability that we can shape a feature around.

---

Apart from doing this in the application code (directly as above, or using some kind of helper method), you could also look at an approach driven by `LoggingLevelSwitch` and the global log level:

```csharp
// Init to any level you like
var levelSwitch = new LoggingLevelSwitch(LogEventLevel.Verbose);

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Destructure.With(new UserProfileDestructuringPolicy(levelSwitch))
    .CreateLogger();
```

In the destructuring policy, you can then check the level switch's `MinimumLevel` to consider the application's current global logging level, and modify user profile capturing accordingly.

HTH!

**Comment by mobilebilly** [comment]
Thank you for the detailed feedback!

Understand your concern. While the current approaches you mentioned, such as manual logging checks or using a LoggingLevelSwitch, can achieve the desired results, they often lead to increased code duplication, mixing of concerns, and potential maintenance challenges as the application grows.

Exposing the log level (or potentially other contextual information) within the IDestructuringPolicy allows for centralized, consistent, and scalable logging behavior across the entire application. This approach not only reduces the cognitive load on developers by separating concerns but also ensures that logging remains adaptable and maintainable as the application evolves.

Considering the potential benefits and the relatively low complexity of implementing this via a marker interface or similar approach, I believe this change could significantly enhance the flexibility and power of the Serilog framework.

e.g. With this enhancement, it will make possible to create a DestructingPolicy to generate log message detail dynamically with Attributes.

```c#
public class RequestContext
{
    public string RequestId { get; set; }
    public string UserId { get; set; }

    [MinLogLevel(LogEventLevel.Debug)]
    public string UserAgent { get; set; }

    [MinLogLevel(LogEventLevel.Debug)]
    public string ClientIpAddress { get; set; }

    public DateTime Timestamp { get; set; }

    [MinLogLevel(LogEventLevel.Verbose)]
    public string RequestBody { get; set; }

    [MinLogLevel(LogEventLevel.Debug)]
    public UserProfile UserProfile { get; set; }
}

public class UserProfile
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [MinLogLevel(LogEventLevel.Debug)]
    public string Email { get; set; }

    [MinLogLevel(LogEventLevel.Verbose)]
    public string Address { get; set; }

    [MinLogLevel(LogEventLevel.Verbose)]
    public DateTime DateofBirth{ get; set; }

    [MinLogLevel(LogEventLevel.Debug)]
    public DateTime AccountCreationDate{ get; set; }
}
```

**Comment by nblumhardt** [comment]
Thanks for your reply.

Currently, the `LoggingLevelSwitch` mechanism will be the best option to go with. The flip side of adding features to Serilog is that we also have to manage a maintenance and complexity budget, so when a need can be met with a reasonable amount of additional code that's usually the preferred approach.
