### ISSUE TITLE
Apache 2.0 license issue

### ISSUE THREAD

**Issue by ringtailpasqualefranzese** [serilog/serilog#2110]
Hi,
I'm the technical director of ringtailinteractive, we are using serilog in our development and want to give proper copyright notice as per your Apache 2.0 license. I've encountered an issue though: you copypasted the apache 2.0 template and left it blank.
Here's a reference to one project that filled it properly https://github.com/castleproject/Core?tab=License-1-ov-file
The main issue is that line where it says
 Copyright [yyyy] [name of copyright owner]
The Apache 2.0 license basically obligates anyone using your code to report it but it's left blank so there's no proper way to give you credit.
As a temporary solution in my company we're going to use the following attribution:
Copyright -2024 serilog
Please let me know if it's a proper approach and if possible fill in the template appropriately, we will update as soon as viable once you do so.

P.S. sorry for using the bug report form, but I didn't see anything that looked more appropriate.

**Comment by nblumhardt** [comment]
Hi! The notices in question appear in the headers of individual source files; to refer to the project as a whole, the language used in the package and elsewhere is generally `Copyright © Serilog Contributors`. Hope this helps!

**Comment by ringtailpasqualefranzese** [comment]
Thanks, updated the attribution to be | Serilog | Serilog Contributors | Apache-2.0 | Copyright © Serilog Contributors |
