### ISSUE TITLE
Expose internal sinks so they can be used via dependency injection

### ISSUE THREAD

**Issue by marlon-tucker** [serilog/serilog#2111]
**Is your feature request related to a problem? Please describe.**
I'm migrating to Serilog 4.x and we have a number of custom sinks that made use of the PeriodicBatching sink project. After upgrading we saw Serilog.Core now exposed the same interface and the PeridoicBatching project readme has been updated to state Serilog 4.x now has the feature built in.

We have a fairly complex sink setup:

The batching sink itself is configured via a DI service, which means we are adding the sink to Serilog via a DI factory service. Inside that factory function we wrap the underlying batching sink inside another sink which blocks log re-entry (aka any logging produced by the sink which we can't control).

Using the periodic batching project this was all achievable as the PeriodicBatchingSink was public, but because the BatchingSink inside Serilog v4 is internal we are unable to instantiate it and add it to the service container. 

At the moment, Serilog only exposes the sinks via the LoggerConfiguration class and as another issue mentions, even if they are created via that route we still can't access the underling sink objects.

**Describe the solution you'd like**
Expose the sinks Serilog natively provides so they can be constructed freely. I realise this makes their constrictors a public facing API.

**Describe alternatives you've considered**
I'm going to have to continue to use the  Serilog.Sinks.PeriodicBatching  project in the short term as anything else is going to require an extensive redesign.

**Comment by nblumhardt** [comment]
Hi!

`LoggerSinkConfiguration.CreateSink()` is the constructor method you're looking for:

```csharp
serviceCollection.AddTransient(x =>
    LoggerSinkConfiguration.CreateSink(writeTo => writeTo.MyBatchedSink()));
```

Something to this effect should work, let me know if you run into any stumbling blocks.

Cheers,
Nick

**Comment by marlon-tucker** [comment]
Cool, yep that worked well.

Thank you, closing this issue.

**Comment by nblumhardt** [comment]
:raised_hands:
