### ISSUE TITLE
CloseAndFlushAsync doesn't work with ReloadableLogger

### ISSUE THREAD

**Issue by VavilovAlex** [serilog/serilog#2115]
**Description**
Calling Log.CloseAndFlushAsync() when using ReloadableLogger as a static logger silently fails and does nothing.

**Reproduction**
1. Set the static logger to a ReloadableLogger.
2. Call Log.CloseAndFlushAsync().

**Expected behavior**
The ReloadableLogger should either:

* Support DisposeAsync() and properly flush the sinks
* Fall back to Dispose() if DisposeAsync() is not available,
* Throw an exception indicating the failure to close and flush.

**Relevant package, tooling and runtime versions**
Serilog 4.0.1

**Comment by nblumhardt** [comment]
That's an awful bug, thanks for the report, will PR a patch now.

**Comment by VavilovAlex** [comment]
Wow, that was very prompt
