### ISSUE TITLE
.net8  wpf   No output to console

### ISSUE THREAD

**Issue by yangl1025** [serilog/serilog#2119]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the core **Serilog** package only.

**Description**
my application is .net8 wpf。I set the serilog write to console, but  the console is not display
the code is :
LoggerConfiguration Logger = new LoggerConfiguration()
   .Enrich.With(new ThreadIdEnricher())
   .MinimumLevel.Information()
   .Enrich.FromLogContext()
   .WriteTo.Console()
   // 调试日志
   .WriteTo.Logger(x => x
       .WriteTo.File(logPath + appName + "-info-.log", rollingInterval: RollingInterval.Day, rollOnFileSizeLimit: true, shared: true,
      retainedFileCountLimit: 30, fileSizeLimitBytes: 10 * 1024 * 1024, outputTemplate: LogTemplate)
   );

**Comment by yangl1025** [comment]
the log wirte a file,but not display on the console.

**Comment by augustoproiete** [comment]
@yangl1025 This is by design. WPF apps don't write to the console in general. If you'd like to write to the console, you should be using a Console app.

For visualizing logs in a WPF app, you might want to consider [Serilog.Sinks.RichTextBox.Wpf](https://github.com/serilog-contrib/serilog-sinks-richtextbox).

**Comment by yangl1025** [comment]
I mean  when debug the app, the log can display in the output ,but not ?this is why ?

**Comment by nblumhardt** [comment]
https://stackoverflow.com/questions/160587/no-output-to-console-from-a-wpf-application
