### ISSUE TITLE
Reuse message strings (templates)

### ISSUE THREAD

**Issue by brgrz** [serilog/serilog#2121]
There is a SO question (not mine) which was never answered and I am not aware of a feature in Serilog but this is such a common use case for messages, to reuse them for more than just logging but not repeat them once in string interpolation and once in message template.

This is the question
https://stackoverflow.com/questions/74110177/reuse-serilog-templates

Is there a solution to this?

**Comment by nblumhardt** [comment]
Looking again, your extension method would need to use `ILogger.BindMessageTemplate()` and `MessageTemplate.Render()` to produce the returned string. The resulting `MessageTemplate` and properties could then be used to construct a `LogEvent` which the `ILogger` would accept via `Write()`. HTH!

**Comment by brgrz** [comment]
Most of my usage/calls are using .NET's ILogger injected by the DI into services, controllers, etc. Serilog is only referenced in composition root (within the Program.cs).

**Comment by nblumhardt** [comment]
If you're not looking to use the Serilog API in the solution, this is probably a question for the Microsoft.Extensions.Logging maintainers, since that's where the .NET `ILogger` interface is defined, and what you'd need to use for a solution that's independent of Serilog.

**Comment by nblumhardt** [comment]
Closing as I don't think there's anything we can add here to make this work via MEL, but if you still need a hand with any of the Serilog APIs please let us know.
