### ISSUE TITLE
Deprecaed Serilog.Sinks.AzureAnalytics is still referenced in documentaion

### ISSUE THREAD

**Issue by arialdomartini** [serilog/serilog#2122]
**Description**
The page https://github.com/serilog/serilog/wiki/Provided-Sinks mentions the sink

[Serilog.Sinks.AzureAnalytics](https://nuget.org/packages/serilog.sinks.azureanalytics)

matching the NuGet package https://www.nuget.org/packages/serilog.sinks.azureanalytics, which is deprecated.

The updated package is: https://www.nuget.org/packages/Serilog.Sinks.AzureLogAnalytics/ (notice the `Log` in the name).
It does not help that both the NuGet package link the same GitHub project, whose documentation reference the old version only. 

I will make a PR to fix the docs in the sink repo. I cannot make a PR here because the wrong information is in the Wiki, not in the repo.

**Comment by nblumhardt** [comment]
Thanks, I've fixed this now. The repository is the same - the new version is in the `vnext` branch:

https://github.com/saleem-mirza/serilog-sinks-azure-analytics/tree/vnext
