### ISSUE TITLE
Serilog-Dependent Progress Bar Package: Feasibility Discussion

### ISSUE THREAD

**Issue by RampantDespair** [serilog/serilog#2124]
*I was looking for some place to post this idea and thought that here was the right place, if that's not the case I do apologize in advance.*

**Project Idea**
I'm considering developing a NuGet package for a progress bar that would be directly dependent on Serilog. The main idea is to create a progress bar that integrates seamlessly with Serilog's logging infrastructure, allowing developers to easily incorporate progress tracking into their Serilog-based logging workflows.

**Potential Features**
- Easy integration with existing Serilog setups
- Configurable progress bar styles
- Ability to log progress events alongside other log entries
- Support for nested progress bars (for sub-tasks)

**Existing Solutions**
I've explored several existing progress bar solutions, but none of them quite fit my needs, especially in terms of tight Serilog integration. This has motivated me to consider developing a custom solution that addresses the specific requirements of Serilog users.

**Concerns and Questions**
I have some concerns about this project's feasibility, particularly regarding Serilog's sink system:
- Sink Compatibility: How would the progress bar work with different Serilog sinks? For example, writing a progress bar to a file sink seems impractical or potentially problematic.
- Console Output: Would the progress bar interfere with normal console logging when using the console sink?
- Non-Linear Sinks: How would the progress bar behave with sinks that don't support overwriting previous output (e.g., network sinks, database sinks)?
- Performance Impact: Could integrating a progress bar with Serilog introduce performance overhead, especially for high-volume logging scenarios?

**Request for Feedback**
I'm reaching out to the Serilog community to gather thoughts on this project:
- Do you see value in a Serilog-dependent progress bar package?
- Are there any obvious technical obstacles that would make this project unfeasible?
- Do you envision such a package being used in real-world scenarios?

**Next Steps**
Depending on the feedback received, I'm willing to take on this project and contribute to the Serilog ecosystem. I'm open to collaborations, suggestions, and any insights that could help shape this idea into a useful tool for the community.
Please share your thoughts, concerns, and suggestions in the comments below. Your input will be invaluable in determining whether to proceed with this project and how to approach its implementation.

**Comment by nblumhardt** [comment]
Thanks for posting a heads-up! I don't think there's much we can do from the Serilog side to help with this, time is unfortunately very tight. Please feel free to post a link to you project here if you give it a shot. Thanks again!
