### ISSUE TITLE
`ReadFrom.KeyValuePairs` cannot load sinks/extensions written in VB.NET

### ISSUE THREAD

**Issue by dsosunov** [serilog/serilog#2126]
**Description**
In VB.NET environments, creating **WriteTo** extensions that are compatible with numerous other extensions proves challenging. This limitation arises from fundamental differences in the language specifications between C# and VB.NET.

The method is defined in src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs

```csharp
 namespace Serilog.Settings.KeyValuePairs;
 
  internal static IList<MethodInfo> FindConfigurationMethods(IEnumerable<Assembly> configurationAssemblies, Type configType)
  {
      var methods = configurationAssemblies
          .SelectMany(
              [RequiresUnreferencedCode("Configuration methods are not trimming safe")]
              (a) => a.ExportedTypes
              .Where(t => t.IsSealed && t.IsAbstract && !t.IsNested))
          .SelectMany(t => t.GetMethods(BindingFlags.Static | BindingFlags.Public))
          .Where(m => m.IsDefined(typeof(ExtensionAttribute), false) &&
                      m.GetParameters()[0].ParameterType == configType)
          .ToList();
       ///....
  }
```
This process filters exported types using the criteria IsSealed and IsAbstract. When it identifies such a type, it attempts to locate extension methods within. This is primarily aimed at identifying extension classes as per the C# Language Specification. However, VB.NET operates differently as it lacks a direct equivalent. In VB.NET, a **Module** is sealed but not abstract, and a **NotInheritable** class, though both sealed and abstract, cannot contain methods marked with the **ExtensionAttribute**. This attribute can only be applied to methods within a **Module**, as specified by VB.NET’s rules.

Ref: https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/extension-methods

**Reproduction**

```vbnet
Imports System.Runtime.CompilerServices

Public Module SampleModule
    <Extension()>
    Public Sub ExtendString(ByVal str As String)
        Console.WriteLine("Extended " & str)
    End Sub
End Module

Public NotInheritable Class SealedClass
    Public Shared Sub PrintSomething()
        Console.WriteLine("Something")
    End Sub
End Class

Sub Main()
    Dim configurationAssemblies As Assembly() = {Assembly.GetExecutingAssembly()}
    Dim configType As Type = GetType(String) ' Example configuration type

    Dim methods = configurationAssemblies.
        SelectMany(Function(a) a.ExportedTypes.
                   Where(Function(t) t.IsSealed AndAlso t.IsAbstract AndAlso Not t.IsNested)).
        SelectMany(Function(t) t.GetMethods(BindingFlags.Static Or BindingFlags.Public)).
        Where(Function(m) m.IsDefined(GetType(ExtensionAttribute), False) AndAlso
                        m.GetParameters()(0).ParameterType = configType).
        ToList()

    For Each method In methods
        Console.WriteLine($"Method found: {method.Name} in {method.DeclaringType}")
    Next
End Sub
```

**Expected behavior**
The method should align with VB.NET specifications and accommodate the distinctions between the two languages.

**Relevant package, tooling and runtime versions**
All Serilog versions are affected

**Additional context**
Workaround: Define C# assembly and link that assembly to VB.NET project

**Comment by nblumhardt** [comment]
Thanks for the note, @dsosunov.

Can you use a `NotInheritable` class, and just manually apply `<Extension()>`, potentially with some compiler warnings ignored? (This might suffice for the configuration reader, as long as you also define a separate extension method to call from VB.NET code.)

**Comment by nblumhardt** [comment]
I think in this case, performance might win out and we stick with the status-quo. It's a bit unfortunate, but as this is the first report in the 13-odd years that this feature's been in the wild, the benefits from a change probably don't justify the potential performance regression we'd see by loosening the restriction on types we inspect.
