### ISSUE TITLE
[Feature] Message-only format specifier for template's Exception property

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog#2139]
### Is your feature request related to a problem? Please describe.
Some standard template properties can be [customised](https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text), e.g. `{Timestamp:HH:mm:ss}`, `{Level:u3}` and `{Message:lj}`.

Not so for `{Exception}`, which prints both message and stack trace, on multiple lines.

For the human-readable console sink, a stack trace adds significant noise and friction, especially when tailing a remote docker container which is already ugly (no colour, for example).

(To see the stack trace, one could consult a durable sink, e.g. file, Seq.)

### Describe the solution you'd like
To be able to show only the exception message. For example `{Exception:m}`.

### Describe alternatives you've considered
I'm aware of Serilog.Expressions. But for something this simple it makes sense to have the `:m` option in the core library, especially given there's precedent for the other standard properties mentioned above.

Also, we've tried to avoid Serilog.Expressions to keep our code as simple as possible.

### Additional context
Hope this will be considered worthy. Thanks!

**Comment by nblumhardt** [comment]
Thanks for the note!

The original output format really is in maintenance mode; at some future point I'm hoping we'll support expression features through the core library everywhere. Although it's a small, obvious feature, there are a _lot_ of small obvious features and these add up. _Serilog.Expressions_ is just a fresh look at output templates, aiming to cover all of those little feature cleanly, after spending a decade or so gathering requirements.

There are two workable options right now, though.

If you're super keen to avoid _Serilog.Expressions_ you can add an enricher to attach an `ExceptionMessage` property to events carrying an exception, and then use `{ExceptionMessage}` in the template.

Or, if you end up reconsidering the expressions path, `{Inspect(@x).Message}` does what you want in the current version.

**Comment by nblumhardt** [comment]
Both options (the built-in formatter and Expressions) only parse the template once, at start-up, so parsing speed is not a big difference between them. Expressions adds a small overhead, but this is mostly because of theming support.

A very simplistic benchmark (ignoring the added `StringWriter` allocation overhead) to compare them:

```
BenchmarkDotNet v0.14.0, macOS Sequoia 15.1.1 (24B91) [Darwin 24.1.0]
Apple M3 Pro, 1 CPU, 11 logical and 11 physical cores
.NET SDK 9.0.100
  [Host]     : .NET 9.0.0 (9.0.24.52809), Arm64 RyuJIT AdvSIMD
  DefaultJob : .NET 9.0.0 (9.0.24.52809), Arm64 RyuJIT AdvSIMD
```

| Method            | Mean     | Error   | StdDev  | Ratio |
|------------------ |---------:|--------:|--------:|------:|
| FormatBuiltin     | 121.8 ns | 0.61 ns | 0.57 ns |  1.00 |
| FormatExpressions | 136.2 ns | 0.28 ns | 0.25 ns |  1.12 |

Low tens of nanoseconds per event is negligible in normal usage.

Here's the source, so you can drop it into a .NET 8 console app and try whatever formats are important in your scenario:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Serilog.Events;
using Serilog.Formatting;
using Serilog.Formatting.Display;
using Serilog.Parsing;
using Serilog.Templates;

BenchmarkRunner.Run<FormattingBenchmark>();

public class FormattingBenchmark
{
    readonly ITextFormatter _expr = new ExpressionTemplate("[{@t:HH:mm:ss} {@l:u3}] {@m}\n{@x}");

    readonly ITextFormatter _builtin =
        new MessageTemplateTextFormatter("[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}\n{Exception}");

    readonly LogEvent _evt = new(
        DateTimeOffset.Now,
        LogEventLevel.Information,
        exception: null,
        new MessageTemplateParser().Parse("Hello, {Name}!"),
        [new LogEventProperty("Name", new ScalarValue("nblumhardt"))]
    );
    
    public FormattingBenchmark()
    {
        var e = FormatExpressions().ToString();
        var b = FormatBuiltin().ToString();
        if (!e.Contains("INF")) throw new InvalidOperationException("?");
        if (e != b) throw new InvalidOperationException("=");
    }
    
    [Benchmark(Baseline = true)]
    public StringWriter FormatBuiltin()
    {
        var sw = new StringWriter();
        _builtin.Format(_evt, sw);
        return sw;
    }
    
    [Benchmark]
    public StringWriter FormatExpressions()
    {
        var sw = new StringWriter();
        _expr.Format(_evt, sw);
        return sw;
    }
}
```
