### ISSUE TITLE
Customization through LogEvent object

### ISSUE THREAD

**Issue by julichan** [serilog/serilog#2146]
Hello,

**Is your feature request related to a problem? Please describe.**
Today, we have a custom framework on top of serilog but noticed it doesn't work anymore when using certain features of serilog due to LogEvent.Copy being a non overidable internal method. We use custom formatters building output based on config and specific event.
When our customized LogEvent object is copied by serilog LogEvent internal copy method, we actually lose all those informations and the custom formatters cannot behave correctly. 

**Describe the solution you'd like**
Any of the following changes would be nice to have:
- Make the method LogEvent.Copy() a virtual public method so that we can propagate necessary information
- Allow to tie an object that to the LogEvent object that will be propagated to copies.

**Describe alternatives you've considered**
I do not currently see an alternative to propagate behavioral information from an event up to the formatters.
I did try to look into providing some configuration through the formatters in configuration files but that would require to repeat the same config an incalculable number of times. Using DI is more feasible but then the configuration would become pragmatic.

**Additional context**
The implemented features allows to add properties in a similar way that LogContext object does in serilog while keeping a state history and merging states based on our needs. Also it allows us to customize static fields names from the formatters, avoid string placeholders to be sent as properties, conditionally manage the output of certain properties and so on...

Note: I can make a PR myself if it helps

Thanks,

**Comment by nblumhardt** [comment]
Hi @julichan, thanks for your message.

Leaving `LogEvent` unsealed was an historical oversight; inheriting from `LogEvent` is not an intended scenario so it would be best to move away from this if possible.

Attaching your additional metadata as a property value (e.g. a `ScalarValue` with well-known name) would support carrying data from event creation through copying to the formatter.

Hope this helps,
Nick

**Comment by julichan** [comment]
Thanks @nickvane, i thought this wasn't the right way but in anycase it works well. Found a useful scalar value to add alongside the data. Case solved.
