### ISSUE TITLE
LogEventProperty and the Visitor Pattern (or lack thereof)

### ISSUE THREAD

**Issue by IanMercer** [serilog/serilog#255]
Currently there is no clean separation of concerns between the structure of a LogEvent and the process of serializing it to a string or to Json through the Render method. The class that implements a tree of property values is intimately bound to the TextWriter class.

So when I tried to create a Bson serializer that goes direct from the tree to Bson (without the current ToJson, Parse, ToBson approach) I was not able to.  Or, if I wanted to create an in memory object tree (i.e. `Dictionary<string,object>` all the way down) and then pass that to a different serializer, like, say Json.net so I could use all of its options, I couldn't do that either.

IMHO it would be better to separate these two concerns. Have LogEventPropertyValues as a pure tree of data representing the property values being logged and then have a separate Visitor class that deals with visiting the tree to convert it into a different form.

The abstract visitor class might look something like this:- 

    /// <summary>
    /// Visit each node in a tree of LogEventProperties
    /// </summary>
    public class LogEventPropertyVisitor<T>
    {
        protected virtual T Visit(LogEventPropertyValue logEvent)
        {
            if (logEvent is ScalarValue)
                return VisitScalar(logEvent as ScalarValue);
            else if (logEvent is SequenceValue)
                return VisitSequence(logEvent as SequenceValue);
            else if (logEvent is StructureValue)
                return VisitStructure(logEvent as StructureValue);
            else
                throw new Exception(logEvent.GetType().Name + " not recognized");
        }
        protected abstract T VisitScalar (ScalarValue scalarValue);
        protected abstract T VisitSequence(SequenceValue sequence);
        protected abstract T VisitStructure (StructureValue structure);
    }

and an override for converting to Json might include methods like this ...

       protected override string VisitSequence(SequenceValue sequence)
        {
            return "[" + sequence.Elements.Select(e => Visit(e)) + "]";
        }

Now all that code that deals with turning the tree into Json has been separated from the property values tree.  Now it's easy to write a different visitor that outputs to a plain formatted string, or, in my case, a BsonDocument.

The base level visitor could also handle the depth limiting code and it could also accept plug-ins like the 'null value property excluder' I proposed earlier.

Any interest in pursuing this approach?  It would be clearly be a large undertaking and would impact many projects in the solution including all of the sinks!  LMK if you want me to help make it happen.

Coupled with the ability to pass in a replacement JsonVisitor this would enable the implementation of many new features on their own (like the null value suppressor, a string-length limiter, ...).

**Comment by nblumhardt** [comment]
This is still a great idea, but it's not looking like there will be time to spend on this for v2 at this stage. Closing for now, but will re-open if anyone wants to dig in further and potentially PR this.

Thanks for the original ticket @IanMercer

**Comment by nblumhardt** [comment]
https://gist.github.com/nblumhardt/bd74fafc61d0c50ec07e0f3715df0d00

Basic implementation and some elaboration in the gist above; if we can't get this into Serilog itself in the near future, we might be able to whip up a `SerilogStructuredDataToolkit` package.....
