### ISSUE TITLE
Log.Verbose does not produce any logs

### ISSUE THREAD

**Issue by attilaszaszlateral** [serilog/serilog#276]
While, Error/Warning/Information correctly logs data to multiple configured sinks, Verbose is ignored. 
The sinks (Glimpse, RollingFile, AzureTable) are configured to Verbose level.
SelfLog does not produce any error messages.

**Comment by borex** [comment]
I still have the same problem. Yesterday when I first tried Serilog, the above mentioned solution solved this problem. 
This was the configuration that I have used:
`
            Log.Logger = new LoggerConfiguration()
                        .WriteTo.Logger(x =>
                        {
                            x.MinimumLevel.Verbose();
                            x.Filter.ByExcluding(le => le.Level == Serilog.Events.LogEventLevel.Error || le.Level == Serilog.Events.LogEventLevel.Fatal);
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/info_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .WriteTo.Logger(x =>
                        {
                            x.MinimumLevel.Error();
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/error_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .CreateLogger();
            Log.Logger.Verbose("sss");
            Log.Logger.Debug("sss");
            Log.Logger.Warning("sss");
            Log.Logger.Information("sss");
            Log.Logger.Error("sss");
            Log.Logger.Fatal("sss");`

Today, I added EventLog sink and changed the configuration to this and Verbose and Debug messages were not getting output:
`
            Log.Logger = new LoggerConfiguration()
                        .WriteTo.Logger(x =>
                        {
                            x.MinimumLevel.Error();
                            x.WriteTo.EventLog(
                                        source: "MyService",
                                        logName: "Application",
                                        manageEventSource: true);
                        })
                        .WriteTo.Logger(x =>
                        {
                            x.MinimumLevel.Verbose();
                            x.Filter.ByExcluding(le => le.Level == Serilog.Events.LogEventLevel.Error || le.Level == Serilog.Events.LogEventLevel.Fatal);
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/info_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .WriteTo.Logger(x =>
                        {
                            x.MinimumLevel.Error();
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/error_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .CreateLogger();`

After that I have tried the following configuration that fixed the problem for Verbose and Debug messages:
`
            Log.Logger = new LoggerConfiguration()
                        .MinimumLevel.Verbose()
                        .WriteTo.Logger(x =>
                        {
                            //x.MinimumLevel.Error();
                            x.Filter.ByIncludingOnly(le => le.Level == Serilog.Events.LogEventLevel.Error || le.Level == Serilog.Events.LogEventLevel.Fatal);
                            x.WriteTo.EventLog(
                                        source: "MyService",
                                        logName: "Application",
                                        manageEventSource: true);
                        })
                        .WriteTo.Logger(x =>
                        {
                            //x.MinimumLevel.Verbose();
                            x.Filter.ByExcluding(le => le.Level == Serilog.Events.LogEventLevel.Error || le.Level == Serilog.Events.LogEventLevel.Fatal);
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/info_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .WriteTo.Logger(x =>
                        {
                            //x.MinimumLevel.Error();
                            x.Filter.ByIncludingOnly(le => le.Level == Serilog.Events.LogEventLevel.Error || le.Level == Serilog.Events.LogEventLevel.Fatal);
                            x.WriteTo.File(
                                        path: Path.Combine(path, "logs/error_.log"),
                                        fileSizeLimitBytes: 1024 * 1024 * 10,
                                        rollingInterval: RollingInterval.Day,
                                        //, buffered: true,
                                        rollOnFileSizeLimit: true,
                                        retainedFileCountLimit: 10,
                                        encoding: Encoding.UTF8,
                                        formatter: new JsonFormatter(),
                                        shared: true);
                        })
                        .CreateLogger();`

Can somebody explain what am I doing wrong in the second configuration and why did it stop working? Thanks.
