### ISSUE TITLE
Natively support JSON.NET dynamic objects (JObject)

### ISSUE THREAD

**Issue by ChristianWeyer** [serilog/serilog#30]
On Twitter you mentioned that it should be fairly straightforward to implement via IDestructuringPolicy
;)

**Comment by mcintyre321** [comment]
@kkozmic Any chance I could take a look at your ```IDestructuringPolicy ``` (the one that works with the wrapper)?

**Comment by kkozmic** [comment]
Sorry, I don't have that code with me anymore.

**Comment by nblumhardt** [comment]
#371 echoes this one, I think it's one for us to reopen, but might be a "2.0"

**Comment by nblumhardt** [comment]
Build 1.4.168 removes the limitation that made this awkward; would love to see a _Serilog.Extras.JObject_ or similar that takes advantage of it :-)

Thanks @Jaben for nailing this!

**Comment by nblumhardt** [comment]
https://github.com/destructurama/json-net

**Comment by mcintyre321** [comment]
Nice!

**Comment by CumpsD** [comment]
@nblumhardt that's awesome, thanks!
