### ISSUE TITLE
EmailSink: Support multiple email recipients

### ISSUE THREAD

**Issue by mookid8000** [serilog/serilog#310]
Instead of using the `MailMessage` ctor that takes a single recipient, how about allowing for specifying a comma-and-or-semicolon separated list of recipients?

I've accompanied my suggestion with a PR

**Comment by raysefo** [comment]
None of the below configurations work for sending multiple recipients with 2.4. How can I send emails to multiple recipients?

"ToEmail": "to1@gmail.com; to2@gmail.com"
"ToEmail": "to1@gmail.com, to2@gmail.com"

**Comment by mookid8000** [comment]
@raysefo What do you mean exactly when you say that it doesn't work? 

Does it send to the first recipient, or does nothing happen?

Does it work when you configure it with only one email address?

**Comment by raysefo** [comment]
Hi @mookid8000 

When I added 2 mail addresses with a comma or semicolon in between, nothing happens. No errors and no emails either.
If I send only one recipient it works, here is my working configuration.
`"Serilog": {
    "Using": [ "Serilog.Sinks.Email", "PurchaseRazerCodesMultipleRequestService", "Serilog.Sinks.File", "Serilog.Sinks.Console", "Serilog.Sinks.MSSqlServer" ],
    "Override": {
      "Microsoft.AspNetCore": "Warning"
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": ".\\logs\\log-.txt",
          "restrictedToMinimumLevel": "Error",
          "buffered": false,
          "rollingInterval": "Day",
          "retainedFileCountLimit": 3
        }
      },
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "Server =.\\SQLEXPRESS; Database=GameAPI;Integrated Security=True;  MultipleActiveResultSets=True; Trusted_Connection=yes; Encrypt=False",
          "tableName": "ExceptionLog",
          "autoCreateSqlTable": true,
          "restrictedToMinimumLevel": "Error",
          "batchPostingLimit": 50,
          "period": "0.00:00:20"

        }
      },
      {
        "Name": "CustomEmail",
        "Args": {
          "ConnectionInfo": {
            "NetworkCredentials": {

              "UserName": "support@support.com",
              "Password": "12345"
            },
            "FromEmail": "support@support.com",
            "MailServer": "smtp.gmail.com",
            "EmailSubject": "[{Level}] Support Requests",
            "Port": "465",
            "IsBodyHtml": false,
            "EnableSsl": true,
            "ToEmail": "test@gmail.com",
            "RestrictedToMinimumLevel": "Error",
            "OutputTemplate": "{Timestamp:yyyy-MM-dd HH:mm} [{Level}] {Message}{NewLine}{Exception}"
          }

        }
      }
    ]
  },`

**Comment by mookid8000** [comment]
I just noticed that you have a space character in the string `"[to1@gmail.com](mailto:to1@gmail.com); [to2@gmail.com](mailto:to2@gmail.com)"` and I can see the code does not trim the strings: https://github.com/serilog/serilog-sinks-email/blob/dev/src/Serilog.Sinks.Email/Sinks/Email/EmailSink.cs#L83

Could you try removing the space?

**Comment by raysefo** [comment]
I tried like this but unfortunately did not get any emails.

`"ToEmail": "test1@gmail.com;test2@gmail.com",`
