### ISSUE TITLE
Remove spurious branches from the main Git repo

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#333]
The main serilog/serilog repository has a number of dead branches from earlier work that no longer belong here. The only branches should be:

* `dev`
* `master`
* `gh-pages`

Until it can be moved elsewhere we should also keep:

* `feature-auditing`

**Comment by merbla** [comment]
Is the work in the following branches required?  Other wise I can kill them off.  I will give it a week for feedback

- cacheTweaks
- feature-adjustablelevels
- simonsRefactor

**Comment by nblumhardt** [comment]
_feature-adjustablelevels_ can definitely go; @SimonCropp might have some thoughts on the others though they're pretty stale now so probably due for the chop.

**Comment by SimonCropp** [comment]
Kill mine off. I will re PR when i get around to it

**Comment by merbla** [comment]
@SimonCropp is the history worth keeping? e.g. tag or something?

**Comment by SimonCropp** [comment]
Nah i can recreate it

**Comment by merbla** [comment]
Removed via website
