### ISSUE TITLE
[Serilog.Extras.Timing] Including extra properties in TimedOperations

### ISSUE THREAD

**Issue by chuwik** [serilog/serilog#338]
TimedOperations are very useful, but sometimes you need to include more properties in the "completed" log entry, like:
- Was it successful or not
- Extra data relevant to the context (number of items processed, etc.)
That could be set by the code before the TimedOperation is disposed.

Would it be possible to do this right now?

**Comment by chuwik** [comment]
Thanks @mivano, this works well. 
However, in my opinion the syntax to do it right now isn't very clean... For the next version, are you thinking about alternative ways of approaching this scenario (adding custom properties to the completed log entry of a timed operation)?

An option could be to expose a list of properties inside the TimedOperation that were public, and adding them at the end to the "Completed" log entry. Functionally it's the same, but I think the syntax would be nicer to use and would point out clearly that the properties belong to that TimedOperation and not all logs (like with LogContext). If the class had the "sealed" removed, it could also open the door for people to take that TimedOperation as a base and create their own custom ones for the needs of their system.

For instance, in a system I work on we have a lot of code that does the same: takes a chunk of items and processes them. In our case, we want devs extending the system with new "processors" to always use TimedOperations with a compulsory set of properties: number of items, etc. If TImedOperation wasn't sealed, I could use it as a starting point and create my own custom ones for this (i.e. ProcessItemsTimedOperation) and other actions. Not to push them to the serilog repo, just internally for the systems.

Just my 2 cents, hope some of this makes sense to you!

**Comment by mivano** [comment]
Makes perfectly sense! I still need to finalize my changes, but simply did not had time yet. Sorry. I will remove the sealed operator and look at your suggestion. Thanks!

**Comment by mivano** [comment]
I added PR #356 in which the sealed keyword is removed. I also implemented the ability to pass additional properties. By creating a subclass and a extension method to return this subclass, you should be able to easily implement your ProcessItemsTimedOperation functionality I hope.

**Comment by chuwik** [comment]
Thanks @mivano, the PR is great :) I'll close the issue.
