### ISSUE TITLE
Split the sinks and extras into separate repositories

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#344]
We've hit 30 sinks - it's no longer really feasible to maintain them all in the same repository, and since the project has stabilised, there's not much advantage to doing so either.

Splitting the project into multiple subprojects will make it easier to manage, and lets contributors with interest in a specific component focus their efforts 

Here's a proposal:

- [ ] Leave only the projects comprising the _Serilog_ NUPKG in the `serilog/serilog` repository
- [ ] For everything else, create a new
  * repository of the form `serilog/serilog-x-y`, for example `serilog/serilog-sinks-couchdb`,
  * _AppVeyor_ build for the package,
  * _README.md_ file in the repository root with more complete documentation
- [ ] Find a single "owner" for each package/repository, either
  * the original contributor of the package, if they're interested, or
  * someone from the core team
- [ ] Make the [Provided Sinks] wiki page an index into each sub-repository (move the docs but keep them discoverable)

I think we should also **turn off** the issue trackers in the sub-repositories and instead point users to the main repository's tracker via a link at the top of the README - otherwise issues with a cross-cutting element might not be handled optimally.

Thoughts?

**Comment by nblumhardt** [comment]
Alright, we're in full swing! The first two:

 * https://github.com/serilog/serilog-sinks-applicationinsights
 * https://github.com/serilog/serilog-sinks-mongodb

I think the strategy is going to require some compromises, doing this as a "big bang" is not much fun. Moving sinks one-by-one as they need to rev seems to work well.

Here's the basic requirements for each move:

 - [ ] Create a new repository _seriog-sinks-sinkname_ in the https://github.com/serilog organisation (readme, VIsual Studio .gitignore, Apache 2.0 license)
 - [ ] Turn off the issue tracker in the new repository
 - [ ] Create a new team _Owners (Sink Name)_ and add the original contributor/interested parties
 - [ ] Grant the team write access to the repo
 - [ ] Remove the sink from the https://github.com/serilog/serilog repository and build script
 - [ ] Push/merge to master, making sure the sink is no longer published from the old location
 - [ ] Copy the project layout and build script from one of the existing independent repositories
 - [ ] Move the source/tests for the sink there
 - [ ] `Install-Package Serilog` and remove the dependencies from the NUSPEC file unless it's one of the customised ones (let the versions be picked up from `packages.config`)
 - [ ] Push!
 - [ ] Create a project in the Serilog organisation in _AppVeyor_
 - [ ] Set the build number appropriately, if not performing a major revision
 - [ ] Copy the versioning, build, deployment settings from an existing independent project (major/minor versions are currently in the build tab)
 - [ ] Kick it off!

I've written this checklist so that it can be copied into the tickets relating to future repository moves.

A bit fiddly, but only 5-10 mins in practise.

Here's what we need to do overall to close this issue (I don't think we should keep it open until all sinks are merged, since there's no schedule pressure):

 - [ ] Tidy up the `Build.ps1` file used by the independent projects so that no editing is required (currently the solution name and description need to be edited in)
 - [ ] Link each independent sink project from the Serilog wiki, e.g. under [Provided Sinks]
 - [ ] Make the _README_s of the two new independent sinks **beautiful** - logos, links, how-to, docs: really setting the bar high here will keep quality up as new contributions come in

I'm sure there's more, but this is enough of a start :-)

Any and all help appreciated; if you want to get stuck in, either on this ticket or on moving sinks, email me - I'll set up any additional permissions you might need. Cheers!

**Comment by merbla** [comment]
Hey @nblumhardt can I get access to create a repo?

**Comment by merbla** [comment]
@nblumhardt I think you will have to do this step, Owner rights needed I think

- [ ] Create a new team Owners (Sink Name) and add the original contributor/interested parties

**Comment by nblumhardt** [comment]
Ah I see - well, that makes the "Admin" permission somewhat useless then. Welcome to the Owners team. Cheers!

**Comment by nblumhardt** [comment]
Next! https://github.com/serilog/serilog-sinks-loggly

:-)

**Comment by nblumhardt** [comment]
Following up on the discussion of @mivano 's PR #356.

@SimonCropp graciously reached out to suggest we consider more carefully where the [serilog](https://github.com/serilog) organisation goes as the project continues to take off.

With _so_ many projects, people and technologies in the mix, it's a topic that's becoming an important one. The demands on my time to coordinate everything are getting pretty high, and while the defacto "benevolent dictator" model I started the project with has proven useful for a small set of things (mostly restraint around the core feature set) it obviously doesn't scale or work well across many projects where other contributors are much more knowledgeable than I am.

I think for continuity, the current plan of moving each sink to its own repository under `serilog` is a good one. If time could be turned back we might have gone for a more distributed model but that ship has sailed.

However, I'd like to suggest strengthening what we're starting under this ticket with a couple more principles.

First, **new sinks**. I have been working under the notion that we'd continue accepting new sinks to `serilog/serilog` as a way of lowering the barriers to entry. I no longer think that's tenable; since we're going to require a substantial investment from contributors to maintain their contributions, I think the better model will be to require new sink contributions as self-contained repositories that we will accept by moving into the `serilog` organisation. By raising the bar a little we'll hopefully reduce future maintenance work.

This isn't to discount eventually moving sinks out of `serilog`, but in the short-to-mid term, keeping the sinks close to the core project and actively maintaining them seems like the right thing to do.

Second, **extras**. We have some great little projects going there - XML config, timing, attributed destructuring, owin, F#, web, ... Extras are where a good amount of innovation happens. Unfortunately by being "blessed" sub-projects, the also suck a bit of air out of the room, making it harder to build a picture of a broad ecosystem of Serilog extensions.

For the extras, including timing, I'd like to propose moving them where appropriate (*) to their own top-level GitHub organisations and projects, with owners separate from the `serilog` org. We can give these new package names and namespaces that refer to Serilog but don't fall under it, e.g. _SerilogMetrics_, _FSharpTypesForSerilog_, ....

The (*) is that in the case of _Serilog.Extras.AppSettings_ I think we should move this functionality into the _Serilog.FullNetFx_ project.

Finally, **new work**. It will cause some friction, but if we're ever going to get all of this done we need a forcing function. I'd like to propose that unless its an important bug-fix, only changes to the _Serilog_ package should hit `master` in the main Serilog repository from this point forward. PRs for sinks, extras and so-on can come to `dev`, but be deleted from there and moved out.

So.......... :) ... what do you good people think?

I'm happy continuing to do this work, with whatever help I can get, but it will definitely take a while and thus feel like the "brakes are on" for a bit.

**Comment by merbla** [comment]
`Splunk` is done, have not had a chance to merge #393 to `master`

**Comment by mivano** [comment]
Regarding the Extras; moving them to their own top-level repository might make them less discoverable so we have to be careful to point out their existence. Although I do not yet fully see why they cannot fit under the Serilog organisation I also see no reasons why they have to be under it :-)

So let me know how you want me to tackle the metrics stuff and I will try to pick it up.

**Comment by nblumhardt** [comment]
@mivano thanks :) The main problems with the Serilog organisation are that it still has a bunch of "management overhead", though the disadvantage it imposes on other projects _not_ under the Serilog organisation is also a significant consideration long-term.

Is https://github.com/serilog-metrics/serilog-metrics a good place for the metrics work? I'm happy to create such a thing, but if you wanted to kick it off and add me as a committer I can help move the code and build over.

Discoverability is a good example of something we should tackle without relying on centralisation. Folks should be able to run their own independent projects yet feel like a first-class part of the Serilog community.

@merbla great! You may still have a few TODOs outstanding ;)

![image](https://cloud.githubusercontent.com/assets/342712/6320884/50fbbc88-bb36-11e4-9ad5-3d8d94b92111.png)

The README also needs an update. I'll merge the removal of the Splunk sink to master now anyway, and to make the process more efficient I'll run over and create all the other sink projects in bulk.

**Comment by merbla** [comment]
@nblumhardt thanks for the pickup.  Appveyor & Git updated along with the readme.  I will go thru the TODO's again.

**Comment by merbla** [comment]
Do we have a next top 5 to move? Was thinking easy ones...

- Email
- SQL Server
- NLog
- Log4net
- Glimpse

**Comment by nblumhardt** [comment]
@merbla LGTM!

**Comment by merbla** [comment]
Thats the point I am learning ;)

**Comment by mivano** [comment]
The organisation and repository for Serilog.Metrics has been created (https://github.com/serilog-metrics/serilog-metrics). I converted the Serilog.Extras.Timing project into a Serilog.Metrics project. 

@nblumhardt; I made you also owner. Can you have a quick look if everything is okay (licenses, use of names etc) and guide me in setting up the creation of the nuget packages?

**Comment by nblumhardt** [comment]
@mivano fantastic! It looks great.

Whether or not we encourage the `Serilog.x` naming for other packages is probably worth discussion/input; on the one hand it would be nice to keep some notion of "part of the Serilog project" vs. "independent" represented in the namespace, but on the other - history (e.g. with Autofac) shows that this won't be achievable past a certain point.

Here's a proposal: how about we put together a nice stock "extension" icon and use that for the package? By providing this we can reasonably ask authors of other packages to use it so that at a glance  the core vs. independent packages are clear in search results, but things can move in and out of the main project without requiring namespace/package names etc.

All of this may of course be "adminstrivia" - I'm happy to take point on it, just let me know if it makes sense to you all :-)

**Comment by nblumhardt** [comment]
BTW @mivano I'm fine with taking on the setting up of CI, packaging etc.; may take a little while as I need to get onto helping with the ES sink move etc. too :)

**Comment by mivano** [comment]
Well, that is the thing that I m a bit unsure about; how close or not close is this to Serilog. The extras package was pretty close to it; shared codebase, license, ci build, nuget and naming conventions. Now it is separated from it so all of this do not apply anymore. 

Regarding naming; I personally would like to keep at least some link to Serilog as it is completely linked and dependant on it. But I can also see your point of sharing the same Serilog.x root namespace so I do value your input and experience in that. Maybe SerilogMetrics instead? Looks like a minor difference but has the reference but still points to something different.

Same applies of course for the nuget package name; Serilog.Metrics would make sense, but again; would you go for support to Serilog or should we advertise SerilogMetrics e.g. for this.

Setting up AppVeyor is not a big deal, more important is to get some consensus about the naming convention before we push any package out. I can still make changes now easily.

And indeed; the ElasticSearch sink move is also big on my wish list as we are working on some nice improvements with @Mpdreamz :-)

**Comment by nblumhardt** [comment]
`SerilogMetrics` would be nice, if that's the direction we want to encourage others to go in. +1 from me.

This is the sort of thing I think we could do so that community projects can be distinguished somewhat from the rest, while still looking presentable:

![image](https://cloud.githubusercontent.com/assets/342712/6382607/b9127864-bd95-11e4-996e-2f651dc971f2.png)

We could switch the sinks to something like this so there's some consistency:

![image](https://cloud.githubusercontent.com/assets/342712/6382617/c7f3a916-bd95-11e4-8b80-2cc20d442692.png)

(The actual wording probably doesn't matter so much :))

Projects like _SerilogMetrics_ are deserving of their own branding/identity so this would be more of a starting point to help projects off the mark...

**Comment by mivano** [comment]
No problem changing it into `SerilogMetrics`, will do that tomorrow unless somebody has other ideas about this. Then I will also use this as Nuget package name and publish under my own key.

Logo looks cool. Would be nice to use for these kinds of projects.

**Comment by mivano** [comment]
I renamed it and added a CI build on top of it using AppVeyor. Working fine as far as I can see. If I missed something or you have other remarks/suggestions, then let me know.

**Comment by nblumhardt** [comment]
Great, will PR the logo and run over the rest soon (-ish) :-)

**Comment by merbla** [comment]
@nblumhardt thinking we need have a target `<dependency id="Serilog" version="[1,2)" />`  in the sink nuspecs.  Thoughts?

**Comment by vossad01** [comment]
Has any thought been given to what happens to [serilog-samples](https://github.com/serilog/serilog-samples) under this reorganization?

**Comment by khellang** [comment]
@vossad01 The samples in serilog-samples uses the different sinks from NuGet packages, fixed to a specific version, so this doesn't affect them.

**Comment by vossad01** [comment]
@khellang But what about maintenance and which projects may be included?

serilog-samples has samples for Extras that are being moved out of the serilog org.  For example, the 'TimingSample' was for Timing which as now moved to (SerilogMetrics)[https://github.com/serilog-metrics/serilog-metrics].

**Comment by nblumhardt** [comment]
Ah yes, the samples, good catch.... I think given each sink will now live in a separate repo, it may be more workable for each repo to include a sample if deemed useful. serilog/serilog-samples hasn't been a great success, but hasn't been a maintenance burden either, so personally I'm happy to leave it as-is until the sinks start making some progress in this area. Open to ideas (or anyone volunteering to PR them to each separate sink)

**Comment by merbla** [comment]
[Email](https://github.com/serilog/serilog-sinks-email) is done. @nblumhardt checkout https://ci.appveyor.com/project/serilog/serilog-sinks-email for the solution/build.ps1 changes.  Thoughts?

**Comment by nblumhardt** [comment]
@merbla fantastic - looks great!

I wonder if adding the `".sln"` in `Build.ps1`, rather than in the AppVeyor script, might be worthwhile? This would make it more likely to be consistent with the ones that also include a `-net40` variant of the solution file.

I'll send a PR with what I mean; I'd also like to take a shot at finding the `.sln` file in the root by convention when not specified, so that from a command prompt running `./Build.ps1 -notouch` is enough to smoke-test the build as a developer.

Cheers!

**Comment by merbla** [comment]
@nblumhardt let me know when you are happy and will template from that.

**Comment by nblumhardt** [comment]
@merbla I've PR'd something here: https://github.com/serilog/serilog-sinks-email/pull/1 - the build fails because the AppVeyor config would need to be tweaked, but this is pretty close to my idea of the "template". What do you think?

**Comment by merbla** [comment]
@nblumhardt merged.. looks good.  Worked both locally & for build.  Will use that as the template for the next sinks.

**Comment by nblumhardt** [comment]
All of the repos are done!! A few more "Owners" teams to add, but they can probably be done lazily.

I'm creating fresh issues for remaining parts of this - there's already a detailed one for AppSettings (#402), will try to come up with solutions for the others.

Have added various cleanup/doc tasks with the `up-for-grabs` label - trying to come up with some solutions for discoverability and so-on.

Thanks for all the help and input on this one! :) ... Closing, finally!
