### ISSUE TITLE
Expand OWIN support

### ISSUE THREAD

**Issue by vossad01** [serilog/serilog#345]
I took some time today to try to implement an analog of `UserNameEnricher` from `Serilog.Extras.Web`  in OWIN.  I used the contribution from #112 as a guide, namely `RequestContextMiddleware`.  I would like to develop things well enough to contributed back to Serilog if possible, but I thought it might be good to bring up design first.

To the extent of my understanding, there is no statically available information for OWIN.  Thus retrieving information will require collecting data in the OWIN pipeline and sharing that state with the logger is needed.  `RequestContextMiddleware` does this with `LogContext`.  This would seem to preclude registering Enrichers to collect more information as seems typical in Serilog.

A limitation I encountered is that the collection user name must be occur in the pipeline after authentication has been configured (I'm using `Microsoft.Owin.Security`).  Implementing this in the same way as `RequestContextMiddleware` this property will be removed from `LogContext` and not be available for logging from any middleware registered prior to it.

To keep adding middleware steps like this it would suggest we need something like a `LogContext` specific for OWIN that is cleared after all other middleware completes (using a special middleware to be registered first).  This would overcome the issue of each property being cleared after its step completes.

Thoughts?

@damianh I am tagging you since you provided the initial OWIN support.

**Comment by nblumhardt** [comment]
Thanks for putting this out there - I'll need some time to catch up on this, but it sounds like a worthwhile set of improvements to be driving. Any overlap/applicability to ASP.NET 5?

**Comment by vossad01** [comment]
ASP.NET 5?  The short answer is "yes."

There should be a good deal of commonality and where there may not be direct reuse do to API changes, I would not anticipate a particularly challenging migration.  This really raises the question about about what level of support is intended for OWIN, Katana, and ASP.NET 5 (vNext).

I am not expert on it and I have not tried out ASP.NET 5 myself yet because I have been waiting for a VS preview that is supposed to be okay for side-by-side install, the following is how I understand it.

There are three related related technologies:
 * OWIN.  A community controlled spec that is mostly (entirely?) defined around "primitives" (strings, IDictionary, Func, etc).
 * Katana: Microsoft's implementation of OWIN for its components, a server implementation, as well as some additional API providing some higher level constructs for building OWIN-based applications.  The `IAppBuilder` interface is defined in the "OWIN" nuget package but I am not sure that is a conical part of the spec and group it with Katana.
 * ASP.NET 5: A reinvention* of ASP.NET.  In addition to a new runtime (Core CLR) and compilation target, it implements an OWIN based pipeline/configuration.  Everything moves under the `Microsoft.AspNet` namespace and the main configuration abstraction is `IApplicationBuilder`.

OWIN is the lowest common denominator and a pure OWIN component can be used with Katana, ASP.NET vNext, or some other OWIN implementation.  The flip side being the implementation cannot leverage anything provided by Katana or vNext.

An adapter exists for Katana components to be hosted in ASP.NET vNext.  My understanding is that vNext is going to absorb (if it hasn't already) Microsoft Katana's components; so, my expectation (though speculation) is that Katana is not going to have a long development life after vNext is released and vNext's OWIN components will just be Katana's successor.

I have never concerned myself with developing for pure-OWIN and just target Katana for now.  @damianh did seem to put effort into keeping it pure OWIN where he comments in #112 that the middleware could drop the MS.Owin (Katana) dependency.  However, some of the integration he provided necessarily depends on Katana (ex. implementing `Microsoft.Owin.Logging.ILogFactory`) which is why the Nuget Package has a `Microsoft.Owin` dependency and he named the extra package `MSOwin`


   \* my word, I am not really sure how MS is marketing it

**Comment by nblumhardt** [comment]
Closing because via #344 we're aiming to support independent projects for add-on functionality; if you end up able to put anything out there along these lines please let us know though! Cheers!

**Comment by vossad01** [comment]
@nblumhardt If you would like I could do the working of splitting Extras.MSOwin to a new org when I do the same for #378.  I am not a candidate for a long term maintainer though.

I am not sure if you would rather keep existing things in `serilog` until a suitable maintainer is found.

**Comment by nblumhardt** [comment]
Thanks @vossad01 - we'll probably deal with this via #344 so no need to dig in here. Cheers!
