### ISSUE TITLE
PropertyValueConverter may blow up with unhandled exception

### ISSUE THREAD

**Issue by konste** [serilog/serilog#348]
One of the primary goals for the logging framework is that it should not cause code crash regardless of what data it tries to log. In PropertyValueConverter.cs method GetProperties contains this:

```csharp
try
{
    propValue = prop.GetValue(value);
}
catch (TargetParameterCountException)
{
    SelfLog.WriteLine("The property accessor {0} is a non-default indexer", prop);
    continue;
}
catch (TargetInvocationException ex)
{
    SelfLog.WriteLine("The property accessor {0} threw exception {1}", prop, ex);
    propValue = "The property accessor threw an exception: " + ex.InnerException.GetType().Name;
}
```

GetValue may throw different exceptions, not only those two caught above. In my case I got NotSupportedException which was not caught and therefore not handled.

As far as I understand we should catch all exceptions here, not only TargetInvocationException.

**Comment by nblumhardt** [comment]
Thanks for the report

**Comment by nblumhardt** [comment]
BTW, can you please let us know under what conditions this exception is possible? Ideally we'll prevent it by avoiding whatever kind of call this is; I've never seen `NotSupportedException` in this scenario so it would be interesting to understand more closely :)

**Comment by nblumhardt** [comment]
Ah - I see the problem:

https://github.com/serilog/serilog/blob/master/src/Serilog/Parameters/PropertyValueConverter.cs#L172

There should be a 'CanRead` filter applied here. Thanks!

**Comment by konste** [comment]
I believe I tried to log web request object which contains Stream as a property. Stream in turn has properties like Length and Position, but not all streams support that properties (web streams probably don’t), so attempt to read those caused NotSupportedException.

I see that you already found it.

Konstantin

**Comment by nblumhardt** [comment]
Hi Konstantin,

I can't repro this - using the code:

```csharp
public class Foo
{
    public string Bar
    {
        get {  throw new NotSupportedException(); }
    }
}

log.Information("Here is {@Foo}", new Foo());
```
I just get

```
2015-01-12 07:32:02 [Information] Here is Foo { Bar: "The property accessor thre
w an exception: NotSupportedException" }
```

I.e. the exception's caught and output into the message. Do you have any other clues?

The lack of `TargetInvocationException` suggests that the property itself does not support `get` operations, but we've made all of the appropriate checks I'm aware of to avoid this.

Cheers,
Nick

**Comment by konste** [comment]
I will work on the repro today or tomorrow as time permits.  I think i remember how it happened.

Konstantin
< sent from mobile device >

On Jan 11, 2015, at 1:35 PM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Konstantin,

I can't repro this - using the code:

public class Foo
{
    public string Bar
    {
        get {  throw new NotSupportedException(); }
    }
}

log.Information("Here is {@Foo}", new Foo());

I just get

2015-01-12 07:32:02 [Information] Here is Foo { Bar: "The property accessor thre
w an exception: NotSupportedException" }


I.e. the exception's caught and output into the message. Do you have any other clues?

The lack of TargetInvocationException suggests that the property itself does not support get operations, but we've made all of the appropriate checks I'm aware of to avoid this.

Cheers,
Nick

-

**Comment by konste** [comment]
Nicholas, I have investigated my scenario further and found that it works after all. One particular reason why I was not getting any log messages is that http Response object is very big and when sent to Elasticsearch sink it was overflowing its limit of 32K for the string, therefore the whole record was thrown away.

This is all good, but look at the three exceptions attached (as pictures). The problem is despite I don’t have first chance exception intercept turned on AND I DO have “Just my code” enabled I still keep breaking in the debugger for each and every exception happening there (as in pictures). For Response object I stop there like 20 times per one log statement! Something must be done about it.

Thanks!
Konstantin

**Comment by nblumhardt** [comment]
Hi Konstantin - thank you very much for the follow-up. Unfortunately GitHub doesn't attach pictures from email attachments; I loathe spurious exceptions too so I'd very much like to take a look at that one, but you may need to paste details into a new ticket via the web site rather than email. I'll close this issue as resolved. Thanks again.

**Comment by konste** [comment]
I have attached the pictures mentioned above here AND also I attach the solution I finally found for my woes - the trick is in VS Debugger settings, see Exhibit #4 :-)

![evidence 1](https://cloud.githubusercontent.com/assets/2653844/5726246/be9422a0-9b0e-11e4-88f4-e4fc6ab9d4b5.PNG)
![evidence 2](https://cloud.githubusercontent.com/assets/2653844/5726244/be8ed246-9b0e-11e4-9744-0cfb5e8ca574.PNG)
![evidence 3](https://cloud.githubusercontent.com/assets/2653844/5726245/be92dddc-9b0e-11e4-998a-b15de9da2598.PNG)
![exhibit 4](https://cloud.githubusercontent.com/assets/2653844/5726384/b4422cb0-9b0f-11e4-81ca-e80370cd2fbf.PNG)

**Comment by nblumhardt** [comment]
Aha! Very good - thanks for the follow-up.

It looks like you should be using destructuring policies to customize how these types are serialized. If a property will be invalid to read, it's best not to include it in the logged representation.

You can plug in your own `IDestructuringPolicy` to do it, but you might also do:

```csharp
.Destructure.ByTransforming<Foo>(foo => new { P1 = foo.P1, ... })
```

...to select only the valid properties.

The exceptions being raised, even though they're caught, will likely have a pretty strong performance impact.

HTH,
Nick
