### ISSUE TITLE
'System.NullReferenceException' occurred in Serilog.Extras.Timing.dll

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog/serilog#349]
Just to let everyone know I'm tracking down an issue with Gauge, I was messing with the new version of Microsoft's Application Insights when I saw I was getting this error, which results in the log not being sent.

I wrongly assumed it was to do with Application Insight's sink or Telemetry Client but it still appears if I disable the ApplicationInsight completely.

I've tried reducing the FUNC<> down to a simple return as well as different combinations of the overload. I just need to finish something unrelated and then I'll come back to it.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, looking forward to hearing where this turns out to be. // cc @mivano

**Comment by mivano** [comment]
There is no explicit try/catch block around it. See https://github.com/serilog/serilog/blob/dev/src/Serilog.Extras.Timing/Extras/Timing/GaugeMeasure.cs#L51
So when the function throws an exception, it will bubble up. Might be good to wrap it inside a try/catch and log separately, but love to hear your opinion.

**Comment by mivano** [comment]
@johnkattenhorn any update on this?

**Comment by nblumhardt** [comment]
Folks, I'll close this for now to keep noise down on the tracker; John, please feel free to reopen it if needed. Thanks!
