### ISSUE TITLE
AzureTableStorage sink and RowKey template

### ISSUE THREAD

**Issue by bragma** [serilog/serilog#350]
I was planning to add a feature to AzureTableStorage sink to allow storing entries in "reversed" timestamp order as an optional parameter. The benefit is that Azure Tables provides a quick "take" parameter, so it may be useful to just "take(1000)" to get the latest (newer) 1000 log entries. At the moment, there is no efficient way to get the last N rows from table storage, so the common solution for this is to reverse the key and take from the beginning.

While reasoning on this, I saw that partition keys are built using the log timestamp, while row keys are not. This may not be a big problem since all entries are already separately timestamped, but cause some inconsistencies when "taking" a fixed amount of entries. Since the row key does not start with the timestamp, all rows within the same partition are sorted by level and then message, which may cause unexpected "cut out" of some entries if the user assumes that entries are sorted on time.

A fake example:
Partition Key - RowKey - Timestamp - LogMessage
...
0000123000 - information|message2 - 12/12/2014-00:00:02 - message2
0000123000 - warning|message1 - 12/12/2014-00:00:01 - message1

Here both messages have the same partition key. "message2" has been logged AFTER "message1" (see the log timestamp), but due to the way RowKeys are sorted, it will apper BEFORE (since "information" comes before "warning" in lexicographical sorting). If we get the last entry of the table, probably we expect to get message2, while we get message1.

WAD solves this problem by adding timestamp to rowkey, so entries are sorted as expected. I'm suggesting to do the same thing too, so that the new rowkey will be:

timestamp | level | message(truncated if too long) | guid | postfix text

Regarding the "reverse" configuration flag, it is not going to impact the actual log data, but only the Azure Table partition and row Keys values. The common solution is to use a properly formatted DateTime.MaxTicks - Timestamp.Ticks as numeric value as  the "timestamp" part of the keys.

I'd like to hear from you about this...

**Comment by nblumhardt** [comment]
Thanks for the heads-up; I'm not sure of the mechanics of table storage, but I know who might be ;) .. cc @robdmoore

**Comment by robdmoore** [comment]
This wasn't so much a problem originally, but now that we are grouping into partition keys it is a problem. I'm not sure if the default order is to retrieve by sorting on rowkey or not though so I'm not sure if your suggestion will work or not.

One thing I do know though is that the main benefit we get from the row key would be lost in that you can search for specific errors or levels of errors by filtering on row key e.g. `RowKey gte 'information'` or on a specific error message.

If we put timestamp in the row key then the row key might as well be `{timestamp}{guid}`.

As a suggestion - we could make this flag that turns on time sorting so that you can tail the logs change the row key to be `{timestamp}{guid}` and the partition key to be reverse ticks and if you don't set that then we leave the current one in there?

**Comment by bragma** [comment]
The problem was present even in the original implementaion, even if a lot less probable. I think there is no perfect solution here, just 2 different use cases. You can still filter on all columns, though. It is slower than using the RowKey, but still an option.
I'll leave this to your decision, I don't know which of the 2 cases is used more frequently.
As another option, we can still reverse the partition key and leave the row key as it is, getting the most from the 2 solutions with the minor inconvenience of the border value.

**Comment by bragma** [comment]
After thinking about this, probably it's not going to be so useful. @robdmoore you are right about the RowKey, sadly it's the only index and there are conflicting requirements.
Probably in most use cases instead of taking last N entries, the Partition key can be used as index for retrieving a specific range of time (which may also be the last X minutes). Results can then be sorted by timestamp if needed.
I think we can close this issue, if you agree,

**Comment by nblumhardt** [comment]
Thanks for your effort on this @bragma and the input @robdmoore - cheers!
