### ISSUE TITLE
"System.Linq": "4.0.0-beta-*" in Project.json

### ISSUE THREAD

**Issue by Devbot-Net** [serilog/serilog#353]
Serilog doesn't specify a version number for Linq in it's project json.  This prevents us from importing the Serilog nuget package into a fresh vnext project unless we force a linq version in the consumer project:

{
    "version": "1.0.0-*",
    "dependencies": {
        "Serilog": "1.4.118"
    },
    "frameworks": {
        "aspnetcore50": {
            "dependencies": {
                "System.Linq": "4.0.0-beta-22231"
            }
        }
}

Failure to add the aspnetcore50 dependency results in compilation issues.  I've not entirely got to grips with vnext yet but the current project.json for Serilog prevents it's use in vnext except against aspnetcore50.

**Comment by Devbot-Net** [comment]
Updating the project.json to the following appears to work:

	{
		"version": "1.0.0-beta-*",
		"dependencies": {
		},
		"code": "**/*.cs",
		"exclude": [ "**/*net40.cs", "bin/*" ],
		"frameworks": {
			"aspnet50": {
			},
			"aspnetcore50": {
				"dependencies": {
					"Microsoft.CSharp": "4.0.0-beta-*",
					"System.Collections": "4.0.10-beta-*",
					"System.Collections.Concurrent": "4.0.0-beta-*",
					"System.Collections.NonGeneric": "4.0.0-beta-*",
					"System.Collections.Specialized": "4.0.0-beta-*",
					"System.Diagnostics.Debug": "4.0.10-beta-*",
					"System.Diagnostics.Tools": "4.0.0-beta-*",
					"System.Dynamic.Runtime": "4.0.0-beta-*",
					"System.Globalization": "4.0.10-beta-*",
					"System.Globalization.Calendars": "4.0.0-beta-*",
					"System.IO": "4.0.10-beta-*",
					"System.Linq": "4.0.0-beta-*",
					"System.Net.Sockets": "4.0.0-beta-*",
					"System.ObjectModel": "4.0.0-beta-*",
					"System.Reflection": "4.0.10-beta-*",
					"System.Runtime": "4.0.20-beta-*",
					"System.Runtime.Extensions": "4.0.10-beta-*",
					"System.Threading": "4.0.0-beta-*",
					"System.Threading.Thread": "4.0.0-beta-*"
				}
			},
			"net45": {
				"dependencies": {
				}
			}
		}
	}

**Comment by nblumhardt** [comment]
Thanks! This might be the cause of the issues holding back #283 - will take another look.

**Comment by Devbot-Net** [comment]
Apologies for the haphazard issue report.  Using the above project.json we were aple to kpm build serilog.  Is it the intent to keep the version number in-line with the KRE are have you not decided how to pull the Serilog version number through?

In either case, with the project.json it does produce a consumable Serilog nuget package through the vnext build process.  Let me know if I can be of assistance in the build (my personal vnext projects also need to build through appveyor).

**Comment by nblumhardt** [comment]
Some help with this would be enormously appreciated here, especially getting the binary into the NuGet package via AppVeyor (!!!!)

I'm only just starting to get familiar with vNext myself - @kanchanm helped kick things off with the first Serilog port, but as you can see I've had some trouble getting binaries out in a consumable form.

If there's any possibility you can put together a PR that's compatible with our CI process (I can update AppVeyor config as required) that would be absolutely wonderful :)

Thanks for all the input!

**Comment by Devbot-Net** [comment]
I know it's not quite a PR, but I have something for you. :)

If you check out my example repo (fully fledged vnext web and vnext class library) you should find everything you need to get this building through appveyor.

http://puu.sh/ex8vl/bc416a6733.png

I've exported the appveyor.yaml with deployments disabled and dropped it into the repo too so you should have access to everything you need.  The repo needs a fair bit of cleaning; through all the iterative trial & error I've likely left some superflous lines and files, but it's 02:30AM and I need my sleep.  If I get a chance I'll look into putting together a PR for Serilog but no promises.

**Comment by Devbot-Net** [comment]
My company would really like Serilog corrected so we can use it inour vNext projects so looks like I'm doing that PR; or at least getting the ball rolling.

Would it be possible to get a copy of the appveyor.yaml (after removing anything you want to remain hidden?).

Unless suggested otherwise I've created a local feature branch and will grind through the vnext changes across the entire solution if possible.  I fear some of the sinks/extras may have dependencies not available under vnext (yet?) but I'll tackle that as I get to it.

The intention right now is to extend the existing build.ps1.  I'll leave all the existing process, but provide additional switches to kick off vnext builds.  For example, the build.ps1 params might look like:

    param(
        [String]   $majorMinor = "0.0",  # 1.4
        [String]   $patch = "0",         # $env:APPVEYOR_BUILD_VERSION
        [String]   $customLogger = "",   # C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
        [Switch]   $notouch,			 # When not set, Major & Minor assembly versions are updated
    	[Alias("r")]
    	[String]   $runtime,             # KRE Runtime (default: $null > MSBuild)
    	[Switch]   $x86 = $false,        # KRE Arch (default: x86)
    	[Switch]   $amd64 = $false,      # KRE Arch (default: x86)
    	[String[]] $args=@()             # KRE Version (default: 1.0.0-beta1)
    )

**Comment by Devbot-Net** [comment]
Options for the runtime are currently limited to "CoreCLR" and "CLR" in keeping with the deprecated svr runtimes.

I have *not* attempted to add in any of the other projects yet.  The build process will attempt to build any projects that contain a project.json.  For the most part a simple copy/paste of the project.json from the Serilog project into a given project should be enough to have it build.  Unfortunately I've run out of time for now.

I tested this locally on clean installs; assuming nuget and such is on your $env:Path, the msbuild will run as per normal, whilst adding a supported runtime argument when calling build.ps1 will kick off a vnext build.  The vnext build dependencies will install themselves to path so no additional pre-requisites should be required to build.

**Comment by nblumhardt** [comment]
Howdy again, sorry about the long pause on this. The `dev` branch is now lined up with ASP.NET 5/CoreCLR/project.json. We're tracking final tasks with the `v2` label.
