### ISSUE TITLE
Serilog.Extras.FSharp does not work on w/Console applications

### ISSUE THREAD

**Issue by ghuntley** [serilog/serilog#358]
Relates to issue #354 - rather than raise the dead this is a new issue.

Serilog.Extras.FSharp installs correctly into Libraries but totally does not work on Console Applications.

See https://github.com/ghuntley/fsharp-serilog-bug-repro

    PM> Get-Project Library | Install-Package Serilog.Extras.FSharp
    Attempting to resolve dependency 'Serilog (ÎåÎíÎå 1.4.128)'.
    Installing 'Serilog 1.4.128'.
    Successfully installed 'Serilog 1.4.128'.
    Installing 'Serilog.Extras.FSharp 1.4.128'.
    Successfully installed 'Serilog.Extras.FSharp 1.4.128'.
    Adding 'Serilog 1.4.128' to Library.
    Successfully added 'Serilog 1.4.128' to Library.
    Adding 'Serilog.Extras.FSharp 1.4.128' to Library.
    Successfully added 'Serilog.Extras.FSharp 1.4.128' to Library.

    PM>  Get-Project ConsoleApp | Install-Package Serilog.Extras.FSharp
    Attempting to resolve dependency 'Serilog (= 1.4.128)'.
    'Serilog.Extras.FSharp 1.4.128' already installed.
    Adding 'Serilog 1.4.128' to ConsoleApp.
    No exact match found for removing reference 'Serilog'. Trying case-insensitive search...
    Failed to find match for removing reference 'Serilog'.
    No exact match found for removing reference 'Serilog.FullNetFx'. Trying case-insensitive search...
    Failed to find match for removing reference 'Serilog.FullNetFx'.
    Install-Package : Failed to add reference to 'Serilog'.
    At line:1 char:1
    + Install-Package Serilog.Extras.FSharp
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by nblumhardt** [comment]
Hi Geoffrey - I have a feeling this might be some VS/FSharp/NuGet flakiness; my original test case was a console app, and on my machine I get:

```
PM> install-package serilog.extras.fsharp
Attempting to resolve dependency 'Serilog (≥ 1.4.128)'.
'Serilog.Extras.FSharp 1.4.128' already installed.
Adding 'Serilog 1.4.128' to ConsoleApp.
Successfully added 'Serilog 1.4.128' to ConsoleApp.
Adding 'Serilog.Extras.FSharp 1.4.128' to ConsoleApp.
Successfully added 'Serilog.Extras.FSharp 1.4.128' to ConsoleApp.
```

Not sure if there's a VS version issue at play, or something else? Please let me know if you turn up any other clues.

Thanks!

**Comment by ghuntley** [comment]
Hey Nick, 

So this morning, using the exact same laptop and solution as the repo with the exact same visual studio instance running I was able to install into the console app. 

Upstream issues with NuGet.org? No freaking idea :-)

![Magic!](http://www.quickmeme.com/img/b3/b370b882311d3a5e1fbc78219ca6da535cf734d9bc1d74d1c5ef23a793343834.jpg)

    PM> nuget
    NuGet Version: 2.8.50926.602

    PM> install-package serilog.extras.fsharp
    Attempting to resolve dependency 'Serilog (≥ 1.4.128)'.
    'Serilog.Extras.FSharp 1.4.128' already installed.
    Adding 'Serilog 1.4.128' to ConsoleApp.
    Successfully added 'Serilog 1.4.128' to ConsoleApp.
    Adding 'Serilog.Extras.FSharp 1.4.128' to ConsoleApp.
    Successfully added 'Serilog.Extras.FSharp 1.4.128' to ConsoleApp.

**Comment by nblumhardt** [comment]
Awesome :) thanks for the report nonetheless!
