### ISSUE TITLE
AssemblyVersion Not Updated

### ISSUE THREAD

**Issue by blachniet** [serilog/serilog#359]
The `AssemblyVersion` does not appear to be updated with each NuGet release. It looks like the `AssemblyFileVersion` and `AssemblyInformationalVersion` are regularly incremented, but not the `AssemblyVersion`. 

This causes problems for me because I'm using Serilog in an environment in which multiple versions of the Serilog dll exist in the directory (all with different names, of course, e.g. *Serilog.1.4.118.dll* and *Serilog.1.4.128.dll*). Since they all have the same `AssemblyVersion`, it appears to just load the first one it comes to. This results in an older version of Serilog being loaded that doesn't have the classes I expect.

For example, [Serilog v1.4.118](http://www.nuget.org/packages/Serilog/1.4.118) and [Serilog v1.4.128](http://www.nuget.org/packages/Serilog/1.4.128) both have an `AssemblyVersion` of **1.4.0**.

**Comment by nblumhardt** [comment]
Hi Brian, thanks for the report. This is by design - using a stable assembly version prevents annoying binding issues (each time it changes there's a huge ripple-on of rebuilds through the ecosystem). HTH! Nick
