### ISSUE TITLE
Update Azure Application Insights sink to new API

### ISSUE THREAD

**Issue by chuwik** [serilog/serilog#360]
I see that the current ApplicationInsights sink in the serilog repo is for the old version (working for Visual Studio Online) which is now deprecated. The new version works with Azure, and the SDK, etc. are different.

Looking into the PRs, I found that @jbattermann updated the sink to this new version but left it in another repo (to avoid problems with pre-release). 

May I suggest deleting the current ApplicationInsights sink from the Serilog repo, since it's now deprecated, and maybe pull the other repo in or update the documentation to send people to it? Otherwise it's pretty difficult to discover there's a new version for Azure Application Insights unless you look at the closed pull requests or search in NuGet for pre-release packages.

I can send a PR updating the documentation once you confirm if you want to do something with this.

(Please @jbattermann, correct me if I got something wrong!)

**Comment by jbattermann** [comment]
Hi @chuwik - you're absolutely right. I basically kept the new one out of the main serilog repository as there were two breaking changes in MS's AI API after the old (0.71.. which was strangely *not* marked as a pre-release) one and as long as the 'new' AI API is still tagged as pre-release, I think it might be the best to keep it that way and once Application Insights goes GA, I'll happily merge the bits over to serilog.

In the meantime it might indeed really be the best to improve the discoverability regarding old vs new type of Application Insights.

**Comment by chuwik** [comment]
Silly question... is it possible to do a pull request on the wiki? :)

I think it requires having some permissions on the project (which I don't have).

**Comment by nblumhardt** [comment]
Thanks for the input guys! I think the best thing here would be to simply update the in-repo sink to the new version - adding docs etc. may just create confusion when we move forward.

@jbattermann are you interested in PR'ing this, or is it up-for-grabs? Cheers!

**Comment by jbattermann** [comment]
@nblumhardt alright & yeah I'll do it over the weekend and do it the other way around.. unlist my separate sink and refer back to the then-updated in-repo one. good stuff.

**Comment by nblumhardt** [comment]
@jbattermann awesome, thanks!

**Comment by nblumhardt** [comment]
New -pre package is now on NuGet
