### ISSUE TITLE
MSSql Sink should have the SourceContext as a column

### ISSUE THREAD

**Issue by worldspawn** [serilog/serilog#361]
Hi there, IMHO the SourceContext should be a first class column on the ms sql sink table. Having it buried in the properties xml cancels out its usefulness as I can't (easily/performantly) query by sourcecontext. The documentation for the ForContext method states

[Writing Log Events](https://github.com/serilog/serilog/wiki/Writing-Log-Events)

>The event written will include a property SourceContext with value "MyNamespace.MyClass" that can later be used to filter out noisy events, or selectively write them to particular sinks.

I don't think the current implementation achieves this as I cannot use it to filter rows from a sql query.

**Comment by nblumhardt** [comment]
Hi @worldspawn  - thanks for the input, this would indeed be useful; perhaps the MSSql sink could be configured with a list of log event properties that would be elevated to Column status?

It's unlikely we'll address this as an issue in the near future, but we would be interested in a PR if you decide to have a shot at this.

Best regards,
Nick
