### ISSUE TITLE
Loggly Sink throws System.TypeLoadException

### ISSUE THREAD

**Issue by samirahmed** [serilog/serilog#362]
`I don't know why this is ... but if i explicitly download

`Install-Package loggly-csharp` in the package manager console and it replaces the existing one ... it works just fine ...

Took me a while to figure that out ... i don't know really know how to fix it / test the fix so i didn't submit a pull request

**Comment by nblumhardt** [comment]
Thanks - I updated the relevant packages, new build should be out in a few hours
