### ISSUE TITLE
CI support for MonoTouch and MonoAndroid projects

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#363]
Both are currently excluded from the release build. There are two ways we could enable them-

 * Find a way to get the MSBuild targets onto AppVeyor, or
 * Turn the libraries themselves into standard PLIBs

From #125

**Comment by ghuntley** [comment]
Yo Nick - call me +61404654654 to discuss :)

**Comment by jbattermann** [comment]
Oh this would be nice - I started to create a sink for [Xamarin Insights](https://xamarin.com/insights), but I personally do only have an Xamarin.iOS subscription (and not an Android one) and even though I could work around this by manually editing the files, I wasn't quite sure who / how the serilog Build infrastructure would handle these projects.

**Comment by nblumhardt** [comment]
This will also require some project work; #377 removed these two from the default solution

**Comment by ghuntley** [comment]
Still in talks with Xamarin, no update yet.

**Comment by merbla** [comment]
AppVeyor supports Xamarin builds however a licence [may be](http://www.appveyor.com/docs/lang/xamarin) required.  I have a licence under my org however not sure I can share over two AppVeyor organisations.  @nblumhardt happy to do this build on my org if that works.

**Comment by ghuntley** [comment]
@merbla https://blog.xamarin.com/xamarin-continuous-integration-early-access-program/ coming soon!

**Comment by merbla** [comment]
@ghuntley @nblumhardt logged a submission on behalf of the Serilog project. Will see how it pans out.

**Comment by nblumhardt** [comment]
Personally I'm not sure we want to carry the burden of a whole extra CI service for this. Since everything is portable nowadays, are we covered well enough by the PCL and its tests?

**Comment by nblumhardt** [comment]
Ah, my mistake - forgot we still have https://github.com/serilog/serilog-sinks-xamarin without CI. How's this going?

**Comment by ghuntley** [comment]
@merbla you heard anything back? I also sent through a submission and pitched getting ReactiveUI on their environment directly to the product manager. Nothing yet.

**Comment by merbla** [comment]
@ghuntley @nblumhardt nothing so far.  Might send a link to this.

**Comment by ghuntley** [comment]
@merbla here's the contact details of the CICD product manager at Xamarin. No update on my end yet.

    Justin Raczak <justin.raczak@xamarin.com> (Product Manager, Xamarin Test Cloud)
    https://www.linkedin.com/in/justinmraczak
    https://twitter.com/justinraczak

**Comment by ghuntley** [comment]
@merbla I heard back from Xamarin today, expect an announcement in the next couple of weeks.

**Comment by merbla** [comment]
@ghuntley any news on your end re: this one?

**Comment by ghuntley** [comment]
Alright, it is possible to generate library .dlls on Windows for Android
and iOS. No need for a Mac to do that. You only need a Mac to generate
IPA's.

With that in mind, it is possible to generate and package for Xamarin using
AppVeyor on Windows. The Xamarin CI ended up being a partnership with
Bitrise. Bitrise does builds on OSX.

Happy to answer any questions people may have and share learning's from
working on the ReactiveUI CI story but I won't be the one to implement this
for Serilog. UpForGrabs for someone else to do.

**Comment by merbla** [comment]
@ghuntley thanks for the info!

**Comment by nblumhardt** [comment]
I promise it's the last time I'll suggest it :-) ... but, since it's such a PITA to support Xamarin, I'd rather close this until someone who has the time and licenses comes along and picks it up. Otherwise it's just cluttering things up here. For/against?

**Comment by nblumhardt** [comment]
Added the following message to the Xamarin sink README:

> This sub-project needs an active maintainer. Without an owner/owners who both have the knowledge and software licenses required to support Xamarin, we've been unable to move this forwards. Please raise an issue on the Serilog tracker if this is you :-)

Apologies if I'm jumping the gun; I'm keen to support this but currently the level of attention given to that project has fallen below the others here.

**Comment by nblumhardt** [comment]
Happy to reopen this if we can make forward progress but not looking like there will be any action here in the short-term.
