### ISSUE TITLE
Migrate MongoDB driver to the C# v2 driver

### ISSUE THREAD

**Issue by aaronpowell** [serilog/serilog#364]
A few days ago MongoDB released a [preview of the v2](http://www.nuget.org/packages/mongoDB.Driver/) driver as a NuGet package.

I'm not 100% across what's new other than:

* Async support
* Most things are now exposed as interfaces, such as `IMongoDatabase` and `IMongoCollection`
* Strongly typed collections are first-class citizens
* No more LINQ like they use to do, instead lambda's are first-class on the `IMongoCollection<T>`

I want to upgrade our app to it, primarily for the async support, but due to the breaking changes it's not able to do binding redirects from v1.x to v2.x against Serilog.

I've created a fork, patched the Sink to support the v2 preview driver (see https://github.com/aaronpowell/serilog/commit/f9c5c7145b73ba18f0d5cd8839c2bd2094262ab8) but have hit a problem, **the new driver is not signed**. This means that I've had to remove signing from the Sink (https://github.com/aaronpowell/serilog/commit/f9c5c7145b73ba18f0d5cd8839c2bd2094262ab8#diff-2161abde4e7f86c75328a0726a6571f0L38) while I work on it.

The other thing is that this is a breaking change dependency, if you're using the MongoDB 1.x driver probably can't upgrade to the new sink. _At least, that's what I think, it looks like all the old code is there just most methods are obsolete. I didn't try a binding redirect as I'm not sure how that plays with going from signed to unsigned assemblies._

I'd prefer not to have to create `Serilog.Sink.MongoDB-v2` or anything, so I'll be looking for feedback on how to approach:

* Updating to the new driver
* Handling the lack of strong name
* Versioning the sink appropriately (since this is done by the Build.ps1 from what I can gather)

I'll continue to test it in our app for the mean time (I don't need strong naming).

/cc @nblumhardt @jaben

**Comment by craiggwilson** [comment]
Hey Aaron, thanks for doing this. LINQ will be coming in 2.1. We just ran out of time and decided to do some Expression tree stuff where it made sense. We haven't bailed on LINQ.  

We've tried to keep as much backwards compat as possible without pinning ourselves down.  I'd be surprised if most people couldn't just update to the 2.0 driver, ignore a warning about client.GetServer() being deprecated, and continue on as normal.  If there is anything specific you come up with, please let us know via jira.mongodb.com in the CSHARP project and we'll try and handle it.

Regarding signing: the general (and overwhelming) consensus in the community seems to be that signing sucks and not to do it. Our current driver (1.x) is signed with a private key in our public repo, so it isn't doing much good anyways.  Do you think we are making a mistake here?

**Comment by aaronpowell** [comment]
@craiggwilson Good to know LINQ is coming back but really the new interface is nice to work with (although a bit tricky to work out some of it without docs :stuck_out_tongue:, I've been in the tests). I really like Aggregate.

Also good to know that it is backwards compatible, it _looked_ like it when going into the code but I wasn't sure.

Regarding signing, I agree that it's nothing more than a pain. The question around it is more to the serilog team, how they want to run with non-signed external dependencies.

**Comment by Jaben** [comment]
@aaronpowell Not trying to talk for Nick here, but he already addressed the signing issue in a previous pull request (https://github.com/serilog/serilog/issues/161): "Yep; sinks that can be signed should be, but if a dependency isn't then an unsigned sink is perfectly fine."

**Comment by Jaben** [comment]
@aaronpowell My suggestion is mark the v2 sink as prerelease-beta and with a major version increment. But @nblumhardt will need to weigh in on how he wants to proceed.

**Comment by aaronpowell** [comment]
I'd also keep it as pre-release while it is referencing the pre-release MongoDB driver

**Comment by nblumhardt** [comment]
Prerelease with major version increment sounds good - I've just merged #365 which requires the same thing and created #368 to track the required build changes (in case anyone wants to pick that up :))

Thanks all!

**Comment by nblumhardt** [comment]
#344 is ultimately intended to help with this too - though it's a bit further off.

**Comment by aaronpowell** [comment]
Ah right

**Comment by nblumhardt** [comment]
Changed direction; created the standalone repository here: https://github.com/serilog/serilog-sinks-mongodb - all building/publishing `-pre` packages to NuGet.
