### ISSUE TITLE
Support major version increments in the build script

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#368]
Some sinks, recently Application Insights (#365) and MongoDB (#367) need to rev ahead of Serilog. We need to support this in Build.ps1 before these can be merged to master.

**Comment by aaronpowell** [comment]
I'd also suggest the ability to generate pre-release builds (the Mongo PR fails as it references a pre-release package). Shall I create a separate issue for that?

**Comment by nblumhardt** [comment]
I think including that is implicit in this one - thanks. (Success criteria here should be producing a _2.0.x-pre_ build of the Mongo sink.)

**Comment by nblumhardt** [comment]
Closing this in favor of separate repositories - e.g. see https://github.com/serilog/serilog-sinks-mongodb
