### ISSUE TITLE
Exception Data property is treated as Sequence, rather than Dictionary

### ISSUE THREAD

**Issue by konste** [serilog/serilog#371]
System.Exception.Data property is IDictionary. i.e. not generic. 

When exception object is destructured PropertyValueConverter.CreatePropertyValue compares property type with Dictionary<,> and does not recognize dictionary in it. Then it checks if it is IEnumerable and as it is - IDictionary get destructured as SequenceValue which is very wrong.

Only after that (in the same method) destructuring policies are checked, so there is no way to provide destructuring policy for IDictionary - it never gets called. 

This throws a wrench into my attempt to get rid of huge custom Exception destructurer and rather treat Exception as the regular StructureValue. 

Any idea how to work around it? 
What is recommended here https://gist.github.com/nblumhardt/dddaa2139bbf4b561fa7 would not work well for the case when inner exceptions also have something in their Data dictionary.

**Comment by nblumhardt** [comment]
This should be fixed in the next build (168), which allows destructuring policies to run before the built-in support for IEnumerable.

**Comment by konste** [comment]
Thanks a lot!

Could you please provide an example of destructuring policy implementation to allow handling of IDictionary as a dictionary, for the benefit of exceptions destructuring. Or may be even build it in and recognize non-generic dictionaries in the same way as you do for generic ones?

< sent from mobile device >

On Feb 7, 2015, at 5:58 PM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


This should be fixed in the next build (168), which allows destructuring policies to run before the built-in support for IEnumerable.

-
