### ISSUE TITLE
Custom global format

### ISSUE THREAD

**Issue by slav** [serilog/serilog#372]
For example, anywhere DateTime is logged, including as part of {@structuredObject}, allow me to specify how it's logged.

Basically global format configuration per type.

**Comment by nblumhardt** [comment]
Hi Slav - thanks for the suggestion. We already have a few different mechanisms either implemented or planned for this, can you please give us a concrete example of what you'd like to do?

Thanks!

**Comment by slav** [comment]
Here's what I ran into. I have log message with {@object}, and inside the object at some level there's DateTime. I want to customize how it's logged. Default ToString for DateTime isn't really very well suitable for logging (at least I personally don't like it). So, I was hoping to specify how to serialize any DateTime, since format would be the same everywhere.

**Comment by nblumhardt** [comment]
Thanks - makes sense. This is still probably something that needs to be done at the sink level, since different sinks will need different formats even when the "presentation" format is adjusted in this way.

Many sinks accept a custom `ITextFormatter` that could in principle be substituted in order to provide this behaviour. Some reuse of the existing provided formatters would be possible.

Having said that, I have no idea how much effort would actually be required - it'd be interesting to have a dig around. Let me know if you decide to take a look. Cheers!

**Comment by slav** [comment]
Why would it need to be done at the sink level? I got impression for basic value types by default ToString is always used. So, I just want to customize ToString used by default for value type with default format string. For non-valuetype I can customize how to serialize it with destruct config, right?

**Comment by nblumhardt** [comment]
Hi Slav,

The destructuring configuration you mention is for deciding what logged data becomes part of the serialized representation, but the formatting decisions are all deferred to the sinks (a `DateTime` has a specific format in SQL vs typical JSON vs ...).

The current design of Serilog for the most part defers display-related decisions to the sinks via a few different helper classes for display, message template rendering and so-on.

I'm not sure among them where the nicest place to try plugging this in might be - there's definitely some investigation/experimentation involved.

One left-field idea might be to pass an `IFormatProvider` to the sink configuration:

```csharp
  .WriteTo.TextWriter(..., formatProvider: x)
```

The format provider will be used in all `ToString()` operations, so you could possibly plug one in that special-cased `DateTimes`?

HTH!

**Comment by nblumhardt** [comment]
Thanks again for raising this, did you get anywhere using `IFormatProvider`? Closing for now as I can't see an obvious way forward for us here, but feel free to reopen it if you have any ideas. All the best!
