### ISSUE TITLE
File Sink does not work well between multiple AppDomains

### ISSUE THREAD

**Issue by konste** [serilog/serilog#380]
When process spins up multiple AppDomains (with ASP.NET being the most natural example) each domain gets its own copy of LoggerConfiguration and Log, which is the right thing to do for the sake of domain isolation. When File Sink is used we need to provide some file name for the log file. In my case log initialization code is not aware that because of multiple domains it is going to be run multiple times and give all log files the same name. As the result logs coming from different threads running in different AppDomains continuously step on each other trying to write to that file and end up incrementing file name suffix and starting new file. What I end up with is rather useless as you can imagine – several (up to configured number) very short log files with weird suffixes, covering very short time period. 

What can be done (on Serilog part or on the application part) to mitigate that problem? One way would be to come out with some smart algorithm to give log files unique name every time (say slap a GUID as the suffix). But on the other hand all those log events are coming from the same process, very much related to each other and ideally we should be able to see them all in the same file. So another way is to make File Sink somehow shared between AppDomains and still producing single log file, in the same way as it handles logs coming from the different threads. 

Thoughts?

Konstantin

**Comment by konste** [comment]
This problem caused us lots of grief, so I had to come out with a workaround, which I have published here: http://1drv.ms/1Fc83zN 

Primary idea is to create RollingFile sink as AppDomain aware singleton (i.e. always just one per process and created in default domain). During Log configuration instead of actual RollingFile sink I create and use proxy objects, which expose the actual underlying sink for logs coming from default AppDomain and transparent proxy to singleton for other domains.  

The problem is that only serializable objects may be marshalled across AppDomain boundaries, and LogEvent class is not serializable. I had to split the task and let proxy object do serialization part and then send resulting string to singleton which finishes processing. 

As RollingFile sink is all private and sealed I had to use reflection to get to its internals, which is extremely hacky and fragile, but I don't see other choice until built in sinks get a little more inheritance friendly.

Let me know if you have any questions, see flaws or can propose better solution.

**Comment by nblumhardt** [comment]
Thanks for sharing your workaround. There have been a good many discussions around this topic in the past, mostly coming back to the problem of available workarounds having issues of their own. Your approach is a reasonable direction for you to take.

One possiblilty that I hadn't considered earlier, but which may be a contender for support in our "2.0", is a `serilogd` process that can run alongside these sorts of ephemeral/clustered process models and handle logging on their behalf.

Essentially, the process would accept events over a local socket and dispatch them to configured sinks, dealing with coordination issues like the shared-file one. This is similar to the approach that would be taken by ETW and several other log collection facilities. It may have some stability benefits.

It's certainly non-trivial, hence this note just to get the idea "out there". It would be great to start nailing something down, but as it stands the file-sharing scenario in its current formulation seems unlikely to get direct support.

Keen to hear any other perspectives out there. Cheers!

**Comment by nblumhardt** [comment]
Still something that would be cool to look at someday, but unlikely to move forward right now so closing this one. Cheers!

**Comment by Shazwazza** [comment]
@konste Any chance you still have your work-around handy? (the link above no longer works). Or is there a new built in work around these days as I'm having the same problem.

**Comment by Shazwazza** [comment]
Ah, looks like our problem is solved by the `shared` parameter of the file sink.
