### ISSUE TITLE
Set up source/build/CI for Exceptionless sink

### ISSUE THREAD

**Issue by niemyjski** [serilog/serilog#381]
There is a Sink for Exceptionless that supports .NET 4.0 and 4.5 located here: https://github.com/enkafan/Serilog.Sinks.ExceptionLess

I'm talking with the author about possible pcl support as we recently added this.

I didn't see any way to update the wiki myself..

**Comment by nblumhardt** [comment]
Hi Blake, thanks for dropping by! At the moment, we only list the sinks provided by the Serilog project - i.e. those we provide maintenance/support for. I am happy to add a list of third-party sinks there, but if it would suit you and @enkafan we'd also be happy to maintain an Exceptionless sink as part of Serilog. No problem either way! :-) Cheers, Nick.

**Comment by niemyjski** [comment]
If you would maintain it that would be awesome! I'll also do what I can. Just let me know what you need and I'll try my best to make it happen. I created an issue there as I'm not the project owner :\ ( https://github.com/enkafan/Serilog.Sinks.ExceptionLess/issues/3 ).

**Comment by enkafan** [comment]
I'd glad to hand it on over to a proper home. Let me know how we can best transition this and I'll make it happen

**Comment by niemyjski** [comment]
Is there any updates on this? We've released 2.0 which features logging. I'd be more than happy to take it over as well @enkafan. If you want to add me to the project and nuget feed (https://www.nuget.org/profiles/niemyjski), I'd be more than happy to do the work.

**Comment by nblumhardt** [comment]
Thanks for the reminder. https://github.com/serilog/serilog-sinks-exceptionless now exists and you both have access.

The structure needs to be something like  https://github.com/serilog/serilog-sinks-email for it to play nicely with the build.

Once you're ready to publish a version, please add the NuGet user `serilog` as an owner of the package, and ping me via this ticket so I can set the CI build up.

Many thanks!

**Comment by niemyjski** [comment]
Will do, @enkafan can you please add me as an owner to the existing nuget package.

**Comment by enkafan** [comment]
@niemyjski - You bet. Username the same on nuget?

**Comment by niemyjski** [comment]
@enkafan yep :) Thank you

**Comment by niemyjski** [comment]
@enkafan I really appreciate all the work you have done! Please let us know how exceptionless is working out for you.

**Comment by niemyjski** [comment]
I just made major changes (untested but I'm pretty confident with my changes) to support 2.0. However there are some issues that I came across. If someone (@merbla, @enkafan) could test the changes that would be greatly appreciated (I'm a serilog nub :\).

* How do you get the log source ([The type that sent the log message](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/ExceptionlessClientExtensions.cs#L10).
* Reading the api key from an [xml config](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/ExceptionLessSink.cs#L30-L40)? If we made this change we could use a in memory client that offers better performance.

**Comment by niemyjski** [comment]
@nblumhardt Is there any chance I could get access to the app veyor build system so I can setup the readme with the build status/nuget. Unless there is something I can do to give you nuget push access.

**Comment by merbla** [comment]
@niemyjski I have updated the build, that PR was only half baked :) 

Also noticed there is 3.0 of ExceptionLess.  Is that the new target?

**Comment by merbla** [comment]
@niemyjski I have updated the readme with the badge (url is convention based).  Also, I need to do another PR to move the solution to the root as apart of the clean up.

**Comment by merbla** [comment]
@niemyjski build basics are setup.  `1.1.10` is the current version of the existing package on NuGet.  I have set the build up to be `1.2`. Authors may need to be updated.

@nblumhardt do we just use the existing NuGet key if `serilog` has been granted access?

**Comment by niemyjski** [comment]
@merbla Yes, that's the latest version of the client that supports log messages, exceptions and feature usage. I think I also need to change back the namespace of the classes to be Serilog.Sinks. Can you please confirm this? I changed it to serilog as that is what you had put as the default namespace of the assembly.

**Comment by niemyjski** [comment]
@merbla can you please take a look at my todo in there and fill in the log source (in nlog the source is set to the type of the class that called log).

**Comment by niemyjski** [comment]
@enkafan Can you please remove your old repo (I'm not sure why it wasn't transferred to the new one). But now there is duplicates for this plugin.

**Comment by merbla** [comment]
hey @niemyjski,
- re: the namespaces, I also changed to use the folder structure of the other sinks.  The fall out is the namespaces will follow folder structure.  e.g. [ExceptionLess.cs](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/Sinks/ExceptionLess/ExceptionLessSink.cs) moves to the namespace `Serilog.Sinks.ExceptionLess`.  Is that what you were referring to?

- re: the TODO, will try to have a look at it this weekend.
- re: versioning, are you ok with `1.2` of the sink when this is cleaned up?

**Comment by niemyjski** [comment]
@merbla Yes, that's what I was referring to.

I think it needs to be moved to 2.0. Because if you were using exceptionless 1.5 you are now migrating to 3.0 which has breaking changes. If you think otherwise, that is fine... But then we need to update the changelog and readme. I'm also thinking that it's pointless to have a change log and a read me when the readme is also a change log. We need to get rid of the changelog in the readme.  I'd prefer just to have release notes as past of a github release.. That way it's much cleaner.

**Comment by merbla** [comment]
@niemyjski I have updated the Appveyor build to be 2.0, I have also cleaned up the readme so feel free to update accordingly.

As for the previous mentioned [TODO](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/Sinks/ExceptionLess/ExceptionlessClientExtensions.cs) what do you mean by source?  The calling class of Log.Information?

**Comment by merbla** [comment]
Hi @niemyjski any thoughts on the TODO?  This is ready to go once the [NuGet Ownership](https://www.nuget.org/packages/Serilog.Sinks.ExceptionLess/) is transferred.

**Comment by niemyjski** [comment]
@merbla Who do I need to add as an owner? Yes, that should be what the source is set to: the calling class.

**Comment by merbla** [comment]
@niemyjski transfer to Serilog

**Comment by niemyjski** [comment]
Added :)

**Comment by merbla** [comment]
@nblumhardt anything in Serilog to [log the calling class](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/Sinks/ExceptionLess/ExceptionlessClientExtensions.cs)? Fody?

**Comment by nblumhardt** [comment]
In Serilog the "calling class" comes through as a property named `"SourceContext"`, but only if the user has passed it e.g. by using `ForContext<MyType>()`.

There have been a few discussions on this over time, there's not really a nice way of doing this automatically without something like Fody.

(Fody will pass this info as `"SourceContext"` as well, when using Serilog, so supporting that is the way to go :))

**Comment by niemyjski** [comment]
We'll it shouldn't hurt to update it to SourceContext (does someone want to make that change?) At least then it will be set if they specified it. It would be nice to automatically set it because you do have the caller attributes.

**Comment by nblumhardt** [comment]
@niemyjski we're spread a bit thinly :-) feel free to give it a shot.

Caller attributes, sadly, don't play nicely with `params` argument lists, so no joy there unfortunately.

(An override of `Log.ForContext(...)` that looked like `Log.ForCaller()` might be a nice happy medium...?)

**Comment by merbla** [comment]
@niemyjski I have pushed to NuGet  Can you check the [package](https://www.nuget.org/packages/Serilog.Sinks.ExceptionLess/) it does not have the `SourceContext` changes however I have opened #439 to address that specific issue.

**Comment by niemyjski** [comment]
Thanks, I'll take a look into source context
