### ISSUE TITLE
Meta package for Reactive Extensions

### ISSUE THREAD

**Issue by khellang** [serilog/serilog#383]
Consuming observables without the actual Rx library, i.e. using only `IObservable<T>` and `IObserver<T>` is Real Hard™.
Actually, general Rx guidelines says that you should never (at least very rarely) have to implement either of those interfaces.

I think we should either pull the observable sink into a separate package (this would have the added benefit of not having to implement `IObservable<T>` and will substantially simplify the sink's code), or create a meta package that has a dependency on `Serilog` and `Rx-Main`.

Some naming suggestions:
 - `Serilog.Reactive`
 - `Serilog.Rx`
 - `Serilog.Sinks.Observable`

What do you think?

**Comment by nblumhardt** [comment]
I'm not sure - if it ain't broke...? (Unless of course it is..... :))

I guess I read the advice like: "if you're using _LINQ_, you should rarely have to implement _IEnumerable<>_"

If there's more interesting work we can do using Rx, would it fit a `Serilog.Extras.Reactive`?

**Comment by nblumhardt** [comment]
@khellang let me know if you think moving forward on this one would still make sense; I'm wondering if maybe consuming observables is hard, but implementing them not-so-much? Seems like things are reasonable but I'm totally keen on an education if you can point me in the right direction :) Cheers!

**Comment by khellang** [comment]
There are only two observable interfaces in the framework, `IObservable<T>` and `IObserver<T>`. The rest of the magic comes from the Reactive Extensions libraries. IMO it makes no sense to consume an `IObservable<T>` _without_ Rx, i.e. implement your own `IObserver<T>`.

This proposal was mainly just to make it easier to use the reactive sink (i.e. just install a package with Rx as a dependency).
The other part (pulling the Rx sink into it's own package) was just an idea to simplify and make the code more maintainable, but as you say; if it ain't broke :smile:

It's not a big deal... I can (continue to) live without the meta-package :wink:

**Comment by khellang** [comment]
Here's an example of consuming an `IObservable<T>` with and without Rx:

### With

```csharp
public class RxExample
{
    public IDisposable Subscribe(IObservable<string> observable)
    {
        return observable.Subscribe(Console.WriteLine);
    }
}
```

### Without

```csharp
public class RegularExample
{
    public IDisposable Subscribe(IObservable<string> observable)
    {
        return observable.Subscribe(new ExampleObservable());
    }

    private class ExampleObservable : IObserver<string>
    {
        public void OnNext(string value)
        {
            Console.WriteLine(value);
        }

        public void OnError(Exception error)
        {
            // Don't care.
        }

        public void OnCompleted()
        {
            // Don't care.
        }
    }
}
```

This is the simplest example I could come up with, and you can see the amount of code involved is 4x :disappointed:

**Comment by nblumhardt** [comment]
Thanks! In our case we're implementing the observer, not the subscriber, so I think we're cool - but will keep an eye on it. Cheers!
