### ISSUE TITLE
MSsql sink writes times as local time

### ISSUE THREAD

**Issue by btrepp** [serilog/serilog#392]
Would it be possible to have this write in UTC?. Sadly the datetime column doesn't store any timezone information. It would be better if we assume this is UTC and convert to local time when pulling it out.

**Comment by abrussak** [comment]
I haven't looked at the implementation but you could try using datetimeoffset in your table: https://msdn.microsoft.com/en-us/library/bb630289.aspx

**Comment by nblumhardt** [comment]
A `utcTimestamp: true` option in the sink configuration might be a nice addition if anyone has the time to look at it.

**Comment by the-dwyer** [comment]
I have submitted a pull request for this enhancement.

**Comment by nblumhardt** [comment]
Thanks - I forgot to "watch" the new repo so missed it come in, will take a look shortly.

https://github.com/serilog/serilog-sinks-mssqlserver/pull/1

**Comment by nblumhardt** [comment]
PR merged, thanks @the-dwyer!
