### ISSUE TITLE
Uppercasing of properties in Output Template does not work.

### ISSUE THREAD

**Issue by thinktainer** [serilog/serilog#395]
When trying to uppercase the logging level, the whole message gets swallowed.

This will reproduce the behaviour:

    using System;
    using Serilog;

    namespace ConsoleApplication1
    {
        class Program
        {
            static void Main(string[] args)
            {
                var logger =
                    new LoggerConfiguration().WriteTo.Console(outputTemplate: "{Timestamp} {Level:u} {Message}").CreateLogger();
                logger.Information("Hello, serilog");
                Console.ReadKey();
            }
        }
    }

**Comment by nblumhardt** [comment]
Interesting - must be a regression introduced when output templates were separated from message templates; thanks for the report!

**Comment by the-dwyer** [comment]
I have submitted a pull request for a possible fix to this issue.

**Comment by nblumhardt** [comment]
As per the discussion in #409, `Level` is not a string and therefore uppercase formatting does not work for it.

Uppercasing within message templates isn't currently supported - not sure we'll go down this path.
