### ISSUE TITLE
Exception Stack Trace detail stripped by sinks

### ISSUE THREAD

**Issue by richardlawley** [serilog/serilog#399]
I am trying to use Serilog (with Seq) to log unhandled exceptions in my application.  I noticed that while the console log would contain a full stack trace including source filenames and line numbers, the exception written to seq would not.  After some investigation, I believe this problem is related to the sink code, or it's an issue with the Exception class in general.  

Seq uses `PeriodicBatchingSink`, and after stepping through the code in debug mode, I discovered that the logEvent.Exception property contains the full stack trace when it enters PeriodicBatchingSink.EmitBatch.  As soon as it calls into the overridden method specific to the sink (SeqSink.EmitBatchAsync in this case), logEvent.Exception no longer contains the line number information (even if you view the variable from the previous caller in the call stack!).

I'm looking for a way to get this information passed through to Seq, preferably in the "proper" way - I'm using an enricher to serialise the stack trace into a second property at the moment as a workaround, but this is not ideal as my log message now contains two stack traces - one complete and one without line numbers.

Very simple sample program:

```
static void Main(string[] args)
{
    Log.Logger = new LoggerConfiguration()
        .WriteTo.ColoredConsole()
        .WriteTo.Seq("http://localhost:5341")
        .CreateLogger();

    try
    {
        throw new NotImplementedException();
    }
    catch (Exception ex)
    {
        Log.Error(ex, "error caught");
    }
}
```

This will cause a full stack trace to be printed to the console, but the version logged to Seq will only contain the function names - no file names or line numbers.

**Comment by nblumhardt** [comment]
Thanks for the report Richard, looking forward to figuring this one out.

**Comment by nblumhardt** [comment]
Hi Richard - I'm still stumped on this one, did you find any other clues? Cheers!

**Comment by richardlawley** [comment]
Both the test case I provided with my initial report and my production program are now logging stack traces with line numbers to Seq, so I guess this must have been accidentally fixed by something else in the last few months.  Are you still seeing the behaviour I reported somewhere?

**Comment by nblumhardt** [comment]
Hi Richard - no, thanks for the update though. Guessing there's some other factor involved. Will close for now and reopen if we get any more reports.

**Comment by nblumhardt** [comment]
Have received further reports of this. Current hypotheses - thread-safety issue in `Exception`, or a version-specific bug in that class. Re-opening!

**Comment by xclp** [comment]
Hi Nick, here are the details of the issue I found. My app is using .NET 4.5/ CLR 4 (specifically v4.0.30319, if that's even relevant).
When using both LiterateConsole and Seq, if I catch and rethrow an exception I get 2 different stack traces when logging the exception. The console shows the correct stack trace if you log the error when the exception is first caught, but in the Seq log it appears the exception has been updated with the new stack trace before Seq gets it. I need to include that, when debugging, if the error appears in Seq before the exception is rethrown then the stack trace is correct in Seq. I don't understand exactly what triggers the messages to be posted to Seq, as sometimes they appear straight away and other times I have to step through many lines of code before they appear (Periodic batching I assume, but what is the trigger?).

I hope my explanation is clear enough but if not then let me know and I'll try to clarify with some examples.

**Comment by nblumhardt** [comment]
Ah, I see - thanks Claire. I think yours is a different issue, actually. Serilog passes the actual `Exception` object around, which is (invalidly) assumed to be immutable, though most of the time this is the case.

When you catch the exception, it sounds like you're re-throwing with:

```csharp
throw ex;
```

What you can do instead is preserve the exception's stack trace by executing:

```csharp
throw;
```

Let me know if I've interpreted this correctly, and if so I think we can again close this one :-) Thanks!

**Comment by xclp** [comment]
Hi Nick, I am actually using throw, not throw ex but it seems the stack trace changes anyway. But yes, it sounds like Seq doesn't use the exception object until after it has changed, whereas the console logs it straight away. This is only a minor issue because the exception usually gives enough information to determine which line of code caused it, but there will be some cases where knowing the line number where the exception is rethrown won't be enough. No big deal if it just can't be fixed, but is there a way to force serilog to flush without closing? That way I could force the exception to appear in Seq before rethrowing.

**Comment by xclp** [comment]
Actually, forget what I just said. The stack trace should still include the line that threw the exception, it just won't be the first line mentioned. So not really an issue, it was just the difference in logs that led me to report it. Being able to force a flush would still be handy, but not necessary.

**Comment by nblumhardt** [comment]
Okay, thanks for the update Claire. I'll close this one (again) but do please raise another if you find anything still amiss. Thanks!

**Comment by JanKinable** [comment]
I'm still having the issue where the linenumbers are missing in the stack info. My setup: Serilog (2.5.0) in conjunction with AutofacSerilogIntegration (2.0.0) and Seq (Serilog.Sinks.Seq 3.4.0). The linenumbers are both missing in the logfiles as in Seq.
Reading the above comments I can't see this issue was fixed.
