### ISSUE TITLE
Textual dump of LoggerConfiguration or Logger

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#40]
With more complex configurations, a representation (either debugger view, or textual dump) of the logger configuration including sinks, enrichers, filters, sub-loggers and so-on, would be a useful debugging aid.

**Comment by thirkcircus** [comment]
hi nicholas,
i know this is an old issue but i'm looking for exactly this...

I'm periodically checking a remote location for configuration params and if it has changed, resetting the Logger configuration.

Is there any way to even read (let alone have a nice representation of) the Logger configuration once it has been assigned?  That would allow me to verify in a test that the new logger configuration is what I expect.

**Comment by nblumhardt** [comment]
Hi Justin,

No, but implementing `ToString()` on the core logger and the nested 'contextual' logger types would be a nice feature for a lot of debugging scenarios, e.g.:

```csharp
Log.Logger = new LoggerConfiguration()
  .MinimumLevel.Debug()
  .Enrich.WithMachineName()
  .WriteTo.File("log.txt")
  .CreateLogger();

var someLogger = Log.ForContext("A", 10);
Console.WriteLine(someLogger);
```

To something akin to:

```
Logger(+A=10) -> Logger(>=Debug, +MachineName, File("log.txt"))
```

I.e. just a compact descriptive format, not anything aiming to be parseable/round-trippable.

Another option might be co-opting the configuration syntax:

```
{(enrich-with:A, 10)} -> {(minimum-level, Debug), (enrich-with:enricher, MachineNameEnricher),
 (write-to:File.path, log.txt)}
```

Neither particularly awesome, but I'm keen on the general idea so long as we could make it reasonably useful and not incur any performance overhead.
