### ISSUE TITLE
Using Serilog in Topshelf makes it lock itself.

### ISSUE THREAD

**Issue by janpieterz** [serilog/serilog#400]
Using a very simple setup using Serilog in Topshelf makes it lock itself and therefore roll into a new file (00x). 
The behavior only occurs when the Topshelf service is started as a service, not when it is started  from VS or command line.

The setup:
```C#
  ILogger configuration = new LoggerConfiguration()
            .WriteTo.ColoredConsole()
                .WriteTo.RollingFile(@"C:\\Temp\\Log-{Date}.txt")
                .CreateLogger();
```
and within the HostFactory.Run method:
```C#
  x.UseSerilog(configuration);
```

In the lower service control I query for the logging by asking the HostLogger for one, where SettingsTracker is the class that extends the ServiceControl:
```C#
private static readonly LogWriter _log = HostLogger.Get<SettingsTracker>();
```
Tried a couple of integrations and have only been able to get two different error messages towards the SelfLog.Out
```
2015-03-04T13:36:31 Rolling file target C:\Temp\Log-20150304.txt was locked, attempting to open next in sequence (attempt 1)
2015-03-04T14:00:10 Caught exception System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The rolling file has been disposed.'.
   at Serilog.Sinks.RollingFile.RollingFileSink.Emit(LogEvent logEvent) in c:\projects\serilog\src\Serilog.FullNetFx\Sinks\RollingFile\RollingFileSink.cs:line 88
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent) in c:\projects\serilog\src\Serilog\Core\Sinks\SafeAggregateSink.cs:line 38 while emitting to sink Serilog.Sinks.RollingFile.RollingFileSink.
```

This gist is one of the examples (the last error message).
https://gist.github.com/janpieterz/33ae2312350fe5605e97

**Comment by nblumhardt** [comment]
Hi - thanks for the note. This sometimes occurs when a service reports itself as "stopped" before all threads in it have terminated; the service can end up restarted while the old process is still running. Do you observe this the first time the service is run after a fresh reboot?

**Comment by janpieterz** [comment]
Sorry for the massive delay on this one, I'm in a job change and everything is a little bit hectic. Hope to try your suggestion ASAP!

**Comment by nblumhardt** [comment]
Hi Jan,

Looking at your gist, I think the issue might be:

```csharp
StreamWriter writer =
                new StreamWriter(File.Open(@"c:\temp\seriself.txt", FileMode.Append, FileAccess.Write,
                    FileShare.ReadWrite));
```

and then:

```csharp
            Task.Factory.StartNew(() =>
            {
                while (true)
                {
                    writer.Flush();
                    Thread.Sleep(1000);
                }
            });
```

I don't think the `StreamWriter` will be thread-safe unless you wrap it with `TextWriter.Synchronized()`.

Did you have `SelfLog` set up this way when the issue originally appeared? A thread safety issue in the file stream used by `SelfLog` could definitely cause the kind of problem you're seeing.

**Comment by janpieterz** [comment]
I didn't have `SelfLog` setup at first but I can't seem to replicate this on my current machine using exactly the same code. I think what I had in the beginning was a couple of tasks just writing log statements randomly, which works fine when you're debugging but when you're running it as a service you run into the same problem you indicate with the `StreamWriter` and before, where threads are still running.

That said, it never hits my own log statements (the one in the `ExampleControl`), while they are begin hit when I run them from my VS. This might be more of a Topshelf issue.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @janpieterz - if you encounter this again (or we have other reports that sound similar) we'll reopen this, but probably a good point to close it now. Cheers!
