### ISSUE TITLE
Core `<appSettings>` support

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#402]
[Serilog.Extras.AppSettings](http://www.nuget.org/packages/serilog.extras.appsettings) has done very well as a simple XML configuration mechanism. For apps targeting one of the .NET platforms with _Web.config_ or _App.config_ (`System.Configuration`) support there's little reason not to use this approach.

The package came in as an "extra" because in Serilog 1.0 the role of configuration was still unclear, and the allowable trade-offs not really in focus. For example, was it desirable to have a configuration model that mixed code-provided parameters with ones set in config files, or was either/or acceptable?

Some experience with _Serilog.Extras.AppSettings_ has cleared up some of these questions, and it's reasonable to move forward in the direction it has set.

In the intervening years however, ASP.NET has announced the new "vNext"/5.0 version with a new [Configuration subsystem](https://github.com/aspnet/Configuration) that Serilog will also need to support.

This ticket outlines how we can get from where we are today, to a simple-but-consistent approach to configuration that Serilog can be prescriptive about.

Sub-tasks:

 - [x] 1. Define a `LoggerConfiguration` extension point for reading external configuration
 - [x] 2. Refactor the implementation of `PrefixedAppSettingsReader` so that the process of adding assemblies, discovering extension methods, and calling them, are shared (the shared part will live in _Serilog_)
 - [x] 3. Implement the extension point by migrating the code from _Serilog.Extras.AppSettings_ into _Serilog.FullNetFx_
 - [x] 4. Remove _Serilog.Extras.AppSettings_ from the main solution, and publish an empty package in its place
 - [ ] ~~5. Determine what, if any, internal changes need to be made in order to support JSON values in app settings (see #401)~~

The issue is marked "breaking/v2" because some incompatible core changes may be considered, but ideally we'd do this in a compatible way so that the changes can ship as Serilog 1.5.

The issue's marked "up-for-grabs" as it's approachable by anyone with good Serilog knowledge, but it's a SIZABLE chunk of work so please add a note here before kicking it off :-)

## 1. `LoggerConfiguration` support

One of the nice features of Serilog's configuration is its regularity. App setting support currently looks like:

```csharp
var log = new LoggerConfiguration()
  .ReadAppSettings()
  .WriteTo.Xyz()
  .CreateLogger();
```

The `ReadAppSettings()` call isn't consistent with the majority of configuration syntax and leaves the door open for inconsistencies as additional configuration sources are added.

Alternative:

```csharp
var log = new LoggerConfiguration()
  .ReadFrom.AppSettings()
```

Using a dotted syntax makes it easier to find options (type `ReadFrom.` to see supported configuration sources) and sticks with the successful `Verb.Noun()` naming style that seems to have worked well for `WriteTo`.

The semantics (immediate invocation of the configuration source against the builder) should stay the same as in the current package.

## 2. `PrefixedAppSettingsReader` refactor

This type discovers configuration methods and maps named arguments onto them. It's likely all configuration mechanisms will do this; we should try to pull out the code from the block at:

https://github.com/serilog/serilog/blob/dev/src/Serilog.Extras.AppSettings/Extras/AppSettings/PrefixedAppSettingsReader.cs#L90

Into a reusable form.

## 5. JSON/complex values in settings

There's a discussion in #401 about this. There are a couple of ways of approaching support for complex types, e.g. via a direct approach like the one mentioned in the linked issue:

> 1. If the parameter (in the extension method) is of a known simple type (e.g. `string`, `int`, `DateTime`, ... perhaps `Uri`) then assume the `value='...'` attribute contents are literal values as we do today
> 2. Otherwise, assume the `value='...'` contents are JSON, and attempt to deserialize an instance of the parameter type from it

> The JSON (de-)serializer would share formatting logic for known simple types like `DateTime` so that the syntax is consistent with (1).

This has the advantage of consistency, but might not be universal enough to include in the core. An alternative might be to provide a plug-in point to the `AppSettings` method that can handle deserialization of unknown types:

```csharp
interface IAppSettingsValueReader
{
  bool TryRead(Type settingType, string appSettingValue, out object setting);
}
```

And:

```csharp
var log = new LoggerConfiguration()
  .ReadFrom.AppSettings(readers: new[] { new JsonValueReader() })
```

Or embedded in the XML itself, per setting:

```xml
<add key='serilog:write-to:Email.credentials' value='{"Username":...}' />
<add key='serilog:write-to:Email.credentials:reader' value='SomeNamespace.JsonValueReader, ...' />
```

It's a bit clunkier than baking something in, but does provide good flexibility and keeps us out of the business of defining yet-another-JSON-parser.

(@mivano and @Mpdreamz  may have some comments, since they've discussed this in context of the ES sink.)

**Comment by nblumhardt** [comment]
I've made a start on this one in the PR linked above. Most of the machinery is there, but it's not quite ready.

The complex type conversion support in (5) looks like over-reaching if this is going to come in at sufficient quality, so I'd like to drop that off of this issue and consider it separately when/if it becomes desirable.

I've also side-stepped giving ASP.NET 5 much consideration by making the external configuration mechanism very, very general.

Here's the new TODO list:

 - [ ] Add more tests (the original _Extras_ package was very, very light on this :-))
 - [ ] Validate configuration strongly - duplicate keys, unrecognised directives, unmatchable sink names/arguments
 - [ ] Update the wiki
 - [ ] Add XML configuration examples to the documentation for the built-in sinks

**Comment by merbla** [comment]
@nblumhardt happy to have a crack at this one

**Comment by nblumhardt** [comment]
@merbla https://github.com/serilog/serilog/pull/422 is on my personal fork; how about I push up the last of the quick changes I have to make and we merge to dev so we can share more of the remainder?

**Comment by nblumhardt** [comment]
I've had a change of heart RE stronger config validation; since config is generally injected at deployment or even run-time I think being more tolerant here is probably best. Scratching some of the items above.

The tests are probably as good as they'll get; the _SmokeTest_ project is now re-purposed as a test for app settings support.

**Comment by nblumhardt** [comment]
@merbla I might spend a few (bus-ride) minutes on the AppSettings wiki page; do you want to split the task of adding examples (or think it's even a worthwhile idea?) Cheers!

**Comment by merbla** [comment]
@nblumhardt we need some examples (I have never used the feature).  Happy to do some.  I guess https://github.com/serilog/serilog/wiki/AppSettings is the place for those as well??

**Comment by nblumhardt** [comment]
I was thinking something more like the tiny snippet in: https://github.com/serilog/serilog-sinks-literate - i.e. per-sink. We could attack it incrementally.

I'd love to get the PR merged and 1.5 out this eve - any chance of a very quick look over that PR? :-)

**Comment by merbla** [comment]
@nblumhardt having a look now

**Comment by nblumhardt** [comment]
Thanks!!

**Comment by JuanjoFuchs** [comment]
> # 5. JSON/complex values in settings

@nblumhardt Was this ever implemented? I can't find an open issue for this one and I find myself in a need to read ```SplunkViaHttp``` configuration from AppSettings

**Comment by merbla** [comment]
@JuanjoFuchs not sure this has been tested with `SplunkViaHttp`.
