### ISSUE TITLE
MongoDB sink writes both timestamps as UTC

### ISSUE THREAD

**Issue by yallie** [serilog/serilog#405]
Both timestamps in UTC format make no sense to me.
UtcTimestamp should be UTC time and Timestamp should be local time.
Looks like a bug in MongoDBJsonFormatter.cs.

I already fixed it for myself and I'll submit a PR when my previous PR is merged:
https://github.com/serilog/serilog-sinks-mongodb/pull/2

**Comment by yallie** [comment]
Sorry, my bad, it's not an issue. Looks like I've missed an attribute on my DTO class.

**Comment by nblumhardt** [comment]
Thanks for the note all the same!

**Comment by pthalacker** [comment]
I downloaded the MongoDB sink last week and my Timestamp is in UTC time.  Can you outline what changes I need to make to have it write local time?

**Comment by yallie** [comment]
I don't know what date format is used by MongoDB sink internally and I'm not sure if there's an option to tweak it. My issue was related to mapping — log entries read from MongoDB had all timestamps as UTC until I added a BsonDateTimeOptions attribute as follows:

```csharp
public class LogEntry
{
    [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
    public DateTime Timestamp { get; set; }
}
```

**Comment by pthalacker** [comment]
Ah, I see.  Thank you.  That should mean I can write the C# Driver queries as local time.
