### ISSUE TITLE
email sink won't write to smtp addres but will write to SpecifiedPickup

### ISSUE THREAD

**Issue by stevenfirstrowinc** [serilog/serilog#407]
Hi 

I'm having a strange problem with the email sink.  When I have my web.config set to write to SpecifiedPickupDirectory I get emails in the pickup directory.  However when I change the config to point to my mail server nothing ever comes.

my config file config
````
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory" from="server@codysoft.net">
        <specifiedPickupDirectory pickupDirectoryLocation="C:\temp\emails" />
        <network host="server" userName="test@test.com" password="xxx" port="25"/>
      </smtp>
    </mailSettings>
  </system.net>
````

My email configuration code

            _configuration.WriteTo.Email(new EmailConnectionInfo
            {
                EmailSubject = string.Format("Error in {0}", _applicationName),
                FromEmail = "from@email.com",
                ToEmail = "to@email.com",
            }, restrictedToMinimumLevel: LogEventLevel.Warning, outputTemplate: OUTPUT_TEMPLATE);

I know my config file is set correctly because I have tests that send email.  It's just the log that isn't working.  Any ideas?  I'm using 1.4.168

**Comment by nblumhardt** [comment]
Hi Steven,

Do you get any results if you pass the credentials in to the sink directly? I believe `EmailConnectionInfo` supports server, host, port, username and so-on.

Cheers!

**Comment by stevenfirstrowinc** [comment]
I check this and it only works if I also set the credentials via code.  I don't know about anyone else but I think this should use the config file settings if no values are provided.  I know I could read from the config file myself but that doesn't seem right to me.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @stevenfirstrowinc 

I am not sure how implementing this one would go - it'd be a nice feature to add. I'll close this for now but if you have a chance to investigate and/or send a PR please feel free to reopen it.

Cheers!

**Comment by stevenfirstrowinc** [comment]
I made a PR.  If you review and have comments I'll alter as you see fit.  Regardless of whether you accept it I did get everything to work on my end but it means user/pwd info is embedded in code and I don't like that.
