### ISSUE TITLE
Move the projects in serilog-samples into sink repositories

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#410]
The serilog/serilog-samples repository contains example projects using each sink.

Now that each sink has its own repository, splitting this project and moving each sample to the corresponding sink repository will make each more discoverable, useful and easy to maintain.

Via #344.

**Comment by merbla** [comment]
Splunk sink done.

**Comment by merbla** [comment]
List of remaining sinks to port.

Sink | Last Touched
------|--------
Demo | a year ago
ElasticSearchSample | a year ago
ElmahIOSample | a year ago
Harness | a year ago
LogentriesSample | a year ago
LogglySample | a year ago
LoggrSample	| a year ago
MSSQLSample	| a year ago
RaygunSample | a year ago
TimingSample | a year ago
WebHarness |a year ago

**Comment by mivano** [comment]
TimingSample has been recreated in the SerilogMetrics repository. So it can be removed. The samples for Loggly, loggr, mssql, raygun are not very interesting samples; they just show you how to configure the sinks, nothing specifics. Might not be worthwhile to keep combined with the documentation we have.

**Comment by merbla** [comment]
Thanks @mivano, I might spend more time on enhancing the doco (as opposed to these examples)  

Thoughts @serilog/core

**Comment by nblumhardt** [comment]
+1, if any sinks end up needing specific samples they'll no doubt be added anyway.

**Comment by merbla** [comment]
So do we torch the remaining samples??

**Comment by nblumhardt** [comment]
Sounds good to me.

**Comment by merbla** [comment]
Last chance... Say goodbye to https://github.com/serilog/serilog-samples

**Comment by nblumhardt** [comment]
Ciao! :-)
