### ISSUE TITLE
Make the Provided Sinks wiki page an index into sink repos

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#411]
Now that each sink lives in its own repository, it'd be great for the README.md file in each of those to contain the kind of usage information now found in https://github.com/serilog/serilog/wiki/Provided-Sinks

Let's move each snippet to the corresponding README.md, and convert the Provided Sinks page into a large table with a row for each sink, linking to that sink's repository.

**Comment by mivano** [comment]
I updated the page containing the sinks with a table listing all the sinks I know of. Please see if this is what you had in mind. I noticed already some are missing from the alphabetical list. We might need to clean the rest and only leave the default sinks (file, rolling file etc) on that page and refer to the sinks for more details?

**Comment by nblumhardt** [comment]
Hi Michiel, thanks for jumping in!

I'm having second thoughts about the table-based layout, it's very loooooong at least on my display, and I think the homepages of the sinks themselves are probably the right place for descriptions, ownership info and so-on. I might have a shot at an alternative that lays things out as a simple bullet-point list and see if that is a bit more compact.

**Comment by mivano** [comment]
I did not know there were so many of them :-). I agree that the table is pretty long and indeed people can quickly follow the link to the sink page itself and see the details. So much better like this now!
Did not know the trick of mentioning a team, thanks.

**Comment by nblumhardt** [comment]
I'm surprised too! Now that they're broken out I can't believe we made it so far with everything jammed into the one repository :-S ... We live and learn ;-)
