### ISSUE TITLE
Create an index into Serilog "extras" and community resources

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#412]
On the wiki, let's create a new page that collects (possibly in table form) an index of Serilog community projects (like SerilogMetrics) and other resources. Aiming to give back some of the visibility lost in #344 (cc/ @mivano).

**Comment by mivano** [comment]
Created a page for this. https://github.com/serilog/serilog/wiki/Community-projects
You might have a better definition (and maybe a better overview of the projects).

**Comment by nblumhardt** [comment]
Great - looks good to me. May add a bit of content and see what comes out :)
