### ISSUE TITLE
Move destructuring packages to Destructurama!

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#414]
Three remaining Serilog "extras" packages:

 * Serilog.Extras.Attributed
 * Serilog.Extras.DestructureByIgnoring
 * Serilog.Extras.FSharp

...all provide custom destructuring capabilities. We also have some PRs with these capabilities included.

Rather than bloating Serilog or dilute the project with many "extras" repositories (see #344), these can move to their own top-level project, where they'll get more attention.

https://github.com/destructurama

Each of the current packages will move to a new repository under that org.

**Comment by nblumhardt** [comment]
PS... Looking for co-founders! cc @serilog/community @serilog/core :-)

**Comment by merbla** [comment]
@nblumhardt love the name! Don't know much about the content. But hey, add me to the list. :grimacing:

**Comment by nblumhardt** [comment]
You can count on me for weird names :-)

Now, to name the new web instrumentation project............ :beer:

**Comment by IanYates** [comment]
Futurama fan? :D  So, just to clarify the plans, extras are separate from destructuring extensions/customisations?  Sinks are a separate beast again.  Is that all three types of "extensions" or "non-core" project types covered?

**Comment by nblumhardt** [comment]
Hi @IanYates - something of a fan :-) ... I think the "*rama" fits the expectations of this project pretty well; all kinds of destructuring goodness without a lot else making the sub-projects cohesive. Could still get interesting!

I am not sure we'll get all project types covered by these few new ones - the new layout comes mostly from the realisation that the current "extras" are pretty tightly clumped. After the web projects come out, and the XML AppSettings support is moved in (#402) the goal is to have nothing but the core remaining. As others come up we may need to find more creative "homes" :)

**Comment by nblumhardt** [comment]
This is all done in `dev` and the packages redirected. I'll complete the merge to master shortly.
