### ISSUE TITLE
NuGet Repository Dependency cannot be found

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog/serilog#415]
I'm been away from serilog for a couple of weeks so only just caught up with the latest re-structuring. It appears that the new sink packages need Serilog > 1.5 but I can only 'see' 1.4.204 in NuGet so you can't install them.

I've checked include pre-release but not there either.

Have I missed a step ?

**Comment by nblumhardt** [comment]
Thanks for the heads up @johnkattenhorn !

In my final rampage to get the repository split finished last week I missed a number of `$version$` tags in sink NUSPECs. There isn't yet a Serilog 1.5, they should all be targeting 1.4. Will take a look now.

**Comment by merbla** [comment]
@nblumhardt you good with this one?

**Comment by nblumhardt** [comment]
Should be sorted now. Thanks again!

**Comment by johnkattenhorn** [comment]
My pleasure, BTW - Still the best contextual logging solution for .NET by a very long way :-)
