### ISSUE TITLE
Create datadog sink

### ISSUE THREAD

**Issue by stefansedich** [serilog/serilog#420]
I have created an initial Sink to push log events up to the [Datadog](http://www.datadoghq.com/) event stream, this is located over on my github here: https://github.com/stefansedich/serilog-sinks-datadog

Would be nice to include this a part of the main repo/build/nuget feeds.

**Comment by nblumhardt** [comment]
Looks fantastic, thanks Stefan!

We're aiming with new sink contributions to set up the contributor with admin rights to the repo, smoothing out the onboarding process and spreading out some of the longer-term maintenance. Does this sound good to you?

Also not 100% sure how to transfer the repo in, might need to coordinate via Skype or mail... Cheers!

**Comment by stefansedich** [comment]
Yeah that sounds good to me. Lets skype tomorrow and sort it out.

Cheers

**Comment by nblumhardt** [comment]
Done - https://github.com/serilog/serilog-sinks-datadog - let me know when I can set up the build/publishing, I have it down to a fine art :-)

**Comment by merbla** [comment]
@stefansedich package is up on NuGet, you happy for this one to be closed?

**Comment by nblumhardt** [comment]
My bad, I should have closed this one. Cheers!
