### ISSUE TITLE
"Literate" console sink RFC

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#421]
At: https://github.com/nblumhardt/serilog-sinks-literate

This is an alternative colored console sink that uses a [literate programming](http://en.wikipedia.org/wiki/Literate_programming)-inspired presentation to showcase the structure/type of the logged data, in contrast to the existing `ColoredConsole` sink that uses color predominantly to emphasise level:

![untitledfdsasf](https://cloud.githubusercontent.com/assets/342712/7040536/ce90314c-de13-11e4-9e1f-3f8342828c81.png)

Rougly, strings are cyan, Booleans and `null` are blue, numbers magenta, and everything else a striking bright green. It deviates a bit from the typical presentation by omitting quotation around strings in simple messages since the notion of type this is intended to convey is redundant because of the coloring.

I've deliberately avoided using background colors, which tend to cause presentation issues for long-running apps because of some kind of whacky console bug. The colors are also very bright because this is necessary to stand out when displayed in a PowerShell default blue window.

I think there's room for improvement, but for some use cases I also think it might be pretty pleasant/usable as-is now. I'd like to drop it in as an option but could be convinced otherwise if the @serilog/core think otherwise :-)

Usage is simple:

```csharp
    .WriteTo.LiterateConsole()
```

Thoughts/comments/suggestions/PRs?

**Comment by khellang** [comment]
I :heart: IT! I CAN HAZ?

**Comment by merbla** [comment]
Love it!

**Comment by nblumhardt** [comment]
HAZ! https://github.com/serilog/serilog-sinks-literate :) Cheers!

**Comment by khellang** [comment]
Already running it! :grin:

![2015-04-08_13-16-53](https://cloud.githubusercontent.com/assets/582487/7044296/24f654a2-ddf2-11e4-8679-960f5bcdc0fe.png)

**Comment by khellang** [comment]
BTW, the TopShelf logging looks a bit off. Seems like everything is treated as a parameter?

**Comment by nblumhardt** [comment]
Hmmm, that's annoying :-( ... there's a `finally { Console.ResetColor(); }` in the sink that should take care of this:

https://github.com/serilog/serilog-sinks-literate/blob/master/src/Serilog.Sinks.Literate/Sinks/Literate/LiterateConsoleSink.cs#L117

Any ideas?

**Comment by nblumhardt** [comment]
Though... it's possibly just interleaved output. You should look at: https://github.com/Topshelf/Topshelf/tree/develop/src/Topshelf.Serilog/Logging - not on NuGet yet, but will funnel all that TopShelf output through Serilog properly :-) // cc @mookid8000

**Comment by mookid8000** [comment]
:+1: :grin:
