### ISSUE TITLE
Support (limited) key-value config in the Elasticsearch sink

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#425]
> https://groups.google.com/forum/#!topic/serilog/j6vLpH509LE

ES sink 2.0 doesn't play well with key-value pair settings. It's not realistic that all options (e.g. the `Func<>`s) supported by the sink will map well onto config, but a subset (e.g. the server URL) would work nicely.

```xml
<add key="serilog:using" value="Serilog.Sinks.Elasticsearch" />
<add key="serilog:write-to:Elasticsearch.serverAddress" value="http://localhost:9200" />
```

This could be supported pretty trivially with an additional overload of `WriteTo.Elasticsearch()`.

(The alternative here of extending the configuration system to support arbitrary serialized objects seems like a non-starter since it would inevitably impinge on the simplicity goals, and isn't used by the majority of sinks. This might also be of interest to @serilog/owners-datadog.)

Thoughts? @serilog/owners-elasticsearch

**Comment by matthewrwilton** [comment]
If Nick's suggestion is the way to go forward I'd be happy to work on it and submit a pull request.

Thoughts on just adding an overload that takes a string for the URI?
```
    public static LoggerConfiguration Elasticsearch(
        this LoggerSinkConfiguration loggerSinkConfiguration,
        string uri,
        ElasticsearchSinkOptions options = null)
```

**Comment by mivano** [comment]
I do not think it would hurt to have a simple overload that takes the uri, the index format and if we want auto template registration. Things we can easily pass in via the appSettings and give a default value. 
Another option would be supporting some sort of JSON serialization, but you are still limited to a specific set of options. 

Shall we start with a simple overload? Would already help most users I would think.

**Comment by Mpdreamz** [comment]
Overload right now simplest option :+1: 

Leaving this brainfart here to see if sticks :)

Another option is serilog finding a method on LoggerSinkConfiguration overload named whatever `write-to` mentions that a single parameter who's type implements `ISinkOptions` 

e.g [ElasticsearchSinkOptions](https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs#L29)

```
public class ElasticsearchSinkOptions : ISinkOptions
{
        public bool AutoRegisterTemplate { get; set; }

        public string TemplateName { get; set; }

        public Uri ServerAddress { get; set; }
}
```

```
<add key="serilog:write-to:Elasticsearch.serverAddress" value="http://localhost:9200" />
<add key="serilog:write-to:Elasticsearch.autoRegisterTemplate" value="true" />
```

try to new an instance of that class and setting its properties, in addition to trying to find a method taking `serverAdress` and `autoRegisterTemplate` as named methods.

**Comment by nblumhardt** [comment]
@Mpdreamz definitely a reasonable approach, I don't think the scenario justifies adding more complexity to the configuration story right now vs. the option of an overload (which the other sinks mostly use) though.

There are definitely some versioning (binary compat) advantages to object-based parameterisation, but heading in that direction would need to be handled in a consistent way across the rest of the Serilog sink configuration APIs to keep things sane. For now just getting the ES one in line with the rest seems like the right move :-)

**Comment by Mpdreamz** [comment]
oh for sure :+1: on adding that overload for now.

But the method overloads is the only fully supported option now which is why all the sinks use it, it'd be nice to see more sinks using option objects instead of overloads with named optional parameters. 

The old ES sink became quite a mindfuck with all the overloads supporting the different scenarios.

**Comment by nblumhardt** [comment]
Absolutely :-) ... looking forward to figuring out a better story there in the future.

**Comment by matthewrwilton** [comment]
I just setup a test to reproduce the issue and it actually works with Serilog versions 1.5.5 and 1.5.6. The only config settings I have are
```
<add key="serilog:using" value="Serilog.Sinks.Elasticsearch" />
<add key="serilog:write-to:Elasticsearch.serverAddress" value="http://localhost:9200" />
```
I haven't looked what changed to make it work yet, but it seems like this issue has been resolved by other changes.

**Comment by nblumhardt** [comment]
Thanks @matthewrwilton - I have a feeling though in this case it only appears to work because your server address is the same as the default  that will be used when none is configured.

**Comment by matthewrwilton** [comment]
@nblumhardt You're right, my bad sorry. I was away from home and setup another environment to reproduce and didn't realise the difference. Back home now and have submitted a pull request that adds an overload.
