### ISSUE TITLE
Exception mapping in the Elasticsearch sink (Kibana related issue)

### ISSUE THREAD

**Issue by guillaume86** [serilog/serilog#426]
I'm new to serilog and elasticsearch/kibana so it's very possible I'm doing something wrong but here's my issue: 

When I'm logging exceptions, the exceptions field is not deserialized into several specific fields in elasticsearch. The documents just have a big json blob in the `exceptions` field and no `exceptions.*` fields. I use the last stable versions of Serilog (1.5.1) / ElasticSearch.Sink(2.0.27) / Elasticsearch(1.5.1) / Kibana(4.0.2).

Is it a bug or a configuration issue on my side? 

Thanks in advance

**Comment by mivano** [comment]
Are you sure that is not just the representation of it in Kibana? if you load the raw data, it should contain an exception field which is an array of exceptions, each having a depth. If this is not the case, then make sure you have a mapping installed. You can do so by specifying this in the config of the sink.

**Comment by guillaume86** [comment]
You're right it seems to be a Kibana issue (big bummer for me, makes it useless with serilog):
https://github.com/elastic/kibana/issues/998

I could try to change the serialization format but I don't see how to do innerExceptions properly without arrays.

**Comment by mivano** [comment]
You can still report over the data, but yes, the visualization of that data is not that clear in Kibana. Other alternatives are nested objects etc, but they also have their limitations.

**Comment by guillaume86** [comment]
Thanks I'll put the exception data in fields while waiting for a fix in Kibana, better than nothing :).
