### ISSUE TITLE
email nuget package version issue

### ISSUE THREAD

**Issue by stevenfirstrowinc** [serilog/serilog#429]
The nuget package for Serilog.Sinks.Email is showing an update for version 1.5.13 even though I have 1.5.5 installed.  I'm not sure how/why this is happening but can you confirm the actual correct version number?

**Comment by merbla** [comment]
Hi @stevenfirstrowinc the listing on [NuGet](https://www.nuget.org/packages/Serilog.Sinks.Email/) shows the following:

Serilog.Sinks.Email 1.5.13  - Friday, April 03 2015
Serilog.Sinks.Email 1.5.11	- Thursday, April 02 2015
Serilog.Sinks.Email 1.5.10	- Wednesday, April 01 2015
Serilog.Sinks.Email 1.5.9	- Thursday, March 26 2015
Serilog.Sinks.Email 1.5.8	- Thursday, March 26 2015
Serilog.Sinks.Email 1.5.5	- Thursday, March 19 2015

`1.5.13` is the latest

**Comment by stevenfirstrowinc** [comment]
ugh, would help if I could count!  Sorry about that

**Comment by merbla** [comment]
No problem, let us know if you have any more issues
