### ISSUE TITLE
Amazon Kinesis Sink

### ISSUE THREAD

**Issue by superlogical** [serilog/serilog#431]
HI all,

I've just finished off writing a serilog to Amazon Kinesis sink, which is based on the Seq sink and the Elastic Search sink. Kinesis is HTTP based so I copied the way those sinks use a durable mode that buffers logs to disk then ships them to Kinesis.

I would like to contribute this code to the serilog project and have it live under the serilog github organisation. If everyone is happy with it I'd like to get it published to NuGet. 

I've included both net40 and net45 versions of the solutions, and I've tested that the Build.ps powershell script works. I haven't tried it on Appveyor yet.

https://github.com/superlogical/serilog-sinks-amazonkinesis

I've also built a RethinkDB sink, and I'd be keen to move that too if anyone thinks it would be useful.
https://github.com/superlogical/serilog-sinks-rethinkdb

Cheers
Jake

**Comment by merbla** [comment]
Hey @superlogical sounds great.  We have ported a few external sinks recently but I will have to check with @nblumhardt if we transfer ownership or just clone the old repo.  Then we can setup AppVeyor/NuGet etc.

Also we will setup you as an admin on the repo so you can manage anything that pops up.

**Comment by superlogical** [comment]
Cool, might be the first Nuget package I've ever published :beers:

**Comment by nblumhardt** [comment]
Awesome, thanks Jake! @merbla I think this'd be a great addition, as would the RethinkDB sink (but let's do that under a separate ticket).

Couple of minor notes:

https://github.com/superlogical/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.AmazonKinesis/Serilog.Sinks.AmazonKinesis.nuspec#L5

Probably doesn't need the `-pre` version suffix. Also, authors shouldn't include Continuous IT (just a copy/paste error I think).

Do the package dependencies also need to be in that NUSPEC? (AWSSDK and so on?)

Perhaps not urgent, but providing an overload of `WriteTo.AmazonKinesis()` that uses an argument list rather than an object would let the sink be configured using <appSettings>.

So long as the GitHub repo's history is clean/minimal, transferring it to `serilog` using Settings > Transfer Ownership is fine.

HTH!

**Comment by superlogical** [comment]
I'm just making these changes now, will update my repo soon

**Comment by superlogical** [comment]
@nblumhardt I've added that overload... hopefully this is what you meant

https://github.com/superlogical/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.AmazonKinesis/KinesisLoggerConfigurationExtensions.cs#L72

I've added the dependencies to the nuspec
https://github.com/superlogical/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.AmazonKinesis/Serilog.Sinks.AmazonKinesis.nuspec#L14

Removed the `-pre` version suffix and the Continuous IT

**Comment by merbla** [comment]
sorry @superlogical also update the [dependency](https://github.com/superlogical/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.AmazonKinesis/Serilog.Sinks.AmazonKinesis.nuspec#L14) to `1.5` for serilog 

Let me know when you transfer the repo

**Comment by superlogical** [comment]
@merbla  Like this?

````xml
<dependency id="Serilog" version="1.5.1" />
````

**Comment by superlogical** [comment]
@merbla Also should I transfer ownership to you or @nblumhardt ?

**Comment by superlogical** [comment]
I think I need admin rights on the serilog org to transfer ownership?

**Comment by nblumhardt** [comment]
IIRC you should be able to "request" transfer to `serilog` - no option to do that?

**Comment by superlogical** [comment]
I've just transferred it to you now.

**Comment by nblumhardt** [comment]
Moved! https://github.com/serilog/serilog-sinks-amazonkinesis - and created @serilog/owners-amazon-kinesis.

**Comment by superlogical** [comment]
Cool thanks!!

**Comment by superlogical** [comment]
Would be cool if someone could help me with setting up Appveyor so that I can publish this package to Nuget. 

https://github.com/serilog/serilog-sinks-amazonkinesis/issues/1

Cheers!

**Comment by merbla** [comment]
@superlogical  this look done, correct?

**Comment by superlogical** [comment]
Yeah, do you want me to move the sample app to serilog-samples?

**Comment by merbla** [comment]
All good, the samples now live with the sink.  Great work
