### ISSUE TITLE
ReThinkDB Sink

### ISSUE THREAD

**Issue by merbla** [serilog/serilog#432]
Related to #431 

Create/port existing from [https://github.com/superlogical/serilog-sinks-rethinkdb](https://github.com/superlogical/serilog-sinks-rethinkdb)

**Comment by merbla** [comment]
@superlogical this is a rinse and repeat of the kinesis sink.  When you port the ownership let me know.

**Comment by superlogical** [comment]
Hi Matthew, I've just transferred this repo to the serilog org.

**Comment by merbla** [comment]
@superlogical ownership/admin should be sorted and I have added the build.  Waiting to see the results :smile:

**Comment by superlogical** [comment]
Cool thanks! I see the build is broken I can fix it up in the morning :)

**Comment by merbla** [comment]
NP, let me know if I can help with anything else

**Comment by superlogical** [comment]
@merbla Got the build fixed, and also set the package to not be pre-release.. hope that's okay :)

It's setting package name as `Serilog.Sinks.RethinkDB.0.0.0.nupkg` when it should be `Serilog.Sinks.RethinkDB.1.0.0.nupkg`

See the history
https://ci.appveyor.com/project/serilog/serilog-sinks-rethinkdb/build/3

**Comment by merbla** [comment]
@superlogical did you want it packaging from the `nuspec` or the `.csproj`?

**Comment by merbla** [comment]
@superlogical some NuGet issues with DNS/AppVeyor tonight, will try in the morning

**Comment by merbla** [comment]
@superlogical can you checkout the [package](https://www.nuget.org/packages/Serilog.Sinks.RethinkDB/) and if all good we can close this one off.

**Comment by superlogical** [comment]
LGTM Thanks!
