### ISSUE TITLE
AppVeyor publishing for Amazon Kinesis sink

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#435]
Moved from https://github.com/serilog/serilog-sinks-amazonkinesis/issues/1

All of the serilog/ repositories are published as `serilog` to NuGet from our AppVeyor account.

To get this set up we need to:

- [ ] Add `serilog` as an owner to http://www.nuget.org/packages/serilog.sinks.amazonkinesis
- [ ] Turn off the standalone CI build
- [ ] Add the build to the Serilog CI server

@superlogical if you can cover 1 & 2, I can do 3 in a jiffy.

Cheers,
Nick

**Comment by superlogical** [comment]
- [x] I've added `serilog` as an owner https://www.nuget.org/packages/serilog.sinks.amazonkinesis
- [x] I've turned off the standalone CI build. 
- [x] I've removed the build badge from the README, 
- [ ] Update the README to add the badge once you have setup the serilog CI server.

@nblumhardt Could you do number 4

Cheers
Jake

**Comment by nblumhardt** [comment]
Done! Waiting to see it succeed, but optimistic ;)

**Comment by superlogical** [comment]
Hey @nblumhardt It's publishing a lower version number (1.0.18) than what I published (1.5.15)

**Comment by superlogical** [comment]
Actually don't worry, I unlisted the wrong versions :)
