### ISSUE TITLE
serilog.sinks.email .net 4.0 support

### ISSUE THREAD

**Issue by wshirey** [serilog/serilog#437]
Please provide support for .NET 4.0 framework. Serilog supports it, as should first party sinks. Thanks!

**Comment by nblumhardt** [comment]
Thanks for the note, great to have your input. Supporting .NET 4 in sinks is currently "best effort" - we'd accept a PR for this I think but the build work is a bit too fiddly to easily implement.

If you are interested in taking a shot let me know, I can provide some pointers. Cheers!
