### ISSUE TITLE
Raygun sink doesn't send default environment variables

### ISSUE THREAD

**Issue by brianfeucht** [serilog/serilog#438]
By default Raygun's are sent with various environment values (e.g. OS Version, Available Memory, Processor Count), but Rayguns sent with the Serilog Sink only send machine name.  I suspect this is due to creating the new RaygunEnvironmentMessage object here https://github.com/serilog/serilog-sinks-raygun/blob/master/src/Serilog.Sinks.Raygun/Sinks/Raygun/RaygunSink.cs#L106

**Comment by nblumhardt** [comment]
Thanks for the heads-up. I am not sure who on the core team is using Raygun- open to PRs that fix this but may not be able to take it on directly. @mivano contributed the sink originally so may have some ideas. Cheers!

**Comment by mivano** [comment]
Well that is some time ago and I do not use Raygun at the moment. So best would be to do a PR indeed.
