### ISSUE TITLE
ExecptionLess Sink should pass SourceContext

### ISSUE THREAD

**Issue by merbla** [serilog/serilog#439]
Related to #381 

The [ExceptionLess Sink](https://github.com/serilog/serilog-sinks-exceptionless) should [log the calling class](https://github.com/serilog/serilog-sinks-exceptionless/blob/master/src/Serilog.Sinks.ExceptionLess/Sinks/ExceptionLess/ExceptionlessClientExtensions.cs)

Possibly via `SourceContext`.

**Comment by niemyjski** [comment]
@merbla @nblumhardt Could you please review my commit.. I had nothing to go off of other than [this](https://github.com/serilog/serilog/blob/1e1cc57ea7023b006916f95099717ff34ec50878/test/Serilog.Tests/Core/LoggerTests.cs#L36) and a quick peek at the source.

**Comment by niemyjski** [comment]
I also committed without testing it returns the source (I really need to spend some time and set up a sample that I can test...)

**Comment by nblumhardt** [comment]
LGTM; you might get some strange results if the `SourceContext` property is passed as something other than a scalar string, but in practice I doubt this'd ever appear.

https://github.com/serilog/serilog-generator would be a good place to start RE a test harness, it's designed for just this scenario :-) Cheers!
