### ISSUE TITLE
Question about filtering

### ISSUE THREAD

**Issue by imperugo** [serilog/serilog#443]
Hi, 
I'd like to remove from log a specific exception (basically a FW I'm using is logging an info as error so my log if full of useless information).

I'd like to filter by error message, so I was thinking to do something like that:

```csharp
.Filter.ByExcluding(Matching.WithProperty<string>("message", p => p == "message string"))
```

is it correct?
is "message" or "Message" the right name (or maybe is a sub property)? 

Thanks
.u

**Comment by nblumhardt** [comment]
Hi Ugo,

The argument to `ByExcluding()` is a predicate on `LogEvent`, so writing the filter as a lambda expression is probably easier in this case.

The simple way to do it is:

```csharp
    .Filter.ByExcluding(le => le.RenderMessage() == "message string")
```

This should be fine under most use cases. If you want to do something more efficient (avoid allocating the rendered message as a string, which many sinks also avoid) you can try working with the template directly:

```csharp
    .Filter.ByExcluding(le => {
        if (le.MessageTemplate.Tokens.Length != 1)
            return false;
       var t0 = le.MessageTemplate.Tokens[0] as TextToken;
       return t0 != null && t0.Text == "message string");
    })
```

The second version assumes the message doesn't contain any `{Holes}` - if it does you may need to modify the filter a bit.

Cheers!

**Comment by imperugo** [comment]
Hi @nblumhardt 
thanks so much for the response. I'll try the RenderMessage approach should be fine for my scenario.

.u
