### ISSUE TITLE
System.AppDomainUnloadedException when running multiple unit tests in different projects

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog#444]
Getting this exception when running all my unit tests, truncated to Serilog code.  Happens on a line like 
```C#
logger.PushProperty("name", value);
```
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
    at Serilog.Context.LogContext.Wrapper.get_Value()
   at Serilog.Context.LogContext.get_Enrichers() in c:\projects\serilog\src\Serilog.FullNetFx\Context\LogContext.cs: line 145
   at Serilog.Context.LogContext.GetOrCreateEnricherStack() in c:\projects\serilog\src\Serilog.FullNetFx\Context\LogContext.cs: line 126
   at Serilog.Context.LogContext.PushProperty(String name, Object value, Boolean destructureObjects) in c:\projects\serilog\src\Serilog.FullNetFx\Context\LogContext.cs: line 74

Anyone ever seen anything similar?

**Comment by jamesbascle** [comment]
I should also note:  I'm using MSTest. I'm also using the enable cross app domain calls option - MSTest PermitCrossAppDomainCalls just aborts the tests with an unshown error if I do not.

**Comment by nblumhardt** [comment]
Hi - thanks for the report! No, not a known issue; what happens in the secondary appdomain? Do you push properties onto the log context within it?

//cc @gertjvr @michaelnoonan

**Comment by jamesbascle** [comment]
The secondary app domain seems to be an already disposed of app domain for another Assembly's unit tests.  I decided to go with a "Singleton Logger" type pattern, with a facade for the common Serilog stuff.

So all logging statements look similar to how one might call Trace.Information or Trace.Error, except of course pushing properties onto the log context.

Those look like using(Logger.Current.ProvideContext("ContextKey","ContextValue")).  The tests in the disposed/unloaded app domain all pass, and exit their using blocks, so the log context should be empty.

**Comment by nblumhardt** [comment]
Closing since we haven't heard of any repros, but please feel free to post new information here.
