### ISSUE TITLE
Would like to have an option to not log RenderedMessage when logging in a structured sink like DocumentDB

### ISSUE THREAD

**Issue by ahmelsayed** [serilog/serilog#446]
I'm using Serilog to log analytics and diagnostics messages in DocumentDB. It's really great as I can log events then aggregate them and have complicated queries for figuring out usage pattern or diagnosing issues in production.

I would like however to not log the [`RenderedMessage`](https://github.com/serilog/serilog-sinks-azuredocumentdb/blob/ed1094a764e8915d2a39a1f2f40e728985c0670e/src/Serilog.Sinks.AzureDocumentDb/Sinks/AzureDocumentDb/AzureDocumentDbSink.cs#L71) because it's pretty large and kind of redundant in this scenario because DocumentDB already has all the `Properties` intact.

Also not log null values, like `Exception` which is always null except in Errors, but that might be a different issue.

**Comment by merbla** [comment]
Hi @ahmelsayed, this is quite similar to #424.

I nearly have a PR for #424 complete however still testing.  I do not have a deep understaning of the DocumentDB sink however a similar implementation may work.

In the initial stages the change would be sink specific, e.g. not in core.

**Comment by ahmelsayed** [comment]
Hi @merbla, thanks for your feedback it does sound very similar. Let me know when your PR is ready and I'll take a look at it and do something similar for DocumentDB

**Comment by merbla** [comment]
@ahmelsayed have a look at the [PR](https://github.com/serilog/serilog-sinks-splunk/pull/5) I am still testing but the basics are there.

**Comment by nblumhardt** [comment]
Ping @serilog/owners-azure-documentdb

**Comment by robdmoore** [comment]
Hi @ahmelsayed.

Cool to hear you are using the Document Db sink. How is that working for you? It's pretty rough around the edges - I threw it together in a couple of hours when Document Db was first announced.

**Comment by ahmelsayed** [comment]
Hi @robdmoore 

It's actually pretty cool, Thanks for putting it together :+1: 
I'm using it mainly as a diagnostics system, and it works quite well. I can very easily trace a user's activity through the app and figure out if they hit any issues or if I have any bug, it's pretty neat!

The main reason I'm raising this issue is because I was experimenting with using it for my own analytics as well, but the space seems to be growing very rapidly, and I was looking for ways to reduce the size of the documents I'm logging. Though I'm pretty sure at this point that I'll continue to use SQL for analytics and keep just the diagnostics logs in documentdb, where I can clear them regularly.

**Comment by nblumhardt** [comment]
Anyone interested in PRing this? I think for now it's an issue we're open to addressing but don't have time carved out for. I'll close it but as mentioned please feel free to submit the change if it's still something of interest. Cheers! :-)
