### ISSUE TITLE
Ship the Microsoft.Framework.Logging (DNX) provider for Serilog

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#447]
Follows on from a discussion at: https://github.com/aspnet/Logging/pull/182

We have a lot to do for Serilog to work seamlessly with the VS2015 tools, including a possible major version bump; I think the proposal here would initially just be to:

 - [x] Create a new project under `/serilog`
 - [x] Migrate in the code from the linked PR
 - [ ] Set up a VS2015 CI build for it

We can support both the "full" and "core" DNX targets with this package.

Naming - _Serilog.Framework.Logging_? //cc @serilog/core

**Comment by merbla** [comment]
Yep, seems reasonable.  What about the package? I know you mentioned a version bump. Still `Serilog` or `Serliog.Framework.Logging`?

**Comment by nblumhardt** [comment]
This would go in _Serilog.Framework.Logging_ and take a dependency on the current _Serilog_ package. Goal's to keep _Serilog_ dependency-free.

Post-VS2015 RTM, I think we'd keep the same split, but possibly bump _Serilog_ and use the new tools to build it. This'd imply leaving .NET 4.0 behind on the 1.x series, and changing the assembly layout, I think.

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-framework-logging (getting started, slowly)

**Comment by nblumhardt** [comment]
I've published a package by hand to NuGet so anyone interested can check it out:

https://www.nuget.org/packages/Serilog.Framework.Logging/1.0.0-beta-1

Some details on usage at in the [README](https://github.com/serilog/serilog-framework-logging).

CI is at https://ci.appveyor.com/project/serilog/serilog-framework-logging waiting to be configured (getting late here!)

**Comment by nblumhardt** [comment]
- [ ] Set the _Microsoft.Framework.Logging_ level from the Serilog level in `AddSerilog()`

**Comment by nblumhardt** [comment]
- [ ] Create a MyGet feed for `dev` branch package builds

**Comment by nblumhardt** [comment]
Now covered in the `v2` list.
