### ISSUE TITLE
Serilog not using all of our resources

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog#448]
"Serilog takes the view that, all things considered, logging is a lower priority than other application code and should never avoidably impact the operation of a running application", however, during batch processing we can potentially log thousands to hundreds of thousands of events in certain error cases.  On application termination in which the logger is disposed,  I would expect Serilog to use as many resources as possible to flush the event queue.

Is there a good way to force Serilog to consume as many resources as possible (cores, bandwidth), to push events as fast as possible?

If it helps, I'm using the Loggly sink with SyslogTcp format.

**Comment by jamesbascle** [comment]
This is actually possibly an issue with the Loggly sink.  I've found https://github.com/samirahmed/serlog.logglybulksink which allows upload @ 7000 messages a second from my production server, vs 20-30/second with the Loggly sink using SyslogTCP, and is configurable from code, which is great for me.  You can close this if you like, but I think the idea of allowing Serilog to  crank up it's resource usage has merit.

**Comment by nblumhardt** [comment]
Hey James - thanks for the heads-up. It'd be awesome to update our default Loggly sink to use batching, since the Serilog infrastructure it is using is batch-oriented anyway, and for this purpose explicitly. Closing now - but a PR would be very welcome in this direction if anyone decides to give it a shot. Cheers!
