### ISSUE TITLE
Support for Xamarin and iOS PCL in nuget package

### ISSUE THREAD

**Issue by ravensorb** [serilog/serilog#449]
Please consider adding support for more profiles -- specifically for Xamarin to the Nuget package that is released.

I think the issue is with the current nuspec file

MonoAndroid10+MonoTouch10

should be

MonoAndroid1+MonoTouch1

**Comment by nblumhardt** [comment]
Hi @ravensorb - thanks for the note. Which Xamarin targets are not compatible with Serilog today? (I.e. which project configurations?) Thanks!

**Comment by ravensorb** [comment]
I was not able to install it in any iOS project.  Once I updated the nuspec file and changed the “10” to “1” in the PCL profile – it matched a valid profile for iOS and the package installed without issue.

**Comment by merbla** [comment]
Hi @ravensorb, with the *Serilog* package, I can install and run in a new *Cross Platform Xamarin Forms* app.  The package was added to the PCL, iOS & Android projects.

My setup is
```
=== Xamarin Studio ===
Version 5.9.1 (build 3)
=== Apple Developer Tools ===
Xcode 6.3.1 (7703)
Build 6D1002
=== Xamarin.iOS ===
Version: 8.10.0.267 (Business Edition)
=== Xamarin.Android ===
Version: 5.1.1.0 (Business Edition)
````
Do you have any more info that might help?

**Comment by merbla** [comment]
Hi @ravensorb do you have any more info on this one?

**Comment by ravensorb** [comment]
I did some more research and it seems that the issue is MonoAndroid10 and MonoTouch10 are not valid for any profiles.  The correct format is would be

MonoAndroid1 and MonoTouch1 

Take a look here
http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview
And more info here

http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html

Note: I believe profile 259 and 328 are the most common right now and the primary ones that Xamarin is targeting.

Note: I updated the nuspec file with the changes above and now it works as expected in most Xamarin and PCL projects.

**Comment by ftedin** [comment]
I am not able to use Serilog.Sinks.PeriodicBatching in a PCL project, any idea?

**Comment by nblumhardt** [comment]
@ftedin this thread is unrelated, can you please raise a new issue? Thanks!

**Comment by nblumhardt** [comment]
PCLStorage's NUSPEC seems to indicate no version is necessary: https://github.com/dsplaisted/PCLStorage/blob/master/common/PCLStorage.nuspec#L31

??

I wonder if we can simply drop the Mono* targets and still get the packages to install?

**Comment by nblumhardt** [comment]
Sounds like we may be encountering: https://github.com/NuGet/Home/issues/562

Cheers!
