### ISSUE TITLE
Reopen subproject issue trackers

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#450]
Though initially I was behind the idea of centralizing all issues in `serilog/serilog`, it's not turning out to be very discoverable and I'm concerned we're losing input from folks who don't go digging. The ES sink maintainers have also expressed interest in opening up a tracker on that repo.

Would @serilog/core find a move back to individual trackers less convenient? If not, I'll switch them back on and watch repos as needed.

**Comment by merbla** [comment]
It is clear some sinks are more active than others.  Perhaps just the ones that demand their own trackers get turned on for the moment?

**Comment by SimonCropp** [comment]
Have u considered waffle for managing multiple repos?

**Comment by khellang** [comment]
We have separate issues for the separate Nancy bootstrapper/serializer repos, but I *really* don't think that's the way to go. Often issues fall between two stools because of it. If the repo has separate maintainers, I think it has value, but otherwise I think it would be best to keep a note in the readme that points to the main repo's issue tracker.

**Comment by nblumhardt** [comment]
Closing this for now. I've enabled the tracker on the Seq one, perhaps the same could be done on the more active repos like Splunk, ES, ...

**Comment by merbla** [comment]
Given the changes to projects/repos and structure, my suggestion is to move issues to the related sink repo etc.

**Comment by mivano** [comment]
I do not see an issue. Already see people looking for a place where to
report issues and then the main serilog repository is not direct obvious.
Op za 20 feb. 2016 om 00:52 schreef Nicholas Blumhardt <
notifications@github.com>

**Comment by nblumhardt** [comment]
(Mostly) done. There will be a few little-used sinks without _Issues_ tabs still, if you spot one please make a note or turn it on via _Settings_ on the repo if you have access.

I've moved the existing issues where appropriate. `serilog/serilog` is down below one page of issues again, finally! :-P

Have a good week everyone :-)
