### ISSUE TITLE
ElasticSearch sink crashes during startup when AutoRegisterTemplate = true and server is down

### ISSUE THREAD

**Issue by tnicolaysen** [serilog/serilog#451]
I'm unsure if this is by design or not.

_Error report:_
Given I have a single ES server at `someIP`
And this server is unavailable
And I have the Serilog/ES sink configuration shown below
When I start my application
Then I get an an `SocketException`
And my application crashes

_Notes:_
If I turn of `AutoRegisterTemplate` everything works even if ES is down.

I normally have a fallback in case ES goes down, so for me it would be best if it tolerates that ES is down.

_Configuration that causes problems:_
```cs
var log = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(
        new Uri("http://someIP:9200"))
        {
            IndexFormat = "myIndex-{0:yyyy.MM.dd}",
            AutoRegisterTemplate = true,
        }
    )
    .CreateLogger();
```

***Proposed solutions***

Option 1) Expose a new method on the connection options or on the sink configuration that allows me to specify how internal exceptions should be handled. 

Option 2) Expose a new method on the connection options or on the sink configuration that mutes internal exceptions and logs it to Serilog's SelfLog

Option 3) Catch exception and log it to Serilog's SelfLog

I can write the code and submit a pull request if someone assist with finding out the solution that fits with the intended design.

**Comment by nblumhardt** [comment]
Thanks for the report, much appreciated. Definitely needs a fix.

I think the right option is for the sink configuration to catch the exception, write it to `SelfLog` and carry on as usual (as per [the policy](https://github.com/serilog/serilog/wiki/Reliability#runtime-configuration-errors)).

I would guess a PR is welcome for this - cc @serilog/owners-elasticsearch

**Comment by mivano** [comment]
Nice catch. That should indeed not happen. If a sinks does not work it should not bring the system down. Instead just log it to selflog. A PR is appriciated as I won't be near a PC for the next week. 



—

**Comment by tnicolaysen** [comment]
PR here: https://github.com/serilog/serilog-sinks-elasticsearch/pulls

**Comment by mivano** [comment]
PR merged. thanks!
