### ISSUE TITLE
EventLog sink does not log 32k char+ messages

### ISSUE THREAD

**Issue by fabsenet** [serilog/serilog#452]
Hi!

Please see the details on why you may get an ArgumentException when writing to the Windows EventLog: https://msdn.microsoft.com/en-us/library/e29k5ebc%28v=vs.110%29.aspx

As far as I can tell, a message (or source) which is large enough will yield an ArgumentException. I would suggest to optionally let the sink trim the source and the payload to the max size.

It is better for me to see a partial message than no message at all.

What do you think?

**Comment by nblumhardt** [comment]
Hi - thanks for the report.

Trimming does sound like a good idea, but 32k is a VERY long message. Perhaps throwing the exception, which will go to Serilog's internal `SelfLog`, is a reasonable option? Hard to say - on the one hand, trimming will get some data into the log; on the other hand, pouring out 32k messages is going to be a bad idea in many ways, and the raising the error will at least get this noticed.

Thoughts?

**Comment by fabsenet** [comment]
I was checking your implementation specifically for this "feature" because I want to replace our home-grown trace solution. We have such trimming code in place.

32k is a large message, sure, but if you unfold a larger object? We currently trace exceptions with message and stack and their inner exceptions recursively. You can easily get there in my opinion, thats why I added this code there :smile: 

The source value is even more at risk, because a class name with its namespace can get to 254 characters easily as well. 

And one more thing :sunglasses: : I have not tested it recently but our code replaces ">" and "<" in the source name because (I guess) it does not work. Think of a generic class. Today I also read the first time, that it is not allowed to have "%1" ... "%9" in your messages.

From my point of view it is better to get trimmed messages than none at all.

Would you be interested in me doing a pull request? (In this case, I would actually test everything again instead of just guessing)

**Comment by nblumhardt** [comment]
Absolutely - PR would be very welcome. I wonder if the .NET APIs already implement some of the string escaping etc? Interesting to find out.

Thanks for sharing your notes!

**Comment by fabsenet** [comment]
I do not want to push this too hard, take your time to review etc. but I am not sure about the process of pull requests too much and your repo structure in particular :) Just wanted to write something here so you maybe get an information about something happened?!

**Comment by merbla** [comment]
@fabsenet having a look, just want to investigate the solutions file (e.g VS 2013/15) 

@serilog/core any preferences re: tooling versions?  Some sinks maintain multiple.

**Comment by nblumhardt** [comment]
@merbla I'd go with 2013 until RTM of 2015 - saves churn :-)

**Comment by merbla** [comment]
@fabsenet any chance to revert to VS2013 in the PR?

**Comment by fabsenet** [comment]
https://github.com/serilog/serilog-sinks-eventlog/commit/ae97720c1019525bf0a7959076b703c6890b5a5f

...I have only the RC2015 of visual studio around here so I am not 100% confident but anyway, the solution file continues with "MinimumVisualStudioVersion = 10.0.40219.1" 

I reverted it anyway

**Comment by merbla** [comment]
LGTM :+1:
