### ISSUE TITLE
Rollingfile relative path not working in ASP.NET MVC + IIS Express

### ISSUE THREAD

**Issue by SathishN** [serilog/serilog#454]
I'm using the serilog on first application, it's ASP.NET MVC app + IIS Express using serilog, configured with following AppSetting configs,
```javascript
<add key="serilog:minimum-level" value="Verbose" />
<add key="serilog:write-to:RollingFile.pathFormat" value="logs\log-{Date}.txt" />
<add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="3" />
```
the application creates log file at C:\Program Files (x86)\IIS Express\logs\

Is there a way to to use the relative path. It works if i use a full path!

I'm using log4net in other MVC apps, it resolves to relative path, though!

**Comment by SathishN** [comment]
Look like I'm the only person having this issue, 

I looked into the code https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/RollingFile/TemplatedPathRoller.cs#L47

Following code used to resolving the path,
```
var directory = Path.GetDirectoryName(pathTemplate);
if (string.IsNullOrEmpty(directory))
{
#if ASPNETCORE50
    directory = Directory.GetCurrentDirectory();
#else
    directory = Environment.CurrentDirectory;
#endif
}
directory = Path.GetFullPath(directory);
```
Instead of Environment.CurrentDirectory, using AppDomain.CurrentDomain.BaseDirectory, that will give the right location.

I'm running the web app on IIS Express, the current directory is "C:\Program Files (x86)\IIS Express"

what's your thoughts?

**Comment by nblumhardt** [comment]
@SathishN thanks for the follow-up!

I wonder - would setting:

```csharp
Environment.CurrentDirectory = AppDomain.CurrentDomain.BaseDirectory;
```

cover it? It'd be interesting to hear if this fixes the issue.

We can't make this change globally because it would break those already depending on the use of log paths relative to the current directory. If `cd`ing works, we might be able to do something in https://github.com/serilogweb/classic.

Cheers!

**Comment by SathishN** [comment]
@nblumhardt thanks, that worked for time being, not sure of it breaking any base asp.net framework stuff!!

I understand, it's breaking change, this should be a considered as a bug though! 

I like the Read from AppSettings feature. While using this feature, I see the relative path is key during development, the folder structure may not be matching across developer boxes and log path has to be relative. 

I did look at log4net on handling relative path, it's using AppDomain.CurrentDomain.BaseDirectory,

I would like to hear your thoughts!!

**Comment by nblumhardt** [comment]
Thanks for the update @SathishN.

Other options you might consider are using environment variables like `%TEMP%` or `%PROGRAMDATA%` to choose a path that will be present on all machines.

I'm not keen on baking any ASP.NET dependencies into Serilog, but I wonder if it's possible by some slight-of-hand, or via https://github.com/serilog-web/classic, to set a variable using `Environment.SetEnvironmentVariable()` that could be used in `Web.config` files?

I.e. it'd be called something like `%BASEPATH%` and be used that way in app settings. Thoughts? Any existing variables that already cover it?

Cheers!

**Comment by klettier** [comment]
:+1: @SathishN 
Using **AppDomain.CurrentDomain.BaseDirectory** would be a good thing.

**Comment by nblumhardt** [comment]
Folks, if anyone has ideas for baking this in more elegantly I'd be interested; for now I think the following in `Global.asax.cs` before configuring the logger:

```csharp
Environment.SetEnvironmentVariable("BASEDIR", AppDomain.CurrentDomain.BaseDirectory);
```

and the following config:

```xml
<add key="serilog:write-to:RollingFile.pathFormat" value="%BASEDIR%\logs\log-{Date}.txt" />
```

is a pretty good option. @SathishN thanks again for the input on this!

**Comment by SathishN** [comment]
@nblumhardt Sorry, I was on something else..  that's workable solution for now.. 

But on long term solution serilog should be using AppDomain.CurrentDomain.BaseDirectory

Here is how log4net handles the path. https://github.com/apache/log4net/blob/trunk/src/log4net/Util/SystemInfo.cs#L969

i'm just showing how is it handled in a popular logging framework.

**Comment by nblumhardt** [comment]
Thank you for the link - definitely food for thought. Cheers!

**Comment by TJSoftware** [comment]
This was driving me insane, I was seeing varied results and it was only due to the how I setup the `RollingFile` path.  I was able to log to a relevant path without the `%BASEDIR%` option.  If your `RollingFile` path has a leading `/`, then the directory will start from `C:` if your `RollingFile` path starts with the directory, the relevant path is used.

##### Relevant path example writes to `wwwroot/logs/logs.txt`
```
Log.Logger = new LoggerConfiguration()
                  .MinimumLevel.Debug()
                  .Enrich.WithMachineName()
                  .Enrich.WithProcessId()
                  .Enrich.WithThreadId()
                  .WriteTo.RollingFile("logs/logs.txt")
                  .CreateLogger();
```

##### Absolute path example writes to `C:/logs/logs.txt`
```
Log.Logger = new LoggerConfiguration()
                  .MinimumLevel.Debug()
                  .Enrich.WithMachineName()
                  .Enrich.WithProcessId()
                  .Enrich.WithThreadId()
                  .WriteTo.RollingFile("/logs/logs.txt") //Notice the leading / here
                  .CreateLogger();
```

**Comment by pashute** [comment]
Question for @TJSoftware 

a. But what happens in IIS Express (during development) where is the log created?

b. What if in regular IIS, I want the logs under my application root and not under wwwroot?

**Comment by TJSoftware** [comment]
@pashute I know that when using Serilog you do not need to add the date to the file, Serilog does this for you.  I personally have not used IIS with .Net 5.  What David Hayden's blog has shown will certainly work as it is just creating an absolute path dynamically based on the `appEnv`.  You can do this with `appEnv`, or Directory.GetCurrentDirectory(), go with the `appEnv` though.  Thanks, I may update a test case with this new informaiton.

**Comment by pashute** [comment]
The following works for me in NancyFX (ASP.Net hosted) with Serilog: 

                string logOutputTemplate = "{Timestamp} [{Level}] ({Name}){NewLine} {Message}{NewLine}{Exception}";
            string logPathFormat = Path.Combine(HttpRuntime.AppDomainAppPath, @"Logs\crbauth.Log-{Date}.txt");
            Log.Logger = new LoggerConfiguration()
                //.WriteTo.Trace(outputTemplate: outputTemplate)
                .WriteTo.RollingFile(pathFormat: logPathFormat, outputTemplate: logOutputTemplate)
                .CreateLogger();

Now I can use this with lines like: 

    Log.LogInformation("hi, informing you...");

**Comment by bradleySuira** [comment]
You can use in appSettings
 <add key="serilog:write-to:RollingFile.pathFormat" value="**./logs/myLog-{Date}.log**"/>

use the dot (.) for current dir

and the application writes to /MyAppDir/logs

Regards!

**Comment by dstj** [comment]
@bradleySuira, really? does not work for me with an IIS hosted NancyFx site.

I'm using

```C#
_logger = new LoggerConfiguration().ReadFrom.AppSettings().CreateLogger();
Log.Logger = _logger;
```

and the following in my Web.config

```
<appSettings>
	<add key="serilog:write-to:RollingFile.pathFormat" value="./data/log-{Date}.txt" />
	<add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />		
	<add key="serilog:minimum-level" value="Verbose" />
</appSettings>
```

it does not work, no log file gets created. But an absolute path such as `/data/log-{Date}.txt` (no leading dot) works...

**Comment by navnit-kumar** [comment]
Hi All,
I'm new to #Github, so please if I'm doing something else that I should not do here then please let me know.

@dstj, you can use following line of code.

I'm using

`Log.Logger = new LoggerConfiguration()`
                `//.MinimumLevel.Debug()`
                `//.WriteTo.RollingFile("log-{Date}.txt")`
               ` .ReadFrom.AppSettings()`
                `.CreateLogger();`

and the following in my App.config

`<appSettings>`
    `<add key="serilog:minimum-level" value="Verbose" />`
    `<add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />`
    `<add key="serilog:write-to:RollingFile.pathFormat" value="..\..\Navnit\log-{Date}.txt" />`
    `<add key="serilog:shared" value="true"/>`
    `<add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="7" />`
    `<add key="serilog:write-to:RollingFile.fileSizeLimitBytes" value="1024" />`
`</appSettings>`

It'll create a new folder on root(if doesn't exists) as "Navnit" and log file(s) inside this folder.

Note: If still, it doesn't fit in your solution please feel free to ping me with your doubts/requirements :)

**Comment by dstj** [comment]
@navnit-kumar, thanks for your help.

I managed to get it working. My problem for two things:
1. Missing `<add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />` in the config file

2. Wrong working directory. I was expecting the logger's working directory to be relative to the webapp's DLL location, but it was relative to `C:\Program Files\IIS Express`... I tried to override the `IRootPathProvider` as in the [following solution](https://github.com/NancyFx/Nancy/issues/1688) but it did not work for the logger... don't know why.

**Comment by codecypher** [comment]
Here is how I did it with an ASP.NET MVC 4/5 application.

Add the following to the web.config file:

    <add key="serilog:minimum-level" value="Information" />
    <add key="serilog:minimum-level:override:Microsoft" value="Information" />
    <add key="serilog:minimum-level:override:System" value="Information" />
    <add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
    <add key="serilog:write-to:RollingFile.pathFormat" value="./Logs/log-{Date}.txt" />
    <add key="serilog:write-to:RollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] [{SourceContext}] {Message}{NewLine}{Exception}" />
    <add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />

Then add the following to the `Application_Start` in Global.asax:

    // Get application base directory
    string basedir = AppDomain.CurrentDomain.BaseDirectory;

    // Setup Serilog for logging
    Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .WriteTo.RollingFile(basedir + "/Logs/log-{Date}.txt")
                .CreateLogger();

**Comment by NeurotechDevelopment** [comment]
**codecypher** it still won't pick _outputTemplate_ setting, because we are invoking constructor manually.

**Comment by ehsansajjad-synergy** [comment]
> Folks, if anyone has ideas for baking this in more elegantly I'd be interested; for now I think the following in `Global.asax.cs` before configuring the logger:
> 
> ```cs
> Environment.SetEnvironmentVariable("BASEDIR", AppDomain.CurrentDomain.BaseDirectory);
> ```
> 
> and the following config:
> 
> ```
> <add key="serilog:write-to:RollingFile.pathFormat" value="%BASEDIR%\logs\log-{Date}.txt" />
> ```
> 
> is a pretty good option. @SathishN thanks again for the input on this!

this worked for me, any more cleaner solution now as it;s quite old post

**Comment by chucklu** [comment]
@nblumhardt   Is it possible add this to documentation?

**Comment by chucklu** [comment]
@nblumhardt  Why add AppDomain.CurrentDomain.BaseDirectory before the relative path is not the default behavior? As I know the log4net and nlog make it as the default behavior for relative log path.
