### ISSUE TITLE
No Serilog.Settings.AppSettings for 4.0

### ISSUE THREAD

**Issue by tsvayer** [serilog/serilog#455]
Is there any reason that  4.0 build has no Serilog.Settings.AppSettings?
I am using latest Serilog package version 1.5.6

**Comment by nblumhardt** [comment]
Hi Vitaly- I don't recall any particular reason, it may just have been missed when the feature was added. If you have a chance to investigate it'd be good to know, I'll take a look as soon as I have a chance. Thanks for getting in touch!

**Comment by tsvayer** [comment]
Hi Nicholas, related Pull Request (https://github.com/serilog/serilog/pull/456)

**Comment by nblumhardt** [comment]
This will be in the next build from master, should take a week or so. Many thanks!

**Comment by tsvayer** [comment]
Great to hear that! Thanks.
