### ISSUE TITLE
Console logging is not thread safe

### ISSUE THREAD

**Issue by jayotterbein** [serilog/serilog#458]
Looking at the text writer sink there is a log around the write to ensure thread safety:
https://github.com/serilog/serilog/blob/dev/src/Serilog/Sinks/IOTextWriter/TextWriterSink.cs

The console logger, however, has no such lock, and I've had messages get mangled together because of this:
https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/SystemConsole/ConsoleSink.cs

Side note: the console sink also doesn't dispose of the string writer.

I would just submit a PR, but I'm not sure your desired workflow, thanks.

**Comment by ChrisMissal** [comment]
Would this be a candidate for an `up-for-grabs` label @nblumhardt ?

**Comment by nblumhardt** [comment]
Thanks for the note guys!

@jayotterbein `System.Console.Out` is a `SynchronizedTextWriter`, so locking should be unnecessary:

![image](https://cloud.githubusercontent.com/assets/342712/7894798/a9dee824-06b4-11e5-812d-17900ad453bd.png)

All of the writing done by the console sink is via single `Write()` calls so there shouldn't be any interleaving.

Were the interleaved outputs you observed both generated by the console sink, or was it console sink + some other code writing to the console? It's possible there are some routes to getting directly to the console output stream which will thwart any of our efforts to synchronize.

Also, did you observe this on .NET 4 or 4.5?

RE the `StringWriter`, the Serilog code's a bit opinionated on disposing objects that don't hold resources. You'll find throughout, we don't dispose `StringWriter`, `MemoryStream` etc. if the type of the variable is explicit.

**Comment by jayotterbein** [comment]
Thanks for the response.  With the new information you've given me, I've tracked it down further.

First, I wasn't precise enough: It's the Colored Console Sink, not the Console Sink, that I was using.  Second, I've done something non-standard, apparently.  I have more than one instance of the logger - which meant I had more than one instance of the Colored Console Sink, which didn't share the same syncing object.

I'm not sure at this point if you would consider if user error to have more than one colored console sink, or application error to have an instance-level syncing root on which locks a static concept (console output).

**Comment by nblumhardt** [comment]
Yes, unfortunately there's not any obvious way to counter this; the second thread writing to the console might just use `Console.Write()` directly, and there's no way for any synchronisation object we use to have any effect.

I think the net result is, as when not using Serilog, that concurrent output to the console needs to be considered carefully by the programmer.

For now, since using Serilog's colored console itself is fine, I'd rather leave this one with the status quo than introduce partial fixes that require static data. Thanks again for the report, though!

**Comment by droyad** [comment]
In my scenario I was able to just have my main logger (Log.Logger) log to the console, and then the other loggers used `.WriteTo.Logger(Log.Logger)` to write to the main logger (and through that to the console),
