### ISSUE TITLE
Azure Insight sink uses global static configuration object

### ISSUE THREAD

**Issue by pawelpabich** [serilog/serilog#465]
Hi,

The sink uses global, static config variable (https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsSink.cs#L54-62) which causes issues when there is another piece of code that uses the same approach. This can be avoided by creating the config object in place using TelemetryConfiguration.CreateDefault(); Happy to submit a pull request.

**Comment by nblumhardt** [comment]
Sounds like a change, or at least an option, would be a good move... @jbattermann ? Cheers!

**Comment by jbattermann** [comment]
Yeah that is a good idea. TelemetryConfiguration and context was subject to a couple changes in the earlier versions of the AI API but creating its very own for the sink would indeed keep the serilog AI interactions separate from the rest of potential AI functionalities hooked up by users (ie performance collectors, trace listeners etc which all rely on their own / default Config).

@pawelpabich if you could send over a PR it would be great, yes!

**Comment by pawelpabich** [comment]
Will try to submit a PR withing next couple of days.

**Comment by jbattermann** [comment]
Fixed / Merged by @pawelpabich with https://github.com/serilog/serilog-sinks-applicationinsights/pull/2 - Thanks again!
