### ISSUE TITLE
Provide the ability for fail over Sinks

### ISSUE THREAD

**Issue by ryanande** [serilog/serilog#466]
It would be great if a Sink fails, i.e. connection error for SQL sink, a fall back sink could be identified to be used, i.e. flat file;

` new LoggerConfiguration().WriteTo.MSSqlServer("connection", "table").WriteToFailOver.RollingFile()`

A **WriteToFailOver** method would be great which would be used in case of failure on the primary writers.

**Comment by MichaelCsitkovics** [comment]
Nice idea!

**Comment by nblumhardt** [comment]
Interesting! There's a lot of work in making this possible as a core feature (many sinks work asynchronously, and so-on) so I don't think we're likely to make the (breaking) changes required to support this.

Sinks that emit events directly in `Emit()` tend to communicate failure by throwing exceptions, so it's not impossible to build a wrapper sink today that would work with a limited subset of them... If you decide to investigate/attempt an implementation it'd be cool to see :-)

Thanks for the suggestion nonetheless!
