### ISSUE TITLE
Disable destructuring of properties with an attribute

### ISSUE THREAD

**Issue by nedstoyanov** [serilog/serilog#468]
It may be nice to be able to disable a property being serialized when destructuring. We have a case
where an event is being destructured and is printing thousands of lines of code as it contains a reference to a massive object. 

I know you can implement and `IDestructuringPolicy` but our logging is configured in an assembly that has not got a compile time reference to the assembly that is doing the logging so I thought a better way would be to have an attribute on the property that disables destructuring it. That way the assembly that defines the complex object can specify how it is destructured.

**Comment by nblumhardt** [comment]
Hi @nedstoyanov - thanks for the note! This is already available, details are here: https://github.com/destructurama/attributed

Best regards,
Nick
