### ISSUE TITLE
Mongo Queries on IMongoCollection for Searching Arrays

### ISSUE THREAD

**Issue by arvindcharyn** [serilog/serilog#470]
I have started working with Mongo Database. I am writing my Mongo queries in c#.net. Can you please help me in writing the Mongo Database queries in c#.net. Thanks in advance for your help and support. I am using Mongo CSharpDriver-2.0.0 version and IMongoCollection Async in my application. My data collection looks as shown in the figure:
issue
![a630c4d4-0fb2-11e5-977e-045ddfe66413](https://cloud.githubusercontent.com/assets/12831464/8089320/d5de37b8-0fc4-11e5-933c-33d97a2575f5.png)

Here I want to perform a Search operation on Categories, basically we will give comma separated list of Category Names and it should return a list of Records that are matching the categories that are provided as input. 
To implement above functionality I am using the below code: This code works fine when I pass a single category.

var collection = _database.GetCollection("BusinessDeals");
var filter = Builders.Filter.Eq("Categories.CategoryName", categorylist) | Builders.Filter.Eq("Accessgroups.AccessgroupName", groups);
var result = await collection.Find(filter).ToListAsync();

But my requirement is to get the records when I provide a Comma separated categories List. For that implementation I have implemented the following code:
var collection = _database.GetCollection("BusinessDeals");
var filter = Builders.Filter.AnyIn("Categories.CategoryName", categorylist.Split(',').ToArr()) | 
Builders.Filter.AnyIn("Accessgroups.AccessgroupName", groups.Split(',').ToArr());
var result = await collection.Find(filter).ToListAsync();
The above code is not returning any results and throwing error as “Not Yielded any Results” and Status message as “Failed”.

My another requirement is get nearest location records, for this implementation is implemented the following code:

            var keyBuilder = Builders<BusinessDeal>.IndexKeys;
            //var keys = keyBuilder.Geo2DSphere("ven.loc").Ascending("cat._id");
            keyBuilder.Geo2DSphere(x => x.Venuedetails.Select(y => y.Location)).Ascending(x => x.Categories.Select(y => y.Id)); 
            keyBuilder.Geo2DSphere(x => x.Venuedetails.Select(y => y.Location)).Ascending(x => x.Accessgroups.Select(y => y.Id));

            BsonDocument geoPoint = new BsonDocument
            {
                {"type","Point"},
                {"coordinates",new BsonArray(new Double[]{Latitude, Longitude})}
            };

            BsonDocument geoNearOptions = new BsonDocument
            {
                {"spherical", true},
                {"limit", 0}, //need to test to see what limit is appropriate, should we do a filter first?
                {"maxDistance", 0},
                //{"query", queryDoc}, //may need to implement for speed
                {"near",geoPoint},
                {"distanceField","dist"}
            };

            var stage = new BsonDocumentPipelineStageDefinition<BusinessDeal, BusinessDeal>(new BsonDocument { { "$geoNear", geoNearOptions } });
            var colAggregate = collection.Aggregate().AppendStage(stage);
This above is also not working.

Can you please help me to proceed further. Thanks in advance for your help and support.

**Comment by nblumhardt** [comment]
Hi Arvind,

This is the Serilog issue tracker - I think what you're looking for would be better answered in a forum for MongoDB, we're not well placed to advise you here.

Thanks for reaching out, and best of luck!

Nick
