### ISSUE TITLE
Support basic sinks in PCL build for Xamarin projects

### ISSUE THREAD

**Issue by kensykora** [serilog/serilog#473]
I am working on a Xamarin project with Serilog 1.5.7. Currently when you install with Xmarin, there are some basic sinks I would expect to be present that aren't, such as Console.

I know there is a Xamarin project on github (https://github.com/serilog/serilog-sinks-xamarin) but it's not available via nuget and additionally I'm having trouble getting it to actually log anything.

Can we include some basic sink functionality in the PCL version of Serilog?

**Comment by kensykora** [comment]
I was able to get that project to work correctly, but would still like to see at least a basic Console implementation in place, and a nuget package released for the xamarin sink.

**Comment by nblumhardt** [comment]
Hi there - thanks for the note. If you're interested in adding to the sink project you mentioned, a PR there would be awesome. We don't have build infrastructure for it though, hence no NuGet package, and Xamarin don't seem interested in supporting this scenario.

(Console isn't available in PCL profiles, hence no core support for it.)

Thanks!
