### ISSUE TITLE
docs: Structured-Data#collections

### ISSUE THREAD

**Issue by tugberkugurlu** [serilog/serilog#474]
Inside the docs [here](https://github.com/serilog/serilog/wiki/Structured-Data#collections):

> If the object passed as a property is `IEnumerable`, Serilog will treat that property as a collection.

Is it worth pointing out *"except for `String`"* here?

**Comment by nblumhardt** [comment]
Thanks for the tip. String's not (statically declared as) IEnumerable in .NET Core/Win8 etc., so though it would clarify it for some people it might be confusing for others in the long term. Might leave it as-is for now, appreciate the feedback though!
