### ISSUE TITLE
List or take control of OrientDB Sink

### ISSUE THREAD

**Issue by psibernetic** [serilog/serilog#476]
I have created a sink that corresponds to the stated requirements for contribution. We needed the nuget package available for our current development, but would gladly transfer ownership to the Serilog project.

https://www.nuget.org/packages/Serilog.Sinks.OrientDB/0.1.0.7

**Comment by nblumhardt** [comment]
Thanks for getting in touch - much appreciated!

I've listed the sink in https://github.com/serilog/serilog/wiki/Provided-Sinks#third-party which should help people to find it. Is there a public GitHub repository for it?

One minor note, we use http://serilog.net/images/serilog-sink-nuget.png as a package icon for sinks that don't have their own customised one. (The one you're using is from the Seq sink, which might be a bit confusing.)

We can definitely consider taking this under the Serilog project umbrella, especially if it becomes widely used, but we're finding this to be less and less valuable over time as we start to encourage contributors to maintain their contributions anyway (it's a challenge to bring in all the skills needed to actually maintain things we're not actively using ourselves). If you have a GitHub repo, it'd be interesting to see how we can further support your project that way.

Keen to have your thoughts. Thanks again for reaching out!

**Comment by psibernetic** [comment]
Our repo is located here: https://github.com/dev-informatics/Serilog.Sinks.OrientDB

I am changing the image and we are fine hosting/maintaining the library, just wanted your take on it. Thanks for listing us!

**Comment by nblumhardt** [comment]
Thanks @psibernetic! :-)
