### ISSUE TITLE
Configure ILogEventEnricher via AppSettings/KeyValuePairs

### ISSUE THREAD

**Issue by artganify** [serilog/serilog#480]
Is there a way to configure an existing `ILogEventEnricher` using *AppSettings* or *KeyValuePairs*? 

According to the current [KeyValuePairSettings.cs](https://github.com/serilog/serilog/blob/dev/src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs) in namespace *Serilog.Settings.KeyValuePairs*, serilog only checks for keys containing `enrich:with-property`, but I can't figure out how to configure e.g. the enrichers from [SerilogWeb.Classic](https://github.com/serilog-web/classic) using that notation.

**Comment by nblumhardt** [comment]
Hi - no, not at present.
