### ISSUE TITLE
Race Condition in Email-Sink

### ISSUE THREAD

**Issue by fabsenet** [serilog/serilog#482]
I have a console application. In main, I configure Serilog to send logs as mail (minimum=verbose):
```C#
void Main()
{
    SetupLogging();
try{
    OtherStuff();
    throw new Exception("test");
}
catch(Exception ex){
Log.Fatal(ex, "...");
}
```

if the exception is thrown to early, I do not get any mail. If the process is already running for some time (probably loaded the correct assemblies already), I will get the exception via mail.

My first idea is: In the sink is a Wait() on the sendingtask missing to ensure, all log entries are sent before continuing to dispose. ( https://github.com/serilog/serilog-sinks-email/blob/master/src/Serilog.Sinks.Email/Sinks/Email/EmailSink.cs#L90 ) 

In my configuration, I also log to console and file and both have the exception logged 100% of the time but email varies as explained.

**Comment by fabsenet** [comment]
I tried some more and it has nothing to do with "otherstuff()" :smile: 

consistently sends no mail:
```C#
void Main()
{
    SetupLogging();
    Log.Fatal("...");
}
```

consistently sends mails:
```C#
void Main()
{
    SetupLogging();
    Log.Fatal("...");
   Thread.Sleep(TimeSpan.FromSeconds(10));
}
```

Please fix this! Currently it is just not deterministic at all!

**Comment by merbla** [comment]
Hi @fabsenet, the Email Sink is a [PeriodicSink](https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/PeriodicBatching/PeriodicBatchingSink.cs) that allows a `TimeSpan` when configuring the sink.

In your configuration, do you have a `TimeSpan` set?  The default is 10 seconds I believe.

**Comment by fabsenet** [comment]
I did not touch the TimeSpan. 

Lets talk expectations for a second: should I receive an email or not when I do 
```C#
void Main()
{
    SetupLogging();
    Log.Fatal("...");
}
```
??

I think I should.

I followed the code in the PeriodicSink and I believe it successfully calls  ```EmitBatchAsync(events).Wait();``` in an shutdown event and the implementation in the email sink awaits the smtp client in this case as well. I cannot see any error but I dont see any mail either.

**Comment by superlogical** [comment]
Your program will shutdown because you've exited Main. The Log call does not block

**Comment by fabsenet** [comment]
okay then what should I do to reliably receive the email with the fatal message in the sample above? because i definitely want to know when my app crashes with an unhandled exception.

**Comment by nblumhardt** [comment]
Hi all-

Thanks for the report Fabian.

These can sometimes be a bit tricky. The sure-fire way to always flush asynchronous sinks on exit is to dispose the logger, e.g.:

```csharp
((IDisposable)Log.Logger).Dispose();
```

If that doesn't work, can you let us know the version of Serilog you're using? There was a fairly recent change to hook the `AppDomain.UnhandledException` event and flush - may be missing from your version.

It's also possible it's related to SMTP mail specifically, but I don't have any info suggesting it. Insights appreciated :-)

Cheers!
Nick

**Comment by fabsenet** [comment]
I tested it on Win10, VS2015 preview, .Net 4.6pre and it "just works". The email is always generated.

At work I have to do the Dispose() call. I have no idea, whats different but it works this way so I leave it as is and call Dispose() to be sure.

Thanks everyone.

**Comment by nblumhardt** [comment]
Thanks for the update Fabian. I think we might need a more prominent note in the wiki about disposing to flush asynchronous loggers, will try to find a spot for it. Cheers!
