### ISSUE TITLE
Change logger/sink configuration at runtime?

### ISSUE THREAD

**Issue by artganify** [serilog/serilog#485]
Is there a straightforward way to change the logger configuration (or sink configuration) at runtime?

I generally set up my main logger with a rolling file sink to print out critical errors (especially at startup) as this works in most scenarios. Independently of what type of application I have (service, website, console), I only need to ensure the file system is write-able and I'm good to go.

    // dummy
    var logfilepath = GetLogFilePath(Assembly.GetEntryAssembly());
    Log.Logger = new LoggerConfiguration()
                            .WriteTo.RollingFile(logfilepath)
                            .CreateLogger();
    Log.Debug("It works!");

However, I also would like to log into other sources that are more prone to fail at startup (e.g. databases when wrong connection strings are given). So what I would like to achieve is the following:

1. Set up a simple, stable logging sink for first startup
2. Set up e.g. database, log everything related to it
3. If e.g. database is up and running, add database sink to serilog.

The only way I see to accomplish this is:

1. Create a logger configuration
2. Do stuff
3. Create a new logger configuration and overwrite the existing one.

Dummy code:

    var logfilepath = GetLogFilePath(Assembly.GetEntryAssembly());
    Log.Logger = new LoggerConfiguration()
                            .WriteTo.RollingFile(logfilepath)
                            .CreateLogger();
    Log.Debug("It works!");

    Log.Debug("Setting up database with {ConnectionString}", connectionString);

    Log.Logger = new LoggerConfiguration()
                                .WriteTo.RollingFile(logfilepath)
                                .WriteTo.SomeDatabaseSink(connectionString)
                                .CreateLogger();

Is there a cleaner, more straightforward approach to change the logger configuration other than overwriting it completely?

**Comment by nblumhardt** [comment]
Here's one option that's debatably better:

```csharp
// <snip>
Log.Debug("Setting up database with {ConnectionString}", connectionString);

Log.Logger = new LoggerConfiguration()
                            .WriteTo.Sink((ILogEventSink)Log.Logger)
                            .WriteTo.SomeDatabaseSink(connectionString)
                            .CreateLogger();
```

Instead of letting the old logger drop, the new one just redirects to it.

It's not ideal, but if you set up enrichment etc. on the second (rather than the first) logger it might cut a bit of duplication/noise out. It also has the property of being less likely to cause file locking issues.

:+1: or :-1: ?

**Comment by IanYates** [comment]
I have a similar issue and hadn't thought of @nblumhardt 's solution.

I have some client workstation endpoints that should be communicating with local services on the workstation (ophthalmic medical equipment).  Those endpoints talk over HTTP back to our server (a mix of WebAPI & SignalR).  The server tells the endpoint what jobs it has to do.

I want Serilog to be able to log back through our server, but if there's a server connectivity issue then I can't really do logging straight away.  Logging locally to a file, and then once the server connection is up including our server as a target via a dirty custom sink I wrote (which ultimately sends it on to Seq with some annotations) is ideal.  I'd made something work but this seems like a cleaner approach.  I'll give it a try soon.

Thanks for the discussion & ideas.

**Comment by artganify** [comment]
@nblumhardt +1 because it's so simple I barely even noticed what you did. -1 because it's so simple I barely even noticed what you did.

Another possible solution would be to treat the `LoggerConfiguration` more as a `LoggerFactory` or `LoggerConfigurationFactory` while exposing a `LoggerConfiguration` directly on the interface of `ILogger` (as well as on `Log` for the static instance). Instead of creating a `SafeAggregateSink` and a new instance of `ILogger` directly from the configuration, you could create a new `LoggerConfiguration` and pass it to the new `ILogger` instance, building up the `SafeAggregateSink`, formatters, message processors etc. directly in the constructor of the logger instead of inside the logger configuration.

    var logger = new LoggerConfigurationFactory()
                            .WriteTo.BlaBla()
                            .CreateLogger();

    // logger configuration factory
    public ILogger CreateLogger() {
        var configuration = new LoggerConfiguration {
            Sinks = _logEventSinks,
            ...
        }

        return new Logger(configuration);
    }

So one could simply...

    logger.Configuration.Sinks.Attach.SomeDatabaseSink(configuration);
    // attach would be of type 'LoggerSinkConfiguration'

I didn't investigate further in the code so I can't really tell if it would break existing extensions, but as far as I can tell, the various serilog extension packages rely on the types available in `Serilog.Configuration` (e.g. `LoggerEnrichmentConfiguration` etc.) instead of the `LoggerConfiguration` class.

(btw. is there a reason `ILogger` enforces methods like `.Verbose`, instead of exposing only e.g. `.Write(LogEvent)` and doing the rest with extension methods?)

**Comment by nblumhardt** [comment]
Thanks for the follow up @artganify.

I suspect something along the lines you've suggested could be made to work, but the one-time-use aspect of `LoggerConfiguration` is also in part due to the "singleton" nature of many sinks created from it, e.g. a file sink can only be created once for a specific filename unless the previous logger was disposed (and there are more situations where parameters passed to sink configuration methods, e.g. `TextWriter`, would end up being desirable to re-specify for the additional logger instances).

All interesting ground to cover but I don't think the scenario gap covers it right now, given a possible workaround.

Just raised #505, which may also be of interest. Cheers!

**Comment by damianh** [comment]
@nblumhardt is https://github.com/serilog/serilog/issues/485#issuecomment-119893957 still the recommended approach?

Just got bitten by this. I am currently of the opinion (not strongly held) that if `Log.Logger` is set, previously retrieved `Logger.ForContext()` should still just work. This is NLog's behviour. https://github.com/damianh/Temp-SerilogStaticReconfig/blob/master/src/ConsoleApplication1/ConsoleApplication1/Program.cs I think Log4Net is the same.

**Comment by damianh** [comment]
The workaround doesn't quite work if the initial logger is `SilentLogger`:

            var logger = Log.Logger.ForContext<Program>();

            Log.Logger = new LoggerConfiguration()
                            .WriteTo.Sink((ILogEventSink)Log.Logger)
                            .WriteTo.Console().CreateLogger();

            logger.Information("Baz to evry1");

![image](https://cloud.githubusercontent.com/assets/57436/10938919/24cdd7dc-82fe-11e5-9783-89cd69b2a479.png)

**Comment by damianh** [comment]
I think I've got a workaround. It's _ugly as hell_. Especially dat cast.

        private static void ZeSerilogWorkAround()
        {
            var delegateLogEventSink = new DelegateLogEventSink();

            // Must do this very first thing. Prob in static ctor of program.cs.
            Log.Logger = new LoggerConfiguration().WriteTo.Sink(delegateLogEventSink).CreateLogger(); 

            var logger = Log.Logger.ForContext<Program>();

            delegateLogEventSink.Inner = (ILogEventSink)new LoggerConfiguration().WriteTo.Console().CreateLogger();

            logger.Information("Baz to evry1");
        }

        private class DelegateLogEventSink : ILogEventSink
        {
            internal ILogEventSink Inner;

            public void Emit(LogEvent logEvent)
            {
                ILogEventSink inner = Inner;
                inner?.Emit(logEvent);
            }
        }

**Comment by nblumhardt** [comment]
Thanks for the weigh-in @damianh. I agree there are some rough edges around this scenario, especially existing contextual loggers, as you point out. I think the way existing loggers continue to point to the sinks they were created with falls out from the immutable/stateless design, which isn't ideal here but brings a lot of other benefits. Do you think your workaround is something that could be made general? It seems like the best approach available at this point.... :-)

I think the new `WriteTo.Logger()` method added in the latest Serilog gets rid of your casting issue:

```
Log.Logger = new LoggerConfiguration()
      .WriteTo.Logger(Log.Logger)
      .WriteTo.Console().CreateLogger();
```
