### ISSUE TITLE
Request: Move PeriodicBatching to PCL version of library

### ISSUE THREAD

**Issue by ravensorb** [serilog/serilog#486]
Serilog is a fantastic logging framework -- unfortunately it is almost unusable in mobile applications as move of the sinks leverage PeriodicBatching and that is only provided in the Full client version.

Note: I am working on a port of it to full PCL -- only issue is the Timer object is not support in Profile259.  I think I have a possible solution and am testing now.

**Comment by merbla** [comment]
@ravensorb there have been a few sinks that required a PCL which have run into this issue.  Most have implemented a mechanism particular to that sink.

e.g.
 - [Previous Issue (Closed)](https://github.com/serilog/serilog/pull/179) 
 - https://github.com/serilog/serilog-sinks-splunk/blob/master/src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkViaHttpSink.cs#L179

Be interested in what you come up with however, there are already a few variations on top of the existing PeriodicBatching that need to be considered.

**Comment by ravensorb** [comment]
I just created the PR. Let me know what you think

**Comment by nblumhardt** [comment]
Thanks for all the investigation Shawn!

To add to Matthew's list - another portable `Timer` replacement that's had a bit of testing: https://github.com/continuousit/seq-client-portable/blob/master/Seq.Client.Portable/Client/Portable/PortableTimer.cs

Definitely needs to happen! :-)

I don't think the timing is great for this right now - VS2015 support is coming soon and there are already a few changes in the works that need to line up there.

I think we should leave **this issue open**, but close the PR and additional (logentries) tickets for the time being. Once 2015 has shipped and the great project reoganisation completed, a lot should fall into place.

What do you think? Cheers!

**Comment by ravensorb** [comment]
Nice, doesn't support the change method but still I like it - might be easier to maintain.

If you me to cancel the PR, that's is ok with me -- I just have an immediate need to support Serilog in a series of mobile PCL based applications so I will need to keep this fork going for now.

Would it be easier if I integrated this into a newer branch? I'd be willing to do another PR if that would help.

**Comment by nblumhardt** [comment]
@ravensorb I think for now let's put this on hold while the core project work happens - making progress, hope to have something on the `dev-v2` branch shortly, but it will be a while before it has stabilised. Cheers!

**Comment by ravensorb** [comment]
ok, I'll cancel it.

**Comment by ravensorb** [comment]
Any update on this? I'd like to stop needing to maintain a private build :smile:

**Comment by nblumhardt** [comment]
Howdy! No, no current update - the `v2` branch will land when ASP.NET 5 does, I'm hoping to do this work over there between now and then.

**Comment by ravensorb** [comment]
With the RC version of ASP.NET 5.0 being release I thought I'd check on how things are going for the v2 branch in terms of stability.

**Comment by merbla** [comment]
@ravensorb a few items of interest will be

- #590 
- #595 

Also #591 will take dev-2 and move it to dev

**Comment by nblumhardt** [comment]
This has been done in the v2 branch, now on dev. Should be out as a beta package before too long.
