### ISSUE TITLE
Port Logentries Sink to PCL

### ISSUE THREAD

**Issue by ravensorb** [serilog/serilog#487]
Once PeriodicBatching is ported to the PCL library it would be great to see Logentries sink ported as well.

**Comment by nblumhardt** [comment]
Closing as dependent on #486 - once that work is done, PRs covering logentries and other currently full-fx sinks would be great.

**Comment by hgjura** [comment]
I tried to add the Logentries sink to PCL library and it failed. I thought there was a PCL version of this.
