### ISSUE TITLE
VS2015 aspnetcore50 platform targets are deprecated

### ISSUE THREAD

**Issue by axefrog** [serilog/serilog#489]
Needs to be changed to dnxcore50 - currently can't reference SeriLog in new CoreCLR projects.

**Comment by nblumhardt** [comment]
Hi - do you mean in the `Project.json` file that's currently in `dev`? If so, it's defunct - Serilog does currently support CoreCLR, but through the regular NuGet package. You may find after referencing the Serilog NuGet package from your project, you need to add references to:

```json
                "System.Collections": "4.0.10-beta-23019",
                "System.Linq": "4.0.0-beta-23019",
                "System.Threading": "4.0.10-beta-23019",
                "Microsoft.CSharp": "4.0.0-beta-23019"
```

(See an example here: https://github.com/serilog/serilog-framework-logging/blob/dev/src/Serilog.Framework.Logging/project.json.)

Work on supporting VS2015 with the core solution is underway, but so far unpublished. It's going to be on the `dev-v2` branch in the next few days.

**Comment by csunali** [comment]
Hi,

Serilog.Sinks.MSSqlServer package reports not supporting the core framework. Do you have any unpublished changes for that as well?

**Comment by nblumhardt** [comment]
@csunali no, not at this point.

**Comment by csunali** [comment]
@nblumhardt is there a document somewhere which describes how may I create one for myself?

**Comment by nblumhardt** [comment]
@csunali cloning and modifying https://github.com/serilog/serilog-sinks-mssqlserver to suit your requirements is probably the best way forward. Please raise another issue or pop up on https://jabbr.net/#/rooms/serilog if you need more help - this thread is unrelated. Thanks!
