### ISSUE TITLE
Trace Sink not Rendering Messages

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog#490]
I'm just calling config.WriteTo.Trace() for the trace sink, and it spits out unrendered log messages, with the {token}'s still in the template.

I can't seem to find any explicit documentation about this - is it supposed to render?

**Comment by nblumhardt** [comment]
G'day James!

When I run this sample:

```csharp
var log = new LoggerConfiguration().WriteTo.Trace().CreateLogger();
log.Information("Hello, {Who}", "World");
```

I see:

```
ConsoleApplication1.vshost.exe Information: 0 : 2015-07-20 07:42:57.313 +10:00 [Information] Hello, "World"
```

in the VS output window. Can you narrow down what might be causing it any further?

Cheers!

**Comment by jamesbascle** [comment]
Bahh, this was totally my fault.  I forgot we created a totally base case non-rendering tracer for debugging purposes a while back, and that one was being configure that one instead of the real Serilog tracer.  It definitely works properly.  Sorry for the issue without diving deeper into it.
