### ISSUE TITLE
KeyValuePair configuration option missing from .net 40 build

### ISSUE THREAD

**Issue by alexfelton** [serilog/serilog#491]
I need to use Serilog with .net 40 projects as we still have some clients on pre Win7/2008 and I wanted to use the KeyValuePair configuration option, which is fine in .net 45, but doesn't seem to be present in .net 40. version, if this was just an oversight then please could it be added unless their was a specific reason for it. Thanks

**Comment by nblumhardt** [comment]
Hi @alexfelton - this change went out just a little while ago; you may need to update the Serilog version used by your app.

https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/LoggerConfigurationFullNetFxExtensions-net40.cs#L272

If you update and the configuration method doesn't appear, please reopen this ticket and I'll take a look. Thanks!

**Comment by alexfelton** [comment]
I was looking to enable the missing KeyValuePairs method in serilog/src/Serilog/Configuration/LoggerSettingsConfiguration-net40.cs

**Comment by nblumhardt** [comment]
I see - my mistake! Yes, this should be enabled.

**Comment by alexfelton** [comment]
Thanks for quick resolution. How long does it normally take for this kind of change to go upto nuget?

**Comment by nblumhardt** [comment]
Just pushed the change to master, it should get to NuGet as soon as it is through CI. Cheers!
