### ISSUE TITLE
Destructuring a IList<Byte[]> on an object does'nt produce any output

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog/serilog#493]
I have a class like 

    public class Foo
    {
        class Foo()
        {
            Bar = new List<Byte[]>();
        }

        public IList<Byte[]> Bar {get;set}
    }

I'm wondering what Serilog would make of this ? I seem to get an empty Collection in the Json even when it's populated with Arrays. I've even tried a custom .Destructure.ByTransforming<Foo> and doesn't seem to make a difference. 

I have an extension which turns an byte[] into a printable string but still get nothing; anyone have any ideas ?

**Comment by johnkattenhorn** [comment]
Here the destructor I've tried

    .Destructure.ByTransforming<OutgoingMessage>(
        r =>
            new
                {
                    DeviceType = r.DeviceType.ToString(),
                    IncomingMessage = r.IncomingMessage,
                    DeviceAddress = r.DeviceAddress,
                    OutgoingResponses = r.MessageCollection.Select(x => new
                    {
                        Raw = x.ToPrintByteArray()
                    }),
                    r.MessageUid
                })

**Comment by nblumhardt** [comment]
Thanks John - not sure what might be causing this, will investigate as soon as possible.

**Comment by johnkattenhorn** [comment]
So sorry should have closed this, I found if I put on a .ToList on the select then all was good.
