### ISSUE TITLE
Elasticsearch sink doesn't support Shield

### ISSUE THREAD

**Issue by hanzo** [serilog/serilog#495]
I hope I'm not missing something obvious, but I don't see a way to configure the Elasticsearch sink to write logs to an Elasticsearch instance that's using Shield authentication. The requests to ES must contain a Authorization header as described here: 
https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_http_rest_clients_with_shield.html

Is this supported with the latest version of the Elasticsearch sink?

**Comment by mivano** [comment]
Not directly, but I have a customer who just uses basic auth by passing the username and password as part of the url. Not ideal but possible. Another alternative is to use the ModifyConnectionSettings functionality (https://github.com/serilog/serilog-sinks-elasticsearch/blob/bcefb37eb8b3da0d55f6b7f945fdf0d01f4f5a18/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs#L77) and set them up within your code.

A good idea would also to add a username/password property and pass that to the elasticsearch.net library from within the sink itself. Open for PR :-)

**Comment by hanzo** [comment]
Thanks, I was able to get the functionality I need using ModifyConnectionSettings: 

ModifyConnectionSettings = x => x.SetBasicAuthentication(username, password);

Seems satisfactory to me, I'll close the issue. Thanks for your help!
