### ISSUE TITLE
Change internal seq sink classes to public

### ISSUE THREAD

**Issue by Venomed** [serilog/serilog#496]
Please consider opening up the Seq sink library so I can offer a PR on it.

I've had a need for using cross-domain logging on the Seq sink and managed to write a domain aware wrapper around your SeqSink (& DurableSeqSink) that I'd like to contribute.

However since the classes are internal, I can't offer it as a separate project. If you prefer, I'm happy to offer the PR on the project itself (that's how it's implemented right now under `DomainAwareSeq` namespace next to `Seq` namespace folder) if you'd prefer to have it merged in the same sink.

**Comment by nblumhardt** [comment]
Hi! Thanks for reaching out. I think in this case it's probably best for you to fork the sink to suit your scenario - it's a valid use case for sure, but not something I'm keen to target in this specific sink. Thanks for the offer of assistance nonetheless!

**Comment by Venomed** [comment]
Roger that. Closing issue in that case :)
