### ISSUE TITLE
Should double-open-braces always be parsed as a single brace?

### ISSUE THREAD

**Issue by adamchester** [serilog/serilog#498]
I believe the message template parser behaves incorrectly when double-open braces `{{` are inside a previous open-brace (i.e. what _appears_ to be inside a property token).

Firstly, is my assumption of how it should behave, actually correct?

The following [test](https://github.com/adamchester/serilog/blob/e5bb5b9d7f06ba1aeeef14abdf5b001f9f279f2a/test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs#L53) currently fails:
```csharp
[Test]
public void DoubledLeftBracketsAreParsedAsASingleBracketInsideProperty()
{
    AssertParsedAs("Well, {he{{llo!}",
        new TextToken("Well, {he{llo!}"));
}
```

The results of `MessageTemplateParser.Parse` with v1.5.9 is:

StartIndex | Length | Text
---------- | ------ | -----
0 | 6 | Well,  
6 | 10 | {he{{llo!}

**Comment by nblumhardt** [comment]
I think your test's behaviour is mildly better and would +1 this on philosophical grounds.

Whether or not we want to change the behaviour in Serilog is probably less clear, since it's a change that's unlikely to be a major benefit to anyone. What are your thoughts?

Cheers!

**Comment by adamchester** [comment]
Agreed, I can't think of any real world scenario where this would cause pain for anyone...

Hmm...

**Comment by nblumhardt** [comment]
Closing for now; thanks Adam!

**Comment by adamchester** [comment]
:+1:
