### ISSUE TITLE
ReSharper plugin for Message Template syntax highlighting

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#50]
Courtesy Matt Ellis from the JetBrains team:

Hi Nick. Nice idea. And the good thing is, it’s close enough to the string formatting highlight that we can use the existing implementation as a guide to implement a plugin. You want to fire up dotPeek, point it at the ReSharper bin folder and find CSharpFormatItemAndMatchingArgumentContextHighlighter. This is the class that does the format string highlighting.
 
The only trouble is, it’s not easy to follow what’s going on. The class has an identifying attribute, and implements a static method to construct an async handler of some kind, but it’s really hard to see when it gets called and how often. I don’t have any experience with this, so I think the best thing to do would be to start to implement something and debug and see how far it goes. Essentially, it’s getting a data provider that can be used to get the current context – the abstract syntax tree of the current file, the currently selected element, the caret offset and selection and so on. It’s then looking for string literals to parse out of the string format, and applies a highlight to the currently selected format item and arguments, using a lifetime. This lifetime is a construct that allows an action to run when the lifetime is terminated – here it’s used to remove the highlight when the lifetime terminates, which will be when the cursor moves out of the way.
 
A different class is responsible for highlighting that an argument isn’t used, or that there aren’t enough arguments – FormatStringProblemAnalyzer. This class performs a number of checks and adds highlights for a number of conditions, including the mismatched arguments. You can reuse the highlight classes, but will have to implement your own ElementProblemAnalyzer.

**Comment by nblumhardt** [comment]
@khellang may be time to move on from this one, at least until there's a big chunk of spare time found somewhere :-) .. Shall we close for now?

**Comment by khellang** [comment]
LOL. Yes. This went nowhere. Now there's the possibility to ship Roslyn analyzers as well, which could be used by a lot more people. Maybe it's worth looking at that instead...
