### ISSUE TITLE
CS0012: The type 'Object' is defined in an assembly that is not referenced after upgrading to .NET 4.6

### ISSUE THREAD

**Issue by oliverjanik** [serilog/serilog#501]
I've just upgraded to VS2015 and .NET 4.6 and retargeted all my nuget packages and Serilog gives me this error on the build server (works fine from VS locally).

Googling suggests it has to do with referencing a PCL library, but I'm fuzzy on the details.

I'm getting a lot of these errors where my code calls serilog methods:

```
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Will this be fixed by a new nuget release that targets 4.6?

**Comment by oliverjanik** [comment]
Never mind. Looks like my CI server was missing dependencies.  If anyone comes across this:

1) Install https://www.microsoft.com/en-us/download/details.aspx?id=46882
2) http://www.microsoft.com/en-us/download/confirmation.aspx?id=48136
3) Copy targets file from dev machine to "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0"

It was the step 2) that I was missing. I'm still not sure why it complained on Serilog calls only. 

Closing the issue.

**Comment by nblumhardt** [comment]
Great! Thanks for closing the loop :+1:
