### ISSUE TITLE
Are there plans for better xml/json configuration?

### ISSUE THREAD

**Issue by AndrewSav** [serilog/serilog#502]
One advantage that log4net has, is that once you have your set of loggers defined by your code, you can change the configuration without recompiling the whole thing and basically log anywhere. You can pull out DbgView, add an appender attach it to a particular logger and off you go. You could have all the system log at the level of ERROR and just this appender at TRACE to get the current trace data from this particular logger. Also the config file can be watched and reloaded on change. This is very powerful while working on production support to get needed information at your fingertips without bogging down the system with unnecessary logging when all is well.

While you can config Serilog a great deal via appSettings, it's nowhere as powerful as log4net.

Could you please let me know if you have plans for better support of xml configuration in future? Is this on todo list or is the current state something you are completely satisfied with?

**Comment by nblumhardt** [comment]
Hi Andrew,

More advanced dynamic/runtime configuration changes aren't currently on the list. There are two aspects - XML configuration side of things, and the logger pipeline functionality.

In the pipeline, immutability rules, and makes concurrency (among other things) much cleaner.

As far as XML config (`System.Configuration`) goes, it's not as common these days to make changes to XML config files on-the-fly, and cloud deployment environments are making this less attractive as a reconfiguration option.

Both considerations combine to make more work on this unlikely at this point.

Note, you can use `LoggingLevelSwitch` today to make level changes on the fly; it'd be nice to extend this through to the sinks as well, and that change might enable some of what you're looking for. Let me know if this is something you'd be interested in.

Cheers!

**Comment by AndrewSav** [comment]
Thanks you.
