### ISSUE TITLE
Serilog.Sinks.Raygun support for UWP (Win10)

### ISSUE THREAD

**Issue by AleksandarDev** [serilog/serilog#504]
Raygun is compatible with Win10 packages.
With Raygun sink I'm getting following error message:

```
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
```

_SDK version 10.0.10240_

**Comment by nblumhardt** [comment]
Thanks for the heads-up Aleksandar. We'd happily accept a PR for this if it is something you're interested in. Cheers!

 (Source is at: https://github.com/serilog/serilog-sinks-raygun)

**Comment by AleksandarDev** [comment]
@nblumhardt So this works now?

**Comment by nblumhardt** [comment]
Hi Aleksandar - no, I don't think anyone has submitted an enhancement to enable this. We're aiming to keep the issue tracker trimmed to just the things we are intending to take action on, but if someone has the opportunity to make that scenario work it'd be a welcome enhancement over on the linked repo. Cheers!
