### ISSUE TITLE
Clean up tests for DNX

### ISSUE THREAD

**Issue by khellang** [serilog/serilog#513]
#512 migrated the tests over to xUnit to run them on DNX. In the process, a few issues came up:

- [ ] 4 tests started failing for some reason. They were just skipped for now, but should be looked into and fixed:
  - `Serilog.Extras.AppSettings.Tests.AppSettingsTests.EnvironmentVariableExpansionIsApplied`
  - `Serilog.Extras.AppSettings.Tests.KeyValuePairSettingsTests.FindsConfigurationAssemblies`
  - `Serilog.Tests.Context.LogContextTests.DoesNotPreventCrossDomainCalls`
  - `Serilog.Tests.Sinks.PeriodicBatching.PeriodicBatchingSinkTests.WhenAnEventIsEnqueuedItIsWrittenToABatch_OnTimer`
- [ ] xUnit does not have a concept of "inconclusive tests", either they pass, or they don't. There are a few tests in `Serilog.Tests.Context.LogContextTests` which used `Assert.Inconclusive`. These needs to be addressed.

We should also look into porting the rest of the test projects:

 - [ ] Serilog.MsTests
 - [ ] Serilog.PerformanceTests
 - [ ] Serilog.SmokeTest

The last 2 are not really test projects, but reside in the test folder. Maybe they should be (re)moved?

**Comment by nblumhardt** [comment]
#586 also covers this
