### ISSUE TITLE
LogContext.Enrichers cleared somehow during Owin/WebApi pipeline

### ISSUE THREAD

**Issue by todd-bowles-onthehouse** [serilog/serilog#517]
I have a fairly simple Owin/Katana/WebApi service.

I have implemented a piece of OwinMiddleware to enrich log messages with things like Path, Http Method, etc.

The enriching seems to work fine (I log a request incoming message straightaway in the middleware), but when the execution path gets into the WebApi controller, the LogContext.Enrichers seems to be null.

By the time the execution path gets back into the middleware, the LogContext is back to what I would expect it to be, and I enrich with StatusCode and StatusDescription.

The most annoying part of this, is that the middleware adds a correlation id so that I can correlate all of the log messages spawned from a single request, but that information (along with path, method, etc) is all gone for every message logged inside a WebApi controller.

Are there thread considerations that I'm missing?

**Comment by IanYates** [comment]
Possibly related to #472...

**Comment by suddenelfilio** [comment]
@todd-bowles-onthehouse I posted in the related issue that changing the order of use statements might potentially fix the problem, not sure if it will in your case.

**Comment by todd-bowles-onthehouse** [comment]
Thanks for the comments. It looks as though your workaround essentially enforces the logging middleware being the last step in the pipeline before the actual modules.

Because that works, it implies that the other middleware component is losing the context, which is likely the root cause in my case as well (I've got the ASP.NET Identity Framework middleware in there).

**Comment by nblumhardt** [comment]
Closing as I don't think there's much we can do on the Serilog side of this right now, but please reopen if you end up with more data pointing our way :-)
