### ISSUE TITLE
Email and LiterateConsole read from AppSettings can't co-exist

### ISSUE THREAD

**Issue by swjensen** [serilog/serilog#519]
When I load Email and Literate from AppSettings like this, the LiterateConsole sink is not loaded. Moving the Email using statement to the top, will cause the Email sink not to be loaded
  <appSettings>
    <add key="serilog:using" value="Serilog.Sinks.Literate" />
    <add key="serilog:using" value="Serilog.Sinks.Email" />

    <add key="serilog:write-to:LiterateConsole"/>
    <add key="serilog:write-to:Email.mailServer" value="..." />
    <add key="serilog:write-to:Email.fromEmail" value="..." />
    <add key="serilog:write-to:Email.toEmail" value="..." />
  </appSettings>

<packages>
  <package id="Serilog" version="1.5.9" targetFramework="net45" />
  <package id="Serilog.Sinks.Email" version="1.5.15" targetFramework="net45" />
  <package id="Serilog.Sinks.Literate" version="1.2.0" targetFramework="net45" />
</packages>

**Comment by swjensen** [comment]
Some of the xml was lost in the editor - trying again

    <add key="serilog:using" value="Serilog.Sinks.Literate" />
    <add key="serilog:using" value="Serilog.Sinks.Email" />
    <add key="serilog:write-to:LiterateConsole"/>
    <add key="serilog:write-to:Email.mailServer" value="..." />
    <add key="serilog:write-to:Email.fromEmail" value="..." />
    <add key="serilog:write-to:Email.toEmail" value="..." />

    <package id="Serilog" version="1.5.9" targetFramework="net45" />
    <package id="Serilog.Sinks.Email" version="1.5.15" targetFramework="net45" />
    <package id="Serilog.Sinks.Literate" version="1.2.0" targetFramework="net45" />

**Comment by nblumhardt** [comment]
Thanks for the heads-up. Is any error written to `SelfLog`? (https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics)

**Comment by swjensen** [comment]
No, nothing gets written to SelfLog
When I put a Watch on Log.Logger after 
Log.Logger = new LoggerConfiguration().ReadFrom.AppSettings().CreateLogger();
only one sink is present, and it is always the sink from the second serilog:using key in AppSettings - in my example "Serilog.Sinks.Email". Switching the order of the using lines in app.config will cause the "Serilog.Sinks.Email" to be present in Log.Logger.

**Comment by nblumhardt** [comment]
Thanks for the follow up. I just realised what I overlooked. `<appSettings>` keys need to be unique; `serilog:using` is just a convenient short-form for when only one sink is configured. To configure more than one you need to make the keys unique:

```xml
<add key="serilog:using:Literate" value="Serilog.Sinks.Literate" />
<add key="serilog:using:Email" value="Serilog.Sinks.Email" />
```

HTH! :-)

**Comment by swjensen** [comment]
Ah - of course. Thanks:)

**Comment by merbla** [comment]
Updated the [wiki](https://github.com/serilog/serilog/wiki/AppSettings)
