### ISSUE TITLE
Are special folders supported in configuration file?

### ISSUE THREAD

**Issue by arteny** [serilog/serilog#520]
Is there way to point file to ApplicationData folder directly from configuration file like in nlog:
fileName="${specialfolder:folder=LocalApplicationData}/x/y.log

**Comment by nblumhardt** [comment]
Hi! Yes, you can use environment variable substitution, in this example "%LOCALAPPDATA%". Cheers!

**Comment by arteny** [comment]
This doesn't work:
			Log.Logger = new LoggerConfiguration()
			//.WriteTo.ColoredConsole()
			//.WriteTo.RollingFile(@"C:\Users\Alexey\AppData\Local\Maza\Log-{Date}.txt")
			.WriteTo.RollingFile(@"%LOCALAPPDATA%\Maza\Log-{Date}.txt")
			.CreateLogger();
When
			Log.Logger = new LoggerConfiguration()
			//.WriteTo.ColoredConsole()
			.WriteTo.RollingFile(@"C:\Users\Alexey\AppData\Local\Maza\Log-{Date}.txt")
			.CreateLogger();
works well.

**Comment by khellang** [comment]
> Is there way to point file to ApplicationData folder **directly from configuration file**

You asked if it was possible "directly from configuration file", i.e. AppSettings. This works.

The sinks don't expand envionment variables. That would make sense, though.

**Comment by arteny** [comment]
Yes, thanks
