### ISSUE TITLE
Specific section for file based configuration + mixed mode file/code

### ISSUE THREAD

**Issue by pardahlman** [serilog/serilog#526]
I just want to open up the discussion for configuring the sinks; I have a few ideas for improvement, but I haven't been around in this code base long enough to know if they are valid.

#### Mixed configuration: file and code
In the [wiki page for AppSettings](https://github.com/serilog/serilog/wiki/AppSettings) it is stated that

>You can mix and match XML and code-based configuration, but each sink must be configured either using XML or in code - sinks added in code can't be modified via app settings.

I prefer to do the configuration in code, but there are some things that should be configurable through configuration files, such as

* Log directory (typically different for local vs prod)
* Min log level (typically debug local and higher in prod)

It would be nice if the `.ReadFrom.AppSettings()` would take add or update sinks. Any thought on this?

#### File based config in seperate section
Imho, AppSettings is a place where application specific settings are made. A logging framework should have an own section (with possibility to move the section to to an external file like `Serilog.config`). As a bonus, we could have sections like `<Sink type="ColoredConsole">` with sub nodes - sweet hierarchy! _(At least a bit cleaner than the prefixed appsettings, right?)_ This could also be the place where #525 is configured.Perhapes like Log4Net does it?

     <mapping>
        <level value="FATAL" />
        <foreColor value="White" />
        <backColor value="Red, HighIntensity" />
     </mapping>

**Comment by nblumhardt** [comment]
Thanks for the detailed ideas. Some of this may be applicable to https://github.com/serilog/serilog-framework-configuration - any help you can provide over there would be hugely appreciated. The "classic" _System.Configuration_ system may not ever be supported on .NET Core, so making this kind of deep (very time-consuming) investment is unlikely right now.

**Comment by pardahlman** [comment]
Roger that, @nblumhardt! If everything goes my way, I'll have a few spare hours the coming week and so I'll be able to have a look at the `serilog-framework-configuration` project and see if I can help out. Thanks for pointing me in the right direction! _However_, the "mixed mode" (config files +code) would still be an outstanding issue, right?

**Comment by nblumhardt** [comment]
@pardahlman I think so, but not one I see us tackling in the near future. It's definitely in the back of my mind, but I'll close this while I don't think we're going to move forward. Thanks for all the input!
