### ISSUE TITLE
Logging full name for objects

### ISSUE THREAD

**Issue by rapoth** [serilog/serilog#527]
While logging an object, is there a way to write the full class name instead of the partial name that is written currently?

For instance,

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Serilog;

namespace SerilogSample
{
    class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.ColoredConsole().CreateLogger();
            Event e = new Event {Timestamp = DateTime.Now, Name="CustomEvent"};
            Log.Logger.Information("{@Event} {Type}", e);
            Console.Read();
        }
    }

    public class Event
    {
        public DateTime Timestamp { get; set; }
        public string Name { get; set; }
    }
}
```

This piece of code currently logs:

```
2015-09-09 08:53:18 [Information] Event { Timestamp: 09/09/2015 08:53:18, Name: "CustomEvent" }
```

However, I want to log:

```
2015-09-09 08:53:18 [Information] SerilogSample.Event { Timestamp: 09/09/2015 08:53:18, Name: "CustomEvent" }
```

**Comment by nblumhardt** [comment]
Sorry about the slow response on this. Yes, but only by plugging in a custom `IDestructuringPolicy` for the types in question (you'd need to add the full type name as an additional property on the created `StructureValue`).

I don't think we can address this in Serilog itself currently, will close for the time being but please reach out if you have more questions.
