### ISSUE TITLE
Email and MSSqlServer Sinks on Dnx 5

### ISSUE THREAD

**Issue by mdmoura** [serilog/serilog#528]
Hello,

Is any plan for email and mssqlserver sinks to suporte dnx 5?

Thank you,
Miguel

**Comment by merbla** [comment]
Hi @mdmoura, the foundation is over @ [Framework Logging](https://github.com/serilog/serilog-framework-logging).  As we do currently, the sinks will sit in their own repo.  

As for how the sinks will be upgraded and managed/supported with multiple versions that is yet to play out.  Feel free to submit a PR or if you have something in the works, would love to see how you are going.
