### ISSUE TITLE
Enhancement to Rolling File: Roll over by hour

### ISSUE THREAD

**Issue by ravensorb** [serilog/serilog#533]
It would be a nice enhancement to the Rolling File sink to support rolling over my hour instead of just by date.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. Rolling files get very complex and so the core project's one is deliberately simple to avoid getting pinned down by subtly incompatible sub-features.

There is an alternative at https://www.nuget.org/packages/Serilog.Sinks.RollingFileAlternate covering some additional scenarios, it may be a good place to consider this addition, or perhaps another similar fork?

Cheers!
Nick
