### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by MatthiasJost** [serilog/serilog#535]
Is the .NET Core migration already on the roadmap?

**Comment by khellang** [comment]
@MatthiasJost It's already sitting on the [dev-v2 branch](https://github.com/serilog/serilog/tree/dev-v2) :smile: I'm not sure what @nblumhardt has in mind when it comes to shipping it, though.

**Comment by MatthiasJost** [comment]
@khellang OK cool. I am still waiting for other libraries to be migrated. It looks like I need to wait a bit. The current version is ASP.NET 6 Beta 7. I guess it would be nice to have a "pre-release" package soon. I do not know when the release is expected.

**Comment by merbla** [comment]
@MatthiasJost if you are looking at ASP.NET, have you checked out the [Serilog repo/package](https://github.com/serilog/serilog-framework-logging) that will fit in with Microsoft.Framework.Logging

**Comment by MatthiasJost** [comment]
That looks very interesting. Saw that Framework.Logging once. Probably very interesting for me. Thank you @merbla.

**Comment by merbla** [comment]
@MatthiasJost an updated set of [packages](https://www.nuget.org/packages/Serilog.Framework.Logging/) are available.  Can this issue be closed?

**Comment by birarich** [comment]
I closed the issue...

But still we have to wait for serilog to run on dnx core 5.o?

**Comment by nblumhardt** [comment]
@birarich Serilog already runs on .NET Core 5.0 - just install the _Serilog_ package and you're good to go!

Its the (externally-shipped) sinks that need updating - the `dev-v2` branch is working towards providing all the APIs that the sinks use on all platforms that support them, so you will likely need to recompile any sinks you need from source.

Notwithstanding any major changes from .NET/ASP.NET (!!!) it is probably time for us to get the pre-release v2 package tidied up and pushed to NuGet so the sinks can start to be re-targeted too. Let's leave this issue open as a way to track it:

 - [ ] `PeriodicBatchingSink` for .NET Core (needs an issue#)
 - [ ] `ILogger` generic overloads and public `Logger` abstract base class with template method for implementors
 - [ ] Check/finalize v2 prerelease build numbering
 - [ ] Publish from _AppVeyor_

Anything else?

**Comment by birarich** [comment]
When I use serilog to write log into file it gives me error saying u cannot
write in file... as file method is obsolute.....

**Comment by nblumhardt** [comment]
Thanks - these sinks are not yet supported on core. Added an item to the list above :-)

**Comment by birarich** [comment]
Yes thanks...

**Comment by MatthiasJost** [comment]
Thank you guys for your support.

**Comment by npnelson** [comment]
@nblumhardt  I'm still trying to get my head around all the ramifications of ASPNET5, CoreCLR, UWP, etc, but I'm pretty sure that you want to replace all the DNXCore50/DNX451 references in project.json with DOTNET references (and any conditional compilation directives). Oren Novotny has a decent summary here (especially in the "Call to Action" section) 

https://oren.codes/2015/07/29/targeting-net-core/

**Comment by nblumhardt** [comment]
Hmm, was just in the process of creating a PR for this and pushed upstream (rather than to my fork) egads! Will try to get that sorted out now.

In good news, `PeriodicBatchingSink`, the tests, and an update to `beta8` are done. We should be able to get this onto NuGet soon.

**Comment by khellang** [comment]
We should move over to the new `netstandard` once it's supported. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md for details.

This issue is dependent on dotnet/corefx#4367 being completed.

**Comment by nblumhardt** [comment]
Hi all, to keep things manageable I've split the remaining tasks into individual issues under the v2 label. Shortly I'll open a PR from the v2 branch to dev, and after that is merged we can start crossing these off.

**Comment by nblumhardt** [comment]
See: https://github.com/serilog/serilog/labels/v2

**Comment by j2ghz** [comment]
What's the status with Colored and Literate console sink? I was redirected here from serilog/serilog-sinks-literate#4, this issue was split, but I don't see it anywhere.

**Comment by nblumhardt** [comment]
Hi Jozef, the literate console sink is still on the TODO list, sorry. Shouldn't be too far away.
