### ISSUE TITLE
ReadFrom.AppSettings() that takes NameValueCollection

### ISSUE THREAD

**Issue by JuanjoFuchs** [serilog/serilog#536]
```AppSettingsSettings.Configure(LoggerConfiguration loggerConfiguration)``` is accessing ```ConfigurationManager.AppSettings``` directly.

It would be helpful for projects that do not have ```ConfigurationManager``` available and want to use an **app.config** file like any other web or console project (http://stackoverflow.com/a/5191101/1277401), taking advantage of all the ```AppSettingsSettings``` features.

**Comment by nblumhardt** [comment]
Thanks for the issue and PR.

Just looking over your changes, it appears that `.ReadFrom.KeyValuePairs()` with the secondary configuration passed through should cover this scenario. What are the limitations there?

Many thanks!
Nick

**Comment by JuanjoFuchs** [comment]
The limitations I've found in ```.ReadFrom.KeyValuePairs()``` are: 

- It expects keys to not have ```serilog:``` as a prefix.
- It doesn't expand environment variables.
- You need to add explicit ```using:``` keys to use serilog's built-in sinks.

In other words, ```.ReadFrom.KeyValuePairs()``` expects a set of keys totally different from what you would use for ```.ReadFrom.AppSettings()``` and I am using the same ```app.config``` file, it's just that sometimes it's not available through ```ConfigurationManager.AppSettings```. 

So, as a user, I thought it would be more transparent if I could have the same set of features with the same set of inputs, but being able to chose how to load them from file. But then again, maybe there's another way to achieve this.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, makes sense. Is there a way to express the API more in terms of configuration files rather than `IDictionary<,>`? The dictionary makes the overlap with `KeyValuePairs` a little confusing - if the overload of `AppSettings()` took a secondary configuration file name as an argument the purpose of the API might be clearer. What do you think?

Just for the benefit of anyone searching for an interim solution (and so I could see it in all its ugly glory myself :-)) I've included the workaround version below:

```csharp
var settings = // Open the dictionary here
settings.Add("serilog:using:_BuiltInSinks", typeof(AppSettingsSettings).Assembly.FullName);

Log.Logger = new LoggerConfiguration()
  .ReadFrom.KeyValuePairs(settings
    .Where(kvp => kvp.StartsWith("serilog:")
    .ToDictionary(kvp => kvp.Substring(8), Environment.ExpandEnvironmentVariables))
  .CreateLogger();
```

**Comment by johnkattenhorn** [comment]
Would this workaround help me with an issue I was about to raise ? Azure Cloud Service Definition files does not like:

`<Setting name="serilog:minimum-level" />`, it errors with

`Name is invalid, The value "serilog:minimum-level" is invalid according to it's data type`

Removing the colon (:) makes it valid again.

**Comment by nblumhardt** [comment]
Hi @johnkattenhorn - yes, sounds like you may be able to get around it that way. Let us know how you go!

**Comment by caioproiete** [comment]
If it helps, here is working example of using the `KeyValuePairs` (lines [25](https://gist.github.com/caioproiete/95144d6252aaed477c15#file-appsettingssettings-cs-L25) to [34](https://gist.github.com/caioproiete/95144d6252aaed477c15#file-appsettingssettings-cs-L34))

https://gist.github.com/caioproiete/95144d6252aaed477c15

**Comment by johnkattenhorn** [comment]
Thanks @caioproiete for the gist, very helpful.

**Comment by johnkattenhorn** [comment]
I put together a PR #581 which allows you to override the default delimiter ":" to make it more Azure ServiceConfiguration friendly, passes the Unit Tests and Smoke Test and I plan to try it for real over the weekend on a project.

**Comment by nblumhardt** [comment]
Hi all - I think it's more likely we'll get traction on this through serilog/serilog-extensions/configuration, happy to reopen here if this is a major pain point for anyone, but keen to focus our efforts on the newer configuration APIs for cases where System.Configuration is not present.
