### ISSUE TITLE
CLS compliance

### ISSUE THREAD

**Issue by stephendrew** [serilog/serilog#538]
Hello,
Great work - I really like this library.
I was wondering if it is possible to mark the assembly as CLS compliant?
Thanks

**Comment by nblumhardt** [comment]
Hi Stephen, thanks for the note. I don't think there are any issues with this, but I'd be interested to know the scenario - what requires `[ClsCompliant]` in order to make use of Serilog? Thanks!

**Comment by stephendrew** [comment]
Hi Nicholas,

I don't think there are any issues presently because it's lacking or will be any if you add the attribute to your assembly info.  

We aim to build all our libraries as CLS compliant: by introducing Serilog at a low level in the chain, it has forced us to cascade turning compliance off through all the projects, in all the builds etc...

If your code is already CLS compliant there should be no harm in marking it as such.

Thanks
Steve

**Comment by nblumhardt** [comment]
Thanks for the follow-up Stephen. Sounds reasonable - marking this one as `up-for-grabs`. Cheers!
