### ISSUE TITLE
Support for .NET 4.0

### ISSUE THREAD

**Issue by NikolaR** [serilog/serilog#54]
It would be possible to support .NET 4.0 by moving IObservable/IObserver to separate project, and removing dependencies to IReadOnlyList and IReadOnlyDictionary.

I'm forced (by corporate rules and a complaint) to downgrade a project to .NET 4.0 so I had to drop Serilog for now.

**Comment by jho1965us** [comment]
Is there any chance of reopening this?

**Comment by nblumhardt** [comment]
Hi @jho1965us - no, no chance as of Serilog 2.0. But, Serilog 1.5 does support .NET 4.0 - any problems with using the 1.5 version for this?

Cheers,
Nick

**Comment by jho1965us** [comment]
Hi Nick

I will take a look at version 1.5

Thanks 
Jens

**Comment by mmassari** [comment]
With our company we have the same problem, stuck in .net 4.0 framework for many other years.
The thing is .net40 is the latest framework possible to run .net application in windows xp. And winXP despite the end of support  by Microsoft is still alive in the retail world. We have 800 shops (with about 3000 computer) all around the world used for point of sale and no way we can upgrade all of them till they works. 
It's a pain work in such a old framework missing all that great features of the newest framework (await/async overall) and all the great libraries that not support old frameworks. But it's life... 
For logging now we are stuck in log4Net and we hope to move to serilog... 
I will try with version 1.5 if it fit our needs. 
Bye
