### ISSUE TITLE
Missing provided Sinks

### ISSUE THREAD

**Issue by alvinmeimoun** [serilog/serilog#541]
Hi,

I added serilog from Nuget Package Manager (tried in a PCL and a Windows Store Apps 8.1 project), but some provided sinks are missing (I need write log in a txt file, but RollingFile and File are missing).

I'm using serilog v 1.5.11

![VS Autocomplete](https://cloud.githubusercontent.com/assets/3252195/10248411/a848f02c-691f-11e5-8f56-c2c430d7c165.png)

**Comment by khellang** [comment]
AFAIK the file sinks etc. are not available as part of the PCL targets. They're a part of the Serilog.FullNetFx.dll, which is only referenced for the `net40` and `net45` targets.
