### ISSUE TITLE
serilog-sink-ravendb with datetime in structured data

### ISSUE THREAD

**Issue by wwwlicious** [serilog/serilog#547]
It looks like the ToString() method is called on DateTime properties in any structured data passed to the ravendb sink. Also the rendered message vs the structured data is not consistent in using the CultureInfo of the thread as one is dd/MM/yyyy and the message is MM/dd/yyyy.

By default ravendb logs DateTime as UTC which happens for the timestamp on the LogEvent object. 

The EventTime is a DateTime property and should IMO be stored in ravendb the same as the Timestamp property in the LogEvent.

```javascript
{
  "Timestamp": "2015-10-20T11:30:48.1397014+01:00",
  "MessageTemplate": "{@stat}",
  "Level": "Information",
  "Exception": null,
  "RenderedMessage": "Stat { EventTime: 09/18/2013 17:50:41 }",
  "Properties": {
    "stat": {
      "EventTime": "18/09/2013 17:50:41",
    }
  }
}
```

I've tried to override this behaviour using a destructuring function but it has no effect on the above eventlog document in ravendb.

```csharp
var logs = new DocumentStore { Url = "http://localhost:8080/",  DefaultDatabase = "TestDb" }.Initialize();
var logger = new LoggerConfiguration()
                .Destructure.ByTransforming<DateTime>(d => d.ToUniversalTime())
                .WriteTo.RavenDB(logs).CreateLogger();
```

**Comment by nblumhardt** [comment]
Hi Scott,

Rather than configure destructuring for `DateTime`, which Serilog treats as scalar and thus does not apply custom policies to, you can configure logging for the owning type:

```csharp
.Destructure.ByTransforming<Stat>(s => new { EventTime = s.EventTime.ToUniversalTime() })
```

HTH,
Nick
