### ISSUE TITLE
TargetInvocationException exception

### ISSUE THREAD

**Issue by birarich** [serilog/serilog#548]
I'm using VS 2015 console application with DNX core 5.0 and DNX 4.5.1, when I installed "Serilog 1.0.0-beta6-10052" I got TargetInvocationException exception: "An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll".
Any idea why it is like this?

**Comment by nblumhardt** [comment]
Hi there - if you include the full exception details (just ToString() the exception so that stack trace/inner exceptions are shown) we should be able to figure it out. Cheers!

**Comment by birarich** [comment]
Also another issue, whenever I try to configure Serilog to write to a file it gives me such compile error:

'LoggerSinkConfiguration' does not contain a definition for 'File' and no extension method 'File' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing a using directive or an assembly reference?)	MyProject.API.DNX Core 5.0	

Serilog does not support DNX Core 5.0?
