### ISSUE TITLE
update elasticsearch sink's template

### ISSUE THREAD

**Issue by Mpdreamz** [serilog/serilog#549]
Quite a few changes have gone in to our reference logstash template.

See also: https://github.com/untergeek/logstash-output-elasticsearch/blob/fix/275/lib/logstash/outputs/elasticsearch/elasticsearch-template.json 

and this PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/276

Opening this ticket as a working item for myself when I get some cycles to spend on it. If someone else wants to jump on this be my guest!

**Comment by nblumhardt** [comment]
This one's been around a while - still needed @Mpdreamz ?

**Comment by nblumhardt** [comment]
Moved to: https://github.com/serilog/serilog-sinks-elasticsearch/issues/26 (see #450)
