### ISSUE TITLE
Log a byte array

### ISSUE THREAD

**Issue by worldspawn** [serilog/serilog#553]
Hi,

I have a specific need to include a byte array in one class's destructured output. So I do not need it for all byte arrays, just this one _special_ byte array. How can I do that?

**Comment by nblumhardt** [comment]
Hi Sam, can you wrap the `byte[]` in a marker type, i.e.:

```csharp
class SpecialBytes
{
    public byte[] Data { get; set; }
}

Log.Logger = new LoggerConfiguration()
    .Destructure.ByTransforming<SpecialBytes>(b =>
        new { Data = Convert.ToBase64String(b.Data) })
    .CreateLogger();

var bytes = new SpecialBytes { Data = ... };
Log.Information("Here are the {@SpecialBytes}", bytes);
```

There are a few variations on that theme (custom `IDestructuringPolicy` being the next option with more flexibility).

**Comment by worldspawn** [comment]
Hi. 

I dont really want to modify my class structure to suit my chosen logging framework (beyond adding a few attributes).

I tried to create a destructuring policy but it seems to only be used to destructure what was passed in to the log call and not its members. What would be _nice_ is if I could swap out or otherwise manipulate the scalar conversion policy list but it's built up in memory - https://github.com/serilog/serilog/blob/df7ad3220b44476b9cd4f06072b0dcb797ea4dfd/src/Serilog/Parameters/PropertyValueConverter.cs#L57

Does the scalar conversion policy have any way to access the member info for the property its converting (where there is a property)? It'd be nice if I could just plop an attribute on that property telling it not to munge the value.

For the moment I'll probably just make a destructuring policy dedicated to the type my byte array is in.

**Comment by nblumhardt** [comment]
:+1:
