### ISSUE TITLE
Restrict http logging to uri's that match one or patterns.

### ISSUE THREAD

**Issue by worldspawn** [serilog/serilog#554]
I have a webapi website that also serve some static files. I dont have any interest/desire to log ppls requests for `app.js` or whatever but any and all requests to `/api/*` would probably be handy to have logged. Is there a way to configure ApplicationLifecycleModule to do something like that?

**Comment by nblumhardt** [comment]
(Probably belongs in https://github.com/serilog-web/classic.)

No, though I know the clutter you're talking about. Not sure what the best way to solve this is - there's a bit of a danger of undirected feature bloat in `ApplicationLifecycleModule`, but open to ideas.

**Comment by worldspawn** [comment]
What I've done in the mean time is copy paste ur source and added an `if`. 

What if the ApplicationLifecycleModule maintained a list of predicates applied against the request that it had to pass before logging the request. The the user can call something like:

`ApplicationLifecycleModule.RequestPredicates.Add(r => r.Url.AbsolutePath.StartsWith("/api"))`

then (from line 162)

```
var request = HttpContextCurrent.Request;
if (request == null || !RequestPredicates.Any(p=>p(r)))
    return;
```

**Comment by nblumhardt** [comment]
Thanks for the follow up. Closing this here, will continue the discussion over on the PR in serilog-web. Cheers!
