### ISSUE TITLE
Custom JSON serializers for custom types.

### ISSUE THREAD

**Issue by drusellers** [serilog/serilog#558]
I use a large number of "custom types" in my code bases that do nothing more than wrap primitives to give them more meaning. So, a `decimal` becomes `Quantity`, and `int` becomes a `Sku`. When I do this though I'm not seeing my values written to the JSON stream

So, instead of

```
"UnitOfMeasure": {
    "_typeTag": "UnitOfMeasure",
    "PrimitiveValue": "EA"
}
```

or

```
"UnitOfMeasure": "EA"
```

I get

```
"UnitOfMeasure": {
    "_typeTag": "UnitOfMeasure"
}
```

---

Now I don't expect to get option 2 out of the box, I have also written a JsonConverter (ala JSON.Net) for each of my primitive types and would love to be able to leverage that some how as well. If I need to write custom ones for Serilog that would be ok too.

Thank you.

**Comment by IanYates** [comment]
I have some similar classes in my code and they're behaving OK with Serilog & Seq.

What sink are you using (looks like Elastic Search in your other question)?  If you use the literate console, or the colored console, do you see the expected values?

Also, how is the primitive value exposed?  Is UnitOfMeasure something like
```
public class UnitOfMeasure
{
    private readonly string primitiveValue;
    public UnitOfMeasure(string primitiveValue)
    {
        this.primitiveValue = primitiveValue;
    }

    public string PrimitiveValue { get { return this.primitiveValue; } }
}
```
(or perhaps using the shorter C# 6 syntax)?

**Comment by iamkoch** [comment]
Could you paste the class?

In some cases the serializer requires a public setter for properties.

**Comment by nblumhardt** [comment]
@drusellers any update on your progress with this one?

**Comment by drusellers** [comment]
I'm currently out of the country and will provide more detailed feedback in a week or so when I am back. 



—

**Comment by drusellers** [comment]
Here you go. :)

https://gist.github.com/drusellers/358755dd570ec823b200

**Comment by drusellers** [comment]
@iamkoch @nblumhardt any thoughts? :)

**Comment by nblumhardt** [comment]
Sorry @drusellers - I should have spotted this earlier. What you need is either:

```csharp
    .Destructure.AsScalar<UnitOfMeasure>()
```

or using destructurama/attributed:

```csharp
[LoggedAsScalar]
public class UnitOfMeasure : // ...
```

and:

```csharp
    .Destructure.UsingAttributes();
```

This will give you strings in Elasticsearch, like `"EA"`.

Given you have a few of these, plugging in a custom `IDestructuringPolicy` is the way to go. (The almost-empty output is due to there being no public properties to serialize on `UnitOfMeasure`.)

How's this go for you?

**Comment by drusellers** [comment]
This worked great! Thank you.

**Comment by nblumhardt** [comment]
Awesome, thanks for closing the loop.

**Comment by adamjones2** [comment]
Hi @nblumhardt, I have the same use case but sometimes the wrapped primitives of mine get logged as dictionary keys. It looks like `[LogAsScalar]` doesn't get picked up by Serilog though to tell it that a dictionary can have the custom JSON object serialisation of `{ "key1": "value1", ... }` when it's a key, like other scalar types do, and instead it tries to destructure dictionaries as a list of key-value pairs. That is,
```
var log = new LoggerConfiguration()
    .Destructure.UsingAttributes()
    .WriteTo.Console()
    .CreateLogger();

var wrappedKey = new Dictionary<Wrapper, int> { [new(1)] = 4, [new(2)] = 5 };
var wrappedValue = new Dictionary<int, Wrapper> { [1] = new(4), [2] = new(5) };

log.Information("Structured, Wrapped key: {@Dictionary}", wrappedKey);
log.Information("Structured, Wrapped value: {@Dictionary}", wrappedValue);
log.Information("Unstructured, Wrapped key: {Dictionary}", wrappedKey);
log.Information("Unstructured, Wrapped value: {Dictionary}", wrappedValue);

[LogAsScalar]
record Wrapper(int Value)
{
    public override string ToString() => Value.ToString();
}
```
prints
```
Structured, Wrapped key: [{"Key": "1", "Value": 4, "$type": "KeyValuePair`2"}, {"Key": "2", "Value": 5, "$type": "KeyValuePair`2"}]
Structured, Wrapped value: {"1": "4", "2": "5"}
Unstructured, Wrapped key: ["[1, 4]", "[2, 5]"]
Unstructured, Wrapped value: {"1": "4", "2": "5"}
```
When the value type of the dictionary is wrapped it works, but when the key type of the dictionary is wrapped it does not (I would expect to see the same as the `Wrapped value` cases). This seems like a bug to me, but is there a way I can make it behave the way I expect if not (or if so, as a workaround until a fix is implemented)?
