### ISSUE TITLE
An unconfigured logger should be "off"

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#560]
It's surprising that instead of an "off" logger, the following:

```csharp
new LoggerConfiguration().CreateLogger()
```

returns an `Information`-level logger with no sinks. The performance of this is not comparable to a truly disabled logger.

If no sinks are configured for a logger configuration, an instance of the (internal) `NullLogger` class should be returned from `CreateLogger()`.

**Comment by horsdal** [comment]
I can't find a `NullLogger`. Did you mean `SilentLogger`, maybe?

**Comment by merbla** [comment]
@horsdal are you happy to pick this one up?

**Comment by horsdal** [comment]
yep. The checks on my PR failed. I'll get it fixed.
