### ISSUE TITLE
Question: Sink to use when using Serilog on ASP.NET 5

### ISSUE THREAD

**Issue by kichalla** [serilog/serilog#569]
I am using Serilog's ASP.NET 5 framework logging in one of my projects. As you know, ASP.NET 5 logging has concept of scopes where a particular log message could be part of a deep scope (ex: RequestId scope -> Action 'blah' execution scope -> Product 'p1' scope etc.). So every log message could be part of a different scope hierarchy depending on where the code is trying to log.

What would be your suggestion regarding which sink to use for this scenario? `Azure DocumentDB` or `Azure Table Storage with properties`?

I tried using `Azure Table Storage with properties` but since each log message can have different scope hierarchy, logging into table storage seems to be creating `columns` where data can be null, so I think is not the one I should use. Probably AzureDocumentDb?

cc @nblumhardt

**Comment by nblumhardt** [comment]
Hi Kiran! :-)

I think overall DocumentDB sounds like a more interesting data store, if your options are those currently available on Azure. I haven't personally spent any time with it, so unfortunately I may not be able to offer much more info.

@robdmoore built the original Table Storage and DocumentDB sinks; - Rob, any thoughts on this?

**Comment by robdmoore** [comment]
What kind of querying do you need to perform on the logs?

Document db is going to make your life easier in that regard, but it's more expensive than table storage.

**Comment by kichalla** [comment]
@nblumhardt @robdmoore Thanks! for the prompt responses. At this moment, my queries are going to very simple. I will try to use DocumentDb.
