### ISSUE TITLE
[AzureDocumentDb sink] Provide an extension method which takes in a connection string

### ISSUE THREAD

**Issue by kichalla** [serilog/serilog#573]
Currently we have only one extension method which takes in the endpoint Uri and account key. Would be helpful if we could have an additional extension accepting a connection string.

https://github.com/serilog/serilog-sinks-azuredocumentdb/blob/master/src/Serilog.Sinks.AzureDocumentDb/LoggerConfigurationAzureDocumentDbExtensions.cs#L40

The connection string is of the format: `AccountEndpoint=<>;AccountKey=<>;`
I will be happy to send out a PR :-)

**Comment by nblumhardt** [comment]
cc @robdmoore 

This sounds good to me.

**Comment by robdmoore** [comment]
+1

**Comment by nblumhardt** [comment]
@kichalla and co, I'm tidying up the tracker - I don't think we need to maintain an issue for this (everyone seems in favour of the change). I'll close this up and leave things to the PR process :-)
