### ISSUE TITLE
Support fixed-length level output for OCD goodness

### ISSUE THREAD

**Issue by iamkoch** [serilog/serilog#574]
I spotted and subsequently tweeted Nick regarding seeing INF, DBG and other shortened levels in output logs to be told that it's only in certain sinks at the moment and that bringing this into the main codebase might be nice...

...so that's what I did. PR coming. Happy for feedback re approach.

I've opted for a dumber inclusion of "Lvl" as a template variable instead of allowing Level:3 / Level:4 or similar as I felt it had the smallest impact on the codebase and limited the wishlist for custom words or text, different interpretations of whether it should be DEB, DEBG, DBUG etc.

**Comment by nblumhardt** [comment]
Completed via the linked PR :tada:
