### ISSUE TITLE
Configure Splunk sink from app settings

### ISSUE THREAD

**Issue by danielwertheim** [serilog/serilog#577]
The Splunk sink repo has no issues support so I guess all Q should go here....

Is there no way to configure the Splunk sink using appsettings?

**Comment by merbla** [comment]
Hey @danielwertheim!

Which sink within Splunk are you targeting?

**Comment by danielwertheim** [comment]
Tcp

**Comment by danielwertheim** [comment]
@merbla there obviously is no rush, as you can build this your self.

**Comment by merbla** [comment]
@danielwertheim will have a look.  I am sure I had something working however it might have been with 6.3 and event collector

**Comment by danielwertheim** [comment]
For me this would be more important: 

https://github.com/serilog/serilog-sinks-splunk/pull/8

**Comment by nblumhardt** [comment]
@merbla is this one still valid?

**Comment by nblumhardt** [comment]
Moved to: https://github.com/serilog/serilog-sinks-splunk/issues/10 (see #450)
