### ISSUE TITLE
Splunk, inject custom message formatter

### ISSUE THREAD

**Issue by danielwertheim** [serilog/serilog#578]
If you open up for injecting custom message formatter, then e.g.  `MessageTemplateTextFormatter` could be used which might be good if a company is using other loggers that reaches splunk that is not JSON formatted.....

**Comment by danielwertheim** [comment]
@merbla any thoughts on this and the PR?

**Comment by merbla** [comment]
@danielwertheim Thanks again for the PR! let me know how you go!

**Comment by merbla** [comment]
@danielwertheim do you think it is worth updating the wiki?  It is a bit bare.

**Comment by danielwertheim** [comment]
Might be good to document a sample use-case of why you would inject a formatter of choice. I'll see if I get to it.

**Comment by danielwertheim** [comment]
@merbla here is something at least showing the possibilities: https://github.com/danielwertheim/serilog-sinks-splunk/wiki/Test

Copy that page (or parts) if you like.
