### ISSUE TITLE
NullReferenceException in RollingFileSink

### ISSUE THREAD

**Issue by konste** [serilog/serilog#579]
RollingFileSink is very old and supposed to be stable, but to my surprise I consistently hit NullReferenceException in it. The following code looks suspicious:
  public void Dispose()
        {
            lock (_syncRoot)
            {
                if (_currentFile == null) return;
                CloseFile();
                _isDisposed = true;
            }
        }

        void CloseFile()
        {
            _currentFile.Dispose();
            _currentFile = null;
            _nextCheckpoint = null;
        }

Dispose checks _currentFile for null, but Dispose is called from CloseFile through _currentFile, which may be null! And it is not theoretical possibility - I really see that happening from time to time, I just never had time to figure exact repro scenario. 

The fix should be trivial though.
Konstantin

**Comment by nblumhardt** [comment]
Hi Konstantin,

Thanks for the report are you able to collect a stack trace when you observe this?

All the best,
Nick

**Comment by nblumhardt** [comment]
Cancel that; found the issue, will fix directly on `dev` for the release I'm about to cut.
