### ISSUE TITLE
ByIncludingOnly not working for sublogger

### ISSUE THREAD

**Issue by jnus** [serilog/serilog#583]
Trying to mimic Log4Net configuration where you can set both minimum and maximum log level. Hence serilog only exposes the MinimumLevel option, I using a sublogger and configuring by using ByIncludingOnly to only log Debug messages in this particular RollingFile sink. However I cannot seem to get this working.

```            
var baselogger = new LoggerConfiguration()
                 .WriteTo.Logger(fileLogger => fileLogger
                        .Filter.ByIncludingOnly(p => p.Level.Equals(LogEventLevel.Debug))
                        .WriteTo.RollingFile(@"c:\log\debug.log",
                            LogEventLevel.Debug, FileOutputFormat, null, 15000000 /*15MB*/, 10));

            return baselogger.CreateLogger();
```

Nothing is ever logged by this sublogger - RollingFile sink of course works as a root logger, including Filter.ByIncludingOnly, but not as a sublogger.
Any hints on what I'm missing? Workaround for logging only certain levels to a file?

**Comment by nblumhardt** [comment]
Sub-loggers only receive events that are actually emitted by the parent logging pipeline; so in this case you would need:

```csharp
var baselogger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Logger(fileLogger => fileLogger
        .Filter.ByIncludingOnly(p => p.Level.Equals(LogEventLevel.Debug))
        .WriteTo.RollingFile(@"c:\log\debug.log",
            fileSizeLimitBytes: 15000000 /*15MB*/,
            maxRetainedFileCount: 10));

return baselogger.CreateLogger();
```

You can then use the `restrictedToMinimumLevel` parameter on any sinks you configure for the root logger, if you don't want the root logger to emit debug-level events.

Hope this helps!

**Comment by jnus** [comment]
Ok, sample was cut down a little too much. I would expect the following to emit Debug logs into 'c:\log\debug.log, however only 'c:\log\all.log' is created and messages written:

```
 var baselogger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.RollingFile(@"c:\log\all.log")
                .WriteTo.Logger(fileLogger => fileLogger
                    .Filter.ByIncludingOnly(p => p.Level.Equals(LogEventLevel.Debug))
                    .WriteTo.RollingFile(@"c:\log\debug.log"));
 
  baselogger.CreateLogger().Debug("Test");
```

Tried with both Serilog 1.5.14 and 1.4.204

**Comment by nblumhardt** [comment]
Ah, sorry Jasper. Got it:

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Console()
    .WriteTo.Logger(fileLogger => fileLogger
        .MinimumLevel.Debug()
        .Filter.ByIncludingOnly(p => p.Level.Equals(LogEventLevel.Debug))
        .WriteTo.Console())
    .CreateLogger();

Log.Debug("Test");
Log.Information("Hello!");
```

Prints:

```
2015-11-19 08:13:31 [Debug] Test
2015-11-19 08:13:31 [Debug] Test
2015-11-19 08:13:31 [Information] Hello!
```

The problem is that the default level of the nested logger is `Information`, not inherited from its parent. The working example has an additional `MinimumLevel.Debug()` in there.

Not sure what the right approach for Serilog to take is here, it doesn't seem quite right but there are challenges with orchestrating "inheritance" of the outer logger's level as well. Interested to hear your thoughts.

**Comment by nblumhardt** [comment]
Anyone think we can/should tackle this one? I'm otherwise thinking the cost/benefit trade-off is stacked against it right now.

**Comment by jnus** [comment]
Not a huge problem from my point of view, since there's a workaround - So maybe just update the documentation about this known misbehavior, regarding sub-loggers and missing level inheritance would be sufficient.

**Comment by nblumhardt** [comment]
Done, thanks: https://github.com/serilog/serilog/wiki/Provided-Sinks#logger
