### ISSUE TITLE
Serilog destructuring generated message contracts is not supported

### ISSUE THREAD

**Issue by fhisashi** [serilog/serilog#584]
It seems that the serilog cannot deconstruct classes (contracts messages) automatically generated by Visual Studio when a service reference is added.
The object is empty.

![image](https://cloud.githubusercontent.com/assets/3601750/11221171/d10ab334-8d4a-11e5-9e94-562d3223ee68.png)

**Comment by nblumhardt** [comment]
Hi, and thanks for the note! Serilog only inspects _properties_, while message contracts like this generate public _fields_. It's possible to write a custom `IDestructuringPolicy` to handle this (there are quite a few examples here: https://github.com/destructurama) - feel free to reach out here or on https://jabbr.net/#/rooms/serilog if you have trouble. Cheers!
