### ISSUE TITLE
Package factoring

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#593]
The "new .NET" has switched to much finer-grained packages as the norm. _Serilog.nupkg_ is currently the "kitchen sink"; since v2 is breaking now is the time to consider a finer-grained factoring.

* _Serilog.Abstractions_: `ILogger`, `Log`, `LogContext`, `LogEvent`, `LogEventLevel`, the various property/value classes; everything potentially used by client application code
* _Serilog_: `LoggerConfiguration`, the pipeline; depends on _Serilog.Abstractions_
* Sink packages for: file, rolling file, console, colored console, trace, observable, periodic-batching
* Enricher packages: environment, ...
* Packages for AppSettings and so-on

The advantage of doing this is reducing churn (no need to version core assemblies as sinks evolve, etc.) and prevention of bloat, especially dependency bloat as will be the case with v2 as it stands currently.

There's a lot of work represented in this, but better to have the discussion while there's an opportunity to make the change.

**Comment by merbla** [comment]
+1.

The file, rolling file, console etc. lived in core for convenience.  With the next version of .Net it seems the approach is to break these down. 

There is a fine line between 1000s of packages and decoupled design.

We need to be wary over the long term of Package **Bloat** vs Package **Explosion** :boom: however I think the benefits are there.

**Comment by khellang** [comment]
I like this. Especially the Serilog/Serilog.Abstractions split. Most libraries in an application only care about the `ILogger` and friends :+1:

**Comment by caioproiete** [comment]
:+1:

**Comment by merbla** [comment]
Might have gone overboard but is this the idea?
[XML Gist for Draw.IO](https://gist.github.com/merbla/5961d474ec90cba3df9b)
![](https://raw.githubusercontent.com/merbla/images/master/serilog/SerilogV2.png)

**Comment by khellang** [comment]
I'd move the types listed below in Serilog.Abstractions and flip things so enrichers, configuration and sink packages depend on that instead.

- `ILogEventSink`
- `PeriodicBatchingSink`
- `ILoggerSettings`
- `ILogEventEnricher`
- `ILogEventPropertyFactory`
- `LogEventProperty`
- `LogEventPropertyValue`

I might've forgotten some...

**Comment by merbla** [comment]
Yep thanks @khellang.  Was initially thinking about packages rather than the actual class structure.

Updated...

![](https://raw.githubusercontent.com/merbla/images/master/serilog/Serilog%20v2.0.1.png)

**Comment by nblumhardt** [comment]
Just thinking - after the split, maybe the _AppSettings_ feature needs a bit more in the way of smarts to locate assemblies... I.e.

```xml
<add key="serilog:write-to:RollingFile.pathFormat" value="..." />
```

should implicitly load _Serilog.Sinks.RollingFile_ rather than require a `serilog:using:` setting (the assembly can be inferred from the name.

RE the package layout, I think the revised diagram makes sense; I would probably exclude `PeriodicBatchingSink` from that list and put it in its own package, since it's something I think we could make massive improvements on (or even redesign entirely) in the future.

`ITextFormatter` and `JsonFormatter` are used by some sinks, but for the same reasons we might want to put the implementations (`JsonFormatter` at least) in separate packages.

Last thought... :-) .... can we keep these all in the same repository for a start, or is it worth taking the pain and splitting them out? I'm inclined to think keeping them together would be okay for the initial 2.0, then slowly we'd evict/split out packages as that made sense...

**Comment by merbla** [comment]
Keep them in the same repo for now.  I just think we need to solve the current issue of when a merge occurs all packages in the repo will get versioned.  e.g. we may only want to bump one package.

**Comment by merbla** [comment]
Might need some help on this one.  Gonna have a crack at this one.

**Comment by caioproiete** [comment]
@merbla: I'd be happy to help. Let me know which one(s) you'd like me to work on.

**Comment by nblumhardt** [comment]
Awesome! It's a monster, so please yell if you need any help :-) :+1:

**Comment by merbla** [comment]
Gonna attack this one as follows.

- [ ] Add Abstractions project/library
- [ ] Ensure Build package working
- [ ] Migrate from Serilog core to abstractions
- [ ] Migrate from Serilog to new configuration projects 
- [ ] Migrate from Serilog to new enrichers projects
- [ ] Migrate from Serilog to new sink projects

**Comment by merbla** [comment]
Initial stub over [here](https://github.com/merbla/serilog/tree/patchingfactoring-abstractions) just playing with a few ideas and need to make sure package dependencies are correct.

**Comment by merbla** [comment]
@caioproiete might grab your help to do the sinks & enrichers projects.  Just want to finalise the abstractions first.

**Comment by caioproiete** [comment]
@merbla sounds good. Just give me a shout when the abstractions is good.

**Comment by merbla** [comment]
After pausing #602 going to change direction and start splitting:

 - sinks
 - enrichers/environment
 - app settings

@nblumhardt we can still work out what makes sense to do re: abstractions when some of the noise from the sinks etc. is gone.

**Comment by nblumhardt** [comment]
Great - :+1: @merbla

**Comment by merbla** [comment]
@khellang @nblumhardt just an FYI, I am going to do a large PR for the remaining sinks now we one vetted.

**Comment by nblumhardt** [comment]
Here's what I think is remaining on this (@merbla is already forging ahead on 1.):

1. Enrichers to their own package(s): `ThreadId`, `ProcessId`, `MachineName`, `EnvironmentUserName`
2. AppSettings support to its own package
3.  `FromLogContext()` can be made a first-class member of `LoggerEnricherConfiguration` since it's well and truly baked into core now
4. `*Extensions` will then be completely empty in the core package and can be deleted (#592)

I think the question of enricher package factoring is still out there (one vs multiple) packages but the rest seems straightforward. I'll PR 2. & 3. now.

**Comment by nblumhardt** [comment]
Two PRs ready to go :+1:

**Comment by merbla** [comment]
@nblumhardt I will rebase and push the enrichers PR.

**Comment by merbla** [comment]
@nblumhardt re: 1. 

FYI I have combined `MachineName` &  `EnvironmentUserName` in the same package.

**Comment by nblumhardt** [comment]
:fireworks:
