### ISSUE TITLE
Is there way to by-pass the template caching pipeline?

### ISSUE THREAD

**Issue by prasannavl** [serilog/serilog#594]
Hi, 

In many cases, we just want to log messages, and not templates. Is there a way to do without incurring the performance overhead?

Disclaimer: I'm returning to Serilog after a long time. The last I checked perhaps, a year or more ago was to use a standard template say `Log.Information("{Message}", message)` - which was kind of a big deal while logging in hotspots on IOT devices where this performance was critical. I'm wondering is there a better way, or is scenario still quite the same?

**Comment by nblumhardt** [comment]
Hi Prasanna! The technique you've described is still the one. I don't think there should be any significant perf cost of using the standard template approach - how's it looking? Cheers!

**Comment by prasannavl** [comment]
Cool. Guess, the only 'inconvenience' would be to use a few extension methods to hide this detail. 

Seems a little workaround-ish when using the new vNext interfaces. Would be nice if there was a way to do this internally. :)

**Comment by IanYates** [comment]
Extension methods being something like InfoRaw, WarnRaw, etc   (or InformationRaw, WarningRaw, etc) perhaps?  They could take a string parameter and nothing else.  Wouldn't hurt to include in Serilog from the point of view of steering people away from logging completely raw strings that might arise from some third party library output.

**Comment by prasannavl** [comment]
Yes, that's how I'm using it. 

Only, I call it `InfoText`, `WarnText` instead of the `Raw` suffix, because its not really raw - its infact the opposite :)

**Comment by prasannavl** [comment]
@nblumhardt  - As I see it, even though Extension methods help to do this, there's really no way to integrate this into Asp vNext's logging interfaces. 

Because then it always has to end up with ugly `Log.Information("{0}", message)` to make this happen. And while loggers can be forced to use a custom adapter that uses text only, this becomes rather difficult since it limits current logger heavily making the crux of serilog unusable. Adding extension methods to vNext's `ILogger` also destroys the point using those interfaces in the first place. 

Is there any suggestion from your side to do this without having to use Serilog's interfaces directly?

**Comment by nblumhardt** [comment]
Hi Prasanna,

ASP.NET vNext supports the Serilog syntax natively, so you can just write:

```csharp
logger.LogInformation("Hello, ASPNET5 from {Name}!", "Nick");
```

and whether you're using Serilog as the back-end, or something else, this will "just work" (TM).

Let me know if I've misunderstood!

Cheers :-)
