### ISSUE TITLE
Rename/incorporate Serilog.Framework.Logging

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#595]
https://github.com/serilog/serilog-framework-logging is maturing in line with ASP.NET 5 and needs to have first-class consideration in our v2 plans.

* Find a new name for the package, now that it's dependency has been renamed _Microsoft.Extensions.Logging_
* Line it up with the repository/project structure that comes out of #593 

Name ideas anyone? _Serilog.ExtensionsLoggingProvider_?

**Comment by khellang** [comment]
If MS could start coming up with some cool names for their frameworks, [like Facebook](https://code.facebook.com/projects/), instead of those horrible namespaces, our lives would be much easier. Just *<awesome-framework-name>.Serilog* :wink:

**Comment by nblumhardt** [comment]
Being left with such awful options, I wonder if we shouldn't revisit _Microsoft.Framework.Logging.Serilog_ anyway. Seems that the NLog sample has kept that name, so I suppose there's precedent. Thoughts?

**Comment by khellang** [comment]
I've been thinking the same. I mean, what are they expecting? Have we heard from MS? What are they saying in terms of 3rd party packages being named Microsoft.*?

**Comment by merbla** [comment]
Elmah has gone a different approach - https://www.nuget.org/packages?q=Microsoft.Framework.Logging

**Comment by nblumhardt** [comment]
Guys, Autofac went with _Autofac.Extensions.DependencyInjection_. I feel like while it's awful, it is

* No more awful than the other alternatives we've come up with
* A logical transformation of _Serilog.Framework.Logging_
* The only precedent we've got

I'll need a strong drink before I can even consider PRing something like that... but is it the best option we've got?

**Comment by nblumhardt** [comment]
BTW, while things are still coming together I'm just dropping commits straight into the `serilog-framework-logging` repo, hope that's okay with everyone (easier to get some work done without an endless stream of PRs). Once the name change is in perhaps we switch this one to regular business-as-usual status :)

**Comment by nblumhardt** [comment]
Okay, looks like it is _Serilog.Extensions.Logging_ ... :-) will make the change when I get a chance.

**Comment by merbla** [comment]
sounds good, we can branch out to other techs this way :sunglasses:

**Comment by nblumhardt** [comment]
Okay, repo is renamed (https://github.com/serilog/serilog-extensions-logging) will PR up the project/package name changes as soon as possible. Cheers!

**Comment by nblumhardt** [comment]
All done.
