### ISSUE TITLE
Upgrade to RC1 bits

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#598]
Currently the v2 branch builds using beta8.

**Comment by nblumhardt** [comment]
Ready to go on `dev`.

**Comment by khellang** [comment]
I'll can do this :+1:

**Comment by khellang** [comment]
I looked at this the other day. Since Serilog doesn't have any dependencies, it looks like there's no changes to be made other than switching the `sdk.version` in global.json to `1.0.0-rc1-final`. I'll send a PR later tonight.
