### ISSUE TITLE
use c#6

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog#601]
interested in a PR that updates the code to c#6?

**Comment by khellang** [comment]
I say yay :+1:

**Comment by nblumhardt** [comment]
:+1: too, nice to have it in one commit rather than patchy updates as we touch each file.

**Comment by khellang** [comment]
Looks like this is partly done; https://github.com/serilog/serilog/commit/34a1aaeb336b23c898a9caa662a1b37fd2229bde

**Comment by nblumhardt** [comment]
I think most of this is covered in v2 now.
