### ISSUE TITLE
Minimum Sink Log Level Configuration Using File 

### ISSUE THREAD

**Issue by DevEnable** [serilog/serilog#603]
Hello,

We have a configuration with multiple sinks.  One of those being the ColoredConsoleSink.  What I want to do is have the ColoredConsoleSink output events only information level and above (whereas the other two sinks will report more verbose events).

I can see on the [documentation](https://github.com/serilog/serilog/wiki/Configuration-Basics) that you can do this through code.  However, I cannot figure out how to do this via configuration file, which is what we need to support.

I've tried the following setting:
```<add key="serilog:write-to:ColoredConsole.minimum-level" value="Information" />```

But this doesn't seem to work.  I can work out a hack to get this working, essentially by taking the LoggingConfiguration object after .ReadFrom.AppSettings() has been called, accessing the private sink and replacing it with a clone with a different LogLevel.  But it would be a real hack involving Reflection which I'd really like to avoid.  

Is this currently supported by Serilog?

**Comment by DevEnable** [comment]
Figured it out through trial and error :).

```<add key="serilog:write-to:ColoredConsole.restrictedToMinimumLevel" value="Information" />```

This works, it's just not entirely obvious due to the minimum-level configuration setting.  I.e. not consistent.

**Comment by nblumhardt** [comment]
Thanks for the note; yeah, the inconsistent name is a trade-off. The meaning of the parameters is different - `MinimumLevel` affects the level at which events will be _produced_, while `restrictedToMinimumLevel:` is a filter (so doesn't work to cause more verbose events to be emitted unless `MinimumLevel` is at the same or a more verbose level). Cheers!

**Comment by DevEnable** [comment]
In terms of the inconsistent naming, I was referring more to the hyphen.  restrictedToMinimumLevel doesn't contain one, whereas minimum-level does.  

I can understand why that is, as minimum-level is a fix in-built configuration value, whereas restrictedToMinimumLevel is supply a constructor parameter value.
