### ISSUE TITLE
Which sink to use for serilog?

### ISSUE THREAD

**Issue by Ncage1974** [serilog/serilog#604]
We are going to be adding serilog to a web application. Would love to use a nosql store like Seq or MongoDB but unfortunately getting something installed on the server is like pulling teeth. 

First if we use log files is there the potential of deadlocks since  multiple threads might be trying to write to the same log file at the same time?

Second is there a better choice of a sink than text files? Maybe there is some type of in-process nosql store i could install into the application without having to actually install something on the server? I don't have the ability to hit any remote sql instance from where i'm at and if possible would prefer to keep it locally anyways.

**Comment by merbla** [comment]
Hey @Ncage1974! There are a few options.

From the [provided sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) the file based sinks are robust.  There are also many other options however re: embedded DB ([RavenDB](https://github.com/serilog/serilog-sinks-ravendb) etc.) there are still a few options. 

For file based options:
- [Rolling File](https://github.com/serilog/serilog/blob/master/src/Serilog.FullNetFx/Sinks/RollingFile/RollingFileSink.cs) will get you going out of the box
- [TextWriter](https://github.com/serilog/serilog/blob/master/src/Serilog/Sinks/IOTextWriter/TextWriterSink.cs) may be better if you need a little control.

**Comment by nblumhardt** [comment]
@Ncage1974 one thing you might consider is XCOPY-deploying Seq; there are some instructions here: http://docs.getseq.net/docs/xcopy-deployment. You'd still need administrative permissions to install it, but using something like [Octopus Deploy](https://octopus.com) this might not be too hard. HTH!
