### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by atlemann** [serilog/serilog#605]
Does not build used in an F# project on Mono on Ubuntu 14.04 LTS. Is support for linux in the pipeline?

F# Compiler for F# 4.0 (Open Source Edition)
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)

Build errors:
- The type 'Object' is required here and is unavailable. You must add a reference to assembly System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
-  The type 'Enum' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by nblumhardt** [comment]
Hi @atlemann - I'm assuming this is the 1.5.x Serilog release (if not the situation will be different). This is usually an outcome of Serilog being a "new style" portable library. In most cases just adding an explicit reference to _System.Runtime.dll_ should cover it.

**Comment by atlemann** [comment]
Hi @nblumhardt - It is Serilog 1.5.14.

We gotthe same problem on a Windows Server 2008 TeamCity build agent after we installed .NET 4.6 and MSBuildTools 2015. We fixed it again by installing a developer pack for 4.5.2.

So for the linux agent, this is how I installed Mono:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
	echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list && \
	sudo apt-get update
sudo apt-get install -y mono-complete fsharp

I am using FAKE and Paket to build and my paket.lock file looks like this:

NUGET
  remote: https://nuget.org/api/v2
  specs:
    FAKE (4.10.0)
    FSharp.Core (4.0.0.1)
    FSharp.Data (2.2.5)
      Zlib.Portable (>= 1.10.0) - framework: portable-net40+sl50+wp80+win80
    FsUnit (1.4.0)
      FSharp.Core (>= 3.1.2.5)
      NUnit (2.6.4)
    MathNet.Numerics (3.9.0)
      TaskParallelLibrary (>= 1.0.2856.0) - framework: net35
    MathNet.Numerics.FSharp (3.9.0)
      FSharp.Core (>= 3.1.2.5)
      MathNet.Numerics (3.9.0)
    NLog (4.2.2)
    NUnit (2.6.4)
    NUnit.Runners (2.6.4)
    Serilog (1.5.14)
    Serilog.Sinks.NLog (1.5.4)
    TaskParallelLibrary (1.0.2856) - framework: net35
    Zlib.Portable (1.11.0) - framework: portable-net40+sl50+wp80+win80
      NLog (>= 3.0.0.0)
      Serilog (>= 1.4.204 < 2.0)

**Comment by nblumhardt** [comment]
Thanks for the update. This kind of thing is usually due to the wrong reference assemblies being used at build time - is it possible your project is targeting .NET 4.0 rather than 4.5?

http://stackoverflow.com/questions/17309846/weird-issues-with-rx-on-net-4-5-and-f has some pointers, may be a little outdated, looks like there could be more possible causes... (Unfortunately I don't have the same setup to try to reproduce this on.)

**Comment by atlemann** [comment]
I'm targeting .NET version 4.6 and F# 4.0 (FSharp.Core 4.4.0.0). 

This is part of my .fsproj file:

    <Choose>
        <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0')">
          <ItemGroup>
            <Reference Include="Serilog.FullNetFx">
              <HintPath>..\..\packages\Serilog\lib\net40\Serilog.FullNetFx.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
            <Reference Include="Serilog">
              <HintPath>..\..\packages\Serilog\lib\net40\Serilog.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
          </ItemGroup>
        </When>
        <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')">
          <ItemGroup>
            <Reference Include="Serilog.FullNetFx">
              <HintPath>..\..\packages\Serilog\lib\net45\Serilog.FullNetFx.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
            <Reference Include="Serilog">
              <HintPath>..\..\packages\Serilog\lib\net45\Serilog.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
          </ItemGroup>
        </When>
        <When Condition="($(TargetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(TargetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrameworkIdentifier) == 'WindowsPhone' And ($(TargetFrameworkVersion) == 'v8.0' Or $(TargetFrameworkVersion) == 'v8.1')) Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'MonoTouch') Or ($(TargetFrameworkIdentifier) == 'Xamarin.iOS') Or ($(TargetFrameworkIdentifier) == 'Xamarin.Mac') Or ($(TargetFrameworkProfile) == 'Profile7') Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile44') Or ($(TargetFrameworkProfile) == 'Profile49') Or ($(TargetFrameworkProfile) == 'Profile78') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile111') Or ($(TargetFrameworkProfile) == 'Profile151') Or ($(TargetFrameworkProfile) == 'Profile157') Or ($(TargetFrameworkProfile) == 'Profile259')">
          <ItemGroup>
            <Reference Include="Serilog">
              <HintPath>..\..\packages\Serilog\lib\portable-net45+win+wpa81+wp80+MonoAndroid10+MonoTouch10\Serilog.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
          </ItemGroup>
        </When>
      </Choose>
      <Choose>
        <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')">
          <ItemGroup>
            <Reference Include="Serilog.Sinks.NLog">
              <HintPath>..\..\packages\Serilog.Sinks.NLog\lib\net45\Serilog.Sinks.NLog.dll</HintPath>
              <Private>True</Private>
              <Paket>True</Paket>
            </Reference>
          </ItemGroup>
        </When>
      </Choose>

**Comment by atlemann** [comment]
To reproduce, we created a tiny project using Xamarin Studio with only included Serilog. It builds on Linux (Ubuntu 14.04) by setting target framework to .NET 4.0. Anything higher gives the same error as the initial post. So I guess the fix will be to keep the logger in a separate project targeting .NET 4.0.

**Comment by nblumhardt** [comment]
Thanks for the follow up. Sounds like a sub-optimal workaround - have you tried adding the reference explicitly on Linux just to see if it sorts things out? YMMV, but I don't think you have to include the full path to the assembly - just use its fully-qualified name in the `<Reference>` element and the compiler should sort out the rest. HTH :-)

**Comment by atlemann** [comment]
Well, what do you know...Adding <Reference Include="System.Runtime" /> in the .fsproj file works for target framework 4.5.1, which is the latest recognized framework on our Linux Mono install. Framework 4.6 is too bleeding edge i guess. I was a bit uncertain on how to reference it the first time you mentioned it, but as you said, the compiler figured it out. Thanks a lot @nblumhardt!

**Comment by nblumhardt** [comment]
Great! Glad to hear it's up and running :+1:
