### ISSUE TITLE
Writing to VisualStudio Test Explorer standard output

### ISSUE THREAD

**Issue by jamesholcomb** [serilog/serilog#607]
I'm trying to get Serilog to write test output to standard out for NUnit unit tests run inside Visual Studio (the clickable Output link in Test Explorer).

However, Debug() and Verbose() logging are not there...only Info() and Error() were captured.

What am I missing?

Output
````
Test Name:	writes_log_to_standard_out
Test Outcome:	Passed
Result StandardOutput:	
From Trace.WriteLine
From Console.WriteLine
From Debug.WriteLine
PROGRAM Information: 0 : 2015-12-12 12:11:41.710 -06:00 [Information] From Serilog
PROGRAM Error: 0 : 2015-12-12 12:11:41.722 -06:00 [Error] From Serilog

[TestFixture]
public class LogTests : IDisposable
{
	[Test]
	public void writes_log_to_standard_out()
	{
		Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
		Log.Logger = new LoggerConfiguration()
			.WriteTo
			.TextWriter(Console.Out)
			.CreateLogger();

		Trace.WriteLine("From Trace.WriteLine");
		Console.WriteLine("From Console.WriteLine");
		Debug.WriteLine("From Debug.WriteLine");
		Log.Verbose("From Serilog");
		Log.Debug("From Serilog");
		Log.Information("From Serilog");
		Log.Error("From Serilog");
	}

	public void Dispose() { }
}
````

**Comment by IanYates** [comment]
The default minimum level in Serilog is `Information`.  Update your `LoggerConfiguration` to set your minimum level to verbose (I can't recall the exact syntax off the top of my head but intellisense will get you 99% of the way there)

**Comment by jamesholcomb** [comment]
doh, I was misinterpreting the `LogEventLevel restrictedToMinimumLevel = Verbose` optional parameter as the default.
