### ISSUE TITLE
Support for PeriodicBatching in Profile 259

### ISSUE THREAD

**Issue by ravensorb** [serilog/serilog#609]
Any plans to support PeriodicBatching in Profile 259?

**Comment by nblumhardt** [comment]
Howdy - no current plans, but the work done in `dev` for v2 should make this easier. I think the availability of `ConcurrentQueue<T>` might be the main blocker.

**Comment by ravensorb** [comment]
Any thoughts to breaking out the interfaces from the actual implementation so that a basic library could be included in any project and then the actual implementation be included in the apps?  That would allow you to effectively remove the platform dependency issue all together?

**Comment by merbla** [comment]
hey @ravensorb some of the work as apart of #593 will hopefully help this as well.

**Comment by ravensorb** [comment]
Looks great!  Anything I can do to help?

**Comment by nblumhardt** [comment]
Currently getting the v2 ship-shape is priority 1 - if there's anything in https://github.com/serilog/serilog/labels/v2 that takes your fancy please let us know! :-) :+1:

**Comment by nblumhardt** [comment]
2.x should now have this covered.
