### ISSUE TITLE
Serilog and EF7 code first: configuration and custom columns

### ISSUE THREAD

**Issue by mdmoura** [serilog/serilog#610]
Hello,

I am using Serilog with ASP.NET 5 and Code First.

Where can I find the EF7 entity for Serilog database table?
Can I configure extra table columns and also change default columns names?

Thank You,
Miguel

**Comment by nblumhardt** [comment]
Hi Miguel,

There's some documentation on adding additional columns here: https://github.com/serilog/serilog-sinks-mssqlserver#writing-properties-as-columns

We don't provide an EF entity for the logs table - creating one yourself is probably the second-best option (the best option is probably to use a log-specific data store for your log events, if you're starting a new project and have the flexibility to choose technologies).

Hope this helps!

Cheers,
Nick

**Comment by mivano** [comment]
Recently functionality has been added to auto create the log table. Adding additional columns is included already. Changing default column names is not. Open for a PR of course. See https://github.com/serilog/serilog-sinks-mssqlserver/blob/master/CHANGES.md for recent changes.
