### ISSUE TITLE
Add Loggly Bulk Sink to Third Party Packages in Wiki

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog#611]
https://github.com/samirahmed/serilog.LogglyBulkSink

We've been using this for > 6 months.  It's pretty stable and has a pretty insane throughput compared to the Serilog maintained Loggly sink.

**Comment by nblumhardt** [comment]
Done, thanks for the tip James! https://github.com/serilog/serilog/wiki/Provided-Sinks#third-party
