### ISSUE TITLE
Serilog {Date} format when using RollingFile

### ISSUE THREAD

**Issue by mcastillo86** [serilog/serilog#612]
Hello,

I'm using serilog and I've noticed that when using RollingFile method a date is added in yyyyMMdd format. Is that something that is hardcoded or something that can be change to for example yyyy-MM-dd?

Expected: Log-2015-12-18.txt

Thanks!

**Comment by nblumhardt** [comment]
Hi - I believe this is hard-coded. On the surface it seems like accepting a format string would be reasonable, but not sure it's enabling enough scenarios to warrant the effort. Are you stuck matching a legacy file name format? Cheers! :-)

**Comment by mcastillo86** [comment]
Hi! Yes, I am. We are progressively changing to Serilog, our current log file where our applications log has the following format [Filename]-yyyy-MM-dd.txt.

**Comment by nblumhardt** [comment]
Hi again - hope you worked out a strategy here. One tip I can suggest is to pipe either your legacy logging through Serilog, or write a Serilog sink that sends events to the legacy pipeline, so the whole thing can be unified. Let me know if we can help with any info/guidance, closing this for now however as we don't plan to change the format in the near future.

**Comment by HarelM** [comment]
Any updates on this? I'm not stuck with a legacy log but the time stamp is hard to read:
2017-02-27 is a lot easier to read than 201702027. When you want to find a specific log file the easier to read its name the less time it will take to find it.
I'm looking to migrate my code to .Net Core web API and I was hoping to use this logging library, this is a must have for me...

**Comment by nblumhardt** [comment]
Hi @HarelM - no, there hasn't been any change on this one. Thanks for the feedback.

**Comment by HarelM** [comment]
This is unfortunate, I believe this is a very basic required feature...

**Comment by Jehoel** [comment]
This issue has been recreated here: https://github.com/serilog/serilog-sinks-file/issues/64

And I've created a PR that allows users to use custom date-time formats in rolling file logs, including in subdirectory names:  https://github.com/serilog/serilog-sinks-file/issues/64

**Comment by kkarakk** [comment]
hey when is this feature going to be integrated? i would really like more readable file names

**Comment by malcolmjerry** [comment]
Use "Serilog Map" , You can customize your directory and file name.

    private readonly Serilog.ILogger _logger; //= Log.ForContext( "Name", "Weather" );

    public WeatherForecastController() {
      string subPath = Path.Combine( DateTime.Now.ToString( "yyyy" ), DateTime.Now.ToString( "MM" ) ) + $"/{DateTime.Now.ToString("dd")}_Weather";
      _logger = Log.ForContext( "Name", subPath );
    }

//////////////////////////////////////////////////////////////////////////////////////////

      .UseSerilog( ( hostingContext, loggerConfiguration ) => loggerConfiguration
        .ReadFrom.Configuration( hostingContext.Configuration )
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .WriteTo.Map(
          "Name",
          "Request",
          ( name, wt ) => {
            if (name == "Request")
              wt.RollingFile( Path.Combine( $"{hostingContext.Configuration["LogPath"]}/{{Date}}-{name}.txt" ) );
            else
              wt.File( $"{hostingContext.Configuration["LogPath"]}/{name}.txt" );
          } )
      );

**Comment by ashkan89** [comment]
Guys use my customized serilog package.you can fully customize date format and file name
https://github.com/ashkan89/serilog-sinks-fileex
Nuget package: Serilog.Sinks.FileEx
Serilog.Sinks..File.GzArchive

**Comment by cocowalla** [comment]
@ashkan89 before forking someone else's project - especially for very minor changes - please always consider contributing to the original project first

But more seriously, when forking someone else's project you _must_ to abide by the license conditions - something you haven't done for either [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) or [serilog-sinks-file-gzip](https://github.com/cocowalla/serilog-sinks-file-gzip). Actually, you've gone even further than not following the license conditions - I see you've actively _removed_ copyright notices from the `Serilog.Sinks.File` code, making what you have done look like an act of plagiarism. Don't do that. 😞

**Comment by afruzan** [comment]
Why the Serilog team doesn't make this very minor change? The feature would be very helpful for us
