### ISSUE TITLE
RollingFileSink issue (with JSON formatter)

### ISSUE THREAD

**Issue by BrianHarboldt** [serilog/serilog#613]
We are attempting to output a JSON formatted log rolling log file. When creating a new `RollingFileSink` (https://github.com/serilog/serilog/blob/dev/src/Serilog/Sinks/RollingFile/RollingFileSink.cs#L59) we see that the log file is formatted correctly, but throws a file exception after the first request.
Alternatively, if we use the extension method (https://github.com/serilog/serilog/blob/dev/src/Serilog/LoggerConfigurationFullNetFxExtensions.cs#L187) we do not get this exception, but the output file is unable to be completely formatted as JSON.

```
                Configuration.
                    WriteTo.Sink(new RollingFileSink(
                        config.LogPath,
                        new JsonFormatter(),
                        2097152,
                        10,
                        Encoding.UTF8)
                    );
```
vs
```
                Configuration
                    .WriteTo.RollingFile(config.LogPath,
                        retainedFileCountLimit: 10,
                        fileSizeLimitBytes: 2097152,
                        restrictedToMinimumLevel: LogEventLevel.Debug
                    );
```

Exception when web request is made when using `WriteTo.Sink(new RollingFileSink(`
```
A first chance exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
```

**Comment by nblumhardt** [comment]
Interesting - is it possible the file's somehow being deleted between the two requests? The formatter shoudn't make any difference to the file handling logic - it only transforms the event payload into a string.

Are you by any chance calling the `Configuration.CreateLogger()` method more than once per application run?

Some output from Serilog's `SelfLog` may help clarify things if that's not the case. (https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics)

**Comment by drusellers** [comment]
@nblumhardt and @BrianHarboldt we were but we have recently cleaned that up based on your previous feedback.

**Comment by nblumhardt** [comment]
Thanks @drusellers - the `SelfLog` output is probably the thing to check out now then.

**Comment by drusellers** [comment]
@nblumhardt https://gist.github.com/drusellers/47898e091b020b2d5ca4

**Comment by BrianHarboldt** [comment]
The SelfLog file remains empty while the exception happens (using the format which @drusellers mentioned). I've done a `SelfLog.WriteLine("test");` and confirmed that does in fact write out to the file without issue.

**Comment by nblumhardt** [comment]
Interesting - thanks for the follow-up. If Serilog itself was catching the exception, I'd expect it to go to SelfLog. Is it possible the exception is a red herring and happening somewhere else? Is it possible to get a stack trace for the error somehow? Cheers!

**Comment by BrianHarboldt** [comment]
I'll see if I can fish something out of the weeds.

**Comment by nblumhardt** [comment]
Great - very interested to hear what you find. Cheers!

**Comment by BrianHarboldt** [comment]
Update - found issue with the way we were registering the ILogger with Autofac.
I was able to resolve when adding `.SingleInstance()` on registration.

**Comment by nblumhardt** [comment]
Great - thanks for the update!

@drusellers does this have you covered? Cheers!

**Comment by drusellers** [comment]
Yeah, i don't understand why it worked (since Autofac is just referencing a singleton) but we are getting logs now. :) :+1:

**Comment by nblumhardt** [comment]
Woot! :)
