### ISSUE TITLE
ASP.NET Core configuration subsystem (JSON) support

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#614]
From: https://github.com/serilog/serilog-sinks-seq/issues/8

Essentially requires an `AppSettings()`-like way to read from _config.json_.

**Comment by khellang** [comment]
I can take this :soon:

**Comment by khellang** [comment]
@nblumhardt Do we want this in a separate repo? Have a good name for it?

**Comment by dazinator** [comment]
One quick comment which may be obvious, I naively tried doing this with this in the project.json:

```
"Serilog": {
    "serilog:using:Seq": "Serilog.Sinks.Seq",
    "serilog:write-to:Seq.serverUrl": "http://localhost:5341",
    "serilog:write-to:Seq.apiKey": "[optional API key here]"
  }
```

But the colon's in the key names are a no-go, so you will probably want to break it out into a proper structure :) 

```
"Serilog": {
    "using": {
       "Seq" : "Serilog.Sinks.Seq"
    },
     "write-to": {
       "Seq.serverUrl" : "http://localhost:5341",
       "Seq.apiKey" : "[optional API key here]"
    }    
  }
```

**Comment by khellang** [comment]
Yeah. The problem is that the AspNet Core configuration system boils everything down to a `Dictionary<string, string>`, where the key is separated by `:`, so

```json
"Serilog": {
    "using": {
       "Seq" : "Serilog.Sinks.Seq"
    },
     "write-to": {
       "Seq.serverUrl" : "http://localhost:5341",
       "Seq.apiKey" : "[optional API key here]"
    }    
}
```

effectively becomes

```csharp
new Dictionary<string, string>
{
    { "Serilog:using:Seq", "Serilog.Sinks.Seq" },
    { "Serilog:write-to:Seq.serverUrl", "http://localhost:5341" },
    { "Serilog:write-to:Seq.apiKey", "[optional API key here]" }
}
```

**Comment by dazinator** [comment]
Interesting.. So based on that I just tried to convert those to key value pairs, and use the existing API:

![image](https://cloud.githubusercontent.com/assets/3176632/12916009/0717430c-cf27-11e5-8c50-d2e8ff73d898.png)

I would have thought that would work but it doesn't appear to as I see no log output in seq!

**Comment by dazinator** [comment]
The "using" key, for the value pair side of serilog ReadFrom api doesn't seem to be consistent iwith the using key you would put in app settings xml.

For example for key value pairs, serilogs wants:

```
var pairs = new Dictionary<string, string>
{
  { "using", "Serilog.Sinks.Seq" }  
});

But in app config xml it wants
```
<add key="serilog:using:Seq" value="Serilog.Sinks.Seq" />

```

Notice the additional "Seq"

  That changes the structure of the equivalent json to something like:

"serilog": {
    "using": "Serilog.Sinks.Seq",
    "write-to": {
      "Seq.serverUrl": "http://localhost:5341"
    }
  }

Which means you can only have a single "using" ?

**Comment by dazinator** [comment]
Have managed to hack some code together than works, by reading the configuration and building key value pairs of the correct format.

With this in project.json:
```
 "serilog": {
    "using": "Serilog.Sinks.Seq",
    "write-to": {
      "Seq.serverUrl": "http://localhost:5341"
    }
  }
```

This code works:

```

 // configure serilog.
            IConfiguration configuration = this.Configuration;

            string serilogSectionName = "serilog";
            IConfigurationSection configSection = configuration.GetSection(serilogSectionName);

            var usingSection = configSection.GetSection("using");
            var usingKeyValuePair = new KeyValuePair<string,string>(usingSection.Key, usingSection.Value);
            var serilogSections = configSection.GetChildren().SelectMany(a => a.GetChildren()).ToList();
            var keyValues = serilogSections.Select(a => new KeyValuePair<string, string>(a.Path.Remove(0, serilogSectionName.Length + 1), a.Value)).ToList();
            keyValues.Add(usingKeyValuePair);

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.KeyValuePairs(keyValues).CreateLogger();

            Log.Logger.Error("Hi There");

```

**Comment by khellang** [comment]
What if you make `using` an array, like

```json
"serilog": {
  "using": [
    "Serilog.Sinks.Seq",
    "Serilog.Sinks.Console"
  ]
}
```

**Comment by merbla** [comment]
@khellang I was thinking same repo with new project for now.

Would this also include the other config setup from https://github.com/serilog/serilog/tree/dev/src/Serilog/Configuration?

**Comment by nblumhardt** [comment]
@merbla @khellang one of the downsides of using the core repo is that it will potentially churn a bit, generating a lot of trivial new versions of _Serilog.*.nupkg_. It's also nicer for someone to hack on this in a separate repo without worrying too much about PRs/reviews, that would come with being in _Serilog_. My vote's for a separate `serilog-configuration-core` (?) or similar.

I think there are some limitations with the key-value-pairs approach that indicate we should consider JSON support a clean slate. I like the style of @khellang's example above - iterating on that a bit:

```json
"serilog": {
  "using": [
    "Serilog.Sinks.Seq",
    "Serilog.Sinks.Console"
  ],
  "writeTo": [
    {"name": "Console"},
    {"name": "Seq", "args": {"serverUrl": "http://localhost:5341"}}
  ]
}
```

One goal I think it is worth keeping in mind is that adding another entry to `writeTo` that duplicates an existing one should be fine, e.g.:

```json
    {"name": "Console", "args": {"restrictedToMinimumLevel": "Warning"}},
```

(Prints `Warning` and above twice :-))

If we imply assembly names based on sink names by default (still supporting the `using` construct) it comes down to:

```json
"serilog": {
  "writeTo": [
    {"name": "Console"},
    {"name": "Seq", "args": {"serverUrl": "http://localhost:5341"}}
  ]
}
```

Thoughts/improvements?

**Comment by dazinator** [comment]
That looks good to me, I like the idea of the infering the assembly names using the sink name, that should cater for the normal case, I doubt many people would have sinks in custom namespaces, and if they do they can always be explicit via the using construct - so long as that's all made clear in the documentation / wiki page etc.

**Comment by tillig** [comment]
I'm actually pretty interested in this for a project I'm on, too. [Is this the repo it'll be in?](https://github.com/serilog/serilog-framework-configuration) I've spent altogether too much time with the new configuration stuff while working with Autofac.Configuration so if I can help out, let me know.

**Comment by tillig** [comment]
Oh, something to note about flattening out the configuration keys and ordered collections (like arrays) - if you have this:

```json
"serilog": {
  "writeTo": [
    {"name": "Console"},
    {"name": "Seq", "args": {"serverUrl": "http://localhost:5341"}}
  ]
}
```

You'll end up with these keys:

```
serilog
serilog:writeTo
serilog:writeTo:0
serilog:writeTo:0:name
serilog:writeTo:1
serilog:writeTo:1:name
```

Ordered collections create "fake keys" at zero-based indexes so you can mimic the same thing in environment variables or XML. Not insurmountable, but something to be aware of as you parse it.

**Comment by nblumhardt** [comment]
Thanks for the info @tillig - looks like there are still a few surprises to uncover.

@khellang/all what's the general feeling about this one currently? I can take a shot at putting something quick together this week if it'd help move us forward.

Not sure yet about the repo/naming, _Serilog.Settings.Something_ is the intention, whatever that _Something_ might be....

**Comment by nblumhardt** [comment]
@khellang mind if I have a hack at this?

**Comment by nblumhardt** [comment]
We're in business! :-)

https://github.com/serilog/serilog-settings-configuration

```json
{
  "Serilog": {
    "Using":  ["Serilog.Sinks.Literate"],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "LiterateConsole" },
      { "Name": "File", "Args": { "path": "%TEMP%\\Logs\\serilog-configuration-sample.txt" } }
    ],
    "Enrich": {
      "WithProperties": {
        "Application": "Sample"
      },
      "With": ["MachineName", "ThreadId", "ProcessId"]
    }
  }
}
```

Usage:

```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .Build();

            var logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            logger.Information("Hello, world!");
        }
    }
```

The `WriteTo` and `With` sections support the same syntax, i.e. you can say:

```json
"WriteTo": ["LiterateConsole", "DiagnosticTrace"]
```

If you don't need any arguments, or you can use the long-form (`"Name":` ...) if you do.

Currently working on getting a build/package done. Needs tests (gratefully accepted if anyone can help) and probably a good solid code review as most of the implementation's just hacked out of the existing key-value pair support.

Ah one last thing - it implements a convention using `ILibraryManager` to find any package with `Serilog` anywhere in the name and pulls configuration methods from it, so the `Using` example above is redundant. Yay! :-)

**Comment by nblumhardt** [comment]
Hmm, spoke too soon, enricher syntax is non-functional - patching up now :-)

**Comment by merbla** [comment]
:clap: : :+1:

**Comment by nblumhardt** [comment]
Not ideal... but now looks like:

```json
    "Enrich": {
      "With": [
        "FromLogContext",
        "WithMachineName",
        "WithThreadId"
      ],
      "WithProperties": {
        "Application": "Sample"
      }
    }
```
 May need a bit more thought...

**Comment by dazinator** [comment]
Cool!

> it implements a convention using ILibraryManager to find any package with Serilog anywhere in the name and pulls configuration methods from it, so the Using example above is redundant.

If using an assembly not within `ILibraryManager` - how does serilog locate the assembly - can you pass it an `IAssemblyProvider` ?

**Comment by nblumhardt** [comment]
@dazinator I'm not sure of the difference between these two mechanisms, I might have picked the wrong one! Where would an `IAssemblyProvider` come into the picture?

(The `Using` syntax should provide a bit of an escape hatch - but not sure under what conditions we'll need to do more to track down the impl...)

**Comment by nblumhardt** [comment]
Nugotten: https://www.nuget.org/packages/serilog.settings.configuration

```json
    "Enrich": {
      "With": ["FromLogContext", "WithMachineName", "WithThreadId"],
      "WithProperties": {
        "Application": "Sample"
      }
    }
```

We could alternatively do `Apply`:

```json
    "Enrich": {
      "Apply": ["FromLogContext", "WithMachineName", "WithThreadId"],
      "WithProperties": {
        "Application": "Sample"
      }
    }
```

Or deviate from 1:1 mapping with the C# API and do:

```json
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"],
    "AddProperties": {
       "Application": "Sample"
    }
```

?

**Comment by dazinator** [comment]
@nblumhardt `ILibraryManager` will return information about packages that your application references when it was published (via project.json file). But if you have an extensible application, like seq for example, where you can install additional "plugins" at runtime, then `ILibraryManager` wont include these plugin assemblies. It's in that case that you would implement an `IAssemblyProvider` as a means to inform the framework about your "additional assemblies". This is usually done by wrapping the `DefaultAssemblyProvider` provided by the framework and appending your extra plugin assemblies to the list of assemblies returned as a result.

As my application is basically an extensible shell, and serilog is an optional module that can be installed at runtime, i'd need a way of telling serilog configuration where the assemblies are as they wont be available in ILibraryManager. If it could check for an IAssemblyProvider or if I could pass in an array of assemblies that would do just fine!

**Comment by nblumhardt** [comment]
@dazinator thanks for the additional info. Looks like something to examine closely once RC2 is out.

All - I just updated the enrich syntax to:

```csharp
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"],
    "Properties": {
       "Application": "Sample"
    }
```

Keen to get this out a bit more widely so that we can pick up some feedback on it, I'll close this thread and follow up on issues in serilog/serilog-settings-configuration.

Cheers!
