### ISSUE TITLE
Use Rx to implement Observable sink

### ISSUE THREAD

**Issue by jbattermann** [serilog/serilog#615]
Hey there,

I was just about to write my own RX based Sink but first checked whether Serilog already has one.. [which it does](https://github.com/serilog/serilog/blob/dev/src/Serilog/Sinks/Observable/ObservableSink.cs).. but I was wondering whether there's any particular reason why the subscriber management is managed by the sink itself & not by using a RX native Subject<LogEvent> (i.e. like this https://gist.github.com/jbattermann/3668c0d52bb1b7892fbe#file-observablesink-cs-L18 for observer subscription & https://gist.github.com/jbattermann/3668c0d52bb1b7892fbe#file-observablesink-cs-L29 for the LogEvent forwarding).

Just wondering as [Subject < T >](https://msdn.microsoft.com/en-us/library/hh242970(v=vs.103).aspx) provides a stable / well tested (un)subscription mechanism and proper disposal/stream-completion handling when disposed itself.

The Subject < T > class is part of the RX package and not part of the BCL as IObservable/IObserver are, but maybe its worth extracting the current ObservableSink into its own package outside the serilog main package for 2.x and simplify it in that regards.

If you think this might make maintaining it a bit easier just let me know and I'll gladly take care of it.

Cheers,
-J

**Comment by khellang** [comment]
We've been through this before... sort of; https://github.com/serilog/serilog/issues/383. Maybe it's time to revisit?

**Comment by jbattermann** [comment]
Ahh oh my - sorry for the duplicate -.- The same argument still applies though and nothing really has changed since then: "no one" consumes observables without RX but at the same time there's no specific *need* now to change anything, now.. or anytime soon.. nor will it greatly *improve* serilog or its maintainability.

The only argument for the split out of core and change from custom observer management to RX native one *now* would be v2 being around the corner, somewhat, and #344

**Comment by khellang** [comment]
Yes. I think it makes sense, and even more so now, when we've split out most other sinks into separate repositories and v2 incoming. I'll leave it up to @nblumhardt to decide :wink:

**Comment by nblumhardt** [comment]
I think this fits the direction we're taking in #593 - let's do it! :-) I think it's implied there, we can leave this issue separately open or just consider it "one of the sinks" - happy either way.

**Comment by nblumhardt** [comment]
_Serilog.Sinks.Observable_ is now its own package, so this one's ready to go if anyone is keen.

**Comment by nblumhardt** [comment]
Hi all - if someone's keen to PR this on serilog/serilog-sinks-observable that would be great, but closing this ticket as it's been around a while without movement :-)
