### ISSUE TITLE
PeriodicBatchingSink.Emit produces too many contentions

### ISSUE THREAD

**Issue by DmitryNaumov** [serilog/serilog#619]
During my investigations of why simple foreach loop with some logging produces log entries with millisecond-sized gaps between each. I suspected thread context switches to be the reason. High contention rate was also noted by performance counters and performance profiler:

DA0039: (Average)Contention Rate / sec = 17.94; A very high rate of .NET Lock contentions is occurring.

I took a look at sink implementation and imo we can do better to avoid _possible_ contention on every write to log. I _do_ understand that if's are fast, but still if thread encounters occupied Monitor, then it's moved from RUNNING state to end of the wait list of the threads with same priority (I do simplify things here). So simple operation like write to log or even do an increment eventually may take milliseconds!

I didn't dive deeply in the logic behind checking _unloading & _started, but I think Monitor Enter/Exit can be easily replaced with Interlocked.CompareExchange operations which do not affect thread scheduling (thread won't go to WAIT state).

        public void Emit(LogEvent logEvent)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));

            lock (_stateLock)
            {
                if (_unloading) return;
                if (!_started)
                {
                    // Special handling to try to get the first event across as quickly
                    // as possible to show we're alive!
                    _started = true;
                    SetTimer(TimeSpan.Zero);
                }
            }

            _queue.Enqueue(logEvent);
        }

**Comment by nblumhardt** [comment]
Thanks Dmitry. As far as I can tell this would be a good change, but it'd need some careful planning and testing no doubt.

**Comment by DmitryNaumov** [comment]
Nicholas,
if you don't mind I can try to create test to show the problem.

**Comment by nblumhardt** [comment]
Thanks for the offer. I should have been more clear in that last comment, sorry - I was thinking ahead to determining whether we'd introduce any regressions by making the change. I'm confident the locking will have the impact you've described when there's heavy contention :+1:

I'm open to making the change, but the bar for maintaining correctness is pretty high here - it'll be a fairly challenging change to be thoroughly confident about. At the moment there's a lot of work in getting v2 out the door that would take precedence, but if you want to tackle it in the meantime please feel free.

**Comment by DmitryNaumov** [comment]
Nicholas,
Given the following changes, do you think they can have some bad consequences?

        private volatile bool _unloading;
        private int _started;

        public void Emit(LogEvent logEvent)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));

            if (_unloading) return;
            if (Interlocked.CompareExchange(ref _started, 1, 0) == 0)
            {
                // Special handling to try to get the first event across as quickly
                // as possible to show we're alive!
                SetTimer(TimeSpan.Zero);
            }

            _queue.Enqueue(logEvent);
        }

**Comment by nblumhardt** [comment]
Hi Dmitry,

If the sink isn't started, and `_unloading` is set between the lines:

```csharp
        if (_unloading) return;
        if (Interlocked.CompareExchange(ref _started, 1, 0) == 0)
```

then it is possible the timer will be started even though the sink has started unloading (so potentially won't then stop the timer).

I don't know if this is likely to be a problem in practise - but reflects the kind of things we'd need to figure out.

Using a single atomically-set integer with three states, (initial, started, unloading) could work and maintain the same invariants?
