### ISSUE TITLE
Output template is different for Verbose/Debug and Information/Warning/Error/Fatal

### ISSUE THREAD

**Issue by Lakritzator** [serilog/serilog#621]
I seem to have a problem with Serilog and output templates.

Example code using 1.5.14 (tried it with 2.0.0-beta-423 which is the same)

			Log.Logger = new LoggerConfiguration()
				.MinimumLevel.Verbose()
				.WriteTo.Trace(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {SourceContext} - {Message}{NewLine}{Exception}")
				.CreateLogger();
			Log.Logger.Verbose("From Serilog");
			Log.Logger.Debug("From Serilog");
			Log.Logger.Information("From Serilog");
			Log.Logger.Warning("From Serilog");
			Log.Logger.Error("From Serilog");
			Log.Logger.Fatal("From Serilog");

This will output:
> 2015-12-28 17:21:18.724 [Verbose]  - From Serilog
> 2015-12-28 17:21:18.743 [Debug]  - From Serilog
> SeriLogPlayground.vshost.exe Information: 0 : 2015-12-28 17:21:18.743 [Information]  - From Serilog
> SeriLogPlayground.vshost.exe Warning: 0 : 2015-12-28 17:21:18.745 [Warning]  - From Serilog
> SeriLogPlayground.vshost.exe Error: 0 : 2015-12-28 17:21:18.745 [Error]  - From Serilog
> SeriLogPlayground.vshost.exe Error: 0 : 2015-12-28 17:21:18.746 [Fatal]  - From Serilog

I must be doing something wrong?

**Comment by khellang** [comment]
This is because the `DiagnosticTraceSink` uses `WriteLine` for Verbose/Debug, while it uses other alternatives for Information/Warning/Error/Fatal: https://github.com/serilog/serilog/blob/71a65c710e826e3fab68efa1da249c81c906c49d/src/Serilog/Sinks/DiagnosticTrace/DiagnosticTraceSink.cs#L42-L49

**Comment by khellang** [comment]
Fun fact; `Trace.Trace[Error|Information|Warning]` all call an internal [`TraceInternal.TraceEvent`](http://referencesource.microsoft.com/#System/compmod/system/diagnostics/TraceInternal.cs,7edee92158401784) with a [`TraceEventType`](http://referencesource.microsoft.com/#System/compmod/system/diagnostics/TraceEventType.cs,f3c16a4fa82f3fbb), which has other levels that would map perfectly agains Serilog's levels, but they're not exposed in a public API :stuck_out_tongue_closed_eyes:

**Comment by Lakritzator** [comment]
Thanks for the quick reply, that actually makes sense.

It would actually be quite easy to simulate the Trace call, most of the code in TraceInternal would actually work:
http://referencesource.microsoft.com/#System/compmod/system/diagnostics/TraceInternal.cs,7edee92158401784

The code would actually not be much more than:

    foreach (TraceListener listener in Trace.Listeners)
    {
        listener.TraceEvent(eventCache, AppName, eventType, id, format, args);
        listener.Flush();
    }


But to be honest, I myself rather have the output of the first lines!
I will have a look at it, and create a pull-request for a solution which has better mapping and also solves my wish with an additional parameter.

P.S.
The TraceEventType doesn't map 100%, but I guess Verbose/Debug -> Verbose should be okay.

**Comment by nblumhardt** [comment]
Very interesting! The second style of output might be more palatable if the default template didn't include the level and timestamp?

**Comment by Lakritzator** [comment]
I guess you are referring to the output in my first comment?

If you would remove the timestamp and level from default template in this case, it would still confuse me. For me it would just suffice if the Trace.WriteLine(text) was available via an option, as I only wanted to read the output and not process it.

Maybe I am **completely** on the wrong track, sometimes you just want a solution for your current problem and forget what you wanted in the first place. What I actually wanted is just have the output visible in the Output window of Visual Studio. I couldn't find a good solution for this, except using the DiagnosticTraceSink which as I reported had inconsistent output.

P.S.
I already knew, while implementing my proposed code, that there will be a possible problem when Trace.UseGlobalLock was set to true. But at that time I forgot to check the default... As this is true, there will be a ArgumentException in most cases. The check could be removed, but I certainly can't lock the global lock from the code, so the result might be unpredictable behaviour.
As I'm no expert on Tracing, I currently can't imagine what this behaviour might be...

**Comment by nblumhardt** [comment]
Thanks for all the input here. I don't think we have a solid direction yet so I'll close this in the interests of keeping the tracker a bit clearer. If anyone hits this and has a solution, some notes here/a PR would be welcome. Cheers!
