### ISSUE TITLE
ColoredConsoleSink not threadsafe?

### ISSUE THREAD

**Issue by jvdonk** [serilog/serilog#631]
Using the Console-sink:
````
.WriteTo.Console()
````
The output is as follows:
![image](https://cloud.githubusercontent.com/assets/1164988/12268181/f7984e8a-b94b-11e5-9c9d-37d0822f3b6c.png)

Perfect. But when using the ColoredConsole-sink:
````
.WriteTo.ColoredConsole()
````
The output is as follows:
![image](https://cloud.githubusercontent.com/assets/1164988/12268270/4bdaecf0-b94c-11e5-9202-a6ad12174bc5.png)

The logger is configured like this:
````
var logger = new LoggerConfiguration()
                .WriteTo.ColoredConsole()
                .WriteTo.Seq("<seq-endpoint>")
                .CreateLogger();
````
````
logger.Information($"Order is succesfully processed: {orderId}");
````

The method where the above logger is instantiated is called from a Hangfire context with multiple workers(threads) processing the jobs(invoking the method with the logger in it)

Shouldn't I use the ColoredConsole-sink in a multi threaded environment?

**Comment by nblumhardt** [comment]
Hi, thanks for the report.

Yes, the `ColoredConsole` sink is threadsafe - but, only for a single instance. Instead of creating multiple `logger` objects you'll need to create a single one that is shared by all the workers.

Let me know if you need any more info. Cheers!

**Comment by jvdonk** [comment]
Managed to do just that using AutoFac(and Hangfire.AutoFac), Console output(colored) is perfect now.

Using AutoFac solved actually a couple of other problems too :)

Cheers!

**Comment by nblumhardt** [comment]
Thanks for following up.

**Comment by bonesoul** [comment]
@nblumhardt I have to create multiple loggers [a main logger and subloggers for jobs], is there a way to accomplish this?
