### ISSUE TITLE
Add batching/thread offloading to many sinks 

### ISSUE THREAD

**Issue by DmitryNaumov** [serilog/serilog#633]
In multi-threaded environment at least some existing sinks suffer from lot of contentions/blocking. For example, ConsoleSink creates lot of contentions inside BCL (TextWriter.Synchronized is used for Console.Out), same issue with FileSink.

It would be nice to support batching and/or background flushing (thread offloading) capability in many of them. But of course it makes no sense to re-invent this wheel in every sink.

If you agree this whole idea worth further discussion, let me write few more sentences to describe my idea:
we do have PeriodicBatchingSink which does exactly what I need. What if using PBS + delegation we can add background flushing to any sink. So calls to Emit actually will be queued in PBS and only when timer fires buffered events will be emitted into original sink in background thread.

This is about background flushing, batching requires changes in ILogEventSink.Emit signature or (which is much better) introducing another interface. As a major and visible change it can be done later.

**Comment by nblumhardt** [comment]
Hi Dmitry,

Thanks for the thoughtful post.

Would the design below (which mimics `WriteTo.Logger()` already in Serilog cover it?

```csharp
var log = new LoggerConfiguration()
  .Enrich.WithThreadId()
  .WriteTo.AsyncLogger(al => al
    .WriteTo.Console())
  .CreateLogger();
```

The `AsyncLogger` sink could use TPL/threadpool/worker thread to shuttle messages to its connected sinks, without blocking the main logger.

I added `WithThreadId()` as a reminder that enrichers applied to the background logger would execute in their own context, so things like thread id and logging context may not appear as expected. Maybe one caveat of this design.

This'd probably make quite a nice _Serilog.Sinks.AsyncLogger_ package without needing any effort in the core right now.

I'd prefer something unintrusive over say, a per-sink wrapper that needs to be accounted for/configured throughout the API.

What do you think?

**Comment by johnkattenhorn** [comment]
This is really interesting, I like the idea of wrapping the existing sync and offloading with `WriteTo.AsyncLogger`

**Comment by DmitryNaumov** [comment]
@nblumhardt I've committed preliminary code in my [repo](https://github.com/DmitryNaumov/serilog/commit/2106f15bddccc289f24ad36baf13ed6e021cd40d) to give some food for discussion. Questions are:

-  Configuration. Extension method WriteAsyncTo doesn't please my eyes. But Logger(Sink)Configuration are doing great job incapsulating their state. 'Internal' doesn't work because configuration and sinks are in different assemblies. Any help/suggestions/ideas are welcome.

- Sink batching support. Imo, sinks should support batches on their lowest level. Otherwise writing to file or network wouldn't be as effective as it can be. It can be done via adding to ILogEventSink, but it breaks contract, deriving from it or adding brand new separate interface for it. Want to hear your opinion.

- Imo makes no sense to have both PeriodicBatchingSink and DelegatingPeriodicBatchingSink. Delegation should be implemented out-of-the-box. Existing sinks like Seq should not derived from PBS, but be implemented in sync-way and use delegating capabilities of PBS or DBPS (which one will survive). It would keep async things in one place and simplifies sink development.

- PBS.EmitBatchAsync. Didn't understand why declare async contract to be called and waited from timer's thread? We're already 'in background', it just complicates things imo.

- And last (but I think I forget something) but not the least - can I use any mock library for tests?

Please share your thoughts on these issues, may be you totally disagree with idea of built-in async support.

**Comment by nblumhardt** [comment]
Hi Dmitry, sorry about the slow reply (as usual for me it would seem :-))

I think currently experimenting with some ideas like this in an add-on package would help move things forwards. Bringing some changes back into the core would be an option if it hits a sweet spot, and if not, it's still a useful thing to have out there to opt into.

Just on your bullet points above:

 * Seems like trade-offs one way or the other here
 * Yes, I would add batching natively to sinks if I could go back in time I think; having said that, the batching algorithm tends to be sink-specific in some cases so not sure one solution would cover everything
 * Also makes sense, but hard to go back now for this as the solution we have is pretty reaonable; perhaps designing chainable sinks as a separate package would help flesh out an alternative design?
 * I'm fine with that; NSubstitute seems to be fairly friendly but if there's anything else in use that'd be fine too

HTH! :-)

**Comment by nblumhardt** [comment]
Great discussion, I think we need to look at these things piecemeal though rather than keep this umbrella ticket alive. Thanks!

**Comment by DaveVdE** [comment]
Looking forward to this async/buffered console output as well. Seeing requests increase from 6ms to 60ms just because I turn on logging.

**Comment by nblumhardt** [comment]
Hi @DaveVdE - as per the comment above, nothing's happening via this thread. If you can open a ticket in https://github.com/serilog/serilog-sinks-console for discussion of the latency issue that'd be great.

If you can include some info on how you're running the app and collecting info that would also be handy. Console output is _horrendously_ slow when there's a visible console window on-screen, but should practically vanish otherwise (e.g. when redirected, or when no console window is visible).

**Comment by DmitryNaumov** [comment]
@DaveVdE I saw same slowness when logging to file, that's why I started this topic.

@nblumhardt I kept silence because as I understand huge changes were expected in 2.0 like every sink now has it's own package, but I can be wrong. I still think we should/may reuse PeriodicBatchingSink functionality and not reinvent the wheel in every sink. But before I should understand how to do it. As far as I understand PBS is not located in assembly referenced by all other sinks. This can be a problem for my solution.

**Comment by DaveVdE** [comment]
@nblumhardt Apologies, I know this thread is closed. I was merely looking for this AsyncLogger that doesn't exist (yet) and maybe a link to an issue that keeps track of that specific feature.

I'm nowhere near ready to start showing hard data.

**Comment by nblumhardt** [comment]
Hi,

@DmitryNaumov - the `File()` sink syncs writes by default; in 2.0 a `buffered` parameter was added to override this: https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs#L59 - buffered writes are normally an order of magnitude (or two) better than sync'd ones, worth checking out if you can afford to sacrifice some durability.

`PeriodicBatchingSink` is in: https://github.com/serilog/serilog-sinks-periodicbatching in case that helps.

@DaveVdE no problem at all, thanks for the input!

Cheers,
Nick

**Comment by DmitryNaumov** [comment]
@nblumhardt if someone is fine to sacrifice durability for performance, why does he still sometimes, but quite often (for every 0x400 written bytes, which is default for StreamWriter buffer size), do IO (say 10ms cost) under lock?

```
        public void Emit(LogEvent logEvent)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));
            lock (_syncRoot)
            {
                _textFormatter.Format(logEvent, _output);
                if (!_buffered)
                    _output.Flush();
            }
        }
```

We saw same problem before, in PBS, and we solved it. So, wouldn't it be better for those who seeks performance to offload those not-so-rare Flush operations to another thread?

**Comment by DmitryNaumov** [comment]
By mentioning Flush I mean when StreamWriter decides it's buffer is full and it is time to flush stream. This is not related to

```
                if (!_buffered)
                    _output.Flush();
```

**Comment by nblumhardt** [comment]
Hi @DmitryNaumov, thanks for the explanation. Please don't let me give the impression I'm against improving performance here - faster writes would be great.

If anyone can collect some benchmarks on flushed, non-flushed, and async versions of this method it'd be a very interesting starting point for some improvements. Right now without numbers to quantify the impact it's hard to make forward progress.

It would also be great to get a bit more shape around the proposal to do generic async logging, either `.WriteTo.AsyncLogger` or a `PeriodicBatchingSink`-like foundation. For either option we'll need to work out how much we can do without breaking the world, but I agree there's an opportunity to take the improvement across the board.

Cheers!
