### ISSUE TITLE
DNXCORE50: 2.0.0-beta-432 LoggerConfiguration is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by colin-young** [serilog/serilog#634]
When using the beta 432 NuGet package I get **The type 'LoggerConfiguration' is defined in an assembly that is not referenced**. If I go back to beta-423 the error goes away. I can't see anything in the current repo that is the obvious culprit (or in the 4 commits after 28 Dec 2015). My net452 and net46 targets build fine. It's only dnxcore50 with beta-432 that has a problem.

**Comment by nblumhardt** [comment]
Hi Colin, thanks for the report!

Are you using any other packages that depend on Serilog? I.e. Serilog.Framework.Logging, or a sink package?

It'd also be good to know which version of which assembly the error is asking you to reference.

Cheers,
Nick

**Comment by colin-young** [comment]
From project.json:

    "frameworks": {
    "net452": { "dependencies": { } },
    "net46": { "dependencies": { } },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-*",
        "System.Collections": "4.0.11-*",
        "System.Security.Cryptography.Algorithms": "4.0.0-*",
        "System.Linq": "4.0.1-*",
        "System.Reflection": "4.1.0-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*"
      }
    }
    },
    "dependencies": {
      "MySpecialLibrary.Logging": "3.0.0-*",
      "Microsoft.Extensions.Configuration": "1.0.0-*",
      "Microsoft.Extensions.Logging": "1.0.0-*",
      "Microsoft.Extensions.PlatformAbstractions": "1.0.0-*",
      "Serilog": "2.0.0-beta-423",
      "Serilog.Sinks.Seq": "2.0.0-*"
    }

The full error:
    
    The type 'LoggerConfiguration' is defined in an assembly that is not referenced. You must add a reference to assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

I'm trying to use it in several extension methods:

```c#
    public static class MySerilogExtensions
    {
        public static LoggerConfiguration WriteToConsoleTarget(this LoggerConfiguration loggerConfiguration, SerilogOptions options) { ... }
        public static LoggerConfiguration WriteToFileTarget(this LoggerConfiguration loggerConfiguration, SerilogOptions options) { ... }

        // This is the one that the error is thrown for:
        public static LoggerConfiguration WriteToSeqTarget(this LoggerConfiguration loggerConfiguration, SerilogOptions options) { ... }
    }
```
    
MySpecialLibrary.Logging depends on (probably overkill providing this, but just in case):

    Dapper
    MySpecialLibrary.PHI.Encryption
    Microsoft.Extensions.Configuration
    Microsoft.Extensions.Configuration.Json
    Microsoft.Extensions.Logging
    Microsoft.Extensions.Logging.Abstractions
    Microsoft.Extensions.Logging.Console
    Microsoft.Extensions.OptionsModel
    Microsoft.Extensions.PlatformAbstractions
    Microsoft.CSharp
    Microsoft.Dnx.Runtime.Abstractions
    System.Linq
    System.Reflection.Extensions
    System.Security.Cryptography.Algorithms
    System.Security.Cryptography.Primitives

I like to think I've done a decent job of isolating Serilog to just the one project so none of the consumers need know how the logging is done.

**Comment by nblumhardt** [comment]
I think the problem is the version of Serilog the Seq sink was built against. Earlier Serilog 2.x builds didn't have an assembly version set correctly. Just published `-beta-28` that hopefully fixes this (https://www.nuget.org/packages/Serilog.Sinks.Seq/2.0.0-beta-28) - can you please let me know if you have any more trouble? Cheers!

**Comment by colin-young** [comment]
Looks good. Thanks!

To be clear, I only verified that I can compile and that the Seq sink is at least writing out a LogBuffer file. I'm having some trouble getting the events shipped to Seq, but I'm inclined to blame that on something in my library since I've had it for some time and it came back after I did some serious reworking of a previously mostly reliable version.
