### ISSUE TITLE
Remove .NET 4.0 compatibility from 2.0 packages

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#635]
Conditional platform support is starting to take its toll on the readability and malleability of the codebase. With .NET 4.0 having reached end-of-life it may be time to shed some of this in our 2.0 release.

It's possible, through Serilog 1.5, to continue supporting all .NET versions from 4.0 forwards, without needing to make the 2.0 codebase carry this burden directly.

This ticket has two parts:

* Update Serilog to drop .NET 4.0
* Update the README to include prominent version compatibility info

Comments, for/against? // @khellang 

From #618

**Comment by colin-young** [comment]
One advantage would be for LogContext since AsyncLocal was introduced with 4.5. I've got a mess of conditional statements in there right now... And they're nested. Ugh.
