### ISSUE TITLE
Serilog Configuration for MongoDB using Appsettings

### ISSUE THREAD

**Issue by stangudu1808** [serilog/serilog#637]
I am unable to configure the MongoDB settings using Serilog.Extras.Appsetting in the web.config file. I have tried like below but no luck. Can any one suggest the way?

add key="serilog:write-to:MongoDB" value="mongodb://localhost/test"
add key="serilog:using" value="Serilog.Sinks.MongoDB" 
add key="serilog:using" value="Serilog.Sinks.MongoDB" 
add key="serilog:write-to:MongoDB.connectionString" value="mongodb://localhost/test"
add key="serilog:write-to:MongoDB.serverUrl" value="mongodb://localhost/test"
add key="serilog:write-to:MongoDB.tableName" value="log"

**Comment by nblumhardt** [comment]
Hi - thanks for getting in touch. I think the first two lines are redundant and may cause issues. Does it work if you leave them off?

**Comment by stangudu1808** [comment]
Hi,

Thankyou for your reply. I have tried with like below but i am getting Serilog.Sinks.MongoDB could not find the assembly error even this dll exists in my project. Any thoughts....

add key="serilog:using" value="Serilog.Sinks.MongoDB"
add key="serilog:write-to:MongoDB.connectionString" value="mongodb://localhost/test"
add key="serilog:write-to:MongoDB.serverUrl" value="mongodb://localhost/test"
add key="serilog:write-to:MongoDB.tableName" value="log"

**Comment by nblumhardt** [comment]
Sounds like you're on the right track! Is the assembly present in the app's output directory? Sometimes assemblies that aren't referenced directly by the code (or by any other assembly) won't automatically get copied into the project's output.

If that's not the case, would you mind posting the complete error message? Many thanks!

**Comment by stangudu1808** [comment]
Thank you for sharing the information. Yes, as you said Serilog.Sinks.MongoDB.dll is not copied but remaining dlls are copied. May i know the reason? 

After configuring the mongodb details, still records are not inserted into Log collection. But now i am not getting errors.

  _logobj = new LoggerConfiguration().ReadFrom.AppSettings().CreateLogger();  // Code

Config file:

add key="serilog:minimum-level" value="Verbose"
add key="serilog:using" value="Serilog.Sinks.MongoDB" 
add key="serilog:write-to:MongoDB" value="mongodb://localhost/test"
add key="serilog:write-to:MongoDB.tableName" value="log"

Am I missed anything here? Please suggest and share the code if you have any which are related to Config using mongodb

**Comment by nblumhardt** [comment]
Hi - no ideas unfortunately, I've never used the MongoDB sink myself.

Connecting up `SelfLog` to the console can be a great way to quickly surface errors in the sinks: https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

**Comment by stangudu1808** [comment]
Hi,

Thank you for sharing this information. I have tried with SelfLog approach but i didnot get any error information. 

_logobj = new LoggerConfiguration().ReadFrom.AppSettings().CreateLogger(); // Code 

Above statement returned as {Serilog.Core.Pipeline.SilentLogger} object  and when i check the properties there is _addsink method but its not reading from the configuration file. But when i use like below

_logobj = new LoggerConfiguration().ReadFrom.AppSettings().WriteTo.MongoDB("mydbconnectionstring").CreateLogger(); 

Then i can able to see the MongoDB Sink... 

Please share any thoughts on this.

**Comment by nblumhardt** [comment]
Thanks for sticking with it. I don't think there are many options apart from copying the code for the `.AppSettings()` method across into your own assembly and step through the reading of the config file in  a debugger. May be a bit of fiddling around, but will get you to a resolution I think.

Would love to hear what you find, so that we can make this more intuitive/robust!

**Comment by nblumhardt** [comment]
Any update on this @stangudu1808?
