### ISSUE TITLE
Getting LogContext added to Microsoft.Extensions.Logging?

### ISSUE THREAD

**Issue by colin-young** [serilog/serilog#641]
Has anyone thought about proposing that the standard `ILogger` support a `LogContext`-like feature? As I was working on #588 for an internal project, I realized I was in a bit of a bind because my goal is to keep all our library dependencies as clean and flat as possible (I dream of being allowed to open source some of them one day), but I also wanted to take advantage of `LogContext` in some libraries. At the moment, I can't see any way to do that other than introducing another layer that would simply extend `ILogger` with `LogContext.PushProperty()` that returns an `IDisposable`, then inherit from that in my logger lib instead of the default `ILogger`.

`ILogger` :arrow_left: `BaseLogger` :arrow_left: `BaseLogger.Serilog`

becomes:

`ILogger` :arrow_left: `ILoggerLogContext` :arrow_left: `BaseLogger` :arrow_left: `BaseLogger.Serilog`

And anyone who wants to use any of my libraries that use logging internally need to take a dependency on `ILoggerLogContext` which while less than ideal is fine if it's internal work, but if I ever get to open source anything...

Simple enough, but it's one more dependency to create, maintain and deal with. It would be much nicer if it was part of the standard interface and any loggers that can't support it could simply provide a no-op implementation.

Thoughts?

**Comment by nblumhardt** [comment]
Thanks for the note. I did consider something like this back when LogContext came onto the scene, but the current design won because it's clear the log context is not tied to the logger (it'd be strange to push something onto the context via an `ILogger`, log an event with a completely _different_ `ILogger`, and see the properties appear on it.

If you just want to push onto a single `ILogger` then `ForContext()` does this; if the goal is to affect multiple `ILoggers` then having the mechanism be external to all of them seems to make sense.

At this point I think it's safe to say the ship has sailed (there's a high bar for interface breaking changes), but interesting to hear about your scenario so thanks again for posting.

**Comment by colin-young** [comment]
I see what you mean, and after further reflection, if it was to go into any interface breaking change, `ILoggerFactory` would probably make more sense. But what would make even more sense would be a completely new interface in the `Microsoft.Logging.Extensions` namespace, something like `ILoggerContext`. If you didn't want to support it, you would just return null.

I just finished cleaning up from a several years-old custom `ILogger` and `ILoggerFactory` implementation, so I'm a bit leery about implementing yet another custom interface that I'm hoping is going to be redundant in a few years.

    // in reality, this would be injected, so could be null
    var logContext = new SerilogLogContext();

    using (logContext?.AddProperty("New context", 1))
    {
        Logger.LogDebug("Debug message");
    }

That seems to work, and I think I could provide an implementation via a lambda with Autofac, thus avoiding the need for another dependency (I could define the interface in the library itself, which would result in some duplication, but I prefer that to another proprietary dependency, especially when my goal is to work with _any_ logger).

**Comment by nblumhardt** [comment]
Ah, sorry Colin, I misread your original post and realise now you're talking about a suggestion for _m.e.Logging_, not Serilog.

It sounds like the design you've reached is a reasonable one; the static/ambient nature of contextual correlation doesn't mesh with interfaces so well to me, but it's more stylistic than substantial, and the testing scenario is a fair one.

Still not sure this is something Serilog can help with, but if you end up raising a discussion on the _Logging_ repo it'd be very interesting to follow along.

**Comment by colin-young** [comment]
Where I thought Serilog could help is by vetting my idea :) I figured the people here probably have way more experience with logging frameworks in general than I do, both individually and collectively. My experience is about 90% with antique versions of log4net (the other 10% being various home-grown frameworks and jury-rigged solutions).

The main thing I don't like about my solution is that it's leaking out logging infrastructure details from a component that has nothing to do with logging. I'd be interested to get feedback on whether others think this is something general enough to be worth bringing up at the _Logging_ repo. It sounds like log4net has a similar concept and it would be nice to be able to normalize them.

**Comment by nblumhardt** [comment]
Not sure there's a huge amount we can do to move this forward from here, so closing for the time being. Would be interesting to continue the discussion sometime, though. Cheers!
