### ISSUE TITLE
ColoredConsoleSink prints missing output properties

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#649]
Normally, when sinks are configured with an output template `{X}` and property `X` is missing from the event, nothing is rendered. The `ColoredConsoleSink` has its own custom rendering and retains the old behaviour, printing `{X}` literally to show the missing property.

http://stackoverflow.com/questions/35014396/is-it-possible-to-only-display-sourcecontext-in-serilog-if-usecontextclass-has

**Comment by Pvlerick** [comment]
I will have a look at this.

**Comment by nblumhardt** [comment]
Great :+1:

**Comment by nblumhardt** [comment]
Howdy @Pvlerick - any feel for how much is involved in this one? Cheers! :-)

**Comment by Pvlerick** [comment]
@nblumhardt I have been looking at this but as stupid as it sounds I'm still struggling to find out how to debug the code base. I can't do it from the solution itself, for some reasons (the tests don't show up in test explorer) and from the packages .pdb file I can't seem to be doing it either.

In short, it's in progress although I'm stuck on details not related to the issue itself :smile:

**Comment by nblumhardt** [comment]
Ah yes :-) the tooling for .NET Core is a bit patchy right now.

Two approaches can work:

1. If you add unit tests, running `powershell ./Build.ps1` in the root of the repo will run them
2. Temporarily adding a console application to the solution and running that can also help

**Comment by Pvlerick** [comment]
Yep, I was doing 1 so far, but in the case of the ```ColoredConsole``` it's not very convenient as the output is hard coded to ```System.Console```.

I'll have to directly reference the debug built dll or use the local package ```Serilog.2.0.0-beta-1.symbols.nupkg```, I suppose.

**Comment by nblumhardt** [comment]
Thanks @Pvlerick, nice improvement :-)
