### ISSUE TITLE
Add `buffered` Boolean configuration parameter to File/RollingFile sinks

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#650]
Both `File` and `RollingFile` flush the file stream after each write. This is a good default, as it's generally the event immediately before an application crash that you need when debugging.

Providing a `buffered` Boolean parameter to both of these configuration methods, defaulting to `false`, seems reasonable for anyone looking for less latency and prepared to make the trade-off.

http://stackoverflow.com/questions/35020648/serilog-file-rollingfile-sink-and-buffering

**Comment by Pvlerick** [comment]
I'm happy to have a look into that :smile:

**Comment by saitejkuralla** [comment]
Hi @nblumhardt
We are facing an issue on performance in logging with serilog 
Below attachment is the delay stats between logs for each log it is taking minimum 400 ms 
Please help us on this.
![image](https://user-images.githubusercontent.com/11627655/49520626-b09d1680-f8c9-11e8-9531-4e03ae3d9d1d.png)
Below is the configuration we used for logging 
![image](https://user-images.githubusercontent.com/11627655/49520715-e641ff80-f8c9-11e8-976e-cfaf2fd2c3b6.png)

**Comment by BernardTheDog** [comment]
I tested it, and when logging strings, its was about 20ms when i logged a class it was a bit more overhead, and when i added bigger and bigger logs, the time for saving increased. So when i tested with 100mb data it took around 400ms to store it.
But if you are able to use async sink it seems to be much faster: https://github.com/serilog/serilog-sinks-async. i got around 15 ms for 300mb of data
