### ISSUE TITLE
Parameters MaxDocuments and MaxSize in the class CreateCollectionOptions

### ISSUE THREAD

**Issue by EugeneStenin** [serilog/serilog#651]
Parameters MaxDocuments and MaxSize in the class CreateCollectionOptions do not work. Instance of CreateCollectionOptions  is transmitted through the parameters in the constructors MongoDBSink : PeriodicBatchingSink. These parameters must specify the maximum number of documents in the collection (MaxDocuments), which is written logs and the maximum size of this collecrion (MaxSize). However, these restrictions do not work out. 
So I had to implement this functionality in a method EmitBatch in the class MongoBDSink. 
Tell me, can I do something wrong. Or, maybe, I do not understand how these parameters should affect the operation of the logger.

**Comment by nblumhardt** [comment]
Hi Eugene, I'm not using MongoDB personally so I can't comment - @serilog/owners-mongodb may have some ideas? We've just recently taken a PR fixing capped collection support so there may be a fix implied in there. If you think there's a bug involved, PRing up the fix would be very welcome. HTH!

**Comment by nblumhardt** [comment]
Moved to: https://github.com/serilog/serilog-sinks-mongodb/issues/8 (see #450)
