### ISSUE TITLE
Unlist obsolete packages from NuGet.org

### ISSUE THREAD

**Issue by khellang** [serilog/serilog#655]
I had a quick look though the packages under the [Serilog profile](https://www.nuget.org/profiles/serilog) on NuGet.org, and noticed quite a few obsolete packages.

Should we unlist them?

**Comment by nblumhardt** [comment]
:+1: definitely

**Comment by nblumhardt** [comment]
Done

**Comment by nblumhardt** [comment]
Looks like I spoke too soon :-(

Using the checkbox to hide a package from search results seems to only unlist the most recent version:

![image](https://cloud.githubusercontent.com/assets/342712/13475860/c541bef2-e110-11e5-9810-37be6b031da6.png)

https://www.nuget.org/packages/Serilog.Extras.FSharp/

This has had the unfortunate effect of removing the obsoletion notices that were on the latest versions of each package.

Is there another/better way to do this?

**Comment by khellang** [comment]
I think you need to unlist all the versions :stuck_out_tongue_closed_eyes:

**Comment by nblumhardt** [comment]
_is going to be a long time_

**Comment by nblumhardt** [comment]
Looks like http://stackoverflow.com/a/24471860/138206 is as good as it gets. For a rainy day.....

**Comment by nblumhardt** [comment]
I can't see myself wrestling with this one anytime soon. Perhaps we just let them get buried as the download counts on the new packages skyrocket ;-)

**Comment by merbla** [comment]
![image](https://cloud.githubusercontent.com/assets/637298/16975087/6acec06c-4e86-11e6-93b6-39254f8a7918.png)

I think we are good FTM.
