### ISSUE TITLE
Confirm: No JavaScript Support?

### ISSUE THREAD

**Issue by Michael-DST** [serilog/serilog#657]
I was going to post to the discussion forum but I am too impatient and want to have one less thing to worry about. :)

I wanted to confirm here that this project does not support JavaScript-based applications, correct?  This is only for .NET applications at the moment?

Thank you for any feedback/consideration.

**Comment by khellang** [comment]
There is https://github.com/structured-log/structured-log. Not sure what its state is, but it's there at least :wink:

**Comment by Michael-DST** [comment]
wow, thank you for the quick response!  To be sure, this not an official/endorsed project of Serilog?  Also, does it work with [Seq](http://getseq.net/)?  Guess I should stop being lazy and check over there, huh? :stuck_out_tongue:

**Comment by khellang** [comment]
TBH I haven't used it myself, and I'm not really sure what the relationship is between the projects :smile:

A Seq sink is issue no. 1 in that repo: https://github.com/structured-log/structured-log/issues/1 :stuck_out_tongue_closed_eyes:

**Comment by Michael-DST** [comment]
LOL!  Two years now!  Wowwww... thank you for being more diligent that me.  I will try to pass it on at some point. :sunglasses: 

By the looks of it, like they are out of sync and probably do not match version/capabilities -- pretty much like every .NET and JS port I know!  Oh, the angst.

**Comment by mivano** [comment]
Have a look at this project if you want javascript logging and still write the events to Serilog on the server: http://jsnlog.com/

**Comment by Michael-DST** [comment]
Geeze... not as streamlined as .NET, huh. :stuck_out_tongue_closed_eyes: I *really* appreciate the information @khellang and @mivano!

FWIW, I have referenced this issue in a blog post that I just posted, as an easy (or easier, relatively) example of a problem in a problem space that I have been obsessed with since... well way too long LOL.  Please feel free to give me any feedback (and I appreciate any support/votes you can provide towards the matter!)
http://blog.developers.win/2016/02/the-great-net-client-divide-a-simple-example-hopefully/

I am definitely interested if I missed any significant points and/or have something wrong altogether.  Open to feedback here across the board.

Thanks again to all, I will mark this issue as closed.

**Comment by merbla** [comment]
If you are using node, there is always https://github.com/trentm/node-bunyan
