### ISSUE TITLE
ReadFrom() appsettings.json?

### ISSUE THREAD

**Issue by dazinator** [serilog/serilog#658]
With dnx projects, we don't use any xml  "app.config" file anymore, instead configuration can come from a variety of different sources, and the default seems to be a json based file `appsettings.json`.

It would be nice if the LoggerConfiguration API would support ReadFrom() an `IConfiguration`.

**Comment by dazinator** [comment]
So you could do something like this:

```
 Log.Logger = new LoggerConfiguration()
                .ReadFrom(configuration["Serilog"]);
```

Then in `appsettings.json`

```

 "Serilog": {
    "serilog:using:Seq": "Serilog.Sinks.Seq",
    "serilog:write-to:Seq.serverUrl": "http://localhost:5341",
    "serilog:write-to:Seq.apiKey": "[optional API key here]"
  }
```

**Comment by nblumhardt** [comment]
Thanks for the sketch! Very keen to have this at v2. Issue tracking it is: #614, so closing this as a duplicate. (Would be great to have some thoughts on how the JSON syntax should look - the option above is great, but some additional structure seems like it would be nice as well.)
