### ISSUE TITLE
Is it possible to map the"Id" data column to a different column name for SQL Server sink?

### ISSUE THREAD

**Issue by vgantonio** [serilog/serilog#661]
I have an existing table for Logs in a SQL Server database and I would like to map the "Id" data column to a different column name ("LOG_UniqueRecordID").  Is it possible to configure this?

**Comment by nblumhardt** [comment]
Hi - no, not currently. I think this is something we'd consider accepting a PR for, however it'd need to cover all the other columns (message, etc.) as well to be generally useful.

The quickest/easiest way to tackle this is probably to grab the code https://github.com/serilog/serilog-sinks-mssqlserver and modify a private copy.

**Comment by nblumhardt** [comment]
Let me know if there's more that we can help with here.

**Comment by vgantonio** [comment]
@nblumhardt  You completely answered my question.  I decided to just rename the column in my existing table.  Thanks for your quick response!
