### ISSUE TITLE
serilog-sinks-elasticsearch does not support elasticsearch 2.0

### ISSUE THREAD

**Issue by jarlelin** [serilog/serilog#662]
Are anyone working on upgrading the serilog-sinks-elasticsearch to use the NEST 2.0 client that supports elastic search 2.0?

I'd be interested in helping out, but want to know if any work has already been started.

**Comment by beruic** [comment]
Same here. Initially you might want to update the NuGet package dependencies so they don't allow upgrade of the Elastisearch.Net package.

**Comment by nblumhardt** [comment]
I think a PR just arrived with this: https://github.com/serilog/serilog-sinks-elasticsearch/pull/23

**Comment by nblumhardt** [comment]
Moved to: https://github.com/serilog/serilog-sinks-elasticsearch/issues/24 (see #450)
