### ISSUE TITLE
MongoDb serilog sink doesn't create capped collections

### ISSUE THREAD

**Issue by davideicardi** [serilog/serilog#665]
MongoDb capped collections need to be explicitly created, now the explicit collection creation is skipped and the `_collectionCreationOptions` field is never used.

See https://github.com/serilog/serilog-sinks-mongodb/blob/master/src/Serilog.Sinks.MongoDB/Sinks/MongoDB/MongoDBSink.cs

**Comment by nblumhardt** [comment]
Hi @davideicardi thanks for the note. https://github.com/serilog/serilog-sinks-mongodb/pull/6 has been submitted with a fix for this - just waiting on final touches, looking good.

**Comment by nblumhardt** [comment]
Fixed via the PR mentioned above. Thanks again!
