### ISSUE TITLE
ElasticSearch Adapter and the temp buffer files

### ISSUE THREAD

**Issue by drusellers** [serilog/serilog#666]
Does ES manage deleting these?
If so what are the properties that need to be configured. I didn't see anything specific on the documentation pages.

**Comment by drusellers** [comment]
It should also be noted that we are running into the issue of clean up with a command line application that generates a unique file name each time it runs so it doesn't step on the toes of other instances of the command line app being run.

**Comment by nblumhardt** [comment]
Hi Dru,

For apps without a long-lived process, it's not a good idea to turn on durable buffering like this. Disposing the root `ILogger` (you have to cast it) or calling `Log.CloseAndFlush()` in the 2.0 beta versions, will flush events to ES without needing the buffer file.

HTH, let me know if you need any help.

Nick

**Comment by drusellers** [comment]
```
  builder.Register(cxt => LoggingBootstrapper.Logger)
                .As<ILogger>()
                .As<IDisposable>()
                .SingleInstance();
```

Would probably help then as well.

**Comment by nblumhardt** [comment]
Yes - though the `As<IDisposable>()` isn't needed - Autofac will work this out dynamically, and disposing is the default behaviour.

https://github.com/nblumhardt/autofac-serilog-integration might be useful for you, not sure if I've pointed this out previously, but should be a good starting point for a better Autofac/Serilog story.

**Comment by nblumhardt** [comment]
Closing, but jump in if there's anything more we can help with.
