### ISSUE TITLE
Is it possible to start different sink when one sink fails?

### ISSUE THREAD

**Issue by dotnetdude** [serilog/serilog#668]
currently we are using serilog sinks seq to write log files seq. In case of any network/hardware failure in accessing seq, is it possible to write the logs into different sinks for example using serilog-sinks-eventlog to write it on windows eventlog?

**Comment by nblumhardt** [comment]
Hi - no, sinks are independent so there's no opportunity to "fall back" from one to another.

If [durable log shipping](http://nblumhardt.com/2014/06/durable-log-shipping-from-serilog-to-seq/) doesn't cover it for you, setting up a local `RollingFile` sink along with whatever network sink you're using is a popular pattern.

**Comment by Refresh06** [comment]
I just implemented a Sink that falls back to Event Log after trying to write to Elasticsearch. It's a simple class that uses the existing Elasticsearch and EventLog sinks.

However I do like the durable log shipping feature of the Seq sink, but wouldn't it be nice to pull this feature into the Serilog implementation and thereby enabling the feature for all sinks without every sink having to implement it?

`Log.Logger = new LoggerConfiguration()
  .WithBuffer("c:\\LogBuffer")
  .WriteTo.Seq("http://my-seq")
  .CreateLogger();`

**Comment by nblumhardt** [comment]
@Refresh06 thanks for the weigh-in. I'd love to make durable buffering a top-level Serilog feature, but the implementations (ES one and Seq one) are fairly intricate and seem to be diverging at this point. It's a challenging design problem to unify them - it'd be great to see but will require a lot of time and effort with no guarantee of success, so I haven't attempted it thus far :-)

**Comment by Refresh06** [comment]
@nblumhardt if only ideas were as easy to implement as they are to come up with ;o)

I completely overlooked the durability feature of the ES sink. Thanks for the pointer, I will start using it immediately.

**Comment by nblumhardt** [comment]
:+1: thanks!
