### ISSUE TITLE
Turn on XML documentation generation for new packages

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#675]
Some missing documentation will have to be added, but shouldn't be very much.

**Comment by tillig** [comment]
FYI, you may have to wait on this until RC2. [There's an `xmlDoc` flag you can add to `project.json`](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/project.json#L12-L13) to enable this, but [it's unclear whether this works in RC1 or not](https://github.com/dotnet/cli/issues/585). I tried it in some of my projects and was not successful.

**Comment by khellang** [comment]
Yeah, `xmlDoc` is a `dotnet`-only feature, AFAIK. It'll all come together when we transition to RC2 and the dotnet CLI :smile:

**Comment by nblumhardt** [comment]
This is available now in `-rc-update1`, so I think we're good to go with:

```json
  "xmlDoc":  true,
```

**Comment by nblumhardt** [comment]
Think we're getting this sorted incrementally as we update packages for RC2.
