### ISSUE TITLE
Installation of the nuget package for Serilog.Extras.MSOwin requires no existsing nuget package "SerilogWeb.MSOwin"

### ISSUE THREAD

**Issue by dprochownik** [serilog/serilog#676]
Hi,

When I tries to install the nuget packages Serilog.Extras.MSOwin I got an exception. The above package requires "SerilogWeb.MSOwin" as a dependency, but such package does not exists in the nuget.org repository.

Am I missing something or there is a bug?

**Comment by nblumhardt** [comment]
Thank you for the note; the correct package is:

https://www.nuget.org/packages/serilogweb.owin

I've fixed the obsoletion notice to point to the correct package name.
