### ISSUE TITLE
ColoredConsole warning level output properties are unreadable

### ISSUE THREAD

**Issue by BlairPaine** [serilog/serilog#680]
Using Serilog to provide output in PowerShell using ColoredConsole.  When I log at warning level the text is in Yellow.  However, the properties are white text on white background making it unreadable.  For example:

Screenshot = http://imgur.com/UX8YnTD

Using Serilog version 1.5.1.0.

**Comment by nblumhardt** [comment]
Yuck! Thanks for the heads-up, Blair. PowerShell uses a slightly different palette to the regular console, so the mapping has gotten us into trouble here.

Are you able to switch to https://github.com/serilog/serilog-sinks-literate? It's much nicer output in my humble opinion, and shouldn't exhibit this issue.

(An alternative scheme for coloring `Warning` events would also be an option, if you have some ideas and have time to send a PR.)

**Comment by blairpaine** [comment]
Many thanks for the quick reply @nblumhardt .  I will try out the literate sink and if suitable use that in the next version of our scripts.

**Comment by nblumhardt** [comment]
How'd you go? Feel free to ping this if you think it needs reopening. Cheers!
