### ISSUE TITLE
Multiple services trying to write into the same file

### ISSUE THREAD

**Issue by mcastillo86** [serilog/serilog#681]
I have 4 wcf services running on IIS, each one has its own appPool. Those services are in the same server and write into the same log file using serilog. I've noticed the following:
Service A writes to "log.txt" file. When service B is trying to write into that file at the same time, serilog creates a new file called "log_001.txt" . If Service C tries to write into any of those files, when locked by the other ones, it will create a new file "log_002.txt". The thing is that When service D tries to write, it can't and no "log_003.txt" is created as I would expect. My question is: does "log_003.txt" wasn't created because I need to do some additional configuration or because it is limited to 2 files only?

Best regards,
Mario

**Comment by nblumhardt** [comment]
Hello - thanks for the note.

The Serilog file/rolling file sinks support a single process only. For multi-process scenarios, using either separate filenames, or one of the non-file-based sinks, is necessary.

(Alternatively, it's possible to create a custom/forked file sink with different synchronisation behaviour if you want to go down that path.)

Let me know if you need any further help; closing this as it's a known design choice. I've added an additional note here to make sure it's clear: https://github.com/serilog/serilog/wiki/Provided-Sinks#rolling-file

**Comment by adaviding** [comment]
FYI:  The boost logger will not allow the same process to write into the same file, it always starts a new file.  It never tries to append to the end of an existing file that it did not create within the process.  IMHO:  That is the best design choice.  It is simple to implement and it solves all kinds of problems.

**Comment by nblumhardt** [comment]
@adaviding :+1: that's a solid approach. In Serilog, just computing the filename when the process starts is enough to get this working:

```csharp
var myLogFile = $"logs/myapp-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid:n}.txt";
Log.Logger = new LoggerConfiguration()
    .WriteTo.File(myLogFile)
    .CreateLogger();
```

(Filename generation schemes are of course another can of worms .. :-) )

**Comment by Chiel92** [comment]
Is it still necessary to generate a unique filename? The option suggested by @adaviding seems much more solid and clean. Having this as a feature request makes sense.

**Comment by greuelpirat** [comment]
@Chiel92 I also came here for logging with multiple processes.

I found: https://github.com/serilog/serilog-sinks-file#shared-log-files

Looks like this is the way to go now.

**Comment by as-atalavera** [comment]
@greuelpirat Awesome!
Thank you!
Great, it is the solution that I needed exactly
It's very simple, just add **shared: true**
Example: 
.WriteTo.File(path, rollingInterval: RollingInterval.Day, shared: true)

**Comment by adaviding** [comment]
https://github.com/serilog/serilog/issues/681#issuecomment-539246868

It turns out the approach with the Boost logger works on Linux but not Windows.
