### ISSUE TITLE
.NET Core support doesn't work on Universal Windows App

### ISSUE THREAD

**Issue by HakanL** [serilog/serilog#684]
I'm trying to add pre-release version 2.0.0-beta-507 to a Universal Windows App (using .NET Core) and I'm getting an error on dependencies. See this log file:
http://pastebin.com/UzH7eVCT

**Comment by khellang** [comment]
I believe that once we ship with `netstandard`, this should be fixed. In the meantime, should we add `netcore50`? See https://github.com/structuremap/structuremap.dnx/blob/master/src/StructureMap.Dnx/project.json#L26

**Comment by HakanL** [comment]
I think you should add "dotnet" and also add some to your nuspec files. See this commit that I do for another project: https://github.com/HakanL/FluentScheduler/commit/555582ecac0754eae695cfd0b29901a0fe924c3b

**Comment by khellang** [comment]
We're already on `dotnet5.x` (which in theory already should support UWP). We're using project.json to build our packages, so no nuspec is necessary. If we were to add UWP support, it'll have to be through `netcore50` for now. That's also [how MS supports it](https://github.com/aspnet/DependencyInjection/blob/1.0.0-rc1/src/Microsoft.Extensions.DependencyInjection/project.json#L25-L41). `netstandard` will take care of this in time for RTM, [I'm certain](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms).

**Comment by HakanL** [comment]
I'm still learning the .NET Core business, but in (my current) view, `dotnet5` is only for ASP.NET Core, it's not compatible with UWP, and I assume that's why I get the errors. Project.json is to configure the dependencies, nuspec is for the nuget package you're building/publishing, I would assume you need both? The referenced commit for FluentScheduler made it work in UWP, but I actually didn't try it in ASP.NET Core.

**Comment by HakanL** [comment]
Btw I tried to add the FluentScheduler to an ASP.NET 5 project and it worked fine.

**Comment by khellang** [comment]
> `dotnet5` is only for ASP.NET Core, it's not compatible with UWP

`dotnet5.x` is an early version of `netstandard1.y` where y = x - 1, so `dotnet5.1 == netstandard1.0`. You can read more about the platforms that the different `netstandard1.x` TFMs support in the [.NET Standard Platform](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) document.

> Project.json is to configure the dependencies, nuspec is for the nuget package you're building/publishing, I would assume you need both?

Not really. project.json is both a place to configure dependencies, and a place to define all metadata that goes into the final package. It's a superset of nuspec, if you will. We've already used project.json to produce the 2.0 prerelease packages that you can find on NuGet.org. nuspecs are a thing of the past in the new model.

> The referenced commit for FluentScheduler made it work in UWP, but I actually didn't try it in ASP.NET Core.

Again, if we added `netcore50` as a supported TFM, you'd be able to reference the package from a UWP app, but ideally we'd like to just wait for the `netstandard` TFMs to settle, before we move over to those. They should, in turn, allow you to reference the package from a UWP app.

**Comment by HakanL** [comment]
I see, I didn't know project.json replaced nuspec, thanks for the info.

So the issue may be that UWP doesn't "support" dotnet5/netstandard yet. But maybe you're right that netcore50 support will help, I'm happy to try it out if you want to build a private nuget pkg.

**Comment by birbilis** [comment]
"dotnet" is like a generic moniker - probably should add it

**Comment by HakanL** [comment]
It's seems that dotnet is the lowest common level, not sure if serilog is compatible on that level. But I also assume dotnet will be replaced with netstandard, but that means UWP has to adopt netstandard too.

**Comment by khellang** [comment]
Have you guys even looked at the document about `netstandard` that I've linked a coupled of times? `dotnet` is going away, `netstandard` is the way forward.

**Comment by birbilis** [comment]
it's like quicksand recently I feel

btw, it mentions this:

NOTE: The netstandard TFM does not work in packages as yet. It's still implemented as dotnet. Please follow the issues for more details and progress updates.

**Comment by khellang** [comment]
> The netstandard TFM does not work in packages as yet. It's still implemented as dotnet.

Exactly. That's why we're still following Microsoft in supporting `dotnet5.1` for the RC1 release and will move to the `netstandard` equivalent, `netstandard1.0`, for RC2.

**Comment by HakanL** [comment]
Yes I've read it, but it didn't solve the issue I had trying to use Serilog in my UWP project today. But I understand if you don't want to add anything that goes away, it's just too bad I can't use Serilog yet.

**Comment by khellang** [comment]
@HakanL Maybe if you send a PR and ask @nblumhardt nicely, he'll push a new pre-release package for you?

**Comment by birbilis** [comment]
is there a problem having redundant monikers? 

guess you could add dotnet and it could deploy to folder netstandard1.0 or something, so that in the future you just rename the moniker and keep the folder

**Comment by nblumhardt** [comment]
@HakanL have you tried the 1.5 release? It should work already on UWP via Profile259, as I understand.

Sink support isn't ideal, but it should be more reliable until the whole `dotnetstandard1.0.5.1` thing is flushed out. Let me know if this doesn't help.

It's hard work keeping on top of TFMs at the moment, and of limited benefit making changes since there's a major revision (hopefully) only a few weeks away. Hope you'll bear with us while we ride it out :-)

**Comment by HakanL** [comment]
Yes, 1.5 works, but I was trying 2.0 since I was using the Microsoft.Extensions.Logging framework and there was a sink which I think required 2.0. So I wanted to report that it didn't work.

**Comment by nblumhardt** [comment]
Thanks @HakanL - hopefully some updates due here after RC2.

Cheers!

**Comment by nblumhardt** [comment]
Looks like we're set now with RC2; please reopen if you hit any issues @HakanL - thanks!

**Comment by HakanL** [comment]
Cool, I will, thanks!
