### ISSUE TITLE
Q: Pushing Property on LogContext in Concurrent setup with multiple loggers

### ISSUE THREAD

**Issue by pardahlman** [serilog/serilog#685]
Hi Seriloggers - thanks for a great logging framework :100:,

I have a bunch of applications that communicate over RabbitMq. Application A is calling Application B that publishes messages for Application D and Application E. You get the idea :smiley:. A `GlobalMessageId` is being passed along by the underlying communication framework to each of the message handlers

```csharp
subscriber.SubscribeAsync<BasicMessage>((message, context) =>
{
	var msgId = context.GlobalMessageId; //passed between handlers
	return _businessLogic.ProcessAsync(message.Prop); // call to underlying business layer
});
```
We're using the [Serilog Elastic Sink](https://github.com/serilog/serilog-sinks-elasticsearch) to push log messages to Elastic. Now, what I want to do is to enrich the logs with the `GlobalMessageId`. Looking at the the [documentation](https://github.com/serilog/serilog/wiki/Enrichment) this is close to what I want to do

```csharp
using (LogContext.PushProperty("B", 1))
{
    log.Information("Carries A = 2 and B = 1");
}
```
The Serilog logger is instanciated in each class like so

```csharp
private static readonly ILogger Logger = Serilog.Log.ForContext<MyService>();
```

Now to my questions

*Propegate dynamic properties*
Is there a way to share the dynamically added properties between loggers? In the example above, `_businessLogic` is a separate class with its own logger. Any other practices that you recommend?

*Dynamics properties and async calls*
The underlying communication framework invokes the message handler method in an async manner, and the business logic also implements async methods, meaning that the same thread can be at different places in `_businessLogic.ProcessAsync(message.Prop)` for different requests. It could be invoked on different threads, too. If I would use the dynamic property as described in the documentation it would be something like this

```csharp
subscriber.SubscribeAsync<BasicMessage>((message, context) =>
{
	var msgId = context.GlobalMessageId; //passed between handlers
        using (LogContext.PushProperty("GlobalMessageId", msgId))
        {
            return _businessLogic.ProcessAsync(message.Prop); // call to underlying business layer
        }
});
```
The first problem would be that the task is return, and so the using statement triggers `dispose` and the `GlobalMessageId` is removed. I'm hesitant to `await` this call, as it would decrease the message handling throughput. Is the dynamic pushing of properties built for concurrency?

Any input or ideas are most welcome!

Best regards,
Pär

**Comment by nblumhardt** [comment]
Hi Pär,

Awaiting is needed if you want to flow the contextual properties. Otherwise, there's nothing actually linking the original and new execution contexts once ProcessAsync() has returned.

LogContext properties will flow even if the callee is using a different ForContext()-created ILogger, so long as they're attached to the same pipeline.

If you just want to avoid an await in the message handling loop, you could do:

```csharp
subscriber.SubscribeAsync<BasicMessage>((message, context) =>
{
    var msgId = context.GlobalMessageId; //passed between handlers
    return Task.Run(async () =>
    {
        using (LogContext.PushProperty("GlobalMessageId", msgId))
        {
            return await _businessLogic.ProcessAsync(message.Prop); // call to underlying business layer
        }
    }
});
```

(Forgive the inevitable syntax errors here :-))

HTH!

**Comment by pardahlman** [comment]
@nblumhardt thanks! I'll try to implement parts of this tomorrow and get back to you what my findings are (if any).

**Comment by pardahlman** [comment]
@nblumhardt it worked perfectly! I benchmarked the `Task.Run` code you proposed to making the message handler it self `async`, and the latter had much better through put.

```csharp
subscriber.SubscribeAsync<BasicMessage>(async (message, context) =>
{
    var msgId = context.GlobalMessageId;
    using (LogContext.PushProperty("GlobalMessageId", msgId))
    {
        return await _businessLogic.ProcessAsync(message.Prop);
    }
});
```

This issue is resolved as far as I'm concerned - closing it now!
