### ISSUE TITLE
"Reusing" Serilog destructuring concepts

### ISSUE THREAD

**Issue by colin-young** [serilog/serilog#688]
Has anyone ever tried to repurpose the `IDestructuringPolicy` for other uses outside Serilog? I have already created an encrypting policy that uses an encryption attribute on a property to signal it needs to be encrypted before logging. I'd like to be able to do the same thing when I'm copying my properties into DTOs and right now I'm looking at having to implement my own (probably much less good) version of the `ILogEventPropertyFactory`.

I should point out that I haven't quite got my head around the full details of exactly how everything hangs together just yet.

**Comment by nblumhardt** [comment]
Hi Colin, hope you figured something suitable out here! Closing as I don't think there are any instances like this I'm aware of, let me know if you turned anything interesting up!

**Comment by colin-young** [comment]
Eventually it finally sunk in that the DestructuringPolicy is really just a strategy pattern. I ended up implementing my own, inspired by the design of Serilog's code. It's quite as clean an implementation, but over time I'm sure I'll get it there.
