### ISSUE TITLE
Serilog and Silverlight

### ISSUE THREAD

**Issue by birbilis** [serilog/serilog#690]
has anyone used Serilog with Silverlight (web apps I mean)?

interested since I see there is a way to write from Serilog to Application Insights which doesn't have Silverlight support itself currently

**Comment by nblumhardt** [comment]
Hi George,

Serilog's AI support is via the official client I think, so probably not an option anywhere AI doesn't itself support.

I don't think Serilog 1.5 has any Silverlight support, but you may be able to rebuild from source to cover most features on that platform. Usage is very low these days so it's unlikely we'll target it in the future, sorry.

Interested to hear how you go and if you hit any roadblocks let me know, happy to help wherever I can.

Regards,
Nick
