### ISSUE TITLE
Overriding Timestamp in the LogEvent class

### ISSUE THREAD

**Issue by syska** [serilog/serilog#691]
I'm trying to do some post processing of event that have been logged in a other system so I can't hook into that ... but I can do some post processing with Serilog and send it to a system aggregate all our logs.

But ... the option to override the LogEvent.Timestamp almost seem impossible since all classes is internal and/or sealed.

Enrichers is run before properties is being added to the event or else I could have used reflection there  to set if ( Have tried and now I only need the right value ). I could do more hacks ... but I'm really hoping that I'm missing something here.

So all ideas is most welcome ... 

This is going to be used with either https://getseq.net/ or https://www.elastic.co/ ...

**Comment by nblumhardt** [comment]
Hi Mikael,

The only way to set `Timestamp` currently is through the constructor:

https://github.com/serilog/serilog/blob/master/src/Serilog/Events/LogEvent.cs#L40

When the events are logged by the other system, do you control how they're passed to Serilog? If so, constructing the `LogEvent` appropriately and calling `ILogger.Write()` should cover it.

If not, can you send a little more detail around the scenario - how do you want to modify the timestamp, and why is it being created incorrectly in the first place?

If all else fails, doing this at the sink layer is always an option, happy to help work through that also.

Cheers,
Nick

**Comment by syska** [comment]
Hi @nblumhardt 

The first problem is that most classes is internal ... the SeqSink and HttpLogShipper which I know is in a other assembly ... so not really your problem i know.

Most of the classes is internal ... even the `MessageTemplateProcessor` and the `PropertyValueConverter`. Any reason for this?

I'm actually reading these from a database ... also have thought of reading them from the event log and them ship them to this system though Serilog.

I really don't want to modify the Timestamp, I want to set to arcording to the source of the events I already have.

This is being done because the system is already running ... but I would love to use Serilog on a new system in the future if I get the chance for it.

If it's being done at the Sink level, I still need to store the value in the "Properties" list and then remove it.

Might have missed something here ... 

( By the way, love Serilog, puts the fun back to logging )

**Comment by nblumhardt** [comment]
Thanks for the follow-up.

The quickest way to import logs into Seq is via HTTP - it might help side-step some of the issues here: http://docs.getseq.net/docs/posting-raw-events. I'd guess Elasticsearch has similar options.

`PropertyValueConverter` and friends aren't necessarily going to be useful in this scenario. You can create events without them like this:

```csharp
// Can use this multiple times
var parser = new MessageTemplateParser();

var evt = new LogEvent(
    DateTimeOffset.Now,
    LogEventLevel.Error,
    new InvalidOperationException("Hello!"),
    parser.Parse("Failed while scanning {Drive}"),
    new[] {
        new LogEventProperty("Drive", new ScalarValue("C:"))
    });
```

At this point though you hit the issue of needing an `Exception` object rather than a `string`, so it's still probably more effective to send HTTP payloads directly instead.

Let me know which approach looks best and I'll help work through the details :+1: Cheers!

**Comment by syska** [comment]
First thing I'm trying it just to get the log events into some sort of searchable format ... using some elmah logs but the search blows(there is no search) ... and the format right now is static, so I can't really take advantage of all seq features :-( Maybe I will look into ElasticSearch also.

Doing this now:
`var logEvent = new LogEvent(error.TimeUtc, LogEventLevel.Error, null, new MessageTemplate(error.Message, new List<MessageTemplateToken>()), new LogEventProperty[0]);
                    logEvent.AddScalar(nameof(Customer), Customer);
                    logEvent.AddScalar(nameof(Environment), Environment);
                    logEvent.AddScalar("MachineName", error.Host);
                    logEvent.AddScalar("Type", error.Type);
                    logEvent.AddScalar("Source", error.Source);
                    logEvent.AddScalar("Detail", detail);
                    logEvent.AddScalar("StatusCode", error?.StatusCode.ToString());
                    logEvent.AddScalar("Application", error.Application);
                    logEvent.AddScalar("ErrorId", error.ErrorId.ToString());`

Seems to work great ... just need to get some data in and see how it performs.

Next ... I'm running this as a ConsoleApp ... and now I see why i really should not do it. Since I'm using the "buffer" which I LOVE BIG TIME ... DurableSeqSink ... 

Think I'm just going to let it run for 10 seconds afterswords every time ... to let it empty the queue of items ... really don't matter. But if you have any other way to watch when a queue is empty.

I know all this is very hacky, but this is to show it off with some more "real" data other than saying ... this looks very cool ... lets spend alot of time on it ... I love it ... but I need to convince some people that we should start using it :-)

**Comment by nblumhardt** [comment]
Excellent, glad you have something working. Yeah, the durable mode is only generally suited to long-running processes :+1: 

Just one tip, when importing unstructured logs, instead of passing `error.Message` as the `messageTemplate`, using `"{Text}"` as the template (`new MessageTemplateToken[] { new PropertyToken("Text"...) }`) and then passing `error.Message` in a scalar property called `"Text"` will help keep the proliferation of unique event types under control. Not a big deal, but it also prevents messages that contain `{` from being mangled.

HTH!

**Comment by syska** [comment]
Sweet @nblumhardt  :-)

Now I also just realized you built both Serilog and Seq...

Ahh, I will make that small change ... good input. I will probably also switch to the non durable to avoid writing to disk if the server if down or rebooting ... since the process will not flag the input as completed and continue with the same logs afterwards.

**Comment by nblumhardt** [comment]
Great - let us know how you go :-)
