### ISSUE TITLE
Async friendly stack traces

### ISSUE THREAD

**Issue by Lavinski** [serilog/serilog#702]
As you probably know async stack traces can be a bit hard to read.

I'd like to run something like https://github.com/aelij/AsyncFriendlyStackTrace over the stack trace so that each Sink only shows the async-friendly format.

How would I do this using Seq?

**Comment by nblumhardt** [comment]
Hi Daniel!

I think there's another discussion at #521 - would be great to figure out how to move this forward a bit. The library is really impressive, but the reflection/heuristics don't seem like a great match for bringing into the core project.

Give it's a formatting concern, would it make sense to...

* Add an `AsyncStackTrace` property using an enricher?
* Somehow override JSON formatting at the sink to do it there?
* Somehow do the unmangling server-side, i.e. in Seq, using a different techique?

Really interested in your thoughts, seems like something that would be great to move on....

**Comment by Lavinski** [comment]
Hey Nick!

Yeah, I agree, putting it in the core doesn't sound like the way to go. I was hoping for a more generic method of overriding the `Formatter`s so that I could easily apply the formatting across multiple Sinks. So I think option 2 would be ideal. 

You could get the `AsyncStackTrace` using an enricher, however I'm not sure if this would result in a good user experience in Seq or other Sinks.

Should I move the discussion over there? Feel free to close this thread if so.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Here's good, but let's move to #451 to keep everything in one place. Cheers!

**Comment by joelweiss** [comment]
@nblumhardt You probably meant #521

**Comment by nblumhardt** [comment]
Thanks @joelweiss, so I did :-)
