### ISSUE TITLE
Serilog in ASP.Net Core and Class Library

### ISSUE THREAD

**Issue by roqz** [serilog/serilog#705]
I have a ASP.NET Core RC1 Web Api project in which I use Serilog. So far no problem.
No I want to Reference a .NET 4.5.1 class library which internally uses Serilog for logging.

As soon as I add the new reference and try to rebuild I get following errors:

> DNX 4.5.1 error CS0433: The type 'RollingFileSink' exists in both 'Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' and 'Serilog.Sinks.RollingFile, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

> DNX 4.5.1 error CS0433: The type 'LogContext' exists in both 'Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' and 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

Any Ideas how to resolve this? Or is this combination not possible at all?

**Comment by merbla** [comment]
Hi @roqz,
As of 2.0 (beta) the rolling sink has been split from the main Serilog package.  Previously (1.5) had some of the core sinks baked into the package.

I am not sure that you will be able to mix and match Rolling Sink (2.0-beta) with Serilog (1.5).

Have you tried removing all the 2.0-beta packages and rely solely on the 1.5 package?
