### ISSUE TITLE
Unable to run unit tests in VS 2015

### ISSUE THREAD

**Issue by chaitanyagurrapu** [serilog/serilog#706]
Hi,
I ran the Build.ps1 which restored all the packages, did the build, ran the test etc.
![image](https://cloud.githubusercontent.com/assets/853059/14142749/d81dd5c2-f6ca-11e5-9a43-33f124b556a9.png)

But when I try to run the tests through visual studio to debug a few tests, I am getting errors. The VS test runner doesn't find any tests in the solution and the R# test runner seems to be looking in the wrong location.

![image](https://cloud.githubusercontent.com/assets/853059/14142850/7e999fb2-f6cb-11e5-9b92-b05f96aa6bec.png)

Quick googling makes it seem similar to this issue regarding R# xunit runner not being up to date with its DNX support. http://stackoverflow.com/questions/32333805/test-explorer-not-discovering-xunit-tests-vs-15. But my current version is 2.2.10 so it should be well past the issue mentioned in the stackoverflow question.

![image](https://cloud.githubusercontent.com/assets/853059/14142948/f62d7378-f6cb-11e5-9f8e-ee6c9d2b29b8.png)

Was wondering if this was a known issue that will be resolved in time once the dnx dust settles or am I making a silly mistake and overlooking something or missing a workaround?

**Comment by merbla** [comment]
Hey @chaitanyagurrapu, this is an dnx/xunit issue as I understand.  I have only been using the .ps1 to test when doing the dnx work.  

I think `dotnet test` has been out for a bit however we have not changed over.

@khellang do you know of any changes upcoming re: XUnit testing.

**Comment by chaitanyagurrapu** [comment]
Thanks for the quick reply @merbla . Just for my understanding, if you needed to, how would you step through/debug a unit test? Do you get the visual studio attach/debug experience? Or is your typical workflow to `Console.WriteLine()` to trace your way though the application?

**Comment by khellang** [comment]
You can just select the "test" command in the Visual Studio UI and press F5/the play button to debug unit tests.

**Comment by chaitanyagurrapu** [comment]
Nice. I knew it would be something simple like that. :+1:
