### ISSUE TITLE
New Slack Sink

### ISSUE THREAD

**Issue by marcio-azevedo** [serilog/serilog#707]
New Slack Sink at https://github.com/marcio-azevedo/serilog-sinks-slack/.

**Comment by merbla** [comment]
Fantasic! @marcio-azevedo 

Updated the list [here](https://github.com/serilog/serilog/wiki/Provided-Sinks)

**Comment by marcio-azevedo** [comment]
Thanks! And congratulations for the awesome Serilog project!
