### ISSUE TITLE
UTC Timestamp flag at a global level?

### ISSUE THREAD

**Issue by patrick-steele** [serilog/serilog#708]
I've been looking at Serilog and recently started writing my logs to an Azure DocumentDB.  One of the first things I noticed was that the timestamp on the logs was the local time of the machine generating the log message -- not UTC.  I searched the issues to see if this was something someone else had run into and I found a [pull request to make this configurable for the MSSQL sink](https://github.com/serilog/serilog/issues/392).  I was going to make a similar change and pull request for the AzureDB sink but then I wondered if this is something that should done at a global level.  By having the timestamp tweaked at a per-sink level, you could get mixed results between logs.

Has this been considered for Serilog?  A global flag (which defaults to false) that could be enabled so the `LogEvent.Timestamp` is initialized to `DateTime.Now.ToUniversalTime()` instead of `DateTime.Now`?

**Comment by nblumhardt** [comment]
Hi @patrick-steele - thanks for the note. The timestamp in Serilog is `DateTimeOffset.Now`, which carries a timezone offset when rendered in ISO 8601 format like: `"2016-04-04T15:04:34.9282770+10:00"`. Some back-ends handle this fine and convert correctly, others need UTC.

If DocumentDB needs UTC time and local time is being sent, that may be a bug in the DocumentDB sink. If a sink's back-end is UTC-only, then the value should be sent as `logEvent.TimeStamp.UtcDateTime`, i.e. `logEvent.TimeStamp.UtcDateTime.ToString("o")`.

If you have a chance to open up a discussion/PR on the docdb sink that would be great, I'm not knowledgeable regarding its format/expectations so can't progress this much further here.

**Comment by patrick-steele** [comment]
Ah, I see.  I re-read the original [issue with MSSQL sink](https://github.com/serilog/serilog/issues/392) and realized that was specific to the SQL `DATETIME` column not storing timezone information.  Azure DocumentDB serializes everything to JSON and the Timestamp does contain the timezone information (don't know how I missed that the first few times I looked at it..)  Here's an example:

    "Timestamp": "2016-04-01T14:27:41.578973-04:00"

Thanks for the follow-up.

**Comment by nblumhardt** [comment]
No worries, glad to help.
