### ISSUE TITLE
Enrich Log with Id and return to User

### ISSUE THREAD

**Issue by jedielson** [serilog/serilog#709]
Hi.

I'd like to return to user an id like a Guid to my user when I generate Logs for Error or Fatal levels at my app.

I was thinking about use an enricher to save it as a property.

So, how can I recover the generated Guid?

And, there is another way to do it?

Thanks for all!!!

**Comment by patrick-steele** [comment]
Is this ASP.NET web application?  If so, the `HttpContext.Current` will return the currently active `HttpContext`.  From there, you'll have access to the users session (perhaps the Guid is stored there?).

Here's an example of an [enricher that includes the current session ID](https://github.com/serilog-web/classic/blob/master/src/SerilogWeb.Classic/Classic/Enrichers/HttpSessionIdEnricher.cs).

**Comment by nblumhardt** [comment]
I tend to do it as:

```csharp
var errorId = Guid.NewGuid();
Log.Error(ex, "Error occurred ({ErrorId})", errorId);
```

I.e. just include it in the log message and all is well! :-)

**Comment by jedielson** [comment]
It will be used most part with asp.net web apps... but can be used with desktop apps too.

It's kind of an encapsulation to give some pattern to the messages generated by developers, and the way users are notified of errors.

I just don't want put this at message, cause it turns hard to users to read in our Log Viewer (something like Seq)

Is there any chance that it can be added like a feature?

Thanks for the Help.

**Comment by nblumhardt** [comment]
Thanks for the extra information. To be honest, I can't see us adding this as a core feature - we'd have to solve all the same design challenges you're experiencing, but in an even more general/generic way. Sometimes the simple solutions are the best :-)

You could wrap up your error logging into an extension method?

```csharp
public static Guid ErrorWithId(this ILogger logger, Exception ex, string messageTemplate, params object[] args)
{
    var id = Guid.NewGuid();
    var withId = logger.ForContext("ErrorId", id);
    withId.Error(ex, messageTemplate, args);
    return id;
}
```

HTH, 
Nick

**Comment by jedielson** [comment]
Ok Nick.
Your solution solve my problem!

Thanks for your Help!!! 

0/
