### ISSUE TITLE
Formatting a type in a specific way

### ISSUE THREAD

**Issue by SeanFarrow** [serilog/serilog#710]
Hi,

I'm in a situation where I'd like to format a type (A TimeSpan in this case) in a specific way. Currently I'm doing the formatting on every log statement, but was wondering whether there is an extension point to allow me to control the formatting of a specific type so I can reuse code.
Any help appreciated.
Kind regards
Sean.

**Comment by nblumhardt** [comment]
Hi Sean,

No, nothing specifically like this exists; one option that may work depending on the rest of your logging pipeline is to write an `ILogEventEnricher` that uses `logEvent.AddOrUpdateProperty()` to replace any property values of type `TimeSpan` with a formatted string.

It's a lossy process unless you also stash the original timespan in something like `logEvent.AddPropertyIfAbsent("OriginalXyz", originalValue)`.

Hope this at least opens up some options.

Cheers,
Nick
