### ISSUE TITLE
DisconnectedContext exception when LogContext.PushProperty is used in a unit test

### ISSUE THREAD

**Issue by patrick-steele** [serilog/serilog#712]
Using Visual Studio 2015 Enterprise (Update 1), I'm getting an exception at the end of a unit test when the code being tested uses `LogContext.PushProperty`.  The error is:

> Managed Debugging Assistant 'DisconnectedContext' has detected a problem in 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\te.processhost.managed.exe'.
> 
> Additional information: Transition into COM context 0x744200 for this RuntimeCallableWrapper failed with the following error: The object invoked has disconnected from its clients. (Exception from HRESULT: 0x80010108 (RPC_E_DISCONNECTED)). This is typically because the COM context 0x744200 where this RuntimeCallableWrapper was created has been disconnected or it is busy doing something else. Releasing the interfaces from the current COM context (COM context 0x744090). This may cause corruption or data loss. To avoid this problem, please ensure that all COM contexts/apartments/threads stay alive and are available for context transition, until the application is completely done with the RuntimeCallableWrappers that represents COM components that live inside them.
> 

I've placed reproduction code in a [public gist](https://gist.github.com/patrick-steele/926e90543c73a271c01f6d5139db19c0).  The code is compiled for .NET 4.6.1.  If you comment out the one line that sets the `context` variable, the unit test runs fine.  Actually, the unit test code completes (all my log message reach their sinks), but after the unit test execution completes, but before the test runner shuts down, the above exception is raised.

**Comment by nblumhardt** [comment]
Thanks for the information. The VS test runner and `LogicalCallContext` don't get along particularly well.

I got rid of the issue with `FreeNamedDataSlot()`:

```csharp
        private void SomethingElse()
        {
            var machineName = Environment.MachineName;

            IDisposable context = null;
            try
            {
                context = LogContext.PushProperty("Machine", machineName);
                Log.Information("Five is {five}", 5);
                Log.Debug("TickCount: {tc}", Environment.TickCount);
            }
            finally
            {
                context?.Dispose();
                CallContext.FreeNamedDataSlot(typeof(LogContext).FullName);
            }

            Log.Information("Something is done");
        }
```

At this point, the _contents_ of the log context is empty, but there's still an empty stack sitting in the data slot.

I think the solution here is to detect the "empty" stack case and free the slot in:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs#L229

```csharp
            set
            {
                if (value.IsEmpty)
                {
                    CallContext.FreeNamedDataSlot(DataSlotName);
                }
                else
                {
                    var context = GetContext(value);
                    CallContext.LogicalSetData(DataSlotName, context);
                }
            }
```

I am marking this "up for grabs" as I don't have a moment right now to properly test this. I'll try to get into it further later in the week, but in the meantime please feel free to send a PR if it's an option.

Thanks for the report and repro!
Nick

**Comment by patrick-steele** [comment]
Thanks Nick.  Unfortunately, I can't devote any time to this either.  However, in this case, I was just looking to add a piece of (sometimes large) XML to a log event, but didn't want it part of the rendered message as well as a property so I just created a new logger:

    var logger = Log.Logger.ForContext("JobXML", someXml);
    logger.Information("Processing start: {JobID}", id);

Gets me around this issue for now.  :)

**Comment by nblumhardt** [comment]
Good to hear. I think #109 might help with this.
