### ISSUE TITLE
Property enrichment but still required in call to actual write call?

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#715]
Hi,

I apologise for the cross post from [SO](http://stackoverflow.com/questions/36614390/serilog-property-enrichment-but-still-required-in-call-to-actual-write-call) but I am confused as to how I make use of property enrichment functionality when a call to ILogger.Verbose() et. al uses the ordinal position to pass values to the internal message formatter.

Could you have a look at the SO item and either reply there or here as to what I am missing?

**Comment by nblumhardt** [comment]
No worries, following up on SO.
