### ISSUE TITLE
Understanding some architecture things....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#716]
Hi,

I am configuring Serilog for use within our platform and have a couple of architecture questions. I have read the docs, but could not find anything definitive. I have not read the code in detail either which I realise I could do, but I figured I would ask first ;-)

We are planning to use Serilog to write to a number of sinks namely:

1. SQL Server
2. DataDog
3. Email
4. UDP

Most of the time we will have 1..3 running, turning on 4. as needed. Not sure if they will have different minimum levels yet but for purposes of this discussion lets say they are all set to Verbose.

1) Performance

When a call is made to ILogger.Write() is this ultimately a blocking call until all the sinks have been serviced? Or does the call return immediately with the payload being placed on an internal Serilog queue for processing? I am just considering the use case where there are say 100 log calls in a second and what happens.

2) ILogger teardown / setup

As I [understand it](https://github.com/serilog/serilog/issues/714) there is no way to dynamically manipulate what an ILogger is doing once CreateLogger() has been called. As we will be primarily using it in an MVC setup and to work around this issue we plan to use the following approach:

- Create ILogger logging instance at application startup from our settings store and store it as a global singleton
- Protect access to be single threaded
- Accessing the singleton will check our settings store (which is v.fast) to see if logging settings have changed. Should this be the case then teardown the current ILogger and create a new one based on the new settings ==> In this way we can "dynamically" change what logging sinks are turned on, their levels etc. merely by making a change in our settings store and not having to worry about restarting the app etc.

Aside from calling dispose are there any other concerns I should have with this approach? As all the sinks are 3rd party I am wondering if I am going to cause some issues here?

Appreciate any insights you can give me.

**Comment by nblumhardt** [comment]
Hi Donovan,

1) This is sink-specific; some sinks such as the *File and *Console families will emit the event synchronously. Most network-based sinks will add the event to an internal queue and send events asynchronously, either singly or in batches.

2) The `LoggingLevelSwitch` and sub-loggers @IanYates mentioned in #714 are usually sufficient for implementing these kinds of scenarios; the logging level is not global - it's per-pipeline - and `WriteTo.Logger()` can be used to run a sink in a pipeline of its own. Probably best to check these two things out in detail and follow up via #714.

HTH,
Nick

**Comment by natiki** [comment]
Hi Nick,

Just making sure I have this right.

1) Apologies for the basic time line figures. So as each sink is processed sequentially internally the time taken for the top level Write() call to complete will always be the time taken internally by each sink?

If I have no sub loggers:

> **Time:**         _Start_............................................._End_
> **Pipeline 1:** ILogger.Write() ==> Sink1..... Sink2.... Sink3

If I have 2 sub loggers (Pipelines 2 & 3) off the top logger (Pipeline 1):

> **Time:**         _Start_....................................................................................._End_
> **Pipeline 1:** ILogger.Write() ==> Sink1..... 
> **Pipeline 2:** .........................ILogger.Write() ==> Sink2. 
> **Pipeline 3:**....................................................................ILogger.Write() ==> Sink3

Pipeline 3 cannot start until Pipeline2 completes back to the original write() call from Pipeline1?

2) Yep sorry I was not clear about the logging level. I realise it is per pipeline. However basically whether I have a single pipeline or pipelines or not I cannot dynamically change the composition of the logger after the call to CreateLogger()?

**Comment by nblumhardt** [comment]
NW.

1. Yes, that's it.
2. No, you can't, but by creating the full topology up front you can turn individual loggers on/off by changing their level, so the effect is the same

Cheers,
Nick

**Comment by natiki** [comment]
1. So a feature request for v2 would be to decouple the processing Q inside ILogger so that the caller is insulated from "poorly" implemented plugins
2. Understood. As long as you don't want to log at Verbose level.

Happy for this one to be closed unless you want to keep the V2 feature request.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. The problem with 1) is that in order to prevent a potential perf issue, all calls would incur the cost of some kind of dispatching. I think avoiding poorly-written sinks is the better option here :-)

RE 2), I think it's at the other end things are discontinuous - you can't "turn off" `Fatal`. We've had an eye on this a while but in practice, it doesn't seem to be an issue. Let me know if I've misunderstood what you mean here.

Cheers!

**Comment by natiki** [comment]
Thanks for clarifying.

1) Agreed assuming there was more than 1 sink per logging destination to choose from ;-)
2) Nah all good. Realise what you are getting at. Whether it is done that way (sub loggers) or a single logger the end result is the same. Perf is determined by sinks and changing levels is the  only way to modify a logger(s) once configured.
