### ISSUE TITLE
The type ILogger is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Jak893** [serilog/serilog#717]
I've only seen one other issue similar to this and looking through my project, I think I have everything set up correctly so I'm not sure if this is an issue my side or on the package side, hopefully someone might be able to shed some light on it!

When I try and build my project at the moment, the following error message is preventing the build.
`Severity	Code	Description	Project	File	Line	Suppression State
Error CS0012 The type 'ILogger' is defined in an assembly that is not referenced. You must add a reference to assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.	website.DNX Core 5.0`

My project dependencies look like this (most have been removed for conciseness).

    dependencies": {
        .....
        "Microsoft.Framework.Logging": "1.0.0-beta8",
        "Serilog": "2.0.0-beta-523",
        "Serilog.Framework.Logging": "1.0.0-rc1-final-10083",
        "Serilog.Sinks.RollingFile": "2.0.0-beta-700"
    }

I have also tried adding the references directly to the `dnxcore50` and `dnxcore451` section of the frameworks element but no luck there as well.

The logging itself is being initialized as below with the offending line pointed out.

    public Startup(IHostingEnvironment env) {
        .....
        Log.Logger =
                new LoggerConfiguration().MinimumLevel.Debug()
                        .WriteTo.RollingFile(Path.Combine(logPath, "CPC-Website-{Date}.log"))
                        .CreateLogger(); //Have attempted to comment these two lines and just call .Debug().CreateLogger(); but issue still persists
        .....
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole(Configuration.GetSection("Logging"));
        loggerFactory.AddDebug();
        .....
        loggerFactory.AddSerilog(); // This is the line the exception message is referencing
        .....
    }

I have double checked the references in both the DNX 4.5.1 and DNX CORE 5.0 and can see all the Serilog packages listed in there.

**Comment by Jak893** [comment]
Ok, weirdly I found a reference to `"Serilog.Extensions.Logging": "1.0.0-rc1-final-10092"` which I used to replace `"Serilog.Framework.Logging": "1.0.0-rc1-final-10083"` and it is now building. The `.Framework.` came when I selected to install Serilog from the nuget repository. Project is now building and seems to be logging fine.

**Comment by nblumhardt** [comment]
I think this is also likely to be trouble:

```
    "Microsoft.Framework.Logging": "1.0.0-beta8",
```

Should now be _Microsoft.Extension.Logging_ RC1.

Cheers!
