### ISSUE TITLE
Pull requests for other serilog projects

### ISSUE THREAD

**Issue by patrick-steele** [serilog/serilog#720]
I hate to put this here, but I'm not sure where else to put it.  Two weeks ago, I put in a [pull request](https://github.com/serilog/serilog-sinks-azuredocumentdb/pull/2) for the serilog-sinks-azuredocumentdb project.  About a week after that, I [opened an issue](https://github.com/serilog/serilog-sinks-azuredocumentdb/issues/3) to get feedback on the pull request.

Is there someone who reviews pull requests on a per-sink basis?  Or does that all bubble up to [Nicholas](https://github.com/nblumhardt)?

**Comment by nblumhardt** [comment]
Hey Patrick - sorry about the delay on those! @robdmoore often reviews the Azure DocumentDB PRs, or I help out where possible, but in the case of this repo I wasn't _Watching_ and I assume Rob has his plate full. I'll pop over there now and check it out.

There's a fairly complete listing of the who's-who for each project here: https://github.com/orgs/serilog/teams

Cheers!

**Comment by patrick-steele** [comment]
No need to apologize!  Thanks for handling the pull request.

Also, your [Teams link](https://github.com/orgs/serilog/teams) just redirects me back to the main serilog github project with a message at the top saying "You’re not a member of any teams in this organization."  Is that the correct link?

Thanks!

**Comment by nblumhardt** [comment]
Hmmm, thanks for the heads-up; I didn't realise the teams page is completely private - we'll have to think harder about where to surface that info....

**Comment by robdmoore** [comment]
Sorry guys - did see these, but been a little busy :p

**Comment by nblumhardt** [comment]
@robdmoore know the feeling :-)

(Tangential question... are you using DocumentDB for much? I haven't spotted it out there in the wild, but guessing it's been gaining some adoption... Just curious :-))

**Comment by robdmoore** [comment]
@nblumhardt I haven't used it to be honest. I've seen a couple of clients use it. I don't think many people know how to use it effectively - it certainly has some powerful scenarios it enables, but for most scenarios sql or table storage do the job well and are less expensive / easier to develop against locally.

**Comment by nblumhardt** [comment]
Thanks @robdmoore

**Comment by patrick-steele** [comment]
Hmmm...  I looked at Table Storage, but it seemed like the indexing capability of DocumentDB would make digging through log entries easier (and faster).  Maybe I'll look at Table storage a little more.

**Comment by nblumhardt** [comment]
@patrick-steele not tempted to use a purpose-built log server? Definitely nicer to work with than a raw data store. Interested to hear your thoughts! :-)

**Comment by patrick-steele** [comment]
Very tempted. :)

We're a startup so money is tight, but I am running Seq locally (and love it!).  Should probably get off my butt and send an email to check into your BizSpark discounts (we're a BizSpark subscriber).
