### ISSUE TITLE
A view of open new issues across the Serilog repositories.

### ISSUE THREAD

**Issue by merbla** [serilog/serilog#721]
As v2.0 breaks apart all the sinks, it would be great to see a view where issues (count) are at a glance across a number of sinks in the Serilog owned repos.

I am sure there is something like this on the internets.

**Comment by merbla** [comment]
ping @serilog/reviewers-core

**Comment by nblumhardt** [comment]
Yeah something along these lines would be great :+1:

**Comment by sheastrickland** [comment]
Only a month or so in, but this has been good to us (pronounced Overview)
https://overv.io

**Comment by merbla** [comment]
Moving this over to #590
