### ISSUE TITLE
Debugging....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#722]
Hi,

I have read the info on https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics, however as symbolsource.org has a runtime error, I am not using a console app (cannot do so easily) and am creating my own ILogger I was hoping you could provide me with an option to get hold of the debug messages that Serilog could be sending my way.

The code below is running as part of an NUnit test being kicked off by R#.... I create my configuration, hook up the UDP and Email sinks and eventually write to the logger:

```c#
    var file = File.CreateText("c:\\rubbish\\dono.log");
    Serilog.Debugging.SelfLog.Out = TextWriter.Synchronized(file);

  LoggerConfiguration loggerConfiguration = new LoggerConfiguration()
                    .Enrich.WithProperty("ApplicationHostName", aParams.ApplicationHostName)
                    .Enrich.WithProperty("ApplicationName", aParams.ApplicationName)
                    .Enrich.WithProperty("ApplicationVersion", aParams.ApplicationVersion)
                    .Enrich.WithProperty("LogVersion", aParams.LogVersion)
                    .MinimumLevel.Verbose();

loggerConfiguration.WriteTo.Email(emailConnectionInfo, MESSAGE_TEMPLATE_UDP, LogEventLevel.Verbose, 1);

loggerConfiguration.WriteTo.Udp(IPAddress.Loopback, 11000, 0, LogEventLevel.Verbose, MESSAGE_TEMPLATE_UDP);

 //Finally we can build the logger
result.Logger = loggerConfiguration.CreateLogger();
```

I see my UDP output but not the email. The C:\rubbish\dono.log is empty.

So my questions are:

1. Is it still "correct" to use Serilog singleton to get logging info
2. How else can I go about debugging why I am not getting the email
3. Can I dial up the "internal debug logging" so that I can an indication of the email sink is being called?

**Comment by nblumhardt** [comment]
Hi Donovan,

Is the issue primarily in a unit test, or have you built the test to figure out what's going on in the production version of the code?

I think everything looks fine in your configuration; the one thing I'd look into is whether the test is being torn down before the asynchronous email delivery has completed.

To test this theory, dispose the logger after writing your message: `((IDisposable)logger).Dispose()` (v2 has a better API for this...).

Let me know if that shows anything up!

Cheers,
Nick

**Comment by natiki** [comment]
Hi Nick,

Legend!!! I will ensure the logger is disposed of and that will sort things out.
