### ISSUE TITLE
Incompatibility between Serilog and .NET Core event level

### ISSUE THREAD

**Issue by williamthiago** [serilog/serilog#726]
Serilog LogEventLevel is Verbose < Debug < Information ...
Microsoft.Extensions.Logging (Abstractions) LogEvent is Debug < Verbose < Information ...

This cause some weird side effects, when I use both, switching Debug for Verbose:

``` csharp
Log.Logger = new LoggerConfiguration()
                .WriteTo.ColoredConsole()
                .MinimumLevel.Verbose()   // set to minimal in serilog
                .CreateLogger();

loggerFactory.MinimumLevel = LogLevel.Debug;  // set to minimal in microsoft framework
loggerFactory.AddSerilog(Log.Logger);

var logger = loggerFactory.CreateLogger<Class>();
logger.LogDebug("Debug");
logger.LogVerbose("Verbose");
logger.LogInformation("Information");
logger.LogWarning("Warning");
logger.LogCritical("Critical");
```

The output is:
```
2016-04-28 00:27:13 [Verbose] Debug
2016-04-28 00:27:13 [Debug] Verbose
2016-04-28 00:27:13 [Warning] Warning
2016-04-28 00:27:13 [Information] Information
2016-04-28 00:27:13 [Fatal] Critical
```

**Comment by williamthiago** [comment]
Found the possible problem, in serilog-extensions-logging:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L126-L129

**Comment by williamthiago** [comment]
NVM! This will be changed in RC2 https://github.com/aspnet/Announcements/issues/124

So, lets wait.

**Comment by merbla** [comment]
Thanks @williamthiago, quite right! RC2 will hopefully iron out these types of issues 👍
