### ISSUE TITLE
Provide API for transformations to match beyond exact type

### ISSUE THREAD

**Issue by adamchester** [serilog/serilog#730]
This issue is intended to allow discussing what API that could be provided for easier destructuring / transformations (`IDestructuringPolicy`).

The first suggestion arises from discussion in #723 and #728.

 * allow `Destructure.ByTransforming` to match derived types. This would be extremely useful for transforming reflection types (#728) because at runtime we receive internal framework implementations of `System.Type` (I.e RuntimeType) which cannot be matched on exact type and therefore can't easily be transformed in the current API.

**Comment by nblumhardt** [comment]
Closed in #782.
