### ISSUE TITLE
Making debugging even easier....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#731]
Hi,

SelfLog is a great tool when trying to see when things go wrong. However if you are deploying to a web  environment you more often than not do not have access to the console or a the physical file system to look at a text log file.

It would be great if there was an option to send this information out by UDP. Ultimately this means zero physical configuration on the destination host aside from say a firewall rule change (a firewall rule change is easier to effect in these scenarios then say getting write permission to a folder within a web root for instance). The UDP listener can be placed anywhere were the packets would reach it.

Configuration for SeriLog UDP Debug would be as follows:

1. Broadcast Port
2. Broadcast to local LAN segment OR Send to specific IP address (Naturally this has to be on the same LAN segment as UDP cannot traverse firewalls by itself)

PS. I could use this functionality right now, because things all work on my local dev environment, but not on the remote web host and you guessed it I cannot get to the console, file system etc. :-)

**Comment by adamchester** [comment]
👍 it would be nice if there was some good implementations of a `SelfLog` sink that could send operational warnings of malformed templates, configuration errors, sink failures, etc.

I notice some other logging libraries have a concept of an *internal target* which is a special kind of *sink* for these kinds of issues.

**Comment by nblumhardt** [comment]
I know it is a bit hacky, but what about if we implemented a `TextWriter` (as supplied to `SelfLog.Out`) on top of `ILogger`?

```csharp
var internal = new LoggerConfiguration().WriteTo.Whatever().CreateLogger();
SelfLog.Out = new LogWriter(internal);
```

This could be cleaned up and encapsulated with:

```csharp
var internal = new LoggerConfiguration().WriteTo.Whatever().CreateLogger();
SelfLog.Logger = internal; // Sets SelfLog.Out
```

Has the nice effect of emulating `Log.Logger`.

But, **serious** footgun territory if any part of the internal logger itself writes to `SelfLog` (this was the impetus for separating them and using a `TextWriter` originally). May be some tricky way to avoid this, but not an obvious/clean one I can see.....

**Comment by adamchester** [comment]
I hope I don't confuse this issue by thinking out aloud, but here goes: Is `System.IO.TextWriter` the best abstraction to use for `SelfLog` ? What if Serilog `SelfLog` was something like this:
```csharp
public static class SelfLog {
    public static ILogEventSink Sink { get; set; }

    public static void Write(LogEvent logEvent) {
        var selfLogSink = Sink;
        if (selfLogSink == null) return;
        try {
            selfLogSink.Emit(logEvent);
        }
        catch (Exception yoDawgIHeardYouLikeExceptions) {
            // now what?!
        }
    }

    public static void WriteLine(string format, object arg0 = null, object arg1 = null, object arg2 = null)
    { // this could be re-implemented to avoid breaking things ?
    }
}
```

**Comment by natiki** [comment]
@all I still want a UDP implementation as a ZERO local configuration please ;-) For all those times when the local machine is pretty much inaccessible.

**Comment by nblumhardt** [comment]
@adamchester it's nice, but most sinks aren't publicly exposed (`FileSink` and the rolling file are, but most others are hidden behind their configuration methods). Functionally I think it'd still suffer the same self-log-inception issue, since the sinks can write to `SelfLog` even in non-exceptional circumstances.

Using `TextWriter` also gets around the complexity of binding message templates, destructuring with _its_ various failure modes, etc. etc. etc. :-)

@natiki I fear there's not much chance we can get it "in the box". You can plug a `TextWriter` into `SelfLog` today that writes its text payloads to UDP, which might be an interesting option to explore. Serilog broadcasting stuff out on UDP by default would be havoc though :-)

**Comment by natiki** [comment]
@nblumhardt Any chance of some sample code showing a TextWriter doing UDP without touching the local disk? I don't want it to broadcast everything just what is on SelfLog (and assuming I have turned on the UDP destination for that)

**Comment by merbla** [comment]
@natiki bit of a naive example that ony pushes a char at a time, however is this the concept you are looking for?

```
   class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.ColoredConsole()
                .CreateLogger();

            Serilog.Debugging.SelfLog.Out = new UDPEndpoint();

            var items =  Enumerable.Range(1, 100);

            foreach (var item in items)
            {
                Log.Information("Hello :{item}", item);
                Log.Information("A malformed message :{item},{PIasdf}", item);
                Thread.Sleep(1000);
            }
        }
    }

    internal class UDPEndpoint : TextWriter
    {
        public UdpWriter()
        {
            Encoding = Encoding.Default;
        }

        public override Encoding Encoding { get; }

        public override void Write(char value)
        {
            base.Write(value);

            using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp))
            {
                var broadcast = IPAddress.Parse("127.0.0.1");
                var sendbuf = Encoding.GetBytes(new[] { value });
                var endPoint = new IPEndPoint(broadcast, 11000);
                socket.SendTo(sendbuf, endPoint);

                Console.WriteLine("Self Log message sent to UDP");
            }
        }
    }
```

**Comment by adamchester** [comment]
Maybe instead of `TextWriter` it could be `ISelfLogSink` And implementations must guarantee not to cause self-log-inception issues. The problem with `TextWriter` is that it has way too many overloads and other use cases, making it harder to implement correctly. It's also fundamentally for writing characters rather than a single log message at a time.

**Comment by adamchester** [comment]
Having said that, I can see some advantages of leaving it the way it is and not causing breakages.

**Comment by nblumhardt** [comment]
Hmm yes, it's a tough one. `Action<string>` would probably also do at a pinch - making it easy to wire up to whatever output is desired (be it a `TextWriter` or another `ILogger`, if you like to live on the wild side..).

```csharp
public Action<string> OnMessage { get; set; }

public TextWriter Out
{
    set { OnMessage = value.Write; }
}
```

^ Breakage probably not an issue if tackled this way.

**Comment by nblumhardt** [comment]
Thoughts on https://github.com/serilog/serilog/pull/758 ?

**Comment by srogovtsev** [comment]
...and maybe ability to set SelfLog from appSettings as well? It's kinda messy having to write one's own configuration key only for that purpose, and it also spoils the beauty of `name="serilog:` column.
