### ISSUE TITLE
Attributes to exclude properties from logging

### ISSUE THREAD

**Issue by arteny** [serilog/serilog#732]
Is there a way to exclude property with annotation from logging when logging object with {@Object} like 		[JsonIgnore] for Newtonsoft.Json?

**Comment by nblumhardt** [comment]
Hi! Yes, this is `[NotLogged]` from https://github.com/destructurama/attributed

If you see any opportunities to improve it, feel free to raise suggestions over there :+1: - thanks!

**Comment by adrianiftode** [comment]
Do you know about a fluent way style of doing it? Something like AutoMapper, FluentValidation?

**Comment by Vazovsk1y** [comment]
> Do you know about a fluent way style of doing it? Something like AutoMapper, FluentValidation?

I tried to implement something similar, if you have time and desire you can leave feedback.
https://github.com/Vazovsk1y/Serilog.FluentDestructuring
