### ISSUE TITLE
Configuration of DateTimeOffset.Now vs DateTimeOffset.UtcNow as log timestamp

### ISSUE THREAD

**Issue by likemike91** [serilog/serilog#735]
I have the requirement to log all events with DateTimeOffset.UtcNow as timestamp.

Please enable the configuration of whether to use Now or UtcNow as the timestampe of the LogEvent instance.

Using the plain `ILogger.Write(LogEvent event)` isn't possible because I'm not able to create an instance of the `MessageTemplateProcessor` to parse the `string messageTemplate` parameter and to process the `params object[] propertyValues` parameter.

Is there any possibility to configure this behavior?

**Comment by nblumhardt** [comment]
Hi Mike - which sink are you using? If it's a text-based sink, enriching events with a `UtcTimestamp` property and using this in the sink's `outputTemplate` is the way to go:

```csharp
class UtcTimestampEnricher : ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        logEvent.AddPropertyIfAbsent(
            propertyFactory.CreateProperty(
                "UtcTimestamp",
                logEvent.Timestamp.UtcDateTime));
    }
}
````

Then:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console(outputTemplate: "{UtcTimestamp} ...")
    .CreateLogger();
```

HTH!

**Comment by likemike91** [comment]
Hi!

I'm using the Elasticsearch Sink and therefore it's necessary to provide the Timestamp in UTC because Elasticsearch uses it internally as a special field for determining the name of the Index where the data is stored.

I could think of adding something like:

```csharp
new LoggerConfiguration()
    .Configuration.UniversalTimeLogTimestamp();
```

Maybe there are better options but this is the first thing which comes into my mind.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Time formats are a sink-specific concern (many different sinks can share the same logging pipeline). I'm pretty sure the ES sink has a facility to handle this already. @mivano any pointers? Cheers!

**Comment by mivano** [comment]
The index name in Elasticsearch is based on the UTC time. We use the below

```csharp
var indexName = _state.GetIndexForEvent(e, e.Timestamp.ToUniversalTime());
```

So if you store a UTC time in your timestamp, it will be okay already. The timestamp itself is written like this

```csharp
protected override void WriteTimestamp(DateTimeOffset timestamp, ref string delim, TextWriter output)
        {
            WriteJsonProperty("@timestamp", timestamp, ref delim, output);
        }
```
So it will contain the timezone details.

**Comment by likemike91** [comment]
Thank you for your answer concerning the Timestamp for the Index.
But what can I do if I have the requirement to also store the Timestamp in UTC?

Is there a configuration option anywhere in any of the sinks?

Thanks so far!

**Comment by mivano** [comment]
Pass in your own custom formatter and you are free to format any of the
fields to your liking. Use the default one as an example.
Op di 10 mei 2016 om 21:42 schreef Michael Hahn <notifications@github.com>

**Comment by likemike91** [comment]
Okay thank you!
I think I've now found a working solution for that problem.
