### ISSUE TITLE
Improve the way malformed templates/arguments are handled

### ISSUE THREAD

**Issue by adamchester** [serilog/serilog#737]
Consider the following scenario:

```csharp
log.Information("Hello, {name}, you have outcome}", "Adam", "Failed");
```
The message template above was accidentally malformed, missing the opening brace before `outcome}`. 
Serilog currently would recognise and match the `{name}` field, but would totally ignore the `{outcome}` field because it doesn't have a corresponding/matching valid placeholder field in the message template. Because we provided the 2nd argument value `Failed`, Serilog would write a warning to `SelfLog` as follows:
> 2016-05-11T09:32:39 Named property count does not match parameter count: Hello, {name}, you have outcome}

I believe Serilog should *include* the `Failed` value with some default/obvious name instead of dropping / ignoring the value.

Related:
logary/logary#119 and [MessageTemplates](https://github.com/adamchester/MessageTemplates)

**Comment by adamchester** [comment]
:tada:

**Comment by adamchester** [comment]
Wait, still going attempt something with positionals

**Comment by nblumhardt** [comment]
Time to close this one? Cheers!
