### ISSUE TITLE
Making debugging even easier.... Using GitLink?

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#738]
Hi,

Any chance of perhaps integrating the following to improve the debugging experience?

https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/
https://github.com/GitTools/GitLink

**Comment by merbla** [comment]
Hi @natiki,
We do have [http://symbolsource.org/](http://symbolsource.org/) however that looks like it is down :(

I have not used GitLink before, I can't see how it hooks into the DNX build pipeline.

**Comment by nblumhardt** [comment]
I hadn't seen GitLink, it looks _awesome_.

If it's possible to hook up with `dotnet build` and friends, a PR integrating it would be a nice alternative to SymbolSource, which has been a bit flaky for us.

If it's not possible, I think we'd keep it in mind but we're unlikely to attempt it in the near term.

**Comment by nblumhardt** [comment]
Closing as it doesn't look like we'll move on this right now, but thanks for the suggestion @natiki! Hopefully the DNX/MSBuild project system merge will make this possible down the road.
