### ISSUE TITLE
Best Performance Practices for enriching messages with properties

### ISSUE THREAD

**Issue by corneliutusnea** [serilog/serilog#739]
Hi guys,

What are the recommended practices for enriching messages with properties from a performance perspective? As far as I could find there are several ways of enriching message:

1: Using the local context
```
var disposable = new DisposableCollection();
disposable.Add(LogContext.PushProperty("property1", "value1"));
disposable.Add(LogContext.PushProperty("property2", "value2"));
using(disposable){
   _logger.Info("template {value}", someValue);
}
```
2: Using ForContext
```
_logger.ForContext("property1", "value1")
   .ForContext("property2","value2")
   .Info("template {value}", someValue);
```
3: Using PropertyEnrichers
```
_logger.ForContext(new PropertyEnricher[] {
   new PropertyEnricher("property1", "value1", true)
   , new PropertyEnricher("property2", "value2", true)
}).Info("template {value}", someValue);
```

Is there a recommended way in order to achieve maximum performance?
No 1 to me feels like the least performance because you have to hit the ThreadLocalStorage both writing those values in the context and reading them.

No 2 seems to be creating a new `Logger` internally for each call into the `.ForContext`. If I have 6-10 such properties instead of 2 that feels like a serious performance hit on the GC to create so many extra objects just to log a string.

No 3 seems to be the best as I could pre-create those `PropertyEnricher`s and keep them on my context higher up the stack and re-feed them to all the logging I have to do inside a context.
However No 3 in the implementation seems to be parsing/deconstructing the value every time it has to enrich a message so reusing it feels like it would not achieve anything really.
Maybe a combination of the `PropertyEnricher` and the `FixedPropertyEnricher` that seems to e caching the `LogEventProperty` so I can truly reuse that parsed/deconstructed property.

Thoughts?

**Comment by nblumhardt** [comment]
Hey Corneliu!

API number three is the one to use; just create your own enricher optimised for your scenario:

```csharp
class RocketParametersEnricher : ILogEventEnricher
{
    readonly LogEventProperty _designation, _capacity;

    public RocketParametersEnricher(string designation, int capacity)
    {
        _designation = new LogEventProperty("Designation", new ScalarValue(designation));
        _capacity = new LogEventProperty("Capacity", new ScalarValue(capacity));
    }

    public void Enrich(LogEvent logEvent, ILogEventPropertyValueFactory unused)
    {
        logEvent.AddPropertyIfAbsent(_designation);
        logEvent.AddPropertyIfAbsent(_capacity);
    }
}
```

Still an array allocation, and the underlying (but very cheap) `Logger`, but skips any binding logic around the values.

```csharp
_logger.ForContext(new[] { new RocketParametersEnricher("A", 123) })
    .Information("Here!");
```

A truly optimal implementation could knock more allocations out and squeeze some more performance from it, but I doubt the above will show up except on very specific microbenchmarks. Any numbers on the scenario you're exploring?

Cheers!

Nick

**Comment by vanni-giachin** [comment]
@nblumhardt would it be possible to turn to public `AddPropertyIfAbsent(ILogEventPropertyFactory factory, string name, object? value, bool destructureObjects = false)` to take advantage of the `ILogEventPropertyValueFactory` available on enrichers and also avoid multiple property initializations? Thank you!
