### ISSUE TITLE
Configure Serilog Sinks and Minimum Logleven without recompile

### ISSUE THREAD

**Issue by escamoteur** [serilog/serilog#740]
Hi,

maybe I missed it in the docs, but is it possible to config used sinks and minimum log leven from an external config file, so that I just had to restart the app to apply config changes?

Thanks
Thomas

**Comment by merbla** [comment]
Hi @escamoteur,

Do you mean something like the [appsettings](https://github.com/serilog/serilog/wiki/AppSettings)?

Cheers

**Comment by escamoteur** [comment]
Yes, that's what I needed, somehow it didn't work when I first tried it.
