### ISSUE TITLE
Archive logs when maximum file size reached/

### ISSUE THREAD

**Issue by Stavrakakis** [serilog/serilog#743]
Hello,

Is it possible to use the FileSink with a maximum file size limit so that it rolls over when it reaches that limit? The behavior I'm seeing at the moment is that it simply stops logging.

Can it just increment the version or create a new file, archiving the old one?

One of my colleagues has asked if this is possible without having to use the RollingFileAppender as he would prefer to not have the date in the file name.

Thanks

**Comment by nblumhardt** [comment]
Hi @Stavrakakis - no, it's not available with this sink. https://github.com/BedeGaming/sinks-rollingfile may be an option, though I think it still rolls the filenames.

Forking one of either the File, RollingFile or Alternate RollingFile repositories and modifying to your requirements is probably the best option if you need this.

HTH!
