### ISSUE TITLE
Update Serilog.Sinks.Raygun with unsigned Raygun assembly

### ISSUE THREAD

**Issue by wwwlicious** [serilog/serilog#744]
The `Serilog.Sinks.Raygun` package is currently using the sn raygun assembly which is causing two packages I have in a project that depend on Raygun to have a contest to see who can cause the most conflicts.

Propose this is either updated to use the non-strong named assembly or a new package is created that doesn't use strong named dependencies so that it can 'play well with others' :)

**Comment by nblumhardt** [comment]
Just realized the tracker was still turned off in the Raygun sink project; turned on now! Moved to https://github.com/serilog/serilog-sinks-raygun/issues/3. Thanks!
