### ISSUE TITLE
Upgrading Third Party Serilog Libraries to 2.0-rc

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog#745]
I am the author of [Serilog.Exceptions](https://github.com/RehanSaeed/Serilog.Exceptions) and want to upgrade to the 2.0-rc release. I'm curious as to why the project.json file targets three frameworks:

- net4.5
- netstandard1.0
- netstandard1.3

Surely, if you target netstandard1.0 it should cover the other two. Probably netstandard1.3 is also being targeted to add extra functionality but I'm not sure why net4.5 is there.

My library works with netstandard1.0. Am I ok to target this framework and not the other two?

**Comment by nblumhardt** [comment]
HI! Yes, just targeting the broadest platform you can is the way to go, and everything should "just work" :+1:

The Serilog code uses different internal implementations on each of these three targets, but the public interface is the same.

**Comment by merbla** [comment]
@RehanSaeed I always end up referring to this... 

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

**Comment by RehanSaeed** [comment]
Thanks, I thought as much.
