### ISSUE TITLE
Efficient creation of `LogEvent` with destructured properties

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#746]
A longtime API rough spot: it's non-trivial to construct a `LogEvent` from its constituent parts except by calling a method on an `ILogger`.

It's not _impossible_, but there are two complications:

 - Parsing and binding parameters to a `MessageTemplate` isn't straightforward
 - Properties not in the template can only be added through `ForContext()`, which is indirect and not super-efficient

The current state of things is summed up pretty well by this method from _Serilog.Extensions.Logging_, which takes a payload from a _Microsoft.Extensions.Logging_ call and passes it through to the Serilog pipeline:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L51

In there you'll observe a lot of.

```csharp
logger = logger.ForContext(property.Key, property.Value);
```

This pattern takes a name/value pair and attaches them as a property by way of enrichment. It's not correct to just call `new LogEventProperty(name, new ScalarValue(value))`, since policies may be in effect for which types are captured as scalar values. (When destructuring is required this is especially true.)

The issue of binding a `MessageTemplate` is side-stepped because the positional mapping is already done by the external logging API, but it's still unfortunate that template parsing in this class can't make use of the internal cache shared by Serilog loggers.

I have one proposal to offer but there are several ways to approach it so this thread is open for ideas :-)

**Comment by nblumhardt** [comment]
### Proposal 1

```csharp
var evt = logger.CreateEvent(
    DateTimeOffset.Now, level, exception, "Some {Number}", 42);

evt.AddOrUpdateProperty(
    logger.CreateProperty("Ticks", 123));

evt.AddOrUpdateProperty(
    logger.CreateProperty("User", user, destructureObjects: true));

logger.Write(evt);
```

 - `CreateEvent()` parses the message template and binds parameters (invoking destructuring policies etc. as needed)
 - `CreateProperty()` just handles the scalar conversion/destructuring duties.

It's not an incredibly elegant interface, lots of long method names - but this kind of thing is only used in glue code, not typical application code.

#### Issues/questions

First, it's a breaking change for the `ILogger` interface. At this point very few 2.0-compatible packages will _implement_ `ILogger`, so it's the last opportunity to get this change in, I think. If we make this change we should also do #585.

The _Serilog.Extensions.Logging_ code above could not use `CreateEvent()` as proposed, since the binding logic generates warnings when template "holes" don't have corresponding values. Because of this, the standalone `MessageTemplateParser` would still be needed. A workaround to benefit from caching might just be to grab a copy of the one from the Serilog source, so maybe a non-issue.

Finally, it's worth noting that the names don't conflict on first character with anything in `ILogger`, but if we decided to add symmetric versions to `Log` then `Create***()` will have a first-char collision with `CloseAndFlush()`. This could be avoided by simply requiring callers to use `Log.Logger.Create***()`, we might come up with an alternative name, or given the infrequent use of both the factory methods and `CloseAndFlush()`, we might not care.

**Comment by adamchester** [comment]
Subscribed

**Comment by nblumhardt** [comment]
Opened https://github.com/serilog/serilog/pull/751
