### ISSUE TITLE
error with named connections SQL Express

### ISSUE THREAD

**Issue by GusBeare** [serilog/serilog#748]
I am using SImple.Data locally and have this code:

 var db = Database.OpenNamedConnection("q2_admin");
 //var db = Database.Open();

It works fine in my dev environment where I am using a developer version of SQL server 2012.

However when my colleague runs the code on his box with SQL Express 2012 he gets this error:

 [Error] Specified argument was out of the range of valid values.
Parameter name: connectionName

If I switch to using the default connection it works fine.

Is SQL Express supported? Or is this a bug?

**Comment by nblumhardt** [comment]
Hi Gus,

SQL Express should work fine; I've moved this issue to the tracker on the corresponding sink repo to dig in further: https://github.com/serilog/serilog-sinks-mssqlserver/issues/25

Cheers!

**Comment by GusBeare** [comment]
arrghh.. sorry. That was meant for Simple.Data.
I posted on the wrong repo issues. Sorry. Please don't waste time on this.
