### ISSUE TITLE
Add a prefix to exclude properties from positional matching

### ISSUE THREAD

**Issue by Suchiman** [serilog/serilog#753]
Support a message template prefix to exclude properties from positional matching, so you can pull in ambient properties into the rendered message.
For example (using `%` here but could be anything, idea taken from `@` destructuring prefix) and the UserName enricher:
`Log.Information("{%UserName} failed to send message to {Receiver}", receiver);`
Currently this only works if `{UserName}` would come last.

**Comment by nblumhardt** [comment]
Hey, thanks for posting this! I think it's an interesting/clever extension to the format.

The bar for adding anything to the message template format is pretty high - it's gaining some wider adoption outside Serilog, and changes/additions will make it harder to achieve some level of consistency/portability (definitely an end-goal).

In this case it's an edge-case scenario with an easy workaround (just re-specify the username, positionally), so may not be compelling enough to add now, even though it may make sense if we were starting from a clean slate.

The event in this example also depends on some global knowledge (about enrichment) that's external to the code doing the logging. Without a `UserName` enricher active, the event is no longer able to be reasonably rendered, which suggests it could be a bit fragile to use this in larger apps that change over time.

My $0.02, interested to hear if this is a bigger issue than I'm aware of though! Thanks again!

**Comment by IanYates** [comment]
What if, instead of changing the message template, you could do something like
```
Log.Information("{UserName} failed to send message to {Receiver}", LogContext.Get("RequestUserName"), receiver)
```
(because you want the message template to treat it as `UserName` but it's in the LogContext as `RequestUserName`)
or even just
```
Log.Information("{UserName} failed to send message to {Receiver}", LogContext, receiver)
```
and a smart destructurer could check the ambient `LogContext` for a UserName and put it into the message.

You could have some special marker object instead of using `LogContext` of course.

**Comment by nblumhardt** [comment]
@IanYates nice idea; the property may not always come from `LogContext` though.

I think we should close this one; the template and its args need to make sense at the callsite, not rely on global logger state to work properly.

If the log message is written in a library, and then later on that library gets reused in another app with different config, it'd be strange to have to go and change it just to get the same basic log output...

**Comment by IanYates** [comment]
No complaints from me.  The idea has some merit but it would be tricky / confusing if you're not using Serilog directly.

Where else, apart from LogContext, would you get `ambient properties`?  I suppose logger.ForContext()?  Anything else I'm missing?  I guess some interceptor could say "hey I know {username} - let me access this HttpContext thingy and make it so".

**Comment by nblumhardt** [comment]
:+1: `.ForContext()` is the one I was thinking of.
