### ISSUE TITLE
RFC: MinimumLevel.Override(context, level)

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#754]
```csharp
Log.Logger = new LoggerConfiguration()
  .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
  .MinimumLevel.Override("MyApp.Something.Tricky", LogEventLevel.Verbose)
  .WriteTo.LiterateConsole()
  .CreateLogger();
```

ASP.NET Core has some useful logging pipeline features, e.g. `RequestId` correlation, top-level error handing, etc., that make it compelling to plug Serilog in even when using Serilog's API directly (i.e. not just _Microsoft.Extensions.Logging_).

However, the framework can create a lot of log noise; Microsoft's own providers (e.g. its Console one), and soon perhaps _m.e.Logging_ itself, offer per-source level mappings to alleviate this. See, for example: https://github.com/aspnet/Logging/issues/437

The `MinimumLevel.Override()` method will allow useful information to be pulled from the framework, without a deluge of events related to ASP.NET plumbing.

### Alternatives

The current `.Filter.By...` API covers the same scenario, but it implements dynamic filtering that's geared towards filtering individual events. Since it relies on the events being created in the first place, it's not as efficient as a per-logger level setting could be. (It's also in need of a refresh, being a bit too flexible for pleasant ergonomics...)

### Details

 * Would we also provide an `Override()` method accepting a dictionary from string to level?
 * Will loggers only respect this when `ForContext()` is called with a type or string, or will we check the property name against `"SourceContext"` even when the name/value overload of `ForContext()` is called? (My preference is for the more limited version, since it'll incur less of a performance impact)
 * Can the second argument (the level) alternatively be a `LoggingLevelSwitch`? (Probably better to build the internals around LLS, since it'll eventually be desirable..)
 * Is it obvious enough in the example above that the pipeline's default level remains at `Information`?
 * Should we go further than the context name/namespace matching logic that we currently maintain for filtering, e.g. to support `"MyApp.*.Something"` as a context name?
 * `<appSettings>` syntax? `Config.json` syntax?

**Comment by RehanSaeed** [comment]
Cool feature. It would be great if Serilog also provided a way to configure it in appSettings.json the same as the other log providers as in my issue https://github.com/aspnet/Logging/issues/437

**Comment by nblumhardt** [comment]
@RehanSaeed it's your issue linked in the original description of this above :-)

We won't support the same config element (`Logging`) as in the example - there are very few other sections that would overlap with the Microsoft one - but the same style would be a winner under `Serilog`.

We have some basic JSON config support for RC1 here, currently being updated to RC2: https://github.com/serilog/serilog-settings-configuration

**Comment by nblumhardt** [comment]
@RehanSaeed raised https://github.com/serilog/serilog-settings-configuration/issues/10 - cheers!
