### ISSUE TITLE
Protecting Sensitive Information

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog#755]
I am evaluating integrating serilog into our ServiceStack architecture for structured logging.
Looks like a great candidate. Only one question in terms of capability.

Other than using declarative attributes (such as `[NotLogged]`) on objects that are destructured (described here: http://nblumhardt.com/2014/07/using-attributes-to-control-destructuring-in-serilog/) , is it possible to achieve the same result in other ways?

Some of the objects we want to log have sensitive customer information that cannot be logged, but we also need to keep these (DTO) objects dependency-free from serilog, as theyare included in shared customer libraries.

**Comment by merbla** [comment]
@jezzsantos you could always destructure using a context.

There are some helpful add ons over at https://github.com/destructurama

e.g.

```
Log.Logger = new LoggerConfiguration()
    .Destructure.ByIgnoringProperties<User>(u => u.Password)
    // Other logger configurationg
    .CreateLogger()
```

**Comment by jezzsantos** [comment]
Great stuff thank you, that will absolutely do it. choice!
