### ISSUE TITLE
Filter.ByExcluding is not working as expected

### ISSUE THREAD

**Issue by riyasat** [serilog/serilog#759]
I have following configuration:
-----------------------------
 Log.Logger = new LoggerConfiguration()
                           .WriteTo.RollingFile(
                               Path.Combine(env.ContentRootPath + "\\Logs", "log-{Date}.txt"),
                           LogEventLevel.Debug,
                           fileSizeLimitBytes: 10485760
                           ).Filter.ByExcluding(x=>x.MessageTemplate.Text.Contains("starting") || x.MessageTemplate.Text.Contains("finished"))
                           .WriteTo.LiterateConsole(LogEventLevel.Error)
                           .CreateLogger();
-----------------------------

It works perfectly fine except its not filtering the message based on the lambda expression. It only exclude the file word, it doesn't matter what ever you put in.

**Comment by nblumhardt** [comment]
Hi @riyasat - what does the event look like that you're expecting to exclude? Is `"starting"` in the _message_, or the _template_? If it's in the message and not the literal template, you'll need to `Render()` the event or search specific properties for the text.

**Comment by riyasat** [comment]
Hi @nblumhardt - Right now serilog logging all events e.g starting GET request, finished request, getting static file etc that's whyI want to filter out the text messages stored in the log file based on strings within message. I am testing this in .NET Core 1.0 (dotnet) and I tested with RC1 and it worked perfectly as expected but not after getting update of serilog extension.

What I want is to log only activities where I specifically use serilog to log. Now log file size is getting increased because of unnecessary log entries as mentioned above. There might be some other way to do that which I certainly do not know as I am new to serilog. 

Do you know how can I achieve that ?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. #754 will allow you to do:

```csharp
    .MinimumLevel.Override("Microsoft", LogEventLevel.Error)
```

exactly for this case.

There's an active pull request pending for it, so it should be in this week.

In the meantime, try using `.ByExcluding(Matching.FromSource("Microsoft"))` - this should have the same effect.

HTH,
Nick

**Comment by riyasat** [comment]
Hi Nick,
Thanks for the quick response.
Yes that Matching.FromSource("Microsoft") actually worked.

**Comment by nblumhardt** [comment]
Great, thanks.

**Comment by nblumhardt** [comment]
#754 merged, build pending.
