### ISSUE TITLE
Level width formatting tweak

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#765]
When @iamkoch and I first set to figuring out fixed-width levels (`INF` and the like) we jumped around a few possible design options but landed on using the format string width specifier syntax (`,n`) like:

```
"{Level,3:u}"
```

This is inconsistent with how width specifiers usually work in format strings; rather than control the width of the value, they merely constrain it once it's already produced from the object being formatted.

Looking back I no longer think this was the right choice; .NET integer types for example use the format specifier to implement this, e.g. `:x8` is an eight-digit hexadecimal. Given the extensive special-casing we had to implement for `Level`, this now looks like the better path to take.

The format above would instead be:

```
"{Level:u3}"
```

(Leaving the width specifier for padding.)

I think this is possibly less code overall, given the `LevelPropertyValue` direction the design eventually took. We should consider switching this before 2.0 is final.

**Comment by iamkoch** [comment]
Would this not contradict the statement in the docs: 

> Property names may be suffixed with an optional format, e.g. :000, to control how the property is rendered; these format strings behave exactly as their counterparts within the `string.Format()` syntax

For example, `string.Format("{0:3}", "Information")` does not return `"Inf"`

The expectation set out with all other string format specifiers would be overridden for the special case of specific strings for level when shortened.

**Comment by nblumhardt** [comment]
This is the case I was thinking of too, when we originally looked at it.

The content after `:` is completely dependent on what type is being formatted, so though `:3` doesn't return a three-digit number when applied to `Int32`, it could if that was the designer's preference over `000`.

For levels, `u3` or `w3` (three uppercase, or three lowercase) is natural when compared against .NET's numeric hexadecimal formats; the only thing missing is a way to specify sentence-cased values, perhaps `s3` or `l3`. It's pretty uncommon to have short values with an inital cap and trailing lowercase, so maybe not something that needs to be accommodated.

**Comment by iamkoch** [comment]
That's true, however the docs would have to change to cover the fact that if you're formatting any string other than level, placing `:3` within the format will behave differently. This means the only place to know how it works is by looking at the docs, which makes me wonder if aligning the new feature with the `string.Format` functionality might add more confusion, given the subtle difference in its behaviour.

**Comment by nblumhardt** [comment]
Agreed, `:3` looks odd. I was thinking we'd only initially support `:u3` and `:w3` for this reason (I can't see mixed-case abbreviated levels being particularly popular).

Figuring out how to format a fixed-width level still requires some documentation/Googling either way, so not sure if it is too much of a caveat. By the same token, formatting any other .NET type (date, numeric etc.) requires specific knowledge of its formatting syntax.

The quirk I think we should try to get away from is that no other .NET type uses the `,n` width specifier to modify the output, only to (potentially) apply whitespace padding. I'd initially thought this was a pretty nifty trick on our part, but in hindsight worry that it's a bit much magic. Though the syntax is clean, the semantics are different enough that knowledge of .NET's formatting conventions isn't enough for someone to discover this functionality directly.

**Comment by nblumhardt** [comment]
PR'd above; to avoid the `:3` oddity, `:t3` will do the `Inf` title-case formatting, in addition to `u3` and `w3` for upper/lowercase.

**Comment by iamkoch** [comment]
Hi Nick

Just looking at the PR and its changes.

I was a bit confused in the instance of logging with {Level:t7}, based on the updated inline data tests:

```c#
[InlineData(LogEventLevel.Warning, 8, " Warning")]
```
became

```c#
[InlineData(LogEventLevel.Warning, 8, "Warning")]
```

Is the expectation of logging at `Debug` level with `{Level:t8}` for the output string to be 8 characters wide, with padding?

**Comment by nblumhardt** [comment]
Hi Anthony,

No, the numeric part of the format is interpreted more like a "trim" than padding. I left the n+1 length tests in there, modified, to make the behavior clear, though the decision to go that way was arbitrary.

To get the padded result, `{Level,8:t7}` would result in `" Warning"` if desired.

It may make more sense to pad, I'm not sure though - the `,n` padding can also provide this so probably not an issue in practice. What do you think?

Cheers,
Nick

**Comment by iamkoch** [comment]
`{Level,8:t7}` seems like a DSL in its own right. I liked the idea that the number told you how wide to expect the output to be, irrespective of its content. There's also the choice to pad right in SeriLog IIRC? How would that be represented, if at all?

**Comment by nblumhardt** [comment]
> {Level,8:t7} seems like a DSL in its own right

Or a _really_ funky emoticon ;)

Yes, it's pretty ugly, though I'd be surprised to spot this one in the wild. I can see this feature used for short level names, but `Information` is already getting pretty wide for use in a text log.

Right padding should be achieved with `,-n` (as in other .NET format strings) but I don't think we've implemented it in Serilog yet.

**Comment by nblumhardt** [comment]
Ah sorry, to properly answer your question. Right pad:

```
"inf   "
```

Would look like:

```
{Level,-6:w3}
```

**Comment by iamkoch** [comment]
`8:t7` does look like some kind of cool monster. I think we're on to something!

I think seeing the examples actually makes it more coherent. We're packing a lot of configuration into a quite restrictive format, so something like `{Level,-6:w3}` is inevitable. This makes me wonder if this is the correct place for it, but aside from configuring it in code there's little else that can be done. I'm sure the community will be the first to complain should they disagree, but I think it's a useful feature and definitely one I'll be using.

**Comment by nblumhardt** [comment]
:+1: thanks again for driving it! It's still pretty much my favourite 2.0 feature :-)
