### ISSUE TITLE
Custom Sink MissingMethodException

### ISSUE THREAD

**Issue by aaronmell** [serilog/serilog#766]
Seeing something strange here, and I can't figure out what I am doing wrong.

This code is in the Emit method of my sink. I'm using the same code present in the log4net sink.

I'm using 1.5.14 and xml configuration.

```
 LogEventPropertyValue type;
                var loggerTypeFullName = GetType().FullName;

                if (logEvent.Properties.TryGetValue("Common.Logging.Type", out type))
                {
                    var sv = type as ScalarValue;
                    if (sv != null && sv.Value is string)
                        loggerTypeFullName = (string)sv.Value;
                }
```

When this code is present the Sink fails with the following error

2016-06-05T13:14:23 Caught exception System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Serilog.Events.LogEventPropertyValue> Serilog.Events.LogEvent.get_Properties()'.
   at Common.Logging.Serilog.CommonLoggingSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent) in C:\projects\serilog\src\Serilog\Core\Sinks\SafeAggregateSink.cs:line 38 while emitting to sink Common.Logging.Serilog.CommonLoggingSink.

If I comment out the code the sink works. When I step through the sink with the code commented out, everything looks fine, and the properties object exists.

Any ideas?

**Comment by aaronmell** [comment]
BTW, this is using 1.5.14

**Comment by nblumhardt** [comment]
Hi @aaronmell - it sounds like you're building your custom sink for .NET 4.0, but then running it in an application that has the .NET 4.5 version of Serilog.dll in there.

Unfortunately when back-porting Serilog to .NET 4, `IReadOnlyDictionary` was not available and so the type of `LogEvent.Properties` had to change to `IDictionary`, creating this binary compatibility issue. We're dropping 4.0 support completely with Serilog 2.0 in the hope of making this situation easier to avoid.

Am I on the mark? Cheers!
Nick

**Comment by aaronmell** [comment]
That was the issue! Thanks
