### ISSUE TITLE
Log on Output window when debugging RC2

### ISSUE THREAD

**Issue by mdmoura** [serilog/serilog#768]
On an ASP.NET Core RC2 project I have the following:

      if (hostingEnvironment.IsDevelopment()) {
        loggerFactory.AddDebug();
        loggerConfiguration
          .WriteTo.Console(LogEventLevel.Verbose);
     }

When I run the application I can see on Output window information such as EF SQL Queries.

If I remove `loggerFactory.AddDebug();` I don't see that information in Output anymore. Shouldn't 

        loggerConfiguration
          .WriteTo.Console(LogEventLevel.Verbose);

do the same as `loggerFactory.AddDebug();`?

Is there a way to also use Serilog to log all information in Output window?

**Comment by nblumhardt** [comment]
Hi,

I think `WriteTo.Trace()` via https://www.nuget.org/packages/serilog.sinks.trace is the way to achieve the same thing with Serilog.

HTH,
Nick

**Comment by nblumhardt** [comment]
Hi Miguel,

2.0.0 of the Trace sink should be hitting NuGet in just a moment: https://www.nuget.org/packages/Serilog.Sinks.Trace/

Let me know if you need any further help.

Regards,
Nick
