### ISSUE TITLE
Include AssemblyInformationalVersion attribute to the  with commit hash

### ISSUE THREAD

**Issue by zihotki** [serilog/serilog#784]
AssemblyInformationalVersion allows to include some additional information like commit hash. This helps to identify the HEAD commit used to build the library. Git tagging is similar to this in some ways but it helps to identify the commit on the git side when the attribute helps to identify directly from library file properties. In some scenarios one way would be easier for someone than another. Generation of the attribute is usually done at the moment when AssemblyVersion is generated during the build. The AssemblyInformationalVersion looks like this in the code:

`[assembly: AssemblyInformationalVersion("1.3.1.74-g23246c2")]`

**Comment by nblumhardt** [comment]
Thank you for the suggestion.

**Comment by saitonakamura** [comment]
@zihotki Do you enrich all the assemblies with this infomation, or just special one?

**Comment by zihotki** [comment]
@saitonakamura My personal opinion is that it's better to let all assemblies to have it, it doesn't add much complexity since usually during a build a common AssemblyInfo is used for all relevant projects.

**Comment by saitonakamura** [comment]
@zihotki at this moment you can enrich you logs like this 
`Enrich.WithProperty("commit hash", GetCommitHashFromAssembly(Assembly.GetExecutingAssembly()))`

P.S. I know that using `typeof(SomeType).Assembly` is recommended over the `Assembly.GetExecutingAssembly()` because of performance issues, but since logger configuration called only once (or several times) I think it's fine

**Comment by zihotki** [comment]
@saitonakamura actually I was not asking how to enrich it, but instead suggested to add the attribute to the assembly during a build of Serilog nuget package. If that information is there then it's easy to do anything, but if not - you have to look on Github.
