### ISSUE TITLE
.Enrich.WithMachineName() - Upgraded from RC1 to RC2

### ISSUE THREAD

**Issue by dazinator** [serilog/serilog#785]
Have upgraded an RC1 project to RC2, here are my serilog dependencies:

```
 "Serilog": "2.0.0-rc-640",
    "Serilog.Sinks.Seq": "2.0.0-rc-57",
    "Serilog.Extensions.Logging": "1.0.0-rc2-10110",
```

I have noticed these extension method can no longer be found:

```
 .Enrich.WithMachineName()
 .Enrich.WithThreadId()
```

Have I done something wrong, is this in progress, or is this removed by design?

Update: Is this replaced with `.Enrich.FromLogContext()`now?

**Comment by adamchester** [comment]
Hi @dazinator, it's been moved into a separate package.

This should help: https://github.com/serilog/serilog/wiki/2.x-Upgrade-Guide#installing-20-enricher-packages

**Comment by nblumhardt** [comment]
:+1: _Serilog.Enrichers.Environment_ is the one.

**Comment by dazinator** [comment]
Cheers ;)
