### ISSUE TITLE
Compact JSON format

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#786]
Hey folks; I've been working on a more efficient JSON representation of Serilog events here: https://github.com/nblumhardt/serilog-formatting-compact

I'm happy to continue this as a pet project but would equally happily move it to the Serilog organisation and continue work there.

I think we need alternatives to the current `JsonFormatter` and it's simple "serialized .NET object" feel; I guess the question posed by this issue is whether we want to do that by backing one or more options here.

**Comment by merbla** [comment]
+1 for moving it under the Serilog banner.  I think it also serves as an education for the options available to extend formatting.

**Comment by nblumhardt** [comment]
Voila, amigos :-p https://github.com/serilog/serilog-formatting-compact
