### ISSUE TITLE
Serilog omitting base class properties on event serialization

### ISSUE THREAD

**Issue by evilpilaf** [serilog/serilog#787]
I am serializing events with Serilog, this events can be sent from a wide arrange of services that extend a base abstract class that contains the essential information for any event, and the child classes add all needed specific event information.

The problem is that in the log only the child class properties are being stored and the parent ones are left out. Is there a way to force serilog to include the base class properties on its serialization?

I tried changing the base class to non-abstract and also setting the Destructor.ToMaximumLength to 10000 but still no luck.

I posted the queston on [StackOverflow](http://stackoverflow.com/questions/37978919/serilog-omitting-base-class-properties-on-event-serialization)

**Comment by nblumhardt** [comment]
Following up on StackOverflow. Thanks!
