### ISSUE TITLE
Unexpected WriteTo.Logger minimum logging level

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog#788]
I'm pretty new to Serilog, and I'm trying to follow a path of least resistance.

I have a code like this:

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.SomeSink() //doesn't matter which
                .WriteTo.Logger(lc => lc
                    .Filter.ByExcluding(Matching.FromSource<ApplicationLifecycleModule>())
                    .WriteTo.SomeOtherSink())
                    )
                .CreateLogger();

So basically, I have several sinks, and I want one of them to exclude some events. But while all events were logging to `SomeSink`, `SomeOtherSink` got only those of them having LogLevel above or equal to `Information`. Can you spot the problem? It's pretty hard, actually, because it is _absence_ of  `MinimumLevel.Verbose()` inside `WriteTo.Logger()` that leads to this.

Simply speaking, subloggers are not inheriting parent logger's minimum log level, and this is not exactly obvious (and I'm actually not sure this is an expected behavior).

**Comment by nblumhardt** [comment]
Hi Serg,

This is one of the pain points (I hope) we've fixed in Serilog 2.0; are you able to upgrade to the RC?

Regards,
Nick

**Comment by nblumhardt** [comment]
(Sorry, silly _Close and comment_ button placement...)

**Comment by srogovtsev** [comment]
I am pretty sure I can. Is there somewhere a list of changes between 1.5 and 2.0, to assess it more carefully?

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog/blob/staging-2.0/CHANGES.md should have it :+1:

**Comment by srogovtsev** [comment]
Seems like (hopefully) nothing will break (although I'll have to pull in a few more packages). Thanks!

(I can get back later with the upgrade experience, if you want)

**Comment by nblumhardt** [comment]
Thanks Serg, that would be great.

**Comment by srogovtsev** [comment]
Upgrade experience goes something like this:

1. Upgrade packages
2. Add packages for AppSettings
3. Clean up now-redundant minimum level in subloggers
4. Compile, deploy, test
5. ???
6. Profit!

**Comment by nblumhardt** [comment]
Awesome, glad to hear the process was smooth :+1:
