### ISSUE TITLE
Logging not working with latest stable release 2.0.0 with .NET 4.x versions

### ISSUE THREAD

**Issue by rgrajan** [serilog/serilog#794]
I have tried the simple logging sample with the latest stable release 2.0.0. The error is unable to load Serilog.Sinks.PeriodicBatching, "Could not load type 'Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink' from assembly"

First issue i noticed is that the PeriodicBatching is not installed automatically by the nuget package manager, then i have installed manually, still i got the error. Then i looked at the dependencies of PeriodicBatching where i saw couple of assemblies like System.Collections.Concurrent & System.Threading.Thread. Both are not installed then i noticed that System.Threading.Thread will not install in .NET 4.5.x projects. Then i upgraded the project to 4.6.1. Still the same error.

Fusion log viewer says load error in System.Web then i downloaded the source of Serilog.Sinks.PeriodicBatching and tried to add as project reference to debug further. Now the project itself is not opened because this assembly requires to install .NET Core SDK and i have installed only .NET 4.x versions. i.e Serilog.Sinks.PeriodicBatching has dependency with .NET Core 1.0.x version and not working with .NET 4.x versions. Please check.

I have recently formatted the system and not yet installed .NET core and that's why i am able to find out this error. The exact error when i open the project is, 
"The project is configured to use .NET Core SDK version 1.0.0-preview2-003121 which is not installed or cannot be found under the path C:\Program Files\dotnet. These components are required to build and run this project."

**Comment by adamchester** [comment]
Hi @rgrajan, I created a new .NET4.5 console application and was able to reference Serilog and Seq (Sink which uses PeriodicBatching). It worked. When targeting NET45, these packages/assemblies have no dependencies outside of the framework itself (and Serilog).

Are you able to share an example of a failing solution?

**Comment by rgrajan** [comment]
[serilog-sample.zip](https://github.com/serilog/serilog/files/337050/serilog-sample.zip)

@adamchester i have attached the sample. Do you have .NET Core 1.0.0 installed in your system? If you have installed, please uninstall and try with only .NET 4.x

**Comment by adamchester** [comment]
Hi @rgrajan, I had a quick look, and the first issue is related to mismatched dependencies.

What you should do in the short term is use Serilog 1.5.14 instead of 2.0.0.

We are still publishing all the required 2.0.0 compatible packages, and some of the ones you have referenced are pre-release incompatible versions.

**Comment by rgrajan** [comment]
Thanks @adamchester, I have started using 1.5.14 version. But the issue is with Serilog.Sinks.PeriodicBatching 2.0.0 which is not working with .NET 4.x versions without .NET Core 1.0.0. Please check during the final release.

**Comment by adamchester** [comment]
Hi again @rgrajan, your sample above had references to RC versions:

```xml
<package id="Serilog.Settings.AppSettings" version="2.0.0-beta-537" targetFramework="net461" />
<package id="Serilog.Sinks.AzureTableStorage" version="2.0.0-beta-20" targetFramework="net461" />
```

They have been updated to `2.0.0` now, and both support `net45` (which is compatible with `net461` that you are using). Can you give them another try now?

Please feel free to reopen this issue if you're still having trouble.
