### ISSUE TITLE
Shared Build Infrastructure

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#795]
The build system has acquired some tech debt that we've put off addressing until .NET Core's tooling stabilized. While we're still only able to use a pre-release SDK now that the .NET Core runtime is out, it's time to jump on some of this stuff to keep everyone sane.

 - [x] Identical build scripts - `appveyor.yml` and `Build.ps1` should be identical across all repositories. The versions in [serilog-settings-appsettings](https://github.com/serilog/serilog-settings-appsettings) has been built with this goal in mind.
 - [x] Simple dev/master branch versioning and publishing - the scripts in the repo mentioned above also aim for this; ideally `project.json` version numbers should rev on the dev branch, e.g. as `2.1.0-*` leading to dev builds like `2.1.0-dev-123`. On merging to master, the build system omits the suffix and `2.1.0` is published without requiring any project.json changes. Before new work begins on dev, it's modified to reflect the next planned build, e.g. `2.2.0-*`.
 - [ ] Correct GitHub release tagging - the (master) builds should tag git with the version number from project.json, not the build number as is being done currently in repos with this enabled
 - [x] New build agent account - the account used for GitHub tagging needs to be a project-specific one (Nick opportunistically reappropriated his Seq build agent to get this off the ground, without realising the account name is shown on the Releases page...)
 - [ ] Easy way to share build scripts between repos - e.g. a repo with Install.ps1 + Build.ps1 + other reused build artifacts

**Comment by merbla** [comment]
Also include:

- [ ] `build.sh` file for OSX/*nix build/development
- [ ] Move CLI and Tooling version into simple env args to allow for migration of RTM tooling. See [here](https://github.com/serilog/serilog/pull/792) as a possible solution.

**Comment by nblumhardt** [comment]
I'm finding the current build system pretty adequate, perhaps it's time to close this and just chip away at improvements as they're needed (and when the .NET Core tooling hits 1.0 ;-) )
