### ISSUE TITLE
Modifying config after the logger is created

### ISSUE THREAD

**Issue by vincentparrett** [serilog/serilog#797]
I really need a way to modify the configuration whilst an application is running. 

Use Case - enable/disable debug logging. 

I want to change an app.config setting to turn on debug logging (to a file) without restarting (which is what we currently do). The reason for not wanting to restart is because sometimes a intermittent fault goes away after restarting, being able to turn on debug logging whilst it's still happening would be a major bonus. 

Edit : Found the .ControlledBy config which helps a lot, but still need to change sinks or at least enable/disable them on the fly.

**Comment by IanYates** [comment]
See https://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/

You can create a separate logger for the file and have your main app logger send events to the file logger.  With that configuration you can have separate logging levels, intercept the logging (I tend to use RX observables for that but there are other ways), etc.

**Comment by nblumhardt** [comment]
Hi @vincentparrett - closing this assuming the link above helped sort this out. Please let us know if you need further info.

**Comment by vincentparrett** [comment]
yes,  that works for me.
