### ISSUE TITLE
Dispose sinks along with logger

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#8]
LoggerConfiguration may return a (disposable) Logger instead of ILogger, to avoid making ILogger itself disposable. Only the root logger should be disposable. Enrichers probably don't require disposal.

**Comment by guillaume86** [comment]
How did this evolved? Is the responsability of disposing the event sinks let to the implementator?

**Comment by nblumhardt** [comment]
Hi @guillaume86 - no, in Serilog today it's sufficient to dispose the logger. `ILogger` itself is not disposable, so something like the following is required:

```csharp
((IDisposable)Log.Logger).Dispose();
```

**Comment by guillaume86** [comment]
Thanks, I'll be able to simplify my code a bit then.

**Comment by Refresh06** [comment]
@nblumhardt 

Why don't we want the ILogger interface to be disposable?

This would enable the usage of using(var log =...) and simplifying the above example to:
`Log.Logger.Dispose();`

Your example is not safe by the way. In case a logger that isn't disposable is returned, the cast will fail.

**Comment by IanYates** [comment]
Yeah I do (logger as IDisposable)?.Dispose() in the shutdown of my app just because I'm pedantic :D

Disposal implies a very final action.  Serilog v2 introduces a Flush() (writing from memory - maybe it's close?) method so you get the flushing behaviour that was previously only accesible via Dispose().  Loggers are nice to share around and it's annoying to think about whether or not something has been disposed when really all you want is to be sure you've flushed your data.

However I can see some use case for being able to dispose sinks if they have some connections that themselves are best disposed early.  However (again!) the sinks I've seen tend to work on a periodic basis where they wake up, do work and then sleep again so things are uploaded in batches.  This means they tend to not hold on to nasty disposable objects themselves (writing this over breakfast - don't quote me!!).

**Comment by nblumhardt** [comment]
Correct - 2.0 has a new method to deal with the static `Log` class:

```csharp
Log.CloseAndFlush();
```

I don't think `ILogger` is a candidate for adding `Dispose()` because most of the loggers in an app aren't disposable - `ForContext()` returns an `ILogger` but no resources/sinks are directly associated with it.

_Ideally_, `LoggerConfiguration.CreateLogger()` would return a `Logger` class that implements both `IDisposable` and `ILogger`.

There would need to be a few design decisions made, e.g. is `Log.Logger` still an `ILogger`? (I think "yes") but perhaps it's time to explore this further given the opportunity presented by the upcoming v2.

I'll have a look today :+1:

**Comment by nblumhardt** [comment]
Okay, I've had a look; unfortunately to make the return value of `CreateLogger()` a class, we'd have to either use more virtual dispatch (in addition to the current interface dispatch, so slower) or get rid of the `SilentLogger` optimisation (slower). Both are global perf regressions that I don't think are worth it for this change, even though it seems worthwhile.

The other option is to return `ILoggerPipeline`, which is both `ILogger

**Comment by nblumhardt** [comment]
...so, not particularly keen on either. Will have to spend some more time on it.

**Comment by Refresh06** [comment]
I totally agree that the disposable pattern smells.

I've made a Dispose extension method for ILogger that does the (log as IDisposable)?.Dispose(), and an AsDisposable that returns a small wrapper DisposableILogger.

Fits my bill, but I don't use the static Log.Logger at all.

**Comment by slepmog** [comment]
> Dispose sinks along with logger

Unless I misunderstand something, that was a very bad decision? It seems to prohibit a [common pattern](https://stackoverflow.com/a/67562497) where you have a nested temporary logger that logs to more sinks than the parent, and to the parent too:

```cs
using (var temporary_nested_logger = new LoggerConfiguration()
  .WriteTo.Sink((ILogEventSink)Log.Logger) //Here we're passing in the parent logger
  .WriteTo.Sink(new SomeOtherSink())
  .CreateLogger())
{
   ...
}
```

When `temporary_nested_logger` is disposed, it disposes the sink which is the parent logger, and the parent logger disposes its sinks too, and the entire logging stops in the entire app - that is, to all sinks that are disposable, in our case that is a Seq sink. Sinks that are not disposable remain unaffected.

And all of this remains undetected by `Serilog.Debugging.SelfLog`. The events simply stop to arrive to Seq until the app is restarted.

We are currently forced to use a workaround where we have a non-disposable wrapper around any parent sinks that we pass to nested loggers:

```csharp
internal sealed class NonDisposableSinkWrapper : Serilog.Core.ILogEventSink
{
    private readonly Serilog.Core.ILogEventSink _actualSink;

    public NonDisposableSinkWrapper(Serilog.Core.ILogEventSink actualSink)
    {
        _actualSink = actualSink;
    }

    public void Emit(LogEvent logEvent)
    {
        _actualSink?.Emit(logEvent);
    }
}
```
```csharp
using (var temporary_nested_logger = new LoggerConfiguration()
  .WriteTo.Sink(new NonDisposableSinkWrapper((ILogEventSink)Log.Logger))
  .WriteTo.Sink(new SomeOtherSink())
  .CreateLogger())
{
   ...
}
```

and this indeed fixes the missed messages straight away.

---

**Am I an idiot for not finding a switch the controls this behaviour, or is it worth opening an issue?**

*(Before you mention it, Yes, we have looked into configuring the main logger with conditional sink selection. The problem with that is that you then have to have additional properties on all messages that control which sinks will be selected, and these properties then get logged into all sinks that provide structured storage, and they don't belong there. To solve that, we would need to deconstruct each message type to remove these routing properties, and that is just nasty.)*
