### ISSUE TITLE
Please update NuGet package Serilog.Sinks.NLog to support Serilog 2

### ISSUE THREAD

**Issue by HakanL** [serilog/serilog#801]
It maxes out at Serilog 1.5.4

**Comment by nblumhardt** [comment]
Thanks for the note Hakan. I didn't realise the tracker is still turned off in that repository. I've moved the issue to: https://github.com/serilog/serilog-sinks-nlog/issues/1

I will add the "up-for-grabs" label as I don't think there's a lot of activity going on in that repository - any help on that front would be great.

Cheers!
