### ISSUE TITLE
upgrade serilog-sinks-exceptionless

### ISSUE THREAD

**Issue by dampee** [serilog/serilog#803]
Hi

There is a new commit done by a guy of exceptionless to support the latest stable version (https://github.com/serilog/serilog-sinks-exceptionless/commit/86aa9fdca3d17d54c6bd469a65e65e93407d44ab).  But this has not been pushed to nuget.  

I would love to see this change(s) pushed.  :-)

Damiaan

**Comment by niemyjski** [comment]
Looks like build failed due to semver. I'm looking into it :)

**Comment by dampee** [comment]
That's why "exceptionless" is so cool.  See how quick someone answered...  ;)

**Comment by niemyjski** [comment]
Should be fixed, please close this issue.

**Comment by dampee** [comment]
Thanks a lot!
