### ISSUE TITLE
Multiple sinks not working?

### ISSUE THREAD

**Issue by styxke** [serilog/serilog#804]
Hi,

I'm trying to use multiple sinks for events of a different loglevel, but I can't seem to get it to work.
The configuration:

```csharp
return new LoggerConfiguration()
                  .MinimumLevel.Verbose()
                  .WriteTo.Logger(config => config
                    .MinimumLevel.Verbose()
                    .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)
                    .WriteTo.File("c:\\...\\log.txt"))
                  .WriteTo.Logger(config => config
                    .MinimumLevel.Verbose()
                    .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information)
                    .WriteTo.Seq("http://...:5341/"))
                  .CreateLogger();
```

I get only information level events in Seq and an empty textfile.
Maybe I'm interpreting the docs incorrectly?

**Comment by nblumhardt** [comment]
Thanks for the note.

Just to make sure we're on the same page, I've created a .NET 4.5 console app, installed the `Serilog.Sinks.Console` package, and slightly modified your example to:

```csharp
var log = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Logger(config => config
        .MinimumLevel.Verbose()
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)
        .WriteTo.Console())
    .WriteTo.Logger(config => config
        .MinimumLevel.Verbose()
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information)
        .WriteTo.Console())
    .CreateLogger();

log.Debug("This is debug");
log.Information("This is info");
```

Both events are written to the console. Changing it to:

```csharp
var log = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Logger(config => config
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)
        .WriteTo.Console())
    .WriteTo.Logger(config => config
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information)
        .WriteTo.Console())
    .CreateLogger();
```

Also works as I expect. I think the problem is likely to be specific to the file - does the process writing the file have adequate permissions? You can verify this be enabling [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics).

In any case, am I correct to assume that the config you really want is this one?

```csharp
var log = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.File("c:\\...\\log.txt")
    .WriteTo.Seq("http://...:5341/", restrictedToMinimumLevel: LogEventLevel.Information)
    .CreateLogger();
```

Hope this helps,
Nick

**Comment by styxke** [comment]
I was able to find a problem with the use of SelfLog and I got it to write to both sinks like I want it.
But I wasn't able to get it to work with:
```c#
var log = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Logger(config => config
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)
        .WriteTo.Console())
    .WriteTo.Logger(config => config
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information)
        .WriteTo.Console())
    .CreateLogger();
```

Final working code:
```c#
return new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Logger(config => config
        .MinimumLevel.Verbose()
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)
        .WriteTo.File("c:\\temp\\log.txt"))
    .WriteTo.Logger(config => config
        .MinimumLevel.Verbose()
        .Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Information)
        .WriteTo.Seq("http://...:5341/"))
    .CreateLogger();
```
I need to specifiy the MinimumLevel lines like this or it won't work.

I really want to log different levels to different sinks, unlike in the code in your assumption: you log all levels to the file but only information as a minimum level to seq?

**Comment by styxke** [comment]
I upgraded to the 2.0 version of serilog, now it's working perfectly with the solution you provided in your assumption.

**Comment by nblumhardt** [comment]
Ah great, thanks for the follow-up. Some `WriteTo.Logger()` behavior [changed in 2.0](https://github.com/serilog/serilog/pull/654).
