### ISSUE TITLE
Configuration-Basics WriteTo.RollingFile Not Writing file

### ISSUE THREAD

**Issue by nathvi** [serilog/serilog#805]
I slightly modified the code in the Configuration Basics tutorial as such:
`Log.Logger = new LoggerConfiguration().WriteTo.LiterateConsole()
            .WriteTo.RollingFile(@"C:\SeriLog\Log.txt").CreateLogger();`

The calling code to write is like this:
`Log.Information("Test 1 2. Test 1 2");`

The program runs fine, but there is no folder created, and no exceptions indicating that the folder cannot be created. What am I doing wrong?

**Comment by nathvi** [comment]
I know why there were no exceptions indicating that the folder cannot be created. It's because there is a
**REQUIRED** parameter inside of the file path, which isn't enforced by the compiler in any way.
The file path requires the {Date} string inside of it. Poor design.

**Comment by nblumhardt** [comment]
Hi @nathvi - this isn't correct, `RollingFile()` will insert `{Date}` into the path itself if not explicitly supplied:

https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/TemplatedPathRoller.cs#L56

I use configuration like your first example often; I'd guess that some kind of permissions issue perhaps prevented creation of the log file on your first attempt?

If you are interested in trying to track down what went wrong, you can enable Serilog's own debugging with something like:

```
SelfLog.Enable(Console.Out);
```

Cheers,
Nick

**Comment by nathvi** [comment]
I think I messed up some dependencies when I copy pasted some nuget dependencies. Thanks.
