### ISSUE TITLE
Serilog Installation Error

### ISSUE THREAD

**Issue by aadil79** [serilog/serilog#806]
I am trying to install serilog and getting the following error:
Serilog' already has a dependency defined for 'Microsoft.CSharp'.

I was starting with a  .Net Framework 4.5 console project.

**Below is my Detailed information** 
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Ultimate

Architecture and Modeling Tools   06181-004-0451022-02530
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2013   06181-004-0451022-02530
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06181-004-0451022-02530
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06181-004-0451022-02530
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451022-02530
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451022-02530
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451022-02530
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06181-004-0451022-02530
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06181-004-0451022-02530
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools   12.4.51016.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Team Foundation Server 2013 Power Tools   12.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

NuGet Package Manager   2.8.50926.663
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.30626
Microsoft Office Developer Tools for Visual Studio 2013 ENU

OpenCoverUISettings   1.0
Visual Studio Integration for OpenCover

PowerShell Tools   1.3
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

TechTalk SpecFlow   2015.1
TechTalk SpecFlow - Binding business requirements to .NET code, http://www.specflow.org
Copyright © 2009–2013 TechTalk

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by adamchester** [comment]
Hi @aadil79 thanks for reporting this.

I've seen the same error with tools that use older versions of nuget, and I assume VS 2013 does too.

Can you try with a newer version of nuget command line?

**Comment by aadil79** [comment]
I will give that a shot and report back on the same.Thanks!

**Comment by aadil79** [comment]
@adamchester  that worked!. Thanks again.

**Comment by nblumhardt** [comment]
I hit this problem also, and updating from a 2.x `NuGet.exe` to a later one (3.x) resolved it, too.

Cheers!

**Comment by saitonakamura** [comment]
I'm getting the same error
Stackoverflow suggested nuget update, but there is no update to 3.x nuget version on Visual Studio 2012, and I'm using latest available `Version 2.8.60318.667`
Currently I workaround it by using latest 1.x serilog version (which is `1.5.14`), but it will be great if we can use 2.x serilog version with nuget 2.x version

**Comment by nblumhardt** [comment]
@saitonakamura you should be able to grab NuGet.exe manually, it's just a command-line tool IIRC. Not sure how ergonomic this will be but it'd be interesting to hear how you go if you try it out. Cheers!
