### ISSUE TITLE
Why is RollilngFile locking file?

### ISSUE THREAD

**Issue by nathvi** [serilog/serilog#808]
I'm calling a sample function twice...

`SampleFunction();
SampleFunction(); // Locking file... ???`

Where the implementation is a void method such that the inside looks like....

`Log.Logger = new LoggerConfiguration()`
                `.WriteTo.LiterateConsole()`
                `.WriteTo.RollingFile(pathFormat: @"C:\SeriLog\{Date}-Log.txt", outputTemplate: @"{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}")
                .CreateLogger();
            Log.Information("Explicit output template test");`

The second time I call SampleFunction, I get an error in the console:

"Rolling file target C:\SeriLog\20160711_010-Log.txt was locked, attempting to open next in sequence (attempt 1)" 

How do I fix this?

**Comment by nblumhardt** [comment]
Hi @nathvi - the built-in File and RollingFile sinks don't support multi-process scenarios, a network-based sink of some kind is a better option for these.

I recently opened a [ticket on the File sink](https://github.com/serilog/serilog-sinks-file/issues/7) with one option for supporting this, but it is non-trivial (to say the least :-) ).

**Comment by DmitryNaumov** [comment]
@nblumhardt log4net rolls files without locking, doing FILE_SHARE_READ. May be this is not about multiple processes writing to a file?

**Comment by nblumhardt** [comment]
@DmitryNaumov FILE_SHARE_READ isn't enough for the second file to perform writes, is it? I'd guess the log4net code you're looking at is upgrading access, or coordinating in another way. (I read the existing log4net file sharing impls a few years ago when building this thing, and the list of caveats was pretty long.)

**Comment by nathvi** [comment]
I seriously doubt that the problem is multiple processes trying to write to the same log. I'm calling the above code twice in a row... like
Code();
Code();

How would this ever be multiple processes?

**Comment by nblumhardt** [comment]
@nathvi ah, I see, yes - the edit makes it much clearer :+1: . You're opening the log file twice and not closing it in between.

When you configure Serilog, you need to construct the logger only _once_, and re-use it throughout the program.

If you do, for some reason, need to close/reopen the logger, you can `Dispose()` it (if an instance) or `CloseAndFlush()` the static `Log` class. I would guess that's not what you're after though.

Cheers!

**Comment by nathvi** [comment]
^.^ @nblumhardt , thanks!
