### ISSUE TITLE
Log.CloseAndFlush() and non http protocol scenarios

### ISSUE THREAD

**Issue by chandmk** [serilog/serilog#811]
How do we dispose Logger in non http protocol scenarios?

Ex: WCF net.tcp hosted in IIS/

There is a static AppInitialize method to initialize the log.  But nothing for gracefully shutting down the app.

**Comment by nblumhardt** [comment]
Hey, good to hear from you!

I haven't been into the nitty-gritty of WCF hosting for many years, so there may be a cleaner way, but handling the `AppDomain.Unloading` event (and `AppDomain.UnhandledException`) should provide a decent hook to do this. Just be careful when hooking `UnhandledException` that the handler fires _after_ any unhandled exceptions are logged (the fragility is the reason for moving away from this).

Let me know if you need more info.

**Comment by chandmk** [comment]
In the case of WCF,  IErrorHandler implementation gives the needed hooks to log the errors.  I am thinking AppDomain.Unloading should be a good place to try flush the log,

**Comment by nblumhardt** [comment]
:+1:
