### ISSUE TITLE
Log to multiple log files

### ISSUE THREAD

**Issue by akshetty9** [serilog/serilog#813]
I am logging events of all types to single Json file irrespective of LogLevel. Now I have a requirement to log some custom performance counters to a separate Json file. How can this be done in Serilog. Should I create different Logger Instance and use that where ever I am going to Log the performance counters? Want to use this with LibLog. If I use multiple log files, how can LibLog find out the logger? Our application logs performance counters like Number of call/sec, Call Duration etc for different APIs and can be viwed on PerfMon. Idea was to log these counters to a separate json file so that it can be transferred to LosStash/ELK. Since we are already using Serilog for logging we thought we can make use of it

**Comment by nblumhardt** [comment]
Howdy, thanks for getting in touch. Just answered via SO: http://stackoverflow.com/questions/38481227/serilog-log-to-different-files/38491795#38491795
