### ISSUE TITLE
Custom sink only logging at informational level and above

### ISSUE THREAD

**Issue by nathvi** [serilog/serilog#814]
I've included the custom sink that I've written.
The problem I'm having is that this sink will only log informational logs and above,
regardless of how I construct the logger. For example:

`Log.Logger = new LoggerConfiguration()
                .WriteTo.KeySink(publisher, restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Debug)
                .CreateLogger();`
            `Log.Debug("Ah, there you are!"); // This will not trigger the Emit function `

`Log.Logger = new LoggerConfiguration()
                .WriteTo.KeySink(publisher, restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Debug)
                .CreateLogger();`
            `Log.Information("Ah, there you are!"); // This will trigger the Emit function `

[KeySink.txt](https://github.com/serilog/serilog/files/376508/KeySink.txt)
[KeySinkLoggerConfigurationExtensions.txt](https://github.com/serilog/serilog/files/376509/KeySinkLoggerConfigurationExtensions.txt)

**Comment by nathvi** [comment]
There must be something I am fundamentally missing. Even when I'm using the Literate Console, I'm not getting the functionality I'm expecting. I'm using it like this:

`Log.Logger = new LoggerConfiguration()
                .WriteTo.LiterateConsole(Serilog.Events.LogEventLevel.Verbose)
                .CreateLogger();`
            `Log.Verbose("Ah, there you are!"); // This won't write to the console`

I'm expecting the above log to log to the console. Am I misguided?

**Comment by aensidhe** [comment]
> Default Level - if no MinimumLevel is specified, then Information level events and higher will be processed.

https://github.com/serilog/serilog/wiki/Configuration-Basics

**Comment by nathvi** [comment]
@aensidhe, 
I thought I did specify the minimumlevel... 

`Log.Logger = new LoggerConfiguration() .WriteTo.LiterateConsole(Serilog.Events.LogEventLevel.Verbose).CreateLogger();`

Even using named params doesn't work:
`Log.Logger = new LoggerConfiguration()
                .WriteTo.LiterateConsole(restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Verbose).CreateLogger();`
            `Log.Verbose("Ah, there you are!"); // This won't write to the console`

**Comment by aensidhe** [comment]
@nathvi try this:
````
Log.Logger = new LoggerConfiguration()
.MinimumLevel.Verbose() /// global minimum level
.WriteTo.LiterateConsole()
.CreateLogger();
````

**Comment by nathvi** [comment]
Yes, that works and makes sense. Thank you!
