### ISSUE TITLE
Bug in overriding while lowering logging level

### ISSUE THREAD

**Issue by aensidhe** [serilog/serilog#815]
Hi. 

Tried to use #754 for our "buggy parts" of code. It seems that pipeline LogLevel ignores all overrides. Full test is in attachment. Code is below.

````
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override(nameof(SerilogTesting), LogEventLevel.Verbose)
    .WriteTo.LiterateConsole(outputTemplate: "[{Timestamp:HH:mm:ss} {Level} {SourceContext}] {Message}{NewLine}{Exception}")
    .CreateLogger();

Log.Logger.Verbose("A"); // <-- not printed, expected

Log.Logger.ForContext<Program>().Verbose("1"); // <-- not printed, NOT expected
````

[SerilogTesting.zip](https://github.com/serilog/serilog/files/377872/SerilogTesting.zip)

**Comment by nblumhardt** [comment]
Thank you for the report and the thorough reproduction - much appreciated. I've just opened a PR with what I expect should be the fix for this.

Regards,
Nick

**Comment by aensidhe** [comment]
@nblumhardt wow. Thank you very much!
