### ISSUE TITLE
Updating to Latest Stable (2.1.0) causes Nuget error

### ISSUE THREAD

**Issue by aidanmorgan** [serilog/serilog#818]
I've just updated to the latest version of Serilog, and now when I try and package my project I get the following error:

`'Serilog' already has a dependency defined for 'Microsoft.CSharp'
`

The entry in my packages.config is:

`
  <package id="Serilog" version="2.1.0" targetFramework="net461" />`

Has there been a change in the latest nuget version that would have introduced this issue?

**Comment by nblumhardt** [comment]
Thanks for the report. Which VS/NuGet versions are you using, and are you upgrading from 1.5 or from 2.0? Cheers!

**Comment by aidanmorgan** [comment]
I've experienced this upgrading from 1.5 and 2.0. I am experiencing the issue in both VS2015u3 and VSTS.

**Comment by nblumhardt** [comment]
Thanks for the additional info. Which NuGet.exe version are you using though? Serilog 2.x requires NuGet 3, so trying to pack with NuGet.exe 2.x can cause issues like this one.

**Comment by aidanmorgan** [comment]
In VS2015u3 it is version 3.4.4.1321
As for VSTS, I am not sure - but it appears to be a V3 NuGet as the feed URL's are v3.

**Comment by nblumhardt** [comment]
Thanks again for the info. Even in those environments, it's possible that the NuGet executable, e.g. under a checked-in `.nuget` folder, is out-of-date.

Can you please track down the command-line that's running for `pack`, or the executable itself, and send the version printed by `NuGet.exe help`?

Cheers,
Nick

**Comment by aidanmorgan** [comment]
The executable that is running shows the version on VSTS as 3.5.1.1621

**Comment by aidanmorgan** [comment]
I'm starting to suspect that this is actually caused by an issue in the hosted VSTS agent as it seems to be resolving itself through my build pipeline now.

**Comment by cswanson0** [comment]
I had the exact same issue and it was indeed a NuGet version.  We use Teamcity and were using NuGet 2.8. As soon as I installed and switched to the latest 3.44 it worked fine.

**Comment by saitonakamura** [comment]
@aidanmorgan  You can workaround it by using old 1.5.14 version (it also applies to sinks and other packages)

**Comment by nblumhardt** [comment]
> it seems to be resolving itself through my build pipeline now

@aidanmorgan closing on the assumption you're in the clear, let us know if you have any more trouble. Cheers all!
