### ISSUE TITLE
Re-enable the macOS target for Travis

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#824]
https://travis-ci.org/serilog/serilog/jobs/151408122

> System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.

It appears that libssl or some other library dependency is missing.

**Comment by merbla** [comment]
Related to 

https://github.com/dotnet/cli/issues/2229

https://github.com/serilog/serilog-sinks-splunk/issues/30

**Comment by nblumhardt** [comment]
@merbla any ideas around this? Shall we disable the macOS build to keep everything else moving along?

**Comment by merbla** [comment]
@nblumhardt it does not seem to be moving too quick to a resolution.

I have disabled the Travis build in the repo settings.

**Comment by nblumhardt** [comment]
Needs:

```diff
 os:
+   - osx
    - linux
```

**Comment by nblumhardt** [comment]
Some additional info from @joshka:

https://github.com/nblumhardt/serilog/commit/d8cd24777a04dd0af9715e5a3b81aa2dde0d3131#commitcomment-18664311

**Comment by merbla** [comment]
MOAR info https://github.com/caskroom/homebrew-cask/pull/23803

**Comment by adamchester** [comment]
Yep I had to do this too, and worked for me 👍

**Comment by merbla** [comment]
@nblumhardt I will have a look into this again.  If nothing jumps up then I suggest we close it.

**Comment by adamchester** [comment]
@merbla [this](https://github.com/messagetemplates/messagetemplates-fsharp/blob/dotnet-cli-rc4/tooling/configure-dotnet-cli-osx.sh) worked [for me](https://travis-ci.org/messagetemplates/messagetemplates-fsharp/jobs/196070943#L66)

```bash
#!/bin/bash

brew config

# instructions taken from https://www.microsoft.com/net/core#macos
brew update
brew install openssl
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

**Comment by nblumhardt** [comment]
In #932.
