### ISSUE TITLE
.Enrich.WithProperty("PropertyName", () => ValueThatConstantlyUpdates);

### ISSUE THREAD

**Issue by ghuntley** [serilog/serilog#829]
See the example the code below:

```
Log.Logger = new LoggerConfiguration()
	.Enrich.WithProperty("ApplicationVersion", NSBundle.MainBundle.InfoDictionary[new NSString("CFBundleVersion")].ToString())
	.Enrich.WithProperty("InstallationIdentifier", UIDevice.CurrentDevice.IdentifierForVendor.AsString())
	.Enrich.WithProperty("BatteryLevel", UIDevice.CurrentDevice.BatteryLevel)
	.Enrich.WithProperty("BatteryState", UIDevice.CurrentDevice.BatteryState)
	.Enrich.WithProperty("DeviceName", UIDevice.CurrentDevice.Name)
	.Enrich.WithProperty("DeviceType", UIDevice.CurrentDevice.UserInterfaceIdiom)
	.Enrich.WithProperty("DeviceModel", UIDevice.CurrentDevice.Model)
	.Enrich.WithProperty("DeviceOrientation", UIDevice.CurrentDevice.Orientation)
	.Enrich.WithProperty("OperatingSystem", UIDevice.CurrentDevice.SystemVersion)
	.Enrich.WithProperty("NetworkConnectivity", CrossConnectivity.Current.ConnectionTypes)
```

- The properties - `NetworkConnectivity`, `DeviceOrientation`, `BatteryState` and `BatteryLevel` are not constant and I'd like to have Serilog fetch the value on each log event
- Potentially have the property enabled/disabled and remotely controllable from Seq via the existing `LoggingLevelSwitch` functionality on a per property basis. "ie. define battery status == debug, network connectivity == informational, deviceorientation == verbose" if there is a serious performance cost.

**Comment by nblumhardt** [comment]
Hi Geoffrey!

The config here will be a lot cleaner if you use:

```csharp
    .Enrich.With<BatteryDetailsEnricher>()
```

And implement `BatteryDetailsEnricher` as an `ILogEventEnricher` adding both `BatteryLevel` and `BatteryState`.

I can see how a delegate version of `WithProperty()` would work, but in practice once configuration gets to this level of complexity refactoring to some enrichers will be much nicer to look at and test.

The idea of turning on/off enrichers based on level is a really interesting one, I need to give it a bit more thought, thanks!

**Comment by ghuntley** [comment]
Alright, sweet I'll take a look into doing proper implementations of `ILogEventEnricher`.

> re: The idea of turning on/off enrichers based on level is a really interesting one, I need to give it a bit more thought, thanks!

Yeah, that's the thing. I'm not actually using Serilog/Seq for "logging" in the traditional sense, it is more of an eventstore and there are lots of events I wish to always be sent back up server side but ultimately the level of detail of properties (ie. which) attached on the event is what matters in this type of setup.
