### ISSUE TITLE
Conflict between logger name and parameter

### ISSUE THREAD

**Issue by oguzhaneren** [serilog/serilog#831]
Hi, 

My configuration is:

```
var log = new LoggerConfiguration()
	.Filter.ByIncludingOnly(Matching.WithProperty<string>("Name", n => n.StartsWith("MyProject.")))
	.Enrich.WithProperty("Version", GetProductVersion())
	.MinimumLevel.Verbose()
	.WriteTo.LiterateConsole()
	.WriteTo.RollingFile(new JsonFormatter(), Path.Combine(logDir, "log-{Date}.txt"), restrictedToMinimumLevel: LogEventLevel.Debug)
	.WriteTo.Logger(lc => lc
		.Filter.ByIncludingOnly(Matching.WithProperty<string>("Name", n => n.StartsWith("MyProject.Message.")))
		.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
							   {
								   AutoRegisterTemplate = true,
								   IndexFormat = "myproject-logs",
								   MinimumLogEventLevel = LogEventLevel.Verbose

							   })
		, LogEventLevel.Verbose)
	.CreateLogger();		
```
I don't want to log anything if logger namespace doesn't starts with "MyProject.". This configuration ok for that.

But when I pass a parameter as "{Name}" on logging that parameter creates a conflict between logger name and parameter itself.

`Logger.Info("{Name} started","MyTask");` is not working.

**Comment by nblumhardt** [comment]
When you're working with loggers-for-types, try using the `Log.ForContext<T>()` and `Matching.FromSource()` methods. These will use an underling `SourceContext` property that will be distinct from the `Name` property you're using.

Cheers!

**Comment by oguzhaneren** [comment]
thank you !
