### ISSUE TITLE
The ContextFor<T> is not remembering the set value.

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog#838]
NOTE: Not sure if this is a possible bug or 'by design'.

---

When using the NLog sink (yes, that is in another repo but the issue is in this repo) I noticed that the 'Source/System' value was always `General` and not the full namespace of the class I was trying to set.

I ended up stepping through the code and seeing this behaviour:

- `myLogger.ForContext<MyClass>();` <-- I manually define the context.
- Step through _this_ code (which enters `Logger.cs`)
- Serilog ends up creating a custom `Enricher` -> a `FixedPropertyEnricher` and inside that _is_ the correct value (the full name of the Class).
- the code finally returns a `new Logger(..)` and this includes setting the global enricher in the ctor of this method .. which it sets ... but as soon as it leaves this ctor, the `_enricher` magically and quickly resets back to an `EmptyEnricher`.
- Finally, when the `Emit` method is called in the NLog repo, then the `LogEvent.Properies` is empty, when it should have the value of the Class in it.

There's a massive possibility that I have no idea what I'm doing and this is all by design and I'm missing some obvious understanding.

I've tried to highlight this using the a rough screenshare to help explain this - apologies for the potato quality....

![untitled-screencast](https://cloud.githubusercontent.com/assets/899878/18071411/e364f9e2-6e98-11e6-8a73-20619bd3f52b.gif)

**Comment by nblumhardt** [comment]
Howdy! I suspect the issue's probably in the NLog integration; I had a look at `ForContext<T>()` and the screencast (thanks!) to check we haven't let anything silly slip through, and everything's working fine for me.

> as soon as it leaves this ctor, the _enricher magically and quickly resets back to an EmptyEnricher.

When this happens in the video, `this` is no longer the same object. When it's a `FixedPropertyEnricher

**Comment by nblumhardt** [comment]
...urg, sorry, keyboard fumble.

When it's a `FixedPropertyEnricher`, `this` is the child logger being created for the new logging context. When it changes back to `EmptyEnricher` you're looking at a `this` which corresponds to the parent logger that the context is being created from.

Are you using the return value of `ForContext<T>()` to log the events?

Cheers!

**Comment by PureKrome** [comment]
But with the NLog library, it has [this main entry point only](https://github.com/serilog/serilog-sinks-nlog/blob/dev/src/Serilog.Sinks.NLog/Sinks/NLog/NLogSink.cs#L18) :

` public void Emit(LogEvent logEvent)`

and the `Properties` in the `LogEvent` instance is empty, The main serilog library sets up this value, I thought. Which is why I thought to look at the `Serilog` library instead of the nlog sink library.

---

>Are you using the return value of ForContext<T>() to log the events?

![image](https://cloud.githubusercontent.com/assets/899878/18071635/d4aacca4-6e9a-11e6-9348-1ccebd61d53c.png)

**Comment by PureKrome** [comment]
I can also grab another screen shot of me stepping into the `Information` method, above. Would that help? (i'm .. not sure I've actually done that, tbh ..)

**Comment by nblumhardt** [comment]
Aha :+1: your code should read:

```csharp
var programLogger = loggingService.ForContext<Program>();
programLogger.Information("## Starting Web Job ##");
// etc.
```

The result of `ForContext<T>()` is a logger instance that you need to call through in order to record the context.

To do the ambient context instead you can add `Enrich.FromLogContext()` to your `LoggerConfiguration` and write:

```csharp
using (LogContext.PushProperty(Constants.SourceContextPropertyName, typeof(Program).FullName))
{
    loggingService.Information("## Starting Web Job ##");
    // etc.
```

(`LogContext` is more often used for pushing properties like `MessageId` and so-on, hence the lack of a type-based push method.)

HTH!

**Comment by PureKrome** [comment]
![](http://i.giphy.com/6z8IzFQWtv1ss.gif)

Ahhh! got it!

case closed and I still suck. Status quo is normal. 

Thanks Nick - very much appreciated.
