### ISSUE TITLE
Destructure -> Capture? (Discussion)

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#839]
We might benefit from a bit of a terminology clean-up; dragging along the term "destructuring" in the API makes the library more confusing than it needs to be.
- `@` - _structure-capturing operator_
- `ICapturingPolicy` and `TryCapture()`
- `Capture.AsScalar()`, `Capture.ByTransforming()`
- `Capturing.Default`, `Capturing.Stringify`, `Capturing.Structured`

I think this can be done without too many breaking changes: the old interfaces and types can stick around, and where they are plugged in, we can adapt them to the newer types/names. E.g.:

``` csharp
    .Destructure.With<T>()
```

would, under the hood, create the `IDestructuringPolicy` and wrap it in an `ICapturingPolicy` adapter and delegate to `Capture.With(wrapper)`.

The old types and members could be marked obsolete and non-browsable for the next couple of major releases.

The most painful-looking changes such as the parameter rename on `ForContext` from `destructureObjects` to `captureStructure` would be source-breaking changes, but not binary-breaking ones.

What's everyone think? Feasible? Worth some inevitable headaches? This would be a 3.0 kind of change, and only something we'd do if other subtle breaking changes come into 3.0, for example I am working on a performance-oriented changeset that slightly modifies `TextToken` and `PropertyToken` constructors. "2017" kinds of things :-)

**Comment by adamchester** [comment]
Totally agree that your proposed terminology is much better.

Totally unsure if it's worth the pain :smile: 

My vote is :+1:

**Comment by tsimbalar** [comment]
Maybe it's just me, but I kinda liked *destructuring*. Even if the terminology is not great, it is kind of consistent with terms like *structured logging*. 

Also, while "structure capturing" is probably better semantically, it's kind of a mouthful :) , and using "capturing" alone is kind of vague .

Totally subjective opinion, of course ;)
