### ISSUE TITLE
Create Templates for issues, PRs etc.

### ISSUE THREAD

**Issue by merbla** [serilog/serilog#842]
From @ghuntley, create templates similar to https://github.com/serilog/serilog-sinks-xamarin/tree/master/.github

https://gitter.im/serilog/serilog?at=57c6b0742dcc4f312948e44c

**Comment by NRKirby** [comment]
Hi,

This PR is for issue #842. I haven't made any changes to the given templates in the issue. If you want them different in any way pls let me know how...

Nick

**Comment by nblumhardt** [comment]
With some more thought.. I wouldn't say issue/PR description quality is a big problem right now. Perhaps we close for now?

**Comment by merbla** [comment]
Agreed.  I have a PR in the works.  When I submit we can discuss then
