### ISSUE TITLE
[wiki] How to develop a sink / new sink for Logmatic.io

### ISSUE THREAD

**Issue by gpolaert** [serilog/serilog#843]
Hi everybody,

I'm working for Logmatic.io. Some of my users want to connect Serilog to [Logmatic.io](http://logmatic.io).
We decided to help them, and start to develop a sink for that.

Unfortunately, I not very confortable with DotNet and Serilog (please, don't blame me :)), and the page about developing a sink is not available.

So, are there some requirements that I have to know? 
If yes, I can compile them and propose a draft for the wiki.

Thanks, Guillaume

**Comment by gpolaert** [comment]
So, I've some tests. Right now, I'm blocked, because I can run the serilog-generator :'(
Here is the first draft: https://github.com/gpolaert/serilog-sinks-logmatic

Anything strange?

**Comment by nblumhardt** [comment]
Hi Guillaume, thanks for dropping by! Great to hear you are developing a sink.

Your best bet with this is to find an existing sink that works in a similar way to what you anticipate, and model your sink off of that (there are many different approaches).

Assuming logmatic is doing JSON + HTTPS, the things to consider are:

 * You'll need to create a formatter like: https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/RenderedCompactJsonFormatter.cs (there are more examples but this one is probably pretty close to what you need)
* A sink class derived from `PeriodicBatchingSink`, if you want to send batched payloads
* Configuration methods that extend `LoggerSinkConfiguration` and live in the `Serilog` root namespace, like: https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs (the parameter names on configuration methods are used to support XML/JSON configuration also)

There are a few JSON/HTTPS sinks that get a lot of use - Seq, Splunk, Elasticsearch are all mature; the MongoDB sink might be a simpler one to get started with as an example.

**Comment by nblumhardt** [comment]
Good timing! :-) I wouldn't worry too much about serilog-generator; it's still often easier to just add a simple console app to the solution for testing.

I'm "watching" your repository, as you go perhaps raise bugs there and I'll jump in and comment/help where possible? There are a few people following along on this issue tracker so moving the discussion over there will save a bit of noise.

**Comment by nblumhardt** [comment]
Looks like it's coming together! I will close this ticket, I've added a listing to https://github.com/serilog/serilog/wiki/Provided-Sinks, some help with the wiki would be great when you've had some experience building sinks but it's probably fairly tricky content to put together right away. Thanks! :-)
