### ISSUE TITLE
Camelcase properties in mongodb sink

### ISSUE THREAD

**Issue by mribichich** [serilog/serilog#845]
Hi there, I wanted to know if there is a way to camelcase the properties when using MongoDb, I couldn't find one.

And if there is a way to flat my custom properties along side the logs properties, without using: 

```
Properties : {  
   ....
}
```

I would like something like this:

```
{
  "timestamp": "2015-04-16T12:35:36.0900887+02:00",
  "level": "Information",
  "message": "The time now is 2015-04-16T12:35:36.0900887+02:00",
  "template": "The time now is {TimeNow}",
  "myprop1": "....",
  "myprop2": "....",
  "myprop3": "...."
}
```

If there is not a way, could you point me the way if I can write some plugin to do it.

thanks!!

**Comment by nblumhardt** [comment]
Hi Matias,

The MongoDB sink is hard-coded to use a `MongoDBJsonFormatter` in:

https://github.com/serilog/serilog-sinks-mongodb/blob/dev/src/Serilog.Sinks.MongoDB/Sinks/MongoDB/MongoDBSink.cs#L139

But, many other sinks now have a configuration overload accepting an `ITextFormatter` that could be substituted here instead to customize the JSON. See: https://github.com/serilog/serilog-sinks-file#json-formatting

An API fitting the pattern like:

```csharp
    .WriteTo.MongoDB(new CamelCaseJsonFormatter(), ...)
```

would be great, if you are interested in adding that capability to the MongoDB sink via a PR?

Cheers!
Nick

**Comment by mribichich** [comment]
I'll try to take a look at it!
thanks for the response.

**Comment by emirhosseini** [comment]
Did this ever go anywhere?
