### ISSUE TITLE
New sink: Logmatic.io (transfer the repository)

### ISSUE THREAD

**Issue by gpolaert** [serilog/serilog#846]
Hello again,

If think it's better if the Logmatic sink is a part of serilog. So, I can transfer the repository to Serilog account if you are OK.

Please feel free to send any feedback about what have been done.
If you don't want to be the its owner, let me know. I should migrate it to the Logmatic repository anyway.

By the way, the current version: 
* https://github.com/gpolaert/serilog-sinks-logmatic
* https://www.nuget.org/packages/Serilog.Sinks.Logmatic/

Thanks :)

**Comment by nblumhardt** [comment]
Howdy! We're no longer fast-tracking sinks into the Serilog organisation except on very rare occasions. The overhead for the Serilog maintainers - keeping up with how to use/test/support/fix each sink is pretty high, so instead we've started listing third-party projects on our "Provided Sinks" wiki page by default.

Transferring it to the Logmatic organisation and maintaining it there, at least until it's matured to some extent, is the best option right now. We're happy to help with any issues that come up, if you need to loop us in. Sound like a plan?

Cheers,
Nick

**Comment by gpolaert** [comment]
Ok sure,

So, I've transferred the repository to logmatic/serilog-sinks-logmatic. 
Could you update the wiki links?  

This week, I will write a draft about developing a plugin.

**Comment by nblumhardt** [comment]
Great, thanks Guillaume. I've updated the link in the wiki. Cheers!
