### ISSUE TITLE
How to use serilog with EF Core 1.0

### ISSUE THREAD

**Issue by SharpNoiZy** [serilog/serilog#847]
The title says it all.

I want to log all sqls and so on, EF offers a interface for that "options.UseLoggerFactory()" but I don't know how to use it with serilog.

Kind regards

**Comment by nblumhardt** [comment]
Hello,

You'll need to plug in https://github.com/serilog/serilog-extensions-logging - this sets up the _Microsoft.Extensions.Logging_ subsystem that EF Core uses.

Regards,
Nick
