### ISSUE TITLE
[Question] Why doesn't Serilog record line number and other [CallerInfo] ?

### ISSUE THREAD

**Issue by OzieGamma** [serilog/serilog#848]

**Comment by nblumhardt** [comment]
Howdy! It's expensive to do this at runtime, and at compile time `[CallerLineNumber]` and friends, by virtue of being optional parameters, can't be used alongside `params` (which the Serilog API makes use of).

Some options have been considered in the past, e.g.:

```csharp
Log.Here().Information("Hello!");
//       ^
//       |--- defaulted args
//
// or:

Log.Information(Log.Location(), "Hello!");
//                           ^
//                           |--- defaulted args
```

But, as in the above, they all have some additional syntactic weight and/or runtime cost.

Open to ideas, but as this has been covered (#258, #85 and others) I'll close this one for now. Cheers!
