### ISSUE TITLE
Where is the best place to insert a middleware that adds users username to Seilog?

### ISSUE THREAD

**Issue by gdoron** [serilog/serilog#849]
Hi,

I wrote a simple middleware that adds a username property to Serilog in ASP.NET core.

	public static class LoggerEnricher
    {
        public static IDisposable AddIdentityContext(string username)
        {
            return LogContext.PushProperty("username", username);
        }

        public static void EnrichLogger(this IApplicationBuilder app)
        {
            app.UseMiddleware<EnrichSerilogContextMiddleware>();
        }
    }
    
        public class EnrichSerilogContextMiddleware
    {
        private readonly RequestDelegate _next;

        public EnrichSerilogContextMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext httpContext, ApplicationDbContext context)
        {
            var username = httpContext.User.FindFirst(ClaimTypes.Email)?.Value;
            IDisposable property = null;
            if (username != null)
            {
                property = LoggerEnricher.AddIdentityContext(username);
            }
            using (property)
            {
                await _next(httpContext);
            }
        }
    }

Question is, where is it the best place in the Startup class to add that middleware component?

I added it here:

    app.UseIdentity();
    app.UseCookieAuthentication();
    app.EnrichLogger();
    app.UseMvc(routes => ...)

But there're many entries in the log without the property, for example:

![image](https://cloud.githubusercontent.com/assets/6141009/18257611/3fc520dc-73cf-11e6-8a7c-8094103e012a.png)

**Comment by nblumhardt** [comment]
Hi Doron,

I think you will get better results using `LogContext`:

```csharp
    public async Task Invoke(HttpContext httpContext, ApplicationDbContext context)
    {
        var username = httpContext.User.FindFirst(ClaimTypes.Email)?.Value;
        IDisposable property = null;
        if (username != null)
        {
            property = LogContext.PushProperty("username", username);
        }
        using (property)
        {
            await _next(httpContext);
        }
    }
```

(Assuming you apply `Enrich.FromLogContext()` to the configuration.)

Is this the kind of approach you're looking for?

Regards,
Nick

**Comment by gdoron** [comment]
@nblumhardt 
Hi Nick,

I'm not seeing any difference from the code I currently have except that you inlined `AddIdentityContext`.

Did I missed something? If not, why should it change the results?

Thanks,
Doron

**Comment by nblumhardt** [comment]
Ah, sorry Doron, my mistake; skim reading error :-)

Hmm, is it possible the middleware's not being inserted early enough into the pipeline?

Regards,
Nick

**Comment by gdoron** [comment]
That's my question exactly... :) Where do I need to insert it?
Since if I insert it before identity I can't get the username.

I'll ask it on the asp.net repository and will let you know what they say.

Sorry for bothering you!

Best,
Doron

**Comment by justinhelgerson** [comment]
@gdoron For the benefit of other Internet travelers, can you share how you resolved this?

**Comment by gdoron** [comment]
@justinhelgerson
Hi,
I no longer work there for over a year but if I'm not mistaken I didn't.
I did have the request id in all the logs so once I found the relevant request id from searching the user I filtered for the requestid.

I hope it helps 🤔
