### ISSUE TITLE
Serilog.Sinks.MongoDB .NET Core

### ISSUE THREAD

**Issue by MatthiasJost** [serilog/serilog#850]
Support for MongoDB Sink in Serilog for .NET Core.

This MongoDB driver ' "MongoDB.Driver":  "2.3.0-rc1"' Supports .NET Core.

`"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0"
    },`

VS2015 Error message when trying to use the latest sink version I saw:

Error

NU1002

The dependency Serilog.Sinks.MongoDB 3.0.0-dev-00030 

does not support framework 

.NETCoreApp,Version=v1.0.

**Comment by nblumhardt** [comment]
Thanks Matthias. It doesn't look like anyone has PR'd the .NET Core support yet: https://github.com/serilog/serilog-sinks-mongodb/blob/dev/src/Serilog.Sinks.MongoDB/project.json

If it's something you're interested in tackling, help would be welcome. Cheers!

**Comment by MatthiasJost** [comment]
What would need to be done? I assume referencing the new library, then checking if anything else needs to be adapted?  The code looks very small, so I assume this should not be hard to do. Can it be done with VS 2015 and then compiled. How exactly then to build and reference this build (nuget?).

**Comment by nblumhardt** [comment]
Hey - yes, it should be pretty straightforward. The need to test against a MongoDB instance (I don't run one) is the main stumbling block.

There's an included Build.ps1 script - `powershell ./Build` does all of the building/packaging, with the NUPKG going to `/artifacts`.

VS2015 needs the .NET Core tools installed for this to work - the build script doesn't, but your experience will be markedly better in VS :-)

Cheers!

**Comment by nblumhardt** [comment]
This has shipped.
