### ISSUE TITLE
Rolling Log not created

### ISSUE THREAD

**Issue by jlcarpenter** [serilog/serilog#854]
I am trying to create a Serilog with a Rolling File Sink.  When I go through everything seems to work but no file is created.  When I look at the sink in the debugger it shows the _currentFile = null.  I am using ILogger to log the information.

            
            var loggerConfig = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.RollingFile(retainedFileCountLimit: 7, pathFormat: "SendGridEvents.txt")
                .CreateLogger();

            loggerFactory.AddSerilog(loggerConfig);

Am I missing something with the creation of the log.

**Comment by nblumhardt** [comment]
Hi @jlcarpenter, how did you go? Can you please share the solution in case anyone else comes across this ticket? Thanks! :-)

**Comment by jlcarpenter** [comment]
I think I had a conflict between nuget packages.  I had a beta version of the Seq Sink and the most current version of the Rolling File Sink.  When I removed the Seq Sink it began working.  I was able to add the current version of the Seq Sink and everything is fine.

**Comment by nblumhardt** [comment]
Thanks for the info, much appreciated :+1:
