### ISSUE TITLE
Custom rendering of Enums

### ISSUE THREAD

**Issue by optical** [serilog/serilog#855]
Hi,

I am attempting to change they way an Enum is displayed in my logs using a custom formatter, however I am not having much luck with it. The enum I am trying to render differently is not a type I have control of. You can see my attempt here: [gist](https://gist.github.com/optical/8d7e74780bc6c75b68beb42e45a2a673)

I've followed the principles of implementing IFormatProvider, ICustomerFormatter as I think they should be, but it appears Serilog doesn't attempt to use the FormatProvider for formatting enums.

I believe this comes down to the fact that Serilog only uses the format provider when rendering Scalars, if the underlying type implements IFormattable. [Ref](https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/ScalarValue.cs#L74)

Is what I am trying to do possible?

**Comment by nblumhardt** [comment]
Thanks Jared. I've just opened PR #856 with what I think should be the solution, including a test for your repro. If you have a chance to sanity check it, any help would be appreciated.

**Comment by optical** [comment]
I've just taken a look over the PR and it looks good to me. 
Appreciate the fast response!

**Comment by nblumhardt** [comment]
Thanks - `-dev-nnnnn` package should be out on NuGet shortly, let us know how it goes! :-)
