### ISSUE TITLE
sink.email not compatible with asp.net core

### ISSUE THREAD

**Issue by arielcloud** [serilog/serilog#859]
> error: Package Serilog.Sinks.Email 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Serilog.Sinks.Email 2.0.0 supports: net45 (.NETFramework,Version=v4.5)

any ETA exist for this? thanks!

**Comment by goenning** [comment]
SmtpClient is not yet supported as you can see here dotnet/corefx#1006, I suppose this is what's holding the port to core

**Comment by adamchester** [comment]
@arielcloud it hasn't been merged yet, but it would help if you could give this a try if you're keen https://github.com/serilog/serilog-sinks-email/pull/19

https://ci.appveyor.com/project/serilog/serilog-sinks-email/build/43/artifacts

**Comment by arielcloud** [comment]
Why they didn't merge it yet? 2 months ago..

**Comment by nblumhardt** [comment]
Dev package published! https://www.nuget.org/packages/Serilog.Sinks.Email/2.1.0-dev-00046 :-)
