### ISSUE TITLE
Alternate rolling file sinks links to differing nuget package than to github

### ISSUE THREAD

**Issue by optical** [serilog/serilog#860]
It looks like the link on the wiki for the Alternate Rolling File sink links to an outdated nuget package. It currently links to https://www.nuget.org/packages/Serilog.Sinks.RollingFileAlternate.MultiPlatform
but it seems like it should probably link to https://www.nuget.org/packages/Serilog.Sinks.RollingFileAlternate/

The MultiPlatform package doesn't appear to support the latest serilog either. Is there any reason it links to this version over the other?

**Comment by nblumhardt** [comment]
I am not sure, can't recall why this would be the case. @merbla might have some recollection?

I've switched the link to the more recent/original package as suggested. Thanks!
