### ISSUE TITLE
Override Exception.ToString() when logging exceptions

### ISSUE THREAD

**Issue by camp-007** [serilog/serilog#862]
My application makes heavy use of async/await methods. When unhandled exceptions occur the stack traces are very hard to read. There is a nuget package that cleans up async stack traces (https://github.com/aelij/AsyncFriendlyStackTrace). This creates an extension method to give you access to a modified/clean stack trace:

    ex.ToAsyncString()

I'd like to be able to use this library to intercept the stack trace before it is written to the log sink (in my case Seq) and instead log the clean/modified stack trace.

When logging exceptions I'm using something like:

    log.Error(ex, "Operation Failed");

Is there a way with Serilog/Seq to control the exact output of the error string that is sent to the log sink?

**Comment by joelweiss** [comment]
Check out issues #521 and #702

**Comment by camp-007** [comment]
Yes, exactly!  I posted some feedback to #521 and I'll follow that from here out.  Thanks!
