### ISSUE TITLE
Visual Studio 2013 Update 5 + New VB .NET Project - Nuget install fails

### ISSUE THREAD

**Issue by xantari** [serilog/serilog#863]
Issue:

Using Visual Studio 2013 Update 5, with latest Nuget release fails when installing Serilog to a brand new VB .NET Console Project.

Error: Serilog already has a dependency defined for Microsoft.CSharp

**Comment by nblumhardt** [comment]
Hi there - you need to install the latest NuGet tools for VS from: https://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca

Cheers,
Nick

**Comment by xantari** [comment]
Wierd, I had installed the update, but I'm guessing my Update 5 patch right after the nuget update may have undone my nuget update.

Thanks!

**Comment by siemandelc** [comment]
Serilog 2.2.1 package isn't being restored when triggered by my CI build but if I pull the contents out of TFS and manually build on the same machine it's being restored. Any possible solutions?
