### ISSUE TITLE
Add example to use IoC container Spring.NET with serilog logger into docs

### ISSUE THREAD

**Issue by Frank591** [serilog/serilog#867]
**Steps:**
https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers 
Section "Using an IoC container"

**Current:**
Examples for using IoC container Spring.net(http://www.springframework.net/doc-latest/reference/html/objects.html) not exists.

**Expected:**
Add examples

**Comment by nblumhardt** [comment]
Hi Frank, thanks for the note. Do you have an example we can link to? In theory we could add all ~10 currently-used IoC containers here, but I think just linking to concrete examples will keep things more streamlined.
