### ISSUE TITLE
Update Using Serilog:AppSettings

### ISSUE THREAD

**Issue by DinoSources** [serilog/serilog#868]
Hey there, the [page in question](https://github.com/serilog/serilog/wiki/AppSettings#adding-a-sink).

You just need to add the line below this to the section I linked (the second In XML: describing how to set a pathFormat).
`<add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />`

**Comment by nblumhardt** [comment]
Fixed, thanks!
