### ISSUE TITLE
Rolling file sink - roll on file size and date

### ISSUE THREAD

**Issue by akshetty9** [serilog/serilog#869]
Rolling file sink creates one file per day, and allows logging in Json format. If i need to roll based on file size and date, it is recommended to use Rolling File alternate, or [Sinks-Rolling file](https://github.com/BedeGaming/sinks-rollingfile). But this does not have option to log in Json format. Is there a reason for not adding file size based option in Rolling File sink and recommending a separate sink? Is there any plan to add Json support? Thank you.

**Comment by nblumhardt** [comment]
Hi, thanks for getting in touch.

The built-in rolling file sink is slowly being extended to cover more cases - this one is certainly on the radar.

To use JSON formatting with the "alternate" rolling file sink that supports roll-on-size, you can use:

```csharp
    .WriteTo.Sink(new  AlternateRollingFileSink(logDirectory, new JsonFormatter(), fileSizeLimitBytes))
```

**Comment by akshetty9** [comment]
Thanks for the update. I do not see any new commits happening on AlternateRollingFileSink since long time. It does not have option to specify file retention. It would be nice to have these useful features on one Sink than having multiple sinks,

**Comment by nblumhardt** [comment]
Thanks for the follow-up. There's quite a bit of functionality we'd eventually like to cover in the rolling file sink, but haven't been able to move forward yet. I'll close this for now as I don't think it will be actioned directly here.
