### ISSUE TITLE
Help with configuring Serilog to log the important data on ASP.NET Core

### ISSUE THREAD

**Issue by gdoron** [serilog/serilog#875]
Hi Nick and all,

I'm using Serilog (and Seq) on ASP.NET Core for several months now, and in general it works very well in tandem, but the problem is, many times important details on the request is missing.
e.g. request headers (mainly the referrer header), request body etc.

In general, I would want to log as much as possible data about the request if it ended up with an exception - HTTP 5xx/ HTTP 4xx (currently I can see 404 in the log, but since I don't have the headers, I don't know where the bad link came from, so I many times need to guess).

Is this even someway possible?

My current setup is:

    var configurations = new LoggerConfiguration()
        .MinimumLevel.Information()
        .Filter.ByIncludingOnly(x => ((ScalarValue) x.Properties["SourceContext"]).Value.ToString().StartsWith("\"Microsoft")
            ? x.Level > LogEventLevel.Information
            : x.Level > LogEventLevel.Verbose)
        .WriteTo.Seq(seqAddress, apiKey: "abcdefghijklmnopqrstwyz") //I hope I know the ABC right ;)
        .Enrich.FromLogContext();

    if (!env.IsProduction())
    {
        configurations.Enrich.WithProperty("Environment", env.EnvironmentName);
    }

    Log.Logger = configurations.CreateLogger();

Can someone share their setup or suggest improvements?

Thanks a lot,
Doron

**Comment by nblumhardt** [comment]
Hi Doron,

One small improvement, you can now add`MinimumLevel.Override()` to achieve what your filter is doing, but more efficiently:

```csharp
var configurations = new LoggerConfiguration()
    .MinimumLevel.Verbose() // For example
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
```

To add more details you can use middleware to either enrich events, or log each request with additional information.

To do either you'll need some middleware (`app.UseMiddleware<RequestLogger>()`), and:

```csharp
public class RequestLogger
{
    readonly RequestDelegate _next;

    public RequestLogger(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        // E.g.:
        Log.Information("Received headers {@Headers}", context.Request.Headers);
        await _next.Invoke(context);
    }
}
```

Or to add properties:

```csharp
public class RequestLogger
{
    readonly RequestDelegate _next;

    public RequestLogger(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        using (LogContext.PushProperty("Headers", context.Request.Headers, destructureObjects: true))
        {
            await _next.Invoke(context);
        }
    }
}
```

Using the latter approach can add a lot of weight to events, so I'd tend towards logging out just the one event if that suits what you're trying to achieve.

(The logging you get out of the box is from ASP.NET, so raising an issue in one of the ASP.NET projects about the missing information may achieve a better long-term outcome.)

Hope this helps!

**Comment by gdoron** [comment]
Sure helped, though couple of things:

1. Getting the headers needs to be fixed.
2. It doesn't log the body.
3. It sends the event even if the request succeeded. I would rather not send the log only if there was a problem with the request. 

Is it possible for example to postpone all the logs until the request is done, and then decide which log messages will hit the server, based on response status code and message level for example?
This sounds like the best feature ever, sorry, EVER! 😄 

My take (that helps with **1** and **2**):

    public async Task Invoke(HttpContext context)
    {
        Log.Information("Received headers {@Headers} {@Body}", context.Request.Headers.Select(x => $"{x.Key}:{x.Value.ToString()}"),
            context.Request.ContentLength > 0
                ? context.Request.Form.Select(x => $"{x.Key}:{x.Value.ToString()}")
                : null);
        await _next.Invoke(context);
    }
Is **3** somehow possible?

**Comment by nblumhardt** [comment]
Great - RE 1 and 2, glad you were able to sort it out, I only meant the code above as an example :-)

The buffering feature truly is an awesome idea. Getting it "in the box" has been elusive because there are quite a few design decisions implicit in it, but @timgaunt has cranked out one implementation:

https://github.com/timgaunt/serilog-sinks-buffered

Not sure how closely it matches your scenario, it'd be cool to hear how you go with it, if you give it a try.

Cheers!

**Comment by timgaunt** [comment]
Thanks for the shout @nblumhardt, it's made a huge difference to the noise that gets sent over to the server. 

We've got two implementations, one that allows you to define the end of the request i.e. for Winform type applications and an extension which is uses the HttpRequest to end.

Happy to talk through how to implement it/how it works if you're interested @gdoron

**Comment by gdoron** [comment]
Thanks Nick and Tim.
I read the code a bit in the repository, looks very nice and pretty much exactly what I was looking for, maybe just small adjustments.

Two quick questions @timgaunt :

1. The code doesn't seem to be compatible with .NET Core or even ASP.NET Core, right?
2. If it does, is there a nuget/myget package or do I need to clone the repo? 

[`static readonly string RequestIdItemName = typeof(HttpRequestIdEnricher).Name + "+RequestId";`](https://github.com/timgaunt/serilog-sinks-buffered/blob/9ddfc3784af8d295b9b25dd89e3d966a46f89f26/src/SerilogSinksBuffered.Web/RequestId.cs#L9) looks a bit awkward to me BTW.

Overall, looks awesome, and I'll be glad to help improving it even more so it'll be made public and more robust if needed.

Thanks,
Doron

**Comment by timgaunt** [comment]
@gdoron it doesn't support .Net Core yet I don't think (it wasn't really around when we started) but I wouldn't have thought it would take a lot to change.

Yes there's a nuget package of both: https://www.nuget.org/packages/Serilog.Sinks.Buffered/ and https://www.nuget.org/packages/Serilog.Sinks.Buffered.Web/

I can't recall why we wrote the `RequestIdItemName` like that but there was a reason :)

More than happy for you or someone else to pick it up and have a play.

**Comment by gdoron** [comment]
Seems like the only significant but not too big part that needs to be changed for core is 
[`PerRequestLoggingModule`](https://github.com/timgaunt/serilog-sinks-buffered/blob/9ddfc3784af8d295b9b25dd89e3d966a46f89f26/src/SerilogSinksBuffered.Web/PerRequestLoggingModule.cs)

I don't know enough about serilog, so I'm quite stuck on how to wire it up in a Serilog way, @nblumhardt any tip?

Also, what's all those Nested scope classes @timgaunt ?

Thanks.

**Comment by nblumhardt** [comment]
Hi @gdoron - how did you go with this? I can't offer much more info at the moment, but let us know if you have hit any stumbling blocks. Otherwise closing. Cheers!

**Comment by gdoron** [comment]
@nblumhardt As I wrote earlier, I'm not familiar with Serilog _plumbing_ nor fully understand Tim's code so I can't port @timgaunt work to Core by my own 😢 .
So I dropped it for now, but we will probably need to revisit it soon, since we get more and more traffic on https://yooocan.com every day, and we don't want it to explode one day because of this.

Doron

**Comment by olsh** [comment]
Sorry for this thread resurrection.
Is it possible to push objects by reference using the `LogContext.PushProperty`?
I have the same problem as OP and I'd like to store HttpContext without destructuring(because it seems very expensive operation for each request) to use it later in a custom sink.
The sink will use the context to extract body, IPrincipal etc. only for `Error` level.

Thanks!

**Comment by olsh** [comment]
I ended up with the approach https://github.com/serilog/serilog/issues/875#issuecomment-252169224
and custom destruction property for `HttpContext`, not sure if this an optimal solution though.
```
    public class ReferenceDestructingPolicy : IDestructuringPolicy
    {
        /// <inheritdoc />
        public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory,
            out LogEventPropertyValue result)
        {
            if (value is HttpContext)
            {
                result = new ScalarValue(value);

                return true;
            }

            result = null;

            return false;
        }
    }
```

Guys, please, advise if there is more efficient and simple solution.
Thanks!

**Comment by cgountanis** [comment]
I would love a way to simply add the host/ipaddress into the logs of my Core 2.0 MVC application without coding a bunch of overhead.

**Comment by nblumhardt** [comment]
@cgountanis Hi Chris - some code will always be needed to tack this info onto events, but it shouldn't be a huge amount. Check out the example at https://blog.getseq.net/smart-logging-middleware-for-asp-net-core/ - the code there adds headers, host and protocol, but it's designed to be easy to modify to add IP address etc.

Since this issue is closed and has diverged from the original discussion, please let us know via a fresh issue if you have trouble getting this working. Cheers!
