### ISSUE TITLE
New Sink to Google PubSub: Transfer to the Serilog organisation.

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog#876]
Hi.

We have just finished a development to create a new Sink to send data to the Google PubSub and I would like to know which steps we have to follow to transfer it to the Serilog organisation.

The Sink link is: https://github.com/XML-Travelgate/serilog-sinks-googlecloudpubsub

One doubt: once transfered, if there is any PR ¿Will we have the controll over it or it will be the community/organisation?

Thanks.
Jose

**Comment by nblumhardt** [comment]
Hi Jose, thanks for the link! I have added the sink to [the list](https://github.com/serilog/serilog/wiki/Provided-Sinks).

We're no longer accepting new sinks into the Serilog organisation except on rare cases where we've possibly missed some fundamental output. Given the enormous variety of outputs it's very hard for the organisation to carry everything forward - testing/maintenance requires systems to be set up, accounts, background knowledge and so-on. Our hope is that it's easier to "concentrate" these things in independent community projects.

If any issues come up, feel free to raise tickets here/loop everyone in for help of course!

Cheers,
Nick

**Comment by jose3m** [comment]
Thank you very much Nick for the info.

I want againt to thank you and all the Serilog team for your great work.

Best regards.
Jose
