### ISSUE TITLE
Find and follow up test coverage opportunities

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#878]
Thanks to @304NotModified, we now get test coverage reports out of each build through codecov.io.

Here's the current dev branch coverage: https://codecov.io/gh/serilog/serilog/tree/dev/src/Serilog

At first glance there's a lot that isn't covered by our tests, but digging deeper a lot of what isn't covered appears to be pretty trivial.

This ticket is really looking for someone to own the task of going through the coverage report and finding opportunities to meaningfully improve test coverage with some additional tests. Any takers?

**Comment by clarkis117** [comment]
It looks like the class `Core.Logger` (in logger.cs) has many methods that use one of the `Core.Logger.Write...` methods which aren't covered.

**Comment by nblumhardt** [comment]
@clarkis117 yes, I think that's a large part of it.

I was tempted to ignore these, but then realized it's a great opportunity to apply a reflection-driven "convention test"; i.e.:

 * loop over all of the logging levels from `Verbose` to `Fatal`
 * for each method
  - use reflection to find each expected variant
  - call the method through reflection and verify the result

The actual test would end up being quite terse I think - and we'd then catch any anomalies like missing overloads.

We could even go a step further here and validate parameter names and so-on.

What do you think - does this sound sane? :-)

**Comment by clarkis117** [comment]
Considering that there’s 60 methods in question, it does sound sane. I was thinking about having a unit test for each log level group. Then, there would be a function to test for each signature in the convention listed below. Each method would be evaluated to see if it matches one of the signatures listed below. If the method does not match one of the signatures the test would fail. Upon matching a signature, the method would be invoked with some arbitrary arguments.

Each method should also be evaluated that it’s public, returns void, and has the `MessageTemplateFormatMethod` Attribute.

To clarify the convention that needs to be validated is (for each log level):
```
Method0 (string messageTemplate) : void
Method1<T> (string messageTemplate, T propertyValue) : void
Method2<T0, T1> (string messageTemplate, T0 propertyValue0, T1 propertyValue1) : void
Method3<T0, T1, T2> (string messageTemplate, T0 propertyValue0, T1 propertyValue1, T2 propertyValue2) : void
Method4 (string messageTemplate, params object[] propertyValues) : void
Method5 (Exception exception, string messageTemplate) : void
Method6<T> (Exception exception, string messageTemplate, T propertyValue) : void
Method7<T0, T1> (Exception exception, string messageTemplate, T0 propertyValue0, T1 propertyValue1) : void
Method8<T0, T1, T2> (Exception exception, string messageTemplate, T0 propertyValue0, T1 propertyValue1, T2 propertyValue2) : void
Method9 (Exception exception, string messageTemplate, params object[] propertyValues) : void
```

**Comment by nblumhardt** [comment]
Looks good. Whoah, what an overload list! :-)

**Comment by clarkis117** [comment]
From #896, the same or similar convention based tests could also be applied to the static class Serilog.Log.
https://codecov.io/gh/serilog/serilog/src/dev/src/Serilog/Log.cs

**Comment by clarkis117** [comment]
It also looks like that support for Serilog.Core.Pipeline.SilentLogger can be added to method overload convention tests.
See: https://codecov.io/gh/serilog/serilog/src/f3c0925a614d25b3850cd4bcf2b75e33fc3b1f14/src/Serilog/Core/Pipeline/SilentLogger.cs

**Comment by nblumhardt** [comment]
Closing this umbrella issue; still plenty of opportunities in there I think, but we might do better by raising specific issues for any weaker areas.
