### ISSUE TITLE
Missing bracket after json gets passed to template

### ISSUE THREAD

**Issue by wendilimMS** [serilog/serilog#884]
Hi, I've been directed here by my [ issue ](https://github.com/aspnet/Logging/issues/503) of a bug where my json string that gets passed into AzureDiagnostics logger drops a bracket after being parsed by the template. Apparently the template I set for the logger gets passed directly to Serilog, so I hope you can help me out.

[Link to the project ](https://github.com/wendilimMS/AzureBugRepro) that I've made to reproduce the error I'm having (I'm not directly calling Serilog). 

The template: `@"{{'timestamp': '{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}', 'level': '{Level}', 'message': '{Message}', 'exception': '{Exception}'}}{NewLine}"`

And the json that gets passed in:
```
{
    "name": "Some name",
    "valueCollection": ["7dfdc479-7b76-4a58-8c98-7d1afefa7256"],
    "objectCollection": [{
        "name": "Some other name",
        "lastModified": "2016-10-18T20:53:45.488Z"
    }],
    "lastModified": null,
    "propertyA": null,
    "propertyB": null,
    "propertyC": null,
    "option": null
}
```

The resulting logged message:
```
// the state object has a missing end brace
{
    'timestamp': '2016-10-20 20:17:16.001 +00:00',
    'level': 'Warning',
    'message': '{"eventId":1001,"eventName":"MyObjectCreated","message":"An object has been created","state":{"name":"Some name","valueCollection":["7dfdc479-7b76-4a58-8c98-7d1afefa7256"],"objectCollection":[{"name":"Some other name","lastModified":"2016-10-18T20:53:45.488Z"}],"lastModified":null,"propertyA":null,"propertyB":null,"propertyC":null,"option":null}',
    'exception': ''
}
```

**Comment by nblumhardt** [comment]
Hi - thanks for getting in touch. I don't have any familiarity with the Azure code you're calling; would you be able to create a reproduction that's based on Serilog only?

Just a note, if you want to create valid JSON with Serilog, message templates/output templates and so-on are going to make that very difficult. If you have access to the Serilog API, a custom formatter of some kind is the way to go (e.g. a derivative of something like: https://github.com/serilog/serilog-formatting-compact).

Regards,
Nick
