### ISSUE TITLE
NaN and PositiveInfinity/NegativeInfinity formatted as invalid JSON

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#885]
The "special" floating point values need to be converted into strings (or some other valid JSON representation) when formatted by `JsonValueFormatter`. See: https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Json/JsonValueFormatter.cs#L185

**Comment by clarkis117** [comment]
@nblumhardt  From my understanding of the issue they need to be formatted as valid JSON, which in this case could just be strings. Therefore, a conditional statement like this should work:

	if ((value is double && (double.IsNaN((double)value) || double.IsInfinity((double)value)))
		|| (value is float && (float.IsNaN((float)value) || float.IsInfinity((float)value))))
	{
		FormatStringValue(value.ToString(), output);
		return;
	}

**Comment by clarkis117** [comment]
PR: https://github.com/serilog/serilog/pull/887
