### ISSUE TITLE
Add string overload of Log.ForContext<T>() : Log.ForContext(string)

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#886]
In some cases, we cannot pass a type as a type-parameter to `Log.ForContext<T>()` / `ILogger.ForContext<T>()` , for instance : 
- if the class is marked as `static` (static classes cannot be used as type arguments)
- if we actually want to log "as if we were another class" but do not want to introduce a reference to the other class' containing assembly

The workaround is to use : 

```
Log.ForContext("SourceContext", "TheNameOfMyClass");
```

But this `"SourceContext"` has the disavantages of _magic strings_: 
- not very Refactor-friendly
- someone unfamiliar with Serilog could wonder what this string means, and maybe change it ... with consequences in the generated events

It would be nice if we could get rid of this magic string alltogether, for instance by : 
- introducing a constant (or maybe a `public static string`) containing that string
- or event better, introduce overloads that would behave similarly as `Log.ForContext<T>()` , but with an arbitrary class name

If possible, using the same method name would be better ... but maybe not explicit enough ... in which case another method name should be found ... for instance : `Log.ForSourceContext("FooBarClassName")`

**Comment by tsimbalar** [comment]
> introducing a constant (or maybe a shared static string) containing that string

My bad, such a constant exists already !
`Serilog.Core.Constants.SourceContextPropertyName`
 at https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Constants.cs#L27

still, a specific Method would be nicer.

**Comment by tsimbalar** [comment]
This is similar to #29 , but different because requesting an overload with a `string` argument.

**Comment by khellang** [comment]
Can't you use `Log.ForContext(Type)`? https://github.com/serilog/serilog/blob/dev/src/Serilog/Log.cs#L115-L118

**Comment by khellang** [comment]
Oh, I see what you're asking here. You don't have a reference to the class, so you can't use the type itself.

It's easy to write your own extension method though:

```csharp
public static ILogger ForContext(this ILogger logger, string context)
{
    return logger.ForContext(Constants.SourceContextPropertyName, context);
}
```

**Comment by tsimbalar** [comment]
> Can't you use `Log.ForContext(Type)` or `ILogger.ForContext(Type)` ?

yes, that one is actually fine for `static class`es , I just discovered that overload !

It is indeed easy to add an extension method for `Logger`, but not possible for the static class `Log` , that still won't give us `Log.ForContext(string)`.

Having an overload with only a single string would also bring the API closer to other logging libraries (like NLog), that have a `LogManager.GetLogger("Example")` and accept an arbitrary string (in addition to `LogManager.GetCurrentClassLogger(Type loggerType)`).

Anyway, the `Log.ForContext(Type)` covers most of the problematic cases (static classes like `WebApiConfig` , `BundleConfig` that are there by default in ASP.NET MVC 5 projects), and extension method or direct use of the constant `Constants.SourceContextPropertyName` are good enough workarounds.

I still think that for symmetry an overload accepting a single `string` would be nice, but it is indeed not essential. 

Feel free to close this issue if you think that would not be a good addition to the library :)

**Comment by tsimbalar** [comment]
>The title "Add non-generic version of `Log.ForContext<T>()`" put me off a bit. I thought you were asking for `ForContext(Type)`.

I've renamed the issue to make it clearer

**Comment by tbrettallen** [comment]
I'm curious what scenario you're running into that requires this?

I'm using the following code for most of my classes

`        /// <summary>
        /// Gets a logger for the current class. Ensure this is set to a static field on the class.
        /// </summary>
        /// <returns>An instance of <see cref="T:Serilog.ILogger" /></returns>
        [MethodImpl(MethodImplOptions.NoInlining)]
        public static ILogger GetCurrentClassLogger()
        {
            if (!Initialized)
            {
                // Don't lock thread unless we've confirmed we're not initialized first.
                lock (SyncLock)
                    if (!Initialized)
                    {
                        Configuration.Initialize();
                        Initialized = true;
                    }
            }

            return Log.ForContext(new StackFrame(1, false).GetMethod().DeclaringType);
        }`

Coupled with

`    public class MyClass
    {
        private static readonly ILogger Log = LogManager.GetCurrentClassLogger();
    }`

And then for my Controllers, I use a base controller and an action filter

`        public override void OnActionExecuting(HttpActionContext actionContext)
        {
            var controller = actionContext.ControllerContext.Controller as BaseApiController;

            if (controller == null)
            {
                base.OnActionExecuting(actionContext);
                return;
            }

            controller.Log = Log.ForContext(actionContext.ActionDescriptor.ControllerDescriptor.ControllerType);
            controller.Log.Debug("Executing Action {Controller}Controller.{Action}({Arguments})", 
                actionContext.ControllerContext.ControllerDescriptor.ControllerName,
                actionContext.ActionDescriptor.ActionName,
                actionContext.ActionArguments);

            base.OnActionExecuting(actionContext);
        }`

**Comment by nblumhardt** [comment]
@tbrettallen I think the method you're using on the static `Log` class is not also mirrored on the `ILogger` interface (hence this issue).

@tsimbalar @serilog/reviewers-core I don't think we'd introduce a breaking change to `ILogger` right now by adding this, and I'm hesitant to start padding out `ILogger` with extension methods (a lone extension method would seem a bit inconsistent/out of place).

 Do we close this and just live with the less comfortable `Constants.SourceContext` method?

**Comment by SimonCropp** [comment]
I think close and live with it is valid in this case

**Comment by nblumhardt** [comment]
Closing, but if there are contrary opinions please feel free to jump back in :-)

**Comment by stephenpatten** [comment]
OK, after reading this a few times I wanted to ask this: Is it possible to have a static logger declared in an abstract class and have classes inherit from said class and the context would reflect the derived class?
