### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by FantasticFiasco** [serilog/serilog#889]
[Serilog.Sinks.UDP](https://github.com/FantasticFiasco/serilog-sinks-udp)

I have developed a Serilog sink that sends UDP packages over the network.

I find myself using it together with [Log2Console](https://log2console.codeplex.com/), where one can send logs to oneself on localhost, or if the team agrees, can send it to a multicast group, thus making it easy to set up an environment where all developers and testers share the same logs.

Would you consider receiving ownership of this repository?

**Comment by merbla** [comment]
Hi @FantasticFiasco,

Thanks for the note, we can add it to the list of provided sinks in the [wiki](https://github.com/serilog/serilog/wiki/Provided-Sinks). Currently we are not accepting new sinks into the organisation unless there is a strong case for it. 

As a team we find it difficult to keep across all the technologies, platforms and frameworks in relation to the testing, issues and ongoing releases of the many Serilog sinks. (Over 80 on NuGet)  If the usage grows and the sink is widely adopted we can revisit moving it under the Serilog organisation.

However please feel free to tag issues or let us know if you have problems.  Once again that for letting us know about the sink.

**Comment by FantasticFiasco** [comment]
I truly do understand the effort it takes for you guys to maintain the amount of sinks you already own, and for that you have earned my respect.

Keep up the good work with Serilog, and I'll allocate effort into keeping my sink up date.

Thanks for updating the wiki, I'm glad to be a part of the family!
