### ISSUE TITLE
Level formatting does not use format provider

### ISSUE THREAD

**Issue by optical** [serilog/serilog#890]
This issue is almost identical to #855

If you provide an IFormatProvider to a sink which is capable of rendering the LogLevel property, it is not used. See https://gist.github.com/optical/77e4e53158a683d6faa91076821b4739 for an example which I would expect to work.

From what I can tell this is because LogEvents end up as LogEventLevelValue's rather than ScalarValue. It looks like there are some custom rules around format strings which this copes with, however it never utilises the supplied formatProvider.

I suspect the correct behaviour of this method should be to delegate to the formatProvider if the formatProvider is able to return a non-null, ICustomFormatter. Otherwise the method would then fallback to its existing approach. 

Thoughts?

**Comment by nblumhardt** [comment]
Yes, `Level` is treated specially so that the `:u3`, `:w4`-type format strings can be applied to it. I can't see any major problem with opening this up to custom format providers, but it's not a scenario I've encountered so far. Can you share a few details around the result you're aiming for? Thanks!

**Comment by optical** [comment]
I am currently migrating a large set of applications off of our inhouse logging framework onto Serilog. On the way to migrating fully to JSON logs, we'd like to continue writing simple logs out to the console. Our current monitoring and logging systems then parse these log lines, and they expect that the level value correspond to values which don't directly align with Serilogs log levels. For example, we render "Information" as "Info" which is the case I have run into at the moment. We may have a need to render them completely differently, such as Verbose -> "TRACE", but that probably isn't directly required.

In this case I've implemented an IFormatProvider and ICustomFormatter which will convert Serilogs log level to our old internal log level and render them as such. Perhaps there is another way I am missing?

**Comment by nblumhardt** [comment]
Thanks for the info.

Yes; although it isn't ideal you can create a custom `ITextFormatter`:

```csharp
    .WriteTo.Console(new LegacyTextFormatter())
```

And in `LegacyTextFormatter.Format()` something like:

```csharp
public void Format(LogEvent logEvent, TextWriter output)
{
    output.Write(logEvent.Timestamp.ToString("o"));
    output.Write(" ")

    var size = (LogEventLevel)arg;
    output.Write(size == LogEventLevel.Information ? "Info" : size.ToString());
    output.Write(" ")

    logEvent.MessageTemplate.Render(logEvent.Properties, output);
    output.WriteLine();

    if (logEvent.Exception != null)
        output.WriteLine(output.Exception);    
}
```

It's not ideal, but it cuts through a lot of abstraction that otherwise doesn't add much value in this scenario anyway. What do you think?

**Comment by optical** [comment]
Yep - this works for me. Happy for you to close this issue if you don't think its worth the additional complexity.

Slightly related - Would it be possible to promote the current pre-release version of the `TextWriter` sink on Nuget sometime soon? The latest stable version lacks the overload for `ITextFormatter`.

**Comment by nblumhardt** [comment]
Great - I think for now the solution above is the way to go, but I'll keep this ticket in mind in case it comes up in future.

https://github.com/serilog/serilog-sinks-textwriter/pull/4 should have TextWriter released in a few minutes 👍
