### ISSUE TITLE
Add a provided sink

### ISSUE THREAD

**Issue by pauldambra** [serilog/serilog#892]
Couldn't see how to fork and PR against the wiki

But I've written a TCP/UDP network sink based off the Splunk sink and wondered if you'd like to add it to the list of provided sinks

`|
[Network *](https://github.com/pauldambra/Serilog.Sinks.Network) | `TCP or UDP` | [Serilog.Sinks.Network](https://www.nuget.org/packages/serilog.sinks.network) <br/>  ![NuGet Version](http://img.shields.io/nuget/v/serilog.sinks.network.svg?style=flat)  | `

**Comment by nblumhardt** [comment]
Added! Thanks Paul 👍
