### ISSUE TITLE
New sink called Serilog.Sinks.Http

### ISSUE THREAD

**Issue by FantasticFiasco** [serilog/serilog#894]
I've implemented a new sink that is capable of sending HTTP POST requests over the network. It integrates well with those that would like to use [Logstash](https://www.elastic.co/products/logstash) in the ELK stack, instead of sending the events directly to Elasticsearch using [Serilog.Sinks.Elasticsearch](https://github.com/serilog/serilog-sinks-elasticsearch).

It provides an alternative to the [proposed solution on stackoverflow](http://stackoverflow.com/questions/25283749/which-serilog-sink-to-use-for-sending-to-logstash), where one has to install and configure [Filebeat](https://www.elastic.co/products/beats/filebeat) on each instance where logs are generated. One would instead add the [HTTP input plugin](https://www.elastic.co/blog/introducing-logstash-input-http-plugin) to Logstash, and post events to its endpoint.

Do you think this sink provides enough value to be listed among the available sinks on your wiki?

[GitHub](https://github.com/FantasticFiasco/serilog-sinks-http)
[NuGet](https://www.nuget.org/packages/Serilog.Sinks.Http/)

**Comment by nblumhardt** [comment]
Great! Added to the wiki - thanks.
