### ISSUE TITLE
LogContext Exception Snapshot

### ISSUE THREAD

**Issue by Jaben** [serilog/serilog#895]
Not sure if this has been suggested or discussed, but it would be great to have a way to snapshot the current log context when an exception is thrown.

I see there is an Import/Export suggestion -- so this is somewhat related. This would be an automatic snapshot if the log context disposable is called from an exception being thrown. In centralized unhandled exception logging code, it could import the most recent snapshot(s). Another added feature would be pushing a stack trace at that point, too.

Code example:

```csharp
try
{
    new OtherClass.FailMe();
}
catch(Exception ex)
{
   // add log context snapshots
   LogContext.WithSnapshots(() => Log.Logger.Error(ex, "Unhandled Exception with Snapshot"));
}
....

class OtherClass {
   public FailMe() {
      using (LogContext.PushProperty("SnapshotValue",1)) {
          // log context IDisposable could detect an exception
          // and push a snapshot (maybe limited scope so that there are not memory leaks)
          throw new Exception("I've failed. I had no choice.");
      }
   }
}
```

**Comment by skomis-mm** [comment]
@Jaben , you can achieve desired effect when logging inside exception filter:
```csharp
try
{
    new OtherClass.FailMe();
}
catch (Exception ex) when (LogError(ex)) // log context at the call site where the exception occurred will be included
{
}
....
static bool LogError(Exception ex) 
{
    Log.Logger.Error(ex, "Unhandled Exception with Snapshot");
    return false;
}
....
class OtherClass {
   public FailMe() {
      using (LogContext.PushProperty("SnapshotValue",1)) {
          // log context IDisposable could detect an exception
          // and push a snapshot (maybe limited scope so that there are not memory leaks)
          throw new Exception("I've failed. I had no choice.");
      }
   }
}
```

**Comment by Jaben** [comment]
@skomis-mm I didn't think about using exception filters like this -- great idea!

@nblumhardt I'm happy with this solution... closing this issue.

**Comment by nblumhardt** [comment]
👍 thanks @Jaben.

@skomis-mm that's a great solution, I'll try to update examples to use that approach as I find them.

BTW, `Log.Logger.Error()` == `Log.Error()`.

Cheers!

**Comment by vdex42** [comment]
The exception filter solution is genius!

However, I have come across a case where this doesn't work. When the exception is thrown from an async  method the context is lost. e.g.

```
        private async Task Invoke(string uri)
        {
            using (LogContext.PushProperty("RequestUri", uri))
            {
                try
                {
                    await Next();                 
                }
                catch (Exception ex) when(LogError(ex))
                {                    
                }
            }
        }

        private async Task Next()
        {
            using (LogContext.PushProperty("orderid", 124))
            {
                _log.Information("about to throw");
                throw new Exception("test");
            }
        }

        private static bool LogError(Exception ex)
        {
            //At this point we do not have the context of orderid
            Log.Logger.Error(ex, "Unhandled Exception with Snapshot");
            return true;
        }

```
Is there a solution for restoring the context that was created inside the async method so that the global catch would have the context of "orderId" in this example. This is so that we could have a global exception handler that would have the context of where the exception occurred

**Comment by nblumhardt** [comment]
Not a solution in itself, but `LogContext.Clone()` seems like it could play a part, here.

**Comment by optical** [comment]
I've been trying to workaround this issue with async not working with exception filters. I've come up with a bit of a hack that appears to work in simple cases. Posting the solution here more to gather feedback around the approach of using `AppDomain.FirstChanceException` to grab and attach a snapshot of LogContext's properties onto the Exception being raised. It appears to work in the simple case, but the implementation is super clunky and almost certainly flawed. 

```
public static class Program {
	public static void Main(string[] args) {
		AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;

		Log.Logger = new LoggerConfiguration()
			.WriteTo.Console(new JsonFormatter())
			.Enrich.FromLogContext()
			.Enrich.WithExceptionDetails()
			.CreateLogger();

		try {
			using (LogContext.PushProperty("MyProperty", "My value")) {
				throw new ArgumentException("??");
			}
		} catch (Exception exception) {
			Log.Error(exception, "Something terrible happened");
		}
	}

	private static void CurrentDomain_FirstChanceException(object sender, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs e) {
		var contextEnricher = LogContext.Clone();
		var logEvent = new LogEvent(DateTimeOffset.Now, LogEventLevel.Debug, null, new MessageTemplate(new List<MessageTemplateToken>()), new List<LogEventProperty>());

		contextEnricher.Enrich(logEvent, new PropertyFactory());
		foreach (var kvp in logEvent.Properties) {
			e.Exception.Data[kvp.Key] = kvp.Value.ToString();
		}
	}
}

public class PropertyFactory : ILogEventPropertyFactory {
	public LogEventProperty CreateProperty(string name, object value, bool destructureObjects = false) {
		// This is almost certainly wrong, but works for simple cases
		return new LogEventProperty(name, new ScalarValue(value));
	}
}	contextEnricher.Enrich(logEvent, new PropertyFactory());
			foreach (var kvp in logEvent.Properties) {
				e.Exception.Data[kvp.Key] = kvp.Value.ToString();
			}
		}
	}

	public class PropertyFactory : ILogEventPropertyFactory {
		public LogEventProperty CreateProperty(string name, object value, bool destructureObjects = false) {
			// This is almost certainly wrong, but works for simple cases
			return new LogEventProperty(name, new ScalarValue(value));
		}
	}
```

@nblumhardt Do you think this general idea is reasonable, or are there better ways to go about it? If its reasonable, perhaps a change to Serilogs API's might make grabbing a snapshot of the current LogContext's Properties simpler? Keen to hear anyones thoughts, as I find having LogContext's properties attached to my exception messages to be very valuable.

**Comment by nblumhardt** [comment]
@optical it's a nice hack :-)

You could simplify it a bit by just putting the result of `LogContext.Clone()` into the `Exception.Data` under a single key (`"SerilogLogContext"?) and then use a custom enricher to apply it in the logging pipeline (where there's access to the `ILogEventPropertyFactory` implementation).

Still not without challenges, but getting close to usable...

Perhaps it's a candidate to try in an out-of-band distribution (gist/add-on package, etc.) to see how it fares in the wild?

**Comment by optical** [comment]
Thanks @nblumhardt  for the feedback. I like the idea of using an Enricher to handle this.

Unfortunately we can't place the `LogContext` straight onto `Exception.Data`, as it isn't serializable, so the add operation throws an exception. We could probably wrap it up in an object that is serializable and have our enricher handle that. I am not sure how well this might play with Serilog.Exceptions - I think we might end up with `"Exception.SerilogLogContext":""` being produced by it as it encounters our wrapped context. Not the end of the world, just a wart.

The other approach would be for the Enricher to have a lookup of Exception -> LogContext, such that when it encounters an exception to log, it can pull its log context from this lookup. We could probably use a `ConditionalWeakTable` to store this association, such that when Exceptions become garbage, our lookup is automatically cleaned up too. We'd also avoid  confusing other enrichers that might be looking at `Exception.Data`.

Any thoughts on which approach sounds best?

**Comment by nblumhardt** [comment]
`ConditionalWeakTable` sounds like the way to go :-) 👍

**Comment by EdouardMYOB** [comment]
This has been a very useful thread @nblumhardt and everyone else! 

I'm trying to achieve basically the same thing - add the LogContext Scope information at the point where the Exception is thrown, rather than where it is caught, so when I log it at the catch site, it provides the additional context to help understand the problem.

My simplistic WIP for this is to create an Exception base class that populates a "ThrownScope" property that I can later inspect or filter on in Seq:

```public class LoggingContextAwareException : Exception
{
    public List<string> ThrownScope { get; } = new List<string>();

    public LoggingContextAwareException(Exception e, string message)
        : base(message, e)
    {
        var contextEnricher = LogContext.Clone();
        var logEvent = new LogEvent(DateTimeOffset.Now, LogEventLevel.Debug, null, new MessageTemplate(new List<MessageTemplateToken>()), new List<LogEventProperty>());
        contextEnricher.Enrich(logEvent, new PropertyFactory());
        if (logEvent.Properties["Scope"] is SequenceValue p)
            ThrownScope = p.Elements
                .Select( el => el is ScalarValue s ? s.Value.ToString() : el.ToString())
                .AsList();
    }
}```

Getting the array of scopes out of the LogContext is doable, but feels pretty messy - what do you think of given users of Serilog a simple way of extracting the scope information through a supported method, rather than everyone having to reinvent an extraction method (which in turn feels like they may not survive future changes in Serilog's implementation)? 

Some sort of `LogContext.CloneCurrentScope()` or `LogContext.Clone().CurrentScope` perhaps?

**Comment by nblumhardt** [comment]
Hi Edouard, thanks for bringing this one back to life! Cool to hear you're using Seq along with Serilog at MYOB 😎.

This might be one to pick apart into two tickets - one for providing some built-in way to pull context from exceptions (e.g. via `AppDomain.FirstChanceException` with CWT), and one for extracting properties from `LogContext`.

I don't think, though, that we're likely to land on an improvement to what you already have, for the second item: the code you've written is about as precise as the design of `LogContext` allows (since enrichers on the context are very flexible/programmatic). HTH!

**Comment by optical** [comment]
For anyone battling the loss of log context within async methods, or just in general when not using the `catch when` syntax, I've finally packaged up my approaches mentioned in the comments earlier. Its a simple enricher which when added will snapshot all context at the time the exception is thrown. When the exception gets logged, the enricher uses that context to enrich the log event. The package can be found here: https://github.com/optical/SerilogExceptionalLogContext (and on nuget)

Apologies for the necro & shameless self promotion, but hoping the package proves to be a simple solution to this. Keen for any feedback!

**Comment by Tolyandre** [comment]
Btw, I also used replies from this thread to solve a similar problem https://github.com/Tolyandre/serilog-throw-context-enricher. Additionally, I took into account a scenario when property exists and differs on rethrow. Also included plumbing to support code that pushes properties through Microsoft's BeginScope(). Ended up with a more complicated solution though

**Comment by optical** [comment]
Nice @Tolyandre, looks cool. Same fundamental principle, but supports other cases. Nice job!

**Comment by fingers10** [comment]
@optical @Tolyandre @skomis-mm what if we the asp.net core project is configured in the below way? How can we achieve the same without filters?

builder.Services.AddProblemDetails();
app.UseExceptionHandler();
