### ISSUE TITLE
Avoiding the messagetemplate treatment.

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog#897]
Hi.

As all we know Serilog uses message templates...
_Serilog uses message templates, a simple DSL that extends .NET format strings with named as well as positional parameters. Instead of formatting events immediately into text, Serilog captures the values associated with each named parameter._
...and it is really usefull especially combined with the Elasticsearch sink.

The point is that we have high performance apps where we use the Elasticsearch sink and messageTemplate but we also use just text (sometimes strings of about 10MB) to send to other storage systems. As you know, Serilog manages the string given as messageTemplate to find out the parameters it contains: with a string of 10MB this implies wasting many time (aprox. 100ms). A work around we do is to use a dummy messageTemplate (i.e. "{Data}") and then the 10MB string as the only parameter combined with a formatter that only gets the parameter value but removing the initial and final doublequotes that are added. This doesn't spend so much time but still adds (aprox. 1ms).

Is there any way in the current Serilog version to avoid messageTemplate treatment or ignoring adding double quotes to parameter values? In negative case, could it be possible to add a new configuration option to Serilog to avoid using messageTemplate and pass any given string directly to the Emit function?

Thanks a lot again, for your time and your great work.
Jose

**Comment by nblumhardt** [comment]
Hi Jose - yes; though it's not totally straightforward, you can do this with:

```csharp
var template = new MessageTemplate(data, new[] { new TextToken(data) });
var logEvent = new LogEvent(..., ..., template, ..., ...);
log.Write(logEvent);
```

There might be a little bit of fiddling around with parameters to construct the log event just the way you need it, but shouldn't be too tricky. Let me know if you need any more info.

Nick
