### ISSUE TITLE
Problem with object structure logging

### ISSUE THREAD

**Issue by LazarevAlexey** [serilog/serilog#899]
Hi everybody!
Then i try log object this way:
`AuditLogger.Information("{@Obj}", obj);`
or this way:
`var res = new CheckResult();`
 `AuditLogger.Information("Processing {@Res}", res);`
logger write only object name. In .log file I have something like:
2016-11-09 15:08:21.309 +05:00 [Information] ImportInfo {  }
2016-11-09 15:08:34.915 +05:00 [Information] Processing CheckResult {  }

All objects are public classes and has public field.

If I try log object by this code all is fine:
`var o = new { p1 = "dsfdsfdfs", p2 = 10 };`
`LoggersInstanses.Instance.AuditLogger.Information("{@obj}", o);`
The .log file text:
2016-11-09 15:38:33.518 +05:00 [Information] { p1: "dsfdsfdfs", p2: 10 }

**Comment by nblumhardt** [comment]
Hi @LazarevAlexey - thanks for the note.

Serilog only supports public _properties_, not public _fields_. You can however configure this on a case-by-case basis using:

```csharp
.Destructure.ByTransforming<CheckResult>(cr => new { cr.Field1, cr.Field2 })
```

If this occurs a lot, and you're not able to switch the values to fields, you can plug in a custom `IDestructuringPolicy` to do it automatically.

**Comment by LazarevAlexey** [comment]
Thanks for answer! Closed.
