### ISSUE TITLE
Observable sink does not honor the "no quotes around string values" flag

### ISSUE THREAD

**Issue by karolz-ms** [serilog/serilog#900]
```csharp
class LogEventObserver : IObserver<LogEvent>
{
    public void OnCompleted() { }
    public void OnError(Exception error) { }
    public void OnNext(LogEvent value)
    {
        Console.WriteLine(value.Properties["alpha"]);
    }
}

var logger = new LoggerConfiguration().WriteTo.Observers(events => events.Subscribe(new LogEventObserver())).CreateLogger();
logger.Information("{alpha:l}", "Hey!");
Log.CloseAndFlush();
Console.ReadKey();
```

Expected:

Hey!

Actual:

"Hey!"

**Comment by karolz-ms** [comment]
Serilog 2.3.0
Serilog.Sinks.Observable 2.0.1

**Comment by nblumhardt** [comment]
Hi Karol, thanks for the report.

The `:l` is part of the message template, and is not carried by the captured values. Here are a couple of alternatives that show how to get un-quoted output:

```csharp
// Original
Console.WriteLine(value.Properties["alpha"]);

// Message template carries the formatting info
Console.WriteLine(value.MessageTemplate.Render(value.Properties));

// Access the raw value
Console.WriteLine(((ScalarValue)value.Properties["alpha"]).Value);

// Alternative, apply the formatting to the `ScalarValue`
value.Properties["alpha"].Render(Console.Out, "l");
```

![image](https://cloud.githubusercontent.com/assets/342712/20158640/4622a81a-a727-11e6-98ca-600bd0411d9b.png)

Do any of these match your scenario better?

**Comment by karolz-ms** [comment]
Thanks, Nicholas, for quick reply! I think I will go with the second option. 

I guess I did not quite understand that Properties["Name"] is not the raw value, but a formatted value.

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up.

Properties in Serilog are captured using an object model that's analogous to JSON.NET's `JArray`, `JObject`, `JValue` and so-on. There are some trade-offs, but the purpose of this design is to:

 * Allow transformations on the structure of the data being logged (custom capturing rules, removal/addition/truncation of property values)
 * Allow structured values to be passed between threads and used concurrently, even if the raw object they were captured from isn't thread-safe (only scalars like `string` are captured as-is)

Can sometimes be a bit surprising, but has the advantages of keeping sinks and pipeline components free of concern for thread safety of the logged data, or transformations into whatever the target serialization format is.

Cheers!

**Comment by alierdogan70** [comment]
Hi,

I developed a custom sink for our needs. I would like to remove the quotes and other escape characters. 

I tried

`value.Properties["alpha"].Render(stringwriter, "l");`

It still returns a value with quotes.
