### ISSUE TITLE
ASP.NET Core ILogger Alignment - Trace ?

### ISSUE THREAD

**Issue by perokvist** [serilog/serilog#901]
Core logging has Trace as a loglevel and method on ILogger. Any plans to follow this path? 
This would aid "routing" to different sinks for trace (link application insights).

**Comment by nblumhardt** [comment]
Hi Per, thanks for the suggestion. Serilog's `Verbose` and ASP.NET Core's `Trace` are treated as the same level, you can use `Verbose` in Serilog configuration to control where ASP.NET Core's `Trace` events are routed.

It would have been nice to achieve consistency here, but at this stage the ripple-out effects of a rename would be more harmful to the ecosystem than any advantage of aligning them.

We _could_ introduce `LogEventLevel.Trace` as a synonym for `Verbose`, but then there would be inconsistency between the enum and API, so probably a non-starter too.

Let me know if you had something different in mind. Cheers!
