### ISSUE TITLE
Consider Capturing Parent Logger SourceContext

### ISSUE THREAD

**Issue by Mike-EEE** [serilog/serilog#904]
Currently `SourceContext` is captured by a logger, but it does not flow to any children loggers it may create through the use of `ForContext`.  That is, the `SourceContext` property is always set/overridden by a child logger and the parent `SourceContext` is not accessible by it.  It would be valuable to provide this property to children loggers so that it is available for filtering (or other as-yet unknown) purposes.

**Comment by Mike-EEE** [comment]
@khellang made a good point in chat that `SourceContext` is added by an enricher.  So is the answer here to make a `ForContext` overload that does the same for the child, but with another enriched property name, perhaps?  `ParentSourceContext`?

**Comment by nblumhardt** [comment]
Hi @Mike-EEE - thanks for the ticket!

By my original comment, I meant creating an alternative to `SourceContext`/`ForContext` that would have the "stacking" behaviour. I would guess it's possible to do this for `SourceContext` but at least at this stage, it would be too intrusive and have too many potential flow-on effects (e.g. additional allocation costs) to be considered in the near future.

The Serilog.Extensions.Logging implementation of `Scope` could form the basis of a `Scope`/`BeginScope`/`FromLoggerScope` enricher to work alongside `SourceContext`, though. It should be able to be bolted on much the same way that `LogContext` works today. Doing this as a third-party extension package would be a good first step if anyone's keen to try it out. Happy to help if so. Cheers!

**Comment by Mike-EEE** [comment]
OK, sounds good @nblumhardt.  Sounds like this issue is not relevant for this repo?  I will close it and we can open it again if necessary.  Thanks for your input, as always!

**Comment by nblumhardt** [comment]
Thanks Mike! Definitely relevant, but just might be one to explore separately (always lots of possibilities out there to investigate :-) )
