### ISSUE TITLE
Serilog-Sinks-Loggly dll is not signed

### ISSUE THREAD

**Issue by JoseTiagoCarvalho** [serilog/serilog#906]
The Serilog-Sinks-Loggly dll is not signed, so i created a pull request for that, please accept (https://github.com/serilog/serilog-sinks-loggly/pull/6).

The Serilog-Sinks-Loggly project does not have the Issues option active, can you please activate (https://github.com/serilog/serilog-sinks-loggly).

**Comment by nblumhardt** [comment]
Thanks, both taken care of now 👍

**Comment by JoseTiagoCarvalho** [comment]
Thanks.
