### ISSUE TITLE
Is there a way to not deconstruct {@MyObject} in message, but still use it for logging its properties

### ISSUE THREAD

**Issue by harvinders** [serilog/serilog#908]
We are using elastic search for logging homegrown Measurable data types like Voltage etc.

```
enum UnitType {mV, V};

class Voltage
{
     public double Value {get; set;}
     public UnitType Unit {get; set;}
     public override string ToString()
     {
          return $"{Value} {Unit}";
     }
}

.....

Voltage readVoltage = meter.Read();

logger.Debug("The measured voltage is {@readVoltage}");
....
```

This logs the voltage **object with its properties `Value` and `Unit` as fields** in the elastic search. This is great. However the **message field** is logged as `"The measured voltage is Voltage {Value : 10, Unit: mV}"`

Is there a way to have the **message field** be logged as `"The measured voltage is 10 mV"`. This is much easier to read especially for complex objects.

**Comment by merbla** [comment]
Hi @harvinders,

Do you want to use the existing`ToString` implementation on `Voltage `?

**Comment by harvinders** [comment]
Yes, and still looking to log the Voltage properties (Value and Unit) in the elasticsearch.

**Comment by adamchester** [comment]
You could stop using `@` for the message template field, so it will covered using `ToString`... and to get the separate fields in elastic search, use `ForContext` On the `ILogger` before logging the message?

**Comment by harvinders** [comment]
We do log lots of events like these and is not just one of requirement. Maybe I can wrap it up to hid the use of `ForContext`.

However, would this not slow down things, as for almost half of the events (they log measurables or similar objects) I would have to create a new `Logger` (through `ForContext` calls)?

**Comment by nblumhardt** [comment]
It's a _tiny bit_ hacky (okay, quite a bit ;-)) but you could combine a destructuring policy and an enricher to do this.

1. The destructuring policy - adds a `AsString` property to the result:

```csharp
.Destructure.ByTransforming<Voltage>(v => new { v.Value, v.Unit, AsString = v.ToString() })
```

2. The enricher looks for structures with a `AsString` property and flattens them out:

```csharp
class AsStringEnricher : ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        foreach (var p in logEvent.Properties)
        {
            var sv = p.Value as StructureValue;
            if (sv != null)
            {
                var s = sv.Properties.SingleOrDefault(sp => sp.Name == "AsString");
                if (s != null)
                {
                    logEvent.AddOrUpdateProperty(new LogEventProperty(p.Key, s.Value));
                    foreach (var sp in sv.Properties)
                    {
                        if (sp != s)
                            logEvent.AddOrUpdateProperty(sp);
                    }
                    break; // Don't enumerate after modifying ;-)
                }
            }
        }
    }
}
```

(Needs work if it is going to support multiple properties of this kind in a single message - just threw it together.)

**Comment by nblumhardt** [comment]
@harvinders did you try this out? Closing as the thread has gone quiet, but please let us know if you take it further.

**Comment by harvinders** [comment]
Sorry, I lost track of this. 

I am not sure this would work for us. 

`.Destructure.ByTransforming<Voltage>(v => new { v.Value, v.Unit, AsString = v.ToString() })` is not really an option as we allow users to define their own data type, this means that we would have to ask users to somehow call this code somehow from exposed APIs. 

On a separate note I think it would be great if we can support this feature natively in serilog, say using another character like `%` or `$` just like `@` for deconstructing.

**Comment by adamchester** [comment]
@harvinders would this work for you?

```csharp
void Main()
{
    var logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.Sink(new LINQPadDumpSink())
        .CreateLogger();

    var voltage = new Voltage { Unit = UnitType.mV, Value = 12345 };
    
    logger
        .ForContext("Voltage", voltage, destructureObjects: true)
        .Information("Don't be afraid. The voltage is {$voltage}", voltage);
}

enum UnitType { mV, V };
class Voltage {
    public double Value { get; set; }
    public UnitType Unit { get; set; }
    public override string ToString() {
        return $"{Value} {Unit}";
    }
}

class LINQPadDumpSink : Serilog.Core.ILogEventSink {
    public void Emit(LogEvent @event) {
        @event.Dump(@event.RenderMessage());
    }
}
```

![image](https://cloud.githubusercontent.com/assets/570470/22332464/ccf07f02-e41c-11e6-8727-e1b46316e6bd.png)

http://share.linqpad.net/442it6.linq

**Comment by adamchester** [comment]
P.s. I'm not sure of the performance exactly, but maybe you give it a try and see if it meets your needs?
