### ISSUE TITLE
lowercase enriched object properties

### ISSUE THREAD

**Issue by atodd-geoplan** [serilog/serilog#910]
Where / how can I ensure lowercase property names for enriched objects, e.g.

```
class ProcessInfoEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            logEvent.AddPropertyIfAbsent(
                propertyFactory.CreateProperty("processInformation", ProcessInformation.Current, true)
            );
        }
    }
```

results in ES properties like:
`fields.processInformation.RequestId`

I would prefer
`fields.processInformation.requestId`

In order to match with similar data in other alternatively sourced indexes.

**Comment by nblumhardt** [comment]
Hi - you could implement an `ILogEventEnricher` to do this. There's a helper class in the `Serilog.Data` namespace (`LogEventPropertyValueVisitor`) that will let you perform the "to lowercase" transform easily on complex property structures. If you hit any challenges please drop us a line! :-)

**Comment by pecigonzalo** [comment]
@nblumhardt I know this is quite old, but do you have any TLDR on how to implement this? I have been trying to implement this (in F#) but Im not sure how assign the `LogEventPropertyValueVisitor` "visitor".

I have created an ILogEventEnricher, but im a bit lost on that last part.
