### ISSUE TITLE
Alternative log

### ISSUE THREAD

**Issue by Basek** [serilog/serilog#911]
There is any possibility to provide the alternative log that will be activated when main failed to write?

**Comment by nblumhardt** [comment]
Hi, thanks for getting in touch.

No, Serilog doesn't implement this - the recommendation is just to use a secondary log in conjunction with the primary one.

HTH!

**Comment by Basek** [comment]
Hi, thanks for answer

We have some constraints and can't use secondary log always. Do you know any plugins or extension for serilog that could provide it?

**Comment by nblumhardt** [comment]
Hi Basek - you could possibly write an implementation of `ILogEventSink` that wraps two other sinks - the primary and secondary destinations. In `Emit()` you would first write to the primary sink, and then to the secondary if an exception is raised.

**Comment by nblumhardt** [comment]
Closing as no action's planned right now, but if anyone decides to tackle it please chime in on this ticket. Cheers!
