### ISSUE TITLE
serilog.fullnetfx.dll is missing from 2.3.0 package

### ISSUE THREAD

**Issue by jllblk** [serilog/serilog#914]
Serilog nuget package 2.3.0 is missing the serilog.fullnetfx.dll which is present in Serilog 1.5.14. The absence of this package causes runtime errors if the user is using Serilog.Extensions.Logging 1.0.0 and has installed Serilog 2.3.0 and has never installed Serilog 1.5.14.

**Comment by nblumhardt** [comment]
Hi @jllblk - it sounds like you have another package built against Serilog 1.5 - there's no _Serilog.FullNetFx.dll_ assembly in the v2 series of Serilog (and _Serilog.Extensions.Logging_ is only built against 2.x).

Can you spot any sinks/third-party packages that might still have a 1.5 dependency?

Cheers,
Nick

**Comment by jllblk** [comment]
Serilog.Sinks.MsSqlServer version 3.0.48

**Comment by merbla** [comment]
@jllblk @nblumhardt 

Looks like the popular 3.x versions have the following dependency.

`Serilog (>= 1.4.204 && < 2.0.0)`

* [3.0.98](https://www.nuget.org/packages/Serilog.Sinks.MSSqlServer/3.0.98)
* [3.0.52](https://www.nuget.org/packages/Serilog.Sinks.MSSqlServer/3.0.52)
* [3.0.48](https://www.nuget.org/packages/Serilog.Sinks.MSSqlServer/3.0.48)

**Comment by nblumhardt** [comment]
Thanks @merbla. _Serilog.Sinks.MSSqlServer_ wasn't updated to use Serilog 2.0 until its _4.x.x_ series of releases.
