### ISSUE TITLE
Cannot reference Serilog as Nuget package

### ISSUE THREAD

**Issue by asipras** [serilog/serilog#917]
I have created a new Windows Forms application and it uses .net framework 4.5.2. I tried referencing Serilog using Nuget Package Manager and I could not do so.

I also tried installing the package using the Package Manager console and go the following message

**Attempting to gather dependencies information for package 'serilog.2.3.0' with respect to project 'App1', targeting 'Windows,Version=v8.1'
Attempting to resolve dependencies for package 'serilog.2.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'serilog.2.3.0'
Resolved actions to install package 'serilog.2.3.0'
Install failed. Rolling back...
Package 'Serilog.2.3.0 : ' does not exist in project 'App1'
Package 'Serilog.2.3.0 : ' does not exist in folder 'C:\Users\asif.prasla\documents\visual studio 2015\Projects\App1\packages'
install-package : An error occurred while downloading package 'Serilog.2.3.0 : ' from source 
'https://www.nuget.org/api/v2/'.
At line:1 char:1
+ install-package serilog
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellC 
   mdlets.InstallPackageCommand**

How can i resolve this?

Thanks

**Comment by merbla** [comment]
Hi @asipras,

What version of VS are you using?

It may be similar to these issues.

* #863 
* #818 
* #806

**Comment by asipras** [comment]
The issue was because i was using visual studio 2015 update 1. I installed update 3 for visual studio 2015 and everything worked fine.

Thanks for your help @merbla
