### ISSUE TITLE
TeamCity conditional formatting

### ISSUE THREAD

**Issue by erick-thompson** [serilog/serilog#918]
I am using Serilog in a number of places where the code executes on a TeamCity agent. I need to format the Console log output when running on TeamCity to output messages in the TeamCity message format ([https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity](url)). This is so that when errors are reported via Serilog they show up as errors in TeamCity, but when running outside of TeamCity they show up normally (based on if an environment variable has been set). 

Before I start down this path, has anyone done this before? Also, what is the best way to go about doing this? Formatter?

Thanks,
Erick

**Comment by nblumhardt** [comment]
Hi Erick - an `ITextFormatter` provides the ultimate flexibility here, but have you investigated using the `outputTemplate` parameter to the console sink to do this?

**Comment by erick-thompson** [comment]
Hey Nick,

The concern that I have with the outputTemplate is that each application would need to have the template in place, and would need to have the logic to detect when running under TeamCity. It's not a huge barrier, but I was hoping for something that would always be running, and only change the format when running under TeamCity. It makes it easier to use and reuse. I'll take a look at ITextFormatter.

Thanks,
Erick

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Sounds like `ITextFormatter` is the right way to go 👍
