### ISSUE TITLE
How to use serilog in a referenced class library (not asp.net core)

### ISSUE THREAD

**Issue by simonpbond** [serilog/serilog#920]
I am working on a legacy winforms application and can sucessfully setup serilog and access it's static method by placing it inside program.cs, 

However I am wanting to also log inside the various referenced class libraries in the project.

As I can't reference the main application from the class library itself, due to a circular dependency, what is the best way to perform logging in these class libraries?

Apologies for my ignorance!

**Comment by nblumhardt** [comment]
Hi Simon, no worries at all.

You need to:

 1. Reference _Serilog_ (either the DLL or NuGet package) from the class libraries
 2. In the class libraries, call static methods like `Log.Information()`

So long as you've initialised `Log.Logger` at application start-up, everything should just work that way.

HTH!

**Comment by simonpbond** [comment]
I can't thank you enough, thanks for taking the time to explain. : )

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up Simon, and good luck with it!

**Comment by beaudamore** [comment]
However, in my experience, enrichers like Serilog.Enrichers.HttpContextInfo will not work since the context doesn't get passed back.

**Comment by nblumhardt** [comment]
@beaudamore sounds like you may be hitting a different configuration issue - if you need a hand, please feel free to open a new ticket with details of how your logger is set up. Cheers.

**Comment by Tonay** [comment]
> Hi Simon, no worries at all.
> 
> You need to:
> 
> 1. Reference _Serilog_ (either the DLL or NuGet package) from the class libraries
> 2. In the class libraries, call static methods like `Log.Information()`
> 
> So long as you've initialised `Log.Logger` at application start-up, everything should just work that way.
> 
> HTH!

Thank you soo much! I missed reference dll's for my project and i added Serilog dll's from nuget into referenced project like you said. It's worked!

**Comment by ndc** [comment]
> However, in my experience, enrichers like Serilog.Enrichers.HttpContextInfo will not work since the context doesn't get passed back.

Just want to refute this claim: I called `Serilog.Log.Information("something");` inside a class library under an asp.net core app and the log contains ActionId, RequestId, ActionName, RequestPath, etc.
