### ISSUE TITLE
Serilog not logging in rolling file when deployed to IIS?

### ISSUE THREAD

**Issue by asadsahi** [serilog/serilog#921]
```
 public Startup(IHostingEnvironment env)
        {
            Log.Logger = new LoggerConfiguration()
            .MinimumLevel
            .Error()
            .WriteTo.RollingFile("logs\\log-{Date}.txt", LogEventLevel.Information) // Uncomment if logging required on text file
            .CreateLogger();
...........
```

With above configuration I can see any errors I log in application in logs folder, but only when I run it locally.

However when I deploy the same website on IIS, even logs directory exist in website root level, it doesn't even create file or write any logs to any text file.

Note: logs is the same folder which I have configured in web.config for stderror output and the file is created for stdoutput though:

web.config:

`    <aspNetCore processPath="dotnet" arguments=".\MyApp.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />`

So it cannot be write permissions issue as stdout file is screated, but serilog fails to crate file for some reason.

**Comment by nblumhardt** [comment]
Hi Asad; I'd guess the path needs to be absolute - could you try that and let us know what you find? Thanks!

**Comment by asadsahi** [comment]
@nblumhardt  Same story:

I tried with serilog rolling file path to be absolute, but that doesn't make any difference. Cannot see any logs written by website running under IIS.

```
        public Startup(IHostingEnvironment env)
        {
            _hostingEnv = env;
            // Configure Serilog
            Log.Logger = new LoggerConfiguration()
            .MinimumLevel
            .Error()
            // Uncomment if logging required on text file
            .WriteTo.RollingFile("C:/inetpub/logs/serilog/logs/log-{Date}.txt")
            .WriteTo.Seq("http://localhost:5341/")
            .CreateLogger();
```

Same app with absolute file path running with VS code lets say on same machine creates file.

**Comment by nblumhardt** [comment]
Ah, I see. Using `%APPDATA%` in the path might get you a reasonable writable default location 👍

**Comment by nblumhardt** [comment]
Sorry, I should say - you'll need to get the value with `Environment.GetEnvironmentVariable()` - `%` syntax only works in the XML/JSON configuration subsystems.

**Comment by asadsahi** [comment]
Nope, same issue. on appdata location when configured like this:

`            .WriteTo.RollingFile(Environment.GetEnvironmentVariable("APPDATA") + "/serilog/logs/log-{Date}.txt")
`

Running it using IDE writes files, but IIS can't write to that location.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Unfortunately Serilog can't do anything about folder permissions in your deployment environment - using something like Octopus Deploy to set the permissions at deployment time sounds like your best bet.

Closing, as I don't think we can help with this, but do please let us know if you think something's amiss with Serilog here.

Hope this helps!

**Comment by chrisfcarroll** [comment]
> However, Giving write access to "IIS AppPool\DefaultAppPool" user on folder "C:\inetpub\logs\serilog\logs" writes log file.
> So the question boils down to, what is recommended practice of writing log files for any website rather everytime giving write permissions to a particular folder. Is there a default folder that we can specify in rolling file path that IIS can write to?

No, there isn't. Default IIS setup is that IIS AppPool\DefaultAppPool has no write-permissions anywhere except %Temp%. 
You want a company- or ops team-level decision to agree a location that you'll give write access to.

**Comment by tsimbalar** [comment]
I know that on our production environments, the IIS application pool accounts do not have any write permissions anywhere ... (it is a choice from the Ops team)

FWIW I believe it is general considered "bad practice" to log to files on production environments, because : 
- it requires explicit permissions
- without proper log-files administration, you might end up filling up the disk
- it makes it hard to extract information from the logs
- it makes it hard to analyze logs in "farm" environments (with several servers handling requests)

**Comment by sgentile** [comment]
Wait, so you're saying this logging project can't log asp.net core solutions in IIS in production?   Odd logger solution ?

**Comment by chrisfcarroll** [comment]
No, we're saying that IIS by default gives no write permissions to the applications that it hosts (except, possibly, to the %temp% directory) so by default no logging solution can write to files.
The solution is to agree with whoever manages your production servers to grant write permissions to your application. Or , log to a database or network share instead.

**Comment by mickyd** [comment]
> 
> FWIW I believe it is general considered "bad practice" to log to files on production environments, because :
> 
> * it requires explicit permissions
> * without proper log-files administration, you might end up filling up the disk
> * it makes it hard to extract information from the logs
> * it makes it hard to analyze logs in "farm" environments (with several servers handling requests)

Utter nonsense.  Going by your logic if a system fails no one will ever be able to fix a fault because there is no diagnostic information due to an irrational fear that the hard drive might fill up.

I guess someone better tell people not to use:

- The Windows Event Log
- MSMQ
- SQL Server Transaction Log
- Dynamic Windows Pagefile

**Comment by nblumhardt** [comment]
Please let's keep the tone constructive, here.

**Comment by alexandis** [comment]
And providing write permissions to a publish folder is rather clumsy. Still not sure I want to bother with that, but what else I can do? [http://sedodream.com/2011/11/08/SettingFolderPermissionsOnWebPublish.aspx](url)

**Comment by hassankamarzadeh** [comment]
https://stackoverflow.com/questions/49891083/enable-file-logging-on-iis-for-serilog
