### ISSUE TITLE
HockeyApp Provider

### ISSUE THREAD

**Issue by tiksn** [serilog/serilog#922]
Please add HockeyApp sinks/provider

**Comment by merbla** [comment]
Hi @tiksn,

Thanks for the request, if you have developed a sink for HockeyApp we can add it to the list of provided sinks in the [wiki](https://github.com/serilog/serilog/wiki/Provided-Sinks). Generally we are not accepting new sinks into the organisation unless there is a strong case for it.  If the usage grows and the sink is widely adopted we can revisit moving it under the Serilog organisation.
