### ISSUE TITLE
Transfer ownership of serilog-extensions-logging-applicationinsights

### ISSUE THREAD

**Issue by micdenny** [serilog/serilog#923]
This is the repo: https://github.com/micdenny/serilog-extensions-logging-applicationinsights

I hope everything's following the serilog naming convention, I've followed the [contributing instruction](https://github.com/serilog/serilog/wiki/Contributing) plus copying build and publish stuff from other serilog project.

It's similar to [serilog-extensions-logging-file](https://github.com/serilog/serilog-extensions-logging-file), but it enables application insights tracing on asp.net core in one line of code, using as a base package [serilog-sinks-applicationinsights](https://github.com/serilog/serilog-sinks-applicationinsights).

The package has been already pushed by appveyor to NuGet and it's ready to use: https://www.nuget.org/packages/Serilog.Extensions.Logging.ApplicationInsights

Let me know if you're interested in transfer ownership.

**Comment by nblumhardt** [comment]
Hi @micdenny - thanks for getting in touch!

I don't think we're ready to go further down this path; making it easier to consume Serilog sinks from _m.e.Logging_ is an interesting angle to explore, but we'd need to do it differently to cope with the large number of projects involved (currently ~90 sinks, IIRC). _File_ was a bit of a special case/experiment that we're still watching pan out.

Interested in further thoughts on how all of this might fit together.
