### ISSUE TITLE
Dynamic/expression-based filtering

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#924]
Filtering in Serilog is currently based on predicates - `Func<LogEvent, bool>` - and some helpers to generate common ones like `Matching.FromSource()`.

In some situations, writing a predicate over a log event can be hard. For example, excluding events with a particular property value:

```csharp
    .Filter.ByExcluding(e => {
        LogEventPropertyValue p;
        if (!e.Properties.TryGetValue("P", out p) ||
          !(p is ScalarValue) || !(((ScalarValue)p).Value is int!))
            return false;
        return 3 != (int)((ScalarValue)p).Value;
    })
```

...or something like that :-). The Serilog representation of structured data, and the need to exactly match or convert the boxed value types (casting to `long` would fail here) makes it extremely error prone.

Filters to do more complex things with structured data are pretty much out of the reach of casual users.

In other cases - XML or JSON configuration - it's not possible to supply a predicate, so other hoops need to be jumped through.

I've spiked an expression-based filtering system using bits and pieces of code from other projects. It supports an SQL-like predicate syntax (think `WHERE` clause body) and is pretty unsurprising:

```csharp
var expr = "@Level = 'Information' and AppId is not null and Items[?] like 'C%'";

Log.Logger = new LoggerConfiguration()
    .Enrich.WithProperty("AppId", 10)
    .Filter.ByIncludingOnly(expr)
    .WriteTo.LiterateConsole()
    .CreateLogger();

// Printed
Log.Information("Cart contains {@Items}", new[] { "Tea", "Coffee" });
Log.Information("Cart contains {@Items}", new[] { "Peanuts", "Chocolate" });

// Not printed
Log.Warning("Cart contains {@Items}", new[] { "Tea", "Coffee" });
Log.Information("Cart contains {@Items}", new[] { "Apricots" });

Log.CloseAndFlush();
```

This is wrapped up in a library tentatively called _Serilog.Filters.Expressions_, which is not yet finalized but can be seen at: https://github.com/nblumhardt/serilog-filters-expressions

Though it's a fairly large amount of somewhat hairy code, I'd like to propose we adopt this in the Serilog project and make it available alongside the other supported libraries. This would encourage us to get the work done to make it fit nicely into the configuration system, also.

```xml
  <add key="serilog:filter:ByExcluding.expression"
            value="SourceContext = 'MyApp.Program'" />
```

On the plus-side, it's functionally fairly complete - aside from fixing the occasional bug, just about any conceivable filter can be constructed, and the execution model is reasonably efficient and reliable.

The package depends on [Superpower](https://github.com/datalust/superpower) for the parser, and so I would not at this stage suggest making it a default part of Serilog, but as an add-on the dependency doesn't seem problematic.

👍 👎 ?

**Comment by nblumhardt** [comment]
Performance of `A = 3` comes out at 4.42&times; slower than the handwritten code, which is within the order-of-magnitude goal:

|            Method |      Median |    StdDev | Scaled | Scaled-SD |
| ------------------ |------------ |---------- |------- |---------- |
|     TrivialFilter |  22.2229 ns | 0.1193 ns |   0.37 |      0.00 |
| HandwrittenFilter |  60.5052 ns | 0.5242 ns |   1.00 |      0.00 |
|  ExpressionFilter | 269.0795 ns | 3.2671 ns |   4.42 |      0.06 |

**Comment by merbla** [comment]
👍

**Comment by nblumhardt** [comment]
Righto, thanks @merbla, let's run with it :-)

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-filters-expressions
