### ISSUE TITLE
Different logger configurations on different target environments?

### ISSUE THREAD

**Issue by naymore** [serilog/serilog#926]
With other logging frameworks (namely NLog) we were used to read a computer environment variable ([ASPNETCORE_ENVIRONMENT](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments)) to decide which configuration file to load for each target environment.

I wonder if there is similar functionality in Serilog.
Of course on application start I could wire up loggers differently depending on the environment variable. I'm just wondering if there is already a built-in way? This might be a candidate for the fluent interface ;-)

**Comment by prochnowc** [comment]
You could simply leverage Microsoft.Extensions.Configuration feature for this. 
Place setting files to override settings depending on environment in your project `appsettings.json` and `appsettings.development.json`.

Then use ConfigurationBuilder like this in startup class:
```
IConfigurationRoot BuildConfig(IHostingEnvironment env)
{
    builder.SetBasePath(env.BasePath)
               .AddJsonFile("appsettings.json")
               .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true);

    return builder.Build();
}
```

Then create and register your logger like this:
```
void Configure(IApplicationBuilder builder, ILoggerFactory loggerFactory)
{
    var loggerConfig = new LoggerConfiguration();
    loggerConfig.ReadFrom.Configuration(ConfigurationRoot);
    loggerFactory.AddSerilog(loggerConfig.CreateLogger());
}
```
