### ISSUE TITLE
Popping Context Properties

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog#927]
Looking at: https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext

It clearly states: 

> Important: properties must be popped from the context in the precise order in which they were added. Behavior otherwise is undefined.

I am logging with the Trace sink, and two properties: 'Source' and 'Context'

Can you confirm for me that this code is going to 'pop' the properties in the right order:
```
    this.logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Trace(outputTemplate: "{Timestamp:T} [{Level}] [{ContextId}] [{Source}] {Message}{NewLine}{Exception}")
                .CreateLogger();

    var source = "asource";
    var context = "acontext";

    using (source.HasValue() ? LogContext.PushProperty("Source", source) : null)
            {
                using (ContextId.HasValue() ? LogContext.PushProperty("Context", ContextId) : null)
                {
                    this.logger.Write(level, messageTemplate, propertyValues);
                }
            }

```

Or perhaps I have it backwards?

**Comment by adamchester** [comment]
Hi @jezzsantos, looks right to me. The `using` statements will do it in the correct order.

**Comment by jezzsantos** [comment]
Thanks @adamchester,

When you say "correct order",  are you referring to the declared order in the "outputTemplate" property of the Trace sink?

My real question was what does the correct order refer to? Is that the order the sink processes the properties? or something else?

**Comment by adamchester** [comment]
The rule is [LIFO](https://en.m.wikipedia.org/wiki/Stack_(abstract_data_type)) (last in, first out).

'In' means pushing a property onto the log context. 'Out' refers to popping a value off the log context.

All log messages inside the `using’ will have the pushed context properties on them.

**Comment by jezzsantos** [comment]
OK, just to complete my understanding here.

Let's say I have a sink that is processing these events.
```
public void Emit(LogEvent logEvent)
{
 // Get the values of the properties, how to pop from LogContext?
}

```

How does this sink pop those properties?

**Comment by adamchester** [comment]
@jezzsantos a sink will already have the correct set of properties inside each log event it receives. A sink should not push/pop log context properties at all. Does that help?

**Comment by jezzsantos** [comment]
OK, great.

Then I can't screw it up on the sink side then - good.

Only gap in my understanding then, is how could I 'pop' the properties in the wrong order?

**Comment by adamchester** [comment]
@jezzsantos I guess if one didn't use `using` statement, or put the `IDisposable` instances into an unordered collection, that could easily make them dispose in the wrong order.

**Comment by jezzsantos** [comment]
I get it now, thanks.
