### ISSUE TITLE
Serilog.Extensions.Logging.File nuget incompatible with dotnetcore 1.1.0

### ISSUE THREAD

**Issue by softlion** [serilog/serilog#929]
"Serilog.Extensions.Logging.File": "1.0.1-dev-00008",

is incompatible with dotnetcore 1.1.0 nugets. Project compiles but throws runtime exception at startup as it can not depend on Microsoft.Extension.Logging version 1.1.0

**Comment by nblumhardt** [comment]
Thanks for the pointer - can you please include the exception information?

**Comment by softlion** [comment]
I had some kind of incompatibility with microsoft logging interface abstraction. I tryed to reproduce the issue today and it works fine. I tryed twice in the past and it didn't worked. This is crazy ...

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up.
