### ISSUE TITLE
Writing to rolling file in GELF format

### ISSUE THREAD

**Issue by jruizaranguren** [serilog/serilog#930]
I'm interested in writing to a rolling file in [GELF format](http://docs.graylog.org/en/2.1/pages/gelf.html). This file will be eventually be loaded to `Graylog2` for consumption.

I'm aware of [this sink](https://github.com/whir1/serilog-sinks-graylog) that allows to send events int `GELF` format directly to `Graylog2` via http. 

I wonder which is the best approach to get this, and if some of this work could be of interest for more people:

* Implement a new sink extending `Rolling File` that simply formats messages in `GELF`.
* Provide templates which ensure that `GELF` is satisfied, using `Rolling File` sink. No public contribution.
* Try to extend [Graylog sink](https://github.com/whir1/serilog-sinks-graylog) to write also to file.

What do you think?
Thanks.

**Comment by nblumhardt** [comment]
Hi @jruizaranguren - `RollingFile` already supports custom formatters; to do this the ideal approach would be:

 * Create a `GelfJsonFormatter` implementing `ITextFormatter` (see [these two formatters](https://github.com/serilog/serilog-formatting-compact/tree/dev/src/Serilog.Formatting.Compact/Formatting/Compact) for inspiration)
 * Plug this in as the first argument of `WriteTo.RollingFile(new GelfJsonFormatter(), ...)`

I'm assuming you want to use the GELF JSON format, which should be pretty close to the `RenderedCompactJsonFormatter` linked above; if you want to do anything fancy with Gzip then things will be trickier :-)

HTH!

**Comment by jruizaranguren** [comment]
Thanks, @nblumhardt,  it really helps. Writing JSON seems pretty straightforward.

I don't plan any chunking so far (that would be interesting for UDP, AMQP, HTTP which is not in my short term plan). But I might give a try to Gzip. 

I may just Gzip each message and write it through TestWriter line by line. 
I am curious what tricky things you are expecting.

**Comment by nblumhardt** [comment]
I'd suggest Gzipping on send, rather than in the file, as the binary data produced by Gzip may contain CR/LF characters that will upset the line splitting later on.

Sounds like you're off to a good start, keep us posted!

**Comment by alexsandro-xpt** [comment]
Nice tip @nblumhardt
