### ISSUE TITLE
Question: Any way to call a second sink if it fails the emission of a first sink?

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog#931]
The question is easy but may be the answer is not, :-P

Imagine that we have a first sink and if its emission fails then we want to send the payload to another sink (maybe of a different serilog instance) and discard the first sink emission (not retry).

Is it possible?

Thanks a lot.

**Comment by nblumhardt** [comment]
Hi Jose,

It's not possible today except by writing a custom sink that does the fail-over.

There was a discussion recently in the Gitter channel about improving `SelfLog` to make it possible to send diagnostics/failures from the logging pipeline into another sink - is this the general idea you're looking for, or is your scenario more specific (i.e. auditing)?

**Comment by jose3m** [comment]
Hi Nick !

The target was to have a mechanism to avoid losing messages (and avoid buffering and retry) if a sink fails and giving these messages to another sink to try it in a different way.

Effectively the solution will be writing a custom sink.

Thanks a lot.
