### ISSUE TITLE
Created Sink for Sumo Logic

### ISSUE THREAD

**Issue by billpratt** [serilog/serilog#933]
Hello,

I wanted to share that I created a sink for writing events to [Sumo Logic](https://www.sumologic.com/). Please feel free to add it to the [available sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) list if you wish. Also, any comments/questions/concerns would be helpful.

GitHub: https://github.com/billpratt/serilog-sinks-sumologic
Nuget: https://www.nuget.org/packages/Serilog.Sinks.SumoLogic/

Thanks,
Bill

**Comment by merbla** [comment]
Hey @billpratt, 
Thanks for letting us know about the sink!  

I have updated the list.
