### ISSUE TITLE
How to create a Sink based on PeriodicBatchingSink  which is initialised using app.config?

### ISSUE THREAD

**Issue by harvinders** [serilog/serilog#935]
I am trying to create a custom sink based on the PeriodicBatchingSink. But I am not sure what needs to be done to make sure the following code constructs the sink object. 

```cs
    var log = new LoggerConfiguration()
        .ReadFrom.AppSettings()
        .CreateLogger();
```

I suppose some sort of container is calling the sink's constructor. How should the sink's constructor look like? And how to pass the settings defined in the <appSettings> to the sink.

I wrote a sink as follows

```cs
namespace Serilog.Sinks.PropertyBasedRollingFile
{
    public class PropertyBasedRollingFileSink : PeriodicBatchingSink
    {
        public PropertyBasedRollingFileSink() : base(1000, TimeSpan.FromMilliseconds(500))
        {
        }
        ...
    }
    ...
}
```

And the app.config looks like 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <appSettings>
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:PropertyBasedRollingFile" value="Serilog.Sinks.PropertyBasedRollingFile" />
    <add key="serilog:write-to:PropertyBasedRollingFile" />
  </appSettings>
</configuration>
```

**Comment by nblumhardt** [comment]
Hi @harvinders - to do this you just need to create an extension method on `LoggerSinkConfiguration` called `PropertyBasedRollingFile()`. The configuration subsystem translates the setting keys/values into method calls/args.

HTH!

**Comment by harvinders** [comment]
Thanks, works like a charm
