### ISSUE TITLE
Sanitizing logs

### ISSUE THREAD

**Issue by Noctis-** [serilog/serilog#938]
As a user i would like to have the option to sanitize logs. 
An example would be to scrub credit cards numbers before they hit storage for PCI compliance.

Currently I couldn't find any straight forward way of doing this.

I've found this [project](https://github.com/PageUpPeopleOrg/SeriLog.LogSanitizingFormatter), but it's for .Net core, so won't even build for our needs.

Other options discussed where using Enrichers, or capturing the event forcing it to a string, and running a regex against it.

**Comment by merbla** [comment]
Hi @Noctis,

Would something like the following work?

https://github.com/destructurama/attributed

**Comment by merbla** [comment]
Or https://github.com/destructurama/by-ignoring

**Comment by nblumhardt** [comment]
@Noctis- the project you pointed to is probably the way to go - if someone could PR the `project.json` change to support .NET Standard instead of/in addition to .NET Core, it should cover what you're looking for.

The best alternative I can come up with is:

```csharp
class Sanitizer: ITextFormatter
{
    readonly ITextFormatter _inner;

    public Sanitizer(ITextFormatter inner)
    {
        _inner = inner;
    }

    public void Format(LogEvent logEvent, TextWriter output)
    {
        var sw = new StringWriter();
        _inner.Format(logEvent, sw);
        var s = sw.ToString();
        var sanitized = s.Replace("Foo", "***");
        output.Write(sanitized);
    }
}
```

As long as your sanitization process doesn't touch `",[]{}:` then this can be used with JSON as well as regular text output. To use it just wrap the required formater:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.File(new Sanitizer(new JsonFormatter()), "log.txt")
    .CreateLogger();
```

The options in addition to `JsonFormatter` are things like `MessageTemplateTextFormatter`, `CompactJsonFormatter`, etc.

Yell if you need more info!

Cheers,
Nick

**Comment by nblumhardt** [comment]
(Just adding to @merbla's answer since the `Sanitizer` approach will also mop up accidental logging of sensitive data in exception messages, stack traces, and message templates.)

**Comment by Noctis-** [comment]
@merbla 
Cheers mate. Both look good, but they are kind of relaying on the fact that people will actually put the attribute on the property. 
I thought about something similar with the Filters, but decided not to do it because if somebody forgets to put it (or someone decides to call the property "bar" instead of "foo") it'll break.

**Comment by Noctis-** [comment]
@nblumhardt 
Looks promising. I've already left a comment on their project earlier today. I'll give ITextFormatter a spin. Seems simple enough for what we need, and for the time being will work.
I might try to push on the other project as soon as i get some time, since others will benefit from it as well, and it can give finer control as well.
Cheers mate.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @Noctis- 👍

**Comment by Noctis-** [comment]
@nblumhardt 
Hmmm ... I gave this a quick spin ... It works great for the file, since it takes an ITextFormatter, on the latest version.
Sadly, we're mainly using either colored console (i prefer literate, but same same), or the seq sink, which won't take an ITextFormatter. 
I've seen the serilog-sinks-json, but it says it's encouraged NOT to use it, since from ver 2 it's done better/different/or the other.  We're using 1.5.xx and can't upgrade ATM due to some other dependencies.
Any suggestions will be appreciated,
Cheers

**Comment by nblumhardt** [comment]
Ah, I see - still some challenges there. Re-opening in case we can turn up some more ideas.

In 2.x, the standard `Console` sink accepts a formatter and works with this technique. `LiterateConsole` won't, and would need to use the enricher option, though it's not a complete solution (you're probably better off just turning off `LiterateConsole` in production if you can).

**Comment by Noctis-** [comment]
@nblumhardt 
Cheers mate.
For now due to deadlines, I'll do what I can with what i have, but I'll keep an eye and delve deeper into the code base in a couple of weeks when things calm down.
I'll also see if the guys on the other project have some suggestions. I've had a look at the .Net Core / standard, but didn't realize how far behind the ball I am on those topics :). More reading and playing around it seems.

Cheers again.

**Comment by nblumhardt** [comment]
I might close this again while things settle - let us know how you go. Cheers!

**Comment by Noctis-** [comment]
No worries. Seems like they are having a nap atm ... and i've been busy with other things.
I will still try to see if i can work around either of the issues.
Cheers again for your help.

**Comment by CADbloke** [comment]
Thanks all for the pointers. I got this working using [@nblumhardt's comment above](https://github.com/serilog/serilog/issues/938#issuecomment-278229386) for async rolling files. Using this I can sanitise the rolling file log on the local user's PC but still write full stack traces to Sentry. Hurrah!

I used it to remove namespaces and method names for things like licensing etc.

````cs
/// <summary> Serilog Exception Stack Trace sanitizer. </summary>
/// <seealso cref="T:Serilog.Formatting.ITextFormatter"/>
class Sanitizer: ITextFormatter // https://github.com/serilog/serilog/issues/938#issuecomment-278229386
{
    private readonly ITextFormatter _mainFormatter;
    private static Regex sanitiser = new Regex(@"now you have 2 problems", RegexOptions.IgnoreCase);

    public Sanitizer(ITextFormatter mainFormatter)
    {
        _mainFormatter = mainFormatter;
    }
    
    public void Format(LogEvent logEvent, TextWriter output)
    {
        StringWriter stringWriter = new StringWriter();
        _mainFormatter.Format(logEvent, stringWriter);
        string input     = stringWriter.ToString();
        string sanitized = sanitiser.Replace(input, "new text");  // <== santise here

        try
        {
            output.Write(sanitized);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "serilog Sanitiser broke"); // <== oh, the irony
        }
    }
}
````

and in my sink config

````cs
internal static string AssemblyName = typeof(App).Assembly.GetName().Name;
 private static string SerilogOutputTemplate = @"[v{Version}] {Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}";
            string LogPath              = AppData + $"\\CADbloke\\logs\\{AssemblyName}\\{AssemblyName}-" +"{Date}.log";
            int?   HowMayLogFilesToKeep = 30;

Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Information()
             // todo:  .ReadFrom.AppSettings() note: log level in app.config so end user can elevate it
#if DEBUG
            .MinimumLevel.Verbose()
#endif
            .Enrich.WithProperty("Version", FileVersion)
            .Enrich.WithExceptionDetails() 
            .WriteTo.Sentry(CrashReporter.SentryDSN, 
                                      release:     FileVersion,
                                      environment: AppUser,
                                      restrictedToMinimumLevel: LogEventLevel.Error,
                                      formatProvider: null,
                                      tags: "logger, Serilog")

            .WriteTo.Async(a => a.RollingFile( pathFormat: LogPath, 
#if !DEBUG
                  formatter : new Sanitizer(new MessageTemplateTextFormatter(SerilogOutputTemplate, CultureInfo.InvariantCulture)),
#endif
                  retainedFileCountLimit: HowMayLogFilesToKeep))
            .Enrich.FromLogContext() 

            .CreateLogger();

Log.Information("{Assembly} just woke up.", AssemblyName);
````

**Comment by Noctis-** [comment]
@CADbloke ROFL ... +1 for "now you have 2 problems" ...

**Comment by nblumhardt** [comment]
For a more rigorous approach that doesn't rely on text formatters, I'm working on an example at:

https://github.com/nblumhardt/serilog-redaction

(Old thread, I know, but still where a lot of inbound links land :-))
