### ISSUE TITLE
Better Properties for MVC?

### ISSUE THREAD

**Issue by kinetiq** [serilog/serilog#940]
Something I run into every time I user Serilog, is that I'm working in MVC, and in each Controller Action, my context inevitably has multiple variables  that I want to log with every single message, that can't be auto-handled by Enrichers as far as I know: 

 - The name of the class and method (limited by PCL status)
 - Usually one or more parameters that the action takes (same) 
 - Maybe something that wasn't an action parameter, like the current logged in user

None of the patterns I'm finding seem to allow me to do this the way I want. To me, the obvious thing to try is grabbing the logger that I injected into the controller and chain ForContext: 

            Log = Log.ForContext<PaymentController>()
                     .ForContext("ContactID", contact.ID)
                     .ForContext("InvoiceID", id);

            Log.Information("Some message...");
  
And I think this used to work, but in my tests, only the final ForContext is active, so only InvoiceID gets logged, at least using the Trace sink. If I could just get this to work, all would be well.

I could probably use an anonymous type for the last two properties, but I still want to log PaymentController. And I would prefer to also auto-log the method that I'm in, but that's not mandatory.

I know I could approach this with a using block, but man, that is super cluttery to me, especially in some of the examples that show multiple nested usings... Why not just have a way to add unlimited properties to a logger instance, and that's it? 

So how are people handling this problem? Am I thinking about this totally wrong? I've done some horrific things to make it work in the past. :)

Thanks for all the hard work, love Serilog, I'm just finally putting this out there because this one area constantly gets me when working in MVC.

**Comment by nblumhardt** [comment]
Hi Brian,

Would an action filter that pushes to `LogContext` be the way to go here?

Cheers!

**Comment by kinetiq** [comment]
Hmm, that might get me part of the way there. I suppose I'm really just wishing I could push multiple properties without having to dispose - but that isn't possible, right?

**Comment by nblumhardt** [comment]
As long as you dispose the outermost pushed property, it'll remove any that are pushed on top of it. Is this what you mean? Cheers!

**Comment by kinetiq** [comment]
Not quite, but I really want to get to the bottom of this, if you will help me.

I suppose my comment is now: when I use Serilog, I am always in some version of this scenario where I have a context that needs to get logged along with my messages, like this:

Log.Information("User {UserID} is trying the thing! {@Context}", userID, context);

try { 
var result = attemptThing();  
} 

...

Log.Information("Oh no! The thing failed! {@Context} {@Result}", context, result);

Only, if I'm being honest, context is not usually an object, it's usually two or three variables, so this can get quite long.

I feel that my code would be cleaner if there wasn't so much repetition, which could be achieved by configuring a logger. However, the only way I know of to do that is by adding multiple levels of using braces, and that would be even worse, if you follow me. 

I have a feeling I am missing a pattern people use in this situation... Surely everyone else deals with this, right?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. You might be missing the opportunity to push the context on in a cross-cutting way, e.g. some kind of middleware or filter?

Another way to frame it: what would your ideal API for this look like? Cheers!

**Comment by kinetiq** [comment]
Great question. I think my ideal API Would be like this.

//Let's say I'm doing a big, complicated chunk of work with contact 5 and invoice 3, so I 
//set my properties to prevent repetition:
Logger.AddProperty("ContactID", 5)
           .AddProperty("InvoiceID", 3);

Logger.Information("Starting invoice sync."); // ContactID and InvoiceID are automatically logged!

... work happens  ... Maybe we are doing this work with a for a bunch of invoices, so eventually I need to update InvoiceID:

Logger.Property("InvoiceID", 4);

Logger.Information("Starting invoice sync."); 

... then there's more work, but something goes wrong:

Logger.Warning("Oh noes! A problem! It was on LineItemID {LineItemID}", lineItemID); //This is just normal use, but ContactID and InvoiceID are still logged.

I suppose I might also want the ability to say:

Logger.ClearProperties(); //Or something very similar.

That's really it. I sense, as I dig into this a bit more, that you've made a lot of decisions around keeping the static Log.Logger clean, and it's funny because I forgot that even existed, since I'm using dependency injection, and I always get my logger through construction injection. 

Final thoughts:
- It would be okay, maybe even desirable, if those Logger.AddProperties() calls had to return a new logger instance by the way.  
 - I tried to make this happen by chaining .ForContext calls, but it seems that only the final ForContext survives.

Thanks for reading this far :)

**Comment by nblumhardt** [comment]
`ForContext` returns a new logger, so you need to chain subsequent `ForContext` calls on it:

```csharp
logger = logger.ForContext("InvoiceID", 4);

logger.Information("Starting invoice sync.");

logger = logger.ForContext("Something else", 5);

// This is just normal use, but ContactID and InvoiceID are still logged.
logger.Warning("Oh noes! A problem! It was on LineItemID {LineItemID}", lineItemID); 
```

You can do the same with `LogContext`:

```csharp
using (LogContext.PushProperty("InvoiceID", 4))
{
    logger.Information("Starting invoice sync.");

    LogContext.PushProperty("Something else", 5);

    Log.Warning("Oh noes! A problem! It was on LineItemID {LineItemID}", lineItemID); 

// Here both properties are popped off.
}
```

**Comment by kinetiq** [comment]
Alright, it seems like I'm good to go. I'm not sure what I was doing before, maybe I didn't have FromLogContext going. I really appreciate the help!

**Comment by nblumhardt** [comment]
No worries, hope it goes well!
