### ISSUE TITLE
Filter.ByExcluding not excluding with Matching.FromSource

### ISSUE THREAD

**Issue by scual** [serilog/serilog#942]
I have the following configuration:

`            Log.Logger = new LoggerConfiguration()

                .MinimumLevel.Debug()

                .WriteTo.LiterateConsole()

                .Filter.ByExcluding(Matching.FromSource("Manager.Utilities"))

                .WriteTo.RollingFile("logs\\Manager-{Date}.txt")

                .CreateLogger();`

then i use Microsoft.Extensions.Logging to get the logger, which is then injected as a dependency:
```
            ILoggerFactory lFactory = new LoggerFactory();

            lFactory.AddSerilog();

            Microsoft.Extensions.Logging.ILogger logger = lFactory.CreateLogger("Manager.App");
```

everything works fine if I filter based on a lambda expression i.e:
`.Filter.ByIncludingOnly(e => e.MessageTemplate.Text.Contains("-")`
however I cannot make it work with Matching.FromSource(), I've also tried different namespace combination, but did not find a way.

an example of how's the namespace's class which I'm trying to exclude:
```

namespace Manager.Utilities
{
    public class SystemMonitoringLogUtility
    {
        public SystemMonitoringLogUtility()
        {
            LogHandlerUtility.Instance.HandleInformation("this is a log from SystemMonitoringLogUtility");
        }
    }
}

```

There's probably something that I'm missing...

**Comment by nblumhardt** [comment]
Serilog/MEL has no way to know which class you're logging from - you need to inject MEL's `ILogger<T>` (where T will be used to compute the "source"), or use Serilog's Log.ForContext<T>() method. HTH!

**Comment by scual** [comment]
Right thanks! - I've created and injected another ILogger<T> and solved the issue.
