### ISSUE TITLE
'Serilog' already has a dependency defined for 'Microsoft.CSharp'.

### ISSUE THREAD

**Issue by ssawyer84** [serilog/serilog#943]
Hi All,

Getting this error: **_'Serilog' already has a dependency defined for 'Microsoft.CSharp'._** 
When executing: **Install-Package Serilog**

I can install an older version like one user suggested:
**Install-Package Serilog -Version 1.5.14**

NuGet Specs:
-------------------------------------------------------------------------------------------------------------------

- NuGet Package Manager version 2.8.60318.667 (most up to date for 2012)
- NuGet Commandline version 3.5

Visual Studio Specs:
-------------------------------------------------------------------------------------------------------------------
Microsoft Visual Studio Professional 2012
Version 11.0.61219.00 Update 5
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2012   04938-004-0034007-02179
Microsoft LightSwitch for Visual Studio 2012

Office Developer Tools   04938-004-0034007-02179
Microsoft Office Developer Tools

Team Explorer for Visual Studio 2012   04938-004-0034007-02179
Microsoft Team Explorer for Visual Studio 2012

Visual Basic 2012   04938-004-0034007-02179
Microsoft Visual Basic 2012

Visual C# 2012   04938-004-0034007-02179
Microsoft Visual C# 2012

Visual C++ 2012   04938-004-0034007-02179
Microsoft Visual C++ 2012

Visual F# 2012   04938-004-0034007-02179
Microsoft Visual F# 2012

Visual Studio 2012 Code Analysis Spell Checker   04938-004-0034007-02179
Microsoft® Visual Studio® 2012 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Visual Studio 2012 SharePoint Developer Tools   04938-004-0034007-02179
Microsoft Visual Studio 2012 SharePoint Developer Tools

.NET Reflector Visual Studio Extension   9.0.1.374
Integrates .NET Reflector into Visual Studio to allow you to seamlessly debug into third-party code and assemblies, even if you don't have the source code for them.

Visit www.reflector.net for more information.

Copyright (c) 2009-2012 Red Gate Software Inc.

ASP.NET and Web Tools   2012.3.41009
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

JetBrains ReSharper Ultimate 2016.3.2    Build 107.0.20170126.120331
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

NuGet Package Manager   2.8.60318.667
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.0
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   11.1.20627.00
Microsoft SQL Server Data Tools

ANTS Profiler Add-in
Visual Studio add-in that integrates ANTS Performance Profiler and ANTS Memory Profiler into Visual Studio to allow you to start profiling from inside Visual Studio.
Visit www.red-gate.com for more information.
Copyright (c) 2009-2010 Red Gate Software Inc.

Git Extensions
Git Extensions is a graphical interface for Git
For more information about Git Extensions, see the Git Extensions website at
http://sourceforge.net/projects/gitextensions/
Copyright © 2008-2014 Henk Westhuis

**Comment by nblumhardt** [comment]
The NuGet version bundled with VS is separate from the cmdline one; see in the above:

> NuGet Package Manager 2.8.60318.667

You'll need to update VS for this one. Cheers!

**Comment by ssawyer84** [comment]
Not sure I'm following when you say update VS for this one. Are you saying I need to update VS itself? or I need to update NuGet? Cause in either scenario I have updated as far as it will let me. Any clarification is much appreciated!

**Comment by nblumhardt** [comment]
Yep, think it is: http://stackoverflow.com/questions/27384885/how-to-upgrade-nuget-with-visual-studio-express-2012

May need to hunt around for a 3.5+ version. HTH!

**Comment by ssawyer84** [comment]
OK, I'm not crazy, see here: https://github.com/NuGet/Home/issues/3131

Apparently it's a known issue and has yet to be resolved for VS 2012. Is the best bet to install an older version for serilog?

**Comment by nblumhardt** [comment]
Ah, that's a shame. I think the _best_ option is to upgrade to a newer VS ;-) ... but other than using the older version, you may be able to install the package manually somehow (or using the CLI tools?)
