### ISSUE TITLE
Support for logging images?

### ISSUE THREAD

**Issue by dbruning** [serilog/serilog#945]
Hi there,
I'm working on an app that involves a lot of image processing. Currently I'm using a logging library that allows me to add images to the log. It's great, but I'd like to switch to Serilog.

I know it seems weird to want to log images, and I know they're big things to log, but in my app it adds an amazing amount of value.

Any suggestions how I could use serilog to log images?

Thanks,
Darren.

**Comment by nblumhardt** [comment]
Hi Darren,

Yes, Serilog can handle this. The main consideration you'll have is where to send the log events - none of the existing sinks will do a very good job of logging images (though the recipe below should keep things sane).

Assumptions:

 * Your images are wrapped up in a type distinct from `byte[]`; example below
 * The image data is immutable once logged

First, the type that carries the image data should be something like:

```csharp
class Image
{
    public string Type { get; private set; }
    public byte[] Data { get; private set; }

    public Image(string type, byte[] data)
    {
        Type = type;
        Data = data;
    }

    public override string ToString() => $"{Type} ({Data.Length} bytes)";
}
```

Then, mark the type as scalar - this means the logging pipeline will pass it through unchanged:

```csharp
Log.Logger = new LoggerConfiguration()
    .Destructure.AsScalar<Image>()
    // ...
```

This will now log your image:

```csharp
var input = new Image(...);
Log.Information("Processed {Input}", image);
```

The existing sinks won't know what to do with an `Image`, so they'll log it out as a string:

```
Processed PNG (12345 bytes)
```

You can then plug in a sink that understands what to do with image properties. Where are you sending the data currently?

**Comment by dbruning** [comment]
Awesome, thanks.

I'm currently sending the data to a proprietary "log viewer" app which comes with the framework I'm using (SmartInspect from Gurock). Any suggestions on an existing Serilog sink that has extension points that I could use to implement image support?

Cheers, Darren.

**Comment by nblumhardt** [comment]
Most of the log storage I'm aware of is strongly text-oriented. You might be better off writing a sink that uploads the images to some kind of shared file storage (a disk drive, SAN, blob store etc.) and then setting things up so that the other non-image-supporting sinks get a hyperlink or key to the data.

E.g.:

```
class Image
{
    public string Type { get; private set; }
    public byte[] Data { get; private set; }
    public string Key { get; } => $"image-{Guid.NewGuid():n}";

    public Image(string type, byte[] data)
    {
        Type = type;
        Data = data;
    }

    public override string ToString() => $"{Key} ({Type}, {Data.Length} bytes)";
}
```

This would show up in normal sinks as:

```
Processed image-0943ea08e8bd408d90d8ee4a3d4a4614 (PNG, 12345 bytes)
```

You'd then write a new sink _just_ concerned with storing the image data:

```csharp
public void Emit(LogEvent logEvent)
{
    var images = logEvent.Properties
        .Select(kv => kv.Value)
        .OfType<ScalarValue>()
        .Select(s => s.Value)
        .OfType<Image>();

    foreach (var img in images)
    {
        // Here, upload the image data somewhere
        Console.WriteLine($"Uploading {img.Key}...");
    }
}
```

**Comment by dbruning** [comment]
Thanks, I will investigate. I might even write a sink that just uses the SmartInspect wire protocol & logs to their viewer.

**Comment by nblumhardt** [comment]
Cool, good luck with it! I'll close this ticket, but please get in touch if you've got more questions.

**Comment by dbruning** [comment]
👍
