### ISSUE TITLE
Wrong configuration found on wiki

### ISSUE THREAD

**Issue by rafaelrbncp** [serilog/serilog#953]
Hello there,

Location:  https://github.com/serilog/serilog/wiki/AppSettings

This configuration:
`<add key="serilog:using" value="Serilog.Sinks.EventLog" />`

Should be:
`<add key="serilog:using:EventLog" value="Serilog.Sinks.EventLog" />`

Please fix :)

**Comment by nblumhardt** [comment]
Thank you Rafael. Actually, both syntaxes should work, as long as there's only one 'using' directive in there. The longer version is definitely more robust though - I've made the change. Thanks!
