### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by stevescc** [serilog/serilog#962]
Hi,

I'm after advice on how to avoid this exception for the Seq client libraries.

> System.MissingMethodException: Method not found

We have a shared logging library that depends on Serilog and Serilog.Sinks.Seq, and we got this error in an app running the latest version of Serilog and had to update from Serilog 2.3 -> 2.4 and Serilog.Sinks.Seq 3.0.1 -> 3.2.

I had the expectation that the dependencies would be in the main backwards compatible. (?)

Aside: I raised [an issue](https://github.com/datalust/seq-apps/issues/29) over in the Seq app repo for the same type of exception. Not sure if there's overlap.

**Comment by nblumhardt** [comment]
Thanks for the report, @stevescc.

I don't think there are too many crazy SemVer violations between those libraries, but it's possible there's one lurking that I am not thinking of.

Do you get any information in the log about the method name, or about the stack trace showing where the exception was thrown?

(Thanks for the other issue in the Seq repository as well. I think they're probably related, let's dig into this one first.)

**Comment by nblumhardt** [comment]
Trying to repro this, I have the following `packages.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Serilog" version="2.4.0" targetFramework="net46" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.File" version="3.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.RollingFile" version="3.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.Seq" version="3.0.1" targetFramework="net46" />
</packages>
```

And the program:

```csharp
static void Main(string[] args)
{
    using (var log = new LoggerConfiguration()
        .WriteTo.Seq("http://localhost:5341")
        .CreateLogger())
    {
        log.Information("Hello, @stevescc");
    }
}
```

Which gives me:

![image](https://cloud.githubusercontent.com/assets/342712/24841256/ada3e66c-1dc3-11e7-9c2d-ed8838818baf.png)

**Comment by stevescc** [comment]
Thanks @nblumhardt 
I've put to together a quick sample project that replicates the error and is similar to our scenario where we have a library (SeqSharedLibrary) that is used by other projects (ConsoleApp1). If you run ConsoleApp1 the method exception occurs on the first line.
https://github.com/stevescc/serilog-seq-issue
Let me know if I can provide anything else.
Thanks
Steve

**Comment by nblumhardt** [comment]
Thanks for the follow-up @stevescc. Unfortunately [this change](https://github.com/serilog/serilog-sinks-seq/pull/39) which went in with [3.1.0](https://github.com/serilog/serilog-sinks-seq/pull/44) introduced this binary, but not source-breaking, change.

Historically, most of the Sink APIs have used SemVer major versions for source-breaking changes, but it's probably time to revisit that to cover the configuration-in-a-library case better.

An update to the same Seq sink version for your library and consumer is the only way to get this to line up as things stand.

**Comment by skomis-mm** [comment]
@nblumhardt , may be in such cases do update `AssemblyVersion`  (to 3.1 in that pr, for example)? Probably for .net core no difference will be noticed, but in case of full .net like this one it can give a hint about possible binary incompatibility while making binding redirection.

**Comment by nblumhardt** [comment]
@skomis-mm sounds like another worthwhile option to consider 👍

**Comment by stevescc** [comment]
Cheers @nblumhardt 
Have updated the Seq sink version in our library to fix.
I haven't quite got my head around the reason (ie "binary, but not source-breaking, change") so if you are aware of documentation that would help me understand it better that would be great.
And is it related to [the other issue we](https://github.com/datalust/seq-apps/issues/29) raised?
