### ISSUE TITLE
New sink for PostgreSQL

### ISSUE THREAD

**Issue by b00ted** [serilog/serilog#970]
Hi!

I've created a new sink, which writes to postgresql table. It would be great if you could add it in the list of sinks in the wiki.
Repo: https://github.com/b00ted/serilog-sinks-postgresql
Nuget: https://www.nuget.org/packages/Serilog.Sinks.PostgreSQL/

**Comment by merbla** [comment]
All Done 👍

**Comment by selvamRK** [comment]
How i can implement this ?
