### ISSUE TITLE
Move some of the great blog posts into docs

### ISSUE THREAD

**Issue by warrenbuckley** [serilog/serilog#971]
After reading through the documentation here on GitHub and come across your blog, you seem to have a wealth of knowledge that may be a little harder to find/discover.

Can I suggest a single source of documentation to make life easier.
A good example that I found out about by going through your blog was the timed operation when used with a `using` code block - https://nblumhardt.com/2016/04/serilog-timings/

I know this is not 'core' functionality but this seems a useful pattern to use or document.

I have yet to go through all the Serilog related posts, but I am sure there is a wealth of knowledge in there that could be put into the documentation.

**Comment by nblumhardt** [comment]
Hey Warren, thanks for the suggestion!

Moving the blog posts into the docs might not have an ideal effect; tracking new content on the wiki isn't as obvious as subscribing to a blog (and also, it's not always clear what's worth doing, and if my blog's PageRank tanks, no one will find new things there :-)) .... But, would and index from the docs to various posts cover this?

If so, can we collect links to articles around the web via this issue thread, and then someone can put them into a prominent doc page on the wiki? Other ideas?

**Comment by nblumhardt** [comment]
Closing for now, but if anyone wants to run with this please jump in! :-) Cheers!
