### ISSUE TITLE
AppSetting level not overriding code for EventLog

### ISSUE THREAD

**Issue by mattkemp** [serilog/serilog#975]
I'm expecting to have some default settings in code that can be overridden by config file changes. 

Here's the example code I'm using:

                Log.Logger = new LoggerConfiguration()
                    .WriteTo.LiterateConsole(outputTemplate: "{Message}{NewLine}{Exception}")
                    .WriteTo.EventLog("myApp", restrictedToMinimumLevel: LogEventLevel.Information)
                    .ReadFrom.AppSettings()
                    .CreateLogger();

then in the appSettings I have this key:

	<add key="serilog:write-to:EventLog.restrictedToMinimumLevel" value="Warning" /> 	

So I expect to only see **Warning** level events in the EventLog. However I get **Information** level.

If I add or change the key 

  	<add key="serilog:minimum-level" value="Warning" />

it does override what was set in code. But the more specific EventLog filtering level key doesn't have any effect.

This question is very similar: <https://stackoverflow.com/questions/24763175/setting-restrictedtominimumlevel-per-sink-in-appsettings>
but they haven't tried to set a level in code as well.

I have tried adding a using as well:

	<add key="serilog:using:EventLog" value="Serilog.Sinks.EventLog" /> 

but it didn't appear to make a difference.

**Comment by nblumhardt** [comment]
Hi Matt, thanks for getting in touch.

App settings and configuration-in-code are separate - to set values in XML, the full configuration for a sink (like EventLog) needs to be done in the XML.

Hope this helps,
Nick

**Comment by mattkemp** [comment]
OK, makes sense.

**Comment by virgoamar** [comment]
I am trying to log in  File as well Eventlog form app.config File seems to be working but not for Eventviewer

<add key="serilog:using:File" value="Serilog.Sinks.File" /> 
..
..
.. some other setting for file which is working and below is for evetnlog all of them are under appSetings 

<add key="serilog:using:EventLog" value="Serilog.Sinks.EventLog" /> 
<add key="serilog:using:EventLog.source" value="POCventLog" /> 

File logging is working but i don;t see any thing in Eventviewer
