### ISSUE TITLE
Best way to work with Azure Functions

### ISSUE THREAD

**Issue by nhwilly** [serilog/serilog#983]
I'm a total noob at this, but I am having some difficulty working with Serilog in an Azure Functions.  I'm just getting started writing some sample things to make sure I understand and that it's going to work for this project.  Here's the simple (awful) code.

    ILogger logger = new LoggerConfiguration()
    .WriteTo.AzureTableStorage(storage, Serilog.Events.LogEventLevel.Verbose, null, "TrustyFunctionsLog")
    .Enrich.FromLogContext()
    .WriteTo.LiterateConsole()
    .WriteTo.Console()
    .WriteTo.Trace()
    .MinimumLevel.Verbose()
    .CreateLogger();

Writing to:
 `AzureTableStorage` is fine.
 `Console` - nothing appears in the console window during local execution, or in the application logging windows in Azure Functions portal.
 `LiterateConsole` - same as above
`Trace` - this seems to work locally to the debug window, but not in production.

I know the AF docs suggest not writing to the console, but I was hoping to see it during development.  I know I can abstract it away to write in multiple places myself, but I have feeling that I'm doing something really wrong...

I know I'm missing something, I just don't know what.

**Comment by merbla** [comment]
Hi @nhwilly,

I have recently been looking at this area as well.  I believe what you are looking for is to write to the `Microsoft.Azure.WebJobs.Script.InterceptingTraceWriter`.  Details are over at [Microsoft.Azure.WebJobs.Script.InterceptingTraceWriter](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Diagnostics/InterceptingTraceWriter.cs).  This is a class that I do not believe a sink currently exists for.

I have started playing with some ideas [here](https://github.com/merbla/serilog-sinks-azure-functions) but nothing functioning.

**Comment by nhwilly** [comment]
I saw your repo, but there wasn't anything in it.  Time constraints for me are such that I can't start another project on top of what I'm doing.  Wish I had the time to help out...

GL with it.

**Comment by merbla** [comment]
@nhwilly sorry, it can't be of much help in the short term.  Closing this out and we can pick things up at the other repo.

**Comment by nblumhardt** [comment]
@nhwilly one option you might consider is to write to a network-based viewer (Seq, Splunk, Elasticsearch, ...) when doing local development. You can spin up Seq on localhost and get a pretty good "console-like" experience via the Seq sink.

**Comment by nhwilly** [comment]
@nblumhardt   Thanks, it's working great.  I have some methods that I am also using on my Asp.Net site that I wanted to use for my new Azure Functions.  They are looking for a `Microsoft.Extensions.Logging` instance and I wanted to stick with an Application Insights all MS solution.  Looks like I'll have to replace all that stuff with Serilog.

**Comment by joseclament** [comment]
@nhwilly Did you manage to get the Microsoft.Extensions.Logging working along with Serilog in your azure function apps? If so please provide the code snipset
