### ISSUE TITLE
Message template syntax improvement

### ISSUE THREAD

**Issue by vnau** [serilog/serilog#984]
Current message template syntax of the log methods have two disadvantages in creating human readable log messages:

First, named properies should be specified in the log method's parameters in the same order as it mentioned in the message template. This could be unacceptable if message template should be localized and words order may vary in different languages.

Another disadvantage is inability to use context properties in the log methods message template.

I do not create separate issues for those two disadvantages as i believe it could be solved with a single syntax improvement.

My suggestion is to combine numeric and named properties syntax so property name may be prefixed with some delimiter symbol ('#' or any other) and parameter ordering number.
In case delimiter is present, but no ordering number specified then context property in log message would be substituted.

Sample of using supposed syntax:
```javascript
    var stageLog = Log.ForContext("Stage", stage);
    stageLog.Warning("Disk quota {1#Quota} MB exceeded by {0#User} at stage {#Stage}.", user, quota);
```
This syntax also would be backward compatible with previous versions.

**Comment by nblumhardt** [comment]
Thank you for the suggestion! Nice syntax design 👍 

I don't think this is a change we'd make at this point - the improvements wouldn't justify the substantial effort involved in rolling this kind of change out through the ecosystem, and would make Serilog diverge from the other message template implementations already out there.

In the most common case the current syntax is also more succinct, so the number of scenarios it would improve are fairly small by comparison.

Thanks again for sharing the idea though - definitely interesting to consider.
