### ISSUE TITLE
Question: How to use this in UWP?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [serilog/serilog#985]
What is the recommended sinks to use with UWP app. I want to try serilog for my UWP apps. Tried file, literate, rollingfile without success. I cant find the logs file. There are no console in UWP. Tried log4net but log4net sinks doesnt work on UWP.

what sinks do you use on UWP?

**Comment by nblumhardt** [comment]
Thanks for the question! I see via the Gitter channel you've gone with Seq; I think any of the network-based sinks like that will be a good fit.

**Comment by syaifulnizamyahya** [comment]
Yes. I have success using UWP Serilog with Seq. Thanks.

**Comment by somildutt** [comment]
Hello 

In my case, Log4net and serilog are not working for logging information in text file in local drive.
Although Metro log are working.

can anyone advise how to use serilog ?

Rgds
Somil

**Comment by Fieel** [comment]
@syaifulnizamyahya sharing more info would be greatly appreciated, this is the main result that comes up when searching for "UWP serilog" after all.

So, the solution is to not use Serilog?

**Comment by nblumhardt** [comment]
@Fieel Hi!

I guess the solution here is for someone doing UWP development to dig in and figure out how to either get the `File` sink working, or perhaps hook up _Serilog.Sinks.TextWriter_ to a `StreamWriter` over a `FileStream` opened appropriately on UWP.

Serilog's sinks are generally quite simple - e.g. [this](https://github.com/serilog/serilog-sinks-textwriter/blob/dev/src/Serilog.Sinks.TextWriter/Sinks/TextWriter/TextWriterSink.cs#L23) is a complete sink implementation in a few lines of code - hooking this up to a file on UWP should be fairly straightforward for someone with knowledge of the platform and a test machine.

Unfortunately I don't do any UWP development, and as far as I can tell, it's not a common skill among the current Serilog contributors, so having someone with UWP skills contribute, here, would be very valuable.

Cheers,
Nick

**Comment by Fieel** [comment]
@nblumhardt Hello and thanks for the reply!

I actually got a very minimal implementation of Serilog working on my UWP app and it's pretty damn simple to set up, here's how I did it:

1. Installed Serilog and Serilog.Sinks.File nugget packages

2. Wrote a custom Class called Logger with a static method:
```
    public class Logger
    {
        public static void ConfigureLogger()
        {

            string logFilePath = Path.Combine(Path.Combine(ApplicationData.Current.LocalFolder.Path, "logs/log.txt"));

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.File(logFilePath)
                .CreateLogger();

            Log.Information("Serilog started!");
        }
    }
```

3. Logger initialized using the previously created static method in App.xaml.cs:

```
        public App()
        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;
            Logger.ConfigureLogger();
        }
```



As you can see I'm saving the log file in the LocalFolder of the UWP app and I can find it in the logs subfolder (es. C:\Users\\*username*\AppData\Local\Packages\\*appname*\LocalState\logs).

And that's it, i can easily call Log.Whatever("message") in my app.

**Comment by nblumhardt** [comment]
Great! Glad you were able to figure it out, @Fieel 👍  ... It sounds like, perhaps, the log file path could be the critical missing piece; hopefully this will unblock others who come across this issue 🏆

**Comment by helloserve** [comment]
Just to take this to the last mile. I added dependency injection to my UWP. It was created using the Windows Template Studio extension, from that I added into `ActivationServices,cs`

```
        private ServiceCollection _services;
        public static IServiceProvider ServiceProvider { get; private set; }
```

And then changed `InitializeAsync()` to include

```
        private async Task InitializeAsync()
        {
            ...
            _services = new ServiceCollection();

            _services.AddLogging(loggingBuilder =>
                loggingBuilder.AddSerilog(dispose: true));

            _services.AddServices();
            _services.AddRepositories();
            _services.AddContext();

            ServiceProvider = _services.BuildServiceProvider();
        }
```

Now you're set to inject `ILogger<TService>` into any constructor you need.
