### ISSUE TITLE
LogContext.get_Enrichers throws Remoting Exception on Serilog 2.3

### ISSUE THREAD

**Issue by noahsyed** [serilog/serilog#987]
We recently upgraded to Serilog 2.3 but we are getting random remoting errors for LogContext.

The issue was supposed to be fixed as part of #840 but it doesn't seem to be, any ideas which Serilog version has this fixed for .Net 4.5?

`"ClassName": "System.Runtime.Remoting.RemotingException",
"Message": "Object '/3e20fcfd_b1fb_4d47_b422_244ebdc7fba2/suzebhbq1+ggvvz7iqwdwmgb_49282.rem' has been disconnected or does not exist at the server.",
"RemoteStackTraceString": " 
at System.Runtime.Remoting.ObjectHandle.Unwrap()\r\n   
at Serilog.Context.LogContext.get_Enrichers()\r\n   
at Serilog.Context.LogContext.PushProperty(String name, Object value, Boolean destructureObjects)`

**Comment by nblumhardt** [comment]
Hi, thanks for the report. I haven't seen any reports of this for a long time (since the aforementioned PR was released), but it's quite possible the majority of work is now being done on .NET 4.6+, where `AsyncLocal<>` is used and thus remoting issues are avoided.

There's a discussion tracing the most recent attempt to fix the problem in: https://github.com/serilog/serilog/issues/835 - can you spot any issues, or assumptions that wouldn't apply in your environment?

Best regards,
Nick

**Comment by noahsyed** [comment]
Thanks Nick.
I did looked at the thread and see that some points apply to our environment example comment from Yallie about calls fail during a cross-app domain call. However we don’t have a consistent repro of the issue like some other folks may be reporting. So am wondering is the remoting issue related to a Serilog version or even the latest 2.5 version has this error?

**Comment by nblumhardt** [comment]
Hi @noahsyed - thanks for the follow-up. At this stage, I think we'll only make progress on this with a repro, since it's so environment/version/application-specific. How are things going? Do you think it's likely you can create a minimal test case/app to reproduce this?

**Comment by skomis-mm** [comment]
Here the complete minimal example:
```csharp
using System;
using System.Runtime.Remoting.Lifetime;
using System.Threading;

using Serilog;
using Serilog.Context;
using Serilog.Core;
using Serilog.Events;

namespace SerilogIssue
{
    class Program
    {
        static Program()
        {
            LifetimeServices.LeaseTime = TimeSpan.FromMilliseconds(200);
            LifetimeServices.LeaseManagerPollTime = TimeSpan.FromMilliseconds(200);
        }

        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.FirstChanceException += (_, e) => Console.WriteLine("First chance exception: " + e.Exception.Message);

            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .AuditTo.Sink<ConsoleSink>()
                .CreateLogger();

            var remote = AppDomain.CreateDomain("Remote", null, AppDomain.CurrentDomain.SetupInformation);

            using (LogContext.PushProperty("Prop", 42))
            {
                remote.DoCallBack(CallFromRemote);

                // throws exception and swallows despite `Audit` setting;
                // after prints unenriched template 'Prop = {Prop}'
                Log.Information("Prop = {Prop}");
            }

            Console.ReadLine();            
        }

        static void CallFromRemote()
        {
            // work
            Thread.Sleep(400);
        }
    }

    class ConsoleSink : ILogEventSink
    {
        public void Emit(LogEvent logEvent) => logEvent.RenderMessage(Console.Out);
    }
}
```

**Comment by noahsyed** [comment]
+ Adrian and Jiang

**Comment by noahsyed** [comment]
Migrating to .NET 4.6 resolved the issue for us, thanks for the help!
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
