### ISSUE TITLE
ForContext is not keeping Context Value

### ISSUE THREAD

**Issue by pathakajay** [serilog/serilog#989]
i am using ForContext Method on WCF Service to set the context values. 
Serilog is writing context values in database for some iterations and for some it is not writing any thing
i am trying to set two context values 
![2017-06-22_15-08-46](https://user-images.githubusercontent.com/18146521/27427522-eeb17a0c-575c-11e7-965c-f6f73a797c33.jpg)

**Comment by nblumhardt** [comment]
Hi! Which `ForContext` method do you mean? `LogContext` or `ILogger`? You might need to paste in a code sample. Cheers :-)

**Comment by nblumhardt** [comment]
Hi again! Closing this for now, until we have some more details to go on. Please re-open if you're still having trouble with this, thanks.
