### ISSUE TITLE
Accessing logger instance from separate threads

### ISSUE THREAD

**Issue by johnernaut** [serilog/serilog#990]
I'm instantiating an instance of `Log.Logger` inside of a class, as well as an instance of `System.Threading.Timer`.  Here's an example

```c#
public class CGTaskRunner
 {
        private TimerState TimerState;
        private Timer TaskTimer;
        private PollingService pollingService;

        public void MepAutoRunStart()
        {
            var logPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            Log.Logger= new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.RollingFile(Path.Combine(logPath, @"cgtr_logs\cgtrlog-{Date}.txt"), shared: true)
                .CreateLogger();

                TimerState = new TimerState();
                TaskTimer = new Timer(TimerDelegate, TimerState, 1000, 3000);
                TimerState.TimerRef = TaskTimer;
        }

        private void TimerDelegate(object state)
        {
            var timerState = (TimerState)state;
            Log.Logger.Debug("Blah"); // THIS logs correctly.
            if (timerState.TimerCancelled)
            {
                timerState.TimerRef.Dispose();
            }

            pollingService.StartPolling(Log.Logger); // the logger instance called from inside this method throws an exception
        }
}
```

The instance of the `Log.Logger` I added logs fine in the `TimerDelegate` ticks, but the instance of the `Log.Logger` that I pass into the method from within the `TimerDelegate` throws this: `Exception thrown: 'System.ObjectDisposedException' in Serilog.Sinks.RollingFile.dll` (although it still seems to log properly). My only guess is that this is a threading issue, but I'm not quite sure how to debug it.  Any ideas would be appreciated.  Thanks!

**Comment by johnernaut** [comment]
Ok, the issue was that I was actually calling `Close and Flush` on the logger instance before all threads were finished - completely my bad.  Thanks!

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up, John 👍
