### ISSUE TITLE
Release build error on UWP: Cannot generate zero initialization code for type 'System.String'.

### ISSUE THREAD

**Issue by JasperE84** [serilog/serilog#993]
After having upgraded to Serilog 2.5.0, my release builds (with .net optimalization) fail with the following error (VS2017).

3>C:\Users\myuser\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: Internal compiler error: Cannot generate zero initialization code for type 'System.String'.

After downgrading to 2.4.0 everything is fine again.

**Comment by skomis-mm** [comment]
.net native toolchain doesn't like [this](https://github.com/serilog/serilog/blob/dev/src/Serilog/Rendering/Padding.cs#L22) line. Not sure what's wrong with it according to the [official guide](https://docs.microsoft.com/en-us/dotnet/framework/net-native/migrating-your-windows-store-app-to-net-native), but seems like a compiler issue. I wonder if CI can run this toolchain as a part of the build process.

**Comment by nblumhardt** [comment]
We've held off adding a specific UWP target to the build, because of the slightly annoying build-time tooling dependency, but if these kinds of issues are present it seems worthwhile 👍 

I'm not sure what kind of workaround might get us past the compiler bug in the meantime. I don't suppose there are any VS updates/tooling patches available for you to install @JasperE84 ?

**Comment by JasperE84** [comment]
I'm using the latest tooling updates (microsoft.net.native.compiler v1.6.2)

**Comment by nblumhardt** [comment]
@JasperE84 https://www.nuget.org/packages/Serilog/2.5.1-dev-00869 includes the workaround from @skomis-mm - any chance you can test this package version and confirm the issue fixed? Thanks!

**Comment by JasperE84** [comment]
@nblumhardt  I can confirm a succesful build with toolchain enabled. Thanks @nblumhardt  & @skomis-mm !

**Comment by MichalStrehovsky** [comment]
.NET Native dev here - yes, this was a compiler issue. Great job root causing it to a single line! Coincidentally, we just fixed this very recently and the fix will ship with the next major release of .NET Native.

Here's another possible workaround: https://github.com/dotnet/corefx/blob/32c4013a5d750c1c6a5b240d37a689991a479097/src/System.Private.Xml/src/System/Xml/Core/XmlTextWriter.cs#L145

**Comment by nblumhardt** [comment]
Great, thanks for the confirmation @MichalStrehovsky 👍

**Comment by bidasknakayama** [comment]
When will you release this fix as major update ?

**Comment by MichalStrehovsky** [comment]
> When will you release this fix as major update ?

The fix is included in [.NET Native 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/).
