### ISSUE TITLE
StructureMap sample code

### ISSUE THREAD

**Issue by jsodeman** [serilog/serilog#995]
I'm having a hard time getting Serilog working with StructureMap. Does anyone have a snippet of the correct way to register Serilog?

**Comment by joelweiss** [comment]
This is how I use it. (Based on [this](https://github.com/structuremap/structuremap/issues/459#issuecomment-261840837) comment)
```csharp
using System;
using System.Linq;
using System.Reflection;
using Serilog;
using StructureMap;
using StructureMap.Pipeline;

namespace PC.Services.Logging
{
    public class LoggingRegistry : Registry
    {
        public LoggingRegistry()
        {
            For<ILogger>().Use(() => Configuration.Logger);
            Policies.Add<SerilogPolicy>();
        }

        public class SerilogPolicy : ConfiguredInstancePolicy
        {
            protected override void apply(Type pluginType, IConfiguredInstance instance)
            {
                ParameterInfo parameter = instance.Constructor?.GetParameters().Where(x => x.ParameterType == typeof(ILogger)).FirstOrDefault();
                if (parameter != null)
                {
                    ILogger logger = Configuration.Logger.ForContext(pluginType);
                    instance.Dependencies.AddForConstructorParameter(parameter, logger);
                }
                else
                {
                    PropertyInfo property = instance.SettableProperties().Where(x => x.PropertyType == typeof(ILogger)).FirstOrDefault();
                    if (property != null)
                    {
                        ILogger logger = Configuration.Logger.ForContext(pluginType);
                        instance.Dependencies.AddForProperty(property, logger);
                    }
                }
            }
        }
    }
}
```

Note: I have a `static Configuration.Logger` with a Serilog logger configured.
And make sure to add the `SerilogRegistry` to your container.

**Comment by jsodeman** [comment]
Thanks, I'd found the linked policy. The part I was missing was
`For<ILogger>().Use(() => Configuration.Logger);`

I was trying to do something more complex.

**Comment by asalaheldin** [comment]
> This is how I use it. (Based on [this](https://github.com/structuremap/structuremap/issues/459#issuecomment-261840837) comment)
> 
> ```cs
> using System;
> using System.Linq;
> using System.Reflection;
> using Serilog;
> using StructureMap;
> using StructureMap.Pipeline;
> 
> namespace Services.Logging
> {
>     public class LoggingRegistry : Registry
>     {
>         public LoggingRegistry()
>         {
>             For<ILogger>().Use(() => Configuration.Logger);
>             Policies.Add<SerilogPolicy>();
>         }
> 
>         public class SerilogPolicy : ConfiguredInstancePolicy
>         {
>             protected override void apply(Type pluginType, IConfiguredInstance instance)
>             {
>                 ParameterInfo parameter = instance.Constructor?.GetParameters().Where(x => x.ParameterType == typeof(ILogger)).FirstOrDefault();
>                 if (parameter != null)
>                 {
>                     ILogger logger = Configuration.Logger.ForContext(pluginType);
>                     instance.Dependencies.AddForConstructorParameter(parameter, logger);
>                 }
>                 else
>                 {
>                     PropertyInfo property = instance.SettableProperties().Where(x => x.PropertyType == typeof(ILogger)).FirstOrDefault();
>                     if (property != null)
>                     {
>                         ILogger logger = Configuration.Logger.ForContext(pluginType);
>                         instance.Dependencies.AddForProperty(property, logger);
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> Note: I have a `static Configuration.Logger` with a Serilog logger configured.
> And make sure to add the `SerilogRegistry` to your container.

Thanks a lot for your answer, but what does the static Configuration.Logger contains in your case, and how can I configure a File Sink in this case?

**Comment by joelweiss** [comment]
@asalaheldin 

Something like this
```csharp
using Serilog;

public static class Configuration
{
	static Configuration()
	{
		Logger = new LoggerConfiguration()
			.WriteTo.File("log.txt")
			.CreateLogger();
	}

	public static ILogger Logger { get; }
}
```

See [here](https://github.com/serilog/serilog-sinks-file#serilogsinksfile----) how to configure the File logger.

**Comment by asalaheldin** [comment]
@joelweiss Thanks a lot. This is very helpful
