### ISSUE TITLE
Serilog.Settings.AppSettings doesn't support .NET Standard

### ISSUE THREAD

**Issue by Leon99** [serilog/serilog#997]
Any alternatives/plans to add support?

**Comment by nblumhardt** [comment]
Hi Leon! _System.Configuration_ isn't present in .NET Standard (not sure about 2.0), so there are no plans to support this currently. https://github.com/serilog/serilog-settings-configuration is the alternative. HTH!

**Comment by Leon99** [comment]
Thanks a lot Nicholas, I'll check it out.

**Comment by shrknt35** [comment]
What about now, now that alternative for <a href="https://www.nuget.org/packages/System.Configuration.ConfigurationManager/4.4.1">System.ConfigurationManager</a> is available for net standard?

**Comment by nblumhardt** [comment]
@shrknt35 thanks for the nudge; seems reasonable to target this, now 👍

**Comment by nblumhardt** [comment]
@nvvarsha2009 this should be through the build pipeline shortly. Thanks for the nudge!

**Comment by shrknt35** [comment]
@nvvarsha2009 I see that the version 2.2.1-dev-00052 is in nuget from last month. are there any plans of creating a release build for app settings?

**Comment by andymartin** [comment]
Version 2.2.1-dev-00056 prerelease is now in nuget. Is a release package coming soon?

**Comment by nblumhardt** [comment]
Thanks all, looks like the intended 2.2.0 was not correctly published. https://github.com/serilog/serilog-settings-appsettings/pull/33 on its way now.
