### ISSUE TITLE
Get data back out of LogContext

### ISSUE THREAD

**Issue by snboisen** [serilog/serilog#998]
My main use case for LogContext is to place the request correlation id in the context, so it will be available to track all events across the system made on behalf of a specific request.

I have created a simple Web API message handler that places the request ID in the context right at the start of handling the request. So far so good.

The challenge is that the system extends beyond the web service to an Azure webjob which is sent tasks to perform based on the request. I want to include the request correlation ID in these tasks, so that I can track actions taken in that component in response to specific requests as well.

But LogContext does not like to hand out the data it is keeping for me. So now I have to create my own AsyncLocal or similar to store this ID in, so I will have it when I need it. This is silly, since LogContext already stores this data.

I would like to propose a way to extract the data stored in the LogContext in an easy way. It does not have to be particularly performant. Something similar to the way you currently [enrich LogEvents](https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs#L164) would be fine.

This would prevent needless double bookkeeping.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. The architecture of `LogContext` doesn't really support this in a first-class way; I think the redundant `AsyncLocal` is about the best available option.

It is possible to ~~hack~~extract information from `LogContext`, but perf won't be great:

```csharp
class CollectorSink : ILogEventSink
{
    public LogEvent LastEvent {get; set;}
    public void Emit(LogEvent evt) { Event = evt; }
}

var collector = new CollectorSink();
var temporaryLogger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .WriteTo.Sink(collector);
temporaryLogger.Information("Hello");

foreach (var p in collector.LastEvent.Properties)
{
   // etc.
}
```
