### ISSUE TITLE
Serilog.ColoredConsoleLoggerConfigurationExtensions.ColoredConsole Missing Method

### ISSUE THREAD

**Issue by Tochemey** [serilog/serilog#999]
Hello
I am using Serilog and the Console Sink and whenever I try to run the application I got the following exception:
Serilog.ColoredConsoleLoggerConfigurationExtensions.ColoredConsole missing method

I am running it from macOs Sierra using mono 5.

Please assist

**Comment by merbla** [comment]
Hi @Tochemey,

This issue may be better living over at the sink repository, https://github.com/serilog/serilog-sinks-console.  We try to keep the issues here focused on Serilog core.

Feel free to create a [new](https://github.com/serilog/serilog-sinks-console/issues/new) issue there.

**Comment by merbla** [comment]
@Tochemey also, what package do you have for the sink?

**Comment by Tochemey** [comment]
The package I have installed are Sinks.Console and Sinks.Literale and AppSettings one.

**Comment by Tochemey** [comment]
The issue was due to package versioning. Thanks for the support
